- src/streamlink/plugins/zattoo.py
Closes #3197 
Thanks to @DESK-coder for his proposal
> plugins.zattoo: fix login error

- docs/plugin_matrix.rst
- src/streamlink/plugins/cdnbg.py
- tests/plugins/test_cdnbg.py
- remove: mmtvmusic.com
- remove: chernomore.bg
- update: bnt.bg
~~I suspect I'll need to push more changes due to warnings from LGTM...~~  Apparently not...
closes #3201
> plugins.cdnbg: update url_re, plugin test, plugin matrix

- docs/plugin_matrix.rst
- src/streamlink/plugins/tv999.py
- tests/plugins/test_tv999.py
> plugins.tv999: new plugin for http://tv999.bg/live.html

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Fixes #3206
Since I want to refactor the entire plugin at some point anyway, I decided to add validation schemas for the metadata API responses instead of just adding a simple `is not None` check. Also added tests with mocked API responses.
I don't know if the videos API response can be empty, similar to the "channel from stream" response, but better safe than sorry.
> plugins.twitch: fix metadata API response handling

- docs/plugin_matrix.rst
- src/streamlink/plugins/livestream.py
- tests/plugins/test_livestream.py
closes https://github.com/streamlink/streamlink/issues/3240
> plugins.livestream: remove AkamaiHDStream, use only secure HLSStream

- docs/developing.rst
~~This adds what I was talking about in: https://github.com/streamlink/streamlink/pull/3245#issuecomment-707386309~~
Edit: I made this a draft PR, as there may well be things that should be changed...
> docs: add plugin addition/removal infos

- src/streamlink/plugins/btsports.py
- src/streamlink/plugins/cnews.py
- src/streamlink/plugins/ellobo.py
- src/streamlink/plugins/kingkong.py
- src/streamlink/plugins/nbcnews.py
- src/streamlink/plugins/skai.py
> plugins: mark some plugins as broken

- src/streamlink/plugins/youtube.py
> plugins.youtube: fix live playback

- src/streamlink/plugins/facebook.py
Fixes https://github.com/streamlink/streamlink/issues/3271
> plugins.facebook: remove User-Agent

- docs/thirdparty.rst
A small PR that updates the screenshot and supported OS list for my third-party application, wtwitch.
> docs: update wtwitch in thirdparty list

- src/streamlink/plugins/nbcnews.py
- add JSON data schema
- add token schema
- add JSON post data and token request
> plugins.nbcnews: fix video ID search, add schemas

- src/streamlink/plugin/api/useragents.py
- src/streamlink/plugins/bilibili.py
- src/streamlink/plugins/btsports.py
- src/streamlink/plugins/live_russia_tv.py
- src/streamlink/plugins/ltv_lsm_lv.py
- src/streamlink/plugins/metube.py
- src/streamlink/plugins/mitele.py
- src/streamlink/plugins/mjunoon.py
- src/streamlink/plugins/okru.py
- src/streamlink/plugins/oneplusone.py
- src/streamlink/plugins/pixiv.py
- src/streamlink/plugins/radiko.py
- src/streamlink/plugins/reuters.py
- src/streamlink/plugins/sbscokr.py
- src/streamlink/plugins/showroom.py
- src/streamlink/plugins/sportal.py
- src/streamlink/plugins/streamme.py
- src/streamlink/plugins/streann.py
- src/streamlink/plugins/stv.py
- src/streamlink/plugins/teleclubzoom.py
- src/streamlink/plugins/tlctr.py
- src/streamlink/plugins/tvp.py
- src/streamlink/plugins/tvrplus.py
- src/streamlink/plugins/vinhlongtv.py
- src/streamlink/plugins/vtvgo.py
- src/streamlink/plugins/willax.py
- src/streamlink/plugins/zengatv.py
- update CHROME + FIREFOX User-Agent
- Remove FIREFOX User-Agent imports, because it is the default User-Agent of Streamlink https://github.com/streamlink/streamlink/pull/2795
> plugin.api.useragents: update User-Agent and removed FIREFOX User-Agent imports

- src/streamlink/plugins/bfmtv.py
- update matching for account/video IDs
- update matching for embed to find Dailymotion ID
- use Dailymotion plugin func for stream data retrieval
closes #3288
> plugins.bfmtv: fix ID & embed re, use Dailymotion

- src/streamlink/plugins/abweb.py
- tests/plugins/test_abweb.py
closes https://github.com/streamlink/streamlink/issues/3281
> plugins.abweb: fixed login issues

- src/streamlink/plugins/vlive.py
- tests/plugins/test_vlive.py
closes #3314 
The site was completely revised recently and url format was changed.
But old format still exists, so I added support for both formats.
> plugins.vlive: fix URL regex and plugin

- src/streamlink/plugins/cdnbg.py
Currently `plugins.cdnbg` has a bug where `urlparse.scheme` is being passed as arg to `urlparse`  (used in  `update_schema` ), but `urlparse` treats it as path (as its simply the protocol name, not a URL). Thus for a URL without a specified protocol, the script fails.
Changes:
- Remove a redundant `if` statement as `update_scheme` handles both cases (with/without scheme)
- Remove a redundant `if` statement as `iframe_url` is always defined
- Use `html.unescape` to unescape HTML-encoded strings (should me more of a robust)
- More robust check (via parsing), whether the supplied URL is already a target URL
> plugins.cdnbg: simplify and fix iframes without schema

- src/streamlink/plugin/api/useragents.py
- update all User-Agent's
- use newer User-Agent's for some duplicates,
for backwards compatibility they are not removed
> plugin.api.useragents: update User-Agent's

- src/streamlink/plugins/mitele.py
The API changed a bit and required a few updates. This should work for all the channels except the one premium channel which requires a subscription and uses DRM so cannot be supported. 
fixes #3336
> plugins.mitele: update plugin to support new website APIs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/plugin_issue.md
- .github/ISSUE_TEMPLATE/plugin_request.md
Also changed the checkbox comment to make it a bit more clear what needs to be done.
> chore: add dev version checkbox to issue templates

- src/streamlink/plugins/pixiv.py
@hatabbich 
@t374
@hat3l0v3
could you test it
closes https://github.com/streamlink/streamlink/issues/3359
> plugins.pixiv: set headers for stream data, fixed login issue

- src/streamlink/plugins/twitch.py
See https://github.com/streamlink/streamlink/issues/3210
> plugins.twitch: fix ads

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
closes https://github.com/streamlink/streamlink/issues/3257
> plugins.twitch: fix --twitch-disable-reruns

- src/streamlink/plugins/pluto.py
Ref https://github.com/streamlink/streamlink/pull/3363#issuecomment-736168003
> plugins.pluto: ignore invalid channels

- src/streamlink/plugins/filmon.py
In my log during a recent stream with the filmon plugin I got:
```
Exception in thread Thread-FilmOnHLSStreamWorker:
File "/home/mythtv-iptv-setup/utils/streamlink/lib/python3.7/site-packages/streamlink/utils/__init__.py", line 53, in parse_json
json_data = json.loads(data)
File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred: …
```
> plugins.filmon: mitigate for non-JSON data response

- setup.py
> Update author email to shared email

- tests/test_cmdline.py
This fixes the issues with `tests/test_cmdline{,_title}.py` when running those test files independently by properly mocking the `subprocess` method calls and the global `streamlink_cli.main.streamlink` variable, so that there are no side effects from other test cases.
See https://github.com/streamlink/streamlink/pull/3390#issuecomment-739636791
```
$ pytest -q --tb=no tests/test_cmdline.py 
.....ssssss                                                                                                                              [100%]
5 passed, 6 skipped in 0.51s
$ pytest -q --tb=no tests/test_cmdline_title.py 
......ssssssss                                                                                                                           [100%]
6 passed, 8 skipped in 0.41s
```
---- …
> tests: fix test_cmdline{,_title}

- src/streamlink/plugin/api/useragents.py
> plugin.api.useragents: update User-Agent

- src/streamlink/plugins/schoolism.py
- tests/plugins/test_schoolism.py
- credit: @tianwang95
closes #2950
> plugins.schoolism: fix and test for colon in title

- CHANGELOG.md
Closes #3235 
I know that there are still a few PRs open and that there are probably a few more changes which need to get squeezed in, but let's try to prepare the changelog for 2.0.0. I will update and rebase this PR when new changes get merged into master.
The changelog is kept as short as possible intentionally because there are so many changes. That's why not every plugin fix/rewrite is explicitly mentioned. It's also possible that I've missed some important changes, so please go ahead and check.
If there's more to add, like short notes on breaking changes for example, please make a suggestion.
> release: 2.0.0

- src/streamlink/plugin/api/http_session.py
The `HTTPAdapterWithReadTimeout` is unneeded and [dead code](https://codecov.io/gh/streamlink/streamlink/src/master/src/streamlink/plugin/api/http_session.py), as [`requests>=2.21.0,<3.0`](https://github.com/streamlink/streamlink/blob/7b74974c4ab59ad49182da81a752cfe436ef961b/setup.py#L13) is the dependency version range defined in Streamlink's setup.py.
Added in 5ebf5af0933f899ce7b7c3e3f73378ce9a50348e 7 years ago as a workaround.
> http_session: remove HTTPAdapterWithReadTimeout

- docs/plugin_matrix.rst
- src/streamlink/plugins/dogus.py
- tests/plugins/test_dogus.py
- ntvspor.net/canli-yayin
closes #3476
> plugins.dogus: remove channel and update test

- src/streamlink/plugins/turkuvaz.py
- tests/plugins/test_turkuvaz.py
- atv.com.tr/a2tv/canli-yayin
- ahaber.com.tr/video/canli-yayin
closes  #3475
> plugins.turkuvaz: add channels and URL tests

- docs/install.rst
I just noticed the URL pointing to the Fedora repo needed to be updated.
> docs: update URL to Fedora repo

- src/streamlink/plugins/bloomberg.py
Fixes #3513
----
Looks like the whole JS webpack bundle stuff can be ignored and removed from the plugin as there's a JSON request which can be made instead to get the list of live streams.
I've also refactored the whole plugin, removed unneeded stuff and simplified the schemas.
Also removed the `contentLoc` field from the VOD schema, as it's just duplicate content via a progressive HTTPStream as mp4 container in a low video bitrate, and it's available via HLS anyway (AFAICT)...
Overall, the HDS / HLS / HTTP distinction could probably also be removed in favor of just HLS. I haven't seen anything else, but I've kept it for now.
----
**Live (US)**
```
$ streamlink -l debug 'https://www.bloomberg.com/live/us'
[cli][debug] OS:         Linux-5.11.0-rc5-1-git-x86_64-with-glibc2.32
[cli][debug] …
```
> plugins.bloomberg: fix and refactor plugin

- src/streamlink/plugins/oneplusone.py
> plugins.oneplusone: site changes: fix iframe url pattern

- src/streamlink/plugins/stadium.py
- hls streams have discontinuities in commercial breaks
- with the option `--player-passthrough hls` the streams can be played with a compatible player
> plugins.stadium: adaptions for new player api

- src/streamlink/plugins/afreeca.py
gs_cdn --> gs_cdn_pc_web
flash  --> common
the api returns `gs_cdn` but it doesn't work with every region.
use `gs_cdn_pc_web` instead.
closes https://github.com/streamlink/streamlink/issues/3538
> plugins.afreeca: use 'gs_cdn_pc_web' and 'common'

- docs/plugin_matrix.rst
- src/streamlink/plugins/nimotv.py
- tests/plugins/test_nimotv.py
> plugins.nimotv: new plugin

- src/streamlink/plugins/tvtoya.py
- update url_re for www. and literal dot escaping
- remove unnecessary update_scheme()
> plugins.tvtoya: minor fixes

- .codecov.yml
https://github.com/streamlink/streamlink/pull/3547#issuecomment-775383616
This will fail, since #3547 hasn't been merged yet. Will rebase once done.
> ci.codecov: 100% tests target, add patch status

- docs/install.rst
Forgot to remove this in #3535
> docs: clean up package maintainers list

- docs/plugin_matrix.rst
- src/streamlink/plugins/mjunoon.py
- tests/plugins/test_mjunoon.py
This was broken, as mentioned in: https://github.com/streamlink/streamlink/pull/1857#issuecomment-777771116
> plugins.mjunoon: rewrite/fix

- src/streamlink/plugins/openrectv.py
plugins.openrectv was not able to get special videos or past streams.
So I fixed it.
Also, I knew that I could download most of videos on openrectv without logging in, so I changed the specs that way.
> plugins.openrectv: update/fix

- src/streamlink/plugin/api/useragents.py
> plugin.api: update useragents

- src/streamlink/plugins/rtpplay.py
RTP Play Plugin was failing for a couple of weeks now. The website changed structure and the URL parsing needed updating.
> plugins.rtpplay: add schema and fix HLS URL

- CHANGELOG.md
Let's prepare the next release...
This changelog is obviously incomplete and I've probably missed something, so please check. I'll update it as soon as new commits get merged into master. Like usual, plugin fixes/improvementes are not mentioned in the highlights list unless it's an important fix of a bigger / more popular plugin, and there currently are none.
Anything missing except for the currently open PRs?
> release: 2.1.0

- src/streamlink/plugins/youtube.py
closes https://github.com/streamlink/streamlink/issues/3668
> plugins.youtube: fix consent dialog

- src/streamlink/plugins/picarto.py
- tests/plugins/test_picarto.py
> plugins.picarto: rewrite/fix

- src/streamlink/plugins/euronews.py
Fixes #3589
**live / main**
```
$ streamlink -l debug 'https://www.euronews.com/live'
[cli][debug] OS:         Linux-5.12.0-rc8-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.3
[cli][debug] Streamlink: 2.1.1+9.g0f220f2
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug]  url=https://www.euronews.com/live
[cli][info] Found matching plugin euronews for URL https://www.euronews.com/live
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: sPgqEHsONK8
[plugins.youtube][debug] get_video_info - 1: Found data
[plugins.youtube][debug] This video is live.
Available streams: 144p (worst), 240p, 360p, 480p, 720p …
```
> plugins.euronews: rewrite and fix live streams

- CHANGELOG.md
New patch release which fixes the Youtube plugin issues
> release: 2.1.2

- src/streamlink/plugins/tf1.py
closes https://github.com/streamlink/streamlink/issues/3747
> plugins.tf1: fixed api_url

- src/streamlink/plugins/bfmtv.py
> plugins.bfmtv: fix/find Brightcove video data in JS

- src/streamlink/utils/url.py
- tests/test_utils_url.py
> utils.url: fix update_scheme with implicit schemes

- docs/plugin_matrix.rst
- src/streamlink/plugins/olympicchannel.py
- tests/plugins/test_olympicchannel.py
> plugins.olympicchannel: fix / rewrite

- src/streamlink/plugins/twitch.py
Resolves #3761
Clips require three different "persisted" GQL queries now (I couldn't make the previously used custom query work), one which fetches the access token and video qualities, one which fetches the broadcaster and category names, and one which fetches the clip title. There's another query called "ClipsSocialShare" which combines the second and third queries, but the result only includes the broadcaster's "login" property, and not the "displayName" property, which is not necessarily the same.
**I am also not sure if there are clips where the validation could break, as it expects all data to be available**, whereas the previous validation schema made the metadata optional.
```
$ streamlink -l debug --title '{author} - {category} - {title}' …
```
> plugins.twitch: add access token to clips

- docs/plugin_matrix.rst
- src/streamlink/plugins/booyah.py
- tests/plugins/test_booyah.py
> plugins.booyah: new plugin

- src/streamlink/plugins/zattoo.py
#3771 
zattoo.com changes also to hello_v3 and new token.js
Quick fix for zattoo.com live streaming and recording.
> Zattoo.com changes to hello_v3 and new token.js

- src/streamlink/plugins/zattoo.py
closes https://github.com/streamlink/streamlink/issues/3604
closes https://github.com/streamlink/streamlink/issues/3771
ref https://github.com/streamlink/streamlink/pull/3773
> plugins.zattoo: cleanup, fix other domains

- src/streamlink/plugins/twitch.py
With #3774 and #3776 being merged, the Twitch plugin can be cleaned up a bit...
- add `_gql_persisted_query` JSON factory function
- replace validate.text with str
- reformat and refactor validation schemas
- switch to nested get calls and union_get calls
API checks:
**invalid**
```
$ streamlink -l debug--title '{author} - {category} - {title}' twitch.tv/somechannelwhichdoesnotexist best
[plugins.twitch][debug] Getting live HLS streams for somechannelwhichdoesnotexist
error: No playable streams found on this URL: twitch.tv/somechannelwhichdoesnotexist
```
**live**
```
$ streamlink -l debug --title '{author} - {category} - {title}' twitch.tv/weplaydota best
[plugins.twitch][debug] Getting video HLS streams for weplaydota
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, …
```
> plugins.twitch: tidy up API calls

- CHANGELOG.md
Let's prepare the `2.2.0` release.
Anything missing that needs to get added? The PR list is pretty much empty now.
Please check the changelog for any mistakes or missing changes which are important.
https://deploy-preview-3800--streamlink.netlify.app/changelog.html
> release: 2.2.0

- src/streamlink/plugins/youtube.py
Allow videos which are `age restricted` and which can be viewed with the `embed url`.
Example:
https://www.youtube.com/watch?v=HtVdAasjOgU
https://www.youtube.com/embed/HtVdAasjOgU
```
$ streamlink https://www.youtube.com/embed/HtVdAasjOgU -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/HtVdAasjOgU
[plugins.youtube][error] Could not get video info - LOGIN_REQUIRED: ...
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
```
---
Not fixed.
- Video's like `This video is age-restricted and only available on YouTube.`
> plugins.youtube: added API fallback

- src/streamlink/plugins/rtvs.py
- tests/plugins/test_rtvs.py
before
```
$ streamlink https://www.rtvs.sk/televizia/live-1
[cli][info] Found matching plugin rtvs for URL https://www.rtvs.sk/televizia/live-1
error: No playable streams found on this URL: https://www.rtvs.sk/televizia/live-1
```
after
```
$ streamlink https://www.rtvs.sk/televizia/live-1
[cli][info] Found matching plugin rtvs for URL https://www.rtvs.sk/televizia/live-1
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
```
> plugins.rtvs: fixed livestream

- src/streamlink/plugins/nos.py
- tests/plugins/test_nos.py
```
$ streamlink https://nos.nl/collectie/13781/livestream/2385461-ek-voetbal-voorbeschouwing-italie-wales-18-00-uur
[cli][info] Found matching plugin nos for URL https://nos.nl/collectie/13781/livestream/2385461-ek-voetbal-voorbeschouwing-italie-wales-18-00-uur
[cli][info] Available streams: 150k (worst), 216p, 270p, 432p, 576p, 1080p (best)
```
closes https://github.com/streamlink/streamlink/issues/3801
> plugins.nos: Fixed Livestream and VOD

- src/streamlink/plugins/vlive.py
- Fixed broken _page_info regex
- HLSStream cleanup
- validate cleanup
Livestreams can be found here https://www.vlive.tv/home/new
closes https://github.com/streamlink/streamlink/issues/3815
> plugins.vlive: fixed livestream

- src/streamlink/plugins/cdnbg.py
- tests/plugins/test_cdnbg.py
closes https://github.com/streamlink/streamlink/issues/3837
> plugins.cdnbg: Fix regex and referer issues

- src/streamlink/plugins/tv8.py
Fixes #3848 
```
$ streamlink -l debug 'https://www.tv8.com.tr/canli-yayin'
[cli][debug] OS:         Linux-5.13.0-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.2.0+23.gdf5e4ec
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug]  url=https://www.tv8.com.tr/canli-yayin
[cli][info] Found matching plugin tv8 for URL https://www.tv8.com.tr/canli-yayin
Available streams: 576p (worst), 864p (best)
```
> plugins.tv8: remove API, find HLS via simple regex

- src/streamlink/plugins/nimotv.py
- tests/plugins/test_nimotv.py
using regex seems easier than https://github.com/streamlink/streamlink/issues/3875#issuecomment-882002731
might break at some point, but should work for now
closes https://github.com/streamlink/streamlink/issues/3875
---
@Trung0246 could you test it
> plugins.nimotv: use 'mStreamPkg'

- CHANGELOG.md
Since there are no major issues left open or PRs unmerged, I think it's time for the 2.3.0 release.
I've set the date for tomorrow, which is in 3 hours and 18 mins.
Anything missing? Any errors?
> release: 2.3.0

- docs/plugin_matrix.rst
- src/streamlink/plugins/rtve.py
- tests/plugins/test_rtve.py
- update pluginmatcher URL
- use https
- remove to many mirror streams
- fix idAsset
closes https://github.com/streamlink/streamlink/issues/3897
> plugins.rtve: update for /play/ URLs

- docs/plugin_matrix.rst
- src/streamlink/plugins/zattoo.py
- tests/plugins/test_zattoo.py
- use hls7 instead of hls5
- added more log details with validate.Schema
> plugins.zattoo: fix HLS stream, added more debug details

- tests/streams/test_hls.py
This should fix https://github.com/streamlink/streamlink/runs/3270358311#step:8:229 by waiting for the worker thread to terminate first after the entire stream has ended.
The problem with the previous test setup (introduced by be40dd4 in #3883) was that `await_write` didn't wait in any of the empty playlist tests, which meant that the main thread could continue while the worker hadn't processed the reload time yet.
> tests.hls: fix playlist reload time tests

- src/streamlink/plugins/nbcnews.py
The NBCNews plugin stopped working recently after updates of the website. This is a fix to this issue.
> plugins.nbcnews: fix stream URL extraction

- src/streamlink/plugin/plugin.py
- tests/plugins/test_dash.py
- tests/plugins/test_filmon.py
- tests/plugins/test_qq.py
- tests/plugins/test_youtube.py
- tests/test_plugin.py
> tests: fix Plugin.bind(session) calls

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
**plugins.twitch: replace remaining kraken API calls**
Twitch's kraken API will be shut down on 2022-02-28.
Replace all remaining kraken API calls with GraphQL API calls, as helix
requires user authentication for every API request and it doesn't make
sense adding (back) user auth for extracting simple stream and video
metadata, like channel name, stream/video title and game name.
The GraphQL API is already being used for various endpoints which don't
exist on any of Twitch's public APIs.
- Remove anything related to `_channel_id`.
This was previously needed for requesting channel metadata.
- Replace `channel` property method with regular property.
This was previously needed for extracting channel names from video IDs.
- Remove `TwitchAPI.channel_from_*` methods
- Rephrase debug log …
> plugins.twitch: remove kraken API calls

- src/streamlink/plugins/abematv.py
closes https://github.com/streamlink/streamlink/issues/3935
> plugins.abematv: skip invalid ad segments

- src/streamlink/plugins/svtplay.py
> plugins.svtplay: fix plugin video id

- src/streamlink/plugins/deutschewelle.py
- replace regexes with XPath queries
- add audio streams
- add metadata
----
Default live channel (English)
```
$ streamlink -l debug 'https://www.dw.com/en/media-center/live-tv/s-100825'
[cli][debug] OS:         Linux-5.13.12-1-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.3.0+27.g5948d16
[cli][debug]  url=https://www.dw.com/en/media-center/live-tv/s-100825
[cli][info] Found matching plugin deutschewelle for URL https://www.dw.com/en/media-center/live-tv/s-100825
[plugins.deutschewelle][debug] Using channel ID: 1
Available streams: 360p (worst), 400p, 576p, 720p, 1080p …
```
> plugins.deutschewelle: rewrite plugin

- src/streamlink/plugins/pluto.py
- tests/plugins/test_pluto.py
> plugins.pluto: fix URL match for 2 letter language codes

- src/streamlink/plugins/welt.py
Live
```
$ streamlink -l debug 'https://www.welt.de/tv-programm-live-stream/'
[cli][debug] OS:         Linux-5.13.12-1-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.3.0+37.g64649fd
[cli][debug]  url=https://www.welt.de/tv-programm-live-stream/
[cli][info] Found matching plugin welt for URL https://www.welt.de/tv-programm-live-stream/
Available streams: 360p_alt (worst), 360p, 540p_alt, 540p, 720p_alt, 720p (best)
```
VODs / news
```
$ streamlink -l debug 'https://www.welt.de/politik/deutschland/article233507036/Ausbleibende-Zahlungen-Geld-fuer-Intensivbetten-Krankenhaeus …
```
> plugins.welt: rewrite and simplify using XPath

- src/streamlink/stream/ffmpegmux.py
Fixes #3991 
No tests for this change, because the test for `FFMPEGMuxer.open` currently doesn't touch the `pipe_threads`, and I don't want to mess with this.
The fix is simple, just break out of the while loop instead of returning, so that the `pipe.close()` call always gets made.
```
$ streamlink -l debug 'https://www.youtube.com/watch?v=xcJtL7QggTI' best
[cli][debug] OS:         Linux-5.13.13-1-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.3.0+49.g830c5ec
[cli][debug]  url=https://www.youtube.com/watch?v=xcJtL7QggTI
[cli][info] Found matching plugin youtube for URL …
```
> stream.ffmpegmux: always clean up named pipes

- CHANGELOG.md
Let's prepare the 2.4.0 release.
- Anything missing in the changelog?
- Any mistakes in the changelog? Anything that should be worded differently?
- Anything important that should be included in 2.4.0? I don't have anything on my radar at least.
Date is set to 2021-09-07, which is in ~2 hours.
> release: 2.4.0

- tests/test_plugins.py
This fixes `test_plugins` which loaded modules via deprecated loader methods on Python 3.10.
Previously `test_plugins` tried loading the plugin modules for a second time in each plugin test case via the passed loader, but that's unnecessary as the plugins already get loaded in the `load_module` call for preparing the list of plugins, so it now passes the module object directly.
It now also filters out plugin files beginning with `common_` instead of checking for an exported `__plugin__` attribute on the module object of all potential plugin files, because that made the `__plugin__` assertion in the test case rather pointless.
----
Related #3971 
Example warnings on the ubuntu test runner:
> =============================== warnings summary ===============================
> …
> tests: fix deprecated module imports on py310

- src/streamlink/plugins/bbciplayer.py
- remove HDSStream (#4040)
- upgrade http to https
---
Before:
```
[cli][info] Found matching plugin bbciplayer for URL bbc.co.uk/iplayer/live/bbcone
[plugins.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugins.bbciplayer][error] Could not authenticate, check your username and password
error: No playable streams found on this URL: bbc.co.uk/iplayer/live/bbcone
```
Now (live):
```
[cli][info] Found matching plugin bbciplayer for URL bbc.co.uk/iplayer/live/bbcone
[plugins.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Available streams: 216p_dash, 288p_dash, …
```
> plugins.bbciplayer: remove HDSStream, upgrade scheme

- src/streamlink/plugins/earthcam.py
Ref #4040 
I'm aware of
> 11. Sites which are static cameras of a physical location
but this is technically just a removal of the RTMP streams of this already existing plugin.
If you want to remove the plugin instead, we can do so, but I don't think it's necessary.
----
Live video stream:
```
$ streamlink -l debug 'https://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo1'
[cli][debug] OS:         Linux-5.14.5-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0+21.g1a5cb46
[cli][debug]  url=https://www.earthcam.com/usa/newyork/timessquare/?cam=tsrobo1
[cli][info] Found matching plugin earthcam for URL …
```
> plugins.earthcam: rewrite plugin, remove rtmp

- src/streamlink/plugins/oneplusone.py
- tests/plugins/test_oneplusone.py
- cleanup, use lxml with validate
- added auto session reload, because some streams might expire to fast
> plugins.oneplusone: cleanup and add auto session reload

- src/streamlink/plugins/bfmtv.py
This removes the `itertags` calls and replaces data extraction from regexes with XPath and validation schemas.
I haven't been able to find any streams using the "brightcove_js" method. I've kept it for now (and updated it accordingly), but I'm pretty sure it's not used on these sites anymore and could be removed here.
----
BFMTV - Live (brightcove):
```
$ streamlink -l debug 'https://www.bfmtv.com/en-direct/'
[cli][debug] OS:         Linux-5.14.8-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0+29.gef90816
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug]  url=https://www.bfmtv.com/en-direct/
[cli][info] Found matching plugin bfmtv for URL …
```
> plugins.bfmtv: rewrite plugin using XPath

- docs/plugin_matrix.rst
- src/streamlink/plugins/pandalive.py
- tests/plugins/test_pandalive.py
closes #3866
I've only used `hls2` for the URLs for the time being, as all point to the same 720p-only variant playlist, even for 360p.  `hls` uses the `http` scheme, the other two use `https`.
<details><summary>API JSON</summary>
```
{
"html5": true,
"media": {
"code": "18036867_2021100288f93bda917504b0",
"title": "[생] 대구 99일차)운동으로 덤벼라,,,!",
"userId": "baseball767",
"userIdx": 18036867,
"userNick": "채서린♡",
"category": "ind",
"isAdult": false,
"isPw": false,
"type": "free",
"heart": 0,
"user": 30,
"userLimit": 300,
"sizeWidth": 1280,
"sizeHeight": 720,
"browser": "win",
"startTime": "2021-10-02 03:59:07",
"endTime": "0000-00-00 00:00:00",
"isLive": true,
"liveType": "live",
"playCnt": 585,
"likeCnt": 25,
"bookmarkCnt": 675,
"totalScoreCnt": 16355,
"storage": "storage86",
"isGuestLive": …
```
> plugins.pandalive: new plugin

- src/streamlink/session.py
- tests/test_session.py
https://github.com/streamlink/streamlink/pull/4053#issuecomment-932944760
> session: don't override https-proxy scheme

- src/streamlink/plugins/showroom.py
- tests/plugins/test_showroom.py
- remove RTMP
- cleanup room_id
- error message for 403 eror on playlist
> plugins.showroom: cleanup

- src/streamlink/plugins/openrectv.py
> plugins.openrectv: be able to get subscription video

- src/streamlink/plugins/picarto.py
- tests/plugins/test_picarto.py
> plugins.picarto: update URL regex and logic

- src/streamlink/plugins/ltv_lsm_lv.py
- tests/plugins/test_ltv_lsm_lv.py
> plugins.ltv_lsm_lv: update the plugin for the new page layout

- script/makeinstaller.sh
Forgot to include this change in #4143
> installer: bump lxml to 4.6.4

- src/streamlink/plugins/twitcasting.py
#4153 
```
$ streamlink 'https://twitcasting.tv/deoxymole' best -l debug
[cli][debug] OS:         Linux-5.15.0-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0+76.g73417ce.dirty
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug]  url=https://twitcasting.tv/deoxymole
[cli][info] Found matching plugin twitcasting for URL https://twitcasting.tv/deoxymole
[plugins.twitcasting][debug] Live stream info: {'movie': {'id': 708601320, 'live': True}, 'fmp4': {'host': '211-133-247-132.twitcasting.tv', 'proto': 'wss', 'source': True, 'mobilesource': True}}
[plugins.twitcasting][debug] Real stream url: …
```
> plugins.twitcasting: re-implement websocket client

- src/streamlink/plugins/twitch.py
- can be used for `Authorization` or other headers
- change PlaybackAccessToken playerType to `site` as `embed` will show ads
- remove some unsed HLS and headers code
---
```
streamlink https://twitch.tv/twitch best \
--twitch-api-header "X-Device-Id=twitch-web-wall-mason" \
--twitch-api-header "Device-Id=twitch-web-wall-mason"
```
closes https://github.com/streamlink/streamlink/pull/4080
> plugins.twitch: new plugin command --twitch-api-header

- src/streamlink/plugins/nicolive.py
- re-implement websocket client
- remove watchinginterval message and scheduler logic
- remove currentstream command handler
- rewrite login and parse response using a validation schema
- rewrite websocket API URL parser using a validation schema
- rewrite custom HLSStream which needs the websocket client reference
- close websocket when stream closes
- close websocket if no stream gets opened
- remove unnecessary log spam when waiting for permit via websocket
- fix URL matcher
- rephrase log messages
- reformat existing code
----
#4153 
1. Login is completely untested. The login logic which is based on cookies didn't get changed though.
2. Not sure about the previously implemented `send_watching` method and the dedicated scheduler thread. The `watchinginterval` command doesn't seem to be …
> plugins.nicolive: re-implement plugin

- src/streamlink/plugin/api/websocket.py
- src/streamlink/plugins/ustreamtv.py
- tests/test_api_websocket.py
- replace flvconcat with ffmpegmux
- add typed namedtuples for stream formats and stream segments
- implement WebsocketClient
- simplify message handling and remove state polling
- use validation schemas to parse messages
- parse stream formats once
- add subscribable thread-safe segment queues (deques)
- rewrite UStreamTVStream{,Reader,Worker,Writer}
- rename stream shortname from "uhs" to "ustreamtv"
- simplify segment waiting logic and immediately stop worker and writer
threads when the stream gets closed
- find channel ID via XPath
- simplify stream initialization
----
ref #4040
This is a complete rewrite of the ustreamtv plugin which uses muxed MPEG4 video and audio streams and finally removes the last import of flash video stuff. :tada: 
The streams which I've tested are working …
> plugins.ustreamtv: re-implement plugin

- src/streamlink/plugins/twitch.py
With #4163 being merged, the API headers initialization can be simplified now
> plugins.twitch: refactor api-headers

- src/streamlink/plugins/.removed
> plugins.rtmp: add to removed plugins list

- CHANGELOG.md
- docs/deprecations.rst
Closes #4145 
Let's prepare the 3.0.0 release.
Writing this changelog took me longer than I anticipated. I haven't fully checked and proof-read it myself yet, so if there's anything wrong or needs to be improved, please comment. I had to put the breaking changes into their own list, because otherwise it would've been way too much. That's why I also didn't include some plugin changes which I would've included otherwise. It also already includes my PR from earlier today which hasn't been merged yet.
Even if the date of the changelog is set for today, nothing is set in stone yet. I'd suggest waiting a bit first to see if there are any last-minute changes. As always, I will update the changelog when new stuff gets merged.
- https://github.com/bastimeyer/streamlink/blob/releases/3.0.0/CHANGELOG …
> release: 3.0.0

- CHANGELOG.md
Hotfix for #4179 
https://deploy-preview-4181--streamlink.netlify.app/changelog.html#streamlink-3-0-1-2021-11-17
> release: 3.0.1

- docs/plugin_matrix.rst
- src/streamlink/plugins/tviplayer.py
- tests/plugins/test_tviplayer.py
https://en.wikipedia.org/wiki/Televis%C3%A3o_Independente
```
$ streamlink https://tviplayer.iol.pt/direto/TVI24
[cli][info] Found matching plugin tviplayer for URL https://tviplayer.iol.pt/direto/TVI24
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p
```
```
$ streamlink https://tviplayer.iol.pt/programa/prisioneira/5c890ae00cf2f1892ed73779/episodio/t2e219
[cli][info] Found matching plugin tviplayer for URL https://tviplayer.iol.pt/programa/prisioneira/5c890ae00cf2f1892ed73779/episodio/t2e219
[cli][info] Available streams: 240p (worst), 360p, 576p (best)
[cli][info] Opening stream: 576p
```
```
$ streamlink https://tviplayer.iol.pt/direto/TVI_AFRICA
[cli][info] Found matching plugin tviplayer for URL …
```
> plugins.tviplayer: new plugin

- src/streamlink/plugins/ard_mediathek.py
- fix schema for age restricted content
- refactor schema similar to ard_live plugin
- return non-auto quality HTTP streams as fallback
- add show titles
----
fixes #4200 
Age restricted content
```
$ streamlink 'https://www.ardmediathek.de/video/fernsehfilm/corpus-christi-oder-drama/wdr/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTVjMTEwZjJmLTUzOTMtNDBlYS04OTRlLWUwZWJkOGM2OGVlOQ/'
[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/video/fernsehfilm/corpus-christi-oder-drama/wdr/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTVjMTEwZjJmLTUzOTMtNDBlYS04OTRlLWUwZWJkOGM2OGVlOQ/
[plugins.ard_mediathek][info] The content is unavailable
error: No playable streams found on this URL: https://www.ardmediathek.de/video/fernsehfilm/corpus-christi-oder-drama/wdr/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTVjMTEwZjJ …
```
> plugins.ard_mediathek: fix plugin

- src/streamlink/plugins/youtube.py
`microformat.playerMicroformatRenderer.category` should always be available, right, @back-to ?
I haven't managed to find any video without it yet.
> plugins.youtube: add category metadata

- src/streamlink/stream/hls.py
This fixes the phenomenon where during twitch stream prerolls,
a lot of TCP connections are opened / closed rapidly,
instead of the same one(s) being reused for sequential segments
like during normal operation.
The response data always needs to be read from the socket,
otherwise the socket cannot be reused by other HTTP requests
(hence the rapid closing/opening of connections during skipped segments)
> stream.hls: read and discard filtered sequences properly

- src/streamlink/plugins/pluto.py
- tests/plugins/test_pluto.py
- use v4 API
- update URL path matching for "Watch Now" VoD URLs
- filter advert segments
- add more metadata support
- update URL tests for "Watch Now" VoD URLs
closes #3462
> plugins.pluto: rewrite/fix

- src/streamlink/plugins/steam.py
- replace itertags with XPath
- simplify logic a bit
- move schemas from plugin class scope
- fix log messages
> plugins.steam: refactor plugin

- src/streamlink/plugins/onetv.py
- tests/plugins/test_onetv.py
```
$ streamlink https://static.1tv.ru/eump/pages/1tv_live_orbit-plus-4.html best
[cli][info] Found matching plugin onetv for URL https://static.1tv.ru/eump/pages/1tv_live_orbit-plus-4.html
[cli][info] Available streams: 360p_430k (worst), 360p_1100k, 720p_1400k, 720p_2600k, 720p_4100k (best)
1tv-orbit-plus-4.m3u8
```
```
$ streamlink https://static.1tv.ru/eump/pages/1tv_live.html best
[cli][info] Found matching plugin onetv for URL https://static.1tv.ru/eump/pages/1tv_live.html
[cli][info] Available streams: 360p_430k (worst), 360p_1100k, 720p_1400k, 720p_2600k, 720p_4100k (best)
1tv.m3u8
```
> plugins.onetv: added support for channel with different timezone +4

- docs/plugin_matrix.rst
- src/streamlink/plugins/stadium.py
- tests/plugins/test_stadium.py
- add VODs support
- remove itertags, use XPath
- update validation schemas
----
```
$ streamlink 'https://watchstadium.com/' best
[cli][info] Found matching plugin stadium for URL https://watchstadium.com/
[cli][info] Available streams: 270p (worst), 360p, 540p, 720p (best)
```
```
$ streamlink 'https://watchstadium.com/live' best
[cli][info] Found matching plugin stadium for URL https://watchstadium.com/live
[cli][info] Available streams: 270p (worst), 360p, 540p, 720p (best)
```
```
$ streamlink 'https://watchstadium.com/sport/college-football/' best
[cli][info] Found matching plugin stadium for URL https://watchstadium.com/sport/college-football/
[cli][info] Available streams: 270p (worst), 360p_alt, 360p, …
```
> plugins.stadium: rewrite

- src/streamlink_cli/main.py
- tests/test_cli_main.py
> cli: create file output before opening the stream

- docs/plugin_matrix.rst
I just noticed I didn't update this.  Sorry about that.
Edit: I really should run a documentation check before pushing...
> plugins.albavision: update plugin_matrix.rst

- src/streamlink/plugins/pluto.py
> plugins.pluto: add filtering of bumper segments

- docs/plugin_matrix.rst
- src/streamlink/plugins/ceskatelevize.py
- tests/plugins/test_ceskatelevize.py
All livestreams are available at https://www.ceskatelevize.cz/zive/
remove unnecessary subdomains with different API.
---
```
$ streamlink https://www.ceskatelevize.cz/zive/ct1/ best
[cli][info] Found matching plugin ceskatelevize for URL https://www.ceskatelevize.cz/zive/ct1/
[plugins.ceskatelevize][debug] current={'channel': 'ct1', 'channelName': 'ČT 1', 'legacyEncoder': 'CT1'}
[plugins.ceskatelevize][debug] next={'channel': 'ct1', 'channelName': 'ČT 1', 'legacyEncoder': 'CT1'}
[cli][info] Available streams: 288p (worst), 404p, 576p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
```
```
$ streamlink https://www.ceskatelevize.cz/zive/ct31/ best
[cli][info] Found matching plugin ceskatelevize for URL https://www.ceskatelevize.cz/zive/ct31/
[plugins.ceskatelevize][debug] …
```
> plugins.ceskatelevize: Fix Livestreams

- src/streamlink/plugins/vk.py
- tests/plugins/test_vk.py
- drop IPHONE6 user agent
- update matcher regexes
- rewrite redirection logic
- rewrite validation schemas, remove itertags
- add id, author and title metadata
- drop HTTPStream and add DASHStream, prefer HLSStream
- update tests
----
Tested various VODs and live streams, but not 100% sure if I've missed something...
> plugins.vk: rewrite and remove itertags

- src/streamlink/plugins/streann.py
- tests/plugins/test_streann.py
- replace itertags with XPath query
- split pluginmatcher into two
- drop willax.tv
> plugins.streann: remove itertags

- src/streamlink/plugins/foxtr.py
Resolves #4283 
```
$ streamlink -l debug 'https://www.fox.com.tr/canli-yayin'
[cli][debug] OS:         Linux-5.15.9-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.10.1
[cli][debug] Streamlink: 3.0.3+31.g455e480
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug]  url=https://www.fox.com.tr/canli-yayin
[cli][info] Found matching plugin foxtr for URL https://www.fox.com.tr/canli-yayin
Available streams: 360p (worst), 480p, 720p (best)
```
> plugins.foxtr: fix regex

- docs/install.rst
- update Ubuntu PPA link
- update Solus and Void package maintainers
----
- https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=streamlink&field.status_filter=published&field.series_filter=
- https://dev.getsol.us/source/streamlink/browse/master/MAINTAINERS.md;streamlink-3.0.3-35$4
- https://github.com/void-linux/void-packages/blame/5c4a62fd8f7b4ec3e5f861b55c036472e01a951d/srcpkgs/streamlink/template#L12
> docs: fix linux package infos

- CHANGELOG.md
There are a couple of changes and bugfixes on the master branch for a few weeks now which should be published in a new release.
Anything else missing that should be included?
Changelog looking good without any errors/mistakes or missing changes?
The release date is as always set for today. I will update it if the PR won't be merged in time.
> release: 3.1.0

- src/streamlink/plugins/twitcasting.py
- fix error msg for users without any 'movie'
- fix error msg for streams that require a login,
--http-cookie can be used to login.
- changed log msg from format to f-string
- use default User-Agent
closes https://github.com/streamlink/streamlink/issues/4281
> plugins.twitcasting: Fix error messages

- examples/opencv-face.py
> typo fix "steams" to "streams" in opencv-face.py

- docs/plugin_matrix.rst
- src/streamlink/plugins/filmon.py
- tests/plugins/test_filmon.py
- use alternative/current sources for live and VOD stream info
- update schemas
- update URL regex
- update tests
- add support for mp4 VOD sources
- add note to docs regarding mp4 VODs
- use TLSSecLevel1Adapter()
closes #4332
> plugins.filmon: fix/update

- src/streamlink/plugins/pandalive.py
Resolves #4337 
```
$ streamlink -l debug 'https://www.pandalive.co.kr/live/play/19178412' best
[cli][debug] OS:         Linux-5.16.7-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1+4.geb8b8be
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug]  url=https://www.pandalive.co.kr/live/play/19178412
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/19178412
[plugins.pandalive][debug] Media code: 19178412
[plugins.pandalive][info] Broadcast type: live
[cli][info] Available streams: 720p (worst, best) …
```
> plugins.pandalive: fix plugin

- src/streamlink/plugins/openrectv.py
> plugins.openrectv: get URLs from subs_trial_media

- docs/plugin_matrix.rst
- src/streamlink/plugins/lnk.py
- tests/plugins/test_lnk.py
[LNK](https://en.wikipedia.org/wiki/LNK_(television_station)) is a Lithuanian broadcasting group with several TV channels under it. Those are freely streamed at https://lnk.lt/tiesiogiai .
> plugins.lnk: add new plugin

- src/streamlink/plugins/nicolive.py
```
$ streamlink https://live.nicovideo.jp/watch/lv
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/lv
[plugins.nicolive][info] Logging in via provided email and password
Enter the 6 digit number included in email: 123456
[plugins.nicolive][info] Logged in.
[cli][info] Available streams: 350k (worst), 690k, 1800k (best)
[cli][info] Opening stream: 1800k (hls)
```
closes https://github.com/streamlink/streamlink/issues/4365
> plugins.nicolive: fix login via email

- CHANGELOG.md
Please check if I've missed something in the changelog.
Release date is set for today, but if there's something that needs to get squeezed in and isn't ready yet, we can of course wait.
> release: 3.2.0

- tests/plugins/test_onetv.py
- tests/plugins/test_tv999.py
> tests: fix accidental URL string concatenation

- src/streamlink/plugins/mdstrm.py
- tests/plugins/test_mdstrm.py
https://www.mediastre.am/en/about-us
closes https://github.com/streamlink/streamlink/issues/4389
ref https://github.com/streamlink/streamlink/pull/4269
```
$ streamlink https://mdstrm.com/live-stream/5a7b1e63a8da282c34d65445
[cli][info] Found matching plugin mdstrm for URL https://mdstrm.com/live-stream/5a7b1e63a8da282c34d65445
[plugins.mdstrm][debug] iframe=https://mdstrm.com/live-stream/5a7b1e63a8da282c34d65445
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p (best)
```
```
$ streamlink https://www.latina.pe/tvenvivo
[cli][info] Found matching plugin mdstrm for URL https://www.latina.pe/tvenvivo
[plugins.mdstrm][debug] iframe=https://mdstrm.com/live-stream/5ce7109c7398b977dc0744cd?autoplay=false&player=
[plugins.mdstrm][debug] …
```
> plugins.mdstrm: new plugin for mdstrm.com livestreams

- README.md
> docs: README.md update link to plugins list

- docs/cli/metadata.rst
- src/streamlink_cli/main.py
- tests/test_cli_main.py
- tests/test_cli_main_formatter.py
> Add `plugin` metadata variable

- src/streamlink/plugins/trovo.py
- tests/plugins/test_trovo.py
> plugins.trovo: new plugin

- docs/install.rst
- https://github.com/streamlink/streamlink/blob/3f613dad4bb509ae8fc8477e13f42c5593fd494c/pyproject.toml#L4
- https://github.com/streamlink/streamlink/pull/4440#issue-1197913434
> docs: fix incorrect min setuptools version

- tests/test_plugins.py
https://github.com/streamlink/streamlink/issues/4383#issue-1160468575
> tests.plugins: make description metadata mandatory

- CHANGELOG.md
Package updates won't be necessary.
> release: 4.0.1

- src/streamlink/plugins/hiplayer.py
- tests/plugins/test_hiplayer.py
* replaces rotana with rewrite/fix
* add support for cnbcarabia.com, media.gov.kw
closes  #4501
> plugins.hiplayer: new plugin

- src/streamlink/stream/segmented.py
- src/streamlink_cli/main.py
A simple, maybe ulgy, attempt to fix #4516 .
There may be more beautiful approaches.
> stream.segmented: join worker+writer on close

- src/streamlink/session.py
- tests/test_session.py
- Import urllib3 directly instead of importing from requests.packages
- Remove unneeded urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST
override, as it's not used on py3
- Update ipv4/ipv6 tests, add http-disable-dh tests
----
Motivation:
https://github.com/psf/requests/blob/v2.27.1/requests/packages.py#L11-L20
The `urllib3.contrib.pyopenssl` stuff in `--http-disable-dh` should've been removed with py2:
https://urllib3.readthedocs.io/en/latest/reference/contrib/pyopenssl.html
----
The `--http-disable-dh` logic could also be changed in the future, so that no global `urllib3.util.ssl_.DEFAULT_CIPHERS` override has to be done. Similar to #4345, TLS cipher updates could be applied in a new `SSLContext` (created via [`urllib3.util.ssl_.create_urllib3_context`](https://github.com/urllib3/urlli …
> session: fix deprecated imports

- src/streamlink/stream/hls.py
The write-discard logic added in #4229 can be simplified by just calling [`urllib3.HTTPResponse.drain_conn()`](https://github.com/urllib3/urllib3/blob/1.26.9/src/urllib3/response.py#L285-L294) instead of consuming the stream iterator from `requests.Response.iter_content()` in an empty for-loop. urllib3 calls this method itself [when performing HTTP redirections](https://github.com/urllib3/urllib3/blob/1.26.9/src/urllib3/poolmanager.py#L404-L418).
This PR also makes the signature of `HLSStreamWriter.write` consistent with `SegmentedStreamWriter.write`.
----
Here's a quick verification that it doesn't create any new TCP connections and properly releases the connection to the connection pool when HLS segments get filtered out, eg. by making `TwitchHLSStreamWriter.should_filter_sequence` …
> stream.hls: simplify discard logic in writer

- src/streamlink/plugins/mildom.py
* add auto update of HLS URL query string for auth
* refactor to use MildomAPI class
---
<details><summary>Before:</summary>
```
[cli][debug] OS:         Linux-4.9.0-18-amd64-x86_64-with-debian-9.13
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 4.0.1+26.gd973cfc0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug]  url=https://www.mildom.com/10269223
[cli][debug]  stream=['144p']
[cli][debug]  --output=/dev/null
[cli][info] Found matching plugin mildom for URL https://www.mildom.com/10269223
[cli][info] Available streams: 144p (worst), 360p_alt, 360p (best)
[cli][info] Opening stream: 144p (hls)
/dev/null
[cli][debug] Checking file output
[stream.hls][debug] Reloading …
```
> plugins.mildom: fix/update

- src/streamlink/plugins/blazetv.py
- tests/plugins/test_blazetv.py
Live UK IP:
```
$ streamlink --title '{id} ! {author} ! {title} ! {category}' blaze.tv/live worst
[cli][info] Found matching plugin blazetv for URL blaze.tv/live
[cli][info] Available streams: 360p (worst), 432p, 504p, 720p (best)
[cli][info] Opening stream: 360p (hls)
```
Live non UK IP:
```
$ streamlink --title '{id} ! {author} ! {title} ! {category}' blaze.tv/live worst
[cli][info] Found matching plugin blazetv for URL blaze.tv/live
error: Unable to open URL: https://blaze.tv/live (403 Client Error: Forbidden for url: https://watch.blaze.tv/live/)
```
VOD UK IP:
```
$ streamlink --title '{id} ! {author} ! {title} ! {category}' …
```
> plugins.blazetv: new plugin

- CHANGELOG.md
Release date is set for tomorrow. Not sure though if it's ready yet. Let's see...
> release: 4.1.0

- src/streamlink/plugins/aloula.py
- tests/plugins/test_aloula.py
closes #4559
Live:
```
$ streamlink https://www.aloula.sa/en/live/sbc-channel
[cli][info] Found matching plugin aloula for URL https://www.aloula.sa/en/live/sbc-channel
Available streams: 360p (worst), 480p, 1080p (best)
```
VOD:
```
$ streamlink https://www.aloula.sa/episode/11178?continue=8 
[cli][info] Found matching plugin aloula for URL https://www.aloula.sa/episode/11178?continue=8
Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
```
Login restricted VOD:
```
$ streamlink https://www.aloula.sa/episode/11577
[cli][info] Found matching plugin aloula for URL https://www.aloula.sa/episode/11577
[plugins.aloula][error] This stream requires a logged-in session cookie to be supplied
error: No playable streams found on this URL: https://www.aloula.sa/episode/11577
```
--- …
> plugins.aloula: new plugin

- setup.cfg
> build: fix python_requires

- src/streamlink/plugins/youtube.py
Fixes #4485 
Unverified... This is based on the assumption that https://github.com/streamlink/streamlink/issues/4485#issuecomment-1148844641 is correct.
@Benfor4 @Kagamia
could you please check and verify?
> plugins.youtube: fix InitialPlayerResponse regex

- src/streamlink/plugins/idf1.py
before
```
[cli][info] Found matching plugin idf1 for URL https://www.idf1.fr/live
error: No playable streams found on this URL: https://www.idf1.fr/live
```
after
```
[cli][info] Found matching plugin idf1 for URL https://www.idf1.fr/live
[cli][info] Available streams: 360p (worst, best)
[cli][info] Opening stream: 360p (hls)
```
> plugins.idf1: fix plugin

- src/streamlink/plugins/telefe.py
- tests/plugins/test_telefe.py
> plugins.Telefe: fix livestream

- docs/install.rst
Forgot to include this in #4597
> docs: fix versioningit version

- src/streamlink/plugin/api/websocket.py
- tests/test_api_websocket.py
> plugin.api.websocket: don't join current thread

- src/streamlink/plugins/vk.py
closes #4612
```
$ streamlink https://vk.com/video-211154316_456239169
[cli][info] Found matching plugin vk for URL https://vk.com/video-211154316_456239169
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
```
> plugins.vk: fix

- src/streamlink/plugins/twitcasting.py
> plugins.twitcasting: discard text frames

- src/streamlink/plugins/rtve.py
- tests/plugins/test_rtve.py
Resolves #4622 
I've also added a test for the new stream URL extraction / de-obfuscation. Probably a bit too much and unnecessary. If you don't want to merge this, and I'm not sure if I want either, then I can remove it, as it's 20KiB of base64 data.
Subtitles are still broken, but that's because the MuxedStream ends when one of its substreams ends, namely the subtitle HTTPStream, which is just a few KiBs. Other plugins also have this problem.
----
Streams tested via Spanish proxy:
Live:
```
$ streamlink 'https://www.rtve.es/play/videos/directo/canales-lineales/la-1/' best
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/directo/canales-lineales/la-1/
[cli][info] Available streams: 360p (worst), 576p, 720p (best)
... …
```
> plugins.rtve: rewrite plugin

- src/streamlink/plugins/trovo.py
- tests/plugins/test_trovo.py
> plugins.trovo: update URL matching, tests

- src/streamlink/plugins/vk.py
Also corrected the API POST `params`/`data` dicts.
closes #4637
> plugins.vk: add support for WAF cookie

- src/streamlink/plugins/vidio.py
Fixes #4640
As mentioned in https://github.com/streamlink/streamlink/issues/4640#issuecomment-1177511874, instead of DASH streams, I would like to use HLS streams for live streams, but I'm not sure how to apply the token to the stream URLs. The website is using DASH streams for live streams, so it's obvious how to apply the token, but it's not for HLS streams, especially because VODs are streamed via HLS, but don't require a token, at least from what I checked.
Don't merge yet. I'd like to see a confirmation first.
```
$ streamlink 'https://www.vidio.com/live/204-sctv' best
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/204-sctv
[cli][info] Available streams: 240p+a153k (worst), 240p+a172k, 360p+a153k, 360p+a172k, 480p+a153k, 480p+a172k, 720p+a153k, 720p+a172k …
```
> plugins.vidio: rewrite plugin

- docs/ext_argparse.py
https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html
> pycodestyle has been updated to >= 2.9.0, < 2.10.0
> Pyflakes has been updated to >= 2.5.0, < 2.6.0
> ci: fix new flake8 5.0.0 linting issues

- src/streamlink/plugins/dlive.py
- remove unneeded json import
- move and update validation schemas
- don't suppress any PluginErrors (raised from ValidationErrors)
- reformat code
> plugins.dlive: refactor

- src/streamlink/plugins/cmmedia.py
- update validation schemas
- fix invalid `validate.validate()` call (should be `schema.validate()`) by merging schemas via `validate.union((..., ...))`
- remove unnecessary functools.partial
> plugins.cmmedia: refactor

- src/streamlink/plugins/ltv_lsm_lv.py
The plugin was broken due to site changes.
- moved and updated validation schemas
- simplified channel ID extraction
- reformatted code
> plugins.ltv_lsm_lv: fix plugin

- src/streamlink/plugins/olympicchannel.py
- move and update validation schemas using XPath
- rewrite parsing of embedded JSON and JSON retrieval from API
- simplify token-generator request
> plugins.olympicchannel: rewrite

- src/streamlink/plugins/btv.py
- move and update validation schemas
- simplify `_get_streams()`
- add geo-block check
> plugins.btv: rewrite

- src/streamlink/plugins/raiplay.py
- move and update validation schemas using XPath
> plugins.raiplay: refactor

- src/streamlink/plugins/blazetv.py
- update and fix validation schemas, and fix `None` return value
- replace `validate.validate(schema, value)` with `schema.validate(value)` (so that it raises a `PluginError` and not a `ValidationError` on error)
- use staticmethods and rename shadowed names
> plugins.blazetv: refactor

- src/streamlink/plugins/albavision.py
- src/streamlink/plugins/mdstrm.py
- src/streamlink/plugins/youtube.py
That should be the last plugin schema updates from me for now. As said on the streamlink Gitter channel, there are a couple of validation schemas left that could be refined according to the newly added stuff, but there are some problems.
```sh
$ GIT_PAGER=cat git grep -Pn --heading \
-e 'validate\.any\(\s*None,\s*validate\.all\(' \
-e 'validate\.transform\(\s*.+?\.search\s*\)' \
-e 'validate\.validate\(' \
-e 're\.Match,' \
-e ',\s+validate\.Schema\(' \
src/streamlink/plugins/
src/streamlink/plugins/ard_mediathek.py
75:                validate.any(None, validate.all(
81:                        "show": validate.any(None, validate.all(
src/streamlink/plugins/common_jwplayer.py
12:    validate.transform(_playlist_re.search),
src/streamlink/plugins/rtbf.py
59: …
```
> plugins: call schema.validate(value)

- src/streamlink/plugins/deutschewelle.py
- tests/plugins/test_deutschewelle.py
> plugins.deutschewelle: rewrite and fix plugin

- src/streamlink/plugins/bloomberg.py
- tests/plugins/test_bloomberg.py
Noticed that the plugin was slightly broken during the recent plugin refactorings but then forgot to fix it...
> plugins.bloomberg: fix default US live stream

- CHANGELOG.md
Anything missing? Any unsubmitted changes?
Release date is set for today, but I will update each day at midnight UTC if it's not ready yet, as usual.
Unmerged PRs:
- #4733
> release: 4.3.0

- src/streamlink/plugins/steam.py
I made a mistake in e999ac5b4f4883b8ee805586b45b7aef375b7911 and accidentally broke the login of the Steam plugin by removing the `donotcache` class property and only replacing one of the property lookups.
The changes of this PR also replace the stack trace of the `SteamLoginFailed` exception on login failure with a simple error log message.
> plugins.steam: fix login

- src/streamlink/plugin/plugin.py
- tests/test_plugin.py
In preparation for #4744
The old tests were in need of a rewrite (similar to the ffmpegmux tests), and updating them for the removal of `Plugin.bind()` doesn't make much sense, so here's a rewrite based on pytest with a much easier setup that can be replaced very easily when `Plugin.bind()` gets removed. I also applied some minor style clean-ups and added typing information...
> tests: rewrite plugin cookies tests

- src/streamlink/plugins/atresplayer.py
Fixes #4755 
As said in #4755, I can't validate whether the plugin is actually working, as the site requires a paid subscription for non-Spanish IP addresses and it also detects my VPN service, so I can't access the site using it either.
@heroku-miraheze @Jeffade1 
Please check if the plugin is working. You can install Streamlink from the branch of my PR, or you can just copy the modified plugin and sideload it. Please post a full debug log once you've done that. Thanks.
https://streamlink.github.io/install.html#pypi-package-and-source-code
https://streamlink.github.io/cli/plugin-sideloading.html
> plugins.atresplayer: fix plugin

- src/streamlink/cache.py
- src/streamlink/logger.py
- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/bbciplayer.py
- src/streamlink/plugins/dailymotion.py
- src/streamlink/plugins/dash.py
- src/streamlink/plugins/ntv.py
- src/streamlink/plugins/radiko.py
- src/streamlink/plugins/tf1.py
- src/streamlink/stream/dash_manifest.py
- src/streamlink/stream/hls_playlist.py
- src/streamlink_cli/main.py
- tests/resources/__init__.py
Just a little low effort code cleanup for string concatenations via the `+` operator.
I also had a look at replacing `stringliteral.format()` calls, but that's completely unfeasible.
> chore: use f-strings for concatenation

- src/streamlink/plugins/okru.py
- tests/plugins/test_okru.py
> plugins.okru: translate mobile URLs

- src/streamlink_cli/utils/progress.py
Just some small optimizations and simplifications that should've been included in #4764 / #4656
> cli.utils.progress: refactor

- src/streamlink/plugins/trovo.py
A couple of days ago method of obtaining vod stopped working.
```
streamlink -l trace https://trovo.live/s/mob5ter/549788169885?vid=lc-387702297637298015
[23:42:42.492682][cli][debug] OS:         Linux-5.4.0-105-generic-x86_64-with-glibc2.31
[23:42:42.492854][cli][debug] Python:     3.9.5
[23:42:42.492904][cli][debug] Streamlink: 3.2.0+279.gc29d58a0
[23:42:42.493845][cli][debug] Dependencies:
[23:42:42.495387][cli][debug]  isodate: 0.6.1
[23:42:42.495864][cli][debug]  lxml: 4.8.0
[23:42:42.496641][cli][debug]  pycountry: 22.3.5
[23:42:42.497071][cli][debug]  pycryptodome: 3.14.1
[23:42:42.497617][cli][debug]  PySocks: 1.7.1
[23:42:42.498124][cli][debug]  requests: 2.27.1
[23:42:42.498624][cli][debug]  websocket-client: 1.3.1
[23:42:42.499078][cli][debug]  importlib-metadata: 4.11.2 …
```
> plugins.trovo: fix VODs

- src/streamlink/plugins/cinergroup.py
- tests/plugins/test_cinergroup.py
fix showtvcomtr and add bloomberg ht
> plugins.cinergroup: rewrite, add bloomberght

- src/streamlink/plugins/dailymotion.py
- tests/plugins/test_dailymotion.py
I want to clean up a couple of simple plugins before preparing the 5.0.0 release.
----
Dailymotion is one of those plugins. Its validation schemas are using the deprecated `validate.text` alias and they are defined as module globals. There are also a couple of issues with how the API error responses are handled. Cleaning it up is therefore very straightforward.
Not sure how relevant the HTTPStream is. I couldn't find any progressive streams, but I kept it, just in case.
Apparently there aren't any live streams on the platform, but since there's a list of "off air" channels, I kept the media ID acquirement for live channels. The old implementation raised a `NoStreamsError` for offline channels. This could be changed, so that a VOD gets returned instead, but I didn't want to change this …
> plugins.dailymotion: rewrite and fix plugin

- src/streamlink/plugins/piczel.py
- tests/plugins/test_piczel.py
Simple plugin rewrite and cleanup, similar to the dailymotion plugin cleanup.
Streams are working fine, won't post any examples.
> plugins.piczel: rewrite

- CHANGELOG.md
Preliminary changelog for the 5.0.0 release.
Release date is set to tomorrow.
> release: 5.0.0

- docs-requirements.txt
Minor bugfix update:
https://github.com/pradyunsg/furo/blob/main/docs/changelog.md
> docs: bump furo theme version to 2022.09.15

- src/streamlink/plugins/hiplayer.py
- tests/plugins/test_hiplayer.py
> plugins.hiplayer: remove cnbcarabia.com

- CHANGELOG.md
Patch release with the release date set for tomorrow.
> release: 5.0.1

- src/streamlink/plugins/raiplay.py
Fixes #4816 
https://github.com/streamlink/streamlink/issues/4816#issuecomment-1257230445
> plugins.raiplay: update and fix plugin

- src/streamlink/plugins/hiplayer.py
Fixes #4857
See https://github.com/streamlink/streamlink/issues/4857#issuecomment-1263998548
----
```
$ streamlink -l debug https://rotana.net/live-clip
[cli][debug] OS:         Linux-5.19.12-1-git-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1+7.gdd7e829d
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  url=https://rotana.net/live-clip
[cli][info] Found matching plugin hiplayer for URL https://rotana.net/live-clip
[plugins.hiplayer][debug] JS …
```
> plugins.hiplayer: fix plugin

- src/streamlink/logger.py
- tests/test_logger.py
> logger: fix trace() module name on py311

- src/streamlink/plugins/tv8.py
closes #4886
```
$ streamlink 'https://www.tv8.com.tr/canli-yayin'
[cli][info] Found matching plugin tv8 for URL https://www.tv8.com.tr/canli-yayin
Available streams: 360p (worst), 480p, 720p, 1080p (best)
```
> plugins.tv8: update stream URL regex

- src/streamlink/plugins/tf1.py
- tests/plugins/test_tf1.py
Resolves #4793 
Closes #4889 
The plugin rewrite includes some of the changes of #4889, so @BZHDeveloper is set as the co-author of this commit.
DASH streams are not needed if HLS streams can always be forced via the IPhone User-Agent header.
----
Geo-block error message:
```
$ streamlink https://www.tf1.fr/tf1/direct best
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugins.tf1][error] Désolé, cette vidéo n'est pas accessible depuis votre zone géographique
error: No playable streams found on this URL: https://www.tf1.fr/tf1/direct
```
Unrestricted content:
```
$ streamlink https://www.tf1.fr/tf1/direct best --http-proxy socks5h://localhost:1920
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[cli][info] Available streams: 234p …
```
> plugins.tf1: rewrite plugin, add "stream" VODs

- .codecov.yml
- .github/workflows/main.yml
> ci.github: add regular Python 3.11 runners

- src/streamlink/plugin/api/websocket.py
- src/streamlink/plugins/ustreamtv.py
- src/streamlink/stream/ffmpegmux.py
- src/streamlink/stream/hls.py
- src/streamlink_cli/main.py
mypy 0.990 has added new warnings and errors which need to be fixed in order to make the CI checks pass
See
https://github.com/streamlink/streamlink/actions/runs/3413199123/jobs/5679637215#step:5:1
> chore: fix new mypy warnings and errors

- docs/developing.rst
Hi. 
In #4923 (464eac5c3daddf2934ff47cc77ce91b30f468dff), I encountered the following error in CI:
```console
$ python -m mypy --no-incremental src/streamlink/ src/streamlink_cli/ tests/ docs/ setup.py
src/streamlink/plugins/niconicochannelplus.py: note: In member "get_master_playlist_url" of class "NicoNicoChannelPlus":
src/streamlink/plugins/niconicochannelplus.py:47:13: error: Need type annotation for "payload" (hint: "payload: Dict[<type>, <type>] = ...")  [var-annotated]
```
I didn't forget to check the code by flake8, but really didn't know to call mypy. To help future developers, I added it to the developing docs.
<br>
At ca4fff1453fbc10dcd583c8a88c922fb7ad16fd1 , I tested mypy 0.990 with Python 3.8.10 and 3.10.4 for Windows, and it only passed when using 3.10:
```console
> python …
```
> docs: add mypy for code linting

- src/streamlink/logger.py
- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls.py
- tests/test_logger.py
> stream.hls: log HLS playlist content while parsing

- docs/ext_plugins.py
- src/streamlink/plugins/twitch.py
- tests/test_plugins.py
See https://github.com/streamlink/streamlink/issues/4934#issuecomment-1312458855
> plugins.twitch: improve plugin notes and arg texts

- src/streamlink_cli/main.py
> cli: fix log format for log level "all"

- src/streamlink/plugins/tv8.py
> plugins.tv8: filter out ad segments

- CHANGELOG.md
> release: 5.1.1

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
- Fix channel ID lookup
- Fix validation schema on missing data
- Add more stream types to live streams: HTTPStream for content restriction clips, and DASHStream where HLS is not available
- Apply minor code refactoring
----
Resolves #4996
I didn't check anything VOD related...
@HappyPlotter could you please test and verify these changes? Thanks.
> plugins.tvp: fix channel ID lookup

- CHANGELOG.md
Release date is set for today. Will merge this later once approved...
This time no mistakes in the changelog :crossed_fingers:
> release: 5.1.2

- src/streamlink/plugins/turkuvaz.py
- tests/plugins/test_turkuvaz.py
I adjusted it to the changed live stream url.
> plugins.turkuvaz: fix url match

- src/streamlink/plugins/vtvgo.py
```
$ streamlink https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
[cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
Available streams: 360p (worst), 480p, 720p (best)
```
closes #5022
> plugins.vtvgo: update headers

- src/streamlink/cache.py
- tests/test_cache.py
- Turn filename into a Path and accept "pathlike" values
- Fix file handle not being closed on error when serializing data
- Add typing information
- Add TO-DO comments
- Rewrite tests
- Switch to pytest
- Use pytests's tmp_path fixture instead of custom temp path stuff
- Properly freeze time during expiration tests
> cache: refactor Cache and rewrite tests

- src/streamlink/plugin/api/websocket.py
- tests/test_api_websocket.py
- Switch to pytest
- Replace custom thread Events with thread handshakes
> tests: refactor websocket tests

- src/streamlink/plugins/dogan.py
- tests/plugins/test_dogan.py
- Update and split up URL matchers
- Use XPath for finding content IDs
- Fix and update API URLs and validation schemas
- Remove nesting and simplify
----
Closes #5052 
The plugin requires a full rewrite and cleanup. The current implementation is pretty old and really, really messy and bad.
@fenopa please check.
The URLs listed in the plugin matcher tests should all work, but it's possible that I missed some URLs not listed in the tests.
```sh
$ echo -e "from tests.plugins.test_dogan import TestPluginCanHandleUrlDogan as test\nfor item in test.should_match: print(item)" \
| python \
| xargs -P1 -n1 streamlink
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/canli-yayin
Available streams: 410k (worst), 570k, 850k, 1100k, 1400k (best)
[cli][info] Found matching plugin …
```
> plugins.dogan: rewrite and fix plugin

- tests/cli/test_cmdline.py
Fix not being able to run `cli/test_cmdline*.py` tests independently.
`subprocess.Popen` can't be mocked as a whole until all plugins get loaded first, otherwise this causes an issue with loading the Crypto module in one of the plugins loaded by the Streamlink session.
----
Btw, these CLI integration tests are in need of a rewrite, but this can be done later.
Failure when running cmdline tests independently:
```
$ pytest tests/cli/test_cmdline.py::TestCommandLinePOSIX::test_open_player_extra_args_in_player
============================================================= test session starts ==============================================================
platform linux -- Python 3.11.1, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/basti/repos/streamlink
plugins: requests-mock-1.10.0, cov-4.0.0, …
```
> tests: fix cmdline tests

- src/streamlink/plugins/mixcloud.py
- tests/plugins/test_mixcloud.py
```
$ streamlink https://www.mixcloud.com/live/UrbanVybez best
[cli][info] Found matching plugin mixcloud for URL https://www.mixcloud.com/live/UrbanVybez
[cli][info] Available streams: 720p (worst, best)
$ streamlink -j 'https://www.mixcloud.com/live/EnjoyableRadio/' | jq .metadata
{
"id": "VXNlcjo0NDc5MzA0MA==",
"author": "Enjoyable Radio",
"title": "'80s REWIND LIVE with Kev, Matt, and Grace : Playing Hits of the Eighties"
}
$ streamlink https://www.mixcloud.com/live/BeachyHeadRadio/
[cli][info] Found matching plugin mixcloud for URL https://www.mixcloud.com/live/BeachyHeadRadio/ …
```
> plugins.mixcloud: new plugin

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
```
$ streamlink --http-proxy ... 'https://www.tvp.info/65275202/13012023-0823' 360p
[cli][info] Found matching plugin tvp for URL https://www.tvp.info/65275202/13012023-0823
[cli][info] Available streams: 224p (worst), 270p, 360p, 450p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 360p (hls)
$ streamlink 'https://www.tvp.info/65275202/13012023-0823'
[cli][info] Found matching plugin tvp for URL https://www.tvp.info/65275202/13012023-0823
[plugins.tvp][error] The content is not available in your region
error: No playable streams found on this URL: https://www.tvp.info/65275202/13012023-0823
$ streamlink 'https://www.tvp.info/'
[cli][info] Found matching …
```
> plugins.tvp: add tvp.info

- src/streamlink/plugins/earthcam.py
```
$ streamlink 'https://www.earthcam.com/events/christmascams/?cam=harborsprings_mi' best
[cli][info] Found matching plugin earthcam for URL https://www.earthcam.com/events/christmascams/?cam=harborsprings_mi
[cli][info] Available streams: 1080p (worst, best)
$ streamlink 'https://www.earthcam.com/events/christmascams/?cam=corning_ny' best
[cli][info] Found matching plugin earthcam for URL https://www.earthcam.com/events/christmascams/?cam=corning_ny
[cli][info] Available streams: 1080p (worst, best)
[cli][info] Stream …
```
> plugins.earthcam: fix cam_name

- CHANGELOG.md
https://github.com/streamlink/streamlink/pull/5116#issue-1553925043
> release: 5.2.1

- src/streamlink/plugins/youtube.py
ref #5137
```
$ streamlink 'https://www.youtube.com/embed/aqz-KE-bpKQ'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/aqz-KE-bpKQ
File "/home/basti/venv/streamlink-311/bin/streamlink", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 933, in main
handle_url()
File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 549, in handle_url
streams = fetch_streams(plugin)
^^^^^^^^^^^^^^^^^^^^^
File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 443, in fetch_streams
return plugin.streams(stream_types=args.stream_types,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/basti/repos/streamlink/src/streamlink/plugin/plugin.py", line …
```
> plugins.youtube: fix adaptive streams KeyError

- src/streamlink/plugins/youtube.py
- tests/plugins/test_youtube.py
https://github.com/streamlink/streamlink/pull/5137#issuecomment-1422597968
```
$ streamlink 'youtube.com/user/Bloomberg'
[cli][info] Found matching plugin youtube for URL youtube.com/user/Bloomberg
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
```
> plugins.youtube: restore /user/... URLs

- src/streamlink/plugins/nimotv.py
Fixes #5114
Add wsSecret and wsTime to the stream url.
> plugins.nimotv: fix livestream stopping after couple of seconds

- src/streamlink_cli/streamrunner.py
Stuff like this will very likely happen more often now with the switch to this new in-development linter until things stabilize.
> chore: fix issues introduced by ruff 0.0.245

- src/streamlink/stream/ffmpegmux.py
- src/streamlink/utils/named_pipe.py
Make sure that each substream's buffer always gets fully emptied when closing the stream, so that no data is missing when muxing the output stream.
TODO: properly refactor FFMPEGMuxer class with full test coverage
----
Fixes #5159 
The second commit fixes another race condition in the `NamedPipePosix` implementation when attempting to close the file descriptor of a broken named pipe where the fifo wouldn't get unlinked in the filesystem.
As mentioned in https://github.com/streamlink/streamlink/issues/5159#issuecomment-1428861109, I will have a look at properly refactoring/rewriting the `FFMPEGMuxer` class some time later.
----
Pipe-copying now ends simultaneously and no data should be missing in the muxed output stream:
```
$ streamlink -l debug -o /tmp/foo.mkv …
```
> stream.ffmpegmux: fix copy-to-pipe race condition

- .git-blame-ignore-revs
> tools: ignore PT refactor commits in git-blame

- src/streamlink/session.py
> session: fix minor mistakes in options docstring

- docs/_static/styles/custom.css
- docs/donate.rst
#5143 
Fixes flexbox stretching on narrow screen sizes
> docs: use grid-cards for team-members

- CHANGELOG.md
> release: 5.3.0

- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_segments_byterange.mpd
- tests/stream/test_dash_parser.py
> stream.dash: fix missing initialization byterange

- src/streamlink/stream/dash_manifest.py
Let's add some basic typing information to the DASH parser. The main motivation of this is having statically typed node attributes and method return values.
This isn't a perfect implementation and there are still some issues left which can be fixed in a future PR:
- constructors are untyped and therefore unchecked
- no proper parent-child type relations (`SegmentTemplate.parent` does have manual typing information because of an ugly hack in its `format_media()` method, which should get rewritten)
- attributes with no parser have the `Any` type instead of `str`, which probably requires overloading typing information of `MPDNode.attr()`
- `MPDNode.walk_back()` has non-ideal return values due to the lack of parent-child type relations
> stream.dash: add basic typing to parser

- src/streamlink/session.py
- tests/test_session.py
> session: fix http-trust-env option

- .editorconfig
SVG is already set here, so let's add XML as well.
> tools: set xml indentation in .editorconfig

- CHANGELOG.md
Will publish later this night (tomorrow)
> release: 5.3.1

- src/streamlink/plugins/tv5monde.py
- tests/plugins/test_tv5monde.py
Fixes #5202 
Don't merge yet. The URLs listed in the tests should be working, but some streams are geo-blocked for me (despite proxies) and the children's site appears to be offline right now during the night (was working earlier).
```sh
for url in $(echo -e "from tests.plugins.test_tv5monde import TestPluginCanHandleUrlTV5Monde as A\nfor a in A.should_match: print(a)" | python); do
echo "$url"
streamlink "$url"
echo
done
```
```
https://live.tv5monde.com/fbs.html
[cli][info] Found matching plugin tv5monde for URL https://live.tv5monde.com/fbs.html
error: Unable to open URL: https://ott.tv5monde.com/Content/HLS/Live/channel(fbs)/variant.m3u8 (403 Client Error: Forbidden for url: https://ott.tv5monde.com/Content/HLS/Live/channel(fbs)/variant.m3u8)
https://europe.tv5monde.com/fr/direct …
```
> plugins.tv5monde: rewrite and fix plugin

- src/streamlink/stream/dash.py
This makes reading the debug log a bit easier while video and audio streams are running
> stream.dash: log mime-type of segment downloads

- src/streamlink/stream/dash_manifest.py
- Convert `isodate.Duration` instances to `datetime.timedelta` in `SegmentTemplate.format_media()` in order to be able to compare with `datetime.datetime` in the timeline generator
- Keep `isodate.Duration` or `datetime.timedelta` instances in `SegmentTemplate.segment_numbers()` before subtracting from `since_start`, as `isodate.Duration()` can't be converted to seconds without a reference `datetime.datetime`
- Replace all `isodate.Duration()` attribute default values with `datetime.timedelta()` for simplicity/performance reasons
- Set the 3 seconds default value of `MPD.suggestedPresentationDelay` on the attribute's default definition instead of using constants in the `SegmentTemplate` methods
> stream.dash: fix suggestedPresentationDelay

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash_parser.py
Motivation of each change in the commit messages...
> stream.dash: refactor

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash_parser.py
Add `available_in` property to `Segment` and add tests
> stream.dash: refactor Segment availability

- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash_parser.py
> stream.dash: fix segment number iterator

- tests/plugins/test_vk.py
Results in a cleaner test summary...
> tests: replace unnecessary xfail marks

- src/streamlink/stream/dash_manifest.py
A bunch of `SegmentList` (and `SegmentTemplate`) fixes. Motivation in each commit message.
Changes are required for implementing `SegmentTimeline` processing in `SegmentList` later on (YouTube live streams with timeshift).
> stream.dash: various SegmentList/SegmentTemplate fixes

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash.py
- tests/stream/test_dash_parser.py
> stream.dash: refactor parser and use base classes

- src/streamlink/plugins/vkplay.py
> plugins.vkplay: fix `category` null

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash.py
- tests/stream/test_dash_parser.py
Fixes #5257 
**master**
> [stream.dash_manifest][debug] Current time: 2023-03-27 11:46:54.734308+00:00
> [stream.dash_manifest][debug] Current time: 2023-03-27 11:46:54.736166+00:00
```
[stream.dash][debug] Opening DASH reader for: ('1', 'video', '1') - video/mp4
[stream.dash][debug] Opening DASH reader for: ('1', 'audio', '1') - audio/mp4
[stream.dash][debug] video/mp4 segment initialization: downloading (2023-03-24T11:49:11.000000Z / 2023-03-27T11:46:54.732777Z)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist: ('1', 'video', '1')
[stream.dash_manifest][debug] Stream start: 2023-03-24 11:49:11+00:00
[stream.dash_manifest][debug] Current time: 2023-03-27 11:46:54.734308+00:00
[stream.dash_manifest][debug] Availability: 2023-03-27 11:46:47+00:00 …
```
> stream.dash: sync timelines of all substreams

- CHANGELOG.md
I'll merge this in the evening today if nothing changes until then. Changelog should be fine, just checked it twice.
https://deploy-preview-5285--streamlink.netlify.app/changelog.html
> release: 5.4.0

- src/streamlink/plugins/dogan.py
Fixes #5297 
The HLS stream URL is read from the `data-url` attribute of the DOM node with the `data-live=true` attribute, so an API query is not needed in this case.
Plugin now finds the correct stream URL on kanald. Other sites are not affected by this change.
```
$ echo -e 'from tests.plugins.test_dogan import TestPluginCanHandleUrlDogan as A\n[print(s) for s in A.should_match]' | python | xargs -n1 -P1 streamlink
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/canli-yayin
Available streams: 410k (worst), 570k, 850k, 1100k, 1400k (best)
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/action/embedvideo/5fa56d065cf3b018a8dd0bbc
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan …
```
> plugins.dogan: find direct HLS URL

- script/test-plugin-urls.py
This adds a useful script for testing whether URLs defined in a plugin's `PluginCanHandleURL` tests are actually still working.
Without such a script, the URLs have to be tested manually, or a custom Python code snippet has to be executed which imports the data from the plugin's test module, and this is always tedious, as the test class name depends on the plugin name.
Since lots of plugins define fake URLs, this script allows adding regexes for ignoring specific URL patterns.
Proxy-data can be set via the `ALL_PROXY` env var. streamlink_cli arguments of any kind won't be parsed. Only a bare session gets initialized.
Example:
```
$ ./script/test-plugin-urls.py --help
usage: test-plugin-urls.py [-h] [-l LEVEL] [--color WHEN] [-n] [-i REGEX] plugin
positional arguments:
plugin …
```
> script: implement plugin URL tester

- .github/ISSUE_TEMPLATE/1_plugin_issue.yml
- .github/ISSUE_TEMPLATE/2_bug_report.yml
- .github/ISSUE_TEMPLATE/3_plugin_request.yml
- .github/ISSUE_TEMPLATE/4_feature_request.yml
- CONTRIBUTING.md
Probably a bit too much for someone who's got no idea about Python stuff, but at least this should solve the confusion about pull request feedback...
> docs: add pull request feedback to CONTRIBUTING.md

- src/streamlink/stream/hls.py
- tests/mixins/stream_hls.py
- tests/stream/test_hls.py
Make `HLSStreamWorker` reload the playlist in strict time intervals instead of just queuing the next playlist reload.
Previously, playlist fetch time and segment processing time always added to the overall reload time, resulting in an eventual shift of the expected reload time, which could lead to an empty segment queue in certain scenarios (live-edge=1 or Twitch low latency streaming).
When the reload time exceeds the expected reload interval, continue with the shifted interval, which matches the old behavior.
----
Resolves #4646 
> When the reload time exceeds the expected reload interval, continue with the shifted interval, which matches the old behavior.
That could be changed, so that if a playlist reload takes too long, the next one could start immediately. I am not sure though if …
> stream.hls: reload playlist in strict intervals

- CHANGELOG.md
Patch release required for #5332
> release: 5.5.1

- src/streamlink/stream/dash.py
- tests/stream/test_dash.py
Add `with_{video,audio}_only` params to `DASHStream.parse_manifest()` which allow video-only or audio-only streams to be included in the returned streams dict. Both parameters default to false, so only muxed streams with video and audio get returned, just like before.
This is a temporary workaround until a proper stream selection mechanism gets implemented at some point in the future.
----
Ref #5339 
I decided to add the `with_` prefix to both parameters, because it makes the intention clearer. Without the prefix, this would imply that muxed streams are not included in the returned streams dict.
```
$ streamlink 'dash://file://./tests/resources/dash/test_timeline_ids.mpd'
[cli][info] Found matching plugin dash for URL dash://file://./tests/resources/dash/test_timeline_ids.mpd
Available …
```
> stream.dash: optional video/audio-only streams

- tests/cli/utils/test_versioncheck.py
- Fix incorrect `called_once` assertion of the `cache` fixture
- Refactor `pypi` and `cache` fixtures
----
py312 revealed that these tests were broken.
There are more broken tests which I will fix later. Most of them are related to the incorrect and now invalid usage of `Mock().called_once`
https://github.com/python/cpython/commit/1d4d677d1c90fcf4886ded0bf04b8f9d5b60b909
and some changes in regards to the `pathlib` module (haven't figured that out yet)
> tests: fix CLI versioncheck tests

- tests/test_streamlink_api.py
> tests: refactor Streamlink API tests

- tests/plugins/test_twitch.py
Follow-up of #5357 
Motivation of course is the switch from unittest to pytest with the existing session and requests_mock fixtures, as well as the caplog fixture. In case of the session, this avoids unnecessarily loading all builtin plugins.
> tests.plugins: refactor some Twitch tests

- tests/test_plugins.py
> tests: require test cases for protocol plugins

- src/streamlink/plugins/pluzz.py
- tests/plugins/test_pluzz.py
Fixes #5355 
```
$ HTTPS_PROXY=socks5h://localhost:1920 python ./script/test-plugin-urls.py pluzz
:: Finding streams for URL: https://france3-regions.francetvinfo.fr/bourgogne-franche-comte/direct/franche-comte
:: Found streams: 216p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://la1ere.francetvinfo.fr/info-en-continu-24-24
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://la1ere.francetvinfo.fr/programme-video/france-3_outremer-ledoc/diffusion/2958951-polynesie-les-sages-de-l-ocean.html
:: Found streams: 216p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://www.france.tv/france-2/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: …
```
> plugins.pluzz: fix magneto player XPath query

- src/streamlink/plugins/turkuvaz.py
- tests/plugins/test_turkuvaz.py
```
$ script/test-plugin-urls.py turkuvaz
:: Finding streams for URL: https://vavtv.com.tr/canli-yayin
:: Found streams: 240p, 360p, 480p, 720p, worst, best
:: Finding streams for URL: https://vavtv.com.tr/vavradyo/video/guncel/munafiklarin-ozellikleri-nelerdir
:: Found streams: 720p, worst, best
:: Finding streams for URL: https://www.ahaber.com.tr/canli-yayin-a2tv.html
:: Found streams: 240p, 360p, 480p, 720p, worst, best
:: Finding streams for URL: https://www.ahaber.com.tr/canli-yayin-anews.html
:: Found streams: 240p, 360p, 480p, 720p, worst, best
:: Finding streams for URL: https://www.ahaber.com.tr/canli-yayin-aspor.html
:: Found streams: 240p, 360p, 480p, 864p, worst, best
:: Finding streams for URL: https://www.ahaber.com.tr/canli-yayin-atv.html
:: Found streams: 288p, 432p, …
```
> plugins.turkuvaz: fix/partial rewrite

- src/streamlink/plugins/showroom.py
Closes #5389 
@CplSgt82 please check and see if this fixes the issue.
> plugins.showroom: fix room-id schema

- script/install-dependencies.sh
Fixes the tests segfaulting on Python 3.12
https://github.com/streamlink/streamlink/actions/runs/5340135736/jobs/9679591404#step:5:73
> ci: update custom lxml cp312 wheel

- docs/donate.rst
low-effort PR which updates the list of team members
> docs: inactive/former team members

- src/streamlink/plugins/nrk.py
Fixes #5407 
100% unsure whether this fixes #5407, because they detect my VPN, so I can't see the API responses.
This PR refactors the plugin and simply removes the stream metadata and adds a region check.
@werid please validate these changes.
----
Test URLs are unmodified and the failing ones are probably outdated...
```
$ ./script/test-plugin-urls.py nrk
:: Finding streams for URL: https://radio.nrk.no/direkte/p1
:: Found streams: 32k, 130k, worst, best
:: Finding streams for URL: https://radio.nrk.no/direkte/p2
:: Found streams: 32k, 130k, worst, best
:: Finding streams for URL: https://radio.nrk.no/podkast/oppdatert/l_5005d62a-7f4f-4581-85d6-2a7f4f2581f2
:: Found streams: live, worst, best
:: …
```
> plugins.nrk: remove metadata, add region check

- src/streamlink_cli/utils/player.py
Slipped through #5310 because I didn't rebase to master before merging the branch. There were linting config changes on master.
> cli.utils: fix E225 linting error

- src/streamlink/plugin/plugin.py
- tests/test_plugin.py
#5401 
https://streamlink.github.io/deprecations.html#deprecation-of-plugin-init-self-url
> plugin: drop deprecated Plugin constructor wrapper

- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- tests/test_session.py
#5401 
https://streamlink.github.io/deprecations.html#plugin-can-handle-url-and-plugin-priority
> plugin: drop deprecated can_handle_url / priority

- docs/api/webbrowser.rst
- src/streamlink/webbrowser/cdp/connection.py
As an addition to #5380 / #5410
> webbrowser.cdp: add CDP connection docs

- src/streamlink/webbrowser/cdp/connection.py
Don't perform potentially expensive string formatting when we're not even logging the message.
> webbrowser.cdp: replace f-string w/ LogRecord args

- setup.cfg
https://github.com/streamlink/streamlink/pull/5414#issuecomment-1626043404
https://github.com/python/typing_extensions/blob/main/CHANGELOG.md
> build: set min-version of typing-extensions

- src/streamlink/plugins/rtvs.py
- tests/plugins/test_rtvs.py
Fixes #5442 
```
$ ./script/test-plugin-urls.py rtvs
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-1
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-2
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-3
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-nr-sr
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-o
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.rtvs.sk/televizia/live-rtvs
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams …
```
> plugins.rtvs: fix plugin

- src/streamlink/plugins/lrt.py
Fixes #5441
```
$ ./script/test-plugin-urls.py lrt
:: Finding streams for URL: https://www.lrt.lt/mediateka/tiesiogiai/lrt-klasika
:: Found streams: 540p_alt2, 540p_alt, 540p, 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica
:: Found streams: 540p_alt2, 540p_alt, 540p, 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.lrt.lt/mediateka/tiesiogiai/lrt-opus
:: Found streams: 540p_alt2, 540p_alt, 540p, 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.lrt.lt/mediateka/tiesiogiai/lrt-plius
:: Found streams: 540p_alt, 540p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: …
```
> plugins.lrt: fix plugin

- docs/cli/config.rst
- docs/cli/plugin-sideloading.rst
Also fixes an example with the old `--player` stuff
> docs: improve config-file + plugin sideloading

- CHANGELOG.md
> release: 6.0.1

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
- Fix options regex
- parse all alphanumerical options with dashes
- be more strict around the option-value operator and properly ignore invalid option formats, just like comments
- Fix parsing of shorthand options
- Add tests
----
Fixes #5481 
Option names containing numbers now get properly parsed.
This also fixes the parsing of shorthand options in config files, so something like this works now
```
l debug
```
This also fixes options with empty values
```
title=
```
And invalid option formats now get properly ignored, just like comments, so
```
non_matching_option
```
won't result in `--non=_matching_option` being returned anymore
> cli.argparser: fix config file args parser

- src/streamlink/plugins/atresplayer.py
- tests/plugins/test_atresplayer.py
Fixes #5131
Fix atresplayer plugin, which broke recently (presumably due to site changes)
> plugins.atresplayer: fix player API URL

- docs/_static/styles/custom.css
- docs/install.rst
Please see the docs preview...
https://deploy-preview-5492--streamlink.netlify.app/install
Adding `title` HTML attributes would be great, but I don't know if this can be done in inline rst elements.
> docs: add icons to packages and install methods

- src/streamlink/stream/dash.py
- src/streamlink/stream/segmented.py
- tests/mixins/stream_hls.py
- tests/stream/test_hls.py
Some basic/trivial changes which should be done before attempting to resolve #5498.
Opening this as a draft, as I'm not sure if more is needed... Will update once I've had the time for another look in the next couple of days or so...
> stream.segmented: basic code refactoring

- src/streamlink/plugins/piaulizaportal.py
- tests/plugins/test_piaulizaportal.py
This is a very simple extractor for video platform "[ULIZA](https://uliza.jp)" operated by the [PIA Corporation](https://corporate.pia.jp/).
Tickets purchased at "[PIA LIVE STREAM](https://t.pia.jp/streaming)" are used for "ULIZA".
There are two public videos:
- [プレゼンテーションプレイヤーのサンプル](https://ulizaportal.jp/pages/005f18b7-e810-5618-cb82-0987c5755d44): A video for testing functionality (with delicious food).
- [【確認用】視聴サンプルページ（ULIZA）](https://ulizaportal.jp/pages/005e1b23-fe93-5780-19a0-98e917cc4b7d?expires=4102412400&signature=f422a993b683e1068f946caf406d211c17d1ef17da8bef3df4a519502155aa91&version=1): A video for testing device and network.
The first one works well with this plugin; the second one, however, makes VLC player end **immediately**.
M3U8 playlists and logs are as follows: …
> plugins.piaulizaportal: new plugin

- docs/cli/metadata.rst
Follow-up of #5516 and #5517 
https://deploy-preview-5519--streamlink.netlify.app/cli/metadata
> docs: rewrite metadata page

- src/streamlink/plugins/twitch.py
- src/streamlink/stream/hls_playlist.py
Store the parser state in dedicated attributes with proper typing information instead of using a state hash map with arbitrary keys.
----
This was never changed since the initial implementation in 39008e9, probably because of the convenience of being able to read and unset certain data in a single call via `pop()`. That however doesn't justify the CPU and memory disadvantanges that come with this design choice, so let's finally fix it.
> stream.hls: refactor M3U8Parser state attributes

- docs-requirements.txt
https://github.com/pradyunsg/furo/blob/main/docs/changelog.md
> docs: bump furo theme version to 2023.09.10

- .github/ISSUE_TEMPLATE/1_plugin_issue.yml
- .github/ISSUE_TEMPLATE/2_bug_report.yml
This refines what I had intended with #5489
> chore: clarify version string req. in issues

- script/build-and-sign.sh
- Refactor build script
- Retrieve version string via the `versioningit` module
- Fix the `build` command of the `win32` and `win-amd64` wheels (with the `streamlinkw` gui_scripts entry-points) by adding a workaround that's needed since `build>=1.0.0`
----
Resolves #5548 
master: 4b1e1298
pr: 9b0ed496
```sh
$ diff -s \
<(bsdtar -xOf dist/streamlink-6.1.0+28.g4b1e1298-py3-none-any.whl streamlink-6.1.0+28.g4b1e1298.dist-info/entry_points.txt) \
<(bsdtar -xOf dist/streamlink-6.1.0+29.g9b0ed496-py3-none-any.whl streamlink-6.1.0+29.g9b0ed496.dist-info/entry_points.txt)
Files /dev/fd/63 and /dev/fd/62 are identical
$ diff -s \
<(bsdtar -xOf dist/streamlink-6.1.0+28.g4b1e1298-py3-none-win32.whl streamlink-6.1.0+28.g4b1e1298.dist-info/entry_points.txt) \
<(bsdtar -xOf …
```
> build: fix build-and-sign script

- src/streamlink/plugins/goodgame.py
- tests/plugins/test_goodgame.py
Fixes #5556 
This rewrite doesn't include the old "DDOS protection" workaround, which accessed the site once, checked for `document.cookie="..."` and set the cookie before accessing it again. No idea if it's still required, but it doesn't seem like it is. As said, the current plugin implementation on master is really old.
@StasYong, please check if there are any problems left, thanks
----
live
```
$ streamlink 'https://goodgame.ru/channel/Nikichar' best
[cli][info] Found matching plugin goodgame for URL https://goodgame.ru/channel/Nikichar
[cli][info] Available streams: 240p (worst), 480p, 720p, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] …
```
> plugins.goodgame: rewrite and fix plugin

- src/streamlink/plugins/wwenetwork.py
- tests/plugins/test_wwenetwork.py
closes #5503
before changes:
```
[cli][debug] OS:         macOS 13.4
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.1.2 1 Aug 2023
[cli][debug] Streamlink: 6.2.0
[cli][debug]  certifi: 2023.7.22
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.4
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.3
[cli][debug]  url=https://network.wwe.com/video/495654/money-in-the-bank-2023
[cli][debug] …
```
> plugins.wwenetwork: new api layout

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Fixes #5590 
```
$ streamlink twitch.tv/smoke
[cli][info] Found matching plugin twitch for URL twitch.tv/smoke
Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
$ streamlink twitch.tv/primevideo
[cli][info] Found matching plugin twitch for URL twitch.tv/primevideo
[plugins.twitch][error] Content Restricted In Region
error: No playable streams found on this URL: twitch.tv/primevideo
```
I'd appreciate it if someone could test this where the content is actually available. It's blocked when I access it with my local German IP address, and it's also blocked with all the VPNs I've tried.
Btw, the geo-restriction could also be checked here:
https://github.com/streamlink/streamlink/blob/6.2.1/src/streamlink/plugins/twitch.py#L270
But I felt like checking on the HLS …
> plugins.twitch: fix HLS multivariant errors

- src/streamlink/plugins/goodgame.py
Some streamers have a different player ID than the channel ID.
```
streamlink -l trace goodgame.ru/channel/miker
[14:55:00.212898][session][debug] Plugin goodgame is being overridden by /home/*/.local/share/streamlink/plugins/goodgame.py
[14:55:00.231627][cli][debug] OS:         Linux-5.4.0-139-generic-x86_64-with-glibc2.31
[14:55:00.231865][cli][debug] Python:     3.9.5
[14:55:00.231977][cli][debug] OpenSSL:    OpenSSL 1.1.1f  31 Mar 2020
[14:55:00.232092][cli][debug] Streamlink: 6.2.1
[14:55:00.232995][cli][debug] Dependencies:
[14:55:00.235118][cli][debug]  certifi: 2023.7.22
[14:55:00.236184][cli][debug]  isodate: 0.6.0
[14:55:00.237114][cli][debug]  lxml: 4.7.1
[14:55:00.238251][cli][debug]  pycountry: 22.1.10
[14:55:00.239149][cli][debug]  pycryptodome: 3.9.9 …
```
> plugins.goodgame: fix plugin

- docs/install.rst
- https://packages.debian.org/bookworm-backports/streamlink
- https://wiki.debian.org/DebianReleases#Production_Releases
> docs: upd Debian stable from bullseye to bookworm

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_suggested_presentation_delay.mpd
- tests/stream/dash/test_manifest.py
> stream.dash: respect the manifest's minBufferTime 

- src/streamlink/plugins/dlive.py
> plugins.dlive: fix live streams

- src/streamlink/plugins/dlive.py
- tests/plugins/test_dlive.py
Follow-up of #5622 
matchers
```
$ ./script/test-plugin-urls.py dlive
:: Finding streams for URL: https://dlive.tv/cryptokaprika
:: Found streams: src, worst, best
:: Finding streams for URL: https://dlive.tv/cryptokaprika#hash
:: Found streams: src, worst, best
:: Finding streams for URL: https://dlive.tv/cryptokaprika?query
:: Found streams: src, worst, best
:: Finding streams for URL: https://dlive.tv/p/countrycafebgky+oLCFcknSR
:: Found streams: src, worst, best
:: Finding streams for URL: https://dlive.tv/p/countrycafebgky+oLCFcknSR#hash
:: Found streams: src, worst, best
:: Finding streams for URL: https://dlive.tv/p/countrycafebgky+oLCFcknSR?query
:: Found streams: src, worst, best
```
live (correct HLS stream segments with Referer header)
```
$ streamlink -l debug …
```
> plugins.dlive: rewrite and fix VODs

- src/streamlink/plugins/mitele.py
Mitele has changed gbx version from v2 to v3
> plugins.mitele: update to gbx v3

- CHANGELOG.md
https://deploy-preview-5634--streamlink.netlify.app/changelog
> release: 6.3.0

- src/streamlink/plugins/welt.py
- tests/plugins/test_welt.py
```
$ ./script/test-plugin-urls.py welt
:: Finding streams for URL: https://welt.de/tv-programm-live-stream/
:: Found streams: 360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung192055593/Strip-the-Cosmos-Die-Megastuerme-der-Planeten.html
:: Found streams: 200k, 1000k, 1500k, 2000k, worst, best
:: Finding streams for URL: https://www.welt.de/mediathek/magazin/gesellschaft/sendung247758214/Die-Welt-am-Wochenende-Auf-hoher-See-mit-der-Gorch-Fock.html
:: Found streams: 700k, 1200k, 2400k, 4800k, worst, best
:: Finding streams for URL: https://www.welt.de/tv-programm-live-stream/
:: Found streams: 360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, …
```
> plugins.welt: rewrite and fix plugin

- CHANGELOG.md
> release: 6.3.1

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
Fixes #5575
```
$ ./script/test-plugin-urls.py tvp
:: Finding streams for URL: https://stream.tvp.pl
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://stream.tvp.pl/
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://stream.tvp.pl/?channel_id=14812849
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://stream.tvp.pl/?channel_id=63759349
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://tvpstream.vod.tvp.pl
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://tvpstream.vod.tvp.pl/
:: Found streams: 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: …
```
> plugins.tvp: fix tvp.info

- src/streamlink/plugins/telemadrid.py
Fix broken XPath in Telemadrid plugin
> plugins.telemadrid: fix xpath

- docs/api/validate.rst
- docs/api_guide.rst
- docs/api_guide/validate.rst
> docs: add plugin.api.validate API guide

- src/streamlink/stream/dash/manifest.py
- tests/stream/dash/test_manifest.py
https://github.com/streamlink/streamlink/pull/5654#discussion_r1386625072
> stream.dash: add init keyword to segments()

- src/streamlink/plugins/raiplay.py
- tests/plugins/test_raiplay.py
Hi, 
I've added support for on-demand videos that require authentication.
The implementation of the authentication system is quite naive, but I hope it's sufficient.
> plugin.raiplay:  add vod support

- src/streamlink/plugins/youtube.py
Fixes #5672 
@cgomesu please check
```
$ streamlink https://www.youtube.com/@ABCNews
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/@ABCNews
Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p (best)
$ streamlink https://www.youtube.com/@ABCNews/live
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/@ABCNews/live
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
$ streamlink https://www.youtube.com/user/ABCNews
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/ABCNews
Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p (best)
$ streamlink …
```
> plugins.youtube: fix video ID retrieval

- CHANGELOG.md
https://deploy-preview-5676--streamlink.netlify.app/changelog
> release: 6.4.0

- src/streamlink/plugins/ssh101.py
> plugins.ssh101: fix plugin

- docs/api.rst
- docs/api/cache.rst
- src/streamlink/cache.py
- src/streamlink/plugin/plugin.py
- https://deploy-preview-5688--streamlink.netlify.app/api/cache
- https://deploy-preview-5688--streamlink.netlify.app/api/plugin#streamlink.plugin.Plugin.cache
> docs: add cache API docs and add Plugin.cache ref

- src/streamlink/plugins/bilibili.py
Fixes #5692 
@hack11112 please check the plugin
As mentioned, no high quality streams available, because they require a login, and I don't have access to an account
----
```
$ streamlink --json https://live.bilibili.com/10129169 | jq .metadata
{
"id": "432478849957793540",
"author": "卡比同学",
"category": "CS:GO",
"title": "B站最纯真的直播间"
}
```
```
$ streamlink -l debug https://live.bilibili.com/10129169 best
[cli][debug] OS:         Linux-6.6.2-1-git-x86_64-with-glibc2.38
[cli][debug] Python:     3.12.0
[cli][debug] OpenSSL:    OpenSSL 3.1.4 24 Oct 2023
[cli][debug] Streamlink: 6.4.1+7.gbcbc32a3
[cli][debug]  certifi: 2023.11.17
[cli][debug]  lxml: …
```
> plugins.bilibili: rewrite and fix plugin

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
- Remove rerun check and disable --twitch-disable-reruns plugin argument
- Implement a new `_check_is_live()` which checks the channel and stream status, based on the previously used `StreamMetadata` GQL query
- Update tests
----
Fixes #5703 
Resolves #5656
Twitch doesn't list this in their API changelog, but reruns were removed some time ago, and streamers can't use VODs anymore to go live automatically. This means that the `--twitch-disable-reruns` plugin argument and the API check it did has to be removed.
In #5703 I initially commented about a different GQL query, but the old `StreamMetadata` query previously used by the rerun check can be reused here, as it returns the same data, in addition to more data we don't care about.
----
Quick test:
**unknown channel**
```
$ streamlink …
```
> plugins.twitch: drop --twitch-disable-reruns

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Follow-up of #5708
Improves #5591
No more unnecessary error log messages for offline channels (`twirp error not_found: transcode does not exist`).
Error log messages for geo-blocked content or other kinds of errors are kept.
----
Online
```
$ streamlink twitch.tv/shroud
[cli][info] Found matching plugin twitch for URL twitch.tv/shroud
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
```
Offline
```
$ streamlink twitch.tv/lirik
[cli][info] Found matching plugin twitch for URL twitch.tv/lirik
error: No playable streams found on this URL: twitch.tv/lirik
```
Offline (corrupt data on Twitch's end)
```
$ streamlink twitch.tv/paymoneywubby
[cli][info] Found matching plugin twitch for URL twitch.tv/paymoneywubby
error: No playable streams found on this URL: …
```
> plugins.twitch: only log errors if channel is live

- src/streamlink/plugins/gulli.py
- tests/plugins/test_gulli.py
Fixes #5724 
@gkovacsp if you want, please give these changes a try and report back if anything is not working. Thanks. Instructions here:
```
$ HTTPS_PROXY=socks5h://localhost:1920 ./script/test-plugin-urls.py gulli
:: Finding streams for URL: https://replay.gulli.fr/Direct
:: Found streams: 224p, 360p, 404p, 540p, worst, best
:: Finding streams for URL: https://replay.gulli.fr/dessins-animes/Bob-l-eponge-s10/bob-l-eponge-s10-e05-un-bon-gros-dodo-vod69736581475000
:: Found streams: 404p, worst, best
:: Finding streams for URL: https://replay.gulli.fr/emissions/Animaux-VIP-une-bete-de-reno-s02/animaux-vip-une-bete-de-reno-s02-e09-la-taniere-du-dragon-vod69634261609000
:: Found streams: 404p, worst, …
```
> plugins.gulli: rewrite and fix plugin

- src/streamlink/plugins/zattoo.py
> plugins.zattoo: force FFmpeg copyts

- src/streamlink_cli/output/player.py
> cli: improve quoted player path warning

- src/streamlink/plugins/artetv.py
- tests/plugins/test_artetv.py
Resolves #5773 
More plugin changes than adding `API_HLS_NG` were required. This PR also fixes some other plugin implementation issues.
@Firmeware please check and see if any streams are not working with this plugin version:
I only checked the live streams and a couple of VODs, but I'm not fully sure if I missed something. The API authorization token was removed, because it was not set in my web browser. I don't know why it was set in the plugin previously, but it's possible that some content might require it.
https://github.com/streamlink/streamlink/blame/6.5.0/src/streamlink/plugins/artetv.py#L31
```
$ ./script/test-plugin-urls.py artetv
:: Finding streams for URL: https://www.arte.tv/de/live
:: …
```
> plugins.artetv: rewrite and fix plugin

- CHANGELOG.md
https://deploy-preview-5777--streamlink.netlify.app/changelog
> release: 6.5.1

- src/streamlink/plugins/twitch.py
This can already be merged into master. Currently included as the first commit of #5793
> plugins: replace pluginargument help f-strings

- dev-requirements.txt
- pyproject.toml
- https://github.com/astral-sh/ruff/blob/v0.2.0/CHANGELOG.md
- https://astral.sh/blog/ruff-v0.2.0
> tools: bump ruff to 0.2.0 and update config

- docs/deprecations.rst
- src/streamlink/session/session.py
#5807
#5814
https://deploy-preview-5818--streamlink.netlify.app/deprecations
> docs: add 6.6.0 deprecations

- src/streamlink/options.py
- tests/test_options.py
ac45740
----
Should've been included in #5815... I thought it wasn't needed, but it is, so this fixes it.
> options: compare equality of Arguments objects

- src/streamlink/stream/hls/hls.py
change to make substreams of MuxedHLSStream be created as inherited class.
https://github.com/streamlink/streamlink/discussions/5833
> stream.hls: add hlsstream keyword to MuxedHLSStream

- docs/ext_argparse.py
- src/streamlink/options.py
- src/streamlink/session/plugins.py
- tests/session/test_plugins.py
- tests/test_options.py
> Fix plugin arguments docs / man page / help text

- dev-requirements.txt
- pyproject.toml
- tests/cli/output/test_player.py
- tests/cli/utils/test_player.py
- tests/plugins/test_wwenetwork.py
- tests/utils/test_path.py
https://github.com/astral-sh/ruff/releases/tag/v0.2.2
> tools: bump ruff to 0.2.2 and fix issues

- CHANGELOG.md
https://deploy-preview-5851--streamlink.netlify.app/changelog
> release: 6.6.2

- pyproject.toml
https://github.com/dateutil/dateutil/blob/2.9.0.post0/NEWS#L30-L33
Added in #5747
> tests: remove unneeded dateutil warning filter

- CHANGELOG.md
No 6.6.6 release :disappointed:
> release: 6.7.0

- tests/cli/test_cmdline.py
> tests: reset root logger level in cmdline tests

- src/streamlink/plugins/vimeo.py
Follow-up of #5892
This marks all `url` attributes in the validation schema as optional. Probably only necessary for HLS and DASH stream URLs, but I added it to progressive HTTP streams and subtitle URLs as well. Doesn't hurt...
master
```
$ streamlink https://vimeo.com/event/4154130/embed
[cli][info] Found matching plugin vimeo for URL https://vimeo.com/event/4154130/embed
error: Unable to validate result: ValidationError(dict):
Unable to validate value of key 'request'
Context(dict):
Unable to validate value of key 'files'
Context(dict):
Unable to validate value of key 'hls'
Context(dict):
Unable to validate value of key 'cdns'
Context(dict):
Unable to validate value
Context(dict):
Key 'url' not found in {'origin': 'studio'}
```
PR
```
$ streamlink https://vimeo.com/event/4154130/embed …
```
> plugins.vimeo: fix offline event streams

- src/streamlink/plugins/vkplay.py
- tests/plugins/test_vkplay.py
Fixes #5907 
```
$ ./script/test-plugin-urls.py vkplay -r CHANNEL resf
:: Finding streams for URL: https://live.vkplay.ru/resf
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://vkplay.live/resf
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
```
> plugins.vkplay: update matcher and API URL

- src/streamlink/plugins/mangomolo.py
- tests/plugins/test_mangomolo.py
> plugins.mangomolo: fix media.gov.kw matcher

- src/streamlink/plugins/twitch.py
- src/streamlink/webbrowser/webbrowser.py
- tests/webbrowser/test_webbrowser.py
- Fix `KeyboardInterrupt`/`SystemExit` exceptions not being propagated in nested `ExceptionGroup`s
- Fix compatibility with `exceptiongroup<=1.1.1` by avoiding their `catch()` context manager
- Add missing test for (re-)raising different exception types
----
Fixes #5929 
1. `exceptiongroup>=1.1.2` fixed their incorrect behavior of raising an `ExceptionGroup` when raising non-group-exceptions in the callback function passed to their `catch()` context manager:
https://github.com/agronholm/exceptiongroup/blob/1.1.2/CHANGES.rst
Due to this change, we can't use the `catch()` context manager anymore and we need to catch all `BaseExceptionGroup`s instead and get a sub-group of the exceptions we're looking for.
2. Instead of re-raising the first exception of the matching group, we're now …
> webbrowser: fix propagation of BaseException

- src/streamlink/plugins/turkuvaz.py
- tests/plugins/test_turkuvaz.py
Fixes #5945 
Despite their API being fully functional when requesting HLS URLs for specific live streams (video-id + website-id), some HLS URLs apparently are hardcoded (in some terrible JS code) and point to a different CDN. The HLS URLs from their API response still work, but the HLS segments don't return any data.
No idea if the list of hardcoded HLS URLs is complete or not. I've included the link to the JS file in the comments.
```
$ streamlink -l debug https://www.minikacocuk.com.tr/webtv/canli-yayin best
[cli][debug] OS:         Linux-6.8.6-1-git-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.2
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 6.7.3+1.g30fa7bf3
[cli][debug]  certifi: 2024.2.2
[cli][debug]  exceptiongroup: …
```
> plugins.turkuvaz: add HLS URL mapping

- .github/ISSUE_TEMPLATE/1_plugin_issue.yml
Ref https://github.com/streamlink/streamlink/pull/5947#issuecomment-2059732166
> chore: update plugin issue template

- build_backend/plugins_json.py
> build: fix encoding when reading plugin files

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Resolves #6015 
Before this can be merged, a couple more tests with live data is needed...
> plugins.twitch: fix ad/discontinuity handling

- src/streamlink/plugins/kick.py
- tests/plugins/test_kick.py
Resolves #6010 
No idea about any potential issues with the stream metadata or with the HLS streams themselves. Didn't check much... Category metadata is not implemented for VODs...
```
$ ./script/test-plugin-urls.py kick -r LIVE_CHANNEL nickmercs -r VIDEO_ID 8bc87173-22f7-493e-a6a8-1ef5d11be9fa -r CLIP_CHANNEL admiralbulldog -r CLIP_ID clip_01HSNHF69RPPR9JX0VQ6WM2YVC
:: Finding streams for URL: https://kick.com/admiralbulldog?clip=clip_01HSNHF69RPPR9JX0VQ6WM2YVC
:: Found streams: clip, worst, best
:: Finding streams for URL: https://kick.com/nickmercs
:: Found streams: 160p, 360p, 480p, 720p60, 1080p60, worst, best
:: Finding streams for URL: https://kick.com/video/8bc87173-22f7-493e-a6a8-1ef5d11be9fa
:: Found streams: 160p, 360p, 480p, 720p60, 1080p60, worst, best
```
```
$ streamlink …
```
> plugins.kick: new plugin

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
This apparently broke ad detection in prefetch segments in some cases. I've tested it yesterday on a couple of streams, but didn't notice any issues.
https://github.com/streamlink/streamlink/issues/6015#issuecomment-2145853480
Going to revert the changes now...
> revert: plugins.twitch: fix ad/discontinuity handling

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
Resolves #6036
@Antuanx Most content is geo-blocked, so please check and verify the plugin changes.
```
$ ./script/test-plugin-urls.py tvp
:: Finding streams for URL: https://stream.tvp.pl
:::: The content is not available in your region
:: Finding streams for URL: https://stream.tvp.pl/
:::: The content is not available in your region
:: Finding streams for URL: https://stream.tvp.pl/?channel_id=1455
:::: The content is not available in your region
:: Finding streams for URL: https://stream.tvp.pl/?channel_id=51656487
:: Found streams: 288p_dash, 396p_dash, 576p_dash, 720p_dash, 1080p_dash, 250k, 288p, 396p, 576p, 720p, 1080p, worst, best …
```
> plugins.tvp: get live streams from API

- CHANGELOG.md
https://deploy-preview-6039--streamlink.netlify.app/changelog
> release: 6.8.0

- tests/conftest.py
- tests/session/test_http.py
> tests: test HTTPAdapters on all python versions

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
This logs Twitch's ad breaks and their respective durations, which is especially useful if `--twitch-disable-ads` is set, so users will know how long the output will be paused for.
Everyone's invited to give this a test:
----
This implementation caches the ad-break's `X-TV-TWITCH-AD-COMMERCIAL-ID` metadata in order to avoid logging multiple parts of the same ad break. This is because multiple `EXT-X-DATERANGE` tags can be inserted into the HLS playlists one after another, e.g. when multiple "ad-break-in-progress" placeholder loops are being shown in a row, or distinct "actual ads" are shown if enabled via `--twitch-access-token-param=playerType=web` (we default to "embed" so we only see the …
> plugins.twitch: log ad breaks with duration

- src/streamlink/plugins/huya.py
Resolves #5487
test url: https://www.huya.com/majiajia
`python.exe -m src.streamlink_cli -j https://www.huya.com/majiajia `
```
{
"plugin": "huya",
"metadata": {
"id": "7386883739648295431",
"author": "\u5fae\u7ade\u4e36\u838e\u8389",
"title": ""
},
"streams": {
"al_500": {
"type": "http",
"method": "GET",
"url": "http://al.flv.huya.com/src/813535483-813535483-3494108293620563968-1627194422-10057-A-0-1-imgplus.flv?wsSecret=91d3e6752a2cb8460f43d740d6a96a3b&wsTime=6683bf16&ctype=huya_live&fs=bgct&seqid=1719922522577&ver=1&u=3161081088&t=100&sv=2401090219&sdk_sid=1719910174604&codec=264&ratio=500",
"headers": {
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
"Accept-Encoding": "gzip, deflate",
"Accept": "*/*",
"Connection": …
```
> plugins.huya: fix 403 error

- src/streamlink/plugins/douyin.py
- tests/plugins/test_douyin.py
Resolves #6062
cookies are necessary
test url : https://live.douyin.com/774321108336
`python.exe -m src.streamlink_cli -j https://live.douyin.com/774321108336 --http-cookie __ac_nonce=xxx --http-cookie __ac_signature=xxx --http-cookie sessionid=xxx`
```json
{
"plugin": "douyin",
"metadata": {
"id": "7386955391675960064",
"author": "\u5927\u65d7\u672c\u4eba",
"title": "\u6296\u97f35\u5e74\u7ecf\u9a8c\u90fd\u5728\u8fd9\u4e86"
},
"streams": {
"ao": {
"type": "http",
"method": "GET",
"url": "http://pull-l3.douyincdn.com/third/stream-691881931476828639.flv?auth_key=1720514018-0-0-0184ef050d0c0ace125c665b29be2bb3&only_audio=1",
"headers": {
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
"Accept-Encoding": "gzip, deflate", …
```
> plugins.douyin: new plugin

- CHANGELOG.md
Going to publish this later today...
https://deploy-preview-6064--streamlink.netlify.app/changelog
> release: 6.8.2

- script/test-plugin-urls.py
```
$ ./script/test-plugin-urls.py twitch -r CHANNELNAME gorgc
:: https://clips.twitch.tv/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
::  360p30, 480p30, 720p60, 1080p60, worst, best
:: https://player.twitch.tv/?parent=twitch.tv&channel=gorgc
::  audio_only, 160p, 360p, 480p, 720p60, 1080p60, worst, best
:: https://player.twitch.tv/?parent=twitch.tv&video=1963401646
::  audio, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: https://player.twitch.tv/?parent=twitch.tv&video=1963401646&t=1h23m45s
::  audio, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: https://www.twitch.tv/clip/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
::  360p30, 480p30, 720p60, 1080p60, worst, best
:: https://www.twitch.tv/dota2ti/v/1963401646
::  audio, 160p, 360p, 480p, 720p, 720p60, …
```
> script: simplify output of test-plugin-urls, add -m/--metadata, fix -r/--replace

- tests/plugins/test_twitch.py
These added tests were already part of #5769 in a slightly different version, but with the recent changes of #6071 it makes sense having this on the master branch now.
> plugins.twitch: add UsherService tests

- src/streamlink/plugins/tiktok.py
- tests/plugins/test_tiktok.py
> plugins.tiktok: new plugin

- src/streamlink/plugins/bloomberg.py
Resolves #6075 
@7k50 please check and see if these changes do indeed work
----
```
$ ./script/test-plugin-urls.py bloomberg
:: https://www.bloomberg.com/live
::  272p, 360p, 720p_alt, 720p, 1080p, worst, best
:: https://www.bloomberg.com/live/europe
::  272p, 360p, 540p, 720p, worst, best
:: https://www.bloomberg.com/live/us
::  272p, 360p, 720p_alt, 720p, 1080p, worst, best
:: https://www.bloomberg.com/news/videos/2022-08-10/-bloomberg-surveillance-early-edition-full-08-10-22
::  540p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
```
```
$ streamlink -l debug https://www.bloomberg.com/live/us best
[cli][debug] OS:         Linux-6.9.8-1-git-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.4 …
```
> plugins.bloomberg: fix bot detection

- CHANGELOG.md
I want the Twitch plugin fix to be released, so this will be published either later today or tomorrow...
> release: 6.8.3

- src/streamlink_cli/console.py
- tests/cli/test_console.py
https://github.com/streamlink/streamlink/discussions/6079
> cli.console: keep unicode chars in JSON output

- src/streamlink/plugins/okru.py
- tests/plugins/test_okru.py
Resolves #6084 
Author metadata seems to be gone, so I set it to optional for now.
----
LIVE
```
$ ./script/test-plugin-urls.py okru -m -r ID 3503444925978
:: https://m.ok.ru/video/3503444925978
::  240p, 360p, 480p, 720p, 1080p, worst, best
::   {'id': '3503444925978', 'author': None, 'category': None, 'title': 'Прямая трансляция телеканала "Общественное телевидение Приморья"'}
:: https://mobile.ok.ru/video/3503444925978
::  240p, 360p, 480p, 720p, 1080p, worst, best
::   {'id': '3503444925978', 'author': None, 'category': None, 'title': 'Прямая трансляция телеканала "Общественное телевидение Приморья"'}
:: https://ok.ru/live/3503444925978
::  240p, 360p, 480p, 720p, 1080p, worst, best
::   {'id': '3503444925978', 'author': None, 'category': None, 'title': 'Прямая трансляция телеканала …
```
> plugins.okru: fix metadata schema

- build_backend/__init__.py
- https://github.com/python/typeshed/blame/a21c4bc4f15c07e07cb3e0bbe684b0fb1c81788f/stdlib/distutils/command/install_egg_info.pyi#L7
- https://github.com/pypa/setuptools/blob/v71.1.0/setuptools/_distutils/fancy_getopt.py#L47-L54
> build: fix typing issue caused by types-setuptools

- src/streamlink/plugins/vk.py
> plugins.vk: fix validation schema, clean up code

- src/streamlink/plugins/nicolive.py
- tests/plugins/test_nicolive.py
Fixes #6125 
```
$ streamlink https://live.nicovideo.jp/watch/user/134029528
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/user/134029528
Available streams: 350k (worst), 690k, 1800k (best)
```
> plugins.nicolive: update matcher

- src/streamlink/plugins/vimeo.py
Resolves #6122
> DASH manifests (sometimes?) are in the JSON format, which is unsupported.
> Previously, it was possible to change the URL's path component and replace the manifest's file name extension,
> but now, URLs are signed and can't be updated anymore, so simply discard those kinds of DASH manifest URLs.
```
$ streamlink https://vimeo.com/144358359
[cli][info] Found matching plugin vimeo for URL https://vimeo.com/144358359
Available streams: 204p (worst), 240p, 272p, 360p, 544p, 720p, 816p, 1080p (best)
```
```
$ ./script/test-plugin-urls.py vimeo
:: https://player.vimeo.com/video/176894130
!! Error while fetching streams
:: https://vimeo.com/783455878
::  240p, 360p, 540p, 720p, 1080p, worst, best
:: https://vimeo.com/channels/music/176894130
::  240p_hls, 1080p_hls, 720p_hls, …
```
> plugins.vimeo: ignore unsupported DASH manifests

- dev-requirements.txt
- tests/cli/utils/test_progress.py
https://astral.sh/blog/ruff-v0.6.0
> tools: bump ruff to 0.6.0 and fix issues

- src/streamlink/plugins/youtube.py
See #6060 
This adds the following error message for VOD content with 4xx HTTP error responses
> This plugin does not support VOD content, try yt-dlp instead
and updates the existing error message for protected videos
> This plugin does not support protected videos, try yt-dlp instead
The protected video stuff is actually useless now, but I didn't want to make any significant plugin changes, so it'll be kept.
----
In order to fix VOD content, we'd need to implement YouTube's adaptive stream URL signatures. As said, I'm not interested in implementing this myself, so if someone wants this to be fixed, they'll need to submit a PR with working code and be willing to keep the plugin maintained.
Live content is of course still working fine.
----
```
$ streamlink …
```
> plugins.youtube: check VOD URLs, raise PluginError

- src/streamlink/plugins/douyin.py
Fixes #6139
```
$ ./script/test-plugin-urls.py douyin -m -r ROOM_ID 682201026704
:: https://live.douyin.com/682201026704
::  ao, md, ld, sd, hd, uhd, origin, worst, best
::   {'id': '7407243544185883433', 'author': '白纾', 'category': None, 'title': '黑神话超高画质剧情纯享版真大圣'}
```
> plugins.douyin: fix validation schema

- dev-requirements.txt
- pyproject.toml
https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html
> tests: set pytest-asyncio config, fix warnings

- src/streamlink/session/http_useragents.py
> session.http_useragents: update useragents

- .github/workflows/test.yml
- pyproject.toml
No reason to merge this just yet
> build: add Python 3.13 to package classifiers

- src/streamlink/plugins/tiktok.py
Resolves #6159
Inaccessible stream (requires login)
```
$ streamlink tiktok.com/@weemonloup/live
[cli][info] Found matching plugin tiktok for URL tiktok.com/@weemonloup/live
[plugins.tiktok][error] The stream is inaccessible
error: No playable streams found on this URL: tiktok.com/@weemonloup/live
```
Some random stream
```
$ streamlink tiktok.com/@zexyzekyt/live
[cli][info] Found matching plugin tiktok for URL tiktok.com/@zexyzekyt/live
Available streams: ao, ld (worst), origin, sd, hd, hd_60, uhd_60 (best)
```
> plugins.tiktok: fix schema of inaccessible streams

- CHANGELOG.md
https://streamlink--6157.org.readthedocs.build/changelog.html
> release: 6.10.0

- src/streamlink/session/http.py
- tests/session/test_http.py
Resolves #6204 
Really not sure if this is the right approach to solve this. This might just be a bug in `urllib3`.
When `--http-no-ssl-verify` is set, `verify` is set to `False` on the `HTTPSession(requests.Session)`. This leads to `cert_reqs=ssl.CERT_NONE` being set on the `HTTPSConnectionPool`. Eventually, `urllib3` will make the TLS connection and verify it. Nothing unusual so far.
However, when the user has also set `--http-disable-dh`, we mount a custom `HTTPAdapter` on the `https://` scheme, which includes a custom `SSLContext` where the Diffie-Hellman key exchange is disabled. This `SSLContext` has all default values set otherwise. It will of course also be passed to the `HTTPSConnectionPool` and taken into account while validating the TLS connection.
The issue here is that …
> session.http: fix custom SSLContext + verify=False

- src/streamlink/webbrowser/cdp/devtools/__init__.py
- src/streamlink/webbrowser/cdp/devtools/browser.py
- src/streamlink/webbrowser/cdp/devtools/debugger.py
- src/streamlink/webbrowser/cdp/devtools/dom.py
- src/streamlink/webbrowser/cdp/devtools/emulation.py
- src/streamlink/webbrowser/cdp/devtools/fetch.py
- src/streamlink/webbrowser/cdp/devtools/input_.py
- src/streamlink/webbrowser/cdp/devtools/inspector.py
- src/streamlink/webbrowser/cdp/devtools/io.py
- src/streamlink/webbrowser/cdp/devtools/network.py
- src/streamlink/webbrowser/cdp/devtools/page.py
- src/streamlink/webbrowser/cdp/devtools/runtime.py
- src/streamlink/webbrowser/cdp/devtools/security.py
- src/streamlink/webbrowser/cdp/devtools/target.py
- src/streamlink/webbrowser/cdp/devtools/util.py
Resolves #6209 
Closes #6210 
This updates Streamlink's Chrome devtools protocol version from `v0.0.1156692` (initialized last year with 81d2ff2c98f1732d934e85ef117983e683da20d1) to `v0.0.1359167`, which fixes compatibility with recent Chromium versions.
```
$ ./script/generate-cdp.py fetch runtime input dom
Output: /home/basti/repos/streamlink/src/streamlink/webbrowser/cdp/devtools
Fetching latest tag from NPMJS
Latest tag: v0.0.1359167
Fetching https://github.com/ChromeDevTools/devtools-protocol/raw/v0.0.1359167/json/browser_protocol.json
Fetching https://github.com/ChromeDevTools/devtools-protocol/raw/v0.0.1359167/json/js_protocol.json
Parsing domains...
Writing output...
Generating module: Browser -> browser.py
Generating module: Debugger -> debugger.py
Generating module: DOM -> …
```
> webbrowser.cdp.devtools: update to v0.0.1359167

- docs/deprecations.rst
- docs/migrations.rst
https://streamlink--6235.org.readthedocs.build/migrations.html#streamlink-7-0-0
> docs: add migration docs for the breaking changes of 7.0.0

- src/streamlink_cli/argparser.py
> cli.argparser: remove VLC --title var escape logic

- src/streamlink/plugins/soop.py
- tests/plugins/test_soop.py
- Fix broken bno in pluginmatcher regex and update capture groups names
- Fix CDN value from API not being used when getting HLS stream URL
- Add special CDN mapping for "gs_cdn"
- Update validation schemas, parse JSON in schema, return tuples
- Update method signatures
- Set all constants as class attributes
- Reformat code
- Update pluginmatcher tests and add plugin options tests
----
CDN param fix:
https://github.com/streamlink/streamlink/issues/6246#issuecomment-2422784065
`bno` in pluginmatcher regex was broken since Streamlink 2.0.0 (2020-12-22):
https://github.com/streamlink/streamlink/commit/c0baa95f82a02147149e2f33d42cb34983b6dcea#diff-3b4336061632b5600984e648cc9bf2a4eec1f02bcdf259c7648f8275994f8c42R30
----
channel, channel+bno
```
$ ./script/test-plugin-urls.py soop -r CHANNEL …
```
> plugins.soop: refactor plugin and fix issues

- .git-blame-ignore-revs
> tools: ignore ruff format commit in git-blame

- src/streamlink/plugins/ruv.py
- tests/plugins/test_ruv.py
This plugin stood out while reformatting the plugins, so I had a look at it and noticed that it wasn't only in really bad shape, but also completely broken. It's probably not useful to keep it, as nobody's opened a plugin issue for it, but fixing it was simple, so let's just do that...
```
$ ./script/test-plugin-urls.py ruv
:: https://www.ruv.is/sjonvarp/beint/ruv
::  360p, 432p, 576p, 720p_alt, 720p, worst, best
:: https://www.ruv.is/sjonvarp/beint/ruv2
:::: The content is not available in your region
:: https://www.ruv.is/sjonvarp/spila/kastljos/35422/ahpu2g
::  360p, 480p, 720p, 1080p, worst, best
:: https://www.ruv.is/sjonvarp/spila/vedur/30766/agcf5m
::  360p, 480p, 720p, 1080p, worst, best
:: https://www.ruv.is/utvarp/beint/ras1
::  350k, worst, best
:: …
```
> plugins.ruv: rewrite and fix plugin

- docs/cli/config.rst
- docs/cli/plugin-sideloading.rst
- https://streamlink--6266.org.readthedocs.build/cli/plugin-sideloading.html
- https://streamlink--6266.org.readthedocs.build/cli/config.html
> docs: rewrite plugin sideloading page

- docs/install.rst
- https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name/st/streamlink
- https://github.com/NixOS/nixpkgs/commit/571c71e6f73af34a229414f51585738894211408
> docs: update NixOS package link

- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .readthedocs.yml
https://github.com/streamlink/streamlink/pull/6270#issuecomment-2468511007
This adds a newline character to the output of awk. Not sure if this will fix the issue. Let's see. Otherwise we'll have to disable the `pipefail` option or explicitly catch the 141 error code and ignore it.
> ci: update git fetch commands

- src/streamlink/plugins/soop.py
Resolves #6320 
@Infinitay please give this PR a quick test and report back with the results. This site requires a phone number when trying to register a new account, so I'm not able to test this myself as I'm surely not going to give them any of my personal data. Please also try purging the stored credentials, logging back in, and checking the stored auth credentials again. Thank you.
----
Instead of checking a list of specific/hardcoded cookies, this PR rewrites the auth logic by checking whether any cookies are available on the HTTP session (restored from the plugin cache) for the `.sooplive.co.kr` domain, and if that's the case, then it attempts to verify the cookies on `GET …
> plugins.soop: rewrite authentication

- src/streamlink/plugins/mangomolo.py
- tests/plugins/test_mangomolo.py
Replace media.gov.kw with 51.com.kw
----
Fixes #6352
> plugins.mangomolo: update plugin matcher

- src/streamlink_cli/argparser.py
> cli: clarify --show-matchers output format

- CHANGELOG.md
Before releasing 7.1.0, I will have a look at some of the open PRs first this weekend. The release date is set to tomorrow, but that's just a template value.
> release: 7.1.0

- CHANGELOG.md
> release: 7.1.1

- src/streamlink/plugins/dailymotion.py
> plugins.dailymotion: fix matcher regex groups

- src/streamlink/plugins/dailymotion.py
- tests/plugins/test_dailymotion.py
Modification of the plugin to add live streams from “l'équipe” channel
> plugins.dailymotion: add lequipe.fr

- src/streamlink/plugins/tiktok.py
- tests/plugins/test_tiktok.py
Fixes #6380 
This fixes live streams and adds support for VODs. The stream type has not been changed and it's still using HTTPStream instead of HLSStream (idc). The "origin" quality is now considered best.
Random live stream
```
$ streamlink tiktok.com/@kamchagaming
[cli][info] Found matching plugin tiktok for URL tiktok.com/@kamchagaming
Available streams: ao, ld (worst), sd, hd, hd_60, uhd_60, origin (best)
```
Random offline stream
```
$ streamlink https://www.tiktok.com/@netflix
[cli][info] Found matching plugin tiktok for URL https://www.tiktok.com/@netflix
[plugins.tiktok][info] The channel is currently offline
error: No playable streams found on this URL: https://www.tiktok.com/@netflix
```
Invalid channel
```
$ streamlink …
```
> plugins.tiktok: rewrite plugin, fix live, add VODs

- src/streamlink/plugins/nicolive.py
Fixes: #6349
@99mirin https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback
> plugins.nicolive: fix mfa login

- src/streamlink/plugins/dailymotion.py
> plugins.dailymotion: add missing $url metadata

- src/streamlink/plugins/chzzk.py
- tests/plugins/test_chzzk.py
Closes: #6333 ~before merging, would be cool resolve PR #6388.~
```
./script/test-plugin-urls.py chzzk -m -i CHANNEL_ID -r CLIP_ID LeqAmSuEQy -r CLIP_ID R9BilMGLOS -r VIDEO_ID 5164033
:: https://chzzk.naver.com/clips/CLIP_ID
:::: 잘못된 contentId 입니다.
:: https://chzzk.naver.com/clips/LeqAmSuEQy
::  720p, worst, best
::   {'id': 'LeqAmSuEQy', 'author': '독케익', 'category': None, 'title': '독카이저 만세!'}
:: https://chzzk.naver.com/clips/R9BilMGLOS
:::: This stream is for adults only
:: https://chzzk.naver.com/video/5164033
::  144p, 720p, 1080p, worst, best
::   {'id': '5164033', 'author': '따효니', 'category': 'League_of_Legends', 'title': '생컨뒤풀이 롤내전 (얍얍, 플레임, 네클릿, 후추, 둥그레, 니니아, 달콤레나, 연리, 이춘향)'}
:: https://chzzk.naver.com/video/VIDEO_ID
:::: 잘못된 값을 입력했습니다.
!! No …
```
> plugins.chzzk: add clips support

- CHANGELOG.md
https://streamlink--6386.org.readthedocs.build/changelog.html
> release: 7.1.2

- dev-requirements.txt
- pyproject.toml
- src/streamlink/validate/_schemas.py
https://github.com/astral-sh/ruff/releases/tag/0.9.0
> tools: bump ruff to 0.9.0 and fix issues

- src/streamlink/plugins/ceskatelevize.py
- tests/plugins/test_ceskatelevize.py
Fixes #6394 
No idea if the validation schema of the sports channel is good enough and catches all cases with weird licensing restrictions of their live streams, but it works now and it's basically the same format as the one from the previous implementation, so I don't really care.
Streams were working fine, unless region blocked.
German IP address: not all inaccessible streams are marked as ones, and a short video with a region block screen is returned instead
```
$ ./script/test-plugin-urls.py ceskatelevize --metadata
:: https://ceskatelevize.cz/zive/art
::  288p, 404p, 576p, worst, best
::   {'id': 'CH_6', 'author': None, 'category': None, 'title': 'ČT art'}
:: https://ceskatelevize.cz/zive/ch-28
:::: The stream is inaccessible
:: https://ceskatelevize.cz/zive/ct1 …
```
> plugins.ceskatelevize: rewrite and fix plugin

- src/streamlink/plugins/wwenetwork.py
Closes: #5674
I can provide an account with an active subscription for testing purposes.
```
$ streamlink --no-config -l debug --hls-duration 5 -o /dev/null --wwenetwork-email REDACTED --wwenetwork-password REDACTED https://network.wwe.com/live/275587 best
[cli][debug] OS:         Linux-5.4.0-196-generic-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.5
[cli][debug] OpenSSL:    OpenSSL 1.1.1f  31 Mar 2020
[cli][debug] Streamlink: 7.1.1+12.g6e2b7af3.dirty
[cli][debug]  certifi: 2024.12.14
[cli][debug]  exceptiongroup: 1.1.1
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.7.1
[cli][debug]  pycountry: 22.1.10
[cli][debug]  pycryptodome: 3.9.9
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: …
```
> plugins.wwenetwork: rewrite and fix plugin

- src/streamlink_cli/argparser.py
Small phrasing change and explicit mentioning of the two possible defaults
> cli: improve --logformat/--logdateformat help text

- src/streamlink/plugins/pluzz.py
Resolves #6427 
This fixes the broken video ID validation schemas.
@novazur972 please check and see if any other streams on the site are not working correctly
While working on the initial changes earlier this evening, I didn't check whether authentication was actually required, because the video ID schemas were still broken. They were showing a football match at the time on the france-2 channel, so I don't know if authentication is required only for certain kinds of content.
I have a second commit that's not part of this PR branch that adds support for authentication (just noticed that it's not working 100% correctly before opening this PR, irrelevant though). If it turns out that authentication is …
> plugins.pluzz: fix video ID schemas

- CHANGELOG.md
Will merge and publish this later today
> release: 7.1.3

- src/streamlink/plugins/okru.py
Fixes #6443 
@leomani51214
Their mobile site sometimes returns a different HTML response which the plugin can't handle. This varying response seems to be similar to the data which is covered by the plugin's logic for their main site, but I don't think it's worth handling this case and refactoring the plugin because of that. Requesting the same video ID on their main site seems to be working, so I instead removed all logic for the mobile site and made the plugin translate mobile input URLs to URLs for their main site.
I however don't know if this solution works reliably, not just for the input URL of #6443. So @leomani51214, since I'm not familar with okru, please go ahead and test the changes of …
> plugins.okru: canonicalize mobile URLs

- tests/stream/hls/test_hls.py
https://github.com/streamlink/streamlink/pull/6445#issuecomment-2676269083
> tests.stream.hls: add key method switching test

- docs/api_guide/quickstart.rst
Leaving this up for review, in case something's not as clear as it should be (which I think it is now).
Ref #6463 
See the rendered docs:
https://streamlink--6464.org.readthedocs.build/api_guide/quickstart.html
> docs: improve API quickstart guide

- src/streamlink/plugins/nicolive.py
Ref https://github.com/streamlink/streamlink/pull/6441#issuecomment-2745230175
@secondaryH please test...
Since there has been no follow up to my request in the linked thread, I haven't tested these changes myself. These were purely done by reading the posted log output.
> plugins.nicolive: filter out blank segments

- src/streamlink/webbrowser/cdp/devtools/__init__.py
- src/streamlink/webbrowser/cdp/devtools/browser.py
- src/streamlink/webbrowser/cdp/devtools/debugger.py
- src/streamlink/webbrowser/cdp/devtools/dom.py
- src/streamlink/webbrowser/cdp/devtools/emulation.py
- src/streamlink/webbrowser/cdp/devtools/fetch.py
- src/streamlink/webbrowser/cdp/devtools/input_.py
- src/streamlink/webbrowser/cdp/devtools/inspector.py
- src/streamlink/webbrowser/cdp/devtools/io.py
- src/streamlink/webbrowser/cdp/devtools/network.py
- src/streamlink/webbrowser/cdp/devtools/page.py
- src/streamlink/webbrowser/cdp/devtools/runtime.py
- src/streamlink/webbrowser/cdp/devtools/security.py
- src/streamlink/webbrowser/cdp/devtools/target.py
- src/streamlink/webbrowser/cdp/devtools/util.py
- tests/webbrowser/cdp/test_client.py
This updates Streamlink's Chrome DevTools Protocol interfaces to `v0.0.1438564`.
The last update was `v0.0.1359167` in #6211 (2024-09-30)
Streamlink's CDP interfaces currently emit warnings due to new additions in the recent CDP versions implemented in Chromium that are not recognized. For example:
```
$ streamlink twitch.tv/CHANNEL --twitch-force-client-integrity --twitch-purge-client-integrity 
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
[plugins.twitch][info] Removing cached client-integrity token...
[plugins.twitch][info] Acquiring new client-integrity token...
[webbrowser.webbrowser][info] Launching web browser: /usr/bin/chromium (headless=True)
[webbrowser.cdp.connection][warning] Unknown CDP event message received: Page.frameStartedNavigating …
```
> webbrowser.cdp.devtools: update to v0.0.1438564

- src/streamlink/plugins/kick.py
- tests/plugins/test_kick.py
- Fix clips matcher
- Refactor API requests
- Add missing API request headers and parse the User-Agent string
Some API requests might fail randomly and solving a JS challenge is required, similar to Twitch's client-integrity token. The JS challenge requirement however seems to be rare and subsequent API request attempts are almost always successful.
----
Fixes #6414
No issues while testing these URLs and lots of other in the past half an hour. But as said in the commit message, sometimes API requests will fail. It's possible that this is also timing-based, which I already suspected in previous PRs.
Either way, having these changes on master should already be an improvement.
Solving the JS challenge is a bit "challenging" when most API requests succeed without it being a requirement. I …
> plugins.kick: refactor, fix clips + 403 API issues

- CHANGELOG.md
Scheduled for Saturday
https://streamlink--6505.org.readthedocs.build/changelog.html
> release: 7.3.0

- src/streamlink/plugins/kick.py
Kick once again returns 403 HTTP responses on their API with the current plugin version on master.
Solving the JS challenge and using the resulting cookies should work. This is now the third or fourth attempt of me implementing this, because the previous PRs all turned out to be unnecessary. I however could verify a few minutes ago before my IP address once again got whitelisted that accessing the API with the JS challenge cookies works. Whether it's unnecessary again because of some missing HTTP headers, like twice previously, I don't know. But since I got whitelisted again, I can't verify this, because even master works again from my end.
I'd therefore very much appreciate PR feedback from anyone. Please give this a quick try.
https://github.com/streamlink/streamlink/blob/master/CONTRIBU …
> plugins.kick: solve JS challenge

- src/streamlink/plugins/picarto.py
Fixes #6510 
This should fix regular and multi streams. VODs apparently were still working (although they appear broken on their website).
Btw, their website uses websocket streams instead of HLS streams. I don't know if this was already the case previously when the plugin was implemented, but if not, then this might be an indicator that their HLS backend might be removed in the future once they stop using it as a fallback mechanism for certain web browsers or other clients/etc.
----
Regular stream
```
$ streamlink https://picarto.tv/FattyNite best --hls-duration=10 -o /dev/null
[cli][info] Found matching plugin picarto for URL https://picarto.tv/FattyNite
[cli][info] Available streams: 1080p (worst, best)
/dev/null …
```
> plugins.picarto: fix schema and multi-streams

- tests/stream/hls/test_hls.py
> tests: fix flaky HLS test

- src/streamlink/plugins/nicolive.py
- src/streamlink/session/http.py
- src/streamlink/session/http.pyi
- tests/session/test_http.py
Fixes #6543 
```
$ streamlink -j https://live.nicovideo.jp/watch/lv347867912 best
{
"type": "hls-multi",
"metadata": {
"id": "lv347867912",
"author": "株式会社 ドワンゴ",
"title": "【24時間 ライブカメラ】クラシックBGMとともに銀座の景色を見る放送〈お天気情報・ニューストピック表示あり〉"
}
}
```
> plugins.nicolive: force utf-8 encoding

- src/streamlink/plugins/twitcasting.py
Ref #6539 
@qwer-lives have a look at this PR please.
This switches to the `llfmp4` and `tc-hls` streams, which also simplifies the plugin. I have no idea about the availability of these streams compared to the previous implementation though, so I'd like to get some feedback on this from users of this site. As can be seen in the PR's diff, previously, llfmp4 was avoided because of alleged video/audio desync issues.
I also have no idea about password protected streams. Similar to before, this is only implemented for the websocket streams.
HLS have been assigned a lower priority because of the delay. `--stream-priority=websocket` / `--stream-priority=hls` allows for selecting only a specific type of …
> plugins.twitcasting: switch to llfmp4 and tc-hls

- CHANGELOG.md
Going to publish this evening today...
https://streamlink--6551.org.readthedocs.build/changelog.html
> release: 7.4.0

- src/streamlink/stream/ffmpegmux.py
- src/streamlink/stream/hls/hls.py
Some typing improvements needed for updating and rebasing #5769
> stream.hls: make MuxedHLSStream generic

- src/streamlink/stream/ffmpegmux.py
Don't log an error message when writing to the named pipe fails after the FFmpeg process has been terminated/killed.
Check if the substream has been closed or if the process does not exist anymore and then log the pipe-copy completion debug message.
----
Unfortunately, we don't have tests written for that. This is a race condition, depending on where the copy-to-pipe thread of each substream is currently at. If the next `stream.read()` call blocks and the result is an empty byte string due to the substream having been closed, then we log the completion message. But if some stream data has been read and it's being written to the named pipe while the FFmpeg process gets terminated/killed upon closing the stream, then we unintentionally log an error message. This needs to be fixed, because …
> stream.ffmpegmux: ign pipe write err on stream end

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
https://github.com/streamlink/streamlink/discussions/6567#discussioncomment-13524353
> tests.cli: require metavar for args with values

- src/streamlink/cache.py
- tests/test_cache.py
- Schedule cache file writes instead of writing immediately when pruning data on get() or when setting/pruning data on set():
Use a write debounce timer of 3s and also add an `atexit` callback
- Keep a dirty state and prevent unnecessary writes
- Don't ignore cache file loading errors and instead log a warning msg
- Always set cache file encoding to UTF-8 when reading or writing
- Refactor cache file writing logic, use higher level stdlib APIs, and log write errors instead of raising some of them
----
Ref #6501
This doesn't fix the data structure issues pointed out in #6501, but it should already be an improvement.
One thing I will have to take a look at before merging (when I get the time) is checking on Windows in regards to the file encoding. Previously, no file encoding was set when …
> cache: rewrite and improve cache file I/O

- tests/test_cache.py
See https://github.com/streamlink/streamlink/pull/6592#issuecomment-3019852485
> tests: fix test_schedule_save in Cache tests

- src/streamlink/plugins/twitcasting.py
Twitcasting serves preroll segments if you request an HLS playlist before enough video data has been sent to the server, typically within ~0-10 seconds of a stream starting. Since they're using fMP4 now, it breaks the output with a discontinutiy, so they need to be filtered.
Fixes #6600 
<details>
<summary>Before</summary>
```
[05:47:13.811937][MainThread][cli][debug] OS:         Linux-6.12.35-1-lts-x86_64-with-glibc2.41
[05:47:13.812288][MainThread][cli][debug] Python:     3.13.5
[05:47:13.812580][MainThread][cli][debug] OpenSSL:    OpenSSL 3.5.1 1 Jul 2025
[05:47:13.812747][MainThread][cli][debug] Streamlink: 7.4.0+37.g6ea1bb4d.dirty
[05:47:13.812903][MainThread][cli][debug] Dependencies:
[05:47:13.816492][MainThread][cli][debug]  certifi: 2025.6.15 …
```
> plugins.twitcasting: filter preroll segments

- src/streamlink/cache.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session/options.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/main/conftest.py
- tests/cli/main/test_setup_plugins.py
- tests/cli/test_argparser.py
- tests/test_cache.py
- tests/test_plugin.py
1. Allow disabling automatic sideloading of third-party plugins
2. Allow disabling plugin key-value store
> Add --no-plugin-sideloading and --no-plugin-cache

- src/streamlink/plugins/lrt.py
Fixes #6636 
The old `stream_url` key is kept as a fallback.
```
$ ./script/test-plugin-urls.py -m lrt
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-klasika
::  540p, 720p, 1080p, worst, best
::   {'id': 'Klasika', 'author': None, 'category': None, 'title': 'Žinios. Orai'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica
::  540p, 720p, 1080p, worst, best
::   {'id': 'WORLD', 'author': None, 'category': None, 'title': 'Gustavo enciklopedija'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-opus
::  540p, 720p, 1080p, worst, best
::   {'id': 'Opus', 'author': None, 'category': None, 'title': 'LRT OPUS muzika'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-plius
::  540p, 720p, 1080p, worst, best
::   {'id': 'LTV2', 'author': None, 'category': None, 'title': '7 Kauno dienos'}
:: …
```
> plugins.lrt: fix channels schema

- docs/cli/plugins/twitch.rst
https://github.com/streamlink/streamlink/discussions/6648#discussioncomment-14278972
> docs: add note about revoking Twitch OAuth tokens

- src/streamlink/webbrowser/cdp/client.py
- src/streamlink/webbrowser/cdp/devtools/__init__.py
- src/streamlink/webbrowser/cdp/devtools/browser.py
- src/streamlink/webbrowser/cdp/devtools/debugger.py
- src/streamlink/webbrowser/cdp/devtools/dom.py
- src/streamlink/webbrowser/cdp/devtools/emulation.py
- src/streamlink/webbrowser/cdp/devtools/fetch.py
- src/streamlink/webbrowser/cdp/devtools/input_.py
- src/streamlink/webbrowser/cdp/devtools/inspector.py
- src/streamlink/webbrowser/cdp/devtools/io.py
- src/streamlink/webbrowser/cdp/devtools/network.py
- src/streamlink/webbrowser/cdp/devtools/page.py
- src/streamlink/webbrowser/cdp/devtools/runtime.py
- src/streamlink/webbrowser/cdp/devtools/security.py
- src/streamlink/webbrowser/cdp/devtools/target.py
- src/streamlink/webbrowser/cdp/devtools/util.py
Last CDP update was in #6481 (`v0.0.1438564` - 2025-03-28)
This update requires a minor change in the return type of `page.navigate()`.
----
Same domain selection: `fetch runtime input dom`
```
$ ./script/generate-cdp.py -l debug fetch runtime input dom
Output: /home/basti/repos/streamlink/src/streamlink/webbrowser/cdp/devtools
Fetching latest tag from NPMJS
Latest tag: v0.0.1510116
Fetching https://github.com/ChromeDevTools/devtools-protocol/raw/v0.0.1510116/json/browser_protocol.json
Parsing JSON...
Fetching https://github.com/ChromeDevTools/devtools-protocol/raw/v0.0.1510116/json/js_protocol.json
Parsing JSON...
Parsing domains...
Writing output...
Generating module: Browser -> browser.py
Generating type BrowserContextID: string
Generating type WindowID: integer
Generating type …
```
> webbrowser.cdp.devtools: update to v0.0.1510116

- src/streamlink/plugins/chzzk.py
This PR enhances the Chzzk plugin to support live playback functionality, allowing users to access past stream content when available.
Chzzk offers a live playback(time machine) feature that allows viewers (particularly paid subscribers) to watch up to 1 hour of past content from ongoing streams, provided the streamer has enabled this functionality. This PR enables Streamlink users to access this content using options like `--hls-start-offset` to download or view past portions of live streams.
> plugins.chzzk: add live playback

- src/streamlink/plugins/aloula.py
Resolves #6661 
```
$ ./script/test-plugin-urls.py aloula
:: https://aloula.sba.sa/en/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://aloula.sba.sa/en/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://aloula.sba.sa/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://aloula.sba.sa/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://www.aloula.sa/en/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://www.aloula.sa/en/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://www.aloula.sa/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://www.aloula.sa/live/saudiatv
::  360p, 480p, 1080p, worst, best
```
> plugins.aloula: fix livestream schema
