script/pushdocs.sh

This is a tiny tweak to the `pushdocs.sh` script, if a pull request was made from a branch inside this repo, it would have built and pushed the docs from that PR. We need to wait a merge to master before updating the docs!

Disable docs on pull requests

---

src/streamlink/__init__.py

Fixes #38, I also noticed this is present here: https://github.com/streamlink/streamlink/blob/9bc8949ca300572d6fb14042e1f013e024d20b7f/win32/livestreamer-win32-installer.nsi#L12 but I don't think it's worth fixing since we're modifying how the Windows build works.

Modify release for streamlink

---

src/streamlink/plugins/twitch.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This PR is a fix for #41.
Example output without the option:
> (streamlink) simon@desktop:~/projects/streamlink$ streamlink https://www.twitch.tv/ster best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/ster
[plugin.twitch][info] ster is hosting overwatchopen
[plugin.twitch][info] switching to overwatchopen
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /usr/bin/vlc
This is the output with the `--twitch-disable-hosting` option
> (streamlink) simon@desktop:~/projects/streamlink$ streamlink https://www.twitch.tv/ster best --twitch-disable-hosting
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/ster
[plugin.twitch][info] ster is hosting …

twitch.tv: add option to disable hosting

---

src/streamlink/plugins/picarto.py

This works for both multistream and individual streams as long as
it isn't a multistream where the primary streamer is offline.
If you go to a page linked to a multistream but the primary streamer
is offline, then this will incorrectly match the secondary or tertiary
stream and record them instead of (correctly) reporting the stream
offline.

Picarto plugin: multistream workaround (fixes #50)

---

.travis.yml
script/makedocs.sh
script/pushdocs.sh

In the last merge, the docs' build just failed randomly, and all the docs got removed. This is an attempt to fix it.

Don't delete everything if docs build fail

---

src/streamlink/plugins/periscope.py

This PR basically allows to handle URLs of kind https://www.periscope.tv/<username>/<broadcast_id> (before it was https://www.periscope.tv/w/<broadcast_id> only)
And it handles live streams same way as recorded.

fixed periscope live streaming and allowed url re

---

src/streamlink/plugins/itvplayer.py
src/streamlink/plugins/livestream.py

py2 and py3 handle integer division differently, in py2 1800000 / 1000 would be 1800, however in py3 it would be 1800.0. This means that for some plugins (itv, and livestream at least) the quality could be named 1800.0k, which is not handled as expected.

Fix stream quality naming issue with py2 vs. py3, fixing #89

---

docs/index.rst

Resolves https://github.com/streamlink/streamlink/issues/92
Unfortunately the index is in rst, and the changelog is in markdown so I just made a quick and dirty change to get this fixed for now. We'll probably want to fix this in a better way at some point.

Modify the changelog link

---

src/streamlink/plugins/orf_tvthek.py

The way stream metadata (such as HLS playlist URLs) is embedded into the ORF TVthek website has changed. As a result, streamlink was unable to extract any stream sources. This PR adapts the plugin to these changes and restores previous functionality.
Additionally, tabs have been converted to spaces as spaces seem customary across the project.

Fix ORF TVthek plugin

---

src/streamlink/plugins/livecodingtv.py

A per the suggestion by @intact. It removed the bad `\l` escape code in the regex. 
Also fixes the plugin so that it finds the streams again.

Fix for erroneous escape coding the livecoding plugin. Fixes #106

---

src/streamlink/plugins/tvplayer.py
tests/test_plugin_tvplayer.py

The User-Agent header needs to be sent for the page to fill in the correct platform variable.

TVPlayer.com: fix for 400 error, correctly set the platform parameter

---

.travis.yml
src/streamlink/plugin/api/http_session.py
tests/test_plugin_api_http_session.py

This should fix #120 and if I understand #19 it should fix that too. 
According to [RFC4627: The application/json Media Type for JavaScript Object Notation (JSON)
](http://www.ietf.org/rfc/rfc4627.txt) JSON is always encoded as Unicode (see section 3.  Encoding) and the specific Unicode encoding can be determined by looking at the pattern of NULL bytes in the first 4 bytes. 
I have added a method that implements this pattern matching and added a couple of tests for it, the tests use `unittest.mock` which is not available in Python 2 - I added `mock` to the `before_install` command for travis. 
Props to @cyluss 👍

Automatically determine the encoding when parsing JSON with HTTPSession

---

src/streamlink/plugins/twitch.py
src/streamlink_cli/main.py

This PR fixes #82
There was a bug in the way that `Twitch._check_for_host` worked in that it would update the `channel_id` to the hosted channel (if the requested channel was hosting), and as such on the next retry it would see that hosted channel (now stored in `channel_id`) was not hosting and would play the hosted channel.
This fix updates `Twitch._check_for_host`so that it does not modify the object state and moves that logic in to the calling method `Twitch._get_hls_streams`.
It also fixes a bug where if you had one channel hosting another channel, that was hosting a different channel, eg. channel_a -> channel_b -> channel_c, you would not find the streams for channel_c. It will also detect cycles and stop eg. channel_a -> channel_b -> channel_a would create an infinite loop :)

Retrying hosted streams with hosting disabled will always retry

---

docs/plugin_matrix.rst
src/streamlink/plugins/adultswim.py
tests/test_plugin_adultswim.py

As requested by @stepshal in #126.
Only the live streams (http://www.adultswim.com/videos/streams/) are supported, the VOD streams appear to be encrypted HDS streams.

plugins.adultswim: added adultswim.com plugin

---

src/streamlink/plugins/goodgame.py

As per the discussion on #130 and [chrippa/livestreamer/#1518](https://github.com/chrippa/livestreamer/issues/1518) I have included @intact's patch to restore the DDOS protection cookie handling.

plugins.goodgame: restored DDOS protection cookie support

---

src/streamlink/plugins/zdf_mediathek.py

File "C:\Python35\lib\site-packages\streamlink-0.0.2-py3.5.egg\streamlink\plugins\zdf_mediathek.py", line 95, in _get_streams
formatList = res["priorityList"]["formitaeten"]
TypeError: list indices must be integers or slices, not str

Fix zdf_mediathek TypeError

---

src/streamlink/plugins/cybergame.py

This PR fixes #147. 
cybergame.tv has switched to using a fixed RTMP url for the live streams, there doesn't appear to be an easy way to automatically get that url. They could change the URL in the future, and if they do that often I will work out a better method to get the RTMP URL, but for now it works.

plugins.cybergame: support the new streaming url for live streams

---

.travis.yml
docs/install.rst
script/makeinstaller.sh

As requested, this PR adds automated nightly (actually build on each commit to master) for the Streamlink NSIS Windows installer, and pushes them to S3. 
The releases are listed [on S3](https://streamlink-builds.s3.amazonaws.com/index.html), and the latest build is always available here [streamlink-latest.exe](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe).
Nightly builds are automatically removed from S3 after 60 days. 
For nightly builds, the version number is constructed out of the current release version (eg. 0.0.2) and the current short commit hash (eg. ba92efb), so they become `0.0.2+ba92efb`. The file name is generated with the build number also (`streamlink-0.0.2-34-ba92efb.exe`), this is so the most recent file can easily be identified and the …

Automated Windows nightly builds

---

docs/install.rst
script/makeinstaller.sh
src/streamlink/plugins/beattv.py
src/streamlink/stream/hls.py

`pycryptodome` is a fork of `pyCrypto` and can be used as a drop-in replacement for `pyCrypto`, either package can be used. 
The advantage of `pycryptodome` over `pyCrypto` is that it has wheels available on PyPi for Windows, which makes it easier for Windows users to install and for us to include in the NSIS installer. I have updated the installer script to include `pycryptodome`.

Use pycryptodome inplace of pyCrypto

---

src/streamlink/stream/rtmpdump.py
win32/streamlinkrc

This patch allows the path to `rtmpdump(.exe)` to be specified as a relative path or as an absolute path. 
FYI @RosadinTV, this patch might break the current version of your portable builder (see my [comment](https://github.com/streamlink/streamlink/issues/155#issuecomment-260892115) on #155).

Support for relative paths for rtmpdump

---

script/makeinstaller.sh
win32/streamlinkrc

I believe this PR fixes #81 and thus unblocks #116. 
This patch adds an extended nsi template that includes the `streamlinkrc` config file in the installer. The config file is only installed _if_ there is no pre-existing config file in the users `%APPDATA%\streamlink` directory. After the config file has been installed the path to `rtmpdump` is _always_ updated to point to the `rtmpdump.exe` included with the `streamlink` install.
I replaced the newlines in the `win32/streamlinkrc` file with Windows line endings, so that it is more friendly for Windows users to edit in notepad :)

Install the streamlinkrc file in to the users %APPDATA% directory

---

script/makeinstaller.sh

- Remove unnecessary start menu shortcut creation
- Don't automatically close the copy/remove file section
- Add checkbox for opening the documentation in the web browser
- Add checkbox for editing the config file

Improve NSIS installer script

---

src/streamlink/packages/shutil_which.py
src/streamlink/stream/rtmpdump.py
src/streamlink/stream/streamprocess.py

This fixes the issue reported by @mmetak.
That was my bad, missed testing on linux :| 
This patch uses `shutil.which` (introduced in Python 3.3, with included backport) to find the command on the PATH

stream.rtmpdump: fixed the rtmpdump path issue, introduced in 6bf7fd7

---

script/makeinstaller.sh

Follow up of #174 
- Remove old start menu shortcut when installing streamlink >= 0.0.3
- Don't try to remove shortcuts when uninstalling (shortcuts are not being created anymore)

Remove shortcut from previous releases on Windows

---

setup.py

Currently `requests>=2.12.0` has strict validation for IDNA2008. This means that some URIs that are in use (specifically by YouTube) will not validate and thus will not work in `streamlink`. This PR pins `requests` to a version before `2.12.0`. We can use a later version if YouTube fix their non-compliant URIs or `requests` gives to option to use a less strict IDNA parer. 
This is documented in #169.
> If I understand it correctly, IDNA was extended to reverse xx--. UTS-46 defines the criteria for valid IDNA encoded unicode characters.
> 
> > The first 5 criteria are from [IDNA2008]. Criterion #2 in particular is meant to allow for future label extensions beyond just xn--, such as for future versions of IDNA. Some implementations appear to consider such extentions unlikely, and allow …

Pin requests to <2.12.0 to avoid the strict IDNA2008 validation

---

src/streamlink/plugins/livestream.py

Latest fix from @intact for the livestream plugin (chrippa/livestreamer/pull/1277), without squashing previous `streamlink` fixes. Could fix #182, but needs to be tested on a Raspberry Pi.

Fix for plugin.livestream courtesy of @intact 

---

src/streamlink_cli/main.py

This simply ensures we're doing the redirect to https://streamlink.github.io/twitch_oauth.html instead of Chrippa's site. Fixes #190.

Modify the browser redirect

---

src/streamlink_cli/main.py

Right now when outputting the stream to stdout (-O option) as root the new warning will end up being printed alongside the stream's content.
It should work like other console messages. This way it will respect the loglevel set and it will be printed on stderr when outputting the stream to stdout.

Use ConsoleOutput for run-as-root warning

---

script/makeinstaller.sh

Python code shouldn't be in quotes.

Fix issue with building installer

---

docs/plugin_matrix.rst
src/streamlink/plugins/atv.py

This PR adds support for the live stream on http://www.atv.com.tr/webtv/canli-yayin as requested by @Rotarum in #146. Unfortunately I cannot read much of the site, so I don't really know what else can be streamed :)

Add support for the live stream on atv.com.tr

---

setup.py

This should resolve #150. 
I have pinned the version of `pycryptodome` as this is a known working version and it has a Windows wheel that supports Python2.7 + Python3.3-3.5.

Add pycryptodome==3.4.3 to the setup.py dependencies

---

docs/players.rst

I have added OMXPlayer to the list of players in the docs, and I added some notes about the workarounds for getting some streams to work as discussed in #182.
Comments? :)

Include omxplayer in the list of players in the docs

---

docs/plugin_matrix.rst
src/streamlink/plugins/bigo.py

As requested by @joneelee81 in #216. 
This one was quite interesting, it uses a custom streaming protocol. To start the stream you have to connect to the ip and port (found in the flashVars) and then send both the `uid` and `sid` as little-endian unsigned longs. Then the server responses with an FLV :)

Add support for bigo.tv

---

docs/plugin_matrix.rst
src/streamlink/plugins/dingittv.py

As requested by @Brainzyy in #227 and other in chrippa/livestreamer#974. 
I have not tested live streams as there were none to test.
It is possible that some stream will not work, in addition to HLS [dingit.tv](http://www.dingit.tv) also use [Octoshape](http://octoshape.com) which provides a proprietary streaming server and flash client. I had a bit of a poke around trying to reverse it but it is quite complex, and if HLS works I see no point trying to support the Octoshape client. 
The HLS URLs are hardcoded in the swf player, so could be changed with a new version of their client. 
If anyone tests this plugin out and finds a stream that does not work, please report it :)

Add support for dingit.tv

---

docs/install.rst
script/makeinstaller.sh

As pointed out by @scowalt in #246, the Visual Studio 2015 Runtimes are required for some versions Windows. I have modified the installer to install the VC runtimes if they aren't already installed. The [Python Embedded Distribution](https://docs.python.org/3.5/using/windows.html#embedded-distribution) page also points out that the runtimes are not included and should be installed by the installer. This is possibly an oversight of `pynsist`, but we can fix it ourselves :)
I tested this out of a vanilla Windows Vista 32bit VM, it would be good if @scowalt could test it out on the Chocolatey test environment and if some other people could test it out :)
I have build a version of the installer that people can use to test this out: [streamlink-0.1.0-vcredist-7a50314.exe](https://s3.amazonaws.c …

Include Visual Studio 2015 Runtime in the installer

---

script/makeinstaller.sh

Resolves #277 
Added version, publisher, about-url, help-url and estimated-size data.

Add metadata to Windows installer

---

docs/plugin_matrix.rst
src/streamlink/plugins/atv.py
src/streamlink/plugins/dogan.py
src/streamlink/plugins/foxtr.py
src/streamlink/plugins/kralmuzik.py
src/streamlink/plugins/ntv.py
src/streamlink/plugins/startv.py
src/streamlink/stream/hds.py

This PR adds support for live streams on the following sites:
- http://www.a2tv.com.tr
- http://www.ntv.com.tr
- http://www.teve2.com.tr
- http://www.kanald.com.tr
- http://www.cnnturk.com
- http://www.dreamtv.com.tr
and VOD support for:
- http://www.teve2.com.tr
- http://www.kanald.com.tr

Tweaks and updates for Turkish streams

---

.coveragerc

`streamlink_cli` wasn't included before, it is now. 
The vendored packages don't need to be covered...

Small tweak to the coverage config

---

.travis.yml
MANIFEST.in
appveyor.yml
build.cmd
dev-requirements.txt
src/streamlink_cli/output.py
src/streamlink_cli/utils/player.py
tests/plugins/testplugin.py
tests/test_cmdline.py
tests/test_plugin_api_http_session.py

This PR does a couple of things. 
Firstly, it fixes the issue reported by @bastimeyer in #293, with some tests (see below). `subprocess.Popen` can be called with a string for the command line under Windows (same as `shell=True` under POSIX). Calling `subprocess.Popen` with the string command line means that it doesn't have to be parsed using `shlex` or quoted, which avoids the parsing issue. Parsing is still required on POSIX as `shell=True` is not advised. 
I tested in `cmd` and `powershell` on Vista and Windows 10:
```powershell
streamlink -a "--input-title-format \"Poker \\\"Stars\\\"\" {filename}" twitch.tv/pokerstars worst
streamlink -p "C:\Program Files\VideoLAN\VLC\vlc.exe --input-title-format \"Poker \\\"Stars\\\"\"" twitch.tv/pokerstars worst
streamlink twitch.tv/pokerstars worst …
```

Windows command line parsing fix

---

docs/cli.rst
src/streamlink/packages/requests_file.py
src/streamlink/plugin/api/http_session.py
src/streamlink/plugins/stream.py
src/streamlink/stream/hls_playlist.py

As requested in #253 and chrippa/livestreamer#1514. 
Support for local files via the `file://` protocol.
`hls`, `hlsvariant` and `httpstream` are supported. Files can be loaded from relative or absolute paths, or even read from `stdin`.
eg.
```sh
streamlink hlsvariant://file://./playlist.m3u8 best
cat playlist.m3u8 | streamlink hlsvariant://file://- best
streamlink httpstream://file://./hadoken.mp4
cat hadoken.mp4 | streamlink httpstream://file://- best
```

Support for local files

---

docs/plugin_matrix.rst
src/streamlink/plugins/liveme.py
src/streamlink/plugins/tv4play.py

This PR adds liveme.com stream support, as requested in #291. 
Could do with some testing, for VOD in particular.
It supports URLS like:
http://www.liveme.com/media/play/?videoid=23456789098765&extra_stuff=xxxx

plugins.liveme: added support for liveme.com streams

---

src/streamlink/plugins/vaughnlive.py

This does two things:
* Updates the `PLAYER_VERSION`—the old one does not work anymore.
* Adds the ability to use URLs with `/embed/video` in them, which come from embedded players.
This seems to work for me.

Fix Vaughn Live plugin

---

docs/plugin_matrix.rst
src/streamlink/plugins/trtspor.py

Adds support for http://www.trtspor.com.
Supports TV and radio streams, the TV streams are geo-locked to Turkey, so tricky to test without being in Turkey or without a Turkish proxy. 
Example URLs:
- http://www.trtspor.com/canli-yayin-izle/trtspor-159/ (geo-locked to Turkey)
- http://www.trtspor.com/canli-yayin-izle/trtspor-160/

plugins.trtspor: added support for trtspor.com

---

.travis.yml
appveyor.yml

Enable Python 3.6 on Travis and AppVeyor. 
Also enable Python 3.7 dev on Travis, but allow failures until 3.7 is closer to release.

Build with Python 3.6 in the CI environments

---

src/streamlink/packages/flashmedia/amf.py

`flashmedia.amf.AMFMessage` sets a field incorrectly when serialising, this PR rectifies that issue.
As this package is no longer maintained by its author, and already has some `streamlink` specific patches, I will continue with small bug fixes for `flashmedia` until a suitable replacement can be found...

packages.flashmedia: fix bug in AMFMessage

---

docs/plugin_matrix.rst
src/streamlink/plugins/mitele.py

Most of the time the streams are geo-blocked to Spain, and sometimes (but not always) some of the streams have DRM. 
Example URLs:
- mitele.es/directo/telecinco
- mitele.es/directo/cuatro
- mitele.es/directo/boing
- mitele.es/directo/bemad

plugins.mitele: support for live streams on mitele.es

---

src/streamlink/plugins/picarto.py

The page layout changed very slightly, they changed one of the arguments in their `placeStream` method so that it takes a name for the default streaming technology (flash or hls), where as before it was an integer. 
While the site change was small I decided to update the plugin a bit, it now has better logging messages, detects multi-channel streams, and detects non-existent stream pages.
It also fixes the issue reported in #364.

Picarto update to support new site layout

---

src/streamlink/session.py
src/streamlink/stream/streamprocess.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
src/streamlink_cli/utils/stream.py

As requested in #327 :)
Adds the option `--subprocess-errorlog-path` (`--errorlog-path`) to specify the path of the subprocess error log.
eg.
```
streamlink --errorlog-path rtmpdump.log itv.com/hub/itv best 
```

Specify the subprocess errorlog path

---

src/streamlink/plugins/twitch.py

Current Twitch API documentation[1] recommends for every API request to specify the API version by setting the Accept HTTP header to the appropriate value. This patch:
* sets the value to v3 (older versions of the API are going to be removed).
* uses the base URL`https://api.twitch.tv/kraken` to access (public) API resources
[1]: https://github.com/justintv/Twitch-API
See #20 for details

Upgrade Twitch plugin to use API v3

---

src/streamlink/plugins/adultswim.py

The plugin erroneously reported that it does not support https://www.adultswim.com URLs.

plugins.adultswim: support https urls

---

docs/plugin_matrix.rst
src/streamlink/plugins/raiplay.py
tests/test_plugin_raiplay.py

As requested in #375.
Example URLs:
- raiplay.it/dirette/rai1
- raiplay.it/dirette/rai3
- raiplay.it/dirette/rainews24
- raiplay.it/dirette/raisport1

plugins.raiplay: added plugin to support raiplay.it

---

docs/plugin_matrix.rst
src/streamlink/plugin/api/useragents.py
src/streamlink/plugins/tf1.py
tests/test_plugin_tf1.py

As requested in #376. 
Example URLs:
- tf1.fr/ft1/direct
- tf1.fr/nt1/direct
- tf1.fr/tmc/direct
- tf1.fr/lci/direct
- lci.fr/direct

plugins.tf1: added plugin to support tf1.fr and lci.fr

---

src/streamlink/plugins/vaughnlive.py

Fixes the bug reported in #378. 
The Info URL and player version have been updated, I added some extra debug logging while updating it. 
The version and info url are hardcoded in the swf, is possible that we could decompress the swf and try to extract the version and info url.

plugins.vaughnlive: updated player version and info URL

---

src/streamlink/plugins/crunchyroll.py
tests/test_plugin_crunchyroll.py

I don't know since when, but rss links on crunchy no longer contain the show name slug on the url, so the current regex fails to match against those links.
I didn't remove the group since some people get the link directly from the page, which still use the previous format.

Links on crunchy's rss no longer contain the show name in the url

---

src/streamlink/plugins/tf1.py
src/streamlink/stream/hds.py

Seems the streams only worked some of the time with the existing plugin. I have updated the plugin to use the correct `pvswf` url and the correct stream info urls. 
I also added the `g` (`guid`) parameter to the Akamai hdcore URLs for manifests which was required for these streams. 
Fixes #376 correctly this time.

Fix TF1.fr plugin

---

src/streamlink/plugins/stream.py

Due to a bug introduced in 707df4f27bf144f4e33dc76ffafbcf2fac2519b8 URLs with scheme (eg. no http) but with a port number would not get http:// appended by default, as urlparse parses anything before the colon as the scheme.

plugins.stream: fix a default scheme handling for urls

---

docs/plugin_matrix.rst
src/streamlink/plugins/bnt.py
src/streamlink/plugins/btv.py
src/streamlink/plugins/eurocom.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_plugin_bnt.py
tests/test_plugin_btv.py
tests/test_plugin_eurocom.py

As requested in #374.
BTV requires a login, the username and password can be set with `--btv-username` and `--btv-password`. 
Should support for the following sites:
- eurocom.bg/live
- bgonair.bg/tvonline
- bitelevision.com/live
- kanal3.bg/live
- nova.bg/live
- tv.bnt.bg/bntworld
- tv.bnt.bg/bnt1/hd
- tv.bnt.bg/bnt1/16x9
- tv.bnt.bg/bnt2/16x9
- btv.bg/live (requires login)

Add support for some Bulgarian live streams

---

src/streamlink/plugin/api/useragents.py
src/streamlink/plugins/bnt.py

When loading the HLS streams some User Agents were rejected, specifically Firefox. Updating the User Agent string to Chrome resolves the issue.

plugins.bnt: fix key request user agent

---

docs/plugin_matrix.rst
src/streamlink/plugins/sportal.py
src/streamlink/stream/rtmpdump.py
src/streamlink/utils.py
tests/test_plugin_sportal.py

Adds support for sportal.bg as requested by @roshavagarga.
Pretty much just supports one URL:
- sportal.bg/sportal_live_tv.php?str=15

Add support for a Bulgarian sports channel

---

src/streamlink/session.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_session.py

Do the same as --can-handle-url but without HTTP operations involved as issued in https://github.com/streamlink/streamlink/issues/331

--can-handle-url-no-redirect parameter added

---

src/streamlink/stream/hls.py

This fixes #370 but also fixes a wider bug in HLS playlist parsing. 
When parsing an HLS playlist only one stream was output for each quality, if multiple streams existed at the same quality the ones appearing later in the playlist would be dropped. This patch fixes this behaviour and will output "alt" streams. eg. `360p_alt, 720p_alt, 360p (worst), 720p (best)` which allows auto-switching if the primary stream fails (as is in the case with the Toonami stream). 💥

Include alt streams when parsing HLS playlists

---

src/streamlink/session.py
src/streamlink/stream/ffmpegmux.py

There was a bug that prevented `avconv` from being used if `ffmpeg` was not available. I have fixed the bug and `avconv` can be used instead of `ffmpeg` (for example on Debian).

Use AVconv if available and FFmpeg is not available

---

docs/plugin_matrix.rst
src/streamlink/plugins/canalplus.py
tests/test_plugin_canalplus.py

This plugin adds support for French Canal+ TV group channels:
* canalplus.fr
* c8.fr
* cstar.fr
Both live and VOD are supported.

Add support for Canal+ TV group channels

---

src/streamlink/plugins/rtve.py

Updated to support their new streaming API, fixed #413.
Should work with the following URLs:
- rtve.es/noticias/directo-la-1/
- rtve.es/television/la-2-directo/
- rtve.es/deportes/directo/teledeporte/
- rtve.es/noticias/mas-24/
- rtve.es/mas24/?assetid=1938030
- rtve.es/television/catalunya/directo/

plugins.rtve: update plugin to support new streaming method

---

docs/plugin_matrix.rst
src/streamlink/plugin/api/mapper.py
src/streamlink/plugin/plugin.py
src/streamlink/plugins/adultswim.py
src/streamlink/stream/hds.py
tests/test_plugin_adultswim.py

Fixes the issues with the previous PR https://github.com/streamlink/streamlink/pull/406#issuecomment-272434885 along with #417 which removes the DRM streams. 
Tested URLs:
- adultswim.com/videos/aqua-teen-hunger-force/vampirus
- adultswim.com/videos/streams/toonami-pre-flight/friday-january-6th-2017 (some DRMed streams)
- adultswim.com/videos/streams/toonami
- adultswim.com/videos/specials/the-adult-swim-golf-classic-extended

Adultswin VOD fix for live show replays

---

src/streamlink/stream/ffmpegmux.py
src/streamlink/utils/__init__.py
src/streamlink/utils/named_pipe.py
src/streamlink_cli/utils/__init__.py
src/streamlink_cli/utils/named_pipe.py

Refactor of `streamlink_cli.utils.named_pipe` so that the `streamlink` module can remain independent from the `streamlink_cli` module, ie. `streamlink` has no dependency on `streamlink_cli`, only the other way around.
The `streamlink_cli.utils` API is not affected by this change.

Move streamlink_cli.utils.named_pipe in to streamlink.utils

---

src/streamlink/stream/hds.py

As discussed in https://github.com/streamlink/streamlink/pull/406#issuecomment-272246813; I have found a better way to deal with the encrypted HDS streams, by simply omitting them when parsing the manifest file.
If the `drmAdditionalHeader` element has some content then it's protected by DRM, so that stream is skipped.

stream.hds: omit HDS streams that are protected by DRM

---

src/streamlink/plugins/livestream.py

(At least some) livestream.com streams currently won't play because streamlink attempts to open a URL that starts with "http:////" (four slashes). This PR fixes this issue.

Fix swf_url in livestream.com plugin

---

script/makeinstaller.sh

Fix the duplicate streamlink bin directories in `%PATH%` as reported in #412 by @thinkpad4

installer: remove the streamlink bin dir from %PATH% before installing

---

src/streamlink/plugins/beattv.py
src/streamlink/plugins/bongacams.py
src/streamlink/plugins/filmon_us.py
src/streamlink/plugins/huajiao.py
src/streamlink/plugins/media_ccc_de.py
src/streamlink/plugins/streamingvideoprovider.py
src/streamlink/plugins/ustreamtv.py
src/streamlink/plugins/vgtv.py
src/streamlink/plugins/youtube.py
src/streamlink/plugins/zhanqi.py

Regular expressions should be raw strings (`r""`) when they contain regex escape sequences (eg. `\w`).

Fix deprecation warnings in Python 3.6

---

docs/install.rst

Streamlink is now available in Fedora from official repositories. This PR updates installation instructions for Fedora.

Update installation instructions for Fedora

---

docs/plugin_matrix.rst
src/streamlink/plugins/playtv.py
tests/test_plugin_playtv.py

This plugin adds support for the French TV streaming platform [Play TV](http://playtv.fr/).
Some channels may be geo-restricted.

Add support for Play TV

---

src/streamlink_cli/utils/progress.py

without it:
```
[download][test.flv] Written 129.2 MB (5s @ 7.5 MB/s)
cli][info] Stream ended
```
with it:
```
[download][test.flv] Written 129.2 MB (5s @ 7.5 MB/s)
```

streamlink_cli.utils.progress: write new line at finish

---

docs/plugin_matrix.rst
src/streamlink/plugins/srgssr.py
tests/test_plugin_srgssr.py

This PR adds the plugin requested in #403.
Testing is required as I couldn't find a Swiss proxy that would work :)
The following URLs would be good test cases:
- srf.ch/play/tv/live
- rsi.ch/play/tv/live#?tvLiveId=livestream_La1
- rsi.ch/play/tv/live?tvLiveId=livestream_La1
- rtr.ch/play/tv/live
- rts.ch/play/tv/direct#?tvLiveId=3608506
- srf.ch/play/tv/live#?tvLiveId=c49c1d64-9f60-0001-1c36-43c288c01a10

Support for SRG SSR sites

---

src/streamlink/plugins/nineanime.py

This PR fixes the issue reported in #447.
The API calls have been updated to use the same URL scheme as the stream URL requested. If the URL requests use http then the API requests also use http, if the stream URL uses https then the API requests use https. 
I suspect 9anime.to is making a transistion to https only.

plugins.nineanime: add scheme to grabber api url if not present

---

src/streamlink/session.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This is useful if an old server has a DH key that is too short for modern implementations of ssl.
(As far as I understand it): 
Due to the logjam attack (CVE-2015-4000) DH primes that are too short will be rejected by ssl. If the stream you are trying to load uses a weak DH key, this option allows you to disable Diffie Hellman as a possible key exchange method and use an alternative. This may or may not be a good idea, and should be used with caution.

session: add an option to disable Diffie Hellman key exchange

---

ISSUE_TEMPLATE.md

I'm not sure if an issue template is really necessary here or if this specific template fits the project, but I thought that we could at least have a discussion about it.
👎
- It might be overwhelming or intimidating for casual users or bug reporters
- Not all information is always necessary
👍
- People *usually* read the template before submitting, resulting in clearer reports
- Reduces the number of duplicates
- Environment details will *most likely* be included without asking first (reduces number of responses)
- Posts are formatted correctly *most of the time*
My suggested template can ofc be changed if it's too much or if sth is missing... 😜

Add a github issue template

---

docs/plugin_matrix.rst
src/streamlink/compat.py
src/streamlink/plugins/srgssr.py
src/streamlink/plugins/swisstxt.py
tests/test_plugin_srgssr.py
tests/test_plugin_swisstxt.py

Here's a fixed version of the srgssr plugin along with support for the swisstxt hosted sports streams. 
The PR fixes #403 
Should now support the sports live streams. You can find the sports streams on the following URLs (however, there are not always any streams available):
- srf.ch/sport/resultcenter/results
- rts.ch/sport/programmes/
- live.rsi.ch/results.html
In addition to the sports streams, there are some extra live streams listed on rsi.ch/live-streaming/
@karlo2105 also confirmed that the plugins were working as expected :-)

Swiss SRG SSR Fix 

---

src/streamlink/stream/hls_playlist.py

If an invalid duration for a segment is encountered eg. `#EXTINF:-0.016,` it is ignored and read as `0` duration, the duration is not that important for our use. The baviour for most players seems to be to ingore the invalid duration and round it to 0, and I don't think it's too bad for us to do the same.
This occurs in some Twitch VOD streams, possibly due to very long duration (the example in #471 is 12 hours long), although I was unable to recreate the issue with any other very long stream (twitch.tv/dotapit/v/116506478 18h works fine).

Read negative segment duration as 0

---

src/streamlink/plugins/twitch.py
src/streamlink/stream/hls.py

This PR fixes #476, an option has been added to `HLSStream` to force the playlist to be played from the start. 
This new option is generally useful for any live stream that has a VOD/DVR feature where you want to start from the beginning of the stream rather than the "live edge".

Play twitch VOD stream from the beginning even if is still being recorded

---

src/streamlink_cli/output.py

As pointed out by @LoneFox78. The loop should wait for the process to exit regardless of the error code, rather than waiting for a non-0 error code. Currently it waits for a truthy response, which means it will wait even if the process ended with exit code 0. 
A gross error on my part this one ...

cli: wait for process to exit, not exit with non-0 error code

---

win32/streamlinkrc

As discussed in #481, the config file previously needed to be updated if the user chose not to install ffmpeg. With this patch, if `rtmpdump.exe` or `ffmpeg.exe` are in the `%PATH%` they will be located automatically, if they are not found then the default behaviour still occurs (which is to omit streams that require `ffmpeg` or `rtmpdump`). 
Should preempt a few issues.

Fix bug in customized Windows install

---

docs/install.rst
script/makeinstaller.sh
setup.py
src/streamlink/plugins/crunchyroll.py
src/streamlink/session.py
src/streamlink/utils/l10n.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_localization.py

The `crunchyroll-locale` option was useful, but too specific to crunchyroll. There is a general usefulness for users to be able to control their desired locale settings. For example, in streams with multiple audio languages the correct language could be selected based on the locale setting. (I am working on this for HLS Streams). 
I have added a `Localization` class that provides some useful methods for compare languages using different length codes (eg. 'en' vs. 'eng') and for determining the default locale settings. 
The Crunchyroll plugin has been updated to use the new locale setting and will benefit from automatically switching to the users locale, much like it would on the web version of crunchyroll. 
Two dependencies were added `iso-639` and `iso3166`, which provide information and …

Add a general locale setting which can be used by plugins

---

docs/install.rst
script/makeinstaller.sh
setup.py
src/streamlink/plugins/crunchyroll.py
src/streamlink/session.py
src/streamlink/stream/ffmpegmux.py
src/streamlink/stream/hls.py
src/streamlink/utils/l10n.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_localization.py

This PR requires #454 be merged first. 
It adds the requested external audio stream feature to the `hls`  module (fixed #111). The `locale` setting is used to pick an appropriate audio stream when there are multiple available. If an audio stream with the language matching your requested language (or system language) then that stream will be picked over the others, if none are found then the default stream is used. 
Example stream: https://streamingrmp-1479.kxcdn.com/vod/smil:hls-maudios-prod.smil/playlist.m3u8
This HLS Stream has 3 audio streams, in 3 different languages, english, french and german (not that they are actually in those languages, there are just 2 extra random audio streams). If you select any of the available languages (`--locale en_US`, `--locale de_DE` or `--locale …

Support for external audio streams in HLS

---

docs/plugin_matrix.rst
src/streamlink/plugins/schoolism.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Requires 3 new command line options have to support the site
--schoolism-email: providing the users email address
--schoolism-password: providing the users password
--schoolism-part: specifying which part of a lesson to play

plugins.schoolism: add support for schoolism.com

---

script/release.sh

When doing the 0.3.0 release I encountered some errors generating the
header of the RST file.
Also, we now automatically build the Windows binary as part of the
release progress through Travis, thus, removing the binary from being
uploaded / generated.

Updating the release script.

---

docs/plugin_matrix.rst
src/streamlink/plugins/gulli.py
tests/test_plugin_gulli.py

This plugin add support for the French TV channel Gulli (for children). It supports both VOD and live streams. Streams are geo-restricted to France, Belgium and Switzerland.
The live stream is available at http://replay.gulli.fr/Direct

Add support for replay.gulli.fr

---

src/streamlink/plugin/api/http_session.py
src/streamlink/session.py
src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This should fix both #446 and #463. 
I fixed the retries on the HLS segments as well as adding retries (via a general HTTPSession mechanism) to the `playlist_reload` and `create_decryptor` methods. A new `--hls-reload-playlist-attempts` option has been added to control the retries for the playlist. 
I reverted most of the changes made for #166/#260 as it has caused some unforeseen issues. Mainly due to the exception handling of `HTTPSession.request` and `iter_content` being quite different. (The exception handling in livestreamer/streamlink is generally a mess.)
We'll have to reopen #166 until we have a more suitable solution.

Ensure retries with HLS Streams

---

src/streamlink/plugins/crunchyroll.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Adds the option `--crunchyroll-session-id` which allows the user to specify a specific API session ID, useful for bypassing the region restrictions. Fixes #505

Option to set crunchyroll session ID

---

src/streamlink/utils/l10n.py

Fixes #537, by defaulting to `en_US` if an unrecognised/invalid locale is set by the environment.

utils.l10n: default to en_US when an invalid locale is set

---

src/streamlink/stream/ffmpegmux.py
src/streamlink/stream/hls.py

Prefer the first audio stream with a specific language, a future enhancement could be to pick the stream based on the characteristics too. HLS streams are muxed out as `mpegts` instead of `mkv` now. 
This should fix #531

stream.hls: pick a better default stream language

---

appveyor.yml

This fixes the build issues we've been having for the last couple of days, since the new version of `pycryptodome` doesn't have wheels for some versions of Python...

AppVeyor build fix

---

src/streamlink/plugins/crunchyroll.py

See Issue #538 
This is a rather trivial pull request, it literally adds a single character to a format string to allow it to function on Python 2.6

Crunchyroll plugin fails on string.format in Python 2.6

---

src/streamlink/utils/l10n.py
tests/test_localization.py
tests/test_localization_pycountry.py

The `pycountry` vs. `iso639+iso3166` l10n tests were broken so that the only the `pycountry` tests were being run. This has now been fixed, which uncovered a bug in the `iso3166` country lookup.

utils.l10n: fix bug in iso3166 country lookup

---

src/streamlink_cli/output.py
tests/test_cmdline.py

When #453 was merged it added some possible delay in killing the player process, this delay was also experienced in the tests. By mocking the expected return values of `poll()`, the delay can be avoided and the runtime of the tests reduced from around 60 seconds to 6 seconds.

tests: speed up the cmdline tests

---

src/streamlink/stream/hls.py

If the HTTP request for the key for an HLS stream fails then the
stream will end. This is a problem for streams where the key is updated
periodically. If the key request fails it will be retried a few times
(same retry count as hls-segment-attempts). This should fix #547.

stream.hls: Retry HTTP requests to get the key for HLS streams

---

src/streamlink/stream/hls.py

As a last ditch effort, fallback on the first audio stream presented as the audio stream to use when an external audio stream is required.

stream.hls: last chance fallback audio

---

src/streamlink/stream/hds.py
src/streamlink_cli/main.py

Make the fact that some streams are protected by DRM more obvious to the user. This is useful if the user specifies a `hds://` URL that has DRMed streams and wonders why no streams are returned.
If child streams are protected by DRM the warning message is only printed once, but a debug message will be printed for each stream. The message is deliberately vague in stating whether or not any stream are available as this message is generated by the HDS manifest parsing method and in a plugin other streams may be available.

stream.hds: warn about streams being protected by DRM

---

src/streamlink/plugins/filmon.py
src/streamlink/stream/__init__.py
src/streamlink/stream/http.py
src/streamlink/stream/rtmpdump.py
src/streamlink/stream/stream.py
src/streamlink/utils/__init__.py
src/streamlink_cli/main.py
src/streamlink_cli/utils/stream.py
tests/test_stream_to_url.py

The current method (`streamlink_cli.utils.stream.stream_to_url`) converts a stream to a URL. The responsibility of converting a stream to a URL should be that of the `Stream` class.
A new `to_url` method has been added to the `Stream` class to facilitate this. This makes is much easier for `Stream` subclasses to generate URLs for streams if possible. For example, in the FilmOn specific HLS stream class, `FilmOnHLS` a subclass of `HLSStream`, it is not always possible to generate a suitable URL, as some streams expire almost immediately.

stream: make Stream responsible for generating the stream_url

---

docs/plugin_matrix.rst
src/streamlink/plugins/tvrplus.py

As requested by @karlo2105 in #586. The most basic plug-in I could come up with ;)
Example URLs:
- `tvrplus.ro/live-tvr-1`
- `tvrplus.ro/live-tvr-hd`
- `tvrplus.ro/live-tvr-2`
- `tvrplus.ro/live-tvr-3`
- `tvrplus.ro/live-tvr-international` (not geo-locked)
- `tvrplus.ro/live-tvr-moldova`
- `tvrplus.ro/live-tvr-cluj`
- `tvrplus.ro/live-tvr-craiova`
- `tvrplus.ro/live-tvr-iasi`
- `tvrplus.ro/live-tvr-targu-mures`
- `tvrplus.ro/live-tvr-timisoara`

plugins.tvrplus: add support for tvrplus.ro live streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/ovvatv.py

As requested in #592 by @karlo2105: 
Add support for the Ukrainian live TV streams on ovva.tv.
The streams are provided via HLS and do not appear to be geo-locked.
Supported URLs:
- ovva.tv/tvguide/1plus1/online
- ovva.tv/ua/tvguide/1plus1/online
- ovva.tv/tvguide/1plus1in/online
- ovva.tv/ua/tvguide/1plus1in/online
- ovva.tv/tvguide/2plus2/online
- ovva.tv/ua/tvguide/2plus2/online
- ovva.tv/tvguide/tet/online
- ovva.tv/ua/tvguide/tet/online
- ovva.tv/tvguide/tsnsurdo/online
- ovva.tv/ua/tvguide/tsnsurdo/online
- ovva.tv/tvguide/unian/online
- ovva.tv/ua/tvguide/unian/online

plugins.ovvatv: add support for ovva.tv live streams

---

src/streamlink_cli/utils/http_server.py

When using `--player-external-http` if streamlink is closed and restarted a `Address already in use` error can be encountered. This is because the socket is still in the `TIME_WAIT` state (more information can be found here: http://hea-www.harvard.edu/~fine/Tech/addrinuse.html).
The solution is to set the socket option `SO_REUSEADDR` so that the address can be reused before the end of the `TIME_WAIT` state. This does **not** mean that multiple streamlink instance can listen on the same port.
This should fix #595 :)

cli.utils.http_server: avoid "Address already in use" with --player-external-http

---

docs/plugin_matrix.rst
src/streamlink/plugins/tvrby.py
tests/test_plugin_tvrby.py

Add support for streaming live TV from the Belarus National TV channels.
Most channel provide one HLS stream and one RTMP stream, both are named "live" as they are equivalent and this respects the user's `stream-priority` setting when requesting "best".
Supported URLs:
- tvr.by/televidenie/belarus-1/
- tvr.by/televidenie/belarus-2/
- tvr.by/televidenie/belarus-3/
- tvr.by/televidenie/belarus-5/
- tvr.by/televidenie/belarus-24/
*Note: VLC3-beta does not currently play video for the `rtmp` streams, only audio.*

plugins.tvrby: support for live streams of Belarus national TV

---

docs/plugin_matrix.rst
src/streamlink/plugins/seetv.py
src/streamlink/stream/hls_playlist.py

Only the streams that are provided directly from seetv.tv will work, embedded (`<iframe />` or `<object />`) streams are not supported.
Example URLs:
- seetv.tv/vse-tv-online/stb-ch-ua
- seetv.tv/vse-tv-online/tv-inter-ua

plugins.seetv: add support for seetv.tv live streams

---

src/streamlink/plugins/mitele.py

A specific mitele cache file was being generated, which is not required as the `Plugin` class already provides a `Cache` instance to use.

plugin.mitele: use the default plugin cache

---

src/streamlink/plugins/ovvatv.py

Affects Python3.3-3.5 where `b64decode` returns a `bytes`, but `json.loads` expects a `str`.
Mea culpa, I didn't test it with Python 3.5...

plugins.ovvatv: fix b64decoding bug

---

src/streamlink_cli/utils/http_server.py

The socket may already be closed on the other end, so ignore any errors that occur when trying to shutdown the server socket.
This should fix #604 reported by @thinkpad4.

cli.utils.http_server: ignore errors with socket.shutdown

---

docs/plugin_matrix.rst
src/streamlink/plugins/pluzz.py
tests/test_plugin_pluzz.py

This PR improves the pluzz plugin to add support for the following VOD platforms for youth, provided by France Télévisions:
* ludo.fr (as requested in https://github.com/streamlink/streamlink/issues/534)
* zouzous.fr
As for the streams on pluzz.francetv.fr, videos on these two websites are georestricted to France, Andorra and Monaco.

plugins.pluzz: add support for ludo.fr and zouzous.fr

---

docs/donate.rst
docs/index.rst

This is an initial draft for what a possible donation page would look like. This fixes #347. I believe that this PR addresses https://github.com/streamlink/streamlink/issues/347#issuecomment-270068127 as it prominently features bountysource in addition to direct donation methods. At this time I've only added myself and @bastimeyer as the donation details were easy to find.
Edit: It would probably good to add a donation page link to the releases as well.

Add a donation page

---

src/streamlink/plugins/daisuki.py

Only the first text portion was being used when converting the XML subtitles to SRT, this meant that only the first line was included.
This fixes the issue mention in #609. Tested in `VLC2.2.4`, `VLC3.0.0beta` and `mpv`.

plugins.daisuki: fix for truncated subtitles

---

docs/cli.rst
src/streamlink/plugins/stream.py
tests/test_plugin_stream.py

Added some notes in the docs about settings more complex parameters, lists, dicts, etc.
Made some slight changes to the `StreamURL` class and the associated tests, nothing significant.
See #640; as the documentation is not very clear for setting lists/multiple values.

docs: updated the docs for built-in stream parameters

---

src/streamlink/plugins/tvplayer.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_plugin_tvplayer.py

Some streams require a login to view, and others are protected by DRM and cannot be viewed. Two new options were added to support authentication for tvplayer.com:
- `--tvplayer-email` the email address for your tvplayer.com account
- `--tvplayer-password` the password for your tvplayer.com account
Non-DRM streams that require a login:
- tvplayer.com/watch/itv4
- tvplayer.com/watch/itv2
DRM streams:
- tvplayer.com/watch/spike
- tvplayer.com/watch/5star

plugins.tvplayer: support for authenticated streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/earthcam.py

_used the commit from beardypig as a base script and changed some stuff there_
_tested this new script on 0.3.2, even if this is 150+ commits behind master_
- __Added HLS__ streams
- Added a better "live" stream check
- __Fixed RTMP__ streams for live streams.
```
BEFORE:
"rtmp_domain": "rtmp://video3.earthcam.com",
"rtmp_path": "/fecnetwork/hdtimes10.flv",
AFTER:
"rtmp_domain": "rtmp://video3.earthcam.com/fecnetwork/",
"rtmp_path": "hdtimes10.flv",
```
- Some old links like `http://www.earthcam.com/newyears/ts2012/` won't work.
- snapshot mode won't work
- works only for cams that are hosted on EarthCam
Here is some debug data,
you can see here why the code changes are so ugly.
They have sometimes dead streams but it gets tagged as live etc.
__RTMP / HLS - Live Stream__
``` …
```

plugins.earthcam add support for earthcam.com streams | Fixed #342

---

src/streamlink/plugins/trt.py

As reported by @karlo2105 in #657.
The URL test was case-sensitive and would only work with Anasayfa, not anasayfa.
The base64 decoded data needed to be decoded to unicode to work in Python 3.

plugins.trt: make the url test case insensitive and fix py3 bug

---

src/streamlink/plugins/vidio.py

As reported by @karlo2105 in #662 :)
The URLs will have the language code `en` when viewing the English version of the website.

plugins.vidio: fix for regex, if the url is the english version

---

docs/plugin_matrix.rst
src/streamlink/plugins/animelab.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

As requested in #645 by @starchivore.
Two new options were added to support this plugin:
- `--animelab-email`: the email address to login to AnimeLab
- `--animelab-password`: the password for your AnimeLab account
The content is only available with a login.
While the website says that it's restricted to Australia and New Zealand, I was able to access using a UK proxy. I was not able to access using a US or German proxy.

plugins.animelab: added support for AnimeLab.com VOD

---

docs/plugin_matrix.rst
src/streamlink/plugins/npo.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

As reported in #638 the NPO.nl plugin has stopped working. 
This is a mostly total rewrite of the existing plugin to use the updated API. 
Subtitles can be enabled on the stream (if available) by using the `--npo-subtitles` option.

plugin.npo: rewrite of plugin to use the new API

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Adds a new option `--auto-version-check=(yes|no)` and suppresses the existing option `--no-version-check`. `--auto-version-check` defaults to `no`, and can re-enabled by setting `--auto-version-check=yes`.
See discussion in #590.

cli: disable automatic version checking by default

---

src/streamlink/plugins/goodgame.py

As reported in #670, by @loboque. 
goodgame.ru has re-enabled http support and no longer has only https URLs.

plugins.goodgame: support for http URLs

---

src/streamlink/plugin/plugin.py
src/streamlink/stream/hls.py
tests/test_plugin_stream.py

This allows developers to use a format string to name the streams, which allows more descriptive names. eg. {pixels}_{bitrate} can be used to produce 720p_3500k, 720p_4500k, which is useful if the streams are available in multiple resolutions at the same bitrate.
This feature can also be used when using the builtin stream plugins, eg.
```shell
streamlink "hlsvariant://test.se/master.m3u8 name_fmt=\"{pixels}_{bitrate}\""
```
The limitation being that the name string has to be enclosed by `"` quotes.
This should go someway to fixing issues like #540.

stream.hls: format string name input for parse_variant_playlist

---

src/streamlink/plugins/wwenetwork.py

Additional for #636, to expose the bit rate.

plugins.wwenetwork: use the resolution and bitrate in the stream name

---

docs/plugin_matrix.rst
src/streamlink/plugins/zdf_mediathek.py

- Removed unused import
- Removed "match" it was not used
- Added missing "name" it was not defined
- Added an **info message** for how to get a **valid link** for the tv channels, if someone uses
`streamlink https://www.zdf.de/live-tv`
- Fixed 403 Client Error (**Added headers for http.get**)
```
[cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/comedy/heute-show/heute-show-vom-24-februar-2017-100.html
error: Unable to open URL: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh (403 Client Error: Forbidden for url: https://api.zdf.de/tmd/2/portal/vod/ptmd/mediathek/170224_sendung_hsh)
```

plugins.zdf_mediathek Added missing headers for http.get

---

src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Some HLS streams have multiple audio sources that do not use the iso standard language codes, or use codes that are reserved for internal use,for example 'qaa' or 'qad'. These have to be interpreted on a case-by-case basis so there is no generic solution to picking the "right" one.
This adds a new option `--hls-audio-select` which overrides the audio stream and selects the one with the specific language code supplied. eg. `--hls-audio-select=qaa`.
Should fix #681 too :)

stream.hls: option to select a specific, non-standard audio channel

---

docs/plugin_matrix.rst
src/streamlink/plugins/bbciplayer.py
tests/test_plugin_bbciplayer.py

Support for live and VOD iPlayer streams.
Supported URLs include:
- bbc.co.uk/iplayer/live/bbcone
- bbc.co.uk/iplayer/live/bbctwo
- bbc.co.uk/iplayer/live/bbcone
- bbc.co.uk/iplayer/episode/b00ymh67/madagascar-1-island-of-marvels

plugins.bbciplayer: add support for BBC iPlayer live and VOD

---

src/streamlink/plugins/vaughnlive.py

This PR is a followup to #378 and should also fix #690. 
It works by downloading the SWF and searching for the info url, player version, etc.

plugins.vaughnlive: find the info url from the SWF file

---

src/streamlink/plugins/pluzz.py

This PR brings back HDS stream support, since the wway to retrieve the flash player on Pluzz has changed.

plugins.pluzz: fix SWF player URL search to bring back HDS stream support

---

docs/plugin_matrix.rst
src/streamlink/plugins/canlitv.py
tests/test_plugin_canlitv.py

Most of the streams works, sometimes there are two iframes.
Just use the link from the iframe and it will works most of the time.
Works only for HLS streams, won't work if the HLS file is broken.
```
canlitv.com
http://www.canlitv.com/24-tv
canlitv.life
http://www.canlitv.life/trt-haber
canlitvlive.co
http://www.canlitvlive.co/izle/ntv.html
canlitvlive.live
http://www.canlitvlive.live/izle/atv.html
ecanlitvizle.net
http://www.ecanlitvizle.net/trt-1-izle/
```
Fixed streamlink/streamlink#145

plugins.canlitv - Added new plugin canlitv

---

src/streamlink/plugins/bigo.py
tests/test_plugin_bigo.py

Fixes #722. Removed the old wrong url, made match more accurate by escaping url-dots. Added unittest.

plugins.bigo : More robust regex for url matching, added unittest

---

src/streamlink/utils/l10n.py
tests/test_localization.py

A fix for #718, if the OS returns a locale that cannot be parsed then the default locale will be used (currently US English).

utils.l10n: use default locale if the system returns an invalid locale

---

src/streamlink/plugins/rtve.py

As requested by @malvinas2 in #743.
Supports the `.avi` and `.mov` VOD streams on RTVE :)
There is an extra `HEAD` request performed for each stream URL as the API returns some junk/non-existent stream URLs (`1080p` for example), and the `HEAD` request identifies the junk URLs. 
These should work now:
- rtve.es/alacarta/videos/cantares/marife-triana-cantares-1978/1692684/
- rtve.es/drmn/embed/video/1692684
- rtve.es/alacarta/videos/version-europea/vida-facil/3453399/
- rtve.es/drmn/embed/video/3453399

plugins.rtve: support for avi/mov VOD streams

---

src/streamlink/plugins/periscope.py

Old periscope URL still works / is accessible. Using new one temporarily (?) during legal action in turkey. API URL (STREAM_INFO_URL) not interchangeable yet.

New Periscope URL #748

---

docs/plugin_matrix.rst
src/streamlink/plugins/googledocs.py
src/streamlink/plugins/googledrive.py

A plugin to support playing videos stored on Google Drive or Google Docs. Only videos that don't require authentication are supported.
(Super) Random Examples:
- drive.google.com/file/d/0B_0CLdJvAxuAM2hFWTJYOXhXVzQ/edit
- drive.google.com/file/d/0B2TQCD_DizLdOHQ5eVhjWk5EVTA/view

Support for videos on Google Docs/Drive

---

docs/plugin_matrix.rst
src/streamlink/plugins/aljazeeraen.py
src/streamlink/plugins/brightcove.py

Only the English variant of the website is support (aljazeera.com).
Live streams and VOD are both supported.
A support class `BrightcovePlayer` was added to simplify the process of playing streams hosted by Brightcove.
Example URLs:
- aljazeera.com/programmes/witness/
- aljazeera.com/live/
- aljazeera.com/programmes/the-big-picture/2017/02/big-picture-people-america-170216063801575.html
I plan to update the `tv8cat` plugin to use the new `BrightcovePlayer` class when/if it is merged.

plugins.aljazeeraen: support for live and vod streams from aljazeera.com

---

docs/plugin_matrix.rst
src/streamlink/plugins/deutschewelle.py

As requested in #756 by @roshavagarga.
Only supports the live streams, the different language streams are supported by including the query string argument `channel` in the URL.
Examples:
- dw.com/en/media-center/live-tv/s-100825 (default language)
- dw.com/en/media-center/live-tv/s-100825?channel=5 (German)
- dw.com/en/media-center/live-tv/s-100825?channel=1 (English)
- dw.com/en/media-center/live-tv/s-100825?channel=3 (Spanish)

plugins.deutschewelle: support for live dw streams

---

src/streamlink/stream/hds.py

Fixes a bug in the `HDSStream`, in some cases the end fragment can be past the end of available fragments which results in 404 errors and stutters in the stream.

stream.hds: ensure the live edge does not go past the latest fragment

---

docs/plugin_matrix.rst
src/streamlink/plugins/nbc.py
src/streamlink/plugins/nbcsports.py
src/streamlink/plugins/theplatform.py

Added a plugin to support NBC, NBCSports and thePlatform (which hosts the NBC videos). 
Only un-authenticated streams are supported, supporting cable logins would be a lot of maintenance. 
NBCSports was requested in #325.
Examples:
- nbc.com/the-tonight-show/video/vin-diesel-is-afraid-of-roller-coasters/3495809
- nbc.com/the-voice/video/the-battles-part-4/3489385
- nbcsports.com/video/league/nba

plugins.nbc: support vod from nbc.com

---

src/streamlink/plugins/dailymotion.py

Updated the method used to find the featured video for a channel so that it is more reliable. Also added a backup stream by way of the Chromecast stream URL that is embedded in the page, when all other stream URLs fail (as was the case in #766).

Dailymotion feature video and backup stream fallback

---

src/streamlink/plugins/playtv.py

This PR fixes the playtv plugin which is broken:
```
$ streamlink "http://playtv.fr/television/euronews" best
[cli][info] Found matching plugin playtv for URL http://playtv.fr/television/euronews
error: Unable to open URL: http://edge-02.playmedia-cdn.net/origin02/euronews_800/manifest.f4m?dar=ws&t=18ddf1b11ff0fbb27659a265b39d11263a96f51d89085ca5602bbe1b2cb7f2adcfd6b0980947f7a6f597bd95024faa49ec3f8a021de2b92113556e66a38547ddb2ca26ce9a72b8ddd99243d0efd1dbf46afec9c5fd5df6e9b1f1b9e8d3b988def790ac41bd7cb113cfa08bf6025c15b9d3ec46ec0e87950d (404 Client Error: Not Found for url: https://edge-02.playmedia-cdn.net/origin02/euronews_800/manifest.f4m?dar=ws&t=18ddf1b11ff0fbb27659a265b39d11263a96f51d89085ca5602bbe1b2cb7f2adcfd6b0980947f7a6f597bd95024faa49ec3f8a021de2b92113556e66a38547ddb2ca26ce9a72b8d …
```

plugins.playtv: disable HDS streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/pcyourfreetv.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_plugin_pcyourfreetv.py

This plugin add support for the German TV platform http://pc-yourfreetv.com/. It provides many TV channel streams from Germany, Switzerland, UK, France and Italy.
Although it's free, it requires a valid username and password (the plugin provides the corresponding options).
Once connected, all streams on the following page should be supported:
http://pc-yourfreetv.com/index_livetv.php?page_id=1

Add support for pc-yourfreetv.com

---

src/streamlink_cli/main.py

Fixes #781 as reported by @strudelkuchen. 
There is a couple other cases where possible a console.exit is better than to just log and exit with success. Namely [L310](https://github.com/Germandrummer92/streamlink/blob/48fb299c556c80a1dd6ac7727abb6f97b4355f9a/src/streamlink_cli/main.py#L310) and/or [L314](https://github.com/Germandrummer92/streamlink/blob/48fb299c556c80a1dd6ac7727abb6f97b4355f9a/src/streamlink_cli/main.py#L314). not sure though if those cases can occur with a "normal" close of the stream (e.g. the streamer stops it) in which case they should stay like they are, or if it's indicative of any error and it should exit with exit code 1.

Will exit with exit code 1 if stream cannot be opened.

---

src/streamlink/plugins/brightcove.py

This PR provides small improvements for the BrightcovePlayer class, required for a plugin I'm currently writing to support bfmtv.com.
* support for HLS playlist URLs with query strings.
For example, with the account ID 5067014665001 and the player ID 5080870408001, the API returns the following data:
```json
{
[...]
"account_id": "5067014665001",
"sources": [
{
"avg_bitrate": null,
"width": null,
"src": "https://rmcsporthdslive-lh.akamaihd.net/i/DVMR_BFMSPORT@182576/master.m3u8?__nn__=5078103454001&hdnea=st=1492124400~exp=1492128000~acl=/i/*~hmac=83b8f65edb5480d9cd997c203f0e1809353d0d9e2f166252775c7f31fc9545cc",
"size": 0,
"height": null,
"duration": -1,
"container": "M2TS",
"codec": "H264",
"asset_id": "5080888428001"
},
{
"avg_bitrate": null,
"width": null,
"src": …
```

plugins.brightcove: support for HLS stream URLs with query strings + RTMPE stream URLs

---

docs/plugin_matrix.rst
src/streamlink/plugins/bfmtv.py
tests/test_plugin_bfmtv.py

This plugin adds support for the French BFMTV group channels:
* [BFMTV](http://www.bfmtv.com/mediaplayer/live-video/)
* [BFM Business](http://bfmbusiness.bfmtv.com/mediaplayer/live-video/)
* [BFM Paris](http://www.bfmtv.com/mediaplayer/live-bfm-paris/)
* [RMC](http://rmc.bfmtv.com/mediaplayer/live-audio/) (radio)
* [BFM Sport](http://rmcsport.bfmtv.com/mediaplayer/live-bfm-sport/)
* [RMC Découverte](http://rmcdecouverte.bfmtv.com/mediaplayer-direct/)
* [01net.com](http://www.01net.com/mediaplayer/) (no live stream, only VOD)
Both [live](http://mediaplayer.bfmtv.com/directs/) and [VOD](http://www.bfmtv.com/mediaplayer/replay/) are supported, as well as any bfmtv.com/01net.com page containing a video.
Streams don't seem to be georestricted. Except for the [BFMTV live …

Add support for BFMTV group channels

---

src/streamlink/plugins/canalplus.py

This PR fixes the canalplus plugin which doesn't work anymore with live streams (VOD streams are OK):
```
$ streamlink http://www.canalplus.fr/pid3580-live-tv-clair.html
[cli][info] Found matching plugin canalplus for URL http://www.canalplus.fr/pid3580-live-tv-clair.html
error: Unable to open URL: http://hds_live_cpc_aka-lh.akamaihd.net/z/cpc_hds@182615/manifest.f4m (400 Client Error: Bad Request for url: http://hds_live_cpc_aka-lh.akamaihd.net/z/cpc_hds@182615/manifest.f4m?hdcore=3.1.0&g=HILLKWGDTICA)
$ streamlink http://www.c8.fr/pid5323-c8-live.html
[cli][info] Found matching plugin canalplus for URL http://www.c8.fr/pid5323-c8-live.html
error: Unable to open URL: http://hds_live_d8_aka-lh.akamaihd.net/z/d8_hds@182613/manifest.f4m (400 Client Error: Bad Request for url: …
```

plugins.canalplus: disable HDS streams for live videos

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
KNOWN_ISSUES.md

I originally just wanted to quickly add some missing stuff to the issue template, but I thought it would be better to have real contribution guidelines. I've copied the one that I'm currently using in the Twitch GUI repo and made a couple of changes. I also added a known issues file, which is currently just linking to the website, but could be improved later on, if desired.
I don't know whether this will help reducing the number of duplicates or whether it will increase the quality of issues, since people usually don't read stuff on the internet, but I think that it will at least not hurt having something more strict. If it is too strict or if there are parts that should be rewritten/reworded or if there are spelling mistakes, let me know or edit the PR. 😃

Improve contribution guidelines

---

docs/plugin_matrix.rst
src/streamlink/plugins/brightcove.py
src/streamlink/plugins/gardenersworld.py

Includes some improvements to the Brightcove player.
Examples:
- gardenersworld.com/how-to/grow-plants/two-ways-of-sowing-hardy-annuals-in-a-border/
- gardenersworld.com/how-to/grow-plants/how-to-plant-a-hydrangea/

plugin.gardenersworld: support for VOD on gardenersworld.com

---

docs/plugin_matrix.rst
src/streamlink/plugins/bloomberg.py
tests/test_plugin_bloomberg.py

This PR provides support for Bloomberg TV, as requested in https://github.com/streamlink/streamlink/issues/776. It supports:
* live TV/radio streams:
* https://www.bloomberg.com/live/europe
* https://www.bloomberg.com/live/us
* https://www.bloomberg.com/live/asia
* https://www.bloomberg.com/live/stream
* https://www.bloomberg.com/live/emea
* https://www.bloomberg.com/live/asia_stream
* https://www.bloomberg.com/audio (radio)
* VOD (https://www.bloomberg.com/news/videos/*/*), for example:
* https://www.bloomberg.com/news/videos/2017-04-18/is-may-s-call-for-an-early-election-a-risky-move-video
* https://www.bloomberg.com/news/videos/2017-04-18/full-show-bloomberg-daybreak-americas-04-17-video
Streams don't seem to be georestricted.

Add support for Bloomberg

---

src/streamlink/plugins/rtve.py

On some platforms catching OSError is not sufficient.

plugins.rtve: stop IOError bubbling up on 404 errors

---

src/streamlink/plugin/plugin.py
src/streamlink_cli/argparser.py
tests/test_streamlink_api.py

When changing the stream priority using `--stream-types` any stream types that are not explicitly included are ignored. For example if a user wants HTTP streams to be preferred and then HLS streams, with the other stream types in any order they might expect that `--stream-types "http,hls"` would be sufficient. However, any stream type not included in this list will be omitted. The default behavior for the `--stream-types` option means that other types are included.
This commit introduces a wildcard character (`*`), where any stream type not listed can be matched. For example, to order the streams with `HTTP`, then `HLS`, then others, the user could specify the `--stream-types` option as `"http,hls,*"`.
The documentation has been clarified to highlight the fact that other stream types not …

cli: add wildcard to --stream-types option

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Fixes #777 by allowing a URL to be set in a config file that can be loaded on demand using the @ syntax.

cli: add --url option that can be used in config files to set a URL

---

docs/plugin_matrix.rst
src/streamlink/plugins/canalplus.py
tests/test_plugin_canalplus.py

This PR enables support for the French TV news channel CNews in the canalplus plugin, as requested in https://github.com/streamlink/streamlink/issues/820.
It supports both [live](http://www.cnews.fr/direct) and [VOD](http://www.cnews.fr/videos).
Since all CNews streams are available on Dailymotion (as well as some streams for other channels supported by the plugin), the plugin will also returns Dailymotion streams if available.

plugins.canalplus: add support for cnews.fr + Dailymotion support

---

.travis.yml

Use the `pytest` runner for coverage (the same as regular tests). It should fix the travis build errors for python3.6 🤞

travis: use pytest to run the tests for coverage

---

.travis.yml
src/streamlink/stream/hds.py

This reverts commit 80eeba095c5a0a27f4c371c22a292b1d2f7656b4 to fix #817.
The issue is more complex that I realised, I think there might be an issue when calculating the fragment offset to find the current latest - however, I have not worked it out. As 80eeba095c5a0a27f4c371c22a292b1d2f7656b4 appears to break more than it fixes I suggest reverting it for now.

Revert "stream.hds: ensure the live edge does not go past the latest fragment"

---

docs/plugin_matrix.rst
src/streamlink/plugins/rte.py
tests/test_plugin_rte.py

This plugin adds support for the Irsh public TV video platform RTÉ Player, as requested in https://github.com/streamlink/streamlink/issues/819. It supports:
* live streams:
* RTÉ News: http://www.rte.ie/player/fr/live/7/
* RTÉ 1: http://www.rte.ie/player/fr/live/8/ (not available all the time)
* RTÉ 2: http://www.rte.ie/player/fr/live/10/ (not available all the time)
* RTÉjr http://www.rte.ie/player/fr/live/6/ (not available all the time)
* VOD; for example:
* http://www.rte.ie/player/fr/show/weather-30003847/10717886/
* http://www.rte.ie/player/fr/show/rte-news-six-one-30003249/10717883/
* http://www.rte.ie/player/fr/show/the-week-in-politics-extras-30004539/10717332/
Streams don't seem to be georestricted.

Add support for rte.ie/player

---

docs/plugin_matrix.rst
src/streamlink/plugins/oldlivestream.py
src/streamlink/plugins/tv1channel.py
tests/test_plugin_oldlivestream.py
tests/test_plugin_tv1channel.py

Some changes on **oldlivestream** so it will work for **tv1channel**
**oldlivestream**
- Support for `cdn` subdomains
- Support for `embed/` streams
**tv1channel**
- New Plugin for embeded streams on tv1channel.org _(youtube.com and livestream.com)_

[tv1channel.org] New plugin and some changes on [oldlivestream]

---

docs/install.rst
docs/plugin_matrix.rst
src/streamlink/plugins/ustreamtv.py

This is a complete re-write of the `UStreamTV` plugin. Only the mobile HLS streams are supported, not the custom fragmented flv/mp4 desktop streams. Some new features have been added though, eg. support for referrer locked embedded streams. There are future plans to support the desktop streams using this new API as well.  
This new plugin uses the new long polling UStream API (rather than the websockets API, to avoid adding a new dependency). The requirement for `python-librtmp` has been removed, and the docs updated to reflect this. 
If this is merged I suggest a new issue be created to track the addition of desktop stream support and the following issues be closed: #57, #58, #110, #129, #719, and #747.

Updated UStreamTV plugin

---

appveyor.yml

The trick appears to be to update `setuptools` :)

appveyor: update config to fix builds on Python 3.3

---

docs/plugin_matrix.rst
src/streamlink/plugins/facebook.py
tests/test_plugin_facebook.py

- Added @ZP [(gist)](https://gist.github.com/zp/c461761565dba764c90548758ee5ae9f) with a patch file / you can see in the [filehistory ](https://github.com/back-to/streamlink/blame/604806374d36f0e539d8fb42cdd9a5475244aa84/src/streamlink/plugins/facebook.py) that @ZP wrote the plugin 
- Added unittests
- Small regex change
since streamlink does not support DASH we can close the Issues
Fixed #226
Fixed #845

[Facebook] New plugin for 360p HLS streams

---

src/streamlink/plugins/artetv.py
tests/test_plugin_artetv.py

- New regex to match **new urls**
- New regex to match **old urls** (some of the old urls still work, some are 404)
- New regex to match **ignore playlists without video ids**
- **Removed rtmp** streams, I don't think they support rtmp anymore
- **Better result for streams**, it will now only show the streams with the same language as the url.
Before (all available languages, only two languages here, but there are streams with five)
```
[cli][info] Found matching plugin artetv for URL http://www.arte.tv/guide/de/074633-001-A/das-testament-des-dr-mabuse
Available streams:
406p_http_alt, 720p_alt, 406p_http, 360p_http_alt, 216p_http, 720p_http,
720p_http_alt, 216p_alt, 360p_http, 61k_alt, 360p_alt, 406p_alt, 216p_http_alt,
61k (worst), 216p, 360p, 406p, 720p (best)
```
After (only language …

[ArteTV] new regex, removed rtmp and better result for available streams

---

src/streamlink/plugins/tvplayer.py

Additional fix for #849, changed since the original PR #850.

plugins.tvplayer: allow https stream URLs

---

docs/plugin_matrix.rst
src/streamlink/plugins/tvnbg.py

Fixes #818. 
Simple plugin, supports:
- live.tvn.bg
- tvn.bg/live/

plugins.tvnbg: add support for live streams on tvn.bg

---

docs/plugin_matrix.rst
src/streamlink/plugins/apac.py

A simple wrapper to find the embedded UStream channel on a-pac.tv and hand it off to the `ustreamtv` plugin.

plugins.apac: add ustream apac wrapper

---

.travis.yml
docs/install.rst
script/bintrayconfig.sh
script/makeinstaller.sh

This PR removes the S3 deploy tasks in Travis and replaces them with Bintray deploy tasks. 
The Bintray deploy will only be performed when Travis is running a cronjob (which needs to be setup to run daily). I have already setup the `BINTRAY_USER` and `BINTRAY_KEY` variables for the travis build. 
I have created a redirect page for the existing S3-hosted installer, it will look like this: https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest2.exe
(@gravyboat, I still need to add you to the Bintray organisation)
Fixes #877

Deploy nightly builds to Bintray instead of S3

---

src/streamlink/plugins/nrk.py

The website uses `'` instead of `"` now.
streamlink/streamlink#859

[NRK.NO] fixed regex for _api_baseurl_re

---

.travis.yml
docs/install.rst
script/bintrayconfig.sh
script/bintrayupdate.sh

I have added a script to update the release notes for the Bintray nightly. It produces a log similar to the one below:
> 
> **This build includes the following changes since [v0.5.0](https://github.com/streamlink/streamlink/releases/tag/0.5.0)**
> 
> 
>  * [`b11ae2a7`](https://github.com/streamlink/streamlink/commit/b11ae2a7784a179b7cc31dbd90880c3fe151c139) build: update the bintray release notes for nightlies
>  * [`5d6fff0b`](https://github.com/streamlink/streamlink/commit/5d6fff0b5935322a5f3f9211b8424ee8473848b3) utils.crypto: fix openssl_decrypt for py27
>  * [`fa2a6a89`](https://github.com/streamlink/streamlink/commit/fa2a6a897ad05d4d4a2ddd0ca855c90ebc918bad) plugins.streann: support for ott.streann.com
>  * [`0648c388`](https://github.com/streamlink/streamlink/commit/0648c388fcfd8c4c …

build: update the bintray release notes for nightlies

---

docs/plugin_matrix.rst
src/streamlink/plugins/hitbox.py

hitbox.tv URLs will continue to work, and new smashcast.tv URLs are newly supported.
To fix #904.

plugins.hitbox: add support for smashcast.tv

---

src/streamlink/plugins/euronews.py
tests/test_plugin_euronews.py

The euronews plugin is broken for live streams, due to API changes (VOD streams are still OK).
```
$ streamlink "http://fr.euronews.com/live"
[cli][info] Found matching plugin euronews for URL http://fr.euronews.com/live
error: Unable to validate JSON: Unable to validate key 'primary': Type of 'http://euronews-fr-p7-cdn.hexaglobe.net/1c52769160a4c3fc93b932305f4e37dc/59136712/euronews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8' should be 'dict' but is 'str'
```
This PR fixes the plugin to use the new API scheme for live streams. Unit tests are also added.

plugins.euronews: update for live API change

---

src/streamlink_cli/utils/http_server.py

The exception generated when closing a socket that is already closed if different in Python 2 and Python 3. This PR updates the `except` statement to handle both cases.
Intended to fix #919

http_server: handle socket closed exception for Python 2.7

---

src/streamlink/plugins/bbciplayer.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This PR sits on-top of the earlier PR (#925) and adds login support. Two new options were added to facilitate this:
* `--bbciplayer-username` the email/username used to register with bbc.co.uk
* `--bbciplayer-password` the password corresponding to that bbc account
The login is currently optional, but will be enforced at some point in the future ("weeks" according to the BBC). 
I have add a info level log message that states that the user should have a TV License.

plugins.bbciplayer: add login support

---

src/streamlink/plugins/bbciplayer.py

The BBC is changing the iplayer system so that it will require a login to watch video content, they appear to have changed the site a bit in preparation for this.
Fixes #922

plugins.bbciplayer: update to reflect slight site layout change

---

docs/install.rst

I think the homebrew package should be listed on the website.
This is the homebrew formula:
https://github.com/Homebrew/homebrew-core/blame/master/Formula/streamlink.rb
Unfortunately, there's no better way of linking to the package. And since there are no dedicated maintainers, there's no one to be added to the package maintainer list.
#398 can be closed then, I guess.
Oh, and I also added a link to the main chocolatey website. I think it's confusing to primarily link to the package url.

Homebrew package

---

docs-requirements.txt
docs/conf.py
docs/docutils.conf

Fixes the documentation error in #934. 
For some reason `html_use_smartypants` has started working and it's broken the `--` in the command line options. This PR updates the `conf.py` and adds `docutils.conf` to disable `smart_quotes`.

docs: update Sphinx config to fix the rendering of --

---

docs/ext_argparse.py
src/streamlink_cli/argparser.py

See https://github.com/streamlink/streamlink/pull/896#issuecomment-303317718...
I should have built the docs myself before merging, sorry.
Parameters will now only be linked if the text is not indented. I couldn't find a better way of fixing this. The order of regexp substitutions needed to be changed, so that text inside normal and note blocks can still link to parameters.
I've also fixed the missing closing angle bracket and the unnecessary quotation in the first --player example.
The docs are now looking good to me, but there's a chance I have missing something, so please check it first before merging.

docs: fix parameters being linked in code blocks

---

docs/plugin_matrix.rst
src/streamlink/plugins/pluzz.py
tests/test_plugin_pluzz.py

This PR adds support for regional France 3 stations, available on france3-regions.francetvinfo.fr, to the pluzz plugin.

plugins.pluzz: add support for regional France 3 stations

---

docs/cli.rst

Lintian was reporting a typo about "specifiying" and I found neverthless in cli.rst, so let's fix them.

docs: fix typo: specifiying, neverthless

---

docs/ext_argparse.py
src/streamlink_cli/argparser.py

- Reword several parameters.
- Add missing examples.
- Fix format of the default value of some parameters.
- Fix missing punctuation.
- Fix invalid text formats (notes).
- Wrap text lines which exceed 80 chars per line.
Resolves #751

Improve CLI documentation

---

script/makeinstaller.sh

`pkg_resources` (`setuptool`) and `requests` have changed the way their packages are structured so that they no longer vendor packages, this means those previously vendored packages have to be included by the installer builder.
This should fix #945, plus an unreported issue with `requests`.

win32: fix missing modules when using windows installer

---

src/streamlink/plugins/dailymotion.py

Fixed broken livestream from `http://www.dailymotion.com/video/x3b68jn`
Not sure why this .f4m file is a .m3u8 file,
most likely a bug on dailymotion end
as long as they don't fix it, streamlink should just try to open hls instead of hds if it fails for livestreams.
Fixed #959

[dailymotion] fix for broken .f4m file that is a .m3u8 file 

---

docs/plugin_matrix.rst
src/streamlink/plugins/tv5monde.py
tests/test_plugin_tv5monde.py

This plugin adds support for the French-speaking channel network [TV5 Monde](http://www.tv5monde.com/).
It supports both [live](http://live.tv5monde.com/fbs.html) and VOD streams from:
* http://www.tv5monde.com/
* http://www.tv5mondeplus.com/
* http://www.tv5mondeplusafrique.com/
Notice that the live stream is geo-restricted to France, Belgium and Switzerland.

Add support for TV5Monde

---

src/streamlink/plugins/pluzz.py
tests/test_plugin_pluzz.py

Hello,
As the French Open (Roland Garros) is currently airing, Pluzz plugin dont work on the network sport dedicated website "sport.francetvinfo.fr".
This commit just adds the ability to retrieve the stream from this website.
Best regards.

Add capability of extracting current sport.francetv stream

---

src/streamlink/plugins/youtube.py

Solution for #978, tiny 3 character commit to allow removing the `/c/` prefix from YouTube live channel links.

Allow live YouTube channel links without '/c/' prefix

---

src/streamlink/plugins/tvplayer.py

The name of a parameter was changed in the API. 
Fixes #988

tvplayer: updated to match change token parameter name

---

src/streamlink/plugin/api/validate.py
src/streamlink/plugins/webtv.py
src/streamlink/utils/crypto.py

Some (all?) of the stream URLs are now encrypted using AES encryption - the key and IV are prepended to the cipher text.
Added some additional util functions to support the decryption.
- An unpad method which performs "standard" pkcs5 unpadding.
- A new validation rule for text; `validate.contains` which validates that the string contains a given substring.

plugins.webtv: decrypt the stream URL when applicable

---

script/makeinstaller.sh

Should fix the broken builds... 
Seems to be related to #969, I think it might be a travis thing ...

win32: update the dependencies for the windows installer

---

src/streamlink/plugins/canlitv.py
tests/test_plugin_canlitv.py

On some pages there is a space before the `:`, after `file`. Added a few tests for the regex too.

plugins.canlitv: simplified and fixed the m3u8 regex

---

src/streamlink/plugins/rtlxl.py

FYI: I made the original Livestreamer plugin as well. Recently, RTL made some changes to the website and the plugin stopped working. These changes make the plugin function again.

Restore support for RTL XL

---

docs/plugin_matrix.rst
src/streamlink/plugins/ufctv.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Add two new arguments to support authentication:
- `--ufctv-username`: The username used to register with ufc.tv.
- `--ufctv-password`: A ufc.tv account password to use with --ufctv-username.
Premium, free and live streams are all supported. Fixes #1029 as requested by @SeanDunford.

plugin.ufctv: support for free and premium vod/live streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/radionet.py
tests/test_plugin_radionet.py

This PR provides support for [radio.net](http://radio.net) (and its locale versions radio.(at|dk|de|fr|it|pt|se|es|pl). radio.net offers free and legal access to radio stations from all over the world.

Add support for radio.net

---

docs/plugin_matrix.rst
src/streamlink/plugins/deutschewelle.py
tests/test_plugin_deutschewelle.py

This PR extends support for:
* [VOD](www.dw.com/en/media-center/all-media-content/s-100826?type=18)
* [Audio streams](http://www.dw.com/en/media-center/all-media-content/s-100826?type=17)
For some video streams, both bitrate and video width are provided by DW. To select the best stream when some videos have the same bitrate, I'm "cheating" by summing bitrate and width (see line 117 in deutschewelle.py). Is there a better way to manage stream quality based on these two parameters?

plugins.deutschewelle: add support for VOD/audio streams

---

src/streamlink/plugins/teamliquid.py
tests/test_plugin_teamliquid.py

Here's the plugin I wrote for teamliquid.net (w/ some help from https://github.com/back-to).
It works with both afreecaTV and twitch.tv streams embedded on teamliquid.net (which covers all streams on teamliquid.net afaict).

A plugin for teamliquid.net

---

setup.py

This is a change to the required version of `requests` to exclude some versions that give an unwanted warning about insecure requests for twitch.tv, fixing #963.

setup: exclude requests version 2.16 through 2.17.1

---

docs/plugin_matrix.rst
src/streamlink/plugins/zattoo.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_plugin_zattoo.py

**New plugin for zattoo**
- zattoo.com
- tvonline.ewe.de
- nettv.netcologne.com
Should work fine. I tested it over the last weeks.
---
Some part of this code is is not necessary, but it's **easier to debug if something fails**.
like this one, you can see what channels are available in your country.
```py
zattoo_list = []
for c in c_list:
zattoo_list.append(c['display_alias'])
if c['display_alias'] == channel:
cid = c['cid']
self.logger.debug('Available zattoo channels in this country: {0}'.format(', '.join(sorted(zattoo_list))))
```
---
For every login it will **cache** the cookies for **24h**.
If you want to use a different Account you need to wait 24h or delete `plugin-cache.json`
---
Fixed #804

[zattoo] New plugin for zattoo.com / tvonline.ewe.de / nettv.netcologne.com

---

src/streamlink/plugins/hitbox.py

Should fix #1078, `media_hosted_media` is not always included in the API response and this should be handled.

plugins.hitbox: fix bug when checking for hosted channels

---

docs/_applications.rst
docs/applications.rst
docs/conf.py
docs/index.rst
docs/thirdparty.rst

Resolves #778 #873 
This adds a new **Third Party Applications** page to the bottom of the main menu. Should this be added at a different position or is this okay?
I'm not sure if I'm too strict here with the included rules (see the reST comment block), so if anybody has any concerns or suggestions here, please let me know.
Unfortunately, I don't know how to disable the generation of submenu items (it also automatically highlights the first item). The rendered page looks like this:

docs: add official and 3rd-party applications list

---

src/streamlink_cli/main.py

The deprecation warning has been removed from the `--http-{cookies,headers,query-params}` options. The options are not listed in the help or in the docs, but they will continue to work.
They should be considered unsupported.
Fixes #573.

cli: remove the deprecation warnings for some of the http options

---

setup.py

This should resolve the issues some people are having with HTTPS websites when using older versions of Python 2.7. As best I can tell the any version before 2.7.10 is affected.
See discussion in #1114.

Resolve InsecurePlatformWarnings for older Python2.7 versions

---

src/streamlink/plugins/twitch.py

Re-enables the certificate verification for the twitch API calls. 
The `--http-no-ssl-verify` flag can be used if users have incompatible versions of OpenSSL or if they want to use a MITM proxy. 
Fixes #966, should also fix #963.

plugins.twitch: enable certificate verification for twitch api

---

docs/donate.rst

This goes along with #1122, if anyone has feedback on the wording please let me know. I considered adding sections for tips based on the payment method, but figured that was too complicated. Open Collective is still using PayPal for payouts so I know some of us can't benefit from it (myself included) but at least we can get the ball rolling so people can make credit card donations easily.

Update donation docs to note open collective

---

script/makeinstaller.sh
setup.py
src/streamlink/plugins/vaughnlive.py

Supports the new vaughnlive websockets API for both RTMP and HLS streams. A new dependency is added to support this `websocket-client`.
Fixes #1034

plugins.vaughnlive: support for the new vaughnlive website layout

---

docs/cli.rst
script/makeinstaller.sh
setup.py
src/streamlink/session.py

Any proxy type that is supported by `requests` can be used.
For example, SOCKS proxies are support by `requests`, and can be used:
- `--http-proxy "socks5://[user:password@]host:port"`
- `--https-proxy "socks5://[user:password@]host:port"`
to set streamlink to use socks proxies for http and https.
Support for SOCKS proxies provided by an extra dependency: `PySocks` via `requests[socks]`.
Fixes #1138.

cli: support for SOCKS proxies

---

src/streamlink/plugin/plugin.py
src/streamlink/plugins/hds.py
src/streamlink/plugins/hls.py
src/streamlink/session.py
tests/test_session.py

Plugins can return a priority level for the URLs that they support.
If two plugins match the same URLs then the plugin with the higher priority will be used. This means that the built-in HLS and HDS plugins can support `.m3u8` and `.f4m` URLs with a lower priority without causing issues with overlapping URL patterns.
By default plugins return NORMAL priority for any URL. It is expected that the `priority` method will only be called with URLs that are actually supported by the plugin.
Thoughts?

plugins: add priority ordering to plugins

---

src/streamlink/plugins/picarto.py

As mentioned in #1193 the page always contains the string "does not exist". Changing it to compare against the full string on the 404 page fixes the issue.

Resolve issue regarding picarto.tv

---

src/streamlink/plugins/bloomberg.py

The bloomberg plugin currently cannot find any sources for the live streams because a regular expression matches an unintended part of the page. This PR fixes this issue.

Fix player URL extraction in bloomberg plugin

---

src/streamlink/plugins/bigo.py
tests/test_plugin_bigo.py

This is a workaround for issue #1031 since FLV streaming is broken

Add support for hls streams in bigo

---

src/streamlink/plugins/bbciplayer.py

When old episodes are made available again (because they were on TV again) they sometimes have rtmp streams available as well, this accounts for the slight difference in the data returned by the API in such cases.

plugins.bbciplayer: support for older VOD streams

---

script/makeinstaller.sh

Noticed that the PySocks module isn't actually included in the Windows installer version :) The `win-inet-pton` module isn't required as we're using Python 3 for the installer version.

installer: include the socks proxy modules

---

docs/cli.rst

Hi,
A codeblock without an empty new line before cause bad docs generation in man and html formats.
This causes a `man` warning: `warning: macro `.' not defined`.
The manpage contains `.. code\-block:: console` which it does not recognize.
In html format, the  generated line is `For example: .. code-block:: console` and the following codeblock is not correctly formatted.
When adding a empty new line before (as this PR does), the docs are correctly generated.
I've not investigated much if this is a sphinx issue or not (as I don't know much reStructuredText language) but this fix docs generation.

docs: add new line before codeblock to fix them

---

src/streamlink_cli/main.py

Adds sys.exit(130) where applicable after a KeyboardInterrupt occurs. Notably there are two consecutive KeyboardInterrupt checks; this commit causes a code 130 even if only the first occurs and not the additional "panic" one.
130 is the correct exit code in this case because KeyboardInterrupt causes a SIGINT which has value n=2 and the appropriate exit code is 128+n (see: http://tldp.org/LDP/abs/html/exitcodes.html)
Fixes #1234

exit with code 130 after a KeyboardInterrupt

---

docs/ext_argparse.py

Sphinx 1.6 has deprecated `sphinx.util.compat.Directive` and it will be removed in Sphinx 1.7.
Use the class in `docutils` as recommended by Sphinx.
Sphinx warning was:
```
/usr/lib/python3/dist-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
RemovedInSphinx17Warning)
```
Detected with Sphinx 1.6.4.
Since Sphinx 1.0b1, sphinx.util.compat.Directive is exactly the one implemented in docutils 0.5+ (https://github.com/sphinx-doc/sphinx/commit/414816bb373379cf1ca8f4b6ef21a329fff1270f#diff-0001522a669602c5402157e0923a3193L40).

Fix sphinx warning on Directive class

---

setup.py

Include `PySocks` instead of `requests[socks]`, due to a pip bug. Also include the `win-inet-pton` module for old versions of Python on Windows.
As discussed in #1291, should fix #1316 (see #1240, #1217, #1219).

setup: fix PySocks module dependency

---

src/streamlink/plugins/showroom.py

A recent API change eliminated the endpoint this plugin used. This PR updates it to use the new endpoint, provided by @back-to 
Fixes #1290

plugin.showroom: update to new api

---

.travis.yml
appveyor.yml
docs/install.rst

Remove Python 3.3 from the automated testing on travis and appveyor.
fixes #1348 and the build issues with #1345

EOL Python 3.3

---

src/streamlink/plugins/kanal7.py

They changed the way the player is setup to get the streaming URL.
Fixes #1350

plugins.kanal7: update to stream player URL config

---

src/streamlink/plugins/pluzz.py

This PR fixes broken support for France 3 Régions streams:
```
$ /usr/bin/streamlink http://france3-regions.francetvinfo.fr/bourgogne-franche-comte/tv/direct/franche-comte
[cli][info] Found matching plugin pluzz for URL http://france3-regions.francetvinfo.fr/bourgogne-franche-comte/tv/direct/franche-comte
error: Unable to open URL: http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=SIM_franche_comte@Regions"></a><div id="lavideo"></div></div><div class="emission-direct-container"><div class="emission-horaire fr3r-livetv-infos"> <span class="tab-hour text-light fr3r-livetv-program-time"></span><p class="tab-emission-title text-medium fr3r-livetv-program-name"> <a href="http://videos.francetv.fr/video/SIM_franche_comte (403 Client Error: Forbidden for url: …
```

[plugins.pluzz] Fix video ID regex for France 3 Régions streams

---

src/streamlink/plugins/huya.py

Fixes #1364 by setting the stream URL to `http` if no scheme is given, eg. `//`.

plugins.huya: fix stream URL scheme prefix

---

docs/plugin_matrix.rst
src/streamlink/plugins/canalplus.py
tests/test_plugin_canalplus.py

C+ has centralized its replay services in mycanal.fr, and remove the old ones (c8.fr, cstar.fr).
Due to changes, this plugin cannot handle live url (for the moment).

[canalplus] Update plugin according to website changes

---

docs/install.rst
src/streamlink/plugins/ceskatelevize.py
src/streamlink/plugins/huomao.py
src/streamlink/plugins/media_ccc_de.py
src/streamlink_cli/argparser.py

These typos were detected using `codespell` tool when running `check-all-the-things`.

Fix various typos in comments and documentation

---

src/streamlink/session.py
src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

It's not really seeking because you can only skip the beginning and end of the streams, but it should go some way to bridging the gap between no seeking and full seeking support. The seeking support is also added to the HLSStream API - which I added for forthcoming plugins. 
I don't expect this to be merged right away, but rather I'm opening it now because it's been in the works and on-hold for a while and I'd like some feedback.

HLS "Seeking" support

---

docs/install.rst

- Cleaned up the whole section
- Added a table in order to match the other sections. The forced line breaks and short sentences are needed here because of Sphinx' default table styles which I didn't want to modify
- Changed the link to the the nightly build (resolves #1333)
- Reworded the `PATH` env var part

docs: rewrite Windows binaries install section

---

dev-requirements.txt
src/streamlink/stream/hls.py
tests/test_hls.py

According to the the HLS RFC [0], AES-128 streams use PKCS#7 padding.
This commit implement PKCS#7 padding decoding.
Although streamlink wasn't implementing this padding, MPEG TS streams
are working because they use a synchronization byte so the non-removed
padding was ignored by video players.
This require to have the full segment buffer instead of iterating the
result in chunks, but requests was still downloading the full segment in
memory as stream=True is not set. See [1].
----
I found that by using this test:
Execute this gist: https://gist.github.com/amurzeau/78e9f9ce958a562e86bba46b18ea8a7f
This script does:
- Create a fake stream
- Encrypt it
- Create HLS playlists for that stream
- Use streamlink on it and output the result in a file
- Compare the streamlink output with concat …

Implement PKCS#7 padding decoding with AES-128 HLS

---

docs/install.rst

Add instructions for installation on Debian in docs.
Note: the package is only available in sid/unstable as of now and in testing in around 10 days.
It will reach stable distribution once the next one (Buster) is released.

docs/install: add Debian instructions

---

docs/install.rst

After a check of which distribution uses sudo with their default
installation, I found that only Ubuntu and Solus use sudo by default.

docs/install: use sudo for Ubuntu and Solus

---

ISSUE_TEMPLATE.md
src/streamlink_cli/main.py

Maybe not exactly what was requested,
but this won't break any third party applications
_Example:_
```
[cli][debug] OS:         Linux-4.14.4-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.9.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
```
Fixed https://github.com/streamlink/streamlink/issues/1323

[cli-debug] Show current installed versions with -l debug

---

src/streamlink/plugins/orf_tvthek.py
src/streamlink/session.py

The server hosting the HLS playlists for tvthek.orf.at does not respect HTTP connection persistence. It closes the connection after a second request is made instead of responding to the request, making streamlink crash with an error while stream sources are collected.
This pull request adds a function to swap out an existing HTTP session for a new one to the Streamlink session object, and calls this function in the appropriate place to have stream enumeration succeed in the orf_tvthek plugin.

[orf_tvthek] Work around broken HTTP connection persistence

---

src/streamlink/stream/hls.py
src/streamlink/stream/segmented.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

You can **ignore segment** names that might **corrupt** or **lag** your output
- this will freeze the player until there is a valid segment name
- this will not add the segment to an output file,
so it won't be damaged and can be edited.
Note: The `--hls-timeout` must be increased, to a time that is longer
than the ignored break.
Example:
`streamlink URL best --hls-segment-ignore-names 000,001,002
--hls-timeout 1200`
This will ignore every segment that ends with 000.ts, 001.ts and 002.ts
---
some names/text can be changed, if someone has a better idea.
---
Hey @RedPenguin2
it would be nice if you could test this,
if you don't know how to, i can help you.
`streamlink http://www.tbd.com best -l debug --hls-segment-ignore-names 0000,0001,0002 -o test.ts --hls-timeout 2400`
change the url …

[hls] New option --hls-segment-ignore-names

---

src/streamlink/plugins/zattoo.py
tests/test_plugin_zattoo.py

Ref streamlink/streamlink#1263

[zattoo] Added support for zattoo recordings

---

src/streamlink/plugins/ruv.py
tests/test_plugin_ruv.py

Hey all,
I have updated the RUV plugin since the current version is highly out-of-date. This PR fixes #643 and contains both many bug fixes and a new feature (support for VODs with multiple qualities available). I have also removed the RTMP stream, since RUV no longer provides that stream.
Note that these streams are usually restricted to Icelandic IP addresses. The only exception is when RUV are showing something they have a full copyright of (i.e. their evening news). Here are some example usages:
**Live stream**
`streamlink http://ruv.is/ruv best`
**Sarpurinn/VOD (with 240p, 360p, 480p, 720p and 1080p available)**
`streamlink ruv.is/spila/ruv/ol-2018-skidafimi-kvenna/20180216 best`
**Sarpurinn/VOD (with only 576p available)**
`streamlink …

Ruv plugin updated. Fixes #643.

---

.coveragerc
.gitignore
.travis.yml
appveyor.yml
codecov.yml

- use **pytest** not coverage for windows
- fixed not working linux upload, only windows upload worked before this.
- `pip install -e .` or pytest upload won't work
- don't run tests twice in travis
- don't ignore init files
- codecov target to 30
- ignore _version.py for #1413
---
`pip install .` will fix the 3.7 build,
`python setup.py install` is still broken on 3.7
---
codecov will go down from 50% to ~30%
with this it will now show the real %, because it will upload the 0% files as well.

[codecov] use pytest and upload all data

---

docs/plugin_matrix.rst
src/streamlink/plugins/idf1.py
tests/test_plugin_idf1.py

This plugin adds support for the French-local TV channel [IDF1](http://www.idf1.fr/).
It supports both [live](http://www.idf1.fr/live) and [VOD](http://www.idf1.fr/videos) streams.

Add support for IDF1

---

src/streamlink/plugins/dogan.py

Plugins get loaded in streamlink/session.py with `imp.load_module`.
`imp.load_module` uses the system locale to read the given python file.
The only way to ensure this will never fail whatever the locale the user
uses is to either:
- Avoid imp.load_module and use something else to be determined
- Use only ASCII characters in plugins
`imp.load_module` might be required to support both python 2 and 3
(unless an alternative exists ?).
So replace the non ASCII character with an ASCII one.
For reference, I encountered a load_module failure in the
test_plugins.py test, when loading this plugin in a containerized
environnement (LC_ALL=POSIX)

Avoid use of non-ASCII in dogan plugin

---

src/streamlink/plugins/tvrplus.py
tests/test_plugin_tvrplus.py

`best` and `worst` won't work, the source is **404**
`streamlink "http://www.tvrplus.ro/live-tvr-international" 1200k`
```
360k (worst) - broken 404
1200k - works
2500k (best) - broken 404
```
Closes https://github.com/streamlink/streamlink/issues/1435

[TVRPlus] Fix for hls_re and use headers for HLSStream

---

src/streamlink/stream/ffmpegmux.py

if a ffmpeg stream gets closed with `ctrl + c` the terminal will get invisible,
this patch will fix it.

[ffmpegmux] Fixed bug of an invisible terminal

---

src/streamlink/plugins/youtube.py
tests/test_plugin_youtube.py

MuxedStream won't work because the HTTPStream's are chunked without a reload,
so it won't work currently.
But **HLS** streams are working with **60 FPS** now, so there is no need for the DASH stream.
- added some debug messages
- added url tests
moved code from `_get_streams` into `_create_adaptive_streams`
closes #1520

[youtube] Don't use MuxedStream for livestreams

---

docs/plugin_matrix.rst
src/streamlink/plugins/rtbf.py
tests/test_plugin_rtbf.py

This plugin adds support for the Belgian public TV video platform RTBF Auvio, as requested in https://github.com/streamlink/streamlink/issues/1367. It supports:
* live video streams (some streams may be georestricted to Belgium or EU): https://www.rtbf.be/auvio/direct#/
* VOD: https://www.rtbf.be/auvio/emissions
* live radio: http://www.rtbfradioplayer.be

Add support for RTBF

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Sometimes I want to launch streamlink before a stream has gone live. The --retry-streams argument lets me loop until the stream starts, but there was no way to tell it to give up after a while. I've added a new argument, --retry-fetch-max, to make streamlink only try N fetch retries before giving up.
I also reworded the documentation for --retry-streams and --retry-open, since I had gotten confused and thought that --retry-open did what I've now done with --retry-fetch-max.
Suggestions / criticisms welcome. I was thinking about implementing an exponential backoff, but I figured I'd keep it simple for now.

New option to limit the number of fetch retries

---

.gitignore

This PR improves the gitignore file, which is missing a list of common OS and editor cache files and directories.
My main intention was to just ignore the config folder of PyCharm and since this is the same as all JetBrains IDEs (.idea), I took what I already had from my other projects and added these common files and directories here. The entire gitignore file could be further improved (and cleaned up) with the help of https://github.com/github/gitignore, if desired.

Add OS + editor file/directory names to .gitignore

---

src/streamlink/plugins/rtve.py
src/streamlink/utils/__init__.py
tests/test_utils.py

This adds an argument to `parse_xml` to try to fix invalid character entities, for example when a plain `&` is in an XML document, ie. it is poorly formed. 
Fixes #1577

plugins.rtve: fix invalid character entities

---

src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
tests/test_hls.py

This changes the --hls-audio-select flag to take a comma-separated
list of audio source names or language codes. This will cause the
ffmpeg muxer to include all selected audio tracks in the output
stream. It also changes so the option takes an asterisk character to
select all available audio tracks.

stream.hls: change --hls-audio-select to take a list and wildcard

---

appveyor.yml

```
File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\python35\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Python35\Scripts\pip.exe\__main__.py", line 5, in <module>
ImportError: cannot import name 'main'
Command exited with code 1
```

[build] Fixed AppVeyor build pip10 error

---

.travis.yml
script/bintrayconfig.sh
script/bintrayupdate.sh

This updates the Travis/BinTray deploy to stop deploying `streamlink-latest.exe` and to delete old nightly versions so we don't run out of quota on BinTray.

build/deploy: do not deploy streamlink-latest, and remove old nightlies

---

docs/plugin_matrix.rst
src/streamlink/plugins/abweb.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_plugin_abweb.py

> AB Groupe
> The AB is a French business group in the field of broadcasting.
> https://en.wikipedia.org/wiki/AB_Groupe
**Requires a login and a subscription.**
Username/Password is only required for the first login every 24h,
it will cache the required cookies and force a relog every 24h.
```
$ streamlink "http://www.abweb.com/BIS-TV-online/bistvo-tele-universal.aspx?chn=ab1" best
[cli][info] Found matching plugin abweb for URL
http://www.abweb.com/BIS-TV-online/bistvo-tele-universal.aspx?chn=ab1
[plugin.abweb][info] Attempting to authenticate using cached cookies
[cli][info] Available streams: 75k (worst), 240p, 360p, 432p, 720p (best)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Closing …
```

[ABweb] New plugin for BIS Livestreams of french AB Groupe

---

src/streamlink/plugins/live_russia_tv.py
tests/test_plugin_liverussiatv.py

Adds support for Russian TV channels from https://live.russia.tv/
E.g.
$ streamlink https://live.russia.tv/index/index/channel_id/4 best

plugins.live_russia_tv New Plugin implementation for live.russia.tv

---

src/streamlink/plugins/tf1.py
tests/test_plugin_tf1.py

Fixes #1659.
The set of pages supported is hardcoded because some need to be remapped, any others that are not listed should be considered unsupported. 
Update: Reverted the site URL regex back to the original style of matching all channels - it's more robust and gives better error messages if new channels are added or renamed.

plugins.tf1: add lci url to the main tf1 domain

---

docs/cli.rst

Fixes #1654 by updating the docs to include a note detailing the difference in DNS lookup handling for the different socks scheme.

docs: add a note about socks4 and socks5 vs socks4a and socks5h

---

docs/plugin_matrix.rst
tests/test_docs_plugins.py

I wrote a test that tests to ensure that each plugin exists in the plugin matrix in the docs (excluding the built in plugins). I found these plugins didn't have a row in the docs: live_russia_tv, ok_live, piczel, streann, and teamliquid. I updated it as best I could, please point out an omissions/mistakes.

tests: test to ensure that all plugins are listed in the plugin matrix

---

src/streamlink/plugins/bilibili.py

BiliBili's player api always returns the stream URLs even though the live is stopped.
It could be avoided via the field `live_status` which is returned by the room api.

plugins.bilibili: fix checking live status

---

src/streamlink/plugins/bbciplayer.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

New option added to enable HD streams for some live channels (BBC One, BBC Two): `--bbciplayer-hd`. Note that not all programmes are broadcast in HD.
Sped up the stream enumeration by ignoring duplicate manifest entries, reduced number of stream looks from ~70 to ~8 on live streams.
Fixes #1033, with the `--bbciplayer-hd` option.

plugins.bbciplayer: enable HD for some channels and speed up start-up

---

script/bintrayconfig.sh
script/makeinstaller.sh

build: use _ instead of + in the Windows installer exe filename

---

tests/test_docs_plugins.py

Ensure that each plugin that is listed in the plugin matrix in the docs actually exists, for example if a plugin was deleted but not removed from the plugin matrix. It's a complimentary test to the one added in #1673.

tests: test to ensure each plugin listed in the plugin matrix exists

---

src/streamlink/plugins/rtve.py
src/streamlink/utils/__init__.py

Slight change in the way the stream URLs are listed.

plugins.rtve: fix for m3u8 stream url formatting

---

examples/opencv-face.py

As this has come up a couple of times (#857 and #1386), I decided to make a more expanded example. 
In this example a stream from streamlink is read by `opencv` (`opencv-python` module is required), and the faces in the stream a detected and highlighted in real-time. It might not work for every stream, and it doesn't support any special streamlink options (proxies, etc.) - but it's an example. Plus, it was quite fun to do and it's amusing to watch 😄

example: added an opencv face detection example

---

docs/plugin_matrix.rst
src/streamlink/plugins/onetv.py
tests/test_plugin_onetv.py

Support for 1tv.ru as requested in #1352, also supports a couple of other live streams and VOD from 1tv.ru.

plugins.onetv: add support for 1tv.ru and a few other related sites

---

docs/plugin_matrix.rst
src/streamlink/plugins/goltelevision.py
tests/test_plugin_goltelevision.py

As requested in #1599. Geo-blocked to Spain.

plugins.goltelevision: support for the live stream

---

setup.py

Now that PyPI is migrating to their new version (warehouse, I think) we have the ability to include the README as Markdown instead of converting it to RST.
This will make the project page on PyPI look much nicer. You just have to check https://pypi.org/project/streamlink/0.12.1/ to see how great it looks right now 😉 
I also updated the classifiers while I was in `setup.py`...

Add the README file to the Python package

---

docs/plugin_matrix.rst
src/streamlink/plugins/ustvnow.py
tests/test_plugin_ustvnow.py

USTV Now has a bad JavaScript UI and the page URLs are all the same, so a station code must be provided using the `--ustvnow-station-code` option, or appended to the URL (eg. watch.ustvnow.com/watch/syfy).
Fixes #911

plugin.ustvnow: plugin to support ustvnow.com

---

src/streamlink/plugins/chaturbate.py

- `""` is not a valid url anymore
- Added **log info** "Stream status: public,offline,hidden,private" ...
- the api doesn't return a geo blocked msg (it's just public),
so it can't be added but streamlink won't start a invalid stream now
Fixed https://github.com/streamlink/streamlink/issues/1179

plugins.chaturbate: only open a stream if the url is not empty

---

src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
tests/test_hls.py

@pcolmer asked if it was possible to stop a live stream after a given time in #1709. This PR enhances the functionality of the existing `--hls-duration` option to include support for live streams. 
Had to fix a test too, it didn't seem to be working as intended anyway.

hls: support for live streams when using --hls-duration

---

dev-requirements.txt
docs/api.rst
setup.py
src/streamlink/compat.py
src/streamlink/plugins/dash.py
src/streamlink/plugins/twitch.py
src/streamlink/stream/__init__.py
src/streamlink/stream/dash.py
src/streamlink/stream/dash_manifest.py
src/streamlink/stream/ffmpegmux.py
src/streamlink/stream/segmented.py
src/streamlink_cli/main.py
tests/__init__.py
tests/mock.py
tests/resources/__init__.py
tests/resources/dash/test_1.mpd
tests/resources/dash/test_2.mpd
tests/resources/dash/test_3.mpd
tests/resources/dash/test_4.mpd
tests/resources/dash/test_5.mpd
tests/resources/dash/test_6_p1.mpd
tests/resources/dash/test_6_p2.mpd
tests/streams/test_dash.py
tests/streams/test_dash_parser.py
tests/test_docs_plugins.py
tests/test_plugin_dash.py
tests/test_session.py
tests/test_stream_dash.py

This PR adds support to MPEG DASH (mpd) streams (it **does not support DRM**). 
This is something I have been working on for a while (started 2 years ago) and I have just gotten round to getting it to a state that it should be OK to merge. 
`DASHStream.parse_manifest` is the method to use if you wanna using DASHStreams in your plugins, and if you have a stream URL that you wanna try out you can use the `dash://` prefix.
**Test URLs**
- http://www-itec.uni-klu.ac.at/ftp/datasets/DASHDataset2014/BigBuckBunny/15sec/BigBuckBunny_15s_simple_2014_05_09.mpd
- http://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd
- http://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd
- http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-ma …

MPEG DASH Support (initial)

---

src/streamlink_cli/main.py

As @back-to to pointed out (https://github.com/streamlink/streamlink/pull/1690#pullrequestreview-124594681) there was an issues with changing the `loglevel` when using plugin specific configs. This PR resolves that by resetting the `loglevel` after the plugin configs have been loaded, before that point the `loglevel` will still be the default/set by command line.

logging: set the log level once the plugin config files have been loaded

---

script/release.sh

Made the release script a bit more streamline. The only function it really performs now is to update the changelog file and prepare a release branch. It doesn't create the PR, but that could be added if required.
The script accepts some command line options:
- `--upstream REPO` - the upstream repo (streamlink/streamlink)
- `--origin REPO` - the users fork of the repo
- `--version VERSION` - the new version number
The script will work out the current version and generate a git shortlog and update the changelog file, then launch the users $EDITOR so that it can be updated ($VISUAL, or $EDITOR, then fallback to vi).

release: update to release script

---

src/streamlink/plugins/onetv.py
tests/test_plugin_onetv.py

The "ctc" channels weren't working, and now DASH streams are supported.

plugins.onetv: fix issues with ctc channels and add DASH support

---

src/streamlink/logger.py
src/streamlink/session.py
src/streamlink_cli/main.py
tests/test_plugin_tvplayer.py

Previously plugins would be loaded with the module name set to the plugin name, eg. `twitch`, this PR changes that so that plugins are loaded within the `streamlink.plugin` hierarchy. 
I also tweaked the way that the plugin load setup is called (I am slowly chipping away at the global variables). There is also now a debugging log message when a plugin is overridden by an external plugin file - this should help us when debugging issues with plugins, in case the user is using a non-standard plugin version.

logging: fixed issue with logging from plugins using logging module

---

src/streamlink/stream/dash.py
src/streamlink/stream/dash_manifest.py
tests/streams/test_dash.py

Should fix the issue @back-to pointed out here: https://github.com/streamlink/streamlink/issues/1723#issuecomment-393961866
It would be good to get some people to test dash streams with this change, I tested a few :)

dash: fix for manifest reload - should be more reliable

---

src/streamlink/plugins/facebook.py

Update the Facebook plugin, support live DASH streams from the specific video page, or the general videos page, also supports archived streams. 
Fixes #1723 
Should address the issues raised in #880 and #990

plugins.facebook: support for DASH streams

---

.coveragerc

This appears to fix an issue with counting the coverage of the tests.

tests: coverage on src instead of the modules

---

docs/players.rst

It works **without any special settings**,
even on older versions.
Fixed https://github.com/streamlink/streamlink/issues/1551

docs: PotPlayer Stdin Pipe

---

src/streamlink/cache.py
src/streamlink/plugin/plugin.py
tests/test_cache.py
tests/test_plugin.py

Adds some new methods to Plugin to simplify the process of storing and loading cookies between sessions. It makes use of the existing cache mechanism, cookies can be filtered before storing and clearing, and are loaded automatically. 
I wanted this feature to store longer lived cookies for anti-robot scripts, eg. in #1721. It can also be used to store auth cookies.

plugins: store cookies between sessions

---

src/streamlink/stream/dash.py
src/streamlink/stream/hds.py
tests/test_stream_json.py

Fixes the `--json` option when using `DASHStream`s. Enables custom headers to be added to the DASHStream request, eg. `User-Agent`, as per the other `Stream` classes.

dash: fix --json for dash streams and allow custom headers

---

src/streamlink/logger.py
src/streamlink_cli/main.py

Add a timestamp to the logs when using `--loglevel trace`.

logging: when using the trace level, log the timestamp

---

CHANGELOG.md
script/release.sh

The changelogs should have `##`, there was a bug in the release script where it only generated one. 
@cdrage we could merge this, delete the old tag and then retag.

scripts: fix bug in the release for generating the CHANGELOG

---

.travis.yml
MANIFEST.in
script/sdistsign.sh
setup.cfg
setup.py

The script to build the sdist and wheel packages is run before the script that uploads them to PyPI. The sdist script doesn't clean up the environment, but extra prune options have been added to the MANIFEST.in file (thanks @back-to).
All the requirements have been changed to use PEP 345 environment markers, instead of deciding the packages to include based on the current interpreter. This means you can build a wheel on Python 3.6.3 and have it work on Python 2.7.14 :) It also tidies up the setup.py quite a bit. 
I'd like to get confirmation from @mmetak that this will work as expected on the streamlink-git AUR before merging :)

sdist and wheel release fixes

---

src/streamlink/plugins/youtube.py
src/streamlink/utils/__init__.py
tests/test_utils.py

As discussed in #1728 with @back-to, this PR modifies the YouTube plugin to search for the channel's video ID in the page first before trying the API. This should alleviate the pressure on the YouTube API key. 
Also added some better error logging if there is an error when calling the API.
**Requires testing on more channels**
Fixes #1728

plugin.youtube: find video id in page, fall back to API

---

src/streamlink_cli/main.py

Perhaps we should do a `0.13.1` release with just this fix - can branch from `0.13.0` (`release-0.13.x`?), apply this fix and tag on the release branch.

logging: rename logger for main back to 'cli'

---

MANIFEST.in

Tests resources files were not included in the source archive before, while tests might require
them. For example dash *.mpd files in tests/resources.

sdist: include tests resources

---

tests/test_plugin.py

Lambda support is a recent addition in freezegun (in the latest release, 0.3.10) and
might not be available everywhere yet (as of now: Debian stable and sid)

tests: freezegun: use object instead of lambda

---

src/streamlink/plugins/rtlxl.py

With only """, the string is still not a raw string (just a multiline
string) and regex escape sequences were read a string escape sequences
by python, with warnings about unknown escape sequences (like \w).

rtlxl: use raw string to fix escape sequences

---

docs/thirdparty.rst

LiveProxy allows Streamlink to be easy accessible from **m3u** playlists,
it is also available for **Kodi Leia** and **Enigma2** devices.
---
It is only meant for a local network.
---
The argparser is copied from **streamlink_cli**,
this makes it easier to maintain and also allows the usage of all Streamlink commands.
Most of them will work, some not because they make no sense for LiveProxy.
**supported**
- Sideloading Plugins
- config files
- HLS, HTTP, HDS are supported.
**not supported**
- RTMP is not supported
- Dash will be supported at some point, but not right now.
It can play the stream or redirect the streaming url.
---
Example of URLs
```
http://127.0.0.1:53422/play/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2Ffrance24
http://127.0.0.1:53422/301/?url=https%253A%252F%252Fwww.eurone …
```

docs.thirdparty: Added LiveProxy

---

src/streamlink/plugins/btsports.py

Super() without arguments in only supported on Python 3.

Add arguments to __init__ - super to work on Python 2.7.X

---

src/streamlink/plugins/abweb.py
src/streamlink/plugins/bbciplayer.py
src/streamlink/plugins/btsports.py
src/streamlink/plugins/funimationnow.py
src/streamlink/plugins/zattoo.py
src/streamlink_cli/argparser.py

On smaller consoles I noticed that the help text gets a bit garbled with text wrapping, so I fixed it up a bit :)
And I noticed a mistake here: https://github.com/streamlink/streamlink/compare/master...beardypig:docs-80-chars?expand=1#diff-2b258c59b2cac0b01e6240cd4024be63R244
There are probably other mistakes, I might spend some time reading the argument help again :)

help: reformat all the help text so that it is <80 chars

---

src/streamlink/plugins/sportschau.py

Without this patch, the plugin currently throws the error:
error: Unable to open URL: //emwdr-lh.akamaihd.net/foobar (Invalid URL
'//emwdr-lh.akamaihd.net/foobar': No schema supplied. Perhaps you
meant http:////emwdr-lh.akamaihd.net/foobar)

plugins.sportschau: Fix "No schema supplied" error

---

docs/plugin_matrix.rst
src/streamlink/plugins/delfi.py
tests/test_plugin_delfi.py

Support for the Delfi web portal. Supports videos on `delfi.lt`, `delfi.lv`, and `delfi.ee`.
I believe the Polish version would work too, as well as any free video on the English version.
Fixes #1815, plugin request by @for-coursera

plugins.delfi: support for delfi.lt web portal

---

src/streamlink/cache.py
src/streamlink/plugins/crunchyroll.py
tests/test_cache.py

This fixes the session issue #1574 using the API rather than the website, as this change caused some other issues.
The only changes I might make are to the X-Android headers, as it is pretty obviously the emulator. 
I added a small convenience parameter to `cache.set` to allow you to set an expiry time rather than expiry duration. (Need to add tests for this)
Should fix #1808.

plugins.crunchyroll: refactoring and updated API calls

---

README.md
docs/cli.rst
docs/index.rst
docs/install.rst
src/streamlink/stream/hls.py

removed `hlsvariant://` documentation,
`hls://` is enough
**README.md**
- removed invalid note
- update some URLs
**cli.rst**
- removed old note
- added `dash://`
**index.rst**
- update for https URLs
**install.rst**
- update for new **Solus** / **Void** URL
- update for **NixOS**, found only this URL
- update for Dependencies
- PyPI URL update
- removed old livestreamer issue ref 401
- use correct URL for Bintray changelog
---
closes https://github.com/streamlink/streamlink/issues/1807

docs: removed some notes, updated some urls

---

src/streamlink/compat.py
src/streamlink/packages/flashmedia/types.py
src/streamlink/plugin/api/support_plugin.py
src/streamlink/plugins/rtbf.py
src/streamlink/stream/http.py
src/streamlink/utils/__init__.py
tests/__init__.py
tests/streams/test_dash.py
tests/streams/test_dash_parser.py
tests/test_hls.py
tests/test_log.py
tests/test_meta.py
tests/test_stream_to_url.py
tests/test_utils.py

`inspect.getargspec` was deprecated since 3.0 in favour of `inspect.getfullargspec`. For most uses the methods are interchangeable, so depending on if it exists or not can use one or the other. 
I added a decorator method to `tests` so that warnings can be suppressed (or captured) on a per-tests basis.
Fixes #1831, the only problem may be that `flashmedia` is untested.

Suppress/fix deprecated warnings for Python 3

---

src/streamlink/exceptions.py
src/streamlink/options.py
src/streamlink/plugin/plugin.py
src/streamlink/session.py
src/streamlink_cli/console.py
src/streamlink_cli/main.py
tests/test_options.py
tests/test_plugins_input.py
tests/test_session.py

I have taken a bash at creating an API for plugins to request input from a user. I have only implemented in solution for the standard `streamlink_cli`, but I have tried to design it in a way that other front-ends can use. 
During the `Plugin.bind` call and additional (optional) parameter is passed - an instance of `UserInputRequester`, the job of which is to provide a way for the user to give an input. Implementations of `UserInputRequester` must implement two methods, `ask` and `ask_password`. `ask` is for users to input non-sensitive data, eg. username. `ask_password` is for users to input sensitive data, eg. password. For example, in the `ConsoleUserInputRequester` the two methods (`ask`, and `ask_password`) are handled by `Console.ask` and `Console.askpass`. 
For a `Plugin` to request …

API for plugins to request input from the user

---

docs/plugin_matrix.rst
src/streamlink/plugins/steam.py
src/streamlink/plugins/steambroadcast.py
tests/test_plugin_steam.py

The long awaited Steam Broadcast plugin... I wrote this a long time ago (Nov 2016), but never completed the DASH support :)
The only outstanding issue is how to de-couple the 2FA requests from `streamlink_cli`, currently they use the `ConsoleOutput` class to ask the user for the codes. This means importing from `streamlink_cli`, I'd like to find a better solution that this. 
Fixes #173

Steam Broadcast Plugin

---

src/streamlink/plugins/twitch.py
src/streamlink/utils/times.py
src/streamlink_cli/argparser.py
tests/test_utils_times.py

**hours_minutes_seconds**:
allow more timestamps
- hours:minutes:seconds to seconds
- 11h22m33s to seconds
- 11h to seconds
- 20h15m to seconds
- seconds to seconds
**twitch**:
- automate `hls-start-offset` for urls with timestamps
- update for the old vod url's, which I don't think exist anymore
**youtube**:
- tested on youtube, but did not add it because there are to many http streams
---
I put it into `api/utils.py` but could also move it somewhere else.
---
will break https://github.com/streamlink/streamlink/pull/1792 as it uses the same file

api.utils: hours_minutes_seconds update, twitch automate time offset

---

src/streamlink/plugins/mitele.py

Sometimes the `ogn` parameter is null (fixes engery). There are two data endpoints, `html5` and `flash` - the `html5` one appears to work more reliably. 
Fixes #1845

plugins.mitele: sometimes ogn is null, html5 pdata endpoint works better

---

src/streamlink/stream/dash.py
tests/streams/test_dash.py

This is a work-around for some DASH streams that have duplicate IDs for representations. By using the mimeType as well as the ID, we can better identify the different streams. Naughty Valve.

stream.dash: use the ID and mime-type to identify a representation

---

src/streamlink/plugins/tv3cat.py

Updated the validation schema and refactored the plugin a bit. It now tries all the streams in order, inside Catalunya there are sometimes higher quality streams.
Fixes #1850

plugins.t3cat: update validation rule, refactor plugin a little bit

---

script/github_releases.py

As reported by @cdrage https://github.com/streamlink/streamlink/pull/1855#issuecomment-400693776. 
Tested with `--dry-run`.

release: fix release notes manual install url

---

script/release.sh

This changes the release date that is automatically added to the release notes from your local timezone to UTC. If different people are deploying two releases in different timezones, it is possible that a newer version could be released "before" the previous version. For example, if someone in Italy deployed a release at 01:00 2018-06-02 (UTC+2) and later someone in California deployed a release at 22:00 2018-04-01 (UTC-7)- we have a time travelling release. If all releases are labeled using UTC then they will be consistent, however it is possible to have a "future" release if you live west of the prime meridian.

release: set the date of the release for UTC time

---

src/streamlink/plugin/plugin.py
tests/test_plugin_stream.py

`DASHStream.parse_manifest` returns stream qualities that sometimes include the audio bitrate, eg. `720p+a128k` and `720p+a256k`. This adds support in the stream weight parser for these types of stream names, so they can be properly sorted and the `"best"`/`"worst"` options will work. 
See https://github.com/streamlink/streamlink/pull/1853#issuecomment-400981479

plugin: support stream weights returned by DASHStream.parse_manifest

---

src/streamlink_cli/main.py

If a `PluginArgument` has been suppress (deprecated) then it should be ignored when collecting the options.

plugin args: if args are suppressed, ignore them

---

src/streamlink/logger.py
src/streamlink/utils/encoding.py
tests/test_log.py
tests/test_utils_encoding.py

Using the `maybe_{en,de}code` methods from #1576 to handle log messages that might be unicode in Python 2.7.

Handle unicode log message in Python 2

---

src/streamlink/logger.py
src/streamlink/plugins/youtube.py

Uses an alternative method to find the videoId for YouTube videos. First the canonical page is loaded (if different from the current page, eg. embed pages), then we use `currentVideoEndpoint.watchEndpoint.videoId` (credits to @back-to) from `ytInitialData` to find the videoId. This worked on all the pages I tested.
The decoding of the video info has been improved to support unicode error messages. This requires the logging fix from #1886 to work correctly. 
Blocked by #1886 
Fixes #1876
Fixes #1865

Update method for finding YouTube videoIds

---

src/streamlink/stream/dash_manifest.py
tests/resources/dash/test_8.mpd
tests/streams/test_dash_parser.py

Fixes the issue reported by @back-to in #1895

stream.dash: fix bug where timeline_segments.t can be None

---

docs/plugin_matrix.rst
src/streamlink/plugins/zattoo.py
tests/plugins/test_zattoo.py

use **new** streamlink **cookie api**
the **default session** time is set to **30 days**,
after every two hours there will be a check if the session is actually valid.
there is also a forced session reset if the streamlink cache data is invalid
---
use **new** streamlink **logging api**
---
New option `--zattoo-stream-types`, this allows the usage of other stream types
- **hls** - normal hls streams - this is the default
- **hls5** - muxed hls streams
- **dash** - dash streams
they are **not enabled by default**, as this would spam to many not needed mirrors.
```
$ streamlink https://zattoo.com/watch/sf-info-intl
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/sf-info-intl
[cli][info] Available streams: 600k_alt (worst), 600k, 900k, 1500k, 3000k, 5000k (best) …
```

plugins.zattoo: session update and allow muxed hls / dash streams

---

src/streamlink/stream/hls.py

If streams that are being muxed include data streams, the stream mapping will not be correct. This PR adds a filter so that only `video` and `audio` streams are mapped. 
Fixes #1898

stream.hls: only include audio/video streams in MuxedHLSStreams

---

.travis.yml
appveyor.yml

**Travis-ci**
- `dist: xenial` for 3.7 because `openssl` is to old on `trusty`
https://github.com/travis-ci/travis-ci/issues/9069
https://github.com/travis-ci/travis-ci/issues/9815
**AppVeyor**
- https://github.com/appveyor/ci/issues/2475

tests: run Python 3.7 tests on AppVeyor and Travis-CI

---

src/streamlink/utils/l10n.py

It will show this message when Localization is called by muxed hls or 
dash streams.
```
$ streamlink ... --locale ru_RU
...
[plugin.dash][debug] Parsing MPD URL: ...
[utils.l10n][debug] Language code: ru_RU
```
or your local system code
```
$ streamlink ...
...
[plugin.dash][debug] Parsing MPD URL: ...
[utils.l10n][debug] Language code: xx_XX
```

debug: Added Session Language code as a debug message

---

src/streamlink/stream/dash.py
tests/streams/test_dash.py

When selecting the audio streams in a dash stream, if the user has specified a locale, the audio streams that match the language of the user's locale will be preferred. If the user does not set a locale then the first language that appears will be preferred. 
Fixes #1917

stream.dash: prefer audio streams based on the user's locale

---

src/streamlink/stream/hls.py

Due to the changes in #1926, if the primary video stream included an audio stream as well it would not be included in the output. This change restores that audio stream. 
Fixes #1938

stream.hls: if the primary video stream has audio then include it

---

src/streamlink/plugins/picarto.py

Looks like picarto started escaping the slashes after the https in their VOD URL. 
This adjusts the regex accordingly and removes the slashes (I hope this is the correct way to do that).
Fixes #1932

[picarto.tv] Fix regarding changed URL

---

tests/test_localization.py

**python-iso3166** got an update which breaks the Streamlink tests.
https://pypi.org/project/iso3166/#history
**python-iso3166** and **pycountry** have now a different `name` for _the United States of America_
> python-iso3166: United States of America
https://github.com/deactivated/python-iso3166/commit/e5f8b37f18b01fcb5fa0e8130d8296fc7a7b5a9f
> pycountry: United States
https://bitbucket.org/flyingcircus/pycountry/src/5aa4bb47e33798cb631a81521b7b5b18f7d6c919/src/pycountry/databases/iso3166-1.json?at=default&fileviewer=file-view-default#iso3166-1.json-1572:1578
https://www.iso.org/obp/ui/#iso:code:3166:US
---
use **en_CA** instead of **en_US** for backwards compatibility,
as changing the **US** name would fail with older versions of **python-iso3166** / **pycountry**

tests.localization: use en_CA instead of en_US for test_equivalent

---

src/streamlink/plugins/pixiv.py

For the hls URL, use the API call that is used for `https://sketch.pixiv.net/lives`
instead of searching it on the User html source code,
as this might have some caching issues.
---
Save the session cookies after a successfully login,
they can be reseted with `--pixiv-purge-credentials`
---
New command to select the co-hosts `--pixiv-performer`,
rather than adding them as an alternative Stream.
The `unique_name` must be used for this command,
if an invalid user is selected Streamlink will ask the User to select a different User.
---
Normal stream
```
$ streamlink URL worst
[cli][info] Found matching plugin pixiv for URL ...
[cli][info] Available streams: 720p (worst), 1080p (best)
```
Stream with other co-hosts
```
$ streamlink URL worst
[cli][info] …
```

plugins.pixiv: use API for the stream URL and cache login cookies

---

docs/plugin_matrix.rst
src/streamlink/plugins/abematv.py
tests/plugins/test_abematv.py

Abema.tv  is a japanese live (news,drama,anime , etc) and vod stream site.
1. Live stream:  https://abema.tv/now-on-air/abema-news
2. VOD stream: https://abema.tv/video/episode/90-1053_s99_p12
3. VOD stream: https://abema.tv/channels/everybody-anime/slots/FJcUsdYjTk1rAb
1.Because of `ext-x-discontinuity` issue, players may not handle live stream discontinuity properly.
2.Streams are geo-restricted to Japan , but could be bypassed via `--http-header 'X-Forwarded-For=A_JAPAN_IP' `   (TESTONLY)

Plugin Request: new plugin for Abema.tv

---

src/streamlink/plugin/api/useragents.py

Most of them are very old and outdated, use some recent versions.
Did not change `Safari7/8, IE6/7/8/9, WindowsPhone8`
Renamed `IPHONE_6` to `IPHONE`, but it can still be used as 6
---
Ref some comments on https://github.com/streamlink/streamlink/pull/1794

api.useragents: use newer and more common User-Agent's

---

src/streamlink/plugins/facebook.py
tests/plugins/test_facebook.py

Support for videos posts. eg. https://www.facebook.com/119555411802156/posts/500665313691162/

plugins.facebook: support for videos in posts

---

src/streamlink/plugin/api/utils.py
src/streamlink/plugins/gardenersworld.py
src/streamlink/plugins/tf1.py
src/streamlink/utils/__init__.py
src/streamlink/utils/url.py
tests/test_plugin_utils.py
tests/test_utils.py
tests/test_utils_url.py

As part of the solution for the issues raised in #1519 by @amurzeau, I have started adding some URL utils that can be used in plugins to better manipulate URLs. 
As well as a useful method for iterating through HTML tags, using regex in a brute force kind of way - like most of the plugins do. 
`update_qsd` and `url_concat` are the two URL manipulation methods. `url_concat` will join together URL parts to make a URL, and `update_qsd` can be used to add, remove or update query string parameters in a URL. 
I updated a couple of plugins as examples.

URL builder utils

---

script/makeinstaller.sh

Python = 3.6.6
Pycryptodome = 3.6.4
**Known Issue:**
Old Python 3.5 files from a previous installation, won't be removed.
(because of the limitations of pynsist)

script.makeinstaller: use a more recent version of Python and Pycryptodome

---

dev-requirements.txt
src/streamlink/__init__.py
src/streamlink/plugin/plugin.py
src/streamlink/stream/hls.py
src/streamlink/utils/__init__.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/plugins/test_stream.py
tests/plugins/test_tvplayer.py
tests/test_plugin_utils.py
tests/test_session.py
tests/test_utils_url.py

- removed **versionchange references** as Streamlink does not use it.
- removed **old code** that was deprecated in Livestreamer
- removed DeprecatedWarning for **2.6** as it is already mentioned in 
`setup.py`
https://github.com/streamlink/streamlink/blob/a14f170a04252d4275de417c13dcc2a19bf269c9/setup.py#L82
- removed **unittest2**
- **Flake8** for some lines/files that I changed.
---
Fixed https://github.com/streamlink/streamlink/issues/1141

Removed old Livestreamer deprecations and API references

---

docs/plugin_matrix.rst
src/streamlink/plugins/ltv_lsm_lv.py
tests/plugins/test_ltv_lsm_lv.py

LTV.LSM.LV is the official website of the Latvian state-owned television. It contains the live streams of 3 TV channels.
1. Live stream: https://ltv.lsm.lv/lv/tieshraide/ltv1
2. Live stream: https://ltv.lsm.lv/lv/tieshraide/ltv7/live.782/
3. Live stream: https://ltv.lsm.lv/lv/tieshraide/visiemltv.lv/live.1480/
Some of the auditions are geo-resticted to Latvia.
Only handling the live TV channels streams has been implemented.
Although a single stream contains the links to 3 different resolutions (and handling setting them has been implemented) at the moment the broadcaster set all of them seem point to the same stream.
For testers - the 3-rd stream seems to be the least frequently geo-restricted.

Plugin Request: new Plugin for Latvian live TV channels on ltv.lsm.lv

---

tests/test_plugin_utils.py

The tests won't pass with `python setup.py test`,
use `unittest` instead of `pytest`.
```
======================================================================
FAIL: test_itertags_multi_attrs (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
File "tests/test_plugin_utils.py", line 59, in 
test_itertags_multi_attrs
self.assertEqual(metas[0].text, None)
AssertionError: 'Title' != None
======================================================================
FAIL: test_no_end_tag (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
File "tests/test_plugin_utils.py", line 80, in test_no_end_tag …
```

tests: use unittest instead of pytest for itertags error

---

src/streamlink/utils/__init__.py
tests/test_utils.py

A playlist has tabs instead of spaces,
`self.node` is `{urn:mpeg:dash:schema:mpd:2011}mpd` instead of `mpd`,
because `ignore_ns` did not work.
```
File "env/bin/streamlink", line 11, in <module>
load_entry_point('streamlink', 'console_scripts', 'streamlink')()
File "src/streamlink_cli/main.py", line 1007, in main
handle_url()
File "src/streamlink_cli/main.py", line 557, in handle_url
streams = fetch_streams(plugin)
File "src/streamlink_cli/main.py", line 437, in fetch_streams
sorting_excludes=args.stream_sorting_excludes)
File "src/streamlink/plugin/plugin.py", line 317, in streams
ostreams = self._get_streams()
File "src/streamlink/plugins/dash.py", line 59, in _get_streams
return DASHStream.parse_manifest(self.session, mpdurl)
File …
```

utils.parse_xml: allow a tab for ignore_ns

---

src/streamlink/plugins/afreeca.py

new ts url examples
invalid
```
800x480/202020202-flash-original-hls_0_preloading.TS
800x480/202020202-flash-original-hls_1_preloading.TS
800x480/202020202-flash-original-hls_2_preloading.TS
```
valid
```
800x480/202020202-flash-original-hls_3_000000123456789ABCDEF12345678910.TS
800x480/202020202-flash-original-hls_4_000000123456789ABCDEF12345678910.TS
800x480/202020202-flash-original-hls_5_000000123456789ABCDEF12345678910.TS
```
closes https://github.com/streamlink/streamlink/issues/2061

plugins.afreeca: ignore new preloading urls

---

src/streamlink/utils/times.py
src/streamlink_cli/argparser.py
tests/test_utils_times.py

Options `HH` part in the `HH:MM:SS` options, so that you can do `10:00` for 10 minutes. 
Also gives extra utility to the `hours_minutes_seconds` method for parsing time offsets from streaming sites, etc.

cli: make the HH part of HH:MM:SS options optional

---

.travis.yml

There are not enough commits for Versioneer `streamlink-0+untagged`,
with more commits the Streamlink version should be fixed for travis.
Fixes Windows build.
Error Example:
https://travis-ci.org/streamlink/streamlink/jobs/436299646#L1165
https://github.com/streamlink/streamlink.github.io/commit/42e74cce133a0dfcc6c40a9a71ebbaa336b3285f#diff-1438650dd2508a32fb38f7b8aa3c8e19
Ref:
https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth

travis: increase git clone depth

---

script/makeinstaller.sh

Fixes #2097
Pynsist is now cleaning its build dir before it generates the config files, so all additional files which are included in the installer need to be copied to a different directory. I've added the new `build/files` dir where `win32/{streamlinkrc,ffmpeg,rtmpdump}` will be copied to. The nsis config file has been changed to load the files from this (absolute) path.
Tested it locally on my machine and the files were correctly included in the built installer.

Fix installer by moving additional files

---

src/streamlink/stream/dash_manifest.py

if `self.parent.id` is None, use `self.parent.mimeType` instead.
This will create two timelines for video and audio,
instead of one for both which won't work.
---
I don't know that much about the MPD class,
maybe it could be solved differently.
---
Test URLs:
https://www.france.tv/france-5/direct.html
http://livesim.dashif.org/livesim/segtimeline_1/testpic_2s/Manifest.mpd
from https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Test-URLs
---
closes https://github.com/streamlink/streamlink/pull/1934

stream.dash_manifest: Fixed bug for dynamic playlists when parent.id is None

---

docs/plugin_matrix.rst
src/streamlink/plugins/ok_live.py
tests/plugins/test_ok_live.py

I noticed that existing ok_live plugin works for VoDs on ok.ru, so I just changed URL regex to support them as well. Closes #2095

plugins.ok_live: Changed URL regex to support VoDs

---

src/streamlink/plugins/ustreamtv.py

- use websocket API from https://github.com/streamlink/streamlink/pull/1777
- use **flv/segmented** streams for better stream qualitys
---
Test plugin URL `ustreamtv.py`
https://raw.githubusercontent.com/back-to/streamlink/ustream_desktop/src/streamlink/plugins/ustreamtv.py
---
might need to change some naming of the new used code.
---
@porcomail
closes https://github.com/streamlink/streamlink/issues/1146
@dd00
closes https://github.com/streamlink/streamlink/issues/1653
@sokkycakes
closes https://github.com/streamlink/streamlink/issues/1767
@InstallGentoo11
closes https://github.com/streamlink/streamlink/issues/2050
@xpatryk89
closes https://github.com/streamlink/streamlink/issues/2076
@beardypig
closes https://github.com/streamlink/streamlink/pull/1777

plugins.ustreamtv: use Desktop instead of Mobile streams

---

src/streamlink_cli/utils/progress.py
tests/test_cli_util_progress.py

Improve terminal progress display for  wide characters

---

docs/plugin_matrix.rst
src/streamlink/plugins/tamago.py
tests/plugins/test_tamago.py

Add support for Tamago Live, a streaming website. Closes #2071

plugins.tamago: support for live streams on player.tamago.live

---

docs/cli.rst
docs/plugin_matrix.rst

I added documentation and notes for the Funimation plugin
**cli.rst**:
- added authentication and `incap_ses` cookie information
**plugin_matrix.rst**:
- added note about the required cookie

docs: add appropriate funimation docs

---

src/streamlink/plugins/youtube.py
tests/plugins/test_youtube.py

URL regex update.
use canonical url for embedded livestreams,
this was not added before because it is not needed for normal videos.
Ref https://github.com/streamlink/streamlink/pull/1888#discussion_r199504011
Added some more regex group tests.
---
Example where this url can be found
`https://www.aljazeera.com/live/` with `Having trouble watching?`
The youtube url is currently not used for Streamlink,
but might be useful for other future websites.

plugins.youtube: Added support for embedded livestream urls

---

docs/donate.rst

With the issues we've encountered with BountySource recently (https://github.com/streamlink/streamlink/issues/1388#issuecomment-423382610) and the need to pull our money we don't want anyone else donating here so I've removed it from the docs. I've also updated my Flattr as they've changed how profiles work.

Remove bountysource from donation page, update flattr

---

src/streamlink/_version.py
versioneer.py

The nightly version won't get build because Streamlink outputs two different versions,
one with 7 and one with 8 characters.
https://bintray.com/streamlink/streamlink-nightly/streamlink
commit `1a5a5fb2e6fccc5a441f987ccd4e53794542dfc9`
> streamlink-0.14.2_133.g1a5a5fb.exe
length 7
https://travis-ci.org/streamlink/streamlink/jobs/440826462#L3090
> streamlink-0.14.2_133.g1a5a5fb2.exe
length 8
https://travis-ci.org/streamlink/streamlink/jobs/440826462#L3198
---
This is a known issue from versioneer, there is also a solution ...
https://github.com/warner/python-versioneer/issues/156
https://github.com/m-labs/artiq/commit/076e4119f744c07afaa6f6cd840a45dfcd13718e#diff-f374b985f7c07f7ff6a8dbaa0b30a10d
https://github.com/m-labs/artiq/commit/d08bd58dffef5c4c13536ecf48d6147f542b7a5b#diff-4af5de46c62 …

versioneer: always use 7 characters

---

docs/plugin_matrix.rst
src/streamlink/plugins/pluzz.py
tests/plugins/test_pluzz.py

This PR:
* speeds up stream resolution for HDS streams (by using a static URL for the SWF player instead of searching it each time the plugin is run)
* makes the plugin use token generator for all kind of streams (since a recent change on France TV)
* enable full support for videos on francetvinfo.fr and its subdomains (fixes https://github.com/streamlink/streamlink/issues/1959)

plugins.pluzz: fixes and francetvinfo.fr support

---

src/streamlink_cli/main.py
tests/test_cli_main.py

Changes to the behaviour of the progress bar when using -o.
If there is no tty available for output (eg. when piping, or running a subprocess), then no progress bar is output. This is because the progress bar rewrites the console, which is only possible on interactive terminals not for a pipe.
If there is no tty available for input and the file already exists an error is given instead of a prompt to the user.
Should fix #1770.

cli: disable progress output for -o when no tty is available

---

src/streamlink/plugins/huomao.py
tests/plugins/test_huomao.py

Plugin for Huomao extracts stream info from mobile webpage, but they have since changed the mobile website, subsequently breaking the plugin.
Closes #2132

plugins.huomao: Fix plugin after website changes

---

src/streamlink/plugin/plugin.py
src/streamlink_cli/argparser.py
src/streamlink_cli/constants.py
tests/plugins/testplugin.py
tests/test_cli_main.py
tests/test_session.py

Add special stream synonyms "best-unfiltered" and "worst-unfiltered" in
cases when all available streams have been filtered out by the
`--stream-sorting-excludes` parameter and the "best" and "worst" stream
synonyms don't exist. These new synonyms point towards the respective
streams of the unfiltered streams list so that the user is able to
select a fallback stream.
Example:
streamlink --stream-sorting-excludes '>=480p' URL best,best-unfiltered
Will try to open the best stream below 480p, but if none is available
will continue with the best of all streams as a fallback selection.
Resolves #1055

feature: {best,worst}-unfiltered stream synonyms

---

docs/plugin_matrix.rst
src/streamlink/plugins/metube.py
tests/plugins/test_metube.py

meTube.id is an Indonesian video sharing website owned by MNC Media that has live streams of many Indonesian TV channels.
Plugin works for both live streams and VoDs. Closes #2031

plugins.metube: Add support for live streams and  VoDs on www.metube.id

---

docs/cli.rst

I added a note under the configuration file contents about adding the full path because I realized we don't have one in the config file example. I also updated the APPDATA note since with Windows 10 it's now `AppData`

Add a note about specifying the full player path

---

src/streamlink/plugins/skai.py
tests/plugins/test_skai.py

Closes #2159
- Updated URL regex to support new valid URL
- Plugin is now extracting stream URL from an API call instead of searching the HTML document
- Added a test for the new URL

plugins.skai: Fix plugin after site update

---

src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This pull request adds the "--hls-segment-key-uri \<URI\>" CLI flag which allows you to override the URI used to retrieve HLS segment keys.
I also force requests to parse the key response body as `binary/octet-stream` as per the HLS spec. Not having this was actually giving me issues.

Add ability to specify custom key URI override for HLS streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/cdnbg.py
tests/plugins/test_cdnbg.py

- http://inlife.bg/
- https://mmtvmusic.com/live/
- http://mu-vi.tv/LiveStreams/pages/Live.aspx
---
- use python logging
- removed SSL Verification for Stream URLs
- find iframes with `&#58;` instead of `:`
closes https://github.com/streamlink/streamlink/issues/1392

plugins.cdnbg: Update for extra channels

---

src/streamlink/logger.py
src/streamlink/plugin/api/utils.py
src/streamlink/stream/hds.py
tests/test_api_validate.py
tests/test_plugins.py

- **logger**: `ValueError: Invalid format '[{name}][{levelname}] {message}'  for '%' style`
- **api/utils**: `SyntaxWarning: invalid escape sequence`
- **hds**: `SyntaxWarning: invalid escape sequence` and `Flake8 E127`
- **test_api_validate**: `SyntaxWarning: invalid escape sequence`
- **test_plugins**: `ResourceWarning: unclosed file`

travis-ci: Fixed Python 3.8 error's

---

setup.py

Updated the versions due to the following issues
1. urllib3
> Vulnerable versions: < 1.23
> Patched version: 1.23
> urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.
https://nvd.nist.gov/vuln/detail/CVE-2018-20060
2. requests
> Vulnerable versions: <= 2.19.1
> Patched version: 2.20.0
> The Requests package through 2.19.1 before 2018-09-14 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network. …

setup: update requests to latest version and set urllib3 to match

---

src/streamlink_cli/output.py

Due to #1576, `args` are `string` on Windows but `list` on other OS.
https://github.com/streamlink/streamlink/blob/94a8a7301c45dfdee89dd7d4d14043438dda4b38/src/streamlink_cli/output.py#L188-L194
A later debug call then converts `string` into space-separated characters.
https://github.com/streamlink/streamlink/blob/94a8a7301c45dfdee89dd7d4d14043438dda4b38/src/streamlink_cli/output.py#L209-L210

Fix subprocess argument debug log on Windows

---

src/streamlink/plugins/filmon.py
tests/plugins/test_filmon.py

If the live tv channel name started with `channel` (eg. `tv/channel-4`) it would not be matched because of the `tv/(?!channel)` rule in the regex. 
Fixes #2222.

plugins.filmon: fix for live tv URLs that start with channel

---

src/streamlink/plugins/powerapp.py
tests/plugins/test_powerapp.py

Updated the url regex to support `tvs` URLs.
Fixes #2221.

plugin.powerapp: support for "tvs" URLs

---

.travis.yml

It seems like some environments ship with an old version of `pytest` that in now incompatible with the latest version of `pytest-cov`. This change should mean that all the packages are at the latest version.

CI: make sure all the dev dependencies are up to date

---

docs/plugin_matrix.rst
src/streamlink/plugins/turkuvaz.py
tests/plugins/test_turkuvaz.py

- use https for api urls
- added missing url tests and plugin matrix entry for other domains
closes https://github.com/streamlink/streamlink/issues/2216

plugins.turkuvaz: Added support for channel 'apara'

---

src/streamlink_cli/main.py

Add a checking for record attribute in output in read_stream function to prevent crashing
when start with --player-continuous-http or --player-external-http option

Fix crashing on missing output.record when using player-continous-http option

---

src/streamlink/plugins/zdf_mediathek.py

* json schema changed slightly
* new playId constant was introduced
* added required "Accept"-header
Closes streamlink/streamlink#2231

fix zdf mediathek plugin

---

src/streamlink/plugins/youtube.py

hlsvp parameter is gone , but hlsManifestUrl is still working.

Workaround for Youtube livestream can't be played.

---

src/streamlink/plugins/tf1.py

HLS streams are still available with the new API, my bad.
Should be a work-around for #2270.

plugins.tf1: re-add support for HLS with the new API

---

src/streamlink/plugins/bbciplayer.py
tests/plugins/test_bbciplayer.py

When using the `--player-external-http` option, some clients will make multiple requests to get the streams. In the case of the BBC iPlayer plugin it was trying to authenticate when it didn't need to, looking for a `nonce` value that would not be there.
This PR adds a check to make sure that double authentication is not attempted. 
Should fix #2278.

plugins.bbciplayer: do not try to authenticate when not required

---

src/streamlink/plugins/ustreamtv.py

`preset` might be a duplicate of `original` use `videoCodec height` instead.
```
{'segmentUrl': '2/4/chunk_%_%.flv', 'bitrate': 2561, 'preset': 'original', 'transcoded': False, 'videoCodec': {'height': 720}}
{'segmentUrl': '2/9/chunk_%_%.flv', 'bitrate': 2556, 'preset': 'original', 'transcoded': False, 'videoCodec': {'height': 720}}
{'segmentUrl': '5/4/chunk_%_%.flv', 'bitrate': 312, 'preset': 'original', 'transcoded': False, 'videoCodec': {'height': 486}}
{'segmentUrl': '5/9/chunk_%_%.flv', 'bitrate': 307, 'preset': 'original', 'transcoded': False, 'videoCodec': {'height': 486}}
{'segmentUrl': '8/4/chunk_%_%.flv', 'bitrate': 243, 'preset': '360p', 'transcoded': True, 'videoCodec': {'height': 360}}
{'segmentUrl': '8/9/chunk_%_%.flv', 'bitrate': 238, 'preset': '360p', 'transcoded': True, …
```

plugins.ustreamtv: handle stream names better, allow '_alt' streams

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_lazy_formatter.py

For #2225 
Adds `{url}` formatting variable to player window `--title`.
Can there be a situation where `args.url` doesn't exist?
If so, maybe I should add a `DEFAULT_STREAM_METADATA["url"]`?
https://github.com/streamlink/streamlink/blob/07387e22d567994f8fe7eaba79638e22cb2be24b/src/streamlink_cli/constants.py#L7-L12

Add {url} argument to window --title

---

src/streamlink_cli/constants.py
src/streamlink_cli/output.py
tests/test_cmdline_title.py
tests/test_output.py

After #1576 we can add window title support to other players.
Due to limitations of PotPlayer, titles can only be added to URL streams and there is no separate title argument.
PotPlayer command line documentation in `PotPlayer - About - Command Line`:
- You can specify titles for URLs by separating them with a backslash (\\) at the end of URLs. ("http://...\title of this url")
Because of this, the title needs to be appended at the end of the filename so args need to be formatted after player check.
Here's an example of it working on Windows 10:

Add window title to PotPlayer

---

src/streamlink/plugins/crunchyroll.py
tests/plugins/test_crunchyroll.py

Multilingual URLs shoud be allowed to be handled by the crunchyroll plugin.
Using [crunchyroll's rss](https://www.crunchyroll.com/rss), I've seen that the `<link></link>` given is formatted depending your localization, probably IP based. Since I am currently living in France I always get the /fr language path
```python
import feedparser
url = 'https://www.crunchyroll.com/rss'
f = feedparser.parse(url)
print(f['entries'][0]['link'])
```
```
http://www.crunchyroll.com/fr/shonen-ashibe-go-go-goma-chan/episode-94-graduating-from-goma-chan-780795
```

plugins.crunchyroll: Allow CR's multilingual URLs to be handled

---

docs/install.rst
script/github_releases.py

These are multiple changes which probably don't belong into one pull request, but since some of them depend on each other, I've added them to just one branch.
Because of this, please don't read the changes as a whole and check each commit individually. If this gets merged, please don't squash.
----
The main intention of these changes was to rewrite the "Source code" section and suggest to rather use the `--user` parameter on Linux. The reason for this is that installing python packages system-wide via pip or setuptools can cause issues on certain Linux distros, because packages installed into `/usr` can conflict with packages of the distro's regular package management. Therefore we should not recommend installing streamlink system-wide. I've also removed this from the script that …

docs: install improvements

---

src/streamlink/stream/dash.py
tests/streams/test_dash.py

Modifies `parse_manifest()` to accept a `url_or_manifest` parameter.
See also: #2239 
This does not include any of the changes for supporting DASH SegmentBase.

streams.dash: Support manifest strings in addition to manifest urls

---

src/streamlink/plugins/streamme.py

Ref https://github.com/streamlink/streamlink/pull/2307#issuecomment-462113332
```
error: Unable to validate response text: Unable to validate key 'formats': Unable to validate key 'mp4-hls':
Unable to validate key 'origin': Type of None should be 'dict' but is 'NoneType'
```

plugins.streamme: Fixed null error for 'origin'

---

tests/test_plugin_utils.py

> 3.7.0 - 3.7.2 and 3.8.0a1
skip only unsupported versions,
test it on future supported updates
---
3.7.3 final: 2019-03-25 (expected)
https://www.python.org/dev/peps/pep-0537/#id3
3.8.0 alpha 2: Sunday, 2019-02-24 (expected)
https://www.python.org/dev/peps/pep-0569/#schedule
---
Ref https://bugs.python.org/issue34294
Fixed https://github.com/streamlink/streamlink/issues/1979

tests: detect unsupported versions for itertags

---

.travis.yml
dev-requirements.txt
script/makeinstaller.sh
script/sdistsign.sh
setup.py

This adds an additional `streamlink-noconsole.exe` "GUI" launcher to the Windows installer and the Streamlink python wheel. This launcher uses `pythonw.exe` under the hood, so that a new terminal window doesn't get opened if executed from a non-terminal context on Windows.
Resolves #2287, #2308 
----
**Motivation of this PR and why this change is needed**
A couple of months ago, both `pip` and `pynsist` changed their entry point launchers on Windows from [`setuptools`](https://github.com/pypa/setuptools/blob/v40.8.0/launcher.c) to [`simple_launcher`](https://bitbucket.org/vinay.sajip/simple_launcher). This change broke the Streamlink resolver in Streamlink Twitch GUI, as these new launchers are lacking the additional `streamlink-script.py` file, which is used for parsing its shebang and …

Build additional "streamlinkw" launcher on Windows

---

src/streamlink/plugins/twitch.py

Resolves #2357
Sets the `platform=_` GET parameter in the stream access token request, which results in `server_ads` to be set to `false` in the response (at least for now - might get changed/fixed in the future).
As I've said in #2357, I'm not sure how to feel about actively suppressing ads in Streamlink and its plugins. Yes, this is what probably most - if not all - of the users want, but this violates the ToS of Twitch and may put us at risk of losing our API client ID in the future. Discussion is welcome.

plugins.twitch: platform=_ in access_token request

---

src/streamlink_cli/main.py

Forces the authentication confirm dialog on Twitch, in case the user is already logged in. This lets them switch to a different account or review the OAuth permissions.

Add force_verify=true to Twitch OAuth URL

---

docs/plugin_matrix.rst
src/streamlink/compat.py
src/streamlink/plugins/facebook.py
tests/plugins/test_facebook.py

Addresses #2168, #2133.
Immediate playback for DASH streams with separate audio and video
streams will not be supported until proper SegmentBase handling is
implemented.
Depends on the `url_or_manifest` changes from #2285.
See also: #2239 
Immediate playback for DASH streams with separate audio and video streams is still not supported, this will require implementing support for DASH SegmentBase.

plugins.facebook: Support manifest strings and tahoe player urls

---

src/streamlink/plugins/live_russia_tv.py

Iframe format is different for different channels. For example: 
this works:
https://live.russia.tv/index/index/channel_id/82
and this doesn't work:
https://live.russia.tv/index/index/channel_id/1

plugins.liverussia: fix iframe format differences

---

src/streamlink/plugins/twitch.py
src/streamlink/stream/hls.py
src/streamlink/stream/hls_playlist.py
tests/plugins/test_twitch.py

Resolves #2368, #2357 (deleted, for whatever reason, which is really sad - I've opened a support ticket to get it hopefully restored) 
Please see #2369 and my comment here first:
https://github.com/streamlink/streamlink/pull/2369#issuecomment-475528275
Adds a custom `TwitchHLSStream` implementation and the `--twitch-disable-ads` CLI parameter, which will skip HLS segments between `#EXT-X-SCTE35-OUT` and `#EXT-X-SCTE35-IN` tags.
If this PR gets merged, **please don't squash the commits**.

 plugins.twitch: implement disable-ads parameter

---

src/streamlink/plugins/bfmtv.py

This PR fixes this issue:
```
$ /usr/bin/streamlink https://bfmbusiness.bfmtv.com/mediaplayer/live-video/
[cli][info] Found matching plugin bfmtv for URL https://bfmbusiness.bfmtv.com/mediaplayer/live-video/
error: No playable streams found on this URL: https://bfmbusiness.bfmtv.com/mediaplayer/live-video/
```

[plugins.bfmtv] Fix player regex

---

src/streamlink_cli/argparser.py
tests/test_cmdline.py

use workaround solution from
https://bugs.python.org/issue9334
don't know if there is any downside,
but seems like it could work
it can be reversed, if there are some issue
closes https://github.com/streamlink/streamlink/issues/971

cli.argparser: Fix single hyphen params at the beginning of --player-args

---

src/streamlink/plugins/goodgame.py

Fixes #2406, use `string.format` instead.

plugins.goodgame: fix for debug logging error

---

src/streamlink_cli/main.py

These checks can take a long time in the case of a typo in the url, for example.
This sets the return code to 130 so that external scripts can handle it
correctly.

Handle keyboard interrupts in can_handle_url checks

---

docs/plugin_matrix.rst
src/streamlink/plugins/teamliquid.py
tests/plugins/test_teamliquid.py

closes https://github.com/streamlink/streamlink/issues/2407
closes https://github.com/streamlink/streamlink/issues/2416
---
not sure if there is a better way for fixing the `stream_weight`,
but this would work for now.
---
Plugin could also be removed, as the website is just reusing other Streams.

plugins.teamliquid: New domain, fix stream_weight

---

src/streamlink/plugins/cdnbg.py
tests/plugins/test_cdnbg.py

Fixes #2501 by adding support for the new BSTV url.

plugins.cdnbg: fix for bstv url

---

src/streamlink/plugins/schoolism.py
tests/plugins/test_schoolism.py

If videos have subtitles, then the data structure that describes the sources is different and the difference needs to be accounted for. 
Fixes #2491.

plugin.schoolism: bug fix for videos with subtitles

---

src/streamlink/plugins/youtube.py

close #2539.
Before this patch
```
PS E:\> streamlink -o test.ts -l debug https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live
[plugin.youtube][debug] Video ID from currentVideoEndpoint
[plugin.youtube][debug] Using video ID: 4EA6OIYo3gM
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 140 = 1080p
[plugin.youtube][debug] MuxedStream: v 299 a 140 = 1080p60
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, …
```

plugin.youtube: bug fix for YouTube live streams check

---

src/streamlink/stream/dash.py

Uses the `DASHStream.args` in the `DASHStreamWriter` to request segments, and in `DASHStreamWorker` to reload the manifest. 
`copy.deepcopy` is used in `DASHStreamWriter.fetch` because the the `headers` can be modified with a Range header, and it would be set the headers for all future requests otherwise. 
Fixes #2291

stream.dash: use the stream args in the writer and worker

---

src/streamlink/session.py
src/streamlink_cli/argparser.py
tests/test_session.py

This sets the default value of `https-proxy` to same as `http-proxy`, it can be overridden still by setting `https-proxy`.

session: default https-proxy option to the same as http-proxy

---

src/streamlink/plugins/beattv.py
tests/plugins/test_beattv.py

There is no easy way to determine which stream to pick in some cases, for example the series pages have multiple streams but nothing in the url to indicate which is playing.
No sure if there is much interest in the plugin, the current one is totally broken and I cannot find an issue about it.

plugins.beattv: partial fix for the be-at.tv streams

---

src/streamlink/stream/ffmpegmux.py

- fixes invalid timestamp on recorded files
- fixes invalid timestamp on live player cache playback
- starts the timestamp always at 0 if -copyts was used
- removed wrong called log, it should have been `self.logger` when it was changed
it was only used for one line instead of all at the moment.
Fixes https://github.com/streamlink/streamlink/issues/2488

ffmpegmux: use -start_at_zero with -copyts

---

src/streamlink/plugins/tvrplus.py
tests/plugins/test_tvrplus.py

Fixes the plugin after website layout change:
```
$ streamlink https://www.tvrplus.ro/live/tvr-international
error: No plugin can handle URL: https://www.tvrplus.ro/live/tvr-international
```

plugins.tvrplus: fix for new website layout

---

src/streamlink/plugins/gulli.py
tests/plugins/test_gulli.py

This PR enables HTTPS support for the Gulli plugin. It also fixes live stream fetching:
```
$ streamlink http://replay.gulli.fr/Direct
[cli][info] Found matching plugin gulli for URL http://replay.gulli.fr/Direct
error: Unable to parse JSON: Expecting property name enclosed in double quotes: line 4 column 21 (char 242) ('[\n                {\n             ...)
```

plugins.gulli: HTTPS support + fix live stream fetching

---

src/streamlink/plugins/ustreamtv.py
src/streamlink_cli/argparser.py

Supports establishing WebSocket connections using the same proxy as specified by `--http-proxy`. 
Fixes #2531.

plugins.ustreamtv: add support for proxying WebSocket connections

---

src/streamlink/plugins/bbciplayer.py

The info API only works over HTTPS now. 
Fixes #2594

plugins.bbciplayer: update API URL to use https

---

src/streamlink/plugins/vk.py

Example Livestreams can be found on https://vk.com/video
```
$ streamlink https://vk.com/video-45085246_456239928 -l info
[cli][info] Found matching plugin vk for URL https://vk.com/video-45085246_456239928
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
```
closes #2595

plugins.vk: use html_unescape for HLS streams

---

src/streamlink/plugins/bilibili.py

The bilibili API has changed and quality options are now in range of [4,3,2]. Using quality=0 could only fetch 720p stream
#2590

plugins.bilibili: fix resolution issue

---

src/streamlink/plugins/foxtr.py

With a small url regex change, this plugin could play both of the media sites of Fox TR.

plugins.foxtr: Extended support

---

README.md

Change default installation instructions to remove use of "sudo", as it is highly discouraged.
References:
- https://pages.charlesreid1.com/dont-sudo-pip/
- https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice
- https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip
Other very popular packages also refraining from using "sudo" in their documentation:
- https://pyyaml.org/wiki/PyYAMLDocumentation
- https://github.com/psf/requests
- https://docs.scipy.org/doc/numpy/user/building.html
---
**Edit:** PR changed according to feedback.

Remove direct installation instructions, link to docs

---

.travis.yml

This "bumps" the `pynsist` (Windows installer) dependency to `2.4` and downloads it from pypi instead of cloning the git repo from github and checking out a pre-release commit ID.
The old commit ID was added because pynsist's author didn't publish a new release when we needed the fixes earlier this year, see here:
https://github.com/takluyver/pynsist/commits/master
This has been resolved now since July.
This PR basically doesn't do much other than making the CI config more readable. Since we're going to add Github actions as a secondary CI service soon, I don't want to have mixed or weird dependency definitions, as it's confusing.

ci/travis: install pynsist 2.4

---

docs/plugin_matrix.rst
src/streamlink/plugins/albavision.py
tests/plugins/test_albavision.py

Supports
- http://www.tvc.com.ec
- http://www.rts.com.ec
- https://www.elnueve.com.ar
with some paritially hardcoded streams. This list can be expanded by
adding more hardcoded stream urls, or by parsing the stream urls from
the javascript (a future enhancement).
Fixes #1825.

plugins.albavision: support for some albavision live streams

---

src/streamlink/plugins/idf1.py
tests/plugins/test_idf1.py

This PR enables HTTPS support for the IDF1 plugin.

plugins.idf1: HTTPS support

---

docs/plugin_matrix.rst
src/streamlink/plugins/linelive.py

Support archived broadcasts for `linelive`
Example URL: https://live.line.me/channels/1805733/broadcast/10625625
Also had a couple of issues reported by flake8 in the previous version that are now fixed.

plugins.linelive: update to support VOD/archived streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/vlive.py
tests/plugins/test_vlive.py

Adds support for live streams on https://www.vlive.tv/
Fixes #2544
Their (edited) VODs are embeded from Naver and work completely differently, so they're not supported.

plugins.vlive: Add support for V LIVE live streams

---

src/streamlink/stream/rtmpdump.py
src/streamlink/stream/streamprocess.py
tests/streams/test_stream_streamprocess.py

StreamProcess provided an is_usable method, use that method to check if the process can be launch and give a more useful error message if not.
~I renamed RTMPStream to `rtmpdump`, because it uses that. I don't think it will be a problem as it's just a pretty name.~ @bastimeyer pointed out this was bad :)

stream.streamprocess: check that a process is usable before using it

---

src/streamlink/stream/hls.py

Fixes https://github.com/streamlink/streamlink/issues/2701
Fixes https://github.com/streamlink/streamlink/issues/2703
not worth to create two PRs as it uses the same log line.

stream.hls: Fix UnicodeDecodeError for log msg and name_prefix for stream_name

---

src/streamlink/plugins/twitch.py

This adds the option to disable twitch reruns similar to disabling hosted streams.
~I know the check for the `stream_type` could also be directly done in `_get_hls_streams`. If you like that better tell me and I can change it :)~
Edit: I decided to change it. This should have less changes and I think my previous solution broke the tests for the skip-ads option.
Closes #2721

Allow to disable twitch reruns

---

src/streamlink/plugins/youtube.py

1080p60 video/webm format that doesn't work
example video: https://www.youtube.com/watch?v=9lb0gZRO2Go
closes https://github.com/streamlink/streamlink/issues/2694

plugins.youtube: Remove itag 303

---

src/streamlink/plugins/bbciplayer.py
tests/plugins/test_bbciplayer.py

solution from https://github.com/streamlink/streamlink/issues/2716#issuecomment-565192550
closes https://github.com/streamlink/streamlink/issues/2716
```
$ streamlink http://www.bbc.co.uk/iplayer/live/bbcone best --bbciplayer-username XXX --bbciplayer-password XXX
[cli][debug] OS:         Linux
[cli][debug] Python:     2.7.15+
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/live/bbcone
[cli][debug] Plugin specific arguments:
[cli][debug]  --bbciplayer-username=XXX (username)
[cli][debug]  --bbciplayer-password=******** (password)
[plugin.bbciplayer][debug] Loading stream for live channel: bbcone
[plugin.bbciplayer][debug] Looking for  tvip on …
```

plugins.bbciplayer: Fixed login params

---

src/streamlink_cli/output.py
tests/test_cmdline_title.py

Fixes #2764
See https://github.com/mpv-player/mpv/commit/d3cef97ad38fb027262a905bd82e1d3d2549aec7
The MPV change is supposed to print out a deprecation warning, but if it causes the player to immediately terminate as described in #2764, this would mean that we should publish a patch release soon. As I've said on Gitter, such a breaking change with the parameter parsing should actually require a major version bump on the side of MPV. Weird.

cli.output: fix mpv player parameter format

---

src/streamlink/plugins/tf1.py

This PR fixes DASH stream retrieving by using a new API (the same currently called by the TF1 website):
* before fix:
```
$ streamlink -l debug https://www.tf1.fr/tmc/direct
[cli][debug] OS:         Linux-5.3.16-300.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[cli][debug] Python:     3.7.5
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tmc/direct
[plugin.tf1][debug] Found channel tmc
[plugin.tf1][debug] Got dash stream https://tmc-das-live-ssl.tf1.fr/tmc/1/dash/live_3000000.mpd?e=1578405380&st=aXyXTL7lopcXZt_o8coVYA
[plugin.tf1][error] Could not open dash stream
[plugin.tf1][debug] Failed with error: Unable to open URL: …
```

plugins.tf1: use new API to retrieve DASH streams

---

src/streamlink/plugin/api/http_session.py
src/streamlink/plugin/api/useragents.py

- User-Agent update
---
less robot detection for http calls without a User-Agent

plugin.api: use Firefox as default User-Agent instead of python-requests

---

src/streamlink/plugins/reuters.py
tests/plugins/test_reuters.py

Update to fix: https://github.com/streamlink/streamlink/issues/2803
- Add support for .com TLD and country specific sub-domains 
- Find IFRAME and then GET its source HTML as necessary
- Update tests to include reuters.com and uk.reuters.com URLs
I've tested this pretty thoroughly, as per: https://github.com/streamlink/streamlink/issues/2803#issuecomment-593011020
closes https://github.com/streamlink/streamlink/issues/2803

plugins.reuters fix

---

src/streamlink/plugins/twitch.py
src/streamlink/session.py
src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/plugins/test_twitch.py

Maybe this should be done in two separate pull requests, but here we go.
These changes are mainly based on the work of @back-to and his low latency test plugin for Twitch (see [here](https://github.com/streamlink/streamlink/issues/1676#issuecomment-430304591)).
**Description**
- Adds the `--hls-segment-stream-data` parameter, which makes Streamlink write the HLS segments to the output buffer while they are being downloaded.
- Adds HLS segment prefetching to the custom `TwitchM3U8Parser`.
- Lowers the playlist refresh time to the duration of the HLS segments (2 seconds).
- Adds the `--twitch-low-latency` shorthand plugin-parameter, which automatically sets `--hls-segment-stream-data` to true and limits the value of `--hls-live-edge` to a maximum of 2, as higher values (default is 3) are …

plugins.twitch: low latency

---

src/streamlink/plugins/bilibili.py

closes https://github.com/streamlink/streamlink/issues/2816
```
[plugin.bilibili][debug] Netloc: d1--cn-gotcha05.bilivideo.com
[plugin.bilibili][error] Netloc: txy.live-play.acgvideo.com with error 403
[plugin.bilibili][error] Netloc: d1--cn-gotcha01.bilivideo.com with error 404
[plugin.bilibili][error] Netloc: txy.live-play.acgvideo.com with error 403
[cli][info] Available streams: source (worst, best)
[cli][info] Opening stream: source (http)
```

plugins.bilibili: ignore unavailable URLs

---

src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
tests/streams/test_hls.py

This will replace the host in the segment URI with the supplied HOST

add templating for hls-segment-key-uri option

---

src/streamlink/plugins/bloomberg.py

Fixes #2823 
Fixes live streams and vods (tested US+EU live streams and most recent VOD).
Couple of notes:
- The JSON object for the live stream CDN data has to be extracted from a webpack-bundled and minified JS file, just like before. The reason why the extraction failed was a change in the structure of this app file. Extracting this data will always be problematic, because the regex requires anchors for the JS module-IDs of the webpack bundle, and just like it is with all webpack production builds, all useful data (for us) gets stripped off and we're left with IDs. ~~This means that as soon as they'll add another module and rebuild the whole thing, the regex will most likely break again due to an ID shift.~~ Even though I've added a second regex for getting the module ID from another …

plugins.bloomberg: fix vods and live streams

---

docs/plugin_matrix.rst
src/streamlink/plugins/showroom.py

use a custom playlist_reload_time of 1.5 sec
closes https://github.com/streamlink/streamlink/pull/2735
closes https://github.com/streamlink/streamlink/issues/2726

plugins.showroom: Fix HLS missing segments

---

docs/ext_argparse.py

Multiple double-dash parameters are currently ignored in the docs. Example:
https://streamlink.github.io/latest/cli.html#cmdoption-twitch-low-latency
Parameter descriptions are now parsed line by line and lines starting with [two spaces](https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-key-uri) (rendered as code blocks) or with [`Example: `](https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-ignore-names) get ignored. Then on each matching line, all double-dash params at the start of the line or with a leading space get transformed into anchors.

docs: fix multiple options on the same line

---

src/streamlink/plugins/pixiv.py

It doesn't work because they use reCAPTCHA,
removed it so it doesn't confuse people.
---
use cookies instead
`--pixiv-sessionid`
https://streamlink.github.io/cli.html#cmdoption-pixiv-sessionid
`--pixiv-devicetoken`
https://streamlink.github.io/cli.html#cmdoption-pixiv-devicetoken
if it doesn't work, try `--pixiv-purge-credentials`
https://streamlink.github.io/cli.html#cmdoption-pixiv-purge-credentials
---
closes https://github.com/streamlink/streamlink/issues/2515
closes https://github.com/streamlink/streamlink/pull/2521
ref https://github.com/streamlink/streamlink/pull/2529

plugins.pixiv: removed not working login process via username

---

docs/api_guide.rst

A module directive for the streamlink module is duplicated in
both `api_guide.rst` and `api.rst`.
Remove the one in `api_guide.rst`.
This was triggering warning with sphinx:
```
WARNING: duplicate object description of streamlink, other instance in
api, use :noindex: for one of them.
```

docs: fix duplicate object description of streamlink in api docs

---

.github/workflows/main.yml

This fixes the irrelevant but potentially confusing error message if a test has failed on one of the required test jobs. Github expects a boolean value on the `continue-on-error` config, but `matrix.continue` is only set on additional allowed-to-fail jobs, which we currently don't have, so the value is an empty string instead, which it doesn't like.
Example:
https://github.com/streamlink/streamlink/runs/567342748?check_suite_focus=true#step:6:15
Fixed:
https://github.com/bastimeyer-test/streamlink-test/runs/567542014?check_suite_focus=true#step:5:271

ci.github: fix continue on error

---

src/streamlink/utils/encoding.py
src/streamlink_cli/main.py
src/streamlink_cli/output.py
tests/__init__.py
tests/test_cli_playerout.py
tests/test_cmdline_title.py

This should resolve the encoding issue in log messages for the command line arguments. 
fixes #2444

util: fix some encoding issue when setting unicode/utf8 titles in py2

---

docs/plugin_matrix.rst
src/streamlink/plugins/rtve.py
tests/plugins/test_rtve.py

Added support for clan tve, children's channel of RTVE, online available at [https://www.rtve.es/infantil/directo/](https://www.rtve.es/infantil/directo/) since March.

Added support for clan tve, children's channel of RTVE

---

src/streamlink/utils/url.py
tests/test_utils_url.py

Updates the `update_qsd` to support blank param values.
As pointed out by @calculon-jr in [#2747](https://github.com/streamlink/streamlink/pull/2747/files/b90362964e5c582eb9d960520386f4f12f8e3f54..b0a5f75146b1e0ca0bca6ecd8405878735c01aa7﻿).
I also refactored the tests for the url utils to be more pytesty.

utils: update_qsd to leave blank values unchanged

---

src/streamlink/plugins/twitch.py
src/streamlink/stream/hls.py
tests/plugins/test_twitch.py

Resolves #2894
Simply filters out segments that are annotated with `#EXTINF:2.002,Amazon[...]`.
`--twitch-disable-ads` needs to be set, just like before.
edit:
Well, it doesn't "resolve" the issue, just replaces the `--twitch-disable-ads` logic with new one. As I've mentioned in the linked thread, Twitch's webplayer is not showing any ads to me and I haven't figured out yet why. If someone knows how to "trick" Twitch into providing the real stream data, then that would be considered the real "fix" for the issue. Nevertheless, the parameter needs new filtering logic.
----
The stream discontinuities when the "ad" switches to the regular stream data seems to be causing a lot of issues in various players, especially VLC (no idea about the used version though). Maybe we should re-evaluate …

plugins.twitch: rewrite disable ads logic

---

.github/workflows/main.yml

See https://github.com/streamlink/streamlink/pull/2656#discussion_r411630309.
I took the liberty of doing it, in case @back-to didn't get round to it :)
We'll need to remove the `PYPI_USER` secret after this is merged too.

actions: no need to use a secret for the PyPI username

---

src/streamlink/session.py

In a future version of streamlink only Python 3.5 and above will be supported.
As suggested in #2921

add python 2.7 deprecation warning

---

src/streamlink/plugins/showroom.py

closes https://github.com/streamlink/streamlink/issues/2918
```
$ streamlink https://www.showroom-live.com/--- low --hls-segment-threads 10 -l info
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/---
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: low (hls)
```

plugins.showroom: use normal HLSStreams

---

.github/workflows/main.yml

such as `streamlink==0+untagged`
https://github.com/streamlink/streamlink/runs/616367673?check_suite_focus=true#step:4:89
also `depth=1` won't work see
https://github.com/streamlink/streamlink.github.io/blob/e066aa52513b89304bf3396e52615c8b3109f1b4/latest/api.html#L10
use better upload names for codecov
> os:ubuntu-latest py:3.7

actions: fixed incorrect versions and use names for codecov

---

docs/install.rst

Users should now use Debian backports when using Debian stable instead of using bintray.

docs: update debian install instructions

---

src/streamlink/plugins/twitch.py

fixes https://github.com/streamlink/streamlink/issues/2751

plugins.twitch: fix call_subdomain

---

src/streamlink/plugins/tvplayer.py

Closes https://github.com/streamlink/streamlink/issues/2983

plugins.tvplayer: Add missing platform key in the GET for stream_url

---

docs/install.rst

This PR adds info on how to install it from there, with the same format at the chocolatey link.

Streamlink was added to Windows Package Manager, adds info on how to install it to the docs

---

src/streamlink/plugin/plugin.py

Only saw it while reading through the source code. Really doesn't matter.

Fixed typo (synonmys => synonyms)

---

.github/workflows/main.yml

These jobs are unnecessary on scheduled builds, since only commits get merged into master which have passed the tests previously.
Also avoids recurring code coverage uploads if no commits get merged into master between two scheduled builds.
----
Ideally we should cancel the whole workflow run if there were no new commits since the last scheduled build, but that would require adding an additional job that runs before the test, documentation and installer jobs.
----
Duplicate code coverage upload:
- https://github.com/streamlink/streamlink/runs/740545127?check_suite_focus=true#step:7:40
- https://codecov.io/gh/streamlink/streamlink/commit/90e634ec17cd7b90f062f25f2b620e50285dd9c0/build

ci: no test/documentation jobs on scheduled run

---

src/streamlink/plugins/radionet.py

I think the page layout for radio.net changed about a month ago, at least that's when the radionet plugin stopped working for me.
I hacked the code so it works for me.
Note - the plugin is hardcoded to return `live` for bitrate as I don't think this is available any more.
Here's a trimmed example of the JSON we scrape from the page:
```
{
'id': 'bbcradio4lw',
'name': 'BBC Radio 4 Long Wave',
'streams': [
{
'url': 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4lw_mf_q',
'contentFormat': 'audio/mpeg'
}
],
'type': 'STATION'
}
```

fix radionet plugin so it works with new radio.net page format

---

script/install-dependencies.sh
src/streamlink/utils/l10n.py

See #3054 and the comments in #3055
~~This will require py2 to be dropped first (tests will fail - will rebase once done), as pycountry's recent release has removed it.~~ The added lookup workaround can be removed as soon as pycountry fixes the issue itself (see flyingcircusio/pycountry#41).
The reason why pycountry had to be downgraded with a fixed version in #3054 was an upgrade of their database with the addition of the En language, causing generic "en" language lookups to return this instead of English. Since the returned language record doesn't have an `alpha_2` code, trying to access this attribute resulted in a raised AttributeError, causing the tests to fail.
Pycountry is being used by the packages on Arch (community repo and AUR), Debian/Ubuntu/etc and Gentoo and thus needs to be …

utils.l10n: fix pycountry language lookup

---

src/streamlink/plugins/nicolive.py

Currently, “broadcast_id” field of Nicolive api is not needed.
fix #3028

Plugin.nicolive:resolve API format change

---

src/streamlink/plugins/showroom.py
src/streamlink/plugins/twitch.py
src/streamlink/session.py
src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/streams/test_hls.py

Adds support for customizable HLS playlist reload times via `--hls-playlist-reload-time`.
Values can be
- numbers (float) greater than 2 - self-explanatory
- `"segment"` - sets refresh time to the duration of the last segment
- `"live-edge"` - sets refresh time to the sum of durations of the `live-edge - 1`  last segments
For all other values, falls back to the playlist's `target_duration` if it is set, otherwise does the same as `live-edge` (this logic got changed, was `segment` before), and if no target duration and no segments are present, then the default value of 15 is used.
Also renames `HLSStreamWorker._set_playlist_reload_time` to `HLSStreamWorker._playlist_reload_time` and sets the reload time from its return value instead.
----
The changes are rather trivial, but I'd like to …

stream.hls: customizable playlist reload times

---

docs/plugin_matrix.rst
src/streamlink/plugins/huomao.py
tests/plugins/test_huomao.py

- Add support for VODs
- Add support for title, author and category information
- Update URLs in tests
I have a couple of things I'd like to ask you about with this PR:
The first thing is while attempting to play the very short (< 4s) clip at: ```https://www.huomao.com/video/v/96953```.  This requires either the use of ```--player-no-close``` or ```--hls-segment-stream-data``` options.  I think I understand the requirement for using either of those options.  In the case of the former, the clip plays eventually and streamlink will exit immediately.  In the case of the latter, the clip plays immediately but streamlink only exits after it has finished its attempts at reloading the playlist.  In both cases, streamlink makes 20+ attempts at reloading the playlist.  With the latter streamlink …

plugins.huomao: fix/rewrite

---

src/streamlink/plugins/bloomberg.py

Fixes #3130
The module structure has slightly changed after a recent update of their site, and now the regex doesn't match anymore.
See my comment from the previous plugin fix/rewrite:
https://github.com/streamlink/streamlink/pull/2825#issuecomment-599043223
Since some stream URLs seem to be static, an alternative to extracting the stream URLs could be hardcoding them into the plugin. This is the JSON data we're currently extracting:
https://gist.github.com/bastimeyer/ec6f3be45adc4a8ffdc476707564814a
----
```
$ streamlink https://www.bloomberg.com/live/us -l debug
[cli][debug] OS:         Linux-5.8.3-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.5.0+13.g80eb861
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found …
```

plugins.bloomberg: fix regex module anchor

---

src/streamlink/plugins/zattoo.py

quantum-tv had changed how their login worked:
- client token is hidden behind a obscure url
- they use zapi/v3
- session hello must only consist of token, uuid, app_version

fix quantum tv streaming

---

src/streamlink/plugins/vk.py

```
$ streamlink https://vk.com/video?z=video-106042931_456240719
[cli][info] Found matching plugin vk for URL https://vk.com/video?z=video-106042931_456240719
[cli][info] Opening stream: live (hls)
```

plugins.vk: remove '\' from data

---

src/streamlink/plugins/nicolive.py

```
$ streamlink "https://live2.nicovideo.jp/watch/lv327858775"
[cli][info] Found matching plugin nicolive for URL https://live2.nicovideo.jp/watch/lv327858775
[cli][info] Available streams: 3600k (worst, best)
[cli][info] Opening stream: 3600k (hls)
```
now
```
$ streamlink "https://live2.nicovideo.jp/watch/lv327858775"
[cli][info] Found matching plugin nicolive for URL https://live2.nicovideo.jp/watch/lv327858775
[cli][info] Available streams: 345k (worst), 691k, 1800k, 3600k, 5400k (best)
[cli][info] Opening stream: 5400k (hls)
```
closes https://github.com/streamlink/streamlink/issues/3151

plugins.nicolive: fix quality

---

src/streamlink/plugins/sportschau.py
tests/plugins/test_sportschau.py

Fixes #3141
**live**
```
$ streamlink -l debug 'https://www.sportschau.de/tourdefrance/live/videostream-livestream-ab--uhr---die--etappe-der-tour-de-france-zum-mont-aigoual-100.html'
[cli][debug] OS:         Linux-5.8.3-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.5.0+20.gb86471b
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin sportschau for URL https://www.sportschau.de/tourdefrance/live/videostream-livestream-ab--uhr---die--etappe-der-tour-de-france-zum-mont-aigoual-100.html
[plugin.sportschau][debug] Found player js https://deviceids-medp.wdr.de/ondemand/221/2214191.js
Available streams: 180p_alt (worst), 180p, 270p_alt, 270p, 288p_alt, 288p, 360p_alt, …
```

plugins.sportschau: rewrite and fix plugin

---

src/streamlink/plugins/raiplay.py

Fixes #3143
Would appreciate it if someone with an italian IP could test that it's working correctly for geo-restricted content.
```
$ streamlink -l debug 'https://www.raiplay.it/dirette/rainews24'
[cli][debug] OS:         Linux-5.8.3-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.5.0+20.g8cf9306
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rainews24
[plugin.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/rainews24.json
[plugin.raiplay][debug] Found stream URL: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1
Available streams: 288p (worst), 352p, 396p (best)
```
```
$ streamlink -l …
```

plugins.raiplay: rewrite and fix plugin

---

src/streamlink/__main__.py
src/streamlink_cli/__main__.py

It seems that `python -m streamlink -h` raises an error, at least on Windows:
```
python -m streamlink -h
No module named streamlink.__main__; 'streamlink' is a package and cannot be directly executed
```
This can be fixed by adding the `__main__.py` files to both `streamlink_cli` and `streamlink` packages with the appropriate content.

support `python -m` invocation style

---

src/streamlink/plugins/twitch.py
src/streamlink/stream/hls_filtered.py
tests/streams/test_hls_filtered.py

Closes #3178
Closes #3165
This adds the general purpose `FilteredHLSStreamWriter` and `FilteredHLSStreamReader` classes which filter out HLS segments and prevent the [`IOError("Read timeout")` from being raised by the `RingBuffer`](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/src/streamlink/buffers.py#L104-L112) while segments are being filtered out and the buffer not being filled / written to.
I'm not sure if this is the best or even a good implementation. The problem is that I don't want to subclass the `RingBuffer` for this and don't want to modify the [`streamlink_cli` logic](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/src/streamlink_cli/main.py#L268-L390) either. This means that the `IOError` needs …

Add FilteredHLSStream

---

src/streamlink/plugins/ine.py

@bastimeyer, I don't know if these test failures under Py2 are something you might need to look into.  Perhaps they're already fixed in #3194 though?

plugins.ine: fix unescaped literal dots in js_re

---

.codecov.yml

Removing covered test lines will reduce the coverage percentage. This is the case for example in plugin removals, and those are not supposed to fail. If we had 100% coverage in a status where the threshold is set to 0, removing lines wouldn't be a problem, but the tests are currently at 99.56%, which means we need to increase the threshold by a bit. This also means that poorly written tests won't fail anymore unless they reduce the overall percentage by 1%.
A proper fix would be increasing the tests coverage to 100%, but some of the missed lines can't be annotated. And then there are also partial hits.

ci.coverage: increase threshold of tests status

---

src/streamlink/stream/hls.py
tests/mixins/stream_hls.py
tests/plugins/test_twitch.py
tests/streams/test_hls.py
tests/streams/test_hls_filtered.py

Sorry for another wall of text, but this is a fix / cleanup for all existing HLS integration tests which I've mentioned in #3194. Please bear with me, because that are quite a lot of changes, although not too difficult and also split up into multiple commits. Except for a few cases, the logic of the individual tests was not changed and just cleaned up / simplified.
Description of the individual commits:
1. Adds the `TestMixinStreamHLS` class and related ones for simplification of all HLS integration tests. The module was added to the `tests.mixins.stream_hls` import path, but I'm not sure if it's a good choice or if it breaks any conventions. If so, this needs to be moved elsewhere.
The mixin provides methods for creating a fake HLS stream, mocking the requests, creating a dedicated read …

tests: clean up existing HLS stream tests

---

src/streamlink/plugins/twitch.py

This once again removes the `platform=_` parameter from the stream access token request.
See #3210
As mentioned there, we need a better solution for this. Am happy to discuss this.
----
History of the parameter:
1. Added in #2358
2. Removed in #2692
3. Added in #3173

plugins.twitch: remove platform access token param

---

docs-requirements.txt
docs/conf.py

Sphinx v1.8 has [deprecated source_parsers](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_parsers) which is used for recommonmark.
This commit replace the use of source_parsers for recommonmark with the
use of recommonmark as an extension (supported by recommonmark since
0.5.0).
Note: I've made a version requirement on recommonmark of >= 0.5.0 as recommonmark can't be used as a sphinx extension before that version.
If you want to keep compatibility with recommonmark v0.4.0 and older, just close this PR :-)

docs: use recommonmark as an extension

---

.codecov.yml
.github/workflows/main.yml

Python 3.9 has been released yesterday / two days ago and Github has added Python 3.9 builds a few hours ago. This requires a bump of the `actions/setup-python` action to `v2`, since it's not available in the default virtual environments of the CI runners.
- https://docs.python.org/release/3.9.0/whatsnew/3.9.html
- https://github.com/actions/setup-python
- https://github.com/actions/python-versions/commit/1430296346bab896c21a97ff3396425c26ad87b1
----
Python 3.5 is also no longer supported now and should be dropped now once we finally drop 2.7:
- https://blog.python.org/2020/10/python-35-is-no-longer-supported.html
That's currently an overall number of 12 test runners now. A bit much. Dropping 2.7 and 3.5 would reduce it to 8.

ci: add python 3.9 test runners

---

src/streamlink/stream/segmented.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py

This should fix the following issue in #3227:
https://github.com/streamlink/streamlink/runs/1227523417?check_suite_focus=true#step:5:257
----
Two issues fixed in one PR (don't squash):
1. Sometimes the writer thread was too fast for the reader thread of the stream_hls test mixin to read, and it closed before the first read occured. The result was an empty read, since the buffer got closed by the writer thread too early. This PR makes the writer thread wait before closing until the reader thread has at least attempted to read once.
2. Currently, Streamlink doesn't wait for the spawned threads of the `ThreadPoolExecutor` to shut down and immediately clears all queued thread pool threads globally. This is not a particularly graceful way to close the writer thread: …

tests: fix early writer close in stream_hls mixin 

---

src/streamlink/plugins/twitch.py
tests/plugins/test_twitch.py

Opening this as a draft PR for now, because it's still WIP.
As already said in #3206, I wanted to refactor the entire Twitch plugin, as it hasn't been done in years and there's a ton of cruft.
I've split this up into multiple commits for reviewing reasons, but this should be squashed if it gets merged. Commits are therefore probably not 100% optimal and also don't have a proper commit message.
I can rebase this into fewer proper commits though, if you feel like it's too many changes for a single commit if squashed.
----
**My goals with the code-refactor are the following:**
1. Move most from the module's global context to class attributes, where it belongs
2. Remove old and now unsupported stuff (also affects plugin's URL regex)
- Remove different video types
[There's only one type …

plugins.twitch: refactor plugin

---

script/deploy-docs.sh

This should fix the clean working tree check in the docs deploy script.
I've restarted the CI jobs earlier today because of an issue on codecov and wanted the reports to be re-uploaded. Then the deploy-docs job failed afterwards, because it tried to commit from a clean working tree. The `git diff-index --quiet HEAD --` check was supposed to catch that, but apparently it doesn't. Checking for an empty stdout of `git status --porcelain` catches all changes, untracked files, etc. and is therefore better, even though git's high-level "porcelain" commands are technically not meant for scripting.
- https://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git/5737794#5737794
- https://github.com/streamlink/streamlink/runs/1225045245#step:7:25
- …

docs: fix working tree check in deploy script

---

CONTRIBUTING.md

The last revision of the plugin request/submission guidelines was made two years ago in #1838.
Lately we've seen a few requests and PRs for radio stations, which we don't want to merge. This should be included in the list of plugin restrictions.
I've also added a generic pull request template, since we don't have one. Nothing big, just a small reminder to read the guidelines, add a comment and run local checks if possible.

docs: update plugin guidelines

---

.github/pull_request_template.md
docs/developing.rst
docs/index.rst

As mentioned in #3244, this adds a **basic** guide for setting up a dev environment and running tests, etc. locally. In the future, this can be extended with guides on how to write plugins, but for now, this is enough.
And of course the pull request template with a link to the new docs section.
Happy to discuss any changes/improvements/additions...

docs: add basic development setup guide

---

docs/plugin_matrix.rst
src/streamlink/plugins/tv3cat.py
tests/plugins/test_tv3cat.py

- allow http and https schemes in URL match
- escape literal dots in URL match
- remove unnecessary pass statement in except
- update test for both http and https
- update plugin matrix with correct domain
I'm not sure why the LGTM check didn't flag the un-escaped literal dots in the URL match for this plugin before...
closes  #3246

plugins.tv3cat: update URL match, test and plugin matrix

---

docs/plugin_matrix.rst
src/streamlink/plugins/cbsnews.py
tests/plugins/test_cbsnews.py

Support for live streams from CBS News.
Including:
- https://www.cbsnews.com/live/
- https://www.cbsnews.com/live/cbsn-local-bay-area/
- https://www.cbsnews.com/live/cbsn-local-ny/

plugins.cbsnews: support for live streams from CBS News

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/plugin_issue.md
.github/ISSUE_TEMPLATE/plugin_request.md
.github/issue_template.md

I don't know if it'll help or perhaps you don't think it's that much of a problem...  It is, however, nice to get log output in text, if only for copying the URL, rather than having to manually type it in if the URL has not been specified in text form elsewhere in the issue.

chore: update issue templates

---

src/streamlink/plugins/artetv.py

Removes the f4m and http streams from the returned list, and only returns the default variant for the stream. I believe this will match the expected behaviour. 
see #3167

plugins.artetv: only pick the first variant of the stream

---

src/streamlink/utils/l10n.py

set `language_code` to `DEFAULT_LANGUAGE_CODE` if `_parse_locale_code()` fails.

utils.l10n: use DEFAULT_LANGUAGE_CODE if locale lookup fails

---

src/streamlink_cli/main.py

As arguments can be loaded from a config file these need to be loaded as soon as possible otherwise some options will not have the desired effect. For example, `quiet` can be specified in `.streamlinkrc`, however it will not take effect. With this change the default config args are loaded earlier, however plugin specific config files are still loaded later.
Options that will take effect from the config file now include:
- `loglevel` **
- `json`
- `stream_url`
- `subprocess-cmdline`
- `quiet`
- `stdout`
- `output`
- `record-and-pipe`
- `plugin-dirs`
The plugin specific config option behaviour remains unchanged, and `loglevel` is the only option that is affected.
I do not think it is possible to sensibly load the plugin specific options early, there are too many opportunities for errors. I …

cli: make config based args available during early setup

---

CHANGELOG.md

Release date is already set for tomorrow, since I don't expect a merge within the next 3 hours.
I had to manually clean up the git shortlog, since commit 50c8cc2f6416083aab61b237e00fe50e54c5b8e3 has a malformed commit message. It was probably just a mistake and everybody is aware of the basic format (and naming scheme), but please take a better look at the commit messages before merging and double-check. It's all fine though and not too much of a big deal.
Closes #3258

release: 1.7.0

---

.codecov.yml
.github/workflows/main.yml
docs/install.rst
script/build-and-sign.sh
script/install-dependencies.sh
setup.cfg
setup.py
src/streamlink/session.py

- Bump Python version requirement to 3.5
- Remove unneeded compatibility dependencies
- Remove py2 warning from streamlink.session
- Update pypi package classifiers
- Update docs
- Remove universal bdist_wheel
- Remove py2 from CI test runners
----
This is **WIP** and needs to be properly tested in a test-release first.
Additional resources:
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers
- https://pypi.org/classifiers/
Resolves #2896 
Closes #2920

chore: drop support for Python 2

---

src/streamlink/logger.py
src/streamlink/session.py
src/streamlink_cli/console.py
src/streamlink_cli/main.py
tests/test_console.py
tests/test_log.py

Split into two commits, each with a description of the changes in the commit message bodies.
Things to note:
1. **BREAKING**: Due to the removal of the custom `LogRecord` class, log calls cannot use the curly bracket format style with custom LogRecord args anymore, like `log.info("foo {0}", bar)`. The default Python behavior is the percent format style, but that's not recommended here, as log messages should all be pre-formatted via f-strings or string.format calls, to make them independent of the logging implementation.
2. **BREAKING**: This will change the trace logging format from `[18:30:35,123]` to `[18:30:35.123456]`
3. **BREAKING**: The LogRecord's msecs won't get used for formatting the trace log and instead its `created` attribute gets used via …

logger: remove deprecated compat logger

---

src/streamlink/plugins/btv.py
src/streamlink/plugins/crunchyroll.py
src/streamlink/plugins/pixiv.py
src/streamlink/plugins/twitch.py
src/streamlink/plugins/ustvnow.py
src/streamlink/plugins/youtube.py
src/streamlink/plugins/yupptv.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

This removes the following deprecated/suppressed CLI arguments:
- `--http-cookies`
Multiple `--http-cookie` arguments need to be used
- `--http-headers`
Multiple `--http-header` arguments need to be used
- `--http-query-params`
Multiple `--http-query-param` arguments need to be used
- `--no-version-check`
Version checking is opt-in via `--version-check` or `--auto-version-check`
- `--twitch-oauth-authenticate`
Auth on Twitch is not possible with OAuth tokens generated by 3rd-party client-IDs like Streamlink's
And the following deprecated/suppressed plugin arguments:
- `--btv-username` / `--btv-password`
- `--crunchyroll-locale`
Generic `--locale` argument needs to be used
- `--pixiv-username` / `--pixiv-password`
- `--twitch-oauth-token` / `--twitch-cookie`
As a workaround, …

chore: remove deprecated CLI arguments

---

dev-requirements.txt
tests/test_log.py

Set `tz_offset=0` so that `time.asctime` returns the expected value. This requires a more recent version of `freezegun`, so I set a minimum version in dev_requirements.txt.

tests: fix log tests when run on a system with a non-UTC timezone

---

src/streamlink/plugins/picarto.py

I had a rather odd failure in viewing a picarto.tv stream, which turned out to be caused by the streamer setting their stream to private. The web interface asks for a password to view the stream. Unfortunately, I don't have any passwords to private streams, so the best I can do for now is to explicitly detect a private stream and cleanly error out.

plugins.picarto: explicitly detect and fail on private streams

---

.github/workflows/main.yml

As briefly mentioned in #3285, this will make the PR checks fail faster in case there are linting errors but all tests are passing.
Also added the `--statistics --count` parameters, so that a summary gets included in the output when there are linting errors.

ci.github: run lint step before test step

---

src/streamlink/plugins/twitch.py

This sets the `player_type=frontpage` request parameter on the access token API call, which currently results in a streaming access token that doesn't embed ads into the HLS stream.
As already said in https://github.com/streamlink/streamlink/issues/3210#issuecomment-717735974, this might get changed again by Twitch, similar to the previous `platform=_` request parameter (#3220).
If this PR gets merged within the next 4.5 hours, it'll be included in the next Windows installer nightly build, which most people are probably looking forward to.

plugins.twitch: player_type access token parameter

---

src/streamlink/plugins/zdf_mediathek.py
tests/plugins/test_zdf_mediathek.py

3sat and ZDF mediathek essentially are the same, only the URLs and the API
URLs differ. So support 3sat URLs and check the URL to decide whether to
use the ZDF or 3sat API. Everything else is identical.

plugins.zdf_mediathek: also support 3sat mediathek

---

.github/workflows/main.yml

This installs the latest version of pynsist instead of pinning it to `2.4`. It was pinned to `2.4` because of #2655.
According to the [pynsist release notes](https://pynsist.readthedocs.io/en/latest/releasenotes.html), the newer versions (current one is `2.5.1`) assemble the executables during build-time rather than run-time/install-time. This cleans up the install directory by a bit and is less confusing for the enduser.
The NSIS GUI has also been improved with proper DPI scaling, but that requires NSIS 3.0 which is currently unavailable on the `ubuntu-18.04` CI image and `ubuntu-latest` still points towards `18.04`. That will change soon though, and once it does, the installer will see those improvements automatically. We could also manually set it to `ubuntu-20.04`.
----
While building …

ci.github: install latest version of pynsist

---

src/streamlink/plugins/abematv.py
src/streamlink/plugins/artetv.py
src/streamlink/plugins/crunchyroll.py
src/streamlink/plugins/cubetv.py
src/streamlink/plugins/dogan.py
src/streamlink/plugins/euronews.py
src/streamlink/plugins/gardenersworld.py
src/streamlink/plugins/nicolive.py
src/streamlink/plugins/onetv.py
src/streamlink/plugins/rtve.py
src/streamlink/plugins/steam.py
src/streamlink/plugins/tamago.py
src/streamlink/plugins/webtv.py
src/streamlink/stream/dash_manifest.py
src/streamlink/stream/hls.py
src/streamlink/utils/l10n.py
src/streamlink_cli/argparser.py
src/streamlink_cli/console.py
src/streamlink_cli/constants.py
src/streamlink_cli/main.py
src/streamlink_cli/output.py
tests/plugins/test_albavision.py
tests/plugins/test_tvplayer.py
tests/plugins/testplugin.py
tests/test_api_http_session.py
tests/test_api_validate.py
tests/test_cli_playerout.py
tests/test_cmdline_title.py
tests/test_utils.py

This removes all superfluous u-strings and also removes the unnecessary `__unicode__` magic method from some of the classes in `streamlink.utils.l10n`.
Most u-strings which were format templates were replaced by f-strings where it made sense.
Also, just as an additional note, some of the unicode related tests are not relevant anymore due to the py2 removal and could be removed as well, but it's not really important.

chore: remove u-strings

---

.github/workflows/main.yml

As mentioned in #3295, explicitly setting the CI environment to `ubuntu-20.04` will make NSIS 3 available for `pynsist`, so that the Windows installers can benefit from proper DPI scaling.
`ubuntu-latest` will be changed from `ubuntu-18.04` to `ubuntu-20.04` next month anyway, but the transitioning period is a couple of weeks and it doesn't hurt us setting an explicit version.
This also bumps the used python version in all CI jobs from `3.8` to `3.9`, as `3.9` is available natively now.

ci.github: set ubuntu to 20.04 and python to 3.9

---

src/streamlink_cli/argparser.py
src/streamlink_cli/constants.py
src/streamlink_cli/output.py
tests/test_cli_main.py
tests/test_cli_playerout.py

- Make the player input variable in the `--player-args` parameter
optional. If it's missing, append it to the parameter value.
- Rename it from `{filename}` to `{playerinput}`, to reduce confusion
and add `{filename}` back as a secondary fallback variable.
- Update parameter docs accordingly and add+fix tests
See: #2947

cli: optional player-args input variable

---

src/streamlink/stream/dash.py
src/streamlink/stream/hls.py
src/streamlink/stream/stream.py
src/streamlink_cli/main.py
tests/streams/test_hls.py
tests/test_cli_main.py
tests/test_stream_json.py

Resolves #3098
This enables the output of the input-stream's manifest/master URL via
`streamlink --stream-url URL` / `streamlink --json URL`
in addition to the already supported output when selecting a stream via
`streamlink --stream-url URL STREAM` / `streamlink --json URL STREAM`
This is primarily helpful for HLS streams with a variant playlist.
----
Things to note:
- This ignores cases where a plugin yields streams from different sources. Only the last stream in the returned `dict/OrderedDict` gets used, which is usually `best` or `best-unfiltered`. `--stream-types` can still be used though for filtering out unwanted stream types.
- I didn't add the manifest/master URL to the HLSStream's string representation and own JSON output, as it'd spam the output by a lot. Maybe it should be …

cli: add support for stream manifest URL output

---

.github/workflows/main.yml
script/makeinstaller.sh

- Install fixed pynsist pre-release version from git. This is necessary
when trying to install wheels with an included Python ABI tag in their
file name, as the tag naming scheme has been changed in Python 3.8.0.
- Bump the installer's Python version to 3.9.0
- Bump pycryptodome dependency to 3.9.9
takluyver/pynsist#210
Yes, I know that we've just switched back to downloading pynsist from PyPI instead of a specific commit from the git repo, but I don't want to wait until its next release, even though the maintainer said he intends to publish the next one this weekend. If he indeed does, we can switch back to installing the latest version from PyPI. At least the issue of the old Python version in the Windows installer is resolved for now.

installer: upgrade to Python 3.9.0

---

.github/workflows/main.yml

2.6 has just been released, so we don't need to install a pre-release
version with the necessary bugfixes from git anymore.
- #3319
- https://pypi.org/project/pynsist/#history

installer: switch back to latest pynsist release

---

docs/install.rst

See #3323, #3330
Linking to certain sections of the document unfortunately requires adding custom references.
A better solution would be adding the `sphinx.ext.autosectionlabel` Sphinx extension to the docs config, but this requires fixing some headers in other sections first, because it doesn't allow duplicate header names (which is stupid).

docs: add note about supported Windows versions

---

src/streamlink/plugins/nrk.py
tests/plugins/test_nrk.py

The TV and radio sites of nrk.no has been changed some time ago which
has left the NRK plugin broken. This change makes use of [PSAPI] to
bring both TV and radio back to working state, for both live and
on-demand shows.
[PSAPI]: https://psapi-we.nrk.no/documentation/

plugins.nrk: fix/rewrite plugin

---

docs/plugin_matrix.rst
src/streamlink/plugins/huya.py
tests/plugins/test_huya.py

Not every mirror works good for every user location,
the users must select the mirror which works for them.
```
$ streamlink https://www.huya.com/kpl -l info
[cli][info] Found matching plugin huya for URL https://www.huya.com/kpl
[cli][info] Available streams: source_al13, source_al (worst), source_tx, source_bd, source_tx15 (best)
[cli][info] Opening stream: source_tx15 (http)
```
closes https://github.com/streamlink/streamlink/issues/3317

plugins.huya: use FLV stream with multiple mirrors

---

docs/_applications.rst
docs/api.rst
docs/api_guide.rst
docs/cli.rst
docs/conf.py
docs/index.rst
docs/install.rst
docs/issues.rst
docs/players.rst
docs/plugin_matrix.rst

**First commit:**
- adds `autosectionlabel` Sphinx extension, so that headlines don't need to be labelled manually
see https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
- sets `autosectionlabel_prefix_document` to True, so that no duplicates exist
- removes custom headline labels
- fixes all `:ref:` links with properly prefixed references
**Second commit:**
- replaces all `http://` links with `https://` where possible
Debian repos and Ubuntu PPAs are all non-TLS, so those are the last remaining http links
- sets new/proper links where the site was either outdated, unofficial or offline
- "What are cookies" replaced with Wikipedia HTTP-Cookies page
- MS doesn't document its old Windows command prompt, link should probably be removed, as it's documenting the …

docs: fix links

---

docs/ext_argparse.py
src/streamlink/options.py
src/streamlink/plugins/funimationnow.py
src/streamlink/plugins/pluzz.py
src/streamlink/plugins/rtve.py
src/streamlink/plugins/svtplay.py
src/streamlink/plugins/vimeo.py
src/streamlink/session.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/plugins/test_funimationnow.py
tests/test_options.py
tests/test_plugins_meta.py

Closes #3282 
Split into two commits. See the commit messages for the descriptions.
----
Since the argparse docs extension had to be refactored, here's a demonstration of the overall CLI docs changes, to make sure that nothing else changed:
```bash
diff <(curl -s https://streamlink.github.io/latest/cli.html) <(cat ./docs/_build/html/cli.html)
```
```diff
10c10
<   <title>Command-Line Interface &mdash; Streamlink 1.7.0+52.gf0b35b6 documentation</title>
---
>   <title>Command-Line Interface &mdash; Streamlink 1.7.0+54.g49ce436 documentation</title>
31c31
<     <link rel="top" title="Streamlink 1.7.0+52.gf0b35b6 documentation" href="index.html"/>
---
>     <link rel="top" title="Streamlink 1.7.0+54.g49ce436 documentation" href="index.html"/>
56c56
<   <span …
```

plugins: turn mux-subtitles into a global argument

---

src/streamlink_cli/argparser.py

Fixed URL pointing to list of mpv format codes

docs: fix mpv property-list link in --title description

---

src/streamlink/plugins/twitch.py

As mentioned in #3210, the `player_type` access token request parameter workaround stopped working and it's pointless to keep (the cycle continues).
Added in #3301.

plugins.twitch: remove player_type parameter

---

src/streamlink/plugins/twitch.py

Resolves #3341
Twitch's old private API namespace `/api` has already been deprecated and replaced by their new private GraphQL API when they redesigned their website several years ago. The only exception until yesterday were the access_token requests, which have now fully migrated after a couple of weeks of testing from what it looked like.
Since it is unknown how long the old API namespace will stay available, we'll have to move the access_token request at some point.
This commit switches the access_token API request to the GQL API and uses the `PlaybackAccessToken` query with the persistedQuery sha256 hash of `0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712`. This is the checksum of the actual GraphQL query for server-caching purposes and for Streamlink, this simply …

plugins.twitch: move access_token request to GQL

---

src/streamlink/plugins/youtube.py
src/streamlink/stream/hls.py

This removes old compat parameters from `HLSStream.parse_variant_playlist`.
Looks like the old params were only used in the youtube plugin.
Still a breaking change for all applications using Streamlink's API.

chore: remove HLS variant playlist compat params

---

src/streamlink/session.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

and remove compat key name translations in the Session options.
Removes the following CLI arguments:
- `--rtmpdump-proxy` (use `--rtmp-proxy` instead)
- `-c` / `--cmdline` (use `--subprocess-cmdline` instead)
- `-e` / `--errorlog` (use `--subprocess-errorlog` instead)
- `--erorlog-path` (use `--subprocess-errorlog-path` instead)
Keeps `--rtmpdump` as a fallback for `--rtmp-rtmpdump`, as the default
streamlinkrc config file of the Windows installer is still using the
old parameter name.
----
https://github.com/streamlink/streamlink/issues/3235#issuecomment-730251337

chore: remove old rtmpdump/subprocess CLI args

---

win32/streamlinkrc

As mentioned in #3349, the streamlinkrc config file still sets the old `--rtmpdump` argument which needs to be changed.
This PR also rewrites most of the rather poor descriptions and adds a couple of things.
Further suggestions/improvements are welcome...

installer: fix + rewrite streamlinkrc config file

---

src/streamlink/stream/ffmpegmux.py

Fixes #3357 
See https://github.com/streamlink/streamlink/issues/3357#issuecomment-731819072
No tests, because the entire module is not tested yet and I didn't feel like writing a test just for checking whether close can be called twice or not.

stream.ffmpegmux: only close FFMPEGMuxer once

---

docs/plugin_matrix.rst
src/streamlink/plugins/pluto.py
tests/plugins/test_pluto.py

https://pluto.tv/live-tv/
- Livestreams will break during commercials without the `self.session.set_option('ffmpeg-fout', 'mpegts')` option enabled.
- VODs might work without it, but I did not test it.
closes https://github.com/streamlink/streamlink/issues/854
closes https://github.com/streamlink/streamlink/pull/2747
closes https://github.com/streamlink/streamlink/issues/3156
Co-authored-by: calculon-jr <54852718+calculon-jr@users.noreply.github.com>

plugins.pluto: new plugin for https://pluto.tv/

---

src/streamlink/plugins/nicolive.py

https://docs.python.org/3/library/logging.html#logging.Logger.warning

chore: fix deprecated logging.Logger.warn calls

---

src/streamlink/plugins/youtube.py

before
```
$ streamlink https://www.youtube.com/user/deutschewelleenglish/live -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/deutschewelleenglish/live
error: Could not find a video on this page
```
after
```
$ streamlink https://www.youtube.com/user/deutschewelleenglish/live worst -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/deutschewelleenglish/live
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 144p (hls)
```

plugins.youtube: quickfix for "/live" URL

---

docs/cli.rst

- move plugin-sideloading section up (under the plugin-config section)
- two blank lines for 2nd layer headlines, one for 3rd layer headlines
- fix (most) punctuation and grammar errors
- fix outdated description in proxy-support section

docs: fix CLI page

---

docs/_themes/sphinx_rtd_theme_violet/static/css/theme.css
docs/ext_argparse.py

instead of separating them with a comma, so that it adds anchors to
secondary arguments. The rendered manpage already splits arguments into
multiple rows if there are multiple arguments for a specific command.
Fix CSS of the rtd_theme_violet theme and hide empty argument values.

docs: split CLI args in HTML output into rows

---

src/streamlink/session.py
src/streamlink/utils/__init__.py
tests/plugins/testplugin_invalid.py
tests/plugins/testplugin_missing.py
tests/plugins/testplugin_override.py
tests/test_plugins.py
tests/test_session.py

Refactor `utils.load_module`:
- move it to the top and add it to `__all__`
- move imports and loader_details to the global scope
Refactor `session`:
- replace plugin imports via `imp` with `utils.load_module`
- fix incorrect plugin module names
"streamlink.plugin.{name}" -> "streamlink.plugins.{name}"
- use `log.exception()` to print plugin load failures
- remove unused `print_small_exception`
Add / fix tests:
- remove session dependency from test_plugins
- add proper assertions for plugin modules, methods and their signatures
- add tests for invalid and for overridden plugins
----
Based on the changes of #2570
**Things to note**
- I've decided to keep the implementation of `importlib.machinery.FileFinder` in the `utils` module and use that for loading the plugins, as I had some issues …

session: replace usage of deprecated imp module

---

docs/cli.rst

This documents the change introduced by #3366 in regards to broken/faulty plugins that get sideloaded

docs: add warning to plugin sideloading section

---

.github/ISSUE_TEMPLATE/config.yml

Closes #3171 
This adds three links to the issue template chooser:
1. Help -> discussions forum
2. Documentation
3. Gitter 
Not sure if everyone will be happy with this. If not, please make a suggestion. I've tried to put the important stuff first and keep it as short as possible.
I've also pushed the PR branch onto the master branch of my streamlink-test repo, so you can see what it looks like:
https://github.com/bastimeyer-test/streamlink-test/issues/new/choose
----
Btw, I think the default "Ideas" and "Show and tell" categories can be deleted from the discussions. "Ideas" are feature requests anyway and "Show and tell" can be posted into "General".

chore: add issue template config with more links

---

src/streamlink_cli/output.py
tests/test_cli_playerout.py
tests/test_cmdline_title.py

Replace MPV's `--title` parameter with `--force-media-title`, as it also
changes the name of the playlist item and not just the window title.
----
See https://github.com/streamlink/streamlink/issues/3231#issuecomment-741636677
Also changed the content of some test assertions in one go, as they were not testing the entire player argument logic (`subprocess.list2cmdline` on Windows).

cli.output: replace MPV player title parameter

---

src/streamlink/plugins/radiko.py
tests/plugins/test_radiko.py

1. modify url regexp to support 'https'.
2. timefree m3u8 default url had been modified.
test url success:
https://radiko.jp/#!/ts/QRR/20201205210000 
https://radiko.jp/#!/ts/YFM/20201206010000

plugins: fix radiko.py url

---

src/streamlink/stream/dash.py
tests/resources/dash/test_10.mpd
tests/streams/test_dash.py
tests/streams/test_dash_parser.py

- create a list of stream_names and rename streams with the same resolution
- `defaultdict` seems the easy way without changing a lot of tests
- added `test_10.mpd`, so we have an actual test file for future updates
closes https://github.com/streamlink/streamlink/issues/3365

stream.dash: allow '_alt' streams with the same resolution

---

src/streamlink/plugins/afreeca.py

- use broadcast number for _get_channel_info
- use FilteredHLSStream instead of --hls-segment-ignore-names
- save cookies for a user session
- add new option --afreeca-purge-credentials
- general plugin cleanup
closes https://github.com/streamlink/streamlink/issues/3407

plugins.afreeca: update '_get_channel_info' with 'bno', plugin cleanup

---

src/streamlink/plugin/plugin.py

since https://github.com/streamlink/streamlink/pull/3366
https://github.com/streamlink/streamlink/blob/5e7a04b006d0e4d7a884b13bf2aa8047791b837b/src/streamlink/session.py#L412
the logger is `[plugins.afreeca]` which was `[plugin.afreeca]` before
update the cls.logger so it will be `[plugins.afreeca]` also
after this PR
```
[plugins.afreeca][debug] Restored cookies: ...
...
[plugins.afreeca][debug] Attempting to authenticate using cached cookies
```

plugins.plugin: use the same cls.logger 'plugins'

---

src/streamlink/plugins/facebook.py
src/streamlink/session.py
src/streamlink/stream/ffmpegmux.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/streams/test_ffmpegmux.py

- don't use `-start_at_zero` as default for `-copyts`
- revert https://github.com/streamlink/streamlink/pull/2559
- change command `--ffmpeg-no-start-at-zero` to `--ffmpeg-start-at-zero`
(there was no release in between this command)
- use `--ffmpeg-start-at-zero` for the facebook plugin,
because the original fix was for it.
https://github.com/streamlink/streamlink/issues/2488
---
as this might have some downsides
Might be helpful for https://github.com/streamlink/streamlink/pull/3404

stream.ffmpegmux: disable -start_at_zero for -copyts as default

---

src/streamlink/session.py
src/streamlink/stream/ffmpegmux.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/streams/test_ffmpegmux.py

`hls-multi` streams occasionally have an input offset between the audio and video streams and the sound is then out of sync. With `copyts`, the offset is not changed when outputting to the player so that the sound is in sync.

add ffmpeg-copyts option

---

src/streamlink_cli/argparser.py

`--stream-url` is currently listed in the "Stream transport options" args group, which doesn't make sense, as it's CLI output related, and not stream transport related. This PR moves it to the "stream" args group, right under `--url` and `--default-stream`.
See the current latest CLI docs:
https://streamlink.github.io/latest/cli.html#cmdoption-stream-url

cli: move --stream-url to different args group

---

src/streamlink/cache.py
tests/test_cache.py

This catches the `OverflowError` that's raised in `streamlink.cache.set` when unsupported timestamps are passed to `time.mktime()` and it sets `expires` to `0` in that case. Also some other minor improvements to the module.
Before merging, I'd first like to see a confirmation that this does indeed fix #3396 (can't test the plugin), because I think another plugin fix might be necessary if the expiration time is set to 0 on auth, as the cache module will clear the credentials immediately.

cache: catch OverflowError in set()

---

src/streamlink/plugins/nicolive.py

`--niconico-timeshift-offset` allows the nicolive Streamlink plugin to start at a particular timestamp in the HLS stream for [timeshift streams](http://help.nicovideo.jp/live_en/2013/06/305what-is-a-timeshiftwatch-period.html).
This proves particularly useful because some broadcasts' HLS streams start with a long "waiting room" during a live broadcast that the web player skips past by default.

add --niconico-timeshift-offset option to the nicolive plugin

---

docs/plugin_matrix.rst
src/streamlink/plugins/dogan.py
tests/plugins/test_dogan.py

- update/add schemas for new/old API responses
- update for dreamturk.com.tr and dreamtv.com.tr API path
- remove dreamtv.com.tr/canli-yayin (no live and redirect loop on old URL)
- add VOD support for cnnturk.com
- add /dream-turk-ozel/.* and /programlar/.* VOD paths for dreamturk.com.tr
- add /dream-turk-ozel/.* VOD path for dreamtv.com.tr
- add /diziler/.* and /embed/.* VOD paths for teve2.com.tr
- update URLs in plugin test
- update plugin matrix
~~No accounts needed, but streams are geo-restricted to Turkey.~~
closes  #3416

plugins.dogan: fix/update

---

src/streamlink/plugins/youtube.py

```
$ streamlink http://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw worst -l info
[cli][info] Found matching plugin youtube for URL http://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
```
```
$ streamlink https://www.youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w worst -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
```
closes https://github.com/streamlink/streamlink/issues/3426

plugins.youtube: Fix 'ytInitialData' for channel pages

---

src/streamlink_cli/main.py

closes https://github.com/streamlink/streamlink/issues/2622
use `127.0.0.1` for local `create_http_server()`
use `0.0.0.0` for external `create_http_server()`
`--player-http` = ***127.0.0.1***
https://streamlink.github.io/cli.html#cmdoption-player-http
`--player-continuous-http` = ***127.0.0.1***
https://streamlink.github.io/cli.html#cmdoption-player-continuous-http
`--player-external-http` = ***None*** / ***0.0.0.0***
https://streamlink.github.io/cli.html#cmdoption-player-external-http
---
we use `AF_INET` which is IPv4
https://github.com/streamlink/streamlink/blob/2.0.0/src/streamlink_cli/utils/http_server.py#L24
we don't use `AF_INET6` which is IPv6, so IPv6 support is unimportant.
Ref https://github.com/streamlink/streamlink/issues/2622#issuecomment-529408813
---
```
$ streamlink …
```

cli.main: use *_args, **_kwargs for create_http_server

---

CODE_OF_CONDUCT.md

Personally, I'm not a fan of Code of Conducts, as it's totally unnecessary to tell adults how to behave themselves :roll_eyes: :roll_eyes: :roll_eyes:, but unfortunately it's a requirement for being able to apply to the Netlify open source plan upgrade (see #3420).
That's why I'm proposing the "Minimalist Code of Conduct", which basically only tells the already implied and known rules of every community, "be nice and respectful", nothing more.
An alternative to the "Minimalist Code of Conduct" could be the "No Code of Conduct":
https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md
Either way, I don't think there's any reason to fight or argue about adding a CoC of such kind. It doesn't change anything here, so if one doesn't like this, they can just ignore it.

docs: add minimalist code of conduct

---

src/streamlink/plugins/nicolive.py

Some videos requiring login on Nicolive for the full video have a free section at the start. Without this fix, even if login credentials are provided, login may not be attempted since get_wss_api_url() will succeed, but once the 'locked section' is reached, it will download a blank 'error' screen (which is what you get if you attempt to view the locked section without logging in):
This fix will attempt an initial login to fix this issue.

plugins.Nicolive: login before getting wss api url

---

src/streamlink/plugins/afreeca.py
src/streamlink/plugins/filmon.py
src/streamlink/plugins/showroom.py
src/streamlink/plugins/twitch.py
src/streamlink/stream/hls.py
tests/mixins/stream_hls.py
tests/plugins/test_twitch.py
tests/streams/test_hls_filtered.py

Fixes #3451 
Changes are split into two commits:
1. Replace static reference to the `HLSStreamReader` in `HLSStream.open()`
2. Fix HLS writer race conditions (see commit message)
This explicitly awaits all writer calls in filtered HLS tests, like the Twitch HLS tests for example.
I've been running all HLS tests in a loop for almost an hour now without any failures, so I think this should be good.
```bash
while pytest -q tests/plugins/test_twitch.py tests/streams/test_hls.py tests/streams/test_hls_filtered.py; do true; done
```

Fix race conditions in filtered HLSStreamWriter tests

---

src/streamlink/plugins/twitch.py

**master**
```
$ streamlink -l debug twitch.tv/xrdtcfyvghutyfcvgyh best
[cli][debug] OS:         Linux-5.10.3-1-git-x86_64-with-glibc2.32
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0+9.g009bbd8
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/xrdtcfyvghutyfcvgyh
[plugins.twitch][debug] Getting live HLS streams for xrdtcfyvghutyfcvgyh
error: Unable to validate JSON: Unable to validate key 'data': Unable to validate key 'streamPlaybackAccessToken': Type of None should be 'dict' but is 'NoneType' or Key 'videoPlaybackAccessToken' not found in {'streamPlaybackAccessToken': None}
```
**fix**
```
$ streamlink -l debug twitch.tv/xrdtcfyvghutyfcvgyh best
[cli][debug] OS: …
```

plugins.twitch: fix access_token on invalid inputs

---

.editorconfig
netlify.toml

As discussed in https://github.com/streamlink/streamlink/pull/3335#issuecomment-742131264, here's a config for docs previews in PRs via netlify.com. This will make reviewing docs changes way more easy.
This config will be required before enabling the repo integration, otherwise it'd create production builds on pushes to the master branch, which is not what we want. I've added comments to the config, so that it's clear what everything's for.
----
So far, I haven't received a response from them yet regarding the upgrade to their "open source" plan. If they are so kind and update the account from the free "starter" plan, that would enable us having multiple account maintainers and an increased build time (which doesn't matter so much).
Since I feel like they probably won't answer my message, …

ci: add netlify docs preview deploy config

---

docs/index.rst

As mentioned in #3420, a link to netlify.com on the index page is required for being able to apply to their "open source" plan, which enables us having multiple maintainer accounts. The other benefits of this plan-upgrade are not really relevant to us.
https://www.netlify.com/legal/open-source-policy/
If there's more to add here or if you think that this should be reworded, please post a suggestion.

docs: add thank-you section to index page

---

.github/workflows/main.yml
setup.py

Resolves #1753 
This adds the man page, if it exists, to wheels via the `data_files` keyword:
https://setuptools.readthedocs.io/en/latest/references/keywords.html
The `data_files` keyword is marked as deprecated, but there doesn't seem to be another way of mapping files from one path to another in the distribution file. What it says about not being supported by wheels is wrong. `package_data` doesn't seem to work here without changing build scripts. At least I wasn't able to make it work.
`sdist` does not include any `data_files`.
Regarding the manpages themselves, it might be necessary on some systems to extend the `MANPATH` env var with `MANPATH="${XDG_DATA_HOME:-$HOME/.local/share}/man:$MANPATH"` so that it looks up man pages in `$XDG_DATA_HOME/man` (which defaults to …

build: include man page in wheels

---

docs-requirements.txt

No big changes here.
https://github.com/pradyunsg/furo/blob/2020.12.28.beta23/docs/changelog.md
I'm just using this one to test the netlify integration, as it changes the `docs-requirements.txt` file which should trigger a docs preview build.

docs: bump furo docs req to 2020.12.28.beta23

---

src/streamlink/plugins/bfmtv.py

[RmcStory](https://rmcstory.bfmtv.com/mediaplayer-direct/) and RmcDecouverte were not working for me.
Looks like it is coming for this modification : https://github.com/streamlink/streamlink/pull/3290
I just added back the second regex for getting the brightcove player id.

plugins.bfmtv : fix rmcstory and rmcdecouverte

---

src/streamlink/plugins/facebook.py

```
$ streamlink https://www.facebook.com/FranceRugby/posts/3017597365007921
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/FranceRugby/posts/3017597365007921
[plugins.facebook][error] Video is not available, You must log in to continue.
error: No playable streams found on this URL: https://www.facebook.com/FranceRugby/posts/3017597365007921
```
closes https://github.com/streamlink/streamlink/issues/3480

plugins.facebook: Add 'Log into Facebook' error message.

---

docs/install.rst

- only document user-base installs via `--user` and don't mention
system-wide installs
- turn user-base note into a warning for better visibility
- remove git+setuptools example
- add example for installing specific tag/branch/commit
- update links

docs: improve install-via-pip section

---

src/streamlink_cli/argparser.py

as well as `--ffmpeg-{audio,video}-transcode`
The current description implies that this CLI argument remuxes the output, which is not the case. See https://github.com/streamlink/streamlink/issues/791#issuecomment-762567588

docs: fix description of `--ffmpeg-fout`

---

MANIFEST.in

Resolves #3507 
This adds the man page to the sdist tarballs by white-listing the man page build path. It can be found here now:
`docs/_build/man/streamlink.1`
Due to the white-listing, the man page gets included twice (same path though), first by the `recursive-include docs *` pattern in the manifest, and second by the `data_files` field in `setup.py` (which was added by #3459 for the `bdist` target).
I would have preferred having the man page in the tarball's root directory or in `share/man/man.1/`, like the wheels, but that would have required copying the file via `script/build-and-sign.sh` first and deleting it again afterwards. Unfortunately, the `data_files` field which moves the man page to `share/man/man.1/` in the wheels doesn't work with distutil's `sdist` command, and it simply …

build: include man page in sdist tarballs

---

src/streamlink/utils/l10n.py
tests/test_localization.py

Fixes #3517
1. Replaces pycountry's generic `languages.lookup` call with several `languages.get(attr=language)` calls, where `attr` is `alpha_2`, `alpha_3`, `bibliographic` and `name`, in this order. Other attributes are probably not relevant for Streamlink. `.get` calls don't raise and just return `None` if the lookup fails. The order of attribute lookups prevents issue #3057, where `language.lookup("en")` would return the "En" language instead of "English".
2. To prevent the `AttributeError` from being raised when certain optional language attributes are missing, like `alpha_2` for example, those will be read via `getattr` with an empty string as fallback (instead of `None`), which matches the data representation of `iso639`. `alpha_3` and `name` attributes always exist.
```bash
curl …
```

utils/l10n: fix langs without alpha_2 in pycountry

---

src/streamlink/plugins/twitcasting.py

Add a `--twitcasting-password` option to the TwitCasting plugin, supporting private (password-protected) TwitCasting streams.
closes #3504
If the command line option is used, then we append `&word={md5_encrypted_password}` to `real_stream_url`.
You can easily start a livestream from Twitcasting by hovering the blue "Broadcast" button at the top right of the site then clicking "Web broadcasting". Scroll down to set a password then back up to start an audio-only livestream. If you do not have an account, you can quickly login with a Twitter or Facebook account if you have one.
This is my first ever pull request, in a language I have essentially no experience with. I hope everything is OK.

plugins.twitcasting: add support for private/password-protected streams

---

src/streamlink/plugins/wwenetwork.py
src/streamlink/session.py
src/streamlink/utils/__init__.py
tests/test_session.py

This replaces the custom `memoize` decorator in favor of the native [`functools.lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache) decorator (available since py 3.2).
Since I didn't set `maxsize=None`, this also changes the cache size of each decorated method, which was infinite prior to these changes and is now set to 128 with the LRU algorithm.
Not sure why I had to force-push and explicitly set `maxsize=128` on py `<3.8`, as it's the default there as well:
https://github.com/python/cpython/blob/3.7/Lib/functools.py#L458
https://github.com/python/cpython/blob/3.8/Lib/functools.py#L487

utils: remove custom memoize decorator

---

docs/_man.rst
docs/conf.py

and add synopsis with examples
----
I'd like to embed some sections from the CLI page in the man page, but that would require rewriting the CLI page and making it modular, so that the sections can be included without duplicating them. At least the tutorial does not get included with this PR.
The examples could probably be improved, so if you have suggestions, please tell.
```
$ make --directory=docs clean man
$ man ./docs/_build/man/streamlink.1
```

docs: remove CLI tutorial from man page

---

src/streamlink/session.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/test_session.py

Resolves #3474 
Resolves #2192
Implements `--interface`, `-4`/`--ipv4` and `-6`/`--ipv6`, similar to curl.
**Concerns**
- What I don't like about this implementation is that it overrides the address family resolving in `requests.packages.urllib3.util.connection` globally, as it's not session based. This means that when someone creates two sessions from the API and sets the `ipv4` or `ipv6` option, all other sessions will be affected as well.
- This does only affect HTTP/HTTPS connections. Web sockets for example are currently all managed individually in certain plugins. The implementation of a common WSSession similar to the HTTPSession would fix this.
- Not sure if the "general" arguments group is the correct choice. Technically it could also go into the "transport" arguments group.
---- …

session: implement --interface, --ipv4 and --ipv6

---

docs/install.rst

as it is unmaintained and currently incompatible with Streamlink 2.0.0
----
Since the repo is currently hosted at streamlink/streamlink-portable, what should we do with it? Should this be archived?

docs: remove RosadinTV Windows portable version 

---

.github/workflows/main.yml

Set fetch depth to 300, like all the other CI runners do, and fix the
Codecov upload error/warning:
> Issue detecting commit SHA. Please run actions/checkout with
> fetch-depth > 1 or set to 0
----
https://github.com/streamlink/streamlink/pull/3547/checks?check_run_id=1853586479#step:9:28

ci.github: increase git fetch depth of tests

---

src/streamlink/stream/dash.py
tests/resources/dash/test_11_static.mpd
tests/streams/test_dash.py
tests/streams/test_dash_parser.py

closes https://github.com/streamlink/streamlink/issues/2873
- set `refresh_wait` for static playlists to default 5 seconds
for this example the `refresh_wait` time was set to 204.32 seconds
which would result in some unexpected behavior.
- Fix for not correct closing streamlink process
- Fix for Pipe copy aborted - Read timeout
`--player-no-close` must be used now
https://streamlink.github.io/cli.html#cmdoption-player-no-close
```
$ streamlink https://vimeo.com/176894130 --stream-type dash -o test.mp4 -l debug
[cli][info] Found matching plugin vimeo for URL https://vimeo.com/176894130
[stream.dash][debug] Opening DASH reader for: video-574992937 (video/mp4)
[stream.dash][debug] Opening DASH reader for: audio-574992933 (audio/mp4)
[stream.dash_manifest][debug] Generating segment timeline …
```

stream.dash: Fix static playlist - refresh_wait - Pipe copy aborted - Read timeout

---

tests/resources/__init__.py
tests/test_api_http_session.py
tests/test_buffer.py
tests/test_cmdline_title.py
tests/test_localization.py
tests/test_plugin_utils.py

- properly rewrite TestPluginAPIHTTPSession.test_read_timeout
- remove Python 2 compat code from TestBuffer.test_reuse_input
- add category variable to simple player --title tests and merge them
- ignore ImportError exceptions from code coverage
- remove unnecessary branch in unsupported_versions_1979
- annotate dead branches in tests/resources and remove unused mock_http
Current tests coverage on master (6646c72) is 99.62%:
https://codecov.io/gh/streamlink/streamlink/tree/6646c72/tests
This raises it to 100%:
https://app.codecov.io/gh/streamlink/streamlink/compare/3547/tree/tests
And also improves this:
https://app.codecov.io/gh/streamlink/streamlink/compare/3547/changes
----
Since this pushes the coverage of the tests to 100%, the threshold in the codecov config could be removed and a …

tests: fix test code coverage

---

docs/install.rst

The install instructions for Debian stable are not exactly accurate, `-t buster-backports` needs to be added else apt will try to use the Debian stable package instead (which is older).

docs: update Debian stable install instructions

---

src/streamlink/plugins/vtvgo.py

Fixes #3558
- add schemas for params and stream_url
- find first script tag via itertags which includes `setplayer(`
- validate params via schema
```
$ streamlink -l trace https://vtvgo.vn/xem-truc-tuyen-kenh-vtv1-1.html
[15:52:13.032591][cli][debug] OS:         Linux-5.11.0-rc6-2-git-x86_64-with-glibc2.33
[15:52:13.032737][cli][debug] Python:     3.9.1
[15:52:13.032774][cli][debug] Streamlink: 2.0.0+45.g4f98eed
[15:52:13.032805][cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[15:52:13.032868][cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv1-1.html
[15:52:14.803509][plugins.vtvgo][trace] [('id', '1'), ('type_id', '1'), ('time', '1613055134'), ('token', '1613055134.591a084a6b190783781ae8232e365350')] …
```

plugins.vtvgo: ignore duplicate params

---

.codecov.yml

The "patch" status which was added by fba55ae also accidentally added
annotations. These are annoying when lots of new and uncovered lines get
added, and it makes reading and reviewing the PR diff unnecessarily
difficult. We are only interested in the "patch" status check itself.
https://docs.codecov.io/docs/github-checks-beta

ci.codecov: disable GH status check annotations

---

.github/ISSUE_TEMPLATE/0_use_the_issue_template.md
.github/ISSUE_TEMPLATE/1_plugin_issue.md
.github/ISSUE_TEMPLATE/1_plugin_request.md
.github/ISSUE_TEMPLATE/2_bug_report.md
.github/ISSUE_TEMPLATE/3_feature_request.md
.github/issue_template.md

- add template for showing the "use the templates" note at the top
- reorder templates by prepending numbers to the file names
- add data for title templates and automatic labels (where applicable)
- make templates more consistent and add more descriptions
- improve debug log comments
- remove "expected/actual behavior" from feature request template
----
The main motivation behind this PR is that the issue templates are currently not that well ordered in the [new issue list](https://github.com/streamlink/streamlink/issues/new/choose) and their descriptions are rather useless. This leads to confusion and thus misuse of the templates.
I've also added a template with the "CHOOSE ONE OF THE ISSUE TEMPLATES" title (similar to the [mpv-player/mpv …

chore: reorder and improve issue templates

---

docs/developing.rst
script/update-removed-plugins.sh
src/streamlink/plugins/.removed
tests/test_plugins_meta.py

- add shell script for updating the removed plugins list from the git
history of deleted and renamed plugin files, compared with the current
list of plugins
- test that the removed plugins list does not include any active plugins
- update removing plugins section in developing docs
----
Resolves #3291 
See #2003
The new removed plugin entries come from here:
- `arconia` 3973bb9 (renamed)
- `atv` cad43f9 (renamed)
- `bnt` 8a66ee7 (renamed)
- `dplay` 2eb54a3 (deleted)
- `googledocs` 7eee543 (renamed)
- `kralmuzik` cad43f9 (deleted)
- `showtv` cad43f9 (renamed)
- `toya` 40e2bb0 (deleted)

plugins: fix and update removed plugins list

---

docs/install.rst

Resolves #3572 
Resolves #669 
Closes #3522
----
I've just moved my streamlink-appimage repo to streamlink/streamlink-appimage and pushed the `2.0.0-1` release:
- https://github.com/streamlink/streamlink-appimage
- https://github.com/streamlink/streamlink-appimage/releases
See #3572 for all the additional infos about the appimage.

docs: add appimages section to install docs

---

netlify.toml

#3620 doesn't have a docs preview because CHANGELOG.md changes are not whitelisted

ci.netlify: build docs when CHANGELOG.md changes

---

docs/install.rst

This makes it consistent with the macOS packages list, as pip is already
listed there, and it also highlights the install option on other OSes.
Special native install options are listed first, then pip, then native
packages with their install commands and further links.
----
https://github.com/streamlink/streamlink/pull/3611#issuecomment-792522236

docs: add pip to packages lists

---

src/streamlink/plugins/abematv.py

Fixed a bug where some free videos (like this:https://abema.tv/video/episode/199-12_s0_p1) were determined to be premium exclusive and could not be downloaded.
*onDemandType list
1: premium only
2: rental only
3: free
*This is a modified version of the previously released pull request(https://github.com/streamlink/streamlink/pull/3616).

plugins.abematv: Fixed download problem.

---

src/streamlink_cli/output.py
tests/test_cmdline_player_fifo.py

Fixes #3568
Originally I had intended to refactor the NamedPipe class and a little bit of the PlayerOutput class as well, but I ran into some other issues which I haven't resolved yet, so here's a simple fix for #3568. I could refactor NamedPipe and keep the same logic as it is right now, but it's not really worth it. A proper implementation will require a complete rewrite of the PlayerOutput as well, and that's a bit much now.
Also, as mentioned in #3568, the named pipe currently doesn't get cleaned up properly if the player fails to start, which I also wanted to fix with my code refactoring.

cli.output: fix named pipe player input on Windows

---

src/streamlink/plugins/zattoo.py

'hls' was removed and can't be used anymore,
'hls5', 'hls7' or 'dash' is only available
closes https://github.com/streamlink/streamlink/issues/3553

plugins.zattoo: use 'dash' as default stream

---

docs/install.rst
setup.py
src/streamlink/plugins/nicolive.py

```
setup.py: require websocket-client>=0.58.0
Make sure all User use the same version where `callback(self, *args)` was changed.
```
```
plugins.nicolive: fixed websocket-client 
```
closes https://github.com/streamlink/streamlink/issues/3631
closes https://github.com/streamlink/streamlink/issues/3633

plugins.nicolive: fixed websocket-client and use websocket-client>=0.58.0

---

src/streamlink_cli/main.py
tests/plugin/testplugin.py
tests/test_cli_main.py

We've had this discussion a while ago and I think we should log all arguments set by the user while debug logging, not just plugin specific arguments.
- The first commit therefore replaces the "Plugin specific arguments" logging with the new `streamlink_cli.main.log_current_arguments` method which logs all arguments set by the user, on the command line, from the main config file, from the plugin config file and from any custom config files. Sensitive plugin argument values get replaced (just like previously) and it prints double-dash argument names instead of the argument's `dest` name, if possible.
- The second commit additionally cleans up `streamlink_cli.main.log_current_versions` and adds tests, for good measure.
----
Example with a mixture of CLI arguments, main-config arguments and …

cli: debug-log arguments set by the user

---

script/build-and-sign.sh

This removes the `-q` option from the sdist/bdist build commands, so that all files are printed to stdout in the build log.
https://github.com/streamlink/streamlink/runs/2171755471?check_suite_focus=true#step:9:11

build: don't build sdist/bdist quietly

---

MANIFEST.in

Fixes #3643 
For some reason, the `src/streamlink/plugins/.removed` file is not part of the sdist tarball in `2.1.0`.
This PR forces the inclusion of that file via `MANIFEST.in`.
I don't know why, but when I build `2.1.0` locally, the file is part of the tarball, but the one built by the CI runner does not include it. Can someone confirm this?

build: include removed plugins file in sdist

---

src/streamlink/plugins/youtube.py
tests/plugins/test_youtube.py

Resolves #3676 
```
$ streamlink -l debug https://youtu.be/SebJIjQgdjg
[cli][debug] OS:         Linux-5.12.0-rc5-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 2.1.1+4.g303c424
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug]  url=https://youtu.be/SebJIjQgdjg
[cli][info] Found matching plugin youtube for URL https://youtu.be/SebJIjQgdjg
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: SebJIjQgdjg
[plugins.youtube][debug] get_video_info - 1: Found data
[plugins.youtube][debug] This video is live.
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
```

plugins.youtube: add short video URLs

---

src/streamlink/plugins/abematv.py

I found a new response from api of abema from [https://api.abema.io/v1/video/programs/203-2_s1_p113](https://github.com/streamlink/streamlink/files/6226501/203-2_s1_p113.txt)
The previous response contained only one "terms", but we found a new response with two "terms", so we fixed it.
> Known Response
> {~,"terms":[{"onDemandType":3,"endAt":＊＊＊}]}
> New Response
> {~,"terms":[{"onDemandType":3,"endAt":＊＊＊},{"onDemandType":1,"endAt":＊＊＊}]}

plugins.abematv: Fixed download problem again.

---

.github/ISSUE_TEMPLATE/1_plugin_issue.md
.github/ISSUE_TEMPLATE/1_plugin_request.md
.github/ISSUE_TEMPLATE/2_bug_report.md
.github/ISSUE_TEMPLATE/3_feature_request.md

My intention with the issue title templates was having a common format for all the issues which get set automatically, but that's a bit difficult to achieve when there are parts which are supposed to be edited by the user and some not. Square brackets seemed like a good idea, but apparently people don't understand that they should be removed when filling out the template. Using all-uppercase text for the parts that should be replaced is also not ideal as there's also room for misinterpretation. So here's a slightly better version, which will probably still get misinterpreted...

chore: remove square brackets from issue titles

---

src/streamlink/stream/ffmpegmux.py
src/streamlink/utils/named_pipe.py
src/streamlink_cli/main.py
src/streamlink_cli/output.py
tests/test_utils_named_pipe.py

- split into two classes with an abstract base class
- remove name parameter from class and generate proper names
- remove mode parameter from open() as it's always binary mode
- change type of NamedPipe.path from str to pathlib.Path
- add tests
This is just a code refactor and doesn't fix the other issues mentioned here, as it would require refactoring the cli.output classes and stream.ffmpegmux in addition to the current changes:
https://github.com/streamlink/streamlink/issues/3568#issuecomment-783130671
There are also a couple of other issues I found while rewriting the Windows specific stuff and it seems like it doesn't close the named pipe gracefully and instead just swallows/supresses errors on the last (invalid) write attempt. I couldn't find a solution for this now, hence the lack …

utils.named_pipe: rewrite named pipes

---

docs/install.rst

docs: fix winget package link

---

src/streamlink/plugins/nicolive.py

nico live run failed with error:
#> streamlink --http-proxy=127.0.0.1:8080 -o ./out.ts "https://live.nicovideo.jp/watch/lv********" test
[plugins.nicolive][warning] setsockopt() takes exactly 3 arguments (1 given)
[plugins.nicolive][warning] wss api disconnected.
[plugins.nicolive][warning] Attempting to reconnect in 5 secs...
fix: websocket threading should init with `kwargs`, not `args`.

plugins.nicolive: fix nicolive broken with proxy

---

src/streamlink/plugins/mitele.py

before
```
[cli][info] Available streams: 360p (worst), 480p, 576p, 720p_alt2, 720p_alt, 720p (best)
```
now
```
[cli][info] Available streams: 360p_364k (worst), 480p_764k, 720p_1564k, 720p_2564k, 576p_5008k, 720p_6891k, 720p_9726k (best)
```
closes https://github.com/streamlink/streamlink/issues/3708

plugins.mitele: use '_{bitrate}' and remove duplicates

---

src/streamlink/plugins/bbciplayer.py

This started happening yesterday:
```
error: Unable to parse JSON: Extra data: line 1 column 32793 (char 32792) ('{"navigation":{"items":[{"id":"cha ...)
```
The old greedy regex was also grabbing:
```
;</script><script id="tvip-script-app-client-config">window.__IPLAYER_CLIENT_CONFIG__ = {"logger":{"level":"error","telemetryUrl":"https://monitoring.ede565d7c6c3ee6b.xhst.bbci.co.uk/tvr-telemetry/iplayer-web/telemetry","serviceName":"iplayer-web-app-highlights","telemetrySamplingRate":0}}
```
This fixes it.  Tested on various live channels and VODs.
closes #3726

plugins.bbciplayer: fix/update state_re regex

---

.github/workflows/main.yml

cpython 3.10-beta is already out since almost two weeks, so let's add it to the test runners.
https://www.python.org/downloads/release/python-3100b1/
The `-dev` suffix is an undocumented feature of the setup-python action and an alias for `>= maj.min.0-a0`.

ci.github: add python 3.10-dev to test runners

---

src/streamlink/plugins/youtube.py

Resolves #3724
I have been using streamlink for more than 1 year and recording Youtube live streams. I started to have the same problem as of May 14, 2021. The PR I posted seems to solve the problem.

plugins.youtube: add html5=1 parameter

---

src/streamlink/plugins/rtpplay.py
tests/plugins/test_rtpplay.py

Resolves #3741 
This is the second time this site has obfuscated their HLS URLs so that they can't be parsed easily.
See my comment here: https://github.com/streamlink/streamlink/pull/3627#discussion_r596186958
These changes however are again simple and only require a quick adjustment of the regex and additional base64 decoding in the validation schema.
I've also added tests with mocked HTTP responses, since there are several different response types.
----
**VOD**
```
$ streamlink -l debug 'https://www.rtp.pt/play/p8501/cidade-despida'
[cli][debug] OS:         Linux-5.12.4-2-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.1.2+1.g0cdc1de
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] …
```

plugins.rtpplay: fix obfuscated HLS URL parsing

---

src/streamlink/utils/url.py
tests/test_utils_url.py

Add `safe` and `quote_via` parameters to `update_qsd`, which are
passed to `urllib.parse.urlencode` for encoding the query string
keys and values.

utils.url: add encoding options to update_qsd

---

docs/plugin_matrix.rst
src/streamlink/plugins/mediavitrina.py
src/streamlink/plugins/onetv.py
tests/plugins/test_mediavitrina.py
tests/plugins/test_onetv.py

**plugins.onetv**
- uses **API v1** which is only 1tv.ru
- remove broken VOD support
**plugins.mediavitrina**
- uses **API v2**
closes https://github.com/streamlink/streamlink/issues/3587
closes https://github.com/streamlink/streamlink/pull/3669

plugins.onetv: split plugin

---

docs/conf.py

And fix inconsistent manpage build paths between recent sphinx
releases. False is the currently expected value, as setup.py
will check for a built manpage in `docs/_build/man/streamlink.1`
for inclusion in the release tarballs.
Even though the doc's HTML theme "furo" does currently limit the
used sphinx version to 3.x, this won't stop users building the
manpage using sphinx 4.x, eg. via a global system-package.
----
What a mess...
https://www.sphinx-doc.org/en/master/changes.html
Sphinx 4:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-man_make_section_directory
> **man_make_section_directory**
> If true, make a section directory on build man page. Default is `True`.
>
> *New in version 3.3.*
> *Changed in version 4.0:* The default is changed to False from `True`.
> …

docs: set man_make_section_directory to false

---

tests/mixins/stream_hls.py
tests/streams/test_hls.py

There are currently no tests for custom HTTP session headers. The tests could have instead been added to the overall session tests, but these changes here also assure that headers are set on HLS segments and (custom) HLS segment keys, so basically killing two birds with one stone.
https://github.com/streamlink/streamlink/issues/3754#issuecomment-849503897

tests.hls: test headers on segment+key requests

---

src/streamlink_cli/argparser.py

The `--help` text has been like this since 2437393c922a641229b8f22fc7cf277462f302e1 :worried: 
The package description which uses the same text was fixed in the py2 removal:
https://github.com/streamlink/streamlink/commit/8034b1606388e325916baf9f8ce738915fa6b528#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R69
And the docs were fixed here:
https://github.com/streamlink/streamlink/commit/b4298c8185cad978c2f1bbccbfeb095e30028c05#diff-c2a3f968b7ac8d84c3935f76af3a93c094b3c5c068777c4cd2548789b9a8d417R9

cli.argparser: fix description text

---

docs/ext_argparse.py
src/streamlink/logger.py
src/streamlink_cli/argparser.py
src/streamlink_cli/compat.py
src/streamlink_cli/constants.py
src/streamlink_cli/main.py
tests/test_cli_main.py

1. tests: refactor TestCLIMainLogging
- always exit streamlink_cli.main.main at the same function call, namely
log_current_arguments
- patch out dummy functions in context manager
- slice debug log mock calls due to common test exit function
- properly reset mocks
- rename streamlink_cli.main.check_root to log_root_warning
- add test for streamlink_cli.main.log_root_warning
2. cli: implement --logfile
- refactor streamlink_cli.main.{setup_logging,setup_console}
and split into setup_logger_and_console and setup_signals
- add LOG_DIR to streamlink_cli.constants
- pass filename to logger.basicConfig
- re-use write stream of logger in ConsoleOutput
- fix escaped chars for percent-formatted argparse help strings in docs
- add tests
----
Resolves #2485

cli: implement --logfile

---

src/streamlink/plugin/api/http_session.py
tests/test_api_http_session.py

- call super() instead of referencing parent class by name
- fix incorrect signature of the constructor
- remove startswith check of the default "User-Agent" header
it could be replaced with requests.utils.default_user_agent(), but it's totally unnecessary
- reformat some lines for better readability
- fix tests and add test for custom default attributes/values

plugin.api.http_session: refactor HTTPSession

---

src/streamlink/plugin/api/http_session.py

Resolves #2365 
This *should* resolve #2365, but I can't validate it myself with data of real HLS streams and don't want to spend time writing sophisticated tests for the entire upstream stack where this bug occurs.
See https://github.com/psf/requests/issues/4956#issuecomment-573325001

plugin.api.http_session: enforce_content_length

---

src/streamlink/stream/hls.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py

- replace stream.hls.pkcs7_decode with Crypto.Util.Padding.unpad
- add tests for invalid encryption data
----
This is what I had originally suggested in #3446 but it keeps the garbage data removal.

stream.hls: replace custom PKCS#7 unpad function

---

src/streamlink/plugin/api/validate.py
tests/test_api_validate.py

There are two validation schema patterns which get re-used all the time and which can be improved.
1. **Nested/recursive `validate.get` calls:**
Nested key lookups currently require three separate `get`-transform calls and one `all` call, which is wasteful and tedious to write. Also, since the `get` method sets its default value to `None` and returns it on any `KeyError`/`IndexError`, error messages in consecutive lookups are not particularly useful.
```py
>>> validate(
...     all(get("first"), get("second"), get("third")),
...     {"first": {"second": {"third": "value"}}}
... )
"value"
>>> validate(
...     all(get("invalid"), get("second")),
...     {"first": {"second": "value"}}
... )
ValueError: "'NoneType' object is not subscriptable"
```
Single `get()` calls with nested lookups …

plugin.api.validate: add nested lookups to get() and implement union_get()

---

src/streamlink/plugins/twitch.py
tests/plugins/test_twitch.py

Fixes hosted channel redirection
**master**
```
$ streamlink -l debug twitch.tv/sheevergaming
[cli][debug] OS:         Linux-5.12.9-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.1.2+16.g1ed85fc
[cli][debug] Requests(2.25.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug]  url=twitch.tv/sheevergaming
[cli][info] Found matching plugin twitch for URL twitch.tv/sheevergaming
[plugins.twitch][debug] Getting live HLS streams for sheevergaming
error: No playable streams found on this URL: twitch.tv/sheevergaming
```
**changes**
```
$ streamlink -l debug twitch.tv/sheevergaming
[cli][debug] OS: …
```

plugins.twitch: query hosted channels on GQL

---

docs/cli.rst
src/streamlink/session.py
src/streamlink_cli/compat.py
src/streamlink_cli/constants.py
src/streamlink_cli/main.py
tests/test_cli_main.py

- **Windows**
- `%APPDATA%\streamlink\streamlinkrc`
- **macOS**
- `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/config`
- `${HOME}/.streamlinkrc`
- **Linux/BSD**
- `${HOME}/.streamlinkrc`
- **macOS**
- `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/plugins`
- **Linux/BSD**
- `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/plugins`
----
- **Windows**
`%APPDATA%\streamlink\config`
- **macOS**
`${HOME}/Library/Application Support/streamlink/config`
- **Linux/BSD**
`${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/config` (no changes)
- **Windows**
`%APPDATA%\streamlink\plugins` (no changes)
- **macOS**
`${HOME}/Library/Application Support/streamlink/plugins`
- **Linux/BSD**
`${XDG_DATA_HOME:-${HOME}/.local/share}/streamlink/plugins`

cli: deprecate old config files and plugin dirs

---

src/streamlink/plugins/funimationnow.py

This fixes a common error with the FunimationNow failing due to an inability to handle content with these select subtitle formats attached to them, such as every single show released past the year 2021 that isn't dubbed.
To reproduce this issue, simply run for yourself 
`streamlink --funimation-email="xxx" --funimation-password="xxx" --http-cookie "incap_ses_xxxx_xxxxxx=xxxxxxxxxxxx" "https://www.funimation.com/en/shows/any-simulcast-show-not-listed-dubbed/"`

plugins.funimationnow: fix subtitle language

---

src/streamlink/plugins/youtube.py
tests/plugins/conftest.py
tests/plugins/test_youtube.py

- translate embedded live-channel URLs to avoid unnecessary HTTP
redirections and having to find the canonical URL in the metadata
- add URL translation tests
- fix plugins can_handle_url pytest collection function
----
In regards to https://github.com/streamlink/streamlink/pull/3797#issuecomment-864449988, channel URLs like `youtube.com/CHANNELNAME` or `youtube.com/channel/CHANNELID` **could** be translated to `youtube.com/CHANNELNAME/live` or `youtube.com/channel/CHANNELID/live` respectively, but that would also require a change of the logic when the embedded data is missing, eg. when a channel is not live, and it'd have to always raise a `NoStreamsError` instead of a `PluginError` for a more graceful error message, which would be misleading in some cases.

plugins.youtube: translate embed_live URLs

---

src/streamlink/plugins/mediaklikk.py
tests/plugins/test_mediaklikk.py

Closes #3824
This rewrites the plugin with proper data extraction and validation schemas, and adds support for these sites, including VODs:
- Mediaklikk.hu
- M4sport.hu
- Hirado.hu
- Petofilive.hu
https://dunamsz.hu
https://en.wikipedia.org/wiki/MTVA_(Hungary)#Internet
The sports channels are geo-locked, but it should find the correct HLS streams on all URLs listed in the tests nevertheless.

plugins.mediaklikk: rewrite plugin

---

src/streamlink/stream/hls.py
src/streamlink/stream/hls_playlist.py
src/streamlink/stream/segmented.py
src/streamlink/utils/__init__.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py
tests/streams/test_hls_playlist.py

Resolves #3328
Resolves #3403 
This implements the "Media Initialization Section" of HLS segments (via the `EXT-X-MAP` HLS tag) which is required for streams which use the fragmented MPEG-4 format (or MPEG2-TS with optional initialization sections). Think of it as segment headers which are loaded from an external source.
> [3.2 MPEG-2 Transport Streams](https://datatracker.ietf.org/doc/html/rfc8216#section-3.2)
> The Media Initialization Section of an MPEG-2 Transport Stream Segment is a Program Association Table (PAT) followed by a Program Map Table (PMT).
> 
> Transport Stream Segments MUST contain a single MPEG-2 Program; playback of Multi-Program Transport Streams is not defined. Each Transport Stream Segment MUST contain a PAT and a PMT, or have an EXT-X-MAP tag (Section 4.3.2.5) …

stream.hls: implement media initialization section

---

src/streamlink/plugins/zdf_mediathek.py

- only use HLS streams (drop redundant HDS streams)
- update player ID from 'ngplayer_2_3' to 'ngplayer_2_4'
- remove custom stream weights
- move everything from global scope to plugin class
- update/improve validation schemas
----
It's probably a bit unnecessary, but the plugin currently yields way too many HLS streams when multiple master playlists exist for different languages. Similar issue with the Arte plugin.
Should this behavior be kept or should we just return the first stream? Or filter for the "main" stream maybe (not sure if this is properly flagged for every kind of content)?
----
```
$ streamlink 'https://www.zdf.de/live-tv'
[cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/live-tv
Available streams: 270p_alt (worst), 270p, 360p_alt, 360p, 540p_alt, …
```

plugins.zdf_mediathek: refactor plugin, drop HDS

---

src/streamlink/plugins/openrectv.py

plugins.openrectv was unable to play the stream in media player due to an update to openrec.tv a few days ago.
So, I have made it possible and use low latency streaming video data.
I also added the feature to download uploaded videos.

plugins.openrectv: update HLS URLs

---

.github/ISSUE_TEMPLATE/1_plugin_issue.yml
.github/ISSUE_TEMPLATE/1_plugin_request.yml
.github/ISSUE_TEMPLATE/2_bug_report.yml
.github/ISSUE_TEMPLATE/3_feature_request.yml

- Fixes a copy-paste mistake in the bug report checklist (incorrectly says "plugin issues")
- Replaces "closed issues/reports/requests" with "recently closed issues/reports/requests"

chore: fix issue forms checklist

---

dev-requirements.txt

Could have already been dropped with the removal of py2 (py>=3.3)

tests: remove mock from dev dependencies

---

script/makeinstaller.sh
setup.py

- Bump requests to latest version:
This replaces transitive dependency chardet with charset-normalizer
- Fix Windows installer dependencies:
List dependencies as wheels with strict versions where possible.
pynsist unfortunately doesn't support additional wheel checksums.
----
This pinpoints the dependency versions to strict values (all up2date), similar to the appimages, except for wheel checksums ("dependency lockfile"), as it's not supported by pynsist:
https://github.com/streamlink/streamlink-appimage/blob/2.2.0-1/config.json
The `iso639` dependency is not a wheel, so it has to be kept in the `packages` directive.
Tested a locally built installer in my Win10 VM...
----
#3862, #3863

vendor: set requests to >=2.26.0,<3

---

tests/plugins/test_twitch.py
tests/streams/test_hls.py
tests/streams/test_hls_filtered.py

Temporarily skip EventedHLSStreamWriter related tests on Windows
----
See #3868 
The Windows installer CI job fail until #3864 got merged and this PR rebased onto it

tests: temporarily skip broken tests on win32

---

tests/test_cli_main.py

I currently have limited internet access due to massive floods in my region :cloud_with_rain:. I've tried fixing #3868, but it's more complicated than I thought. We'll probably have to disable these affected tests until this is fixed.
This PR however fixes the tests while being offline.

tests: fix unnecessary hostname lookup in cli_main

---

src/streamlink/plugins/youtube.py

- Revert `isLiveContent` from https://github.com/streamlink/streamlink/pull/3797 use `isLive`
- Added more log details for `videoDetails`
basically same as https://github.com/streamlink/streamlink/pull/3026
closes https://github.com/streamlink/streamlink/issues/3872

plugins.youtube: detect Livestreams with 'isLive'

---

docs/deprecations.rst

https://streamlink.github.io/latest/deprecations.html#id1 (2.3.0)
and
https://streamlink.github.io/latest/deprecations.html#id2 (2.2.0)
are terrible anchor names and need to get fixed. It probably also makes sense distinguishing between streamlink and streamlink-cli on the deprecations page.
----
Let's also prepare the 2.3.0 release. We've had a lot of big changes, the new plugin matching API, fragmented HLS streams, a couple of fixes/improvements for high priority plugins (youtube), regular plugin fixes and a couple of plugin removals. Even if the commit log isn't that long yet, a minor release should be justified.
I'll be submitting the changelog tomorrow, so if there are further changes which should get included, post them.

docs: fix headline anchors on deprecations page

---

script/makeinstaller.sh
setup.py
tests/plugins/test_twitch.py
tests/streams/test_hls.py
tests/streams/test_hls_filtered.py

This temporarily fixes the issue of randomly failing tests on
Windows which seems to be related to the latest requests version
2.26 and requests-mock, where mocked request responses take an
random/arbitrary time to return data, which makes the
EventedHLSStreamWriter tests miss their time frames when writing
HLS segment data to the output buffer.
Since Windows builds of Streamlink don't rely on system python
packages like on most Linux distros for example, downgrading and
forcing an older version of requests on Windows should be fine.
This commit thus partly reverts 35cb8d9f and 29a25fc7 which fixed
the broken dependencies of the Windows installer and skipped the
randomly failing tests on Windows.
----
Resolves #3868 
Even if this resolves #3868 and will make the tests pass again, I'd like …

vendor: downgrade requests to 2.25.1 on Windows

---

src/streamlink/plugins/tv4play.py
tests/plugins/test_tv4play.py

I tried to run for example the news stream from tv4play but it did not work. I know it worked in the past. So my guess is that they changed their URL convention recently.
Here is a current URL from their website: https://www.tv4play.se/program/nyheterna/live/13351122
The current plugin regex in master is: tv4play\.se/program/[^?/]+
But in order to support their new URL convention it needed to be updated to: tv4play\.se/program/[^?/]+/[^?/]+
Based on all URLs I can find on the tv4play website all follow this new pattern of /program/XX/YY/<video_id>
I updated the regex and the tests. Ran them and installed. Now it works.
Here are the changes.

plugins.tv4play: fix plugin URL regex

---

src/streamlink/buffers.py
src/streamlink/stream/hls.py
src/streamlink/stream/segmented.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py
tests/streams/test_hls_filtered.py

As mentioned in #3880, here are some improvements which I wrote while debugging #3868.
The changes are split into multiple logical commits, so please review them one by one.
There's one minor change in the HLSStreamReader in regards to `hls-timeout` and `stream-timeout`, where `stream-timeout` will be used when `hls-timeout` is falsy / zero, but that is also the case for the `hls-segment-attempts`, `hls-segment-threads` and `hls-segment-timeout` parameters in the HLSStreamWriter.
IMO, we don't need special `hls-` or `dash-` options/parameters when generic `stream-` ones already exist. The `dash-` ones which are read in the DASHStreamWriter aren't even defined as streamlink_cli arguments or on the Session's options.

Refactor and improve HLS tests and HLS/Segmented stream classes

---

src/streamlink/plugins/twitch.py
src/streamlink/stream/hls.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py
tests/streams/test_hls_filtered.py

If hls-playlist-reload-time is set to "segment" or "live-edge" and
no segments are available, return the playlist's targetduration
instead of continuing with checking other input values.
Make immediately starting the HLS stream and reader thread optional
in TestMixinStreamHLS and fix subclasses of HLSStream (eg. Twitch)
which have custom open() logic due to the change of starting logic,
so that certain methods on the HLS classes can be mocked.
----
Fixes #3884 
```
$ streamlink -l debug --hls-playlist-reload-time=segment 'https://hakk.in/crash.m3u8' best
[cli][debug] OS:         Linux-5.13.1-2-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.2.0+47.gf57fea8
[cli][debug] …
```

streams.hls: fix playlist_reload_time

---

docs/deprecations.rst
docs/issues.rst
src/streamlink/session.py
src/streamlink/stream/dash.py
src/streamlink/stream/hds.py
src/streamlink/stream/hls.py
src/streamlink/stream/http.py
src/streamlink/stream/rtmpdump.py
src/streamlink/stream/segmented.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

Having multiple session options and CLI arguments for different stream
types which are already covered by generic options/arguments is not only
redundant, but also confusing.
A distinction between different stream types does only make sense when
multiple different stream types are available and the user needs to
explicitly set different values for each of them, but since it's not
always clear which stream type is returned when a stream is selected
via the "best" stream name synonym for example, this makes it even more
confusing. And it's redundant as well, since only one stream can be
selected anyway.
- deprecate `{dash,hds,hls}-segment-attempts`
in favor of `stream-segment-attempts`
- deprecate `{dash,hds,hls}-segment-threads`
in favor of `stream-segment-threads`
- deprecate …

session: deprecate options for spec. stream types

---

src/streamlink/plugins/twitch.py
src/streamlink/session.py
src/streamlink/stream/hls.py
src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
tests/plugins/test_twitch.py

- always stream data from unencrypted segment downloads
- never stream data from cached initialization sections, as the
response content can only be consumed once when stream=True
- update --twitch-low-latency plugin argument and its description
----
This also fixes a bug with the previous media initialization sections (segment maps) implementation, which raises an exception when stream is set to True, as the content can only be consumed once when iterating and writing chunks to the buffer.

stream.hls: remove hls-segment-stream-data option

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py

- subdivide into multiple categories
- reorder arguments and keep generic ones at the top
- rewrite, fix and improve certain argument help texts
----
Please check if my changes are good (enough) and make suggestions if something's not 100% right. There were lots of spelling mistakes, bad grammar/wording and style issues which were not fixed since 2014. I haven't read everything though.

docs: reorganize stream transport options

---

src/streamlink/stream/hls.py

All kinds of errors/exceptions should be caught that can be raised by requests when reading the streamed response content, not just `ChunkedEncodingError`.
https://github.com/psf/requests/blob/v2.26.0/requests/models.py#L757-L765

stream.hls: except more errors raised by requests

---

src/streamlink/stream/hls.py

Streamlink can crash with `streamlink.exceptions.StreamError` since
https://github.com/streamlink/streamlink/commit/193c5c6eb9147a56df25de160f4d35d6f230733a
---
Test URL
https://gist.githubusercontent.com/back-to/514946aad6ce17586d992d05ee42673c/raw/521fe8dd25200042c71f1756b3f61cdd66093a8d/hlsva.m3u8
---
streamlink 2.2.0
```
[cli][debug] Streamlink: 2.2.0
[cli][info] Found matching plugin hls for URL hlsva.m3u8
[cli][info] Available streams: 180p (worst, best)
[cli][info] Opening stream: 180p (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('test_1.m3u8', 'hlsva.m3u8')>
(Could not open stream: Attempted to play a variant playlist, use 'hls://test_1.m3u8' instead)
error: Could not open stream <HLSStream('test_1.m3u8', 'hlsva.m3u8')>, tried 1 times, exiting
```
streamlink 2.3.0 …

stream.hls: handle exception StreamError in Thread-HLSStreamWorker - iter_segments

---

src/streamlink/plugins/raiplay.py

`res.encoding` is `None`
and `charset-normalizer` can't find the right encoding
closes https://github.com/streamlink/streamlink/issues/3895

plugins.raiplay: use 'res.encoding = "UTF-8"'

---

src/streamlink/stream/hls.py
tests/mixins/stream_hls.py
tests/streams/test_hls.py

- close stream immediately when the first playlist fails to parse
- add tests for all playlist parsing errors in the worker thread
----
Follow up of #3903

stream.hls: close stream on initial parsing error

---

.github/workflows/main.yml
docs/install.rst
script/makeinstaller.sh
setup.py
tests/mixins/stream_hls.py

`self.rebuild_proxies(request, self.proxies))` seems to slow down `requests`
https://github.com/psf/requests/commit/60ea7f0c2def461a9ddc20e7af0fc90b68dbe0de#diff-c80d84057edadb04b5615f7169c55f88ccda358d7c20af966afb20c0d0d1056a
which results in a pytest timeout, because 5 seconds is not enough on windows
```
with kwargs.setdefault('proxies', self.proxies)
============================================================================================ slowest 10 durations =============================================================================================
0.86s call     tests/streams/test_hls.py::TestHLSStreamEncrypted::test_hls_encrypted_aes128
0.53s call     tests/streams/test_hls.py::TestHLSStreamEncrypted::test_hls_encrypted_aes128_key_uri_override
0.43s call …
```

tests: increase TIMEOUT_AWAIT_WRITE and update requests

---

src/streamlink/plugins/sportschau.py

Resolves #3945
Not the focus of Streamlink to fix audio-only streams, I know, but the fix is simple and at least it doesn't raise any errors.
The olympics/paralympics section on the site still does not work with these changes, as they seem to be using some special stream setup with iframes just for the event (tokio2020.sportschau.de). It's not worth supporting this unless we know that similar setups will be kept for future events.

plugins.sportschau: fix audio streams

---

docs/install.rst
script/makeinstaller.sh
setup.py

Resolves #3944 
This adds the `lxml` dependency for parsing XML and HTML to Streamlink's `install_requires`.
There's also the `lxml-stubs` package available on pypi for adding type definitions which are lacking in the `lxml` package, but I don't know how this external package works. I'm using pycharm professional and it's generating types from the docs automatically (not that well though). `lxml-stubs` is supposed to go into `dev-requirements.txt` I think. Should this be added?
----
The validation methods and `parse_xml` utility method have not been modified yet and are still using the standard library methods for parsing XML. DASH streams and the validation methods (which are only called one single plugin - rtve) are therefore not affected.
I've tried to update the methods, but ran into …

vendor: add lxml dependency

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
src/streamlink_cli/utils/__init__.py
src/streamlink_cli/utils/formatter.py
src/streamlink_cli/utils/path.py
tests/test_cli_main.py
tests/test_cli_utils_formatter.py
tests/test_cli_utils_path.py

- support the same plugin metadata variables in `--output`, `--record`
and `--record-and-pipe` like they already exist in `--title`:
`{url}`, `{author}`, `{category}`/`{game}` and `{title}`
- substitute unsupported file name characters on specific OS-types
- add `--fs-safe-rules` CLI argument for overriding substitution logic
- add new Formatter class with caching and parameter translation
- create formatter instance in `handle_stream` and pass it to output
methods where player titles or file names need to be formatted
- rewrite test_cli_main tests
Co-Authored-By: Ian Cameron <1661072+mkbloke@users.noreply.github.com>
----
Resolves #3898
Related #3954, #3933, #3913 
----
- ~~The critical code path where the formatter gets initialized is currently not tested because there weren't any test …

cli: player title and file output metadata vars

---

src/streamlink/plugin/api/validate.py
src/streamlink/plugins/radiko.py
src/streamlink/utils/__init__.py
tests/resources/__init__.py
tests/test_api_validate.py
tests/test_utils.py

- replace xml.etree from standard library with lxml.etree in
plugin.api.validate, utils.parse_xml, plugins and tests
- add validate.xml_xpath() and validate.xml_xpath_string() methods
- fix validate.get() and return attribute value for given attribute key
- refactor validate.xml_element() validation method
- fix and add tests
----
#3952

plugin.api.validate: switch to lxml.etree

---

src/streamlink/plugins/booyah.py

The current booyah plugin does not support the source quality. This PR adds support for it.

plugins.booyah: add support for source stream

---

src/streamlink/plugin/api/validate.py
src/streamlink/plugins/atresplayer.py
src/streamlink/plugins/rtve.py
src/streamlink/utils/__init__.py
src/streamlink/utils/parse.py
tests/test_api_validate.py

1. plugin.api.validate: add args+kwargs to transform
2. plugin.api.validate: add parse_{json,html,xml,qsd}
- add parse_{json,html,xml,qsd} validate.transform wrapper methods
- refactor utils module and move parse* methods into utils.parse
- refactor parse* methods and use common parsing + exception handling
- reformat all-export list in utils

plugin.api.validate: add parse_{json,html,xml,qsd}

---

src/streamlink/plugin/plugin.py
src/streamlink/plugins/booyah.py
src/streamlink/plugins/deutschewelle.py
src/streamlink/plugins/dlive.py
src/streamlink/plugins/galatasaraytv.py
src/streamlink/plugins/latina.py
src/streamlink/plugins/mjunoon.py
src/streamlink/plugins/nbcnews.py
src/streamlink/plugins/nimotv.py
src/streamlink/plugins/nos.py
src/streamlink/plugins/nrk.py
src/streamlink/plugins/openrectv.py
src/streamlink/plugins/picarto.py
src/streamlink/plugins/pluto.py
src/streamlink/plugins/reuters.py
src/streamlink/plugins/streann.py
src/streamlink/plugins/stv.py
src/streamlink/plugins/svtplay.py
src/streamlink/plugins/tv4play.py
src/streamlink/plugins/tv8.py
src/streamlink/plugins/twitch.py
src/streamlink/plugins/youtube.py
src/streamlink/plugins/zeenews.py
tests/plugin/testplugin.py
tests/test_cli_main.py

- add author, category and title attributes to base Plugin class
- make getters return attributes instead of None
- remove unnecessary duplicate attributes and getters from plugins
- keep getters in plugins which use custom logic
----
This change makes it much easier to set the plugin metadata by simply setting the attributes instead of overriding the `get_{author,category,title}` methods every single time with different return values.
The `author`, `category` and `title` attributes are already a well established pattern, so making them part of the Plugin base class is the right choice.

plugin: metadata attributes

---

src/streamlink/plugins/common_jwplayer.py
src/streamlink/plugins/euronews.py
src/streamlink/plugins/livestream.py
src/streamlink/plugins/qq.py
src/streamlink/plugins/steam.py
src/streamlink/plugins/twitch.py

This makes all plugins import the `parse_*` utility methods from `streamlink.util` directly instead of `streamlink.plugin.api.util`.
https://github.com/streamlink/streamlink/pull/3972#issuecomment-909694571
Since these imports/exports have been there in `streamlink.plugin.api.util` since 2014, 3rd party plugins might use them, so we can't remove them yet.
I haven't marked them as deprecated yet because I want to do this once all imports of `itertags` have been removed as well, so the entire module can be deprecated as a whole.

plugins: fix utils imports

---

src/streamlink/plugins/reuters.py

The plugin on the master branch is currently getting the HLS streams exclusively via the fallback method, which searches for HLS-like URLs in the entire content, and it's very slow. This PR improves the resolve time by at least 3x.
Front page
```
$ streamlink -l debug 'https://www.reuters.com/'
[cli][debug] OS:         Linux-5.13.12-1-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.3.0+37.g75ca640
[cli][debug]  url=https://www.reuters.com/
[cli][info] Found matching plugin reuters for URL https://www.reuters.com/
[plugins.reuters][debug] Trying to find source via meta tag
[plugins.reuters][debug] Trying to find …
```

plugins.reuters: rewrite and fix using XPath

---

src/streamlink/plugins/euronews.py

Live (main - youtube)
```
$ streamlink -l debug 'https://euronews.com/live'
[cli][debug] OS:         Linux-5.13.12-1-git-x86_64-with-glibc2.33
[cli][debug] Streamlink: 2.3.0+37.g1d121ba
[cli][debug]  url=https://euronews.com/live
[cli][info] Found matching plugin euronews for URL https://euronews.com/live
[plugins.youtube][debug] Using video ID: sPgqEHsONK8
[plugins.youtube][debug] This video is live.
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
```
Live (de - youtube)
```
$ streamlink -l debug 'https://de.euronews.com/live'
[cli][debug] OS: …
```

plugins.euronews: rewrite and fix using XPath

---

script/makeinstaller-assets.json
script/makeinstaller.sh

This is a preparation commit for the new FFmpeg asset files:
https://github.com/streamlink/FFmpeg-Builds
It moves the Windows installer assets JSON data from the remote streamlink-assets repo to here, which is more reliable, safe and secure. Assets data which verifies files shouldn't be loaded from a remote source.
https://github.com/streamlink/streamlink-assets/blob/2020.4.21/data.json
There's also a slight modification of the data structure (type + sha256) and file sources. Previously, the makeinstaller script read the latest tag from the streamlink-assets repo via the GH API, got the assets data from the JSON file of that tag and downloaded/verified the release files on that tag's release.
Now it has the URLs of the release files included directly instead of having to query the GH API. …

installer: move assets config to local JSON file

---

script/makeinstaller-assets.json

Resolves #3931 
Upgrades the bundled 3rd party FFmpeg build (Zeranoe) in Streamlink's Windows installer from 4.2 to 4.4, built here on GH actions:
https://github.com/streamlink/FFmpeg-Builds
FFmpeg build flags (chosen by the `win32 gpl 4.4` build flavor):
```
--enable-gpl
--enable-version3
--disable-debug
--disable-w32threads
--enable-pthreads
--enable-iconv
--enable-libxml2
--enable-zlib
--enable-libfreetype
--enable-libfribidi
--enable-gmp
--enable-lzma
--enable-fontconfig
--enable-libvorbis
--enable-opencl
--enable-libvmaf
--enable-vulkan
--disable-libxcb
--disable-xlib
--enable-amf
--enable-libaom
--enable-avisynth
--enable-libdav1d
--disable-libdavs2
--disable-libfdk-aac
--enable-ffnvcodec
--enable-cuda-llvm
--enable-frei0r
--enable-libglslang
--enable-libgme
--enable-libass …
```

installer: switch to streamlink/FFmpeg-Builds

---

src/streamlink/stream/__init__.py
src/streamlink_cli/console.py
src/streamlink_cli/main.py
tests/test_cli_main.py
tests/test_console.py

1. `console.msg()` should only receive an interpolated string as sole parameter, same as all `log.{info,warning,debug,error,trace}()` calls.
2. `console.msg_json()` should be able to receive multiple args and keywords that will be merged in the output without altering the main object.
This is required for an implementation of #3941 where a stream object output needs to include additional properties.
3. `console.{ask,askpass}()` should use the same output stream as the regular msg calls and the logger, namely `stdout`, and not use `stderr`.
- Since (1) already forces almost all parameters of `console.*` calls to be changed, I fixed all strings in the entire cli.main module.
- (2) adds types to the global vars, so all console methods (and attrs/methods of the other vars) can be referenced. …

cli.console: refactor ConsoleOutput

---

src/streamlink/plugin/plugin.py
src/streamlink_cli/main.py
tests/test_cli_main.py

- Add `Plugin.get_metadata()` which returns a dict of all metadata.
- Add `metadata` property to list of all resolved streams, but merge
all metadata properties with the specific stream output in order to
not introduce a breaking change in the JSON output format.
----
Resolves #3941

cli: include plugin metadata in --json output

---

src/streamlink_cli/output.py
tests/test_cli_playerout.py

Don't raise a `KeyError` when an invalid or unknown variable is set by the user in `--player-args` / `-a`.

cli.output: fix unknown vars in --player-args / -a

---

src/streamlink_cli/argparser.py
src/streamlink_cli/main.py
src/streamlink_cli/utils/__init__.py
src/streamlink_cli/utils/formatter.py
tests/test_cli_utils_formatter.py

This adds support for the `{time}` / `{time:format}` variable to `--title` and `--output`, which has been a much requested feature in the past. The answer has always been "use your command line shell", which is not that great and Streamlink should support something very basic like that.
The `:format` part is optional and based on the standard string format specifiers described in PEP3101:
https://www.python.org/dev/peps/pep-3101/#format-specifiers
The logic for this is however much simplified and doesn't support nesting, etc, because we don't need it here.
Format strings on variables where there's no formatting callback registered get ignored. Conversion flags like `!r`, `!s`, etc, get ignored as well.
https://www.python.org/dev/peps/pep-3101/#explicit-conversion-flag
----
- In order to …

cli: add {time:format} var to --output / --title

---

src/streamlink_cli/argparser.py

`ValueError: unsupported format character 'Y' (0x59) at index 2696`

cli.argparser: Fixed ValueError for streamlink --help

---

docs/_man.rst

The manpage should not suggest deprecated CLI arguments (#3893)

docs: fix CLI argument example in manpage

---

docs-requirements.txt
docs/_static/styles/custom.css

- upgrade furo to 2021.08.31
- fix/restore custom theme overrides
----
The furo theme had its first stable release last week.
https://github.com/pradyunsg/furo/releases
Most of the changes are only bugfixes, but there's also a custom theme variant selection now which makes it worth upgrading. The only noticeable difference should be a short scroll animation for link anchors, the rest should look and behave the same except for very minor spacing changes.
This version of furo also requires sphinx 4 now, but that shouldn't be a problem anymore after 5e65d2d9227814ea303300b4dd7269c215fa1865 fixed a build option which caused problems between sphinx 3 and 4.
Please carefully compare the docs preview with the live docs before merging. There's a chance that I missed something that needs fixing …

docs: bump furo docs req to 2021.09.08

---

src/streamlink/plugin/api/http_session.py
tests/test_api_http_session.py

According to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1), URLs are considered equal even if they differ in the case of the hexadecimal digits of percent-encoded characters, eg. `%FF` == `%ff`. URL normalizers **should** always use uppercase characters, which is why `urllib3` correctly transforms those lowercase digits to uppercase ones.
This is a problem though for sites which compare the request URL (or parts of it) byte for byte and return different responses depending on that. See https://github.com/streamlink/streamlink/issues/4002#issuecomment-916038530
This PR therefore adds overrides for `urllib3` which make it not transform hexadecimal digits of percent-encoded characters to uppercase. Since URLs are still considered equal, this shouldn't break anything …

http_session: override urllib3 percent-encoding

---

tests/__init__.py

tests: fix typo in pytest skipif marker

---

src/streamlink/plugins/ard_live.py
src/streamlink/utils/__init__.py
tests/test_utils.py

I've been trying to clean up the `streamlink.utils` module and from what it looks like, the `verifyjson` method seems to be only used by the `ARDLive` plugin which itself could use a rewrite / simplification. This PR rewrites the plugin and removes the unneeded utility method.
Even though I'm pretty sure that the entire content is available as HLS via the "auto" quality name, I left the HTTPStream stuff, but didn't merge both stream types together like before, because it's unnecessary and confusing. There's also a couple of simplifications of the validation schema due to changes on the site and its JSON data. And I've added the title metadata.
----
Live:
```
$ streamlink 'https://live.daserste.de/'
[cli][info] Found matching plugin ard_live for URL https://live.daserste.de/
Available …
```

plugins.ardlive: rewrite plugin

---

script/install-dependencies.sh

- Fix CI, don't fail on python 3.10
- temporary until lxml gets an update
closes https://github.com/streamlink/streamlink/issues/3971
---
Original files are downloaded from `the unofficial Windows binaries https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml`
- https://github.com/lxml/lxml/blob/ea954da3c87bd8f6874f6bf4203e2ef5269ea383/INSTALL.txt#L105-L115
- https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
```text
556433cadf982a578ee74e989883a07aa9d2a59a04eb2b9f6397c0b4b471ecad  lxml-4.6.3-cp310-cp310-win_amd64.whl
f756d973f89dd0715b5e93301afb9ebdd612ef53ac8986516c1eb0bc6518d85f  lxml-4.6.3-cp310-cp310-win32.whl
```

ci: temporary windows python 3.10 fix for missing `lxml 4.6.3` wheel

---

src/streamlink/plugins/abweb.py
src/streamlink/plugins/akamaihd.py
src/streamlink/plugins/albavision.py
src/streamlink/plugins/ard_mediathek.py
src/streamlink/plugins/atresplayer.py
src/streamlink/plugins/cdnbg.py
src/streamlink/plugins/delfi.py
src/streamlink/plugins/dogus.py
src/streamlink/plugins/earthcam.py
src/streamlink/plugins/euronews.py
src/streamlink/plugins/hds.py
src/streamlink/plugins/hls.py
src/streamlink/plugins/http.py
src/streamlink/plugins/idf1.py
src/streamlink/plugins/mediaklikk.py
src/streamlink/plugins/nbc.py
src/streamlink/plugins/nbcsports.py
src/streamlink/plugins/sportschau.py
src/streamlink/plugins/streamable.py
src/streamlink/plugins/vk.py
src/streamlink/plugins/webtv.py
src/streamlink/session.py
src/streamlink/stream/hds.py
src/streamlink/utils/__init__.py
src/streamlink/utils/url.py
tests/test_utils.py
tests/test_utils_url.py

This is part of another clean-up of the utils module (there's still much to do)
- `absolute_url` and `prepend_www` (unused) belong into the `streamlink.utils.url` module.
I've also improved the logic a big and fixed the tests.
- Modules should not import from `streamlink.utils` but instead from the specific submodules.
Once a new regex-based plugin resolver will get added in the future, this will avoid unnecessary imports of the entire utils module.

utils: move all URL methods to utils.url

---

src/streamlink/stream/hls.py

from
```
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', 'SAMPLE-AES')
```
to
```
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
```

stream.hls: Fix error msg for 'Unable to decrypt cipher ...'

---

script/install-dependencies.sh
tests/test_stream_json.py

Fixes #4021 
----
requests `2.26.0`:
https://github.com/psf/requests/commit/5351469472eccee7ed1a6cae53341446c520d807#
> When the brotli or brotlicffi packages are installed,
> urllib3.util.make_headers() inserts ',br' in the Accept-Encoding header
> and decodes br from the answers.

tests: fix Accept-Encoding headers in stream_json
