- docs/plugin_matrix.rst
- src/streamlink/plugins/pluzz.py
- tests/plugins/test_pluzz.py
Resolves #4017 
This is a complete plugin rewrite which was necessary because of the API changes and video-id extraction.
This also removes the unused HDS streams, subtitle muxing and specific error messages for geo-blocked or expired content. Since ludo.fr and zouzous.fr were both redirecting to france.tv, I removed them as well.
I've tested all of the URLs listed in the test file and removed those which returned a 4xx.
According to some API URL tests via curl, it looked like all those query parameters were required to get valid JSON responses. This is reconstructed from the site's JS code, but since some parameters are optional and since there's also a timezone parameter, I can not guarantee that this is working 100% correcly for all the content.
It's possible that subtitle muxing could …
> plugins.pluzz: rewrite plugin

- src/streamlink/plugins/artetv.py
Resolves #4026 
Closes #4027 
----
I had already implemented stream version selection for all the available languages/sub-streams (see #3167) when I noticed that Streamlink currently doesn't support HLS media items of the type `SUBTITLES` (aka. "non-external subtitles"):
- https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.1
- https://github.com/streamlink/streamlink/blob/24c59a23103922977991acc28741a323d8efa7a1/src/streamlink/stream/hls.py#L512-L516
This unfortunately means that adding a sub-stream selection via `--artetv-stream-version` for example or via an optional URL hash doesn't make sense, as the different stream versions are mostly just including different subtitles. Once this feature gets implemented, the stream version selection can be added very easily.
----
```
$ …
```
> plugins.artetv: rewrite plugin using v2 API

- src/streamlink/plugins/bloomberg.py
This updates the plugin code and removes the unnecessary `HDSStream` and `HTTPStream` imports (the original intention of this change). Duplicate HLS streams also get removed, which results in fewer `_alt` streams.
Live - US:
```
$ streamlink -l debug 'https://www.bloomberg.com/live/us'
[cli][debug] OS:         Linux-5.14.5-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0+18.gdabab9f
[cli][debug]  url=https://www.bloomberg.com/live/us
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
[plugins.bloomberg][debug] Found liveId: PHOENIX_US
[utils.l10n][debug] Language code: …
```
> plugins.bloomberg: rewrite plugin

- .github/workflows/main.yml
- dev-requirements.txt
- script/build-shell-completions.sh
- setup.py
Resolves #2993
This builds shell completions files for BASH and ZSH via `shtab`, which unlike other tools I've looked up in the past can parse an `argparse.ArgumentParser` object:
https://github.com/iterative/shtab
It's also only a simple build step and no runtime dependencies are required for implementing shell completions, which is the ideal solution.
Unfortunately, it currently does only support BASH and ZSH. I would love to see FISH support in the future as well.
----
The shell completion files get built via `./script/build-shell-completions.sh` and are optional in the `data_files` field in `setup.py`, just like the man pages.
This means the wheels will include these files when built prior to running setup.py, and pip will write them to
- …
> build: include bash and zsh completions in wheels

- src/streamlink/plugins/picarto.py
Fixes #4051 
The HLS URL hostname for live streams gets read from the player.js URL on the channel page, and VODs take the HLS URL hostname from the preview image address that's available in the GQL API response.
```
$ streamlink -l trace 'https://picarto.tv/Kyorukun'
[10:26:04.626694][cli][debug] OS:         Linux-5.14.5-1-git-x86_64-with-glibc2.33
[10:26:04.626836][cli][debug] Python:     3.9.7
[10:26:04.626869][cli][debug] Streamlink: 2.4.0+26.g38cba64
[10:26:04.626896][cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
[10:26:04.627210][cli][debug] Arguments:
[10:26:04.627238][cli][debug]  url=https://picarto.tv/Kyorukun
[10:26:04.627268][cli][debug]  --loglevel=trace
[10:26:04.627293][cli][debug]  --player=mpv
[10:26:04.627393][cli][info] Found matching plugin picarto for …
```
> plugins.picarto: fix HLS URL hostname

- src/streamlink/plugins/akamaihd.py
- src/streamlink/plugins/albavision.py
- src/streamlink/plugins/cdnbg.py
- src/streamlink/plugins/delfi.py
- src/streamlink/plugins/dogus.py
- src/streamlink/plugins/earthcam.py
- src/streamlink/plugins/hds.py
- src/streamlink/plugins/hls.py
- src/streamlink/plugins/http.py
- src/streamlink/plugins/invintus.py
- src/streamlink/plugins/mediaklikk.py
- src/streamlink/plugins/nbc.py
- src/streamlink/plugins/nbcsports.py
- src/streamlink/plugins/streamable.py
- src/streamlink/plugins/tv999.py
- src/streamlink/plugins/vk.py
- src/streamlink/plugins/webtv.py
- src/streamlink/session.py
- src/streamlink/utils/url.py
- tests/utils/test_url.py
Previously, update_scheme only added schemes on scheme-less URLs and
kept target URLs which included a scheme intact.
This is confusing for plugin implementers and it has already been used
incorrectly a lot of times when trying to force the HTTPS protocol on
unencrypted HTTP URLs. Since the method is called update_scheme, it
should do exactly that, in all cases.
However, always updating the target scheme will break those calls of
update_scheme where the scheme was previously only added if needed, eg.
on scheme-less URLs, partial URLs or URL paths.
An example of this are scheme-less input URLs passed to Streamlink's
`Session.resolve_url()`, which has to implicitly set the HTTP scheme.
Always overriding the scheme would turn explicit HTTPS schemes to HTTP,
which can break certain …
> utils.url: make update_scheme always update target

- src/streamlink/plugins/youtube.py
This replaces `itertags` in the youtube plugin with XPath and validation schemas. Still a couple of plugins left which use itertags...
The `TypeError` exception handling is necessary in the `_get_data_from_api` method because it doesn't check for `str` return values of the `xml_xpath_string` call or `None` return values of the regex. Otherwise another if block would be necessary.
Not sure if it's better to raise the `PluginError` if the validation fails, but since all exceptions were caught previously and `None` was returned on a failed tag lookup, I kept it this way.
> plugins.youtube: replace itertags with XPath

- src/streamlink/plugins/youtube.py
Based on https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136
- Works in videos like https://www.youtube.com/watch?v=Tq92D6wQ1mg
- embedUrl is required for videos like https://www.youtube.com/watch?v=HsUATh_Nc2U but I can't find any examples that aren't protected so I left it out
- Still doesn't work for videos like https://www.youtube.com/watch?v=Cr381pDsSsA which seem to have embedding explicitly disabled (since it returns an `Playback on other websites has been disabled by the video owner.` error)
> plugins.youtube: Better API age-gate bypassing

- tests/plugins/__init__.py
- tests/plugins/test_mediavitrina.py
- tests/plugins/test_orf_tvthek.py
Fixes #4066 
The plugin URL test fixes are optional, but I noticed that they were missing, so I added them...
> tests: fix partial coverage in can_handle_url

- src/streamlink/plugins/akamaihd.py
- src/streamlink/plugins/dash.py
- src/streamlink/plugins/hds.py
- src/streamlink/plugins/hls.py
- src/streamlink/plugins/http.py
- src/streamlink/session.py
- tests/plugins/test_dash.py
- tests/plugins/test_stream.py
- tests/test_session.py
Apply the https scheme to all input URLs if the scheme is missing:
- session:
- Session.resolve_url()
- session option `http-proxy` (`--http-proxy` CLI argument)
- plugins.akamaihd: `akamaihd://URL`
- plugins.dash: `dash://URL` or `URL.mpd`
- plugins.hds: `hds://URL` or `URL.f4m`
- plugins.hls: `hls://URL` or `URL.m3u8`
- plugins.http: `httpstream://URL`
Regular http URLs (non-https/TLS) will need to be set explicitly now.
Also
- update/fix test_session
- refactor/fix test_dash
- refactor/fix test_stream
----
Resolves #4047 
Follow-up of #4053
- **Does this introduce a breaking change?**
This changes the way user input is handled. In almost all cases, this simply avoids the initial insecure http request when no scheme was defined, which then gets redirected by the server to a secure …
> session: move from http to https as default scheme

- src/streamlink/plugins/brightcove.py
- tests/plugins/test_brightcove.py
- remove RTMP + flashmedia imports
- refactor `BrightcovePlayer` class
- remove `from_url` and `from_player_key` class methods
- simplify `get_streams`
- update validation schemas
- update plugin URL matcher
----
ref #4040 
These changes do not affect the functionality of the BFMTV plugin, which is the only one currently importing the `BrightcovePlayer` class. Technically, this is a breaking change for custom plugin implementations (removal of the static class methods), but that doesn't matter, since it's not a stable API Streamlink provides.
I've only tested streams on the brightcove player page from BFMTV, but that should cover all the stream types which this plugin supports, namely HLS and MP4 VOD (httpstream).
----
HLS
```
$ streamlink -l debug --title '{title}' …
```
> plugins.brightcove: rewrite plugin

- docs/cli.rst
- docs/deprecations.rst
- src/streamlink/session.py
- src/streamlink_cli/argparser.py
- tests/test_session.py
I have made the `--https-proxy` command line argument in to an alias for `--http-proxy` and suppressed the help output for `--https-proxy`. `https-proxy` has been removed from the `get/set_option` methods, and it will have no effect if set. An `info` log level message is auto emitted if the `--https-proxy` option is used. 
resolves #4094
> cli: remove the https-proxy option in favour of a single http-proxy option

- script/makeinstaller-assets.json
This upgrades FFmpeg to the latest version n4.4.1 and it upgrades some of the build dependencies as well:
https://github.com/FFmpeg/FFmpeg/releases/tag/n4.4.1
https://github.com/streamlink/FFmpeg-Builds/compare/20210826-1...20211030-1
https://github.com/streamlink/FFmpeg-Builds/runs/4054376109?check_suite_focus=true#step:4:12
The previous version was a random commit on the 4.4 branch (latest at that time). The main intention of publishing a new build was cleaning up a merge conflict on the FFmpeg-Builds fork.
> installer: bump ffmpeg to n4.4.1

- script/install-dependencies.sh
- setup.py
And remove the compat wheel installs on Windows for the CI runners, as
lxml 4.6.4 has fixed the missing python 3.10 wheels
https://pypi.org/project/lxml/4.6.4/#files
----
Resolves #4100 
The version requirement got bumped to ensure that everyone's up2date and will be able to find a matching wheel download, even though it's not strictly necessary. The lxml changes themselves are irrelevant for Streamlink.
https://github.com/lxml/lxml/blob/lxml-4.6.4-5/CHANGES.txt
I've also added the less than 5.0 constraint because we should do that on all dependencies, to prevent issues when breaking changes in dependencies are introduced. I will update the version of the websocket-client requirement once I'm done with my new websocket implementation. The other ones will need further review.
> vendor: bump lxml to >4.6.4,<5.0

- setup.cfg
Now that the dependency issues are resolved, let's finally add Python 3.10 to the package classifiers lists.
> setup: add Python 3.10 to classifiers list

- .github/workflows/main.yml
[CVE-2021-42574](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42574) has been published a couple of days ago:
> An issue was discovered in the Bidirectional Algorithm in the Unicode Specification through 14.0. It permits the visual reordering of characters via control sequences, which can be used to craft source code that renders different logic than the logical ordering of tokens ingested by compilers and interpreters. Adversaries can leverage this to encode source code for compilers accepting Unicode such that targeted vulnerabilities are introduced invisibly to human reviewers.
Even though [Github has started showing a warning](https://github.blog/changelog/2021-10-31-warning-about-bidirectional-unicode-text/) about this vulnerability …
> ci.github: check for unicode bidi control chars

- src/streamlink/plugins/nicolive.py
- tests/plugins/test_nicolive.py
There's a special type of nicovideo livestream URL that always points to the latest livestream of a community page which is really convenient. This PR adds support for that type of URLs.
> plugins.nicolive: add support for community urls

- src/streamlink/logger.py
- the `logging.WARN` constant is a deprecated alias for `logging.WARNING` (same as `FATAL` is a deprecated alias for `CRITICAL`)
- `streamlink.logger.TRACE` should be properly exported via `__all__`
> logger: fix warning import and trace export

- setup.py
- src/streamlink/plugin/api/websocket.py
- src/streamlink/session.py
- tests/test_api_websocket.py
- tests/test_session.py
- bump websocket-client requirement to >=1.2.1,<2.0
- avoid circular import by importing HTTPSession in session directly
- implement a common WebsocketClient based on the WebSocketApp API of
websocket-client, so that plugins don't have to re-implement basic
boilerplate code
- automatically apply User-Agent header
- automatically apply proxy settings
- set websocket log level (globally)
- add tests
----
This is a simple wrapper for `websocket-client`'s `WebSocketApp` class, which sets the HTTP header of the initialization request and which sets the HTTP proxy options from the session instance. The tests therefore don't test any actual websocket functionality, only the correct usage of the `WebSocketApp` API.
- https://websocket-client.readthedocs.io/en/latest/
- …
> plugin.api: implement WebsocketClient

- src/streamlink/plugins/twitch.py
- src/streamlink/session.py
- src/streamlink/stream/hls.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/plugins/test_twitch.py
This reverts commit ccdd84bf769fab57f2c99816a726e1ae1d5cf4f8
- resolve merge conflicts
- keep stream=False parameter in HLSStreamWriter.fetch_map
- keep updated help text of --twitch-low-latency
----
closes #4126
closes #4146
Let's temporarily revert ccdd84bf until a fix has been found for the segment request issues when `stream` is set to `True`.
See https://github.com/streamlink/streamlink/issues/4126#issuecomment-955822923
TL;DR
Add back the suppressed `--hls-segment-stream-data` CLI parameter (and its according session option), with default value of `False`, so that HLS segments don't get downloaded with `stream=True` by default, which is causing issues since the 2.4.0 release.
> revert: stream.hls: remove hls-segment-stream-data option

- src/streamlink/plugins/goltelevision.py
- tests/plugins/test_goltelevision.py
```
$ streamlink https://goltelevision.com/en-directo -l info
[cli][info] Found matching plugin goltelevision for URL https://goltelevision.com/en-directo
[cli][info] Available streams: 360p (worst), 480p, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
```
> plugins.goltelevision: fix api url and update plugin url

- src/streamlink/session.py
- src/streamlink_cli/main.py
- tests/plugins/test_stream.py
- tests/test_cli_main.py
- tests/test_plugins_input.py
- tests/test_session.py
Breaking change:
Instead of resolving a plugin instance in `Streamlink.resolve_url(url)`
from the provided input URL (which can be redirected), resolve the
plugin class and the resulting URL, and cache the tuple. Also affects
`Streamlink.resolve_url_no_redirect(url)`.
The main reason for this change is streamlink_cli and how the plugin
options get set. The plugin options need to be set on the class before
it gets initialized, so that the instance can access the options in its
constructor method. This also fixes any kind of state stored on the
plugin instance.
- resolve and cache a tuple of the plugin class and resulting URL
- initialize plugin in streamlink_cli after applying its options
- remove plugin variable from global scope in streamlink_cli
- fix, rewrite and add tests
---- …
> session.resolve_url: return plugin class + URL 

- docs/cli.rst
- src/streamlink/stream/http.py
As mentioned in #4169, the method parameter was not working.
I've also changed `valid_args()` and hardcoded the supported args, because `requests.Request()` and `requests.Session.request()` don't share the same set of args and some args should not be set by the user anyway.
No tests, because there are no HTTPStream tests, and I don't want to add new ones. You can check the output of `--json` instead.
> stream.http: fix custom method argument

- docs/install.rst
- setup.py
- remove the `STREAMLINK_USE_PYCRYPTO` env var switch from setup.py
- sort dependencies list
- update dependencies section in install docs
- sort dependencies table
- rephrase notes column
----
ref #4170, #713
pycrypto has had its last update in 2013
https://pypi.org/project/pycrypto/#history
As I've shown in #4170, there are no streamlink packages (anymore) which depend on pycrypto. If I missed one, then they will have to upgrade.
I included the updates for the docs in this commit because I don't want to post two PRs. I also removed the versions of non-build-dependencies from the docs because they were never up2date and it doesn't make sense having two lists for this. The only dependency list that matters is the one in setup.py (or setup.cfg if we move to a declarative list). Please take …
> setup: drop pycrypto support

- docs/install.rst
- script/install-dependencies.sh
- script/makeinstaller.sh
- setup.cfg
- setup.py
- src/streamlink/utils/l10n.py
- tests/utils/test_l10n.py
- drop iso-639 and iso3166 dependencies in favor of pycountry
- remove the `STREAMLINK_USE_PYCOUNTRY` env var switch from setup.py
- move dependencies list from setup.py to setup.cfg
- update utils.l10n and its tests
- update Windows installer config
- update docs
----
resolves #4170
> setup: drop iso-639/iso3166, default to pycountry

- .gitignore
- MANIFEST.in
- script/build-shell-completions.sh
- setup.py
- move build directory of the shell completions from /build/shtab to
/completions due to an sdist restriction of setuptools and MANIFEST.in
- recursively include the /completions directory in MANIFEST.in
- update data_files path in setup.py (for inclusion in wheels)
- update .gitignore
----
https://github.com/streamlink/streamlink/pull/4177#issuecomment-969088309
```
$ rm -rf src/streamlink.egg-info build/lib
...
$ ./script/build-shell-completions.sh
Completions for bash written to /home/basti/repos/streamlink/completions/bash/streamlink
Completions for zsh written to /home/basti/repos/streamlink/completions/zsh/_streamlink
$ python setup.py clean sdist bdist_wheel
...
$ bsdtar tf dist/streamlink-2.4.0+92.g54356a0.tar.gz | grep -E 'bash|zsh'
streamlink-2.4.0+92.g54356a0/completions/bash/ …
```
> setup: include shell completions in sdist

- .github/workflows/main.yml
- script/makeinstaller-requirements.json
- script/makeinstaller.sh
Resolves #4179 
This fixes the broken pycountry import in the Windows installer's Python environment by building the pycountry wheel locally in the makeinstaller.sh script and including it instead of the source tarball:
https://github.com/streamlink/streamlink/issues/4179#issuecomment-971382579
**A `3.0.1` release needs to be published right after testing/confirming and merging this.**
This fix isn't an ideal solution. All I want is to resolve this as quickly as possible. I will take a look at rewriting this properly afterwards, similar to the appimages build config, which uses a package "lockfile" (which we don't have here) with hashes. Pynsist unfortunately doesn't support this and since we're now using pip for building wheels locally anyway, we can utilize that and switch to the …
> installer: rewrite wheels config, fix pycountry

- src/streamlink/plugins/crunchyroll.py
Currently, none of the metadata attributes is set, this PR adds them using 3 fields provided by the API
- `media.name` as _title_ is the title of the episode
- `media.series_name` as _author_ is the name of the anime/show
- `media.media_type` as _category_ is a more general category, like "anime" or "drama"
> plugins.crunchyroll: add metadata attributes

- src/streamlink_cli/__init__.py
- src/streamlink_cli/main.py
- tests/__init__.py
- tests/test_cli_main.py
- Don't raise a KeyboardInterrupt until streamlink_cli has been fully
initialized. This prevents a stack call from being printed to stderr
when streamlink_cli gets interrupted early.
- Restore default signal handlers once streamlink_cli has finished its
initialization, so that KeyboardInterrupt exceptions can be caught to
perform clean up tasks.
- Restore default signal handlers in test immediately after importing
streamlink_cli once as early as possible, to be able to cancel the
test runners regularly via a KeyboardInterrupt.
- Refactor CLI logging tests, which test the log output of the
initialization and need to stop execution at some point.
----
resolves #4188 
Both the regular entry script and invocation via `python -m streamlink{,_cli}` work.
```bash
$ /usr/bin/timeout …
```
> cli: override default signal handlers

- src/streamlink/plugins/twitch.py
This partly reverts dfea62af0fd8cc2eeb9781e46583c613214a7c2c
----
#4156, #4106
`playerType=embed` seems to cause fewer ads and no midroll ads at all, at least from what I've seen so far.
> plugins.twitch: set playerType back to embed

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
A minor improvement for the prefetch segments in Twitch's HLS streams.
Prefetch segments don't include any information other than the URL of a segment that is available in the future. The parser therefore has to clone the last segment and replace its `uri` attribute.
If the segment durations however vary, which is the case for some streams, then the next playlist reload time can be either too short or too long, as it depends on the last queued segment in the worker, which is one of the prefetch segments. This change therefore calculates the average duration of all available segments for queued prefetch segments, so that the playlist reload time is neither too short or too long.
This PR also adds type annotations and refactors the TwitchSegment a bit.
> plugins.twitch: calculate the average duration for prefetch segments

- src/streamlink/plugins/ard_mediathek.py
Resolves #4191 
One issue I couldn't fix is the text encoding of the metadata which gets messed up by `validate.parse_html()`. See the VOD title down below...
https://github.com/streamlink/streamlink/blob/175d4748561c7154bb80c5a47dae22039e45d4ce/src/streamlink/utils/parse.py#L54-L55
Some VODs also have a second title, eg. if it's a TV show, but I couldn't be bothered to implement this. Not important.
----
Das Erste - Live:
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/' best
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Das Erste - Das Erste" -
```
WDR - Live:
```
$ streamlink -l debug --title '{author} - {title}' …
```
> plugins.ard_mediathek: rewrite plugin

- src/streamlink/utils/parse.py
- tests/utils/test_parse.py
This fixes the character encoding in parsed HTML documents. This should've been caught way sooner.
lxml's XML parser requires bytes as input, hence why strings must be encoded to bytes first (default utf8 encoding). The content is then decoded and parsed correctly as utf8 regardless whether the XML declaration with the document's encoding is missing or not.
The HTML parser on the other hand treats byte inputs differently, but only when the `<meta charset="utf8">` tag is missing in the first X bytes of the document. So if we encode input strings here to bytes as well (default utf8 encoding) and if the tag is missing too, then this will lead to decoding errors, as the parser won't treat the input as utf8 encoded data.
See the added tests.
> utils.parse: fix encoding in parse_html

- src/streamlink/plugin/plugin.py
- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/youtube.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/constants.py
- src/streamlink_cli/main.py
- tests/plugin/testplugin.py
- tests/plugins/test_twitch.py
- tests/test_cli_main.py
- tests/test_plugin.py
The `{id}` metadata is useful for writing unique file names to the filesystem when recording a stream.
This PR also adds the ID metadata to YouTube and Twitch.
The `--title` docs should ideally be rewritten and the available attributes moved to a different section. I will check this later today. After that I'd like to publish 3.0.2, because of the Twitch ads stuff.
> plugin: add 'id' metadata property

- docs/cli.rst
- src/streamlink_cli/argparser.py
- add dedicated metadata variables section to the CLI docs
- rewrite --title help text
- update --output, --record and --record-and-pipe help texts
----
ref #4205 
This moves the metadata variables from the argparse help texts into the CLI docs. This unfortunately means that the argparse help texts can't link to the metadata variables section. At least I don't know how to do this.
It also means that the metadata vars are currently not part of the man page anymore, because the man page only includes the argparse stuff and not the entire CLI document (because we don't want the CLI tutorial in the man page). This could be fixed in the future by splitting up the sections into their own documents and including those in the CLI document and man page. …
> docs: add dedicated metadata variables section

- CHANGELOG.md
The change/fix of the Twitch access token needs to be published as a stable release.
> release: 3.0.2

- src/streamlink/utils/parse.py
- tests/utils/test_parse.py
Resolves #4209 
https://github.com/streamlink/streamlink/issues/4209#issuecomment-980173868
> utils.parse: parse invalid XHTML5 documents

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/test_cli_main.py
Fixes #4212 
Since this isn't the first time that the output of `--help` didn't get checked after modifying the argparse help texts, I've added some tests.
I've also moved the `if args.help` statement to the top of `main()` and prioritized `--help` by doing that, like it is common with other CLI applications. Streamlink shouldn't suppress the help text if there's an input URL set.
> cli: prioritize --help and fix its output

- src/streamlink/plugins/svtplay.py
Update to the new plugin URL matching API removed a couple of characters in the matching URL which broke the live channel matching.
> plugins.svtplay: fix live channel URL matching

- src/streamlink/stream/dash.py
- tests/stream/test_dash.py
could be done differently, but this should work for a quick fix.
```
[stream.dash][debug] Available languages for DASH audio streams: sv-x-tal, sv (using: sv)
720p = 4590.0
720p_alt = 2995.0
[cli][info] Available streams: 234p (worst), 360p, 540p, 720p_alt, 720p (best)
```
closes https://github.com/streamlink/streamlink/issues/4217
> stream.dash: sort video duplicated resolutions by bandwidth

- src/streamlink/plugins/youtube.py
Fixes #4221 
The JSON data has a different scheme on `/live` URLs for some reason. Non-`/live` channel URLs don't have this problem.
> plugins.youtube: fix metadata on /live URLs

- src/streamlink/plugins/ustreamtv.py
Fixes #4236 
```
$ streamlink -l debug 'https://video.ibm.com/nasahdtv' best
[cli][debug] OS:         Linux-5.15.5-2-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.9
[cli][debug] Streamlink: 3.0.3+5.g5eb2ff6
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug]  url=https://video.ibm.com/nasahdtv
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/nasahdtv
[plugins.ustreamtv][debug] Connecting to UStream API: media_id=6540154, application=channel, referrer=https://video.ibm.com/nasahdtv, cluster=live
[plugin.api.websocket][debug] Connecting to: wss://r4225582-1-6540154-channel-ws-live.ums.services.video.ibm.com/1/ustream …
```
> plugins.ustreamtv: fix websocket address

- src/streamlink/logger.py
- src/streamlink_cli/console.py
- tests/test_cli_main.py
- tests/test_console.py
- tests/test_log.py
Resolves #4235 
The reason why there are still log messages being written to stdout/stderr when any "silent" CLI argument is set (`--json`, `--quiet`, `--stream-url` or even `--loglevel=none`) is because of how Streamlink's `NONE` log level gets interpreted in Python's logging module.
Each logger instance (subclasses of `logging.Logger` or `streamlink.logger.StreamlinkLogger`) can optionally have their own log level. When a logger instance needs to check whether a certain message can be written to the output or not, it first tries to read its own log level value, and if it is set to `logging.UNSET` (which is the default and its value is 0), then it continues with its parent logger instance until it reaches `logging.root` (`RootLogger`). This RootLogger does have a default log level of 30, …
> logger: change NONE loglevel to sys.maxsize

- src/streamlink/plugins/yupptv.py
Not sure for how long this was broken - but for me YuppTV doesn't work without overriding the encoding and adding an addition header.
> plugins.yupptv: override encoding, set Origin header

- tests/test_cli_main.py
**master**
```
$ ls /tmp/streamlinkpipe-*
fish: No matches for wildcard “/tmp/streamlinkpipe-*”. See `help expand`.
ls /tmp/streamlinkpipe-*
$ pytest
$ ls /tmp/streamlinkpipe-*
/tmp/streamlinkpipe-1400506-1-5978  /tmp/streamlinkpipe-1400506-2-6981
```
**this PR**
```
$ ls /tmp/streamlinkpipe-*
fish: No matches for wildcard “/tmp/streamlinkpipe-*”. See `help expand`.
ls /tmp/streamlinkpipe-*
$ pytest
$ ls /tmp/streamlinkpipe-*
fish: No matches for wildcard “/tmp/streamlinkpipe-*”. See `help expand`.
ls /tmp/streamlinkpipe-*
```
> tests: fix named pipe being created in CLI tests

- src/streamlink/plugins/nos.py
Just a small plugin code refactor without any changes to the stream retrieval logic. VODs are working, but I couldn't find any "broadcasts"/"livestreams" on the site. The live streams which are listed on nos.nl lead to a different site and they are DRM protected DASH streams. The live streams which are/were supported by the plugin (#3810) were special sports streams (football, etc), I think.
> plugins.nos: remove itertags

- tests/test_plugins_meta.py
- run test setup only once
- rename some vars / class attributes
- avoid branches in test cases
- fix some assertion messages (longMessage = False)
Ideally, the test cases should be parametrized via pytest, but that requires more boilerplate code which is rather unnecessary.
The reason why I made these changes was that I wanted to see if we could add tests for the removed plugins file, but then I noticed that this would only work in a special CI step that checks the PR branch for removed plugins, and it wouldn't work in the regular python test suite.
> tests: rewrite plugins_meta tests

- src/streamlink/plugins/delfi.py
- tests/plugins/test_delfi.py
- remove itertags
- use validation schemas
- add support for different live streams and VODs:
1. old delfi API (sites use new graphql API)
VODs are not supported on delfi.ee
2. embedded youtube streams / VODs
3. embedded sport.delfi.ee live streams
- remove unnecessary DASHStream and HTTPStream
----
delfi.lt seems to have switched to YouTube for their live streams and some VODs.
All three sites are using a (new) GraphQL API now for VODs from what it looks like, but the API endpoints which were used by the plugin previously are still working on delfi.lt and delfi.lv, so I kept it. If one wants delfi.ee VODs supported, they'll have to implement stream URL retrieval logic via the GQL API.
> plugins.delfi: rewrite plugin

- src/streamlink/plugins/twitch.py
Resolves #4291 
Btw, this is a common problem in lots of other plugins where URL capture groups are used at the end. A proper fix would be not using a capture group for extracting the data but using urlparse and reading/parsing the result instead.
> plugins.twitch: fix pluginmatcher regex

- src/streamlink/stream/hls_playlist.py
Fixes #4300 
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.2
> The EXT-X-BYTERANGE tag indicates that a Media Segment is a sub-range
> of the resource identified by its URI.  It applies only to the next
> URI line that follows it in the Playlist.  Its format is:
>
> `#EXT-X-BYTERANGE:<n>[@<o>]`
>
> where n is a decimal-integer indicating the length of the sub-range
> in bytes.  If present, o is a decimal-integer indicating the start of
> the sub-range, as a byte offset from the beginning of the resource.
> If o is not present, the sub-range begins at the next byte following
> the sub-range of the previous Media Segment.
>
> If o is not present, a previous Media Segment MUST appear in the
> Playlist file and MUST be a sub-range of the same media resource, or
> the Media …
> stream.hls: fix byterange parser

- src/streamlink/stream/hls.py
- tests/stream/test_hls.py
- Move "Range" header value calculation to separate class:
Don't cache offsets by segment URL, and instead refer to the previous
sequence. Initialization maps always require an existing offset value.
- Refactor HLSStreamWriter.fetch and related methods
- Add byterange tests
----
rel #4300, #4301
`EXT-X-BYTERANGE`
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.2
`EXT-X-MAP`
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.5
The spec does not say anything about mandatory offset values for initialization map byteranges, so I'm not sure if what I've implemented is correct. It currently raises a StreamError when the offset is missing on a map's byterange, and the download will fail. It could also default to zero in this case, but I'm not sure if this is implied by the …
> stream.hls: refactor segment byterange calculation

- src/streamlink_cli/main.py
- tests/test_cli_main.py
Hi there!
For new CLI users (e.g., on Ubuntu Server), it is more friendly to tell them that this utility has the ability to save and pipe streams.  
I know they should "RTFM", but IMO, more detailed error messages might get them started sooner.
Original:
```console
$ streamlink ...
[cli][info] ...
[cli][info] ...
[cli][info] ...
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
```
New:
```console
$ streamlink ...
[cli][info] ...
[cli][info] ...
[cli][info] ...
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player, a filepath to save the stream with --output, or pipe the stream to another program with --stdout.
```
> cli: tell users the stream could be saved or piped

- .github/workflows/main.yml
See #4307 
According to my locally built installers, downgrading distlib to 0.3.3 fixes the issue of the broken executables. This is not a long-term solution, but it should work for now.
I'd like to publish 3.1.1 as soon as possible, but I also want to see if the next nightly is working as intended once this gets merged.
As said in #4307, the executables are only broken when trying to run them from a non-command-line context on Windows, eg. from a GUI application and they immediately terminate with exit code 3221225477. I don't know how the executables work. I only know how pynsist concatenates the binaries built by the distlib project with a shebang and the application's entry script.
> installer: set pynsist to 2.7 and distlib to 0.3.3

- src/streamlink/plugins/pluzz.py
Fixes #4325 
```
$ streamlink --http-proxy socks5://localhost:1920 'https://www.france.tv/beijing-h24/direct.html' best
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/beijing-h24/direct.html
[cli][info] Available streams: 216p (worst), 360p, 432p, 540p, 720p (best)
```
> plugins.pluzz: fix workflow value in API schema

- src/streamlink_cli/main.py
- tests/test_cli_main.py
Streamlink currently doesn't log the full path when writing the output to a file. This is an issue when the output path is dynamically generated from the input argument via the stream's metadata, because the user doesn't know where the data was actually written to. The output path gets already logged if the file already exists, but that's not really helpful.
The log message added by this PR does only get printed if the stream is written to a file, and not to stdout via `--stdout` or `--output=-`.
I'm not sure though if we should put the path into quotes and escape it (via shlex.quote), because if there are spaces, it's not perfectly clear. It is however on a separate line in the output, so maybe it is. The file path in the confirm message could also be removed, but that would require the …
> cli: log resolved file output path

- src/streamlink/plugin/api/http_session.py
Creates an adapter with OpenSSL security level 1.  Example usage:
from streamlink.plugin.api.http_session import TLSSecLevel1Adapter
adapter = TLSSecLevel1Adapter()
self.session.http.mount("https://filmon.com", adapter)
self.session.http.mount("https://www.filmon.com", adapter)
---
~I have not added this to `__all__`, is that reasonable?~
There are no tests; I'm not really sure how to test it.
merge before #4335
> plugin.api.http_session: add class TLSSecLevel1Adapter()

- docs/plugin_matrix.rst
- src/streamlink/plugins/rtpa.py
- tests/plugins/test_rtpa.py
See #4341, #4343
Regional Spanish TV channel:
https://en.wikipedia.org/wiki/Radiotelevisi%C3%B3n_del_Principado_de_Asturias
https://www.rtpa.es/
Live:
```
$ streamlink 'https://www.rtpa.es/tpa-television' best
[cli][info] Found matching plugin rtpa for URL https://www.rtpa.es/tpa-television
[cli][info] Available streams: 500k (worst), 1500k (best)
[cli][info] Opening stream: 1500k (hls)
```
VOD:
```
$ streamlink 'https://www.rtpa.es/video:Ciencia%20en%2060%20segundos_551644582052.html' best
[cli][info] Found matching plugin rtpa for URL https://www.rtpa.es/video:Ciencia%20en%2060%20segundos_551644582052.html
[cli][info] Available streams: 240p (worst), 480p (best)
[cli][info] Opening stream: 480p (hls)
```
> plugins.rtpa: add new plugin

- script/makeinstaller-requirements.json
closes #4329 
The main intention of this PR is bumping `charset-normalizer` to the latest version, which fixes the broken charset detection in HTTP requests without charset data in the content-type header, which has previously often lead to broken HLS playlist contents.
The pycountry source-dist tarball did not get bumped in this commit, because it would require additional changes in the installer's build script. Doesn't really matter though.
I will probably also publish a new AppImage release (3.1.1-2) with bumped dependencies. Deps get always bumped there on each release, but since charset-normalizer is a transitive dependency of streamlink, publishing a new patch release here would only make sense if we add it to streamlink's own dependencies list.
> installer: update wheels to latest versions

- docs/cli.rst
> docs: correct minor typo

- src/streamlink/plugins/ard_live.py
Fixes #4354 
```
$ streamlink 'https://live.daserste.de/' best -l debug
[cli][debug] OS:         Linux-5.16.10-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1+12.g2120481
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug]  url=https://live.daserste.de/
[cli][info] Found matching plugin ard_live for URL https://live.daserste.de/
[plugins.ard_live][debug] Player URL: 'https://www.daserste.de/live-de-102~playerJson.json'
[cli][info] Available streams: 270p (worst), 360p, 540p, 720p, 1080p (best)
```
> plugins.ard_live: fix live.daserste.de inputs

- src/streamlink/plugins/twitch.py
- tests/__init__.py
- tests/plugins/__init__.py
- tests/plugins/conftest.py
- tests/plugins/test_filmon.py
- tests/plugins/test_qq.py
- tests/plugins/test_twitch.py
- tests/plugins/test_youtube.py
This should simplify testing plugin URL capture groups and make it more consistent between tests.
Please see the commit messages of both commits.
> tests.plugins: implement should_match_groups

- src/streamlink/plugins/goltelevision.py
and remove unneeded HLSStream subclass
----
Fixes #4367 
The master playlist can be accessed from any region, but individual streams are geo-blocked, so I can't fully verify the plugin. Shouldn't matter though.
```
$ streamlink -l debug 'https://www.goltelevision.com/en-directo'
[cli][debug] OS:         Linux-5.16.11-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1+15.g35f6fb7
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug]  url=https://www.goltelevision.com/en-directo
[cli][info] Found matching plugin goltelevision for URL https://www.goltelevision.com/en-directo
[stream.hls][debug] Using external …
```
> plugins.goltelevision: fix API URL

- tests/test_plugins.py
- tests/test_plugins_meta.py
This rewrites plugin meta tests using pytest, in preparation for my plugin matrix replacement (see #4369). The plugin matrix replacement will then remove the last remaining tests from `tests/test_plugin_meta.py` that have not been touched here.
The old tests were making test assertions inside for-loops while iterating plugin names, etc., which is bad. This PR parametrizes everything while using pytest fixtures, so this will increase the number of collected test and the test results by a lot due to the large number of plugins (see the pytest output), but it'll make reading and fixing test failures much more easy by doing so, especially when I add strict tests for plugin metadata. And reading the tests is much more easy with this change, too. Another bonus is that there's no negated …
> tests: rewrite plugins tests

- src/streamlink/plugins/mildom.py
Issue: 403 error during livestream playback, unable to get m3u8
```
>streamlink -l debug https://www.mildom.com/10148036 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.5
[cli][debug] Streamlink: 3.1.1
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug]  url=https://www.mildom.com/10148036
[cli][info] Found matching plugin mildom for URL https://www.mildom.com/10148036
[cli][info] Available streams: 144p (worst), 360p, 540p, 720p, 1080p (best)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][error] Unable to …
```
> plugins.mildom: get token for livestream

- docs/_static/styles/custom.css
- docs/ext_github.py
I was looking into adding icons to external links in the docs and found a bug in the custom `ext_github` sphinx extension, which generates lots of empty anchor elements while parsing `#issue`, `#pr` or `@username` notations in the document contents. This made the icons appear twice, on the actual link and on the empty one next to it. The fix is to ignore already parsed reference nodes in the extension while parsing the hashtag- and at-notations.
The only two lines in the docs where hashtags- and at-notations are used outside of links are this:
- https://github.com/streamlink/streamlink/blame/3.1.1/docs/cli.rst#L286
- https://github.com/streamlink/streamlink/blame/3.1.1/docs/players.rst#L78
While the changelog explicitly links to the issues and pull requests:
- …
> docs: fix GithubReferences transform, add external link icons

- docs/developing.rst
I accidentally used the wrong format in the doc's plugin metadata example.
----
With the plugin metadata changes being merged, should we publish a new release tomorrow (3.2.0)?
> docs: fix plugin metadata example

- src/streamlink/plugins/afreeca.py
- src/streamlink/plugins/ssh101.py
- src/streamlink/plugins/twitcasting.py
Some module imports that can be cleaned up which I noticed while trying to implement the list of stream types which each plugin returns for the plugins page in the docs. Parsing the plugin ASTs and checking the stream class imports unfortunately doesn't work well, because some plugins return the result of `self.session.streams(URL)`, implement their own stream types (like ustream for example), or subclass HLSStream with required custom logic, so it doesn't make sense implementing such a list if the results are not correct.
> chore: clean up some imports

- src/streamlink_cli/argparser.py
Hi. Today I'm going to download a stream. I tried multiple times and then encountered the following prompt:
```
File foo.ts already exists! Overwrite it? [y/N] 
```
Alright, I want to overwrite the existing file without confirmation, but what options should I specify? Searching for the "overwrite" word in [Command-Line Interface](https://streamlink.github.io/cli.html) turned up nothing, so I made this PR to improve the docs.
> cli: add "overwrite" to --force help text

- src/streamlink/plugins/oneplusone.py
```html
<div class="playlist-player-iframe-container">
<iframe allow="autoplay; fullscreen" class="playlist-player-iframe iframe-player"
data-id=""
allowtransparency="true" allowfullscreen="" scrolling="no" tabindex="0"
src="/tvguide/embed/1?autoplay=0&l=ua"
frameborder="0"></iframe>
</div>
```
> plugins.oneplusone: fix iframe

- docs/_static/styles/custom.css
Long CLI arguments with dashes should never wrap.
> docs: fix CLI argument line breaks

- src/streamlink/plugins/cmmedia.py
- tests/plugins/test_cmmedia.py
> plugins.cmmedia: new plugin

- src/streamlink/plugins/htv.py
- tests/plugins/test_htv.py
~Nobody commented on https://github.com/streamlink/streamlink/issues/4225#issuecomment-1085268031, so...~
URLs:
```
$ streamlink htv.com.vn/truc-tuyen # defaults to first channel in list
$ streamlink htv.com.vn/truc-tuyen?channel=n # where n is valid channel ID
```
Channel IDs are discovered from the player page and can be shown in debug output:
```
$ streamlink --http-proxy 'socks4://localhost:9050' -l debug 'htv.com.vn/truc-tuyen'
[cli][debug] OS:         Linux-5.4.0-107-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 3.2.0+13.g59e847e
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug]  url=htv.com.vn/truc-tuyen
[cli][debug] …
```
> plugins.htv: new plugin

- docs/cli/protocols.rst
- src/streamlink/plugins/dash.py
- src/streamlink/stream/hls.py
1. **plugins.dash: add support for parameters**
This allows passing parameters to `DASHStream` and `requests.request`,
similar to the HLS protocol plugin. See `DASHStream.parse_manifest`.
2. **docs: add protocol-plugin parameters documentation**
and fix docstring of `HLSStream.parse_variant_playlist`
> Add parameters to DASH plugin and document protocol plugin parameters

- docs/cli/protocols.rst
- docs/conf.py
- src/streamlink/stream/dash.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/http.py
- add intersphinx mapping for `requests`, skip Python standard library
- fix `requests.Session.request` references in docs and docstrings
----
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
I didn't include references to the Python standard library, because it adds external links everywhere, which is annoying.
Since this downloads data from external sites, packages like Debian will probably patch out these changes, but that's nothing we care about here.
> docs: add intersphinx config

- setup.cfg
Forgot to include this in #4405
> build: drop removed plugins file from package_data

- .codecov.yml
- .github/workflows/main.yml
- docs/install.rst
- setup.cfg
- setup.py
Resolves #4277 
Required for #4441
> chore: drop support for Python 3.6

- src/streamlink/plugins/svtplay.py
- tests/plugins/test_svtplay.py
Links to https://oppetarkiv.se are redirected to https://www.svtplay.se/kategori/oppet-arkiv
> plugins.svtplay: oppetarkiv.se is not functional anymore

- setup.py
The error message from the `if CURRENT_PYTHON < REQUIRED_PYTHON` block can't be shown if importing setuptools or versioningit raises any errors, so they have to be moved down. Moving the imports into an `if __name__ == "__main__"` block shouldn't cause any linting errors, so adding annotations shouldn't be required.
> build: move imports in setup.py

- src/streamlink/plugins/linelive.py
The following error occurred due to a change in API URL.
```
$ streamlink https://live.line.me/channels/4120347/broadcast/18115135 best
error: Unable to open URL: https://live-api.line-apps.com/app/v3.2/channel/4120347/broadcast/18115135/player_status (404 Client Error: Not Found for url: https://live-api.line-apps.com/app/v3.2/channel/4120347/broadcast/18115135/player_status)
```
This pull request follows the current API URL.
> plugins.linelive: fix API URL

- src/streamlink/plugins/cdnbg.py
- don't use suffix operators in pluginmatcher regex
- don't define validation schema and regexes as class attributes
- replace itertags with xpath query
- make validation schemas more legible by adding _find_url util method
----
ref #4455 
I've checked all the URLs defined in the plugin URL tests, and everything was working except for the ones with geo-restrictions or those which require additional HTTP headers.
> plugins.cdnbg: rewrite plugin

- src/streamlink/plugins/funimationnow.py
ref #4455 
Completely untested changes. This is just the equivalent of the itertags-based logic. Returns the value of the `value` attribute of the first `input` element with the `name` attribute value set to `self.CSRF_NAME`, or `None`.
> plugins.funimationnow: replace itertags

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/test_cli_main.py
Write stream to stdout while also opening it in the player.
----
Closes #4461 
Example
```
$ streamlink --record=- twitch.tv/esl_dota2 best | ffmpeg -hide_banner -i pipe:0 -c copy -f null /dev/null
[cli][info] Found matching plugin twitch for URL twitch.tv/esl_dota2
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[plugins.twitch][info] This is not a low latency stream
Input #0, mpegts, from 'pipe:0':
Duration: N/A, start: 17878.165000, bitrate: N/A
Program 1 
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 191 kb/s
Stream …
```
> cli: add support for --record=-

- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- src/streamlink/stream/hls.py
- src/streamlink/utils/cache.py
- src/streamlink/utils/url.py
- src/streamlink_cli/main.py
- tests/mixins/stream_hls.py
- tests/utils/test_cache.py
- tests/utils/test_url.py
- Replace collection.OrderedDict with builtins.dict where possible:
Python 3.7+ ensures the correct order in builtins.dict objects and is
no longer an implementation detail of cpython.
- Fix OrderedDict type annotation in streamlink.utils.cache.LRUCache
- Add unit test for streamlink.utils.cache.LRUCache
----
https://docs.python.org/3.7/library/stdtypes.html#dict
> Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6.
> chore: remove unnecessary collection.OrderedDict

- docs-requirements.txt
- netlify.toml
- Add versioningit to docs-requirements.txt
Needed dependency when Streamlink was installed in editable mode.
- Reformat netlify.toml
- Update PYTHON_VERSION env var (based on Ubuntu 20.04)
- Always fetch all tags to ensure correct version strings in docs builds
- Add plugins dir to ignore check
----
Changes made in the settings menu on netlify.com:
- Updated to Ubuntu 20.04
- Disabled embedded netlify feedback overlay stuff on rendered docs
> ci: fix netlify PR preview builds

- src/streamlink/plugins/facebook.py
See https://github.com/streamlink/streamlink/issues/4455#issuecomment-1100520504
This only replaces the usage of `itertags` and doesn't fix the whole plugin. Additional changes are "fixes" for the login-requirement detection and an improvement of the title metadata logic, so that it doesn't fetch the same URL twice. I didn't touch any other stuff, hence why the validation schemas rely on `res.text` inputs and why the page's HTML gets parsed twice.
The facebook plugin is currently the last one using `itertags`, so after this PR has been merged, the whole `streamlink.plugin.api.utils` module can be removed.
> plugins.facebook: replace itertags

- docs/install.rst
https://en.wikipedia.org/wiki/Debian_version_history#Release_table
The `buster-backports` package is outdated:
https://packages.debian.org/buster-backports/streamlink
Whereas `bullseye-backports` is not:
https://packages.debian.org/bullseye-backports/streamlink
> docs: update debian backports info

- src/streamlink/plugins/showroom.py
- rewrite room_id lookup
- get live status and title metadata from API
- replace HLSStream subclass with hls-playlist-reload-time override
----
fixes #4472 
Not 100% sure about the `live_status == 2` for live streams, but from what I observed using a Japanese proxy, this should be fine.
@DCxDESIGN could you please test/verify these changes? If you're unsure how to apply these changes, just download the whole plugin code from [here](https://raw.githubusercontent.com/streamlink/streamlink/d346b0a8f5f3f386b1407e124df1d0caec0f5534/src/streamlink/plugins/showroom.py) and either replace it in your streamlink install, or better, [sideload the plugin](https://streamlink.github.io/latest/cli/plugin-sideloading.html).
> plugins.showroom: fix plugin

- src/streamlink_cli/argparser.py
Ref: #4085 and #4477
I don't think the dir/subdir creation behaviour is documented anywhere, so this does so.
> cli.argparser: update help with dir/subdir creation info

- .github/release_template.md
- docs/_static/styles/custom.css
- docs/donate.rst
This updates the releases page and makes it consistent with the one in the streamlink/windows-installer repo:
https://github.com/streamlink/windows-installer/releases
Most importantly, it adds a warning message for people looking for the installers (which should be added temporarily).
Since it also changes the "support" section, I updated and fixed the donations page in the docs.
> Update GitHub release template and donations page in the docs

- src/streamlink/plugins/nicolive.py
Fix `AttributeError: 'NicoLive' object has no attribute 'hls_stream_url'` when `--niconico-timeshift-offset` option is used
> plugins.nicolive: fix timeshift-offset option

- CHANGELOG.md
Let's see if we're ready for the 4.0.0 release. Opening this directly as a PR instead of asking in an issue thread first, so everyone can see the current changelog...
Anything missing?
- the crunchyroll plugin for example is currently broken and it's one of the plugins that has lots of users (it's a VOD-only plugin though)
- useragents are probably out-of-date
Any mistakes in the changelog?
Btw, I want to finally change the changelog format after the 4.0.0 release. Writing the changelog in pycharm is lagging like crazy, even without WYSIWYG preview, and browsing it in the docs or git repo is stupid due to its length, too.
As usual, the date is set for today, but that's just a placeholder.
> release: 4.0.0

- .github/workflows/main.yml
Fixes #4502 
The unnoticed mistake was that BASH doesn't match anything in brace expansions if there's only one element.
```sh
$ bash -c 'ls dist/*{.tar.gz}'
ls: cannot access 'dist/*{.tar.gz}': No such file or directory
$ bash -c 'ls dist/*{.tar.gz,.exe}'
ls: cannot access 'dist/*.exe': No such file or directory
dist/streamlink-4.0.0.tar.gz
$ bash -c 'shopt -s nullglob; ls dist/*{.tar.gz,.exe}'
dist/streamlink-4.0.0.tar.gz
```
As an alternative to this PR, I've got #4497 pretty much ready and validated multiple test releases in my test-repo using my test-account, but just apply this simple fix here and release 4.0.1.
----
Issue was introduced by #4405:
https://github.com/streamlink/streamlink/commit/2dd2f35930143946afe920c084ff910912a41547#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203 …
> ci: fix github deploy config

- docs/cli/tutorial.rst
live page with as of opening of this PR broken link: https://streamlink.github.io/cli/tutorial.html
> docs: fix broken relative link

- docs/_static/styles/custom.css
- docs/install.rst
`versioningit` needs to be documented here, because packagers who use setuptools directly will need it.
I've also reformatted the dependencies table in one go and added notes about PEP517/PEP518 and the 4.0.0 release.
> docs: update dependencies section in install docs

- docs/cli/tutorial.rst
rel #4506 
This should've been a cross reference to the specific section in the docs, not a direct link. The issue came up when the CLI tutorial was moved in #4415. Git-blame from before #4415:
https://github.com/streamlink/streamlink/blame/3.2.0/docs/cli.rst#L38
> docs: use cross-reference instead of direct link

- src/streamlink/plugins/youtube.py
Fixes #4513 
Old consent dialog (I agree):
```
$ streamlink -l debug youtube.com/hospitalrecords/live
[cli][debug] OS:         Linux-5.17.5-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.0.1+7.g7426d573
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug]  url=youtube.com/hospitalrecords/live
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords/live
[plugins.youtube][debug] consent target: https://consent.youtube.com/s
[plugins.youtube][debug] consent data: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: jdkegu3Zexg
[plugins.youtube][debug] This video is live. …
```
> plugins.youtube: fix consent dialog

- src/streamlink/plugins/crunchyroll.py
- tests/plugins/test_crunchyroll.py
* update params for Windows app
* remove Android headers
* fix device_id cached value
* add id to metadata
* minor spelling corrections
* add support for beta URLs
* update tests
* update cache.set() calls to use expires kw
* update expires_at=0 to expires=0
closes #3674
closes #4453
> plugins.crunchyroll: update/fix

- src/streamlink_cli/main.py
- tests/test_cli_main.py
When running test as root, there is an additional log done to warn the
user that it is running streamlink as root. This causes some logging
tests to fail.
For these logging test, ensure we run with a mocked user euid when not
testing for the root euid.
I know that running as root is unusual, but it can happen when packaging for distributions.
> tests: mock user euid to be able to run tests as root

- src/streamlink/plugin/api/http_session.py
`InsecureRequestWarning` can be emitted by urllib3 here:
https://github.com/urllib3/urllib3/blob/1.26.9/src/urllib3/connectionpool.py#L1042-L1062
----
Example with HTTPS requests on a temporarily set up TLS certificate that's self-signed:
Without `--http-no-ssl-verify` (`SSLCertVerificationError`):
```
$ streamlink httpstream://https://test.bastimeyer.de/test.mp4 best
[cli][info] Found matching plugin http for URL httpstream://https://test.bastimeyer.de/test.mp4
[cli][info] Opening stream: live (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('https://test.bastimeyer.de/test.mp4')> (Could not open stream: Unable to open URL: https://test.bastimeyer.de/test.mp4 …
```
> http_session: don't disable InsecureRequestWarning

- docs/api_guide.rst
- Use unopinionated Apple HLS stream example URL
- Update Stream string representations
- Fix class/method/attribute references
> docs: rewrite API guide

- docs/donate.rst
Just cleaning up my donation methods since some of them are stale.
> Clean up gravyboat donation links

- src/streamlink/stream/hls.py
- tests/mixins/stream_hls.py
- tests/stream/test_hls.py
- Catch ValueError when decrypting and unpadding segments, as well as
other exceptions that can be raised when downloading the segment,
similar to unencrypted segments, and log error messages accordingly.
Don't close the stream on any of those errors.
- Remove garbage data truncation from encrypted segments:
This was (most likely) implemented because of an old issue related to
Content-Length HTTP headers not being handled correctly, leading to
partial segment downloads. Cutting off data that doesn't fit into the
AES block size doesn't make sense, as it implies that the segment data
incomplete, and incomplete segment data misses its padding bytes at
the end which must always be included.
- Update tests
----
*updated commit message above, old initial comment below*
----
`ValueError`s can …
> stream.hls: refactor segment decryption

- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls_playlist.py
- Generate a mapping of tags->callbacks on parser init once
and cache mapping as class attribute (avoid parent class lookups)
- Performance: look up tags in cached mapping in `parse_line()`
- Re-order `parse_tag_...` methods by definition order of RFC 8216
- Add docstring to each `parse_tag_...` method with link to RFC 8216
- Add typing annotations to each `parse_tag_...` method
- Fix minor typing issues in regards to optional URIs in Key and Media
and update parse methods accordingly
- Pass keywords to various named tuples instead of positional args
----
This improves the performance of the `M3U8Parser`, as it doesn't have to generate a string with the name of supported tag methods for each tag anymore, and it can simply look up tags in a pre-generated mapping of tags->callbacks that get …
> stream.hls_playlist: refactor M3U8Parser

- docs/conf.py
The TLS cert of https://python-requests.org/ is currently broken due to a domain suspension. The non-TLS version is broken too.
See
https://github.com/psf/requests/issues/6140
Unless intersphinx gets disabled, docs tests and docs builds will fail, as it can't pull the linked docs data from requests.
Once the issue has been resolved, intersphinx can be re-enabled.
> docs: temporarily disable intersphinx

- src/streamlink/plugins/useetv.py
- tests/plugins/test_useetv.py
There are 4 types of content I have found:
* Live TV (/livetv/ URLs)
* TV replay VODs (/tvod/ URLs)
* Premium VODs (/vodpremium/ URLs)
* Event VODs (/ev/ URLs)
There appear to be 3 levels of access:
* Unrestricted
* Country restricted to Indonesia
* Country restricted to Indonesia with subscription (login required)
The main method of access control appears to be based on dynamically rendered HTML pages which either include or do not include the playlist/manifest URL.
Country restricted to Indonesia with subscription has not been tested and is therefore unsupported.  I suspect, however, that with a valid session cookie they may work, as long as they conform to a format supported in `find_url()`.
Live TV:
https://www.useetv.com/livetv/seatoday (unrestricted) …
> plugins.useetv: new plugin

- docs/conf.py
Revert of #4543
According to https://github.com/psf/requests/issues/6140#issuecomment-1135071992, requests' readthedocs should not redirect to their own domain anymore, so let's choose readthedocs as intersphinx source for requests. This should be more reliable anyway.
> docs: enable intersphinx again

- .github/workflows/lint.yml
- .github/workflows/main.yml
- .gitignore
- dev-requirements.txt
- pyproject.toml
- src/streamlink/plugin/api/websocket.py
- src/streamlink/plugins/pluzz.py
- src/streamlink/stream/dash_manifest.py
- src/streamlink/stream/hls_playlist.py
- src/streamlink/utils/l10n.py
- src/streamlink_cli/main.py
- src/streamlink_cli/utils/http_server.py
- tests/stream/test_hls_playlist.py
- tests/test_api_websocket.py
- Add mypy and available typing stubs to dev-requirements
- Add mypy config
- Add py.typed to streamlink + streamlink_cli packages (PEP 561):
This is required, so that mypy can import types from streamlink when
installed in editable mode. Don't publish this file for now.
Once various streamlink APIs are properly typed, typing stub files
can be added instead.
----
Follow-up of #4538.
This doesn't add mypy to the CI (yet), but it defines its config, so it can be run locally without yielding typing errors.
In #4538 I had the `ignore_missing_imports` option set to true, but this is now set to false and import errors are fixed by adding typing stubs of supported dependencies to `dev-requirements.txt`, and adding `py.typed` ([PEP 561](https://peps.python.org/pep-0561/)) to `streamlink` and …
> Add mypy config

- src/streamlink/plugins/useetv.py
closes #4547 
```
$ streamlink --http-proxy 'socks5h://localhost:1920' 'https://www.useetv.com/livetv/dwtv'
[cli][info] Found matching plugin useetv for URL https://www.useetv.com/livetv/dwtv
[plugins.useetv][error] The content is not available in your region
error: No playable streams found on this URL: https://www.useetv.com/livetv/dwtv
```
```
$ streamlink --http-proxy 'socks5h://localhost:1920' 'https://www.useetv.com/livetv/seatoday'
[cli][info] Found matching plugin useetv for URL https://www.useetv.com/livetv/seatoday
Available streams: 270p (worst), 360p, 540p, 720p, 1080p (best)
```
> plugins.useetv: geo+subscription error messages

- src/streamlink/plugins/raiplay.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/hls_playlist.py
- Accept both `str` and `requests.Response` in `M3U8Parser.parse`
- Always set encoding of variant and media HLS playlists to utf-8
https://datatracker.ietf.org/doc/html/rfc8216#section-9
- Remove old custom utf-8 overrides
----
Passing the HTTP Response object to the parser and iterating its content prevents having to keep a copy of the entire response content in memory. Support for `str` is kept for backwards compatibility and because some tests rely on it and would need to get rewritten.
The content is now also always read as UTF-8, as defined by RFC 8216. This was previously guessed by `chardet`/`charset_normalizer` if no HTTP response headers were set (see #4329) and it required custom overrides if there were issues while figuring out the unknown encodings. All HLS tests have been …
> stream.hls: parse M3U8 from Response obj directly

- src/streamlink/plugins/nicolive.py
fixes #4539
The `user_session` cookie already gets set in certain regions, so there's no need to check for a confirmation code.
Tested with local German IP and Japanese proxy, using a fresh account.
----
@cddb222 could you please confirm that this is working for you?
Download the plugin file and sideload it
https://streamlink.github.io/cli/plugin-sideloading.html
https://raw.githubusercontent.com/bastimeyer/streamlink/958c42e028160cfdb7f2bedc9cfced414ac63000/src/streamlink/plugins/nicolive.py
> plugins.nicolive: fix email logins

- src/streamlink/plugin/api/useragents.py
Maybe worth popping this into 4.1.0.
All these were taken from the various sub-pages at: https://www.whatismybrowser.com/guides/the-latest-user-agent/
> plugin.api: update useragents

- src/streamlink/plugins/ltv_lsm_lv.py
- src/streamlink/plugins/twitch.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls.py
- Move `M3U8Parser.base_uri` to `M3U8.uri`
- Add `multivariant` to `{,Muxed}HLSStream` and deprecate `url_master`:
- Set `multivariant` in `HLSStream.parse_variant_playlist` instead of
`url_master`, so that stream instances can keep a reference of
their parsed multivariant playlist.
This is required for implementing the `EXT-X-SESSION-{DATA,KEY}`
HLS tags, or for accessing custom tags in HLS subclasses.
- Update `to_manifest_url`
TODO: rename method / refactor interface
- Fix subclasses in various plugins
----
The `url_master` parameter was not removed from `{,Muxed}HLSStream` for backwards compatibility reasons. This can be done later when other HLS method signatures get changed in the future.
Instead of "master", I chose the name "multivariant", because that's how master playlists will …
> stream.hls: cache parsed multivariant playlist

- src/streamlink/stream/hls.py
This will make it easier to override HLS playlist fetching behavior.
In the past, we've added `HLSStream._get_variant_playlist` for overriding the parsing of variant playlists and `HLSStreamWorker._reload_playlist` for overriding the parsing of media playlists. Playlist-fetching however could not be customized, so plugins like FilmOn for example subclassed the worker class and [redefined the whole `reload_playlist` method, which is pretty bad](https://github.com/streamlink/streamlink/blob/7cb0ebe96f659f3eeb7b36e58eb545cd2cb9894c/src/streamlink/plugins/filmon.py#L25-L75), because regular HLSStreamWorker changes would also need to be applied there.
I will open a PR with a rewrite of the FilmOn plugin based on the changes of this PR later.
Other plugins with URL-refreshing logic all do that …
> stream.hls: add methods for fetching playlists

- src/streamlink/plugins/aloula.py
I looked at the full login; it does look to be a bit of a PITA, plus there's the multi profiles within the account thing, so did not seem worthwhile.  This just updates the message to be a bit more precise about what is needed.
> plugins.aloula: update login required message

- src/streamlink/plugins/filmon.py
- tests/plugins/test_filmon.py
- Rewrite FilmOnHLS{,Worker}
- Override fetching logic of HLSStreamWorker._fetch_playlist
- Rewrite playlist URL refresh logic and move everything to the
FilmOnHLSStream.url property
- Clean up FilmOnAPI and schemas
- Clean up FilmOn plugin class
- Move http adapter definitions to constructor
- Set hls-playlist-reload-time to "segment"
- Clean up _get_streams
- Fix tests
----
No idea why the channel ID caching was implemented, but I kept it.
Reducing the HLS playlist reload time seemed to be necessary to not cause any issues when updating the playlist URL. Otherwise, segments were missing sometimes, leading to discontinuities in the stream. This could still be the case though, not sure, but it's an improvement compared to the old implementation.
Also not sure how relevant the 403 and 502 …
> plugins.filmon: rewrite plugin

- setup.cfg
- src/streamlink_cli/compat.py
- src/streamlink_cli/main.py
- tests/test_cli_main.py
- Require importlib-metadata as fallback on Python < 3.8
- Add importlib_metadata to streamlink_cli.compat
- List all dependencies in `log_current_versions`
- Update tests
----
All of Streamlink's dependencies should be listed in the debug output. This is especially useful for figuring out issues like #4562.
```
$ streamlink -l debug
[cli][debug] OS:         Linux-5.18.1-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.1.0+7.g0b539fd1
[cli][debug]  lxml: 4.9.0
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  requests: 2.27.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug] …
```
> cli: list all dependencies in debug output

- src/streamlink/plugins/mediavitrina.py
- tests/plugins/test_mediavitrina.py
- remove URL of invalid/protected website
- use v3 api, instead of v2
```
$ streamlink https://player.mediavitrina.ru/gpm_matchtv_v2/matchtv/smotrim_web/6116305cba71a/player.html
[cli][info] Found matching plugin mediavitrina for URL https://player.mediavitrina.ru/gpm_matchtv_v2/matchtv/smotrim_web/6116305cba71a/player.html
[cli][info] Available streams: 360p_390k (worst), 720p_1400k, 1080p_6300k (best)
[cli][info] Opening stream: 1080p_6300k (hls)
```
> plugins.mediavitrina: fix invalid url_json

- docs/install.rst
Resolves #4579 
- https://github.com/streamlink/windows-builds
- https://github.com/streamlink/windows-builds/blob/master/CHANGELOG.md#410-3-2022-06-11
----
This removes beardypig's portable builds from the docs, reformats the windows binaries section and it updates the links/anchors at the top (the sub-sections got renamed).
> docs: update windows binaries section

- src/streamlink/plugins/pandalive.py
Updates pandalive for usernames, rather than numeric IDs.  Fixes validation of streams that are no longer online or not available.
Before:
```
$ streamlink https://www.pandalive.co.kr/live/play/csp1208
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/csp1208
error: No playable streams found on this URL: https://www.pandalive.co.kr/live/play/csp1208
```
After (online):
```
$ streamlink https://www.pandalive.co.kr/live/play/csp1208
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/csp1208
[plugins.pandalive][info] Broadcast type: live
Available streams: 160p (worst), 360p, 480p, 720p (best)
```
After (not online):
```
$ streamlink https://www.pandalive.co.kr/live/play/bar3ie
[cli][info] Found matching plugin …
```
> plugins.pandalive: update/fix

- src/streamlink_cli/main.py
- tests/test_cli_main.py
Fixes #4589 
`console.exit(msg)` requires a `str` parameter, otherwise it'll try to serialize the unknown input type as JSON if `args.json` is True, which can fail:
https://github.com/streamlink/streamlink/blob/2a5b71fa76c538ad0d3ab82492f558514d9b24a0/src/streamlink_cli/console.py#L89-L95
As already said in other threads, the ConsoleOutput usage and handling of console.exit() is pretty bad and needs to be rewritten.
----
> cli: fix pluginerror in handle_url if json is True

- docs/install.rst
Forgot to include that in #4581
> docs: remove windows portable maintainer note

- docs/install.rst
The openSUSE package had not been updated in a while until a few days ago.
Some package builds for some repos seem to be scheduled still, eg. for tumbleweed x86_64, and leap doesn't seem to be available at all, but that doesn't mean that the package shouldn't be added to the install docs.
> docs: add openSUSE package

- dev-requirements.txt
- docs-requirements.txt
- pyproject.toml
and update deprecated version format strings:
https://github.com/jwodder/versioningit/blob/v2.0.0/CHANGELOG.md
----
Please note that everyone who's installed streamlink in "editable" mode (`pip install -e .`) will need to update versioningit (`pip install -U --upgrade-strategy=eager -r dev-requirements.txt`), as it's not defined as a runtime dependency, only as a build dependency in the isolated build environment where the static version string gets set when building.
> build: upgrade versioningit to >=2.0.0, <3

- src/streamlink/plugin/api/websocket.py
- src/streamlink/plugins/twitcasting.py
- tests/test_api_websocket.py
Fixes #4604 
See
https://github.com/websocket-client/websocket-client/blob/v1.3.2/websocket/_app.py#L345-L369
Two commits:
1. Fix typing in WebsocketClient and export opcodes for easier access in subclasses
2. Fix twitcasting plugin and make sure to always write bytes to the stream buffer
> Fix websocket typing, fix twitcasting plugin

- docs-requirements.txt
- docs/_static/styles/custom.css
- docs/conf.py
This updates the furo theme to the latest version and adds an edit button and scroll-to-top button. Except for some minor details, everything should stay the same, but please check thoroughly before merging.
Noticeable changes
- CLI arguments and API reference are displayed much clearer
- Code highlighting colors are different
- Some tables don't define a colgroup anymore and have thus different sizes
----
This also replaces recommonmark (abandoned project) with myst-parser for parsing markdown (changelog). No differences here.
And sphinx gets set to `>=4.0.0`, which was already a requirement of the previously used version of furo. Sphinx 5.0.0 does not have any interesting changes, and both furo and myst-parser require at least 4.0.0. We've been using the latest version the whole time, …
> docs: update dependencies

- docs/install.rst
The docs should link to the package's page on brew.sh, not to the package build instructions in the git repo on github.
> docs: update homebrew package link

- docs/ext_argparse.py
- src/streamlink/plugins/schoolism.py
- src/streamlink_cli/argparser.py
Hi!
e8f01855ddf2c8dca59fa9c2bb253cb2f93471a0 :
> > <p>Defaults is 1.</p>
> 
> > <p>Default is: <strong>1</strong>.</p>
449b0122b29732ff49bf37599bbfd919358c250a :
> > <p>When using -o or -r, always write to file even if it already exists (overwrite).</p>
> 
> > <p>When using <a class="reference internal" href="#cmdoption-output"><code class="xref std std-option docutils literal notranslate"><span class="pre">--output</span></code></a> or <a class="reference internal" href="#cmdoption-record"><code class="xref std std-option docutils literal notranslate"><span class="pre">--record</span></code></a>, always write to file even if it already exists (overwrite).</p>
> > <p>When using -o or -r, show the download progress bar even if there is no terminal.</p>
> 
> > <p>When using <a …
> docs: apply bold style to a default value; create more links for cross-references

- src/streamlink/stream/ffmpegmux.py
Resolves #3137
The `FFMPEGMuxer` was closing its substreams sequentially, which is bad when closing a substream takes a bit of time. This is especially the case now that the [`SegmentedStreamReader` waits for its worker and writer threads to terminate](https://github.com/streamlink/streamlink/blame/ad8cf544236a420808111efeec6122d8a41467e5/src/streamlink/stream/segmented.py#L232-L235).
DASH streams need #4630 to be merged in order to close without any unnecessary additional delay.
One issue still remains though, and that is that HTTP requests don't get cancelled when a segmented stream gets closed, so if a segmented stream (eg. one of the substreams of a muxed stream) still has ongoing HTTP requests, then these need to finish first because the [`SegmentedStreamWriter` waits for all of its …
> stream.ffmpegmux: close sub-streams concurrently

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- src/streamlink/stream/segmented.py
- tests/stream/test_dash.py
Resolves #4311
This replaces the `time.sleep()` calls made by the `DASHStreamWorker` thread and threads of the `DASHStreamWriter` thread pool with `threading.Event.wait()` calls, so that the execution of those threads can be stopped immediately when the stream gets closed.
----
1. Refactor `SegmentedStream{Worker,Writer}` and add a common `wait()` method via the `AwaitableMixin`.
Not sure if this is a fitting name. Any better suggestions?
2. Refactor `DASHStreamWorker` tests. Not strictly necessary, but one test needed to be parametrized, because it was testing two things without resetting its state. Parametrizing while also patching via unittest.mock doesn't work via decorators, so the whole test needed to be rewritten either way.
3. Remove `time.sleep()` from …
> stream.dash: remove time.sleep() calls

- docs/deprecations.rst
- src/streamlink/stream/hls.py
- tests/stream/test_hls.py
with backwards compatibility for the deprecated url_master parameter,
and read the value from the parsed multivariant playlist instead, if it
exists.
See 7cb0ebe96f65
----
Backwards compatibility for #4568, when custom user plugins or users of Streamlink's Python API are accessing an HLSStream's master playlist URL.
Tests for MuxedHLSStream were not added, because I didn't want it to be repetitive and I didn't want to rewrite the test class because of that.
> stream.hls: turn url_master into property

- CHANGELOG.md
Preliminary changelog with the release date set for tomorrow, but as usual, nothing is set in stone here.
Please check for any mistakes or if something important is missing.
There are still a few PRs/issues open, so it might make sense waiting a bit more.
----
Regarding the changes of #4568, the `url_master` parameter of `HLSStream` and `MuxedHLSStream` was deprecated in favor of `multivariant`, but no proper deprecation was added to the docs, and only the parameter docstrings were updated. Is that something you think should be added to the doc's deprecations page?
> release: 4.2.0

- .github/workflows/main.yml
#4639 
The *should* resolve pushed tags being ignored by GH actions.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-branches-or-tags-for-push-events
> If you define only tags/tags-ignore or only branches/branches-ignore, the workflow won't run for events affecting the undefined Git ref. If you define neither tags/tags-ignore or branches/branches-ignore, the workflow will run for events affecting either branches or tags.
----
I have deleted the `4.2.0` tag pushed by @gravyboat as well as mine. Once this is merged, I will re-tag. No need for a 4.2.1 release.
> ci: fix push filter ignoring tags

- .github/workflows/main.yml
https://github.com/actions/setup-python#available-versions-of-python
----
3.11 release schedule:
https://peps.python.org/pep-0664/
Release might be delayed though:
https://mail.python.org/archives/list/python-dev@python.org/thread/3JWVCSBPBFWY5ZWSJ7RYB6FS5NIMCEOY/?sort=thread
> ci: add cpython 3.11-dev test runners

- netlify.toml
Trying to fix the incorrect version number on netlify preview builds.
~~Don't merge yet. I need to see the git remotes first. According to support forum threads, they have some weird caching and build setup in regards to git repos, and apparently no remotes at all are defined.~~
If that's the case (will see after the initial push in the build logs), I will fetch explicitly from the GH repo.
> ci: fix git fetch in netlify build config

- docs/ext_argparse.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/plugins/test_funimationnow.py
- tests/plugins/test_ustreamtv.py
- tests/test_options.py
- Use a custom mapping of parent->child argument group relations
instead of calling `group.add_argument_group()` for creating
a tree structure of argument groups (deprecated in Python 3.11)
- Override `parser.add_argument_group()` and add the `parent` keyword
argument to nested group defintions
- Update custom `--help` format output
- Update the argparser Sphinx extension
- Fix tests
----
Resolves #4648 
Help text stays the same, and so do the docs (see the preview build).
```sh
$ diff \
<(~/venv/streamlink-310/bin/streamlink --help) \
<(~/venv/streamlink-311/bin/streamlink --help)
$ echo $?
0
```
> cli: refactor nested argparse argument groups

- src/streamlink/plugins/vidio.py
The `referer` header needs to be an exact match, otherwise it'll return HTTP status 403 on DASH stream manifest requests.
https://github.com/streamlink/streamlink/issues/4640#issuecomment-1182772500
> plugins.vidio: fix referer HTTP header

- src/streamlink/utils/l10n.py
- tests/utils/test_l10n.py
Replace `locale.getdefaultlocale()` with `locale.getlocale()`, as it's
deprecated since Python 3.11.
Also rewrite and add more tests.
----
- https://bugs.python.org/issue46659
- https://docs.python.org/3.11/library/locale.html#locale.getdefaultlocale
- https://github.com/python/cpython/blame/3.11/Lib/locale.py#L534-L609
----
No changes compared to master:
```bash
streamlink -l debug hls://file:///dev/null | grep utils.l10n
env LC_ALL=de_DE.UTF-8 streamlink -l debug hls://file:///dev/null | grep utils.l10n
[utils.l10n][debug] Language code: de_DE
env LC_CTYPE=de_DE.UTF-8 streamlink -l debug hls://file:///dev/null | grep utils.l10n
[utils.l10n][debug] Language code: de_DE
env LANG=de_DE.UTF-8 streamlink -l debug hls://file:///dev/null | grep …
```
> utils.l10n: switch to locale.getlocale()

- docs/ext_argparse.py
- src/streamlink/plugins/nicolive.py
- src/streamlink/plugins/twitch.py
- src/streamlink_cli/argparser.py
Hi! This PR contains the re-implement of 1e12d02ba922e936d342d86848b34de5623b95c1 in #4618 . The comparison are as follows.
Commit: cfe5b418c4add84e38f466167ddea27d8cc1f96c
Original:
> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-niconico-timeshift-offset">
> <span class="sig-name descname"><span class="pre">--niconico-timeshift-offset</span></span><span class="sig-prename descclassname"> <span class="pre">[HH:]MM:SS</span></span><a class="headerlink" href="#cmdoption-niconico-timeshift-offset" title="Permalink to this definition">#</a></dt>
> <dd><p>Amount of time to skip from the beginning of a stream. Default is 00:00:00.</p>
> </dd></dl>
New:
> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-niconico-timeshift-offset">
> <span …
> docs: tweak CLI argument help texts

- src/streamlink/stream/ffmpegmux.py
- tests/stream/test_ffmpegmux.py
- Remove redundant commands with `.exe` suffixes.
`shutil.which` will pick those up via `PATHEXT` on Windows.
- Move executable lookup to `FFMPEGMuxer.resolve_command`, so its inputs
and return values can be cached using `functools.lru_cache` without
relying on a Streamlink session instance as input
- Keep interface of `FFMPEGMuxer.is_usable` and `FFMPEGMuxer.command`
- Add proper tests
----
`FFMPEGMuxer.is_usable` currently doesn't get cached, which means that when generating a list of `MuxedHLSStream`s for example, `ffmpeg` will get looked up every single time, and additionally when a the stream gets opened.
- https://github.com/streamlink/streamlink/blob/4.2.0/src/streamlink/stream/hls.py#L748
- https://github.com/streamlink/streamlink/blob/4.2.0/src/streamlink/stream/ffmpegmux.py#L119 …
> stream.ffmpegmux: cache executable lookups

- src/streamlink/plugins/nbcnews.py
Closes #4664 
Cleanup of the issues mentioned in my review of #4664, with a plugin rewrite
```
$ streamlink -l debug nbcnews.com/now
[cli][debug] OS:         Linux-5.18.11-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.2.0+15.g20db6378
[cli][debug]  lxml: 4.9.0
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  url=nbcnews.com/now
[cli][info] Found matching plugin nbcnews for URL nbcnews.com/now
[plugins.nbcnews][debug] API ID: 2007524
Available …
```
> plugins.nbcnews: fix plugin

- tests/stream/test_ffmpegmux.py
Follow-up of #4660 
This replaces the very repetitive tests of the ffmpegmuxer with parametrized tests, as the setup is exactly the same everywhere. Also some minor adjustments of the tests added in #4660, as the test fixtures could be improved and shared between the newly added tests.
Second commit adds tests for `--ffmpeg-verbose` and `--ffmpeg-verbose-path`. That's mainly just a coverage improvement though.
> stream.ffmpegmux: rewrite tests

- docs/install.rst
I can't remember when I renamed the `windows-installer` repo to `windows-builds`, but this change should've probably been included in #4581. GitHub automatically redirects from old repo names, but the links should still be fixed in the docs.
> docs: fix windows-builds repo links

- src/streamlink/plugins/livestream.py
- tests/plugins/test_livestream.py
Closes #4557
Reviewing/annotating the changes of #4557 and fixing them step-by-step would take too long.
All the different URL types listed in the tests should be working. This includes the protected/hidden example stream URL mentioned in #4557.
> plugins.livestream: rewrite and fix plugin

- src/streamlink/compat.py
- src/streamlink/utils/named_pipe.py
- src/streamlink_cli/compat.py
- src/streamlink_cli/constants.py
- src/streamlink_cli/main.py
- src/streamlink_cli/output.py
- src/streamlink_cli/utils/path.py
- src/streamlink_cli/utils/terminal.py
- tests/test_cli_main.py
- tests/test_cmdline.py
- tests/test_cmdline_player_fifo.py
- tests/test_cmdline_title.py
- tests/utils/test_named_pipe.py
- Move `is_darwin` from `streamlink_cli.compat` to `streamlink.compat`
- Remove `is_win32` from `streamlink_cli.compat`
- Replace last remaining `unittest.skipIf` test decorators with the
`posix_only`/`windows_only` pytest decorators from the `tests` module
- Remove `is_win32` check when importing from `ctypes` in `named_pipe`
> refactor: is_darwin/is_win32 compat exports

- docs/install.rst
Closes #4670 
Since nobody has had anything to comment about my suggested removal of dead packages from the install docs, I'm just going to submit a PR.
Please see the rendered docs fist. I've tried to be as precise and short as possible in the added notes. I don't mind rewriting/improving it though.
The removals are done in separate commits, in case we want to revert this later on, should the package maintainers start maintaining the packages again.
> docs: remove dead packages and add package availability notes

- src/streamlink/plugins/huya.py
- tests/plugins/test_huya.py
Resolves #4684 
I've once again tried adding HLSStreams instead of having the plugin yield progressive HTTPStreams (see https://github.com/streamlink/streamlink/issues/4609#issuecomment-1159697918), but to no luck. Server response 403 using the same URL logic as the HTTP "FLV" streams.
The issue from the report in #4684 was stream data sometimes not being base64 encoded, so a different regex and validation logic was needed. Because of this, I rewrote and cleaned up the entire plugin in one go, and also added stream metadata.
```
$ streamlink -l debug 'https://www.huya.com/688062'
[cli][debug] OS:         Linux-5.18.14-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.2.0+26.gad51118e
[cli][debug] …
```
> plugins.huya: rewrite and fix plugin

- src/streamlink/stream/ffmpegmux.py
- tests/stream/test_ffmpegmux.py
`--ffmpeg-verbose-path=~/ffmpeg.log` should be properly expanded to the user's home directory. This is currently not the case.
> stream.ffmpegmux: expand user in verbose-path

- .github/release_template.md
The release message body still includes the outdated `streamlink/windows-installer` repo name and link.
The download and configuration secions could also be worded better, so let's change it.
We can remove the Windows installers warning again in a couple of releases/months.
> chore: update GitHub release message body

- src/streamlink/plugins/atpchallenger.py
- tests/plugins/test_atpchallenger.py
Hi team,
This change implements one of the plugin I proposed in this issue: https://github.com/streamlink/streamlink/issues/4693. This plugin enables streamlink to scrap livestream from https://www.atptour.com/en/atp-challenger-tour/challenger-tv. 
For testing, I locally run the tests described here: https://streamlink.github.io/latest/developing.html#validating-changes
Thanks,
Yu
> plugins.atpchallenger: new plugin

- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugin/api/validate/_schemas.py
- src/streamlink/plugin/api/validate/_validate.py
- tests/test_api_validate.py
This adds new schema validation methods that are useful for commonly used patterns.
The list instance validation schema (eg. `[int, str]`) only validates a subset of the input, which means it defines any items that can match. This is often not what plugin authors have in mind when trying to validate a list where each indexed item needs to be validated.
The `ListSchema` (via `validate.list(...)`) on the other hand therefore checks for equal length of the input list and then validates each item according to the schema.
Instead of having to define the `validate.transform(re.compile(...).search)` validation pattern, a simple `re.compile(...)` is now supported, which will call the `search()` method internally and return either `None` or an instance of `re.Match`. Other methods like `findall()` …
> plugin.api.validate: ListSchema, re.Pattern and NoneOrAllSchema

- src/streamlink/plugins/ard_mediathek.py
- tests/plugins/test_ard_mediathek.py
Fixes #4687 
This doesn't fully fix the plugin, because some HLS streams (most live TV streams and some VODs) are using external [packed audio](https://www.rfc-editor.org/rfc/rfc8216.html#section-3.4) streams, which Streamlink currently does not support. Raw ADTS segments with ID3 metadata will be concatenated by Streamlink's HLS implementation and the data gets piped into FFmpeg, which it does not understand, so there's no output stream when trying to mux the video and audio streams. This is however not related to the plugin, and a separate issue needs to be opened for that.
> plugins.ard_mediathek: fix plugin

- src/streamlink/plugins/huajiao.py
- tests/plugins/test_huajiao.py
Not sure how relevant this plugin actually is. It's been using an old and long-time deprecated base64 decoding API which was removed from the standard library in 3.9, so everyone trying to open streams using those python versions would see an error, and there haven't been any plugin issue reports.
https://docs.python.org/3/whatsnew/3.9.html
> base64.encodestring() and base64.decodestring(), aliases deprecated since Python 3.1, have been removed
----
Apparently, there are also HLS URLs in the "feed" data, but I haven't seen any of those. The website does use HTTP video streams, and so does the plugin when trying to access a stream. I kept it though, just in case. And I also upgraded the plugin to HTTPS and removed the verify=false option on the session.
> plugins.huajiao: rewrite and fix plugin

- src/streamlink/plugin/api/validate/_validate.py
- tests/test_api_validate.py
See https://github.com/streamlink/streamlink/pull/4702#issuecomment-1206106699
`re.Pattern` validations should accept any kind of subclass instances of `str` or `bytes`, like [`xml.etree._ElementUnicodeResult`](https://lxml.de/api/lxml.etree._ElementUnicodeResult-class.html) for example, which is the result of XPath queries when returning an element attribute value, text or tail.
> plugin.api.validate: fix pattern input type

- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugin/api/validate/_schemas.py
- src/streamlink/plugin/api/validate/_validate.py
- tests/test_api_validate.py
Follow-up of #4691 / #4708
As mentioned in https://github.com/streamlink/streamlink/pull/4702#issue-1329216134, non-optional regexes currently don't raise useful error messages when a simple `re.Pattern` or `validate.transform(re.Pattern.search)` validation is made. The `RegexSchema` raises a `ValidationError` with a proper error message if the return value is `None`. See the added tests.
`validate.regex` (`RegexSchema`) also takes a second parameter which changes the method that's called on the compiled regex pattern. This is useful for calling `re.Pattern.findall` for example.
> plugin.api.validate: add RegexSchema

- src/streamlink/plugin/api/http_session.py
This fixes the [new typing error](https://github.com/streamlink/streamlink/runs/7702581070?check_suite_focus=true#step:5:8)
> src/streamlink/plugin/api/http_session.py:42:1: error: Cannot assign to a type  [misc]
which is caused by an upgrade of the `types-requests` package:
https://github.com/python/typeshed/commit/3e88363b34f916ab816c3f7ed5a79c1620f9deee
> plugin.api.http_session: suppress type error

- src/streamlink/plugins/picarto.py
For streams it looks like the page no longer includes the player JS used to read the stream server URL when loading the page without JS enabled. However it is included in the already existing call to the private API.
For VODs it seems to just complain about the type of the video ID.
Tested with some random streams.
Resolves #4727.
Before:
```
streamlink https://picarto.tv/Noxcuro best
[cli][info] Found matching plugin picarto for URL https://picarto.tv/Noxcuro
[plugins.picarto][error] Could not find server netloc
error: No playable streams found on this URL: https://picarto.tv/Noxcuro
#VOD
streamlink https://picarto.tv/sate/videos/681901
[cli][info] Found matching plugin picarto for URL https://picarto.tv/sate/videos/681901
error: Unable to validate response text: ValidationError(dict): …
```
> plugins.picarto: Fix streams and VODs

- src/streamlink/plugin/api/validate/_validators.py
- src/streamlink/plugins/deutschewelle.py
- src/streamlink/plugins/funimationnow.py
- src/streamlink/plugins/mdstrm.py
- src/streamlink/plugins/useetv.py
- tests/test_api_validate.py
- Add supported `Element.xpath()` keywords to `validate.xml_xpath()`
- `namespaces` for defining prefix-namespace mappings
- `extensions` for defining custom XPath functions in Python
- `smart_strings` for disabling element tree references on any string
return values that will be kept in memory
- `**variables` for being able to define custom XPath variables
instead of having to embed strings in the XPath query itself
- Add `namespaces`, `extensions` and `**variables` keywords to
`validate.xml_xpath_string()` and always disable `smart_strings`
- Add `namespaces` to `validate.xml_find()`, `validate.xml_findall()`
and `validate.xml_findtext()`
- Handle XPath evaluation errors via `lxml.etree.XPathError`
and ElementPath syntax errors via `SyntaxError`
- Update error messages of …
> plugin.api.validate: rework XML validators

- src/streamlink/plugins/cbsnews.py
- tests/plugins/test_cbsnews.py
Resolves #4742 
main news
```
$ streamlink cbsnews.com/live
[cli][info] Found matching plugin cbsnews for URL cbsnews.com/live
Available streams: 180p (worst), 360p_alt, 360p, 540p, 720p_alt, 720p (best)
```
regional news
```
$ streamlink cbsnews.com/losangeles/live
[cli][info] Found matching plugin cbsnews for URL cbsnews.com/losangeles/live
Available streams: 180p (worst), 360p_alt, 360p, 540p, 720p_alt, 720p (best)
```
sports (geo-blocked at HLS segment level, so no checks)
```
$ streamlink cbsnews.com/live/cbs-sports-hq
[cli][info] Found matching plugin cbsnews for URL cbsnews.com/live/cbs-sports-hq
Available streams: 224p (worst), 288p, 360p, 432p, 540p, 720p, 1080p (best)
```
> plugins.cbsnews: fix regex, add metadata

- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- src/streamlink/user_input.py
- src/streamlink_cli/console.py
- tests/test_plugins_input.py
- Remove `user_input_requester` from `Plugin.bind()`, don't set it in
`Session.load_plugins()` and remove `Plugin._user_input_requester`
- Make `Plugin.input_ask{,_password}` read input requester from session
- Move `UserInputRequester` to the new `streamlink.user_input` module,
turn it into an abstract base class, and update imports
- Fix docstring of `Session.set_option()`
- Rewrite tests
----
In preparation for #4744
> plugin: remove user_input_requester from bind()

- docs/ext_plugins.py
- src/streamlink/options.py
- src/streamlink/plugin/__init__.py
- src/streamlink/plugin/plugin.py
- src/streamlink/plugins/afreeca.py
- src/streamlink/plugins/bbciplayer.py
- src/streamlink/plugins/clubbingtv.py
- src/streamlink/plugins/crunchyroll.py
- src/streamlink/plugins/funimationnow.py
- src/streamlink/plugins/nicolive.py
- src/streamlink/plugins/openrectv.py
- src/streamlink/plugins/pixiv.py
- src/streamlink/plugins/rtve.py
- src/streamlink/plugins/sbscokr.py
- src/streamlink/plugins/schoolism.py
- src/streamlink/plugins/steam.py
- src/streamlink/plugins/streann.py
- src/streamlink/plugins/svtplay.py
- src/streamlink/plugins/twitcasting.py
- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/ustreamtv.py
- src/streamlink/plugins/ustvnow.py
- src/streamlink/plugins/vimeo.py
- src/streamlink/plugins/wwenetwork.py
- src/streamlink/plugins/yupptv.py
- src/streamlink/plugins/zattoo.py
- src/streamlink_cli/main.py
- tests/plugin/testplugin.py
- tests/test_cli_main.py
- tests/test_plugins.py
This PR changes the plugin argument definitions from
```py
from streamlink.plugin import Plugin, PluginArgument, PluginArguments
@pluginmatcher(...)
class Foo(Plugin):
arguments = PluginArguments(
PluginArgument(...),
PluginArgument(...),
PluginArgument(...),
)
```
to
```py
from streamlink.plugin import Plugin, pluginargument, pluginmatcher
@pluginmatcher(...)
@pluginargument(...)
@pluginargument(...)
@pluginargument(...)
class Foo(Plugin):
...
```
As mentioned in https://github.com/streamlink/streamlink/issues/4741#issue-1340972848, having plugin arguments definied in a similar declarative way as the URL matchers makes it much more consistent and easier to read. The previous definitions were all rather messy.
This also simplifies the parsing of each plugin module's AST via the plugins …
> plugin: pluginargument decorator

- src/streamlink/plugin/plugin.py
- tests/test_plugin.py
Follow-up of #4747 
The plugin arguments were covered by other tests as a side-effect. This properly adds explicit tests for both the new decorator as well as the class attribute definition style.
Also added typing information that was missing.
> plugin: add explicit pluginargument tests

- src/streamlink/plugins/mitele.py
Fixes #4726 
This refactors the plugin (mainly code style and validation schema refinements) and fixes the "Forbidden token format" issue.
The problem was how the query string with the HMAC was applied to the stream URL. Both parts are retrieved from different API calls and instead of concatenating the parts like `{url}?{querystring}`, the query string was parsed and the URL updated with the parsed query string dictionary. While updating the URL, Python automatically quotes/percent-encodes query string values, which broke the token format, hence the added `quote_via=lambda string, *_, **__: string` keyword to `update_qsd()` which simply passes through the value.
- https://github.com/streamlink/streamlink/blame/c1a14d6338a36794cb235e00e79f4faed1614776/src/streamlink/plugins/mitele.py#L93-L9 …
> plugins.mitele: fix and refactor plugin

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
Resolves #4738 
No tests, because [no tests have ever been written for `output_stream_http()`](https://app.codecov.io/gh/streamlink/streamlink/blob/master/src/streamlink_cli/main.py) or the entire [`streamlink_cli.utils.http_server` module](https://app.codecov.io/gh/streamlink/streamlink/blob/master/src/streamlink_cli/utils/http_server.py).
- https://github.com/streamlink/streamlink/blame/4.3.0/src/streamlink_cli/main.py#L164-L274
- https://github.com/streamlink/streamlink/blame/4.3.0/src/streamlink_cli/utils/http_server.py
----
There are two choices that can be made for implementing the new CLI argument:
1. The current implementation, with `--player-external-http-continuous=bool` requiring a boolean value and affecting the logic of the main argument `--player-external-http`.
The issue …
> cli: implement --player-external-http-continuous

- src/streamlink/plugins/ustreamtv.py
- tests/plugins/test_ustreamtv.py
Fixes #4753
All URLs in the rewritten URL matcher tests are working fine.
> plugins.ustreamtv: fix matcher

- src/streamlink/plugins/huya.py
Fixes the Huya plugin, closes #4762 
It appears that Huya have updated its JSON respose and changed `liveId` from `int` to `str`, which causes Streamlink to throw `ValidationError`
An example of such JSON response
```js
var TT_ROOM_DATA = {
"type": "NORMAL",
"state": "ON",
"isOn": true,
"isOff": false,
"isReplay": false,
"isPayRoom": 0,
"isSecret": 0,
"roomPayPassword": "",
"id": "2246718540",
"sid": "2246718540",
"channel": "2246718540",
"liveChannel": "2246718540",
"liveId": "7134653690594404016",
"shortChannel": 0,
"isBluRay": 1,
"gameFullName": "QQ飞车",
"gameHostName": "qqfc",
"screenType": 1,
"startTime": 1661166012,
"totalCount": 94949,
"cameraOpen": 0,
"liveCompatibleFlag": 0,
"bussType": 1,
"isPlatinum": 1,
"isAutoBitrate": 0,
"screenshot": …
```
> plugins.huya: update `liveId` to type `str`

- src/streamlink/plugins/rtve.py
Fixes #4757
See https://github.com/streamlink/streamlink/issues/4757#issuecomment-1221357795
Some content is geo-blocked, and will result in 403 HTTP requests on HLS segments.
----
Live (via new simple HLS URL requests)
```
$ streamlink https://www.rtve.es/play/videos/directo/la-1/
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/directo/la-1/
Available streams: 360p (worst), 576p, 720p (best)
$ streamlink https://www.rtve.es/play/videos/directo/canales-lineales/la-2/
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/directo/canales-lineales/la-2/
Available streams: 360p (worst), 576p, 720p, 1080p (best)
```
Documentaries and TV shows  (via old, obfuscated HLS URLs)
```
$ streamlink …
```
> plugins.rtve: fix plugin

- tests/test_options.py
Small update of the plugin arguments setup tests.
This should've been included in #4751 / #4747.
I noticed that while updating the tests for the `Plugin.bind()` removal (#4744), so these changes don't have to be included in that PR.
> tests: refactor options tests

- src/streamlink/plugins/albavision.py
- src/streamlink/plugins/hiplayer.py
- src/streamlink/plugins/htv.py
Fixes #4769 
These changes are based on the diff of #4702, where plugins and their validation schemas were refactored. In some plugins, I modified some regexes and added named capture groups for back-references of quotations, but forgot to change the index of the capture group getter. This change replaces the indexed getter with a named one, to avoid this.
----
```
$ streamlink 'https://rotana.net/live-clip'
[cli][info] Found matching plugin hiplayer for URL https://rotana.net/live-clip
Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
```
```
$ streamlink 'https://www.cnbcarabia.com/Pages/live'
[cli][info] Found matching plugin hiplayer for URL https://www.cnbcarabia.com/Pages/live
Available streams: 240p (worst), 360p, 480p, 720p (best)
```
```
$ streamlink …
```
> plugins: fix regex capture groups

- docs/api.rst
- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- Add docstrings for the `pluginmatcher` and `pluginargument` decorators
- Update typing information of `Plugin.arguments` and add docstring
- Update docstrings of `Argument` and `Arguments`
- Fix minor issue in `Arguments.requires()`
----
rel #4747
> docs: add plugin{matcher,argument} docstrings

- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugin/api/validate/_exception.py
- src/streamlink/plugin/api/validate/_validate.py
- src/streamlink/plugin/api/validate/_validators.py
- tests/test_api_validate.py
- Remove `ValidationError` from package's `__init__` module.
It was never meant to be a public export. Update tests accordingly.
- Remove `context` argument from `ValidationError` and use the
exception's `__cause__` property instead, and add the "raise from"
statements to schema validations and validators where a context was
set previously. Explicitly "raise from None" where a context should
be suppressed.
- Fix unneeded type cast when printing `ValidationError` template string
- Fix length comparison in `length` validator
> plugin.api.validate: refactor ValidationError

- src/streamlink/plugins/hiplayer.py
- tests/plugins/test_hiplayer.py
Testing Evidenc
```
~$ streamlink 'https://alwasat.ly/live' best
[cli][info] Found matching plugin hiplayer for URL https://alwasat.ly/live
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Starting player: /opt/homebrew/bin/VLC
^C[cli][info] Stream ended
Interrupted! Exiting...
~$ 
```
Testing other urls have not broken
```
~$ streamlink 'https://rotana.net/live-clip/' best
[cli][info] Found matching plugin hiplayer for URL https://rotana.net/live-clip/
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Starting player: /opt/homebrew/bin/VLC
^C[cli][info] Stream ended
Interrupted! Exiting... …
```
> plugins.hiplayer: add alwasat.ly

- src/streamlink/plugins/okru.py
- tests/plugins/test_okru.py
Resolves #4682
Reverts #4779
I removed the exception handling of the `PluginError`, because validation error messages are useful now.
----
Mobile HLS
```
$ streamlink 'https://mobile.ok.ru/live/1366902775399'
[cli][info] Found matching plugin okru for URL https://mobile.ok.ru/live/1366902775399
Available streams: 240p (worst), 360p, 480p, 720p (best)
```
Mobile HTTP
```
$ streamlink 'https://mobile.ok.ru/dk?st.cmd=movieLayer&st.groupId=70000000124591&st.discId=4242734320303&st.retLoc=top&st.rtu=%2Fdk%3Fst.cmd%3DuserMovies%26st.page%3D1%26_prevCmd%3DuserMovies%26tkn%3D8051&st.discType=GROUP_MOVIE&st.mvId=4242734320303&_prevCmd=userMovies&tkn=3276#'
[cli][info] Found matching plugin okru for URL https://mobile.ok.ru/dk?st.cmd=movieLayer&st.groupId=70000000124591&st.discId=4242734320303&st.re …
```
> plugins.okru: support mobile page

- src/streamlink/stream/ffmpegmux.py
- tests/stream/test_ffmpegmux.py
There is way too much confusion about FFmpeg and muxed streams.
The problem is that it's not transparent at all which streams are muxed and which are not. This is due to how streams get returned, as a mapping of name->stream dicts or tuples with "alt" deduplications already done by the `Stream` implementations themselves or the `plugin.streams()` method, and only names get shown by the CLI.
The HLS implementation with external audio streams is also not ideal, because it silently falls back to streams without external audio. That needs to be changed, ideally with the implementation of alternative video streams (#3579).
So in order to at least give the user some feedback, let's add warning messages when FFmpeg is not available on the system.
The warning messages get only shown once if …
> stream.ffmpegmux: show warning if unavailable

- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- src/streamlink_cli/main.py
- tests/test_cli_main.py
- tests/test_plugin.py
- tests/test_session.py
Deprecation messages should consistently get logged as warnings, to make them distinguishable from regular log messages, and to make it clear that user interactions are required.
While changing the log message channel, I experimented with switching to the `warnings` module and emitting `DeprecationWarning`s via `warnings.warn()` instead, but that would require capturing warnings in Streamlink's root logger, default warning filters would need to be changed (which I'm not sure how it would affect third party code), and in order to show warnings in a meaningful way for end-users, the resulting `LogRecord`s would need to get changed as well. This is not worth the effort for using the deprecation warnings API of the stdlib.
> logger: log deprecation messages as warnings

- src/streamlink_cli/main.py
- src/streamlink_cli/utils/versioncheck.py
- tests/cli/test_versioncheck.py
- Move to separate module (slim down main module)
- Catch and log errors
- Don't call `sys.exit()` and instead alter flow of `main.main()`
if `--version-check` is set
- Handle `KeyboardInterrupt`
- Add tests
> cli: refactor version check

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/test_argparser.py
- tests/cli/test_main.py
- Merge `setup_options()` and `setup_http_session()` and always
initialize all session options:
It doesn't make sense having this split up into two functions, just
so that some CLI functions can have a partially configured session
with just the HTTP options set
- Move merged session setup logic into the `argparser` module
and replace the dozens of if-statements and `session.set_option()`
calls with a list of "CLI argument -> session option" mappings
- Add tests and update `streamlink_cli.main` tests respectively
> cli: refactor setup of session options

- src/streamlink_cli/main.py
- src/streamlink_cli/output.py
- src/streamlink_cli/utils/__init__.py
and replace it with `contextlib.suppress`
----
Available since Python 3.4
https://docs.python.org/3/library/contextlib.html#contextlib.suppress
> cli: remove custom `ignored` contextmanager

- src/streamlink/plugin/api/http_session.py
- src/streamlink/session.py
- tests/test_session.py
The `parse_{cookies,headers,query_params}` methods were added when the
subclass of `requests.Session` was implemented in order to support
setting cookies, headers and query parameters via `k1=v1;k2=v2` strings
(in addition to key-value dicts) via the session API and via the CLI:
- 936e66dd90f67377451be27951a7d5553a09088c
- c6e54fd57a71a90bbbbdad0508ac1615ccb9ac65
Since these methods implement logic purely for the `Streamlink` session
interface and are not meant to be called by any plugin or stream
implementations which use the session's `HTTPSession` instance, they
should be removed. Cookies, headers and query string parameters should
be set directly on their respective `HTTPSession` attributes:
- `cookies`: instance of `requests.cookies.RequestsCookieJar`
- `headers`: instance of …
> plugin.api.http_session: remove parse_* methods

- setup.cfg
This adds official support for the upcoming Python 3.11 release in October (unless it gets delayed - RC2 already is).
Python 3.11 deprecations in the stdlib have already been fixed:
- #4651
- #4654
and dependency-wise, I haven't noticed any problems apart from `lxml` still only having released pre-built `cp311` wheels for `musllinux_1_1`, `manylinux_2014_x86_64` and `manylinux_2010_i686`, so other platforms will have to build from source with libxml2 and libxslt being installed, but that will get resolved hopefully soon:
- https://pypi.org/project/lxml/4.9.1/#files
- https://bugs.launchpad.net/lxml/+bug/1977998
> build: add Python 3.11 to package classifiers

- script/install-dependencies.sh
See https://github.com/streamlink/streamlink/pull/4806#issue-1364468477
That will make the tests on Windows with Python 3.11 pass... As soon as lxml has published official wheels, we can remove it again.
The wheel is not intended for any end users, just for the CI.
Its build config can be found here:
https://github.com/streamlink/temp-wheel-for-lxml-cp311-win-amd64/blob/lxml-4.9.1-1/.github/workflows/main.yml
> ci: install custom lxml wheel on cp311 win-amd64

- dev-requirements.txt
- setup.cfg
- src/streamlink/plugin/api/http_session.pyi
- src/streamlink/plugin/plugin.py
- Add typing information to `Plugin.session`
- Implement `http_session` stub file due to the `HTTPSession` subclass
of `requests.Session` which adds additional keywords to the
`request()` method, including all other HTTP-verb methods
- Add `flake8-pyi` and `typing_extensions` to dev-requirements.txt
(`typing_extensions` is not a runtime dependency)
----
With the removal of the `Plugin.bind()` classmethod in #4768, now that the `Streamlink` session instance gets set on each `Plugin` instance, typing information can finally be added, as the `session` attribute doesn't have to be defined as `None` anymore initially.
Adding typing informations finally allows plugin implementors to see all the stuff that's defined on the `Session`, including the `HTTPSession` via `self.session.http`. However, …
> plugin: add session typing information

- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/ustreamtv.py
- src/streamlink/stream/dash.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/http.py
- src/streamlink/stream/segmented.py
- src/streamlink/stream/stream.py
- tests/mixins/stream_hls.py
- Add typing information to `Stream`
- Explicitly set the stream, reader, worker and writer types
- Fix minor typing issues
----
Follow-up of #4802, which was a requirement for being able to add session typing information to the stream classes.
Some typing definitions are redundant, but since some are not, I chose setting all of them explicitly, to make it more consistent.
The stream classes which I didn't touch are either untyped or don't require any changes. And the other changes are minor typing fixes, removals of redundant stuff (duplicate `self.stream = self.reader.stream`) and updates of legacy py2 code (`super()` calls).
> stream: add session typing information

- src/streamlink/plugins/cinergroup.py
Showtvcomtr is not opened when self._schema_data_ht is ahead. Showturk is opened.
I had already been trying to fix that issue in previous branch.
> plugins.cinergroup: fix showtvcomtr

- src/streamlink/plugins/tv3cat.py
- tests/plugins/test_tv3cat.py
Simple plugin rewrite and cleanup, similar to the dailymotion plugin cleanup.
This also updates the version of the API requests.
Geo-block status could be checked via XPath, but it's not worth it considering that the site's frontend can change at any time.
Not entirely sure how useful the stream fallbacks are, because, as you can see down below, the streams are still blocked even with fallback. It's possible though that this still works in a different region. Btw, the old implementation was trying to catch the wrong exception.
----
Non-geo-blocked streams (TV3 and 324)
```
$ streamlink https://www.ccma.cat/tv3/directe/tv3/ best
[cli][info] Found matching plugin tv3cat for URL https://www.ccma.cat/tv3/directe/tv3/
[plugins.tv3cat][info] Accessing stream from region TOTS
[cli][info] …
```
> plugins.tv3cat: rewrite

- src/streamlink/plugins/linelive.py
- tests/plugins/test_linelive.py
Simple plugin rewrite and cleanup, similar to the dailymotion plugin cleanup.
Live:
```
$ streamlink https://live.line.me/channels/4912891/broadcast/20864925
[cli][info] Found matching plugin linelive for URL https://live.line.me/channels/4912891/broadcast/20864925
Available streams: 256p (worst), 426p, 640p, 854p, 1280p (best)
```
VOD
```
$ streamlink https://live.line.me/channels/5677886/broadcast/19532126
[cli][info] Found matching plugin linelive for URL https://live.line.me/channels/5677886/broadcast/19532126
Available streams: 640p (worst), 854p, 1280p (best)
```
> plugins.linelive: rewrite

- src/streamlink/stream/ffmpegmux.py
- tests/stream/test_ffmpegmux.py
The [libav](https://en.wikipedia.org/wiki/Libav) (avconv) fork of FFmpeg has been abandoned since several years with its last release in February 2018. There is no reason to still support it. Everyone who's switched to libav in 2011 has switched back to FFmpeg years ago. The only popular Linux distros which default to libav are outdated Debian releases (Jessie) and forks of it (Ubuntu 14). Debian's Stretch release switched back to FFmpeg in 2017 (announced in 2015).
- https://packages.debian.org/search?suite=stretch&arch=any&mode=exactfilename&searchon=contents&keywords=avconv
- https://packages.debian.org/stretch/libav-tools
- https://lists.debian.org/debian-devel-announce/2015/07/msg00001.html
- https://en.wikipedia.org/wiki/Debian_version_history#Release_table
- …
> stream.ffmpegmux: remove avconv

- src/streamlink_cli/utils/progress.py
- tests/cli/utils/test_progress.py
Fixes #4829 
See https://github.com/streamlink/streamlink/issues/4829#issuecomment-1250047704
Relative paths on Windows accidentally cut off the first part of the `path.parts` property when no `path.drive` was set.
> cli.utils.progress: fix relative Windows paths

- src/streamlink/plugins/rtve.py
- tests/plugins/test_rtve.py
Fixes #4838
As mentioned in https://github.com/streamlink/streamlink/issues/4838#issuecomment-1252536683, it's possible (very likely) that the whole embedded and obfuscated stream URL data extraction is useless now. Since I'm not fully sure, I've kept it for now. I've also wrapped the HTTP request which retrieves the obfuscated data into a try-except block, so that if the site removes the endpoint, the plugin will continue working with the generic HLS URL template.
I only tested the URLs listed in the URL matcher tests. The site is also geo-blocked (on the HLS playlist level), so I can't fully test it anyway. The main issue however should be fixed (the old while-loop - see https://github.com/streamlink/streamlink/issues/4838#issuecomment-1252528944).
@jairoxyz I would appreciate it if you …
> plugins.rtve: fix ZTNR.translate

- src/streamlink/plugin/api/http_session.pyi
This typeshed update has broken type validation:
https://github.com/python/typeshed/commit/b3db49abbd563a8543783fcd2b4d6765b32812b0
> plugin.api.http_session: update and fix typing

- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/useragents.yml
Some GitHub workflow actions are outdated and are running on NodeJS 12, which will soon be deprecated:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
This bumps all external actions (we're not using any internal ones) to the latest version:
- `actions/checkout@v3`
https://github.com/actions/checkout/releases
- `actions/setup-python@v4`
https://github.com/actions/setup-python/releases
- `codecov/codecov-action@v3`
https://github.com/codecov/codecov-action/releases
- `peter-evans/create-pull-request@3f9dbd5a76a3cb3e1d94af1115652b322e3a198c`
Using an explicit commit ID because the action has write permissions
https://github.com/peter-evans/create-pull-request/releases
> ci.github: bump actions to latest version

- src/streamlink/plugins/vinhlongtv.py
- tests/plugins/test_vinhlongtv.py
Closes #4848 
This updates the API URL and adds the required request headers and timezone query string parameter.
As mentioned in #4848, the `timezone` query string parameter on the site is read from
```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```
which means it'll always be in the `$Region/$City` format. The plugin implementation however sets the timezone parameter to the `UTC` string, because it needs the UTC timezone for calculating the MD5 hash in the headers, which depends on the user's local time, and this needs to be calculated based on UTC. Otherwise, we'd need to get the timezone name from the user's local time, and that would require adding `pytz` as a dependency here, because the provided timezone parameter must match. I am not sure though how reliable setting the …
> plugins.vinhlongtv: rewrite and fix plugin

- src/streamlink/plugin/plugin.py
The `@Plugin.broken` has been unused for a while now and the last time that any plugins were annotated as broken was two years ago. The latest commits with diffs that contained the decorator were either plugin removals or plugin fixes.
```
$ git log --format='%h %cI %s (%an)' -S '@Plugin.broken'
0a3f65a2 2021-03-20T22:49:16+01:00 plugins.btsports: remove plugin (back-to)
2c8f46ba 2020-10-31T18:28:34+01:00 plugins.nbcnews: fix video ID search, add schemas (Ian Cameron)
0aaeb19b 2020-10-31T18:19:40+01:00 plugins.ellobo: plugin removal (Ian Cameron)
f25f2dd1 2020-10-31T18:15:19+01:00 plugins.cnews: fix video ID search, add schema (Ian Cameron)
500c5c4a 2020-10-31T12:45:08+01:00 plugins.kingkong: plugin removal (Ian Cameron)
e2aa85d4 2020-10-31T08:44:44+01:00 plugins.skai: plugin removal (Ian …
```
> plugin: remove broken decorator

- src/streamlink/plugin/plugin.py
With the addition of the `@pluginargument` decorator in #4747, the initial `Plugin.arguments` value was changed from sharing a common `Arguments()` instance with all plugins that don't define any plugin arguments to `None`:
https://github.com/streamlink/streamlink/pull/4747/files#diff-6c2b818d0eb96fa625a2ff3f5da29b40a1867d6e34a58c730a0972e79c07c99dR197
The `Plugin.get_argument()` method needs to be fixed in regards to this. The method is not used and not tested, so this slipped through.
----
Btw, the [`Plugin.options` attribute is still sharing a common `Options()` instance](https://github.com/streamlink/streamlink/blob/5.0.1/src/streamlink/plugin/plugin.py#L233) (`Plugin.get_option()` and `Plugin.set_option()` are related to this PR here). Individual `Options()` instances get set by the …
> plugin: fix get_argument()

- dev-requirements.txt
- src/streamlink/session.py
- src/streamlink/stream/ffmpegmux.py
- src/streamlink/utils/processoutput.py
- src/streamlink_cli/argparser.py
- tests/stream/test_ffmpegmux.py
- tests/utils/test_processoutput.py
Recently, warning messages were added to the `FFMPEGMuxer` if muxing streams is unavailable because FFmpeg could not be found on the user's system:
#4781
There are a couple of things which can be further improved though:
1. The FFmpeg version should be logged on the debug logging level, similar to the Streamlink + Python version and the dependencies:
This will make debugging issues easier, e.g. #4825 
2. The FFmpeg executable should be verified via its version output:
The user can set arbitrary executables as the `--ffmpeg-ffmpeg` value, and Streamlink will execute it blindly. Not only is this bad, but if a different executable gets set, or if the `ffmpeg` executable on the user's system doesn't work, no error messages will be printed.
3. Muxing certain kinds of streams requires having a …
> FFmpeg version logging and validation

- src/streamlink/plugins/sbscokr.py
- tests/plugins/test_sbscokr.py
I noticed the `--sbscokr-id` plugin argument while cleaning up some plugins, and apparently it's not needed anymore as the individual streams are accessible from a canonical URL now.
This PR therefore suppresses the plugin argument. The old implementation also didn't support "virtual" channels which are retrieved from a different API endpoint. Geo-restriction seems to depend on the content that's currently being shown.
**master**
```
$ streamlink https://play.sbs.co.kr/onair/pc/index.html --sbscokr-id S01
[cli][info] Found matching plugin sbscokr for URL https://play.sbs.co.kr/onair/pc/index.html
[plugins.sbscokr][info] Available IDs: S01 (SBS), S02 (SBS Sports), S03 (SBS Plus), S04 (SBS funE), S05 (SBS Golf), S06 (SBS BIZ), S07 (POWER FM), S08 (LOVE FM), S09 (SBS M), S10 (Kizmom), S17 …
```
> plugins.sbscokr: rewrite and fix plugin

- src/streamlink/plugins/qq.py
- tests/plugins/test_qq.py
Quick plugin cleanup and improvement, with support for optional room IDs
**master**
```
$ streamlink https://live.qq.com/
error: No plugin can handle URL: https://live.qq.com/
$ streamlink https://live.qq.com/10164211
[cli][info] Found matching plugin qq for URL https://live.qq.com/10164211
Available streams: live (worst, best)
$ streamlink https://live.qq.com/10164211 -j | jq .metadata
{
"id": null,
"author": null,
"title": null
}
```
**PR**
```
$ streamlink https://live.qq.com/
[cli][info] Found matching plugin qq for URL https://live.qq.com/
Available streams: live (worst, best)
$ streamlink https://live.qq.com/ -j | jq .metadata
{
"id": "10003870",
"author": "蓝猫篮球lan解读",
"category": "棒球/橄榄球/冰球",
"title": "公羊vs49人【蓝猫】"
}
$ streamlink https://live.qq.com/10164211 …
```
> plugins.qq: rewrite and fix plugin

- src/streamlink/plugins/tvrplus.py
- tests/plugins/test_tvrplus.py
Just slowly updating some plugins which are still using the deprecated `validate.text` export...
This is one of them, and one of the last simple ones. Others require much more effort and are geo-locked in lots of cases, or they require having an account, which is annoying.
I was thinking about submitting a PR with a simple text substitution for all the `validate.text` definitions in the validation schemas, but that's kinda stupid, because most of those plugin implementations are really old and some are (partially) broken, so applying automated code changes is rather pointless. Maybe I should make a list of old plugins that are in need of a cleanup.
> plugins.tvrplus: rewrite plugin

- src/streamlink/plugins/goltelevision.py
Fixes #4872 
Tested with Spanish VPN. Geo-blocking happens on the media-playlist level, so it's not worth adding a check for that.
```
$ streamlink -l debug goltelevision.com/en-directo best
[cli][debug] OS:         Linux-5.17.0-rc6-1-git-01586-g15f9cd4334c8-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1+16.gf13f431b
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  url=goltelevision.com/en-directo
[cli][info] Found matching plugin …
```
> plugins.goltelevision: add missing HTTP headers

- src/streamlink/plugins/atresplayer.py
- tests/plugins/test_atresplayer.py
Fixes #4875 
This ensures that the input URL ends with a `/`.
A different and maybe better solution would've been requesting the input URL and reading the `url` attribute from the redirected HTTP response. That would require rewriting the validation schema setup, and it's not worth it.
Site detects my VPN, so I can't validate the actual streams.
```
$ streamlink https://www.atresplayer.com/directos/nova
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/nova
[plugins.atresplayer][error] Player API error: geoblocked - Content is geoblocked
error: No playable streams found on this URL: https://www.atresplayer.com/directos/nova
```
```
$ streamlink https://www.atresplayer.com/directos/nova
[cli][info] Found matching plugin atresplayer for URL …
```
> plugins.atresplayer: update input URLs

- src/streamlink/plugins/btv.py
Fixes #4884 
@TPlamen could you please verify these changes? The site is geo-blocked and I currently don't have local access to a Bulgarian IP address via a VPN/proxy.
Install my branch via pip
https://streamlink.github.io/install.html#pypi-package-and-source-code
or sideload the updated plugin
https://raw.githubusercontent.com/bastimeyer/streamlink/e53ec135d687625c4683d9dce670c4e6f593a3c5/src/streamlink/plugins/btv.py
https://streamlink.github.io/cli/plugin-sideloading.html
> plugins.btv: fix validation schema

- .github/ISSUE_TEMPLATE/1_plugin_issue.yml
- .github/ISSUE_TEMPLATE/2_bug_report.yml
- .github/ISSUE_TEMPLATE/3_plugin_request.yml
- .github/ISSUE_TEMPLATE/4_feature_request.yml
- .github/ISSUE_TEMPLATE/config.yml
Let's update the issue forms and fix some minor issues.
This PR
1. fixes the order of issue templates: 1. Plugin issue 2. Bug 3. Plugin request 4. Feature request
2. adds a link for empty/blank issues that can only be accessed by maintainers
3. adds emojis to the issue selection titles for better visual clarity and separation of the kinds of issues
4. fixes some (missing) punctuation
5. improves text + markdown in some form description with more emphasis on important parts, and adds proper lists
6. addresses incorrect usage of new threads on the discussion forum
7. addresses packaging issues
8. makes the checklist at the bottom more visible by adding non-interactive checkboxes
9. updates the donation/support text+link
preview:
https://github.com/bastimeyer-test/streamlink-test/issues/new/c …
> chore: update issue forms

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
Fixes #4904 
The old URLs get properly redirected, so I kept them in the plugin matcher regex.
When retrieving the video ID, the `Connection: close` header had to be set, because otherwise, the server would abort the next request for some reason. Took me a bit figure out, because I couldn't observe the behavior in my web browser or via curl, and it wasn't caused by session data like cookies, etc. Also had a look at urllib3's connection pool, but setting the header seems to work and is far easier than trying to close any connections in the connection pool, which is a private low-level API call anyway and probably not wise to use.
```
$ streamlink -l debug 'https://stream.tvp.pl/' best
[cli][debug] OS:         Linux-5.17.0-rc6-1-git-01595-gf3fa490960e8-x86_64-with-glibc2.36
[cli][debug] …
```
> plugins.tvp: rewrite and fix plugin, add VODs

- src/streamlink/plugins/dailymotion.py
Fixes #4909 
The JSON response data format has changed.
```
$ streamlink --http-proxy socks5h://localhost:1920 'https://www.dailymotion.com/video/x2lefik'
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x2lefik
Available streams: 180p_alt2 (worst), 180p_alt, 180p, 288p_alt2, 288p_alt, 288p, 477p_alt2, 477p_alt, 477p, 720p_alt2, 720p_alt, 720p, 1080p_alt, 1080p (best)
```
```
$ streamlink -j --http-proxy socks5h://localhost:1920 'https://www.dailymotion.com/video/x2lefik' | jq .metadata
{
"id": "x2lefik",
"author": "lachainelequipe",
"title": "la chaine L'Équipe en direct"
}
```
> plugins.dailymotion: fix validation schema

- tests/test_plugins.py
See #4923 
- https://docs.python.org/3/library/tokenize.html#tokenize.tokenize
- https://docs.python.org/3/library/io.html#text-encoding
> tests: fix plugins metadata encoding

- .github/workflows/lint.yml
- pyproject.toml
- src/streamlink_cli/compat.py
- Move list of files from CI config to mypy config in pyproject.toml, so that mypy can be run locally without having to specificy the same inputs as CLI arguments. Keep --no-incremental exclusive to CI runner.
- Update Python version of mypy CI runner.
- Fix typing ignore comment when importing importlib_metadata fallback in the streamlink_cli.compat module.
----
See #4929
> tools: move list of files to mypy config

- docs/developing.rst
As discussed in https://github.com/streamlink/streamlink/pull/4923#issuecomment-1307365789, I thought it might be useful to add some code style documentation.
I thought it might be useful to summarise each, while not unnecessarily duplicating the information contained via each of the links.
Hopefully I have the main stuff covered.  Let me know if there's anything else that needs adding and if the section placement within the page is OK.
> docs: add code style section

- docs/cli/plugins/twitch.rst
Update doc for #4939, fix header name for twitch authentication.
> docs: fix twitch oauth token header name

- src/streamlink/stream/hls.py
Adding more debug messages to `HLSStreamWriter.write()` will make debugging segment filtering much easier.
This should be done independently of the current Twitch ad filtering issues #4934.
> stream.hls: add more debug messages to write calls

- setup.cfg
- src/streamlink/plugin/api/http_session.py
- src/streamlink/plugin/api/http_session.pyi
- tests/test_api_http_session.py
Streamlink currently sets the version range of its `requests` dependency to `>=2.26.0,<3.0`. `requests` however still defines its `urllib3` dependency version range as `>=1.21.1,<1.27` in its `2.26.0`-`2.28.1` releases, including its current state in git.
Recent fixes in Streamlink's HLS implementation unfortunately were made with methods which are only supported by `urllib3 >=1.26.0`. This obviously breaks installs with older versions of `urllib3` installed which are still supported by the defined version range.
In order to avoid having to backport more `urllib3` stuff, moving it from a transitive dependency and defining it as a direct dependency with a specific version range set to `>=1.26.0` makes more sense when fixing the issue. This doesn't conflict with the version range defined by …
> build: add urllib3 directly and set it to >=1.26.0

- docs/cli/plugins/twitch.rst
- src/streamlink/plugins/twitch.py
Since authentication data for example can be set via `--twitch-api-header="Authorization=OAuth some-token"` and it is thus a useful generic plugin parameter, adding `--twitch-access-token-param` could be useful as well.
Having `--twitch-access-token-param` allows setting different `playerType` API request parameter values for example. The default value of this is `embed`, which makes Streamlink retrieve an access token for Twitch's embeddable web player. `site` is another valid value.
In the past we've had to change this multiple times and reverted everything back again (see #3210). Adding this parameter allows for customizations made by users without having to modify the plugin itself. Should there be any new developments in terms of special Twitch players with access tokens without …
> plugins.twitch: add --twitch-access-token-param

- src/streamlink/plugins/vtvgo.py
```
$ streamlink 'https://vtvgo.vn/xem-truc-tuyen-kenh-vtv1-1.html'
[cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv1-1.html
Available streams: 360p (worst), 480p (best)
$ streamlink 'https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html'
[cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
Available streams: 360p (worst), 480p, 720p (best)
```
closes #4948
> plugins.vtvgo: update to get required cookies

- src/streamlink/logger.py
- src/streamlink_cli/argparser.py
- tests/test_logger.py
Logging extremely verbose data like HLS playlist contents for example doesn't really fit on the `trace` log level. Adding an ultimate verbosity log level makes more sense here, so we can add log calls to the HLS parser and similar things.
Is the name "all" fine? I've just renamed it from "paranoid" before submitting this PR, because I wasn't really happy with that name. "all" is the opposite of "none", which is at the other end of the log level list, and it's easier to remember, too.
Since there are two custom log levels now, I had to refactor a bit of code in order to prevent duplicate stuff and duplicate tests.
> logger: add new log level "all"

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Resolves #4934
Resolves #4106 
**WORK IN PROGRESS**
Don't merge yet without strong confirmation that this is indeed working correctly. As mentioned in #4934, one of the mid-rolls I encountered resulted in the filtering not stopping. I don't know why, because I didn't run trace logs at the time. It's possible though that the streamer simply forgot to turn off ads. I'm saying that, because the last 8 mid-rolls or so I had on other channels were properly filtered out and the stream continued fine afterwards, hence why I'm opening this PR now. The added test fails without the modification made to the `TwitchM3U8Parser`. The test is derived from data I gathered earlier today.
**DEBUGGING**
Please apply the following diff first when testing this PR/branch and then set `--loglevel=trace` and …
> plugins.twitch: fix date offset of prefetch ads

- docs/_man.rst
- Split up synopsis and examples sections
- Add bugs section
- Add "see also" section
- Update some examples
----
The CLI synopsis should not be part of the list of examples. Footnotes should also be added.
Render the man page and check the results
```sh
$ make --directory=docs clean man
$ man docs/_build/man/streamlink.1
```
The current man page:
- https://man.archlinux.org/man/streamlink.1
- https://manpages.ubuntu.com/manpages/kinetic/man1/streamlink.1.html
The CLI parameter names and descriptions unfortunately get rendered in the most stupid way, and it depends on the length of the parameter name whether a line break gets included or not. That's nothing that can be fixed here though.
> docs: fix and update man page

- CHANGELOG.md
Release date is set for tomorrow. I'm going to merge once approved, so I can immediately build the AppImages and Windows releases afterwards.
As usual, only fixes for those plugin are mentioned directly which are more relevant or which had more comments or changes than average.
Full changelog:
https://github.com/streamlink/streamlink/compare/5.0.1...bastimeyer:streamlink:releases/5.1.0
> release: 5.1.0

- docs/install.rst
This was missed in #4950. It's not super important, but should be included. This also fixes the links to the docs of requests.
> docs: add missing urllib3 to install page

- src/streamlink/stream/segmented.py
- tests/mixins/stream_hls.py
If `super().close()` doesn't get called in `SegmentedStreamReader.close()`, then `closed` won't be set to `True`.
https://docs.python.org/3/library/io.html#io.IOBase.close
Noticed that while working on a solution for #4642
> stream.segmented: properly close StreamIO

- src/streamlink/stream/filtered.py
- src/streamlink/stream/hls.py
- tests/stream/test_hls_filtered.py
This abstracts the filtering logic from the `HLSStreamReader` and moves it into a dedicated module called `filtered` with a mixin class `FilteredStream` that has properly named public interfaces. The `test_hls_filtered` and `test_twitch` tests already cover the entire logic, so no new abstract tests are needed.
Initially I wasn't sure if defining this as a mixin for multiple class inheritance would make more sense than making `SegmentedStreamReader` inherit from it directly (both inherit from `StreamIO` aka `io.Base`). But since the filtering logic isn't used in the `DASHStreamReader` and no other segmented stream implementations exist apart from custom plugin stuff like UStreamTV, being able to declare specific stream implementations as filterable makes more sense, hence the mixin.
> stream: add FilteredStream and abstract filtering

- docs/install.rst
- setup.cfg
- src/streamlink/plugin/api/websocket.py
- tests/test_api_websocket.py
- Add `certifi` as a direct dependency (already defined by `requests`) and don't set a version range
- Set the `ca_certs` SSL option in `WebsocketClient` which defaults to the CA certs file bundled by `certifi`, similar to HTTPS requests made by `requests`
----
Resolves streamlink/streamlink-appimage#1
While `requests` uses the bundled `cacert.pem` CA certificates file by the `certifi` dependency (via `certifi.where()`) for all HTTPS requests being made by Streamlink (since Streamlink doesn't set any custom paths), `websocket-client` defaults to the system's CA certs which get loaded by OpenSSL. Depending on the system config, this can cause issues, and it's also inconsistent with HTTPS requests made by `requests`. Streamlink should therefore load the same `cacert.pem` when making secure …
> plugin.api.websocket: use certifi's cacert.pem

- .github/workflows/main.yml
Resolves #4988 
I've created a bug report upstream, so if this gets fixed, I will be notified, so we can remove the downgraded version again. Only downgrading on the CI side, as I don't want to set the restriction in the docs-requirements.txt.
We should probably take a look at releasing 5.1.1 due to this issue.
> ci.github: temporarily downgrade Sphinx to 5.2.3

- docs/install.rst
- Adds info for using `pipx` to install into venv
- Clarifies installing master into a venv with `pip` and `pipx`
> docs: add pipx install info

- CHANGELOG.md
Forgot to include the "Full changelog" link at the bottom. This is also used by the GH-releases deploy script for splitting the changelog, hence why I had to update the release body by hand afterwards.
#4990
> docs: fix changelog of 5.1.1 release

- .github/workflows/main.yml
- docs/Makefile
- docs/conf.py
- Update Makefile and define DOCSDIR variable
- Add `man` sphinx build tag to the `man` make-target
- Exclude `_man.rst` if the `man` build tag is set
- Revert b45e685f
----
See
#4988 
https://github.com/sphinx-doc/sphinx/issues/10987
Removing `:orphan:` from the man page can't be done, because it'll still complain about not being included in a toctree when building the man page.
----
Expected results:
1. No links to `_man.html` at all in the HTML build, even in `genindex.html`
2. Man page stays the same, including any references to other pages
> docs: fix man page links in HTML docs

- src/streamlink/stream/ffmpegmux.py
See
- https://github.com/streamlink/streamlink/pull/4994#issuecomment-1327722034
- https://docs.python.org/3/library/io.html#io.IOBase
This fixes the `copy_to_pipe` thread reading the input stream after it has been closed, which in this case raises a `ValueError`:
> ValueError: read of closed file
This is another case of an ungraceful stream end where it aborts the pipe copying due to thread timing issues that are not being dealt with correctly.
No new tests, because there are no tests for the `copy_to_pipe` thread. :/
> stream.ffmpegmux: abort on ValueError during read

- src/streamlink/plugins/svtplay.py
Resolves #4992 
This is a full plugin rewrite which cleans up the API request and validation schema, and it adds support for HLS streams.
As you can see, there's a stream priority list, because apparently there's a difference between the available qualities of the available stream types, and for some reason, some DASH streams offer higher resolutions and bitrates. It's probably an overkill having all kinds of formats there, but whatever... Also a pretty good reason for a rewrite of the stream selection, as described in #4902.
I can access the API and VOD content with my VPN, but HLS live streams return a 403, so I can't actually test all plugin changes.
@mkbloke, please have a look, thanks.
> plugins.svtplay: rewrite plugin and add HLS

- docs/cli/config.rst
- docs/install.rst
I initially wanted to only update the AppImage section of the install docs, but then decided to also update the Windows binaries section and do some additional cleanup.
The main focus is to make finding the important information easier and quicker. This also involves adding an icon to the download links.
The third commit is not really important and could be ignored if anyone feels like it's unnecessary.
> docs: rewrite Windows + AppImage install sections

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Twitch doesn't include duration data for prefetch segments, which means when more than one prefetch segment is included in the HLS playlist, the start time of the second (or third) prefetch segment has to be guessed from the duration of the regular segments. This is done by calculating the average of all available regular segments and using that as an offset of the last regular segment for each prefetch segment.
This however can cause issues when segment durations vary a lot and the start time of an annotated ad block doesn't match the extrapolated start time of the first ad segment due to the miscalculation. The ad segment then gets incorrectly included in the output stream.
Since a discontinuity tag is always present, even between prefetch tags with ads, we can make use of it and treat …
> plugins.twitch: fix ad filtering bug

- src/streamlink/options.py
- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
- Refactor `TwitchAPI` class:
- Set `CLIENT_ID` as a class attribute (for test references)
- Allow `call()` to pass custom headers (currently unused)
- Remove unneeded `json.dumps()`
- Handle `PlaybackAccessToken` error response and log error messages
- Add `Options.clear()` for resetting plugin options state after tests
- Add access token API tests
----
Resolves #5009 
This adds error logging to the access token processing and also adds tests for the access token responses and how the `--twitch-api-header` and `--twitch-access-token-param` influence the access token request.
----
Small side-note in regards to the added `Options.clear()` method:
I've already mentioned somewhere in the `Plugin.bind()` removal in 5.0.0 (#4744 / #4768) that `Plugin.options` will also need to get fixed at …
> plugins.twitch: better access token error handling

- tests/mixins/stream_hls.py
- tests/stream/test_hls_filtered.py
- tests/testutils/handshake.py
- tests/testutils/test_handshake.py
This cleans up and simplifies the HLS test mixins by implementing a generic thread-handshake class for synchronizing code execution between two threads: application logic (producer thread) and tests (consumer/main thread), with optional error capturing. The previous implementation was using a similar setup in multiple different classes. This is now defined with a proper interface and proper method names, for much better readability of the tests.
I've also added support for async coroutines in case this is required at some point. And I added tests for the new `tests.testutils.handshake.Handshake` class, so that it doesn't get tested implicitly via the other tests.
This work is required for my code refactoring of the CLI's `read_stream()` stuff (see #4974 - not yet finished), because I …
> tests: refactor thread handshakes

- tests/conftest.py
- tests/plugins/conftest.py
Tests should be run in the following order
1. test-utility tests
2. application-utility tests
3. \*
4. stream tests
5. plugin tests
6. cli tests
so that dependencies get tested first. If a dependency breaks, this makes it clear where the issue is coming from, should tests of dependent code also break.
For example, since certain tests require certain test utilities, those test utilities should be tested first, to ensure that everything is working when running the entire test suite.
> tests: change order of collected tests

- tests/__init__.py
**master**
```
$ pytest --durations=10 | tail -n12
============================= slowest 10 durations =============================
946550580.35s setup    tests/cli/utils/test_formatter.py::TestCLIFormatter::test_title
946550580.34s setup    tests/cli/utils/test_formatter.py::TestCLIFormatter::test_path
946550580.34s setup    tests/cli/utils/test_formatter.py::TestCLIFormatter::test_path_substitute
946550573.89s setup    tests/utils/test_formatter.py::TestFormatter::test_unknown
946550573.88s setup    tests/utils/test_formatter.py::TestFormatter::test_format
946550573.87s setup    tests/utils/test_formatter.py::TestFormatter::test_format_spec
946453134.91s setup    tests/plugins/test_filmon.py::test_filmonhls_to_url
946453134.88s setup …
```
> tests: fix freezegun's default module ignore list

- script/install-dependencies.sh
lxml 4.9.2 has been released with all wheels, including cp311-win_amd64
----
Closes #4903 
After this got merged, I will update the master branch protection rules and switch from py310 to py311 for the required test runs
> ci: remove custom lxml wheel for Windows

- src/streamlink/plugins/cdnbg.py
I've not tested BNT3 via a proxy, as I have not found one that seems to be usable so far.  BNT4 is not geo-restricted, the rest are.
```
$ streamlink http://tv.bnt.bg/bnt3
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt3
[plugins.cdnbg][error] Geo-restricted content
error: No playable streams found on this URL: http://tv.bnt.bg/bnt3
$ streamlink http://tv.bnt.bg/bnt4
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt4
Available streams: 576p (worst, best)
```
closes #5039
> plugins.cdnbg: update regex

- src/streamlink/plugins/vkplay.py
- tests/plugins/test_vkplay.py
Plugin to support live streaming on vkplay.live
```
streamlink https://vkplay.live/sguhoman
[cli][info] Found matching plugin vkplay for URL https://vkplay.live/sguhoman
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
```
> plugins.vkplay: new plugin

- src/streamlink_cli/main.py
- src/streamlink_cli/streamrunner.py
- src/streamlink_cli/utils/progress.py
- tests/cli/test_streamrunner.py
- tests/cli/utils/test_progress.py
Replace `read_stream()` with a new `StreamRunner` class, refactor stream reads and output writes, as well as the progress thread data feeding, and move player polling into a separate thread which closes the stream once the player process gets terminated/killed.
This fixes the player polling issue, or rather the detection of its broken pipe while reading the stream, as stream read calls can stall for various reasons, e.g. due to segmented streams or the filtering of stream data which pauses the stream output and disables any timeouts.
- Implement `StreamRunner` and `PlayerPollThread` classes in dedicated `streamlink_cli.streamrunner` module
- Remove old `streamlink_cli.main.read_stream()` implementation
- Keep the same log messages
- Make `StreamRunner.run()` raise `OSError` on read/write …
> cli: replace read_stream() with StreamRunner

- .github/workflows/main.yml
Just wanted to update the master branch protection rules and noticed that the Ubuntu runners are still on 20.04.
Both Linux and Windows runners should use the latest OS release versions respectively. Upgrading from Ubuntu 20.04 to 22.04 shouldn't cause any issues.
After this has been merged, I will make Python 3.11 a requirement for PRs.
> ci.github: ubuntu-20.04 -> ubuntu-latest

- .github/workflows/main.yml
- script/build-and-sign.sh
Use `build` to build sdist and wheels instead of calling setuptools directly, which is deprecated.
See
https://github.com/pypa/build
----
I've checked the sdist tarball and the built wheels, and everything looked okay to me. The win32 and win-amd64 wheels also have the correct GUI entry scripts (streamlink**w**).
> build: update build script

- src/streamlink/options.py
- src/streamlink/session.py
- tests/test_options.py
- tests/test_session.py
This replaces the logic of the `Streamlink.{get,set}_option()` methods with a new `StreamlinkOptions` subclass which uses mapped option getters+setters that apply the custom option logic instead.
The motivation for this is that this improves the runtime of said methods, as option mappers are looked up in Python dictionaries in constant time, so option names don't have to be checked one after another. The old implementation is also really really bad code-wise and not extensible.
In order to do this, the `Options` class had to be refactored a bit and extended:
1. Previously, the internally stored option keys were normalized with argument names of the `argparse.Namespace` in mind, so dashes were replaced with underscores. Since Streamlink's session options are defined using dashes, I changed …
> session: refactor option getter+setter methods

- .github/workflows/main.yml
- script/build-and-sign.sh
- script/deploy-pypi.sh
Follow-up of #5077 
----
As said, I don't have the password for the signing key, so I can't actually test the changes to the gpg decryption command. That's just a trivial change though, and it reads the passphrase from stdin now, which is the preferred way. Just take a look at the manual.
https://man.archlinux.org/man/gpg.1#passphrase-fd
I've messaged @beardypig and asked him to post the password to the protonmail account, as a backup.
----
The second change is in regards to the PyPI deploy script.
The current authentication method when uploading release files to PyPI is password based. This will change it to a token-based authentication, with different env vars. I will add those to the secret env vars after this has been merged. The token has been sent to the protonmail mailbox. …
> build: update auth in sign+deploy scripts

- docs/api.rst
- src/streamlink/exceptions.py
- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/oneplusone.py
- src/streamlink/plugins/pixiv.py
- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/vk.py
- tests/plugin/testplugin.py
- tests/plugins/test_twitch.py
- tests/plugins/test_vk.py
- Make `NoPluginError` inherit from `StreamlinkError` instead of `PluginError`
- Update and fix docstrings of all Streamlink exception classes
- Update list of exceptions in API docs
- Fix exports
----
`NoPluginError` is only raised [here](https://github.com/streamlink/streamlink/blob/ae7583473626a09f870fbdb71e4a988a83664ea6/src/streamlink/session.py#L439) and caught in the main CLI module where URLs get resolved. It shouldn't inherit from `PluginError`, because it's something entirely different.
> exceptions: update docs, fix NoPluginError and remove url arg from NoStreamsError

- src/streamlink/exceptions.py
- src/streamlink/logger.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- src/streamlink_cli/main.py
- tests/cli/test_argparser.py
- tests/cli/test_main.py
- tests/cli/test_main_setup_config_args.py
- tests/stream/test_hls_filtered.py
- tests/test_logger.py
- tests/test_plugin.py
- tests/test_session.py
See #4785
This makes Streamlink's root logger capture warnings (disabled by default, enabled via streamlink_cli) and it replaces various warning log messages for deprecated (user-facing) stuff with `FutureWarning`s.
https://docs.python.org/3/library/exceptions.html#warnings
https://docs.python.org/3/library/warnings.html#warning-categories
The reason for this is that this allows for finer control over the kind of deprecation messages (API stuff for devs, or other stuff for end-users) and it uses the standard interfaces for warnings, which is preferred. Warnings from dependencies can also be caught this way, but I'm not sure how useful this is, because I modified the default warning message format, so it doesn't include the file+line of the warning, because it's not useful for Streamlink's …
> logger: capture warnings

- docs/deprecations.rst
- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/adultswim.py
- src/streamlink/plugins/bbciplayer.py
- src/streamlink/plugins/crunchyroll.py
- src/streamlink/plugins/funimationnow.py
- src/streamlink/plugins/kugou.py
- src/streamlink/plugins/n13tv.py
- src/streamlink/plugins/openrectv.py
- src/streamlink/plugins/pixiv.py
- src/streamlink/plugins/rtbf.py
- src/streamlink/plugins/schoolism.py
- src/streamlink/plugins/tv4play.py
- src/streamlink/plugins/vimeo.py
- src/streamlink/plugins/wasd.py
- src/streamlink/plugins/webtv.py
- src/streamlink/plugins/zhanqi.py
- tests/test_api_validate.py
- Deprecate text alias and raise StreamlinkDeprecationWarning on access
- Add deprecation to docs
- Replace validate.text with str in remaining plugins
- Update test
----
The deprecation warning gets triggered when accessing `text` via the module's `__getattr__()` method. This is better than raising the warning when validating a specifc schema with a specific input.
Importing `*` from the validate module will also trigger the deprecation warning, but that's nothing that can be changed unless `text` gets removed from `__all__`, but that would be a breaking change from the previous implicit inclusion of all module namespace members. So if there are third-party plugins which import `*` and are not using `text`, then they will still trigger the warning. But since importing `*` is already …
> plugin.api.validate: deprecate text alias

- pyproject.toml
- src/streamlink/plugin/api/validate/__init__.py
Accidentally forgot to suppress coverage of the `TYPE_CHECKING` block added in #5090.
https://app.codecov.io/gh/streamlink/streamlink/pull/5090
This PR adds `TYPE_CHECKING` to the list of excluded lines via `pyproject.toml`. But since pycharm seems to ignore this when building coverage reports via the `coverage` module, I also added the regular `# pragma: no cover` directive.
> chore: ignore coverage in TYPE_CHECKING blocks

- dev-requirements.txt
- pyproject.toml
- tests/cli/output/test_playeroutput.py
- tests/cli/test_main.py
- tests/test_plugin.py
- tests/test_session.py
See the individual commit messages...
TL;DR: file handles and sockets were not closed in some tests
This once again demonstrates the need for a rewrite of the PlayerOutput and the main CLI module :disappointed: 
Not tested on Windows, let's see if I made a mistake while rewriting the playeroutput tests...
> tests: set filterwarnings=always via pytest config

- src/streamlink/plugin/api/http_session.py
- src/streamlink/session.py
- tests/test_session.py
Just a small correction after `urllib3` was added to the dependencies list in November (#4950)
> chore: remove unneeded noinspection directives

- src/streamlink/plugins/ceskatelevize.py
- tests/plugins/test_ceskatelevize.py
@duunsupen, could you check this is working for all channels by [sideloading](https://streamlink.github.io/cli/plugin-sideloading.html) the updated plugin, please?  I think it's probably working OK, but they seem to detect VPS based proxies, so I just get the short clip telling me the channel isn't available for all except CT24.
---
For some reason, the subdomains are both different to the main channels in terms of HTML and JSON data, and different to each other as well.  The API response is slightly different for `sport` too.  All a bit strange.
I didn't bother going through the process of finding the id for CT24, as it seems unlikely it'll change.
I notice that sometimes the streaming URL gets an empty response, but it seems intermittent.  I've seen that happen in the web browser too …
> plugins.ceskatelevize: update for ct24, sport and sportplus; add decko

- docs/developing.rst
- src/streamlink/plugin/plugin.py
- tests/test_plugin.py
This adds support for optionally named plugin matchers, e.g.:
```py
@pluginmatcher(re.compile("http://foo"), name="foo")
@pluginmatcher(re.compile("http://bar"), name="bar")
class MyPlugin(Plugin):
def _get_streams():
if self.matches["foo"]:
return self._get_streams_foo()
else:
return self._get_streams_bar()
```
Both `Plugin.matchers` and `Plugin.matches` can now be referenced by matcher index, like before, as well as matcher name, if it was set. Invalid values will raise an `IndexError` and `KeyError` respectively.
This is useful if multiple matchers are defined, so match results don't have to be referenced by matcher index, which depends on the (reverse) order of the pluginmatcher decorators.
> plugin: add support for named plugin matchers

- docs/developing.rst
- tests/plugins/__init__.py
- tests/plugins/conftest.py
- tests/plugins/test_goltelevision.py
- tests/plugins/test_lnk.py
- tests/plugins/test_tvp.py
- tests/plugins/test_tvtoya.py
- Rewrite dynamic test parametrization
- Test named plugin matchers
- Update tests with named matchers accordingly
- Fix incorrect test class names
----
ref https://github.com/streamlink/streamlink/pull/5103#issuecomment-1398561108
> tests.plugins: rewrite PluginCanHandleUrl tests

- src/streamlink/buffers.py
- src/streamlink/stream/hls.py
- tests/stream/test_hls_filtered.py
- tests/test_buffers.py
A warning message should've been added a while ago...
This adds the `written_once` attribute to the base `Buffer` class instead of the `HLSStreamWriter` class, because `HLSStreamWrite` would be the wrong place should a multi-buffer `HLSStream` ever get implemented for being able to write multiple files when a discontinuity occurs.
> stream.hls: warn when writing after discontinuity

- CHANGELOG.md
Release date is set to tomorrow. I will have a look later today or tomorrow if there's some stuff missing, e.g. in regards to the new warnings logging and deprecation messages.
There's also the potential of a release failure due to the recent changes in #5077 and #5081, as mentioned...
> release: 5.2.0

- .github/workflows/main.yml
- script/deploy-pypi.sh
Partially reverts de5bda806d28d7c41879049237391c3dd68f01e4
----
Release 5.2.0 failed while uploading the files to PyPI due to the recent changes of #5081.
This switches the upload auth data back to username+password. I will also remove the 2FA restriction again from the streamlink PyPI repo.
Will publish a 5.2.1 release afterwards...
https://github.com/streamlink/streamlink/pull/5111#issuecomment-1401057624
https://github.com/streamlink/streamlink/actions/runs/3990883680/jobs/6845136470#step:10:1
> ci: revert deploy-pypi changes

- MANIFEST.in
For some reason, the `icon.svg` file was never added to the sdist manifest file, which meant the icon file was only included by accident in the docs dir, from the symlinked icon in the `_static` subdirectory. Let's fix this.
```sh
$ curl -sSL 'https://files.pythonhosted.org/packages/9e/0c/b8c90cda86583a141dcc584eb32838ed312fb8cd9d5aab20faaa7f49d5fb/streamlink-5.2.1.tar.gz' \
| bsdtar -tf - \
| grep -E '^streamlink-.+/icon.svg'
streamlink-5.2.1/docs/_static/icon.svg
```
```sh
$ python -m build --sdist >/dev/null 2>&1
$ bsdtar -tf dist/streamlink-5.2.1+1.gb5d5a042.tar.gz \
| grep -E '^streamlink-.+/icon.svg'
streamlink-5.2.1+1.gb5d5a042/docs/_static/icon.svg
streamlink-5.2.1+1.gb5d5a042/icon.svg
```
> build: include icon.svg in sdist

- .github/workflows/lint.yml
- docs/developing.rst
- pyproject.toml
Mypy currently checks the `docs` directory by default via the included `tool.mypy.files` entry in `pyproject.toml`.
However, when no `docs-requirements.txt` were installed, no Sphinx and related packages as well as docs typing stub packages are available in the environment, which leads to an error when just running `mypy`:
```
$ python3.11 -m venv ~/foo
$ source ~/foo/bin/activate
$ pip install -U --upgrade-strategy=eager -r dev-requirements.txt -e .
$ mypy
docs/ext_releaseref.py:6:1: error: Library stubs not installed for "docutils.nodes"  [import]
docs/ext_releaseref.py:6:1: error: Library stubs not installed for "docutils"  [import]
docs/ext_releaseref.py:7:1: error: Cannot find implementation or library stub for module named "sphinx.util.nodes"  [import] …
```
> tools: check typing in docs dir separately

- .github/DISCUSSION_TEMPLATE/general.yml
- .github/DISCUSSION_TEMPLATE/q-a.yml
This adds templates to the discussions forum, similar to the issue templates.
The markdown header is mainly copied from the stickied thread which I will remove once merged:
https://github.com/streamlink/streamlink/discussions/4578
The checklist is a pseudo-checklist, so that the list doesn't get included in the discussion thread. The "description" header unfortunately gets included, as it's the title of the textarea, which is the only user input (required when using a template).
Both templates are idential, because there's not much difference between the two categories. The function of the Q&A category is already explained in its title description.
I've tested this on my fork repo, and everything worked just fine. The YML schema is still considered public beta, but I don't expect anything …
> chore: add templates for GitHub discussions

- docs/deprecations.rst
- docs/ext_argparse.py
- docs/ext_plugins.py
- src/streamlink/options.py
- src/streamlink/plugins/rtve.py
- src/streamlink/plugins/svtplay.py
- src/streamlink/plugins/vimeo.py
- src/streamlink_cli/main.py
- tests/test_options.py
- tests/test_plugins.py
- Raise `StreamlinkDeprecationWarning` when `is_global=True`
- Remove all global plugin arguments and replace them with simple option lookups on the Streamlink session instance
- Remove global argument detection in custom Sphinx plugins extension
- Remove supported plugins list from custom Sphinx argparse extension and remove respective setup from `setup_plugin_args` in the CLI module
- Add deprecation note to the docs
- Update tests
- Check whether builtin plugins define global plugin arguments
- Capture deprecation warnings
----
This is partly cherry-picked from the (current state of the) first commit of #5033 where global plugin arguments get removed, and it instead deprecates the usage of global plugin arguments and just removes them from Streamlink's builtin plugins and the docs. …
> options: deprecate global plugin arguments

- setup.cfg
`py.typed` should be included in setuptools' `package_data`, so it gets included in the source and binary distributions, so 3rd party applications can read Streamlink's typing informations ([PEP 561](https://peps.python.org/pep-0561/)). #4544 didn't include it when the file was added, because it was just meant to enable mypy back then (an incorrect decision).
The file of the `streamlink_cli` package is explicitly not included here, since that package is not considered a public interface, only the `streamlink` package is, hence the split of the two packages.
```sh
$ curl -sSL 'https://files.pythonhosted.org/packages/9e/0c/b8c90cda86583a141dcc584eb32838ed312fb8cd9d5aab20faaa7f49d5fb/streamlink-5.2.1.tar.gz' \
| bsdtar -tf - \
| grep py.typed
$ echo $?
1
$ python -m build --sdist --wheel …
```
> build: include py.typed in package_data

- src/streamlink/plugins/youtube.py
- tests/plugins/test_youtube.py
Fixes #5136 
This splits up the ugly verbose matcher regex into separate matchers for each URL type, and it adds the new `@`-URLs and `/live/video-id` URLs.
Before merging, please help me validate all the supported URLs, because splitting up the matchers required some refactoring, and not all `self.match[key]` keys are available anymore, which can lead to an unintended `IndexError` being raised.
----
Btw, this unrelated issue with the muxed adaptive streams and missing audio bitrates needs separate fixing:
```
$ streamlink 'https://www.youtube.com/embed/aqz-KE-bpKQ'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/aqz-KE-bpKQ
File "/home/basti/venv/streamlink-311/bin/streamlink", line 8, in <module>
sys.exit(main())
^^^^^^ …
```
> plugins.youtube: rewrite and fix matchers

- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls_playlist.py
This fixes and cleans up the M3U8Parser's attribute list regex+parser and some individual attribute parser methods, and it adds missing unit tests.
The old attribute list regex was incorrect and was also missing some stuff. This is now fixed and it's a bit more strict when parsing the attribute list, but it's not doing that 100% according to the spec either, because the previous one also wasn't (and shouldn't, to be able to support broken/invalid playlists).
https://www.rfc-editor.org/rfc/rfc8216#section-4.2
One key difference here is that the entire attribute list gets discarded if there's a parsing issue with one of the attributes in the attributes list. Previously, this was not the case and the already parsed attributes of a specific tag were returned and it kept parsing via …
> stream.hls: refactor and fix attribute list parser

- .github/workflows/lint.yml
- dev-requirements.txt
- docs/developing.rst
- pyproject.toml
- setup.cfg
Step 1 of 3+x, as detailed in #5145 
This replaces `flake8` and plugins with `ruff`, sets a similar config, and updates the docs.
The import linting config is missing and will be added in a subsequent PR via ruff's `isort` "I" rules, which are slightly different and require lots of module code changes. This PR only changes the bare minimum for having a short diff without any code changes.
> tools: replace flake8 with ruff

- .git-blame-ignore-revs
See `man git-blame`, `git blame --ignore-revs-file <file>` and the `blame.ignoreRevsFile` git config option.
----
- https://git-scm.com/docs/git-blame
- https://git-scm.com/docs/git-blame#Documentation/git-blame.txt-blameignoreRevsFile
- https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
----
Step 3 of 3+x, as detailed in #5145 
These are currently the commits with the biggest number of changed files:
```sh
git log --max-count=2000 --no-merges --shortstat --format='%H %cs' \
| awk '/^[a-f0-9]{40}/ { c=$0 }; /^ [0-9]+ files? changed/ { print $1 " " c }' \
| sort -nr \
| awk '$1 >= 25 { print "- " $2 ": " $1 " (" $3 ")" }'
```
- 57fa6f80e8defa12dde4e6bbc7a1df7a3c492a9a: 203 (2023-02-09)
- …
> tools: add .git-blame-ignore-revs

- .gitattributes
Added by 416c834 and made obsolete by 9b0815d
----
https://git-scm.com/docs/gitattributes#_export_subst
> tools: remove export-subst from .gitattributes

- docs-requirements.txt
- docs/cli/tutorial.rst
- docs/conf.py
The main motivation of these changes is having a short linkable example of how to escape URLs in various command-line shells, because this question comes up often and gets incorrectly (and annoyingly) reported as a bug.
Since there'd be a lot of repetition when showing examples for different shells, I decided to add the `sphinx-design` extension, to be able to have support for tabs (and other things that might be useful in the future). It's recommended by the furo-theme author and it's maintained by the developer of the `myst-parser` extension which Streamlink already uses for markdown support in the docs.
https://sphinx-design.readthedocs.io/en/furo-theme/index.html
This PR also rewrites and clarifies some sections and fixes broken links. I also replaced the tutorial's example URL with …
> docs: rewrite, fix and improve CLI tutorial

- .github/ISSUE_TEMPLATE/config.yml
Gitter is now a native Matrix server
https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/
> chore: update Gitter link in issue template config

- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls_playlist.py
I made a mistake in #5125.
A warning should not be logged when the input value of `parse_hex()` is `None`, which is the case when `#EXT-X-KEY:METHOD=NONE` is set for example, because it's missing the `IV` attribute.
The `not log or log-records-comp` assertion in the tests was also pretty stupid because it misses the case when a warning does get logged when it's not supposed to log anything...
> stream.hls: fix parse_hex warning message

- src/streamlink/compat.py
- src/streamlink/stream/ffmpegmux.py
- tests/stream/test_ffmpegmux.py
- Change priority of --ffmpeg-verbose-path and --ffmpeg-verbose
- Remove unneeded subprocess.DEVNULL compatibility export
- Suppress OSError when closing fd of --ffmpeg-verbose-path
- Update tests
> stream.ffmpegmux: refactor errorlog fd

- pyproject.toml
Ignore new `pkg_resources.declare_namespace` DeprecationWarning which was added in the setuptools 67.3.0 release.
----
The DeprecationWarning was added in the setuptools 67.3.0 release:
- https://setuptools.pypa.io/en/latest/history.html#v67-3-0
- https://github.com/pypa/setuptools/commit/925a792d8c7f69500c0169c932df08f73f30f6fe
And it gets triggered by the various `sphinxcontrib-*` **namespace packages** which are listed as dependencies of the sphinx package.
- https://github.com/sphinx-doc/sphinx/blob/v5.3.0/pyproject.toml#L60-L65
- https://github.com/sphinx-doc/sphinxcontrib-devhelp/blob/1.0.2/setup.py#L69
- https://github.com/sphinx-doc/sphinxcontrib-jsmath/blob/1.0.1/setup.py#L67
- https://github.com/sphinx-doc/sphinxcontrib-qthelp/blob/1.0.3/setup.py#L69
- …
> tests: ignore setuptools 67.3.0 DeprecationWarning

- src/streamlink/options.py
- src/streamlink/session.py
- src/streamlink/stream/hls.py
- tests/test_options.py
- tests/test_session.py
- Fix default options
- Reorder according to cli argparse mapping
- Add missing defaults (except deprecated keys)
- Fix incorrect defaults
- Fix set_option() docstring
- Replace rst table with list-table from myst-parser extension
- Reformat table and add key, type, default and description columns
- Add all missing keys, including deprecated keys
- Reorder keys according to default keys
- Fix types and update descriptions
- Add docstring tests
----
https://github.com/streamlink/streamlink/discussions/5173#discussioncomment-5001628
First commit is only meant for having some kind of public interface on the `Options` class for iterating its keys (as used in the added session options documentation tests), or for getting/setting values with the bracket syntax, which could be useful in plugins …
> session: fix options docstring

- docs/ext_argparse.py
- pyproject.toml
- src/streamlink/logger.py
- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugins/adultswim.py
- src/streamlink/plugins/booyah.py
- src/streamlink/plugins/pluto.py
- src/streamlink/plugins/tvp.py
- src/streamlink/stream/dash_manifest.py
- src/streamlink/stream/hls_playlist.py
- src/streamlink/stream/segmented.py
- src/streamlink/utils/args.py
- src/streamlink_cli/main.py
- tests/cli/utils/test_formatter.py
- tests/plugins/test_twitch.py
Just a couple of more linting rules for ensuring cleaner code, without major code changes.
pylint's "refactor" ruleset is not included in this PR, because its rules set a default function/method complexity limit and a max number of function/method parameters, and Streamlink's codebase violates most of those rules, so adding the ruleset just to suppress most rules of this set doesn't make much sense.
https://beta.ruff.rs/docs/rules/#pylint-pl
I'd also like to add flake8-bugbear in the future, but that will require more code changes which I didn't want to include here just yet.
https://beta.ruff.rs/docs/rules/#flake8-bugbear-b
> tools: add pylint, flake-pie and flake-builtins rules to ruff config

- src/streamlink/plugins/vinhlongtv.py
- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash_parser.py
- tests/stream/test_hls_playlist.py
1. Use the [`datetime.timezone.utc`](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc) stdlib class instance instead of the custom `isodate.UTC` class instance (differs in `dst()`, but that's irrelevant) (`datetime.UTC` is only available on 3.11+)
- https://github.com/python/cpython/blame/v3.11.0/Lib/datetime.py#L2409
- https://github.com/python/cpython/blame/v3.10.0/Lib/datetime.py#L2301
- https://github.com/gweis/isodate/blob/0.6.1/src/isodate/tzinfo.py#L13-L46
2. Fix default param in `stream.dash_manifest.count_dt()` (should be the current time when initializing)
3. Rename constants for consistency reasons
4. Use dataclass for DASH `Segment`s, add typing information, rename `range` to `byterange` (similar to HLS's `Segment` (currently still a NamedTuple)) and …
> stream.dash: fix and refactor

- dev-requirements.txt
- pyproject.toml
Fixes issue introduced in ruff's 0.0.250 release yesterday.
https://github.com/charliermarsh/ruff/releases/tag/v0.0.252
PLW2901 is a nonsense rule, so it gets ignored now:
https://beta.ruff.rs/docs/rules/redefined-loop-name/
Otherwise, it'll raise errors on stuff like this:
https://github.com/streamlink/streamlink/blob/d33df662a4f4f28332ec3980b6dd964f990c7a35/src/streamlink/plugin/api/validate/_validate.py#L379-L382
> tools: bump ruff to >=0.0.252 and ignore PLW2901

- src/streamlink/stream/dash_manifest.py
- Fix incorrect typing
- Fix error messages, as well as docstrings and comments
- Fix indentation
- Replace str.format with f-strings
- Use consistent order of `MPDNode.attr()` call keywords, but keep the order of the method's arguments
- Use keywords when initializing the `Segment` dataclass
- Flatten nested if-blocks in `SegmentTemplate.format_media()`
- Remove unnecessary if-block in `Representation.segments()`
> stream.dash: refactor and reformat code

- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_nested_baseurls.mpd
- tests/stream/test_dash_parser.py
Fixes #4586 
Previously, when formatting init/media segment URLs of a `SegmentTemplate`, its own inherited `base_url` property was used, which does only work in MPD documents where the next `BaseURL` node is a child node of one of the `SegmentTemplate`'s ancestor nodes, namely `AdaptationSet`, `Period` or `MPD`:
```xml
<MPD ...>
<BaseURL>one</BaseURL>
<Period ...>
<BaseURL>two</BaseURL>
<AdaptationSet>
<BaseURL>three</BaseURL>
<SegmentTemplate .../>
<Representation .../>
</AdaptationSet>
</Period>
</MPD>
```
This left out potential `BaseURL` child-nodes in `Representation` nodes that are siblings of `SegmentTemplate` (and similar cases):
```xml
<MPD ...>
<BaseURL>one</BaseURL>
<Period ...>
<BaseURL>two</BaseURL>
<AdaptationSet>
<BaseURL>three</BaseURL>
<SegmentTemplate .../> …
```
> stream.dash: fix SegmentTemplate's BaseURL context

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash.py
ref https://github.com/streamlink/streamlink/discussions/4319#discussioncomment-2085613
Requires an update of all MPD mocks in the DASH tests, because of `Mock`'s autospec, turning `contentProtection` into a truthy value if unset. Setting the `spec` is of no use here.
> stream.dash: ContentProtection in Representation

- pyproject.toml
- src/streamlink/logger.py
- src/streamlink/utils/named_pipe.py
New ruff version added `PLW0603`.
Global state gets legitimately/consciously set in the `logger` and `named_pipe` modules, so the new `PLW0603` rule gets ignored via the `noqa` annotations there. The `main` CLI module is unfortunately riddled with the `global` statement, so the rule gets ignored for the entire module until a much needed refactor happens at some future time (hopefully).
> tools: ignore PLW0603 ruff rule

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_timeline_ids.mpd
- tests/stream/test_dash.py
- tests/stream/test_dash_parser.py
**stream.dash: fix old timeline ID workaround**
When building segment timelines, don't use the `mimeType` attribute of the `SegmentTemplate`'s parent node as a fallback when the parent's `id` attribute is missing.
This doesn't work if the parent node is a `Period`, as it doesn't have the `mimeType` attribute, and it also generates timeline keys which are not unique if two streams of the same `mimeType` would get muxed (currently not supported).
Instead, build an `ident` tuple on the `Representation` instance consisting of the ids of the parent `Period` and `AdaptationSet`, and the `Representation` itself, with its required `id` attribute. This ensures a unique key for the `timelines` dict.
Then simply pass the `ident` tuple to the `SegmentTemplate.segments()` generator, similar to the …
> stream.dash: fix old timeline ID workaround

- src/streamlink/session.py
- src/streamlink/stream/dash.py
- src/streamlink_cli/argparser.py
This adds `--dash-manifest-reload-attempts` and the respective session option with a default value of 3, similar to `--hls-playlist-reload-attempts`.
HTTP requests of dynamic DASH stream manifests currently don't have a retry value set, so if a request fails due to a temporary connection/server issue, then no new segments can be queued. Failed requests still raise a `StreamError` on the worker thread, same as the HLS implementation, which needs to be fixed separately.
> stream.dash: add --dash-manifest-reload-attempts

- pyproject.toml
- src/streamlink/logger.py
- src/streamlink/plugins/crunchyroll.py
- src/streamlink/plugins/htv.py
- src/streamlink/plugins/oneplusone.py
- src/streamlink/plugins/pluzz.py
- src/streamlink/plugins/rtbf.py
- src/streamlink/plugins/ustreamtv.py
- src/streamlink/utils/times.py
- src/streamlink_cli/main.py
- tests/cli/test_main.py
- tests/plugins/test_filmon.py
- tests/plugins/test_twitch.py
- tests/test_logger.py
- tests/utils/test_formatter.py
- tests/utils/test_times.py
- Add "DTZ" ruff rule
- Add utility functions to `streamlink.utils.times` which use "aware" datetimes with explicit timezone information, and use `isodate`'s local timezone implementation
- Replace all "naive" datetimes without timezone information
- Replace all custom ISO8601 parsers with `isodate`'s implementation
- Add tests for new utility functions
----
https://docs.python.org/3/library/datetime.html#aware-and-naive-objects
https://beta.ruff.rs/docs/rules/#flake8-datetimez-dtz
> chore: aware datetimes

- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_nested_baseurls.mpd
- tests/resources/dash/test_segment_list.mpd
- tests/resources/dash/test_segments_dynamic_number.mpd
- tests/resources/dash/test_static_no_publish_time.mpd
- tests/stream/test_dash_parser.py
The segment availability "anchor time" depends on the sum of the manifest's `availabilityStartTime` and the period's `start` attribute, for both static and dynamic manifests.
Fix segment availability times:
- Set the correct `available_at` value for static manifests with segment templates and segment timelines instead of using the current time
- Set the `available_at` value for `SegmentList` segments instead of defaulting to `EPOCH_START`
- Set the `available_at` value for all initialization segments
Fix segment numbers:
- The number offset now also takes the period start into consideration
Also:
- Allow passing keywords to child node constructors
- Keep the `Period` reference on `SegmentList`, `SegmentTemplate` and `Representation`
- Check segment availability times in certain tests
- …
> stream.dash: fix segment availability times

- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_segments_dynamic_number.mpd
- tests/stream/test_dash_parser.py
- Fix segment number iterator and segment availability-time iterator for dynamic timeline-less DASH streams by calculating the right segment number offset and basing the segment availability-time on the segment number, and not just on the current time alone
- Set a default value of 0 seconds for presentationTimeOffset
- Ensure that segment durations are known
- Never calculate negative segment number offsets
- Reduce unnecessary delay by starting with the upcoming segment in the generated timeline to be as close to the live-edge as possible (with minBufferTime and presentation offset+delay in mind)
- Add debug log output
- Update MPD manifest test fixture with better time data
Next:
- Consider removing the default value of suggestedPresentationDelay, as it seems to be a relict of …
> stream.dash: fix dynamic timeline-less streams

- src/streamlink/plugins/vimeo.py
Parameters to reproduce
```
https://player.vimeo.com/video/803849296?h=1f71c5e810 best
```
> plugins.vimeo: fix playerConfig regex

- pyproject.toml
Follow-up of c3ff5a0.
Ignore all warnings raised by `pkg_resources`:
New `DeprecationWarning`s were added by setuptools 67.5.0
----
- #5167
- https://setuptools.pypa.io/en/latest/history.html#v67-5-0
The reason why `pkg_resources` gets imported is `pycountry`:
`streamlink` -> `streamlink.session` -> `streamlink.l10n` -> `pycountry`
hence why the warnings occurred in every test module
> tests: ignore all pkg_resources warnings

- tests/__init__.py
- tests/cli/output/test_output.py
- tests/cli/output/test_playeroutput.py
- tests/cli/test_cmdline.py
- tests/cli/test_cmdline_player_fifo.py
- tests/cli/test_cmdline_title.py
- tests/cli/test_main.py
- tests/cli/utils/test_path.py
- tests/cli/utils/test_progress.py
- tests/conftest.py
- tests/utils/test_named_pipe.py
- Remove `posix_only`/`windows_only` `skipIf` marker aliases
- Add `posix_only`/`windows_only` custom markers based on generic conditional test markers in the root conftest module
----
This avoid unnecessary `from tests` imports, and more conditional test markers can be added this way, if needed.
https://docs.pytest.org/en/7.2.x/example/markers.html#marking-platform-specific-tests-with-pytest
A side-effect of this is that the skipped tests don't get reported individually anymore, and pytest only summarizes tests skipped by those markers from conftest.py. Doesn't matter though.
- https://github.com/streamlink/streamlink/actions/runs/4375507930/jobs/7656312057#step:5:286
- https://github.com/streamlink/streamlink/actions/runs/4373964644/jobs/7652803269#step:5:286
> tests: add custom markers for conditional tests

- netlify.toml
Documentation previews should always be built when something in `src/` changes, not just in `src/streamlink/plugins/` or `src/streamlink_cli/argparser.py`. Otherwise, docstring changes of documented APIs will be missed.
> ci: fix netlify git-diff ignore list

- src/streamlink/plugins/steam.py
The `url` property of the JSON response is unset for offline streams and needs to be declared as optional.
I accidentally removed that in #5222...
There's also still a 404-segment-issue with DASH streams from steamcommunity.com which looks like it's caused by segments being requested a bit too early.
> plugins.steam: fix validation schema

- src/streamlink/stream/segmented.py
The `SegmentedStreamWriter`'s `_wait` event needs to be set before awaiting the shutdown of the thread-pool executor, otherwise the threads of the executor won't ever receive this signal. For example, queued segment downloads can't be cancelled because the event never gets set before awaiting the shutdown of the executor, so `wait()` calls in the executor's threads time out regularly and return `True`.
----
Fixes queued DASH segments being downloaded after closing the stream.
> stream.segmented: fix wait() in writer thread-pool

- src/streamlink/stream/dash.py
- src/streamlink/stream/dash_manifest.py
- tests/stream/test_dash_parser.py
Description/motivation in each commit message...
Example debug log:
```
[stream.dash][debug] Opening DASH reader for: ('1', 'video', '1') - video/mp4
[stream.dash][debug] Opening DASH reader for: ('1', 'audio', '1') - audio/mp4
[stream.dash][debug] video/mp4 segment initialization: downloading (2023-03-10T22:36:52.000000Z / 2023-03-10T23:40:42.016551Z)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist: ('1', 'video', '1')
[stream.dash_manifest][debug] Stream start: 2023-03-10 22:36:52+00:00
[stream.dash_manifest][debug] Current time: 2023-03-10 23:40:42.016825+00:00
[stream.dash_manifest][debug] Availability: 2023-03-10 23:40:36+00:00
[stream.dash_manifest][debug] presentationTimeOffset: 0:00:00; suggestedPresentationDelay: 0:00:03; minBufferTime: 0:00:03 …
```
> stream.dash: improve segment logging

- src/streamlink/stream/segmented.py
Follow-up of f234c690
Properly fix the `SegmentedStreamWriter`'s `_wait` Event when closing the thread.
Depending on which thread attempted to close the writer thread, the `close()` method's `self.reader.close()` call can block, leading to the `_wait` event to not get set until all threads have terminated and joined. So make sure to set the event first, so that all threads of the writer's thread-pool executor can be stopped first, for example segment downloads waiting for the segment's availability.
----
Follow-up of #5236
> stream.segmented: properly fix wait() in writer

- tests/cli/test_argparser.py
- tests/conftest.py
- tests/stream/test_dash.py
- tests/stream/test_ffmpegmux.py
- tests/stream/test_stream_json.py
- tests/stream/test_stream_to_url.py
- tests/test_api_websocket.py
- tests/test_plugin.py
- tests/test_plugin_userinput.py
- tests/test_session.py
No need to re-define the fixture multiple times
> tests: share session fixture

- src/streamlink/utils/args.py
- src/streamlink_cli/argparser.py
- tests/utils/test_args.py
- Replace `min` and `max` with `ge`, `gt`, `le` and `lt`
- Update and fix params/values of numeric CLI argparser arguments
- Rewrite `num()` tests
----
This rewrite is required for being able to add numeric CLI args which allow a min value of 0. This is currently not possible, as `num()` is checking for `value >= min`. Min values of int args were set to -1 because of this, but this doesn't work for float args (there currently are none of that kind, but I'm intending to add one).
- `--player-external-http-port` had an incorrect min value, as the default is set to 0
- `--stream-segment-threads` is now properly clamped between 1 and 10
- all int args have their min value set via `ge` instead of `gt`
> utils.args: update num() argparse utility function

- src/streamlink_cli/output.py
- tests/cli/output/test_playeroutput.py
- tests/cli/test_streamrunner.py
Instead of passing `os.devnull` file-handles to `subprocess.Popen`, use the `subprocess.DEVNULL` identifier for stdout/stderr streams.
This avoids `ResourceWarning`s in tests when the file-handles don't get closed despite never calling `PlayerOutput.open()`, as they were already opened in the `PlayerOutput`'s constructor, e.g. during test collection in parametrized tests without indirect fixtures.
Also call `PlayerOutput.close()` in tests where a *mocked* player output was explicitly opened.
----
**master**
https://github.com/streamlink/streamlink/actions/runs/4394894339/jobs/7696256649#step:5:282
> sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
**PR**
https://github.com/streamlink/streamlink/actions/runs/4397095519/jobs/7699992192#step …
> cli.output: use subprocess.DEVNULL in PlayerOutput

- dev-requirements.txt
- pyproject.toml
Ruff 0.0.255 introduced some changes, one of them being an incorrectly deprecated selector alias and a new rule for empty string comparisons which we don't want in test assertions.
Let's pinpoint the version of ruff in the dev-requirements, so that new releases don't break our linting config here immediately. If there's anything new and interesting, ruff's version can be bumped manually and new errors can be fixed in one go.
> tools: pinpoint ruff to 0.0.255 and fix rules

- src/streamlink/stream/dash_manifest.py
- tests/resources/dash/test_no_segment_list_or_template.mpd
- tests/stream/test_dash_parser.py
Fix segment duration in representations without a segment list or segment template and add test for segments of this kind.
> stream.dash: fix segment duration

- docs/deprecations.rst
- docs/ext_argparse.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- src/streamlink_cli/streamrunner.py
- tests/cli/test_main.py
- tests/cli/test_streamrunner.py
This adds support for suppressing the progress output when writing to a file by setting `--progress=no`.
Instead of adding a new `--no-progress` CLI argument, I decided to add `--progress={yes,no,force}` with default value `yes` and deprecate `--force-progress`.
```
$ streamlink --output=/dev/null httpstream://file:///dev/zero best
[cli][info] Found matching plugin http for URL httpstream://file:///dev/zero
[cli][info] Opening stream: live (http)
/dev/null
[download] Written 989.41 MiB to /dev/null (1s)
^C
Interrupted! Exiting...
```
```
$ streamlink --progress=no --output=/dev/null httpstream://file:///dev/zero best
[cli][info] Found …
```
> cli: add --progress={yes,no,force} CLI argument

- docs/install.rst
Solus had a critical infrastructure outage in early January, and apart from switching their static homepage to GitHub pages, they still haven't been able to get their stuff back online, including packaging and package updates.
I've never used that distro, but I've been observing this whole situation since at least the end of January, and it doesn't look like this will be resolved any time soon, if at all. There's zero communication from their project lead, who's responsible for this mess.
Let's remove the Solus entry from the install docs, to avoid dead links and to avoid making distro suggestions to new users. If they manage to recover the distro and packages get updated again, the entry can be restored.
> docs: remove solus from install docs

- src/streamlink/plugins/vk.py
- tests/plugins/test_vk.py
VK platform uses both vk.ru and vk.com domain names, but Streamlink only supports vk.com.
> plugins.vk: support .ru domain

- src/streamlink/stream/ffmpegmux.py
- src/streamlink/stream/hls.py
- tests/stream/test_hls.py
`ruff` 0.0.261 (not bumped in this PR) added some new rules which violate the access of class attributes without further usage. 
This is currently done in the HLS external audio tests, which access `master_stream.substreams` without being aware of the actual subclass, namely `HLSStream` or `MuxedHLSStream`. Since I didn't want to simply suppress the linting error, I decided to properly rewrite the tests using pytest. A bump of `ruff` is therefore not needed.
This then led to the generic type for `MuxedStream` being added in the first commit, with `MuxedHLSStream` defining `HLSSteam` as `TSubstreams`, so that `MuxedHLSStream.substreams[].url` can have proper typing information. Other usages of `MuxedStream` don't have the concrete substreams typing information added, because those usages …
> tests: rewrite HLS external audio tests

- src/streamlink_cli/output/__init__.py
- src/streamlink_cli/output/abc.py
- src/streamlink_cli/output/file.py
- src/streamlink_cli/output/player.py
- tests/cli/output/test_output.py
- tests/cli/output/test_playeroutput.py
- tests/cli/test_cmdline.py
- tests/cli/test_streamrunner.py
Let's reorganize `cli.output` a bit by splitting up the module into a subpackage, using separate modules for each output implementation and defining `Output` as a proper abstract base class
This should be done first before fixing/rewriting any of the output implementations.
I initially had another commit on this branch that made `HTTPServer` inherit from `Output`, which was actually the main intention of this PR, but this unfortunately breaks a couple of things in regards to the `--player-external-http` implementation. I will have a go at this later.
I also didn't touch any tests here. This can be done later when actually fixing the output implementations.
> cli.output: split up module into subpackage

- src/streamlink/plugins/openrectv.py
OPENREC.tv recently made a small change.
When fetching m3u8, it now returns 401 if "https://www.openrec.tv" is not specified in the referer.
So I avoid that error by adding a referer.
> plugins.openrectv: fix 401 error

- src/streamlink_cli/main.py
- src/streamlink_cli/output/__init__.py
- src/streamlink_cli/output/http.py
- src/streamlink_cli/output/player.py
- src/streamlink_cli/streamrunner.py
- src/streamlink_cli/utils/__init__.py
- tests/cli/test_streamrunner.py
- Move `streamlink_cli.utils.http_server` to `streamlink_cli.output.http`
- Rename `HTTPServer` to `HTTPOutput`
- Refactor `HTTPOutput`
- Inherit from `Output`
- Remove `bind()` and initialize socket in `start_server()`
- Split up `open()` into `accept_connection()` and `_open()`
- Split up `close()` into `_close()` and `shutdown()`
- Refactor `streamlink_cli.main`
- Update signature of `create_http_server()` and fix initialization
- Move `iter_http_requests()` logic into `output_stream_http()`
- Update http server logic in `PlayerOutput`
- Update `StreamRunner` according to new `Output` inheritance
----
Follow-up of #5288
Motivation: `HTTPServer` should inherit from `Output`, as it's used the same way in `StreamRunner` as the other output implementations.
Not 100% satisfied with these …
> cli.output: refactor HTTPOutput

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
Preferably, `--player-external-http` should be turned into a non-`store_true` argument with an argument value for being able to set the interface and port, so `--player-external-http-interface` and `--player-external-http-port` could be deprecated and removed eventually, but that would be an unnecessary breaking change. Making the value optional doesn't work either, e.g. when the following argv tokens are positional arguments like the stream URL or stream quality.
----
I also had a look at adding support for outputting the list of server URLs as JSON data, but I'm not sure how useful it is, considering that `--json` disables all logging output and considering that the process doesn't terminate after printing the JSON payload and keeps running.
----
```
$ streamlink --player-external-http …
```
> cli: add --player-external-http-interface argument

- .github/workflows/lint.yml
- docs-requirements.txt
- docs/_templates/sidebar/brand.html
- docs/conf.py
This updates the furo docs theme to the latest version.
The main intention however is bumping Sphinx to 6.x, which drops the unnecessary jQuery+underscore.js bloat:
https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022
Sphinx's minimum version requirement however is 5.x (defined by furo and the other build dependencies). I decided against bumping the min version to 6.x, because Sphinx is also used for building the man page. Some Linux distros are still on Sphinx 5 and I don't want to unnecessarily introduce incompatibilities for no reason.
Sphinx 6 also drops support for py37, but we've already dropped support for building docs on py37 a while ago in 46496db3698e4753154061aeb504e348270d3f9f
In order for being able to bump Sphinx to 5.x/6.x, myst-parser and …
> docs: bump furo to 2023.03.27

- docs/install.rst
Revert commit e99ccc44c9c8aa0656bed5c947b7fb8de74b9aaf
----
#5273
Apparently [they've recovered](https://getsol.us/2023/04/18/a-new-voyage/) and the package got updated, too, so there's no reason to not revert the changes.
> revert: docs: remove solus from install docs

- src/streamlink/plugins/mitele.py
```
$ streamlink --http-proxy "http://pass:user@host:8080/" https://www.mitele.es/directo/telecinco/ 360p_620k
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco/
[cli][info] Available streams: none_150k, 360p_620k_alt (worst), 360p_620k, 360p_1100k_alt, 360p_1100k, 576p_1900k_alt2, 576p_1900k_alt, 576p_1900k, 720p_3400k_alt, 720p_3400k, 720p_4800k_alt, 720p_4800k (best)
[cli][info] Opening stream: 360p_620k (hls)
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid …
```
> plugins.mitele: fix/add Origin header

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/test_main_setup_config_args.py
This disables loading any default or custom config files. Only arguments set directly will be parsed.
----
Default config + plugin config
```
$ streamlink -l debug twitch.tv/...
...
[cli][debug]  url=twitch.tv/...
[cli][debug]  --player-args=--cache=yes --demuxer-max-back-bytes=2G
[cli][debug]  --stream-segment-threads=2
[cli][debug]  --hls-live-edge=2
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-disable-reruns=True
[cli][debug]  --twitch-low-latency=True
```
Disabled default config + plugin config
```
$ streamlink --no-config -l debug twitch.tv/...
...
[cli][debug]  url=twitch.tv/...
[cli][debug]  --no-config=True
```
Custom configs …
> cli: add --no-config argument

- tests/cli/test_main.py
- tests/test_logger.py
Remove the attached logging handler from the streamlink root logger again after running logger tests
> tests: clean up root-logger state

- .github/workflows/useragents.yml
- bump Python to 3.11
- bump peter-evans/create-pull-request to v5 and resolve set-output GH actions deprecation
----
- https://github.com/streamlink/streamlink/actions/runs/4847083525
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.com/peter-evans/create-pull-request/commits/main
- https://github.com/peter-evans/create-pull-request/releases
> ci.github: bump deps of useragents workflow

- setup.cfg
`urllib3` is a transitive dependency of `streamlink`, via `requests`.
We define it here too because of the main CLI module which lists all direct dependencies from the package's metadata (via `importlib.metadata`) when the log level is <= debug, and listing urllib3 is useful. Another reason is that we're applying a couple of urllib3 overrides.
We don't specify an upper version limit though. This is only done by requests, namely `<1.27`. Now that urllib3 has published its 2.0 release last week, there are some issues. For some reason, the version doesn't always get resolved correctly by pip. I just noticed that in the `get-dependencies.sh` script of the Windows builds which unnecessarily downloads and tries to build urllib3 2.x until it falls back to 1.x. And then there was #5324 yesterday. …
> build: update version range of urllib3

- setup.cfg
- src/streamlink/plugin/api/http_session.py
- src/streamlink/plugin/api/http_session.pyi
- src/streamlink/session.py
- tests/test_session.py
- Bump max version constraint from `<2` to `<3`
- Fix `_PERCENT_RE` constant name in URL percent encoding override
- Fix `StreamlinkOptions._set_http_disable_dh()`, remove the override of the old `urllib3.util._ssl.DEFAULT_CIPHERS` list and instead add `streamlink.plugin.api.http_session.TLSNoDHAdapter` which reads the ciphers returned by Python's default SSLContext, adds `:!DH` to the updated ciphers list, and finally replaces the HTTP session's `https://` adapter
- Use `urllib3.util.create_urllib3_context()` for creating `SSLContext` objects in custom `HTTPAdapter`s
----
Resolves #5324 
urllib3 migration guide here:
https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html
> session: add support for urllib3 2.0

- CHANGELOG.md
Preliminary changelog for tomorrow (5.5.0 on May 5th :open_mouth:).
#5326 hasn't been merged yet. If there's been no review until tomorrow noon or afternoon, I'm going to merge it myself and publish this here afterwards, so we can have a stable release that's not broken when installing from PyPI without downgrading urllib3 to 1.26.15.
> release: 5.5.0

- src/streamlink/plugins/vimeo.py
- tests/plugins/test_vimeo.py
The current implementation extracts the player configuration URL from the page itself. However it looks like not all the pages contain the URL itself. This PR changes the behaviour to 
1. Get the authorization token from the viewer API. This also grabs the API base-URL (although that probably could be hard-coded)
2. Grab the video URI from the oembed API.
3. Use the previously grabbed API base-URL, video URI and authorization token to request the configuration URL.
Let me know if there are any issues (not sure I've used the schema validation correctly).
Tested with some random URLs and seems to work fine:
```
streamlink https://vimeo.com/771745400/840d05200c -l debug   
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.11
[cli][debug] Streamlink: 1.7.0+1115.gd2251c01 …
```
> plugins.vimeo: Fix unable to find configuration URL on some pages

- src/streamlink/plugin/api/http_session.py
Fix import of `create_urllib3_context` method on urllib3 <2.0.0. Only import from `urllib3.util.ssl_` module as a fallback.
----
Fixes #5332 
```
$ pip show urllib3 | grep Version
Version: 1.26.15
$ pytest -q tests/test_session.py | tail -n1
43 passed in 0.57s
```
```
$ pip show urllib3 | grep Version
Version: 2.0.2
$ pytest -q tests/test_session.py | tail -n1
43 passed in 0.57s
```
> http_session: fix create_urllib3_context import

- src/streamlink/plugins/vimeo.py
- tests/plugins/test_vimeo.py
- Split pluginmatcher into two
- Rewrite validation schemas
- Move data retrieval into separate methods
- Always query API on non-player URLs and don't try to find embedded config data first
- Add stream metadata
- Clean up stream collection and only include streams from at most one CDN in order to avoid unnecessary duplicates
----
Follow-up of #5331 
```
$ ./script/test-plugin-urls.py vimeo
:: Finding streams for URL: https://player.vimeo.com/video/176894130
:: Found streams: 720p_hls, 360p_hls, 540p_hls, 240p_hls, 1080p_hls, 240p, 240p+a52k, 240p+a120k, 240p+a237k, 360p, 360p+a52k, 360p+a120k, 360p+a237k, 540p, 540p+a52k, 540p+a120k, 540p+a237k, 720p, 720p+a52k, 720p+a120k, 720p+a237k, 1080p, 1080p+a52k, 1080p+a120k, 1080p+a237k, worst, best
:: Finding streams for URL: …
```
> plugins.vimeo: refactor plugin

- tests/stream/test_dash.py
Fix incorrect `called_once` assertion of the reader's `open()` method
> tests: fix DASH stream open tests

- tests/cli/utils/test_versioncheck.py
- tests/conftest.py
- tests/plugins/test_twitch.py
- tests/plugins/test_vk.py
- tests/stream/test_dash.py
- Add a globally shared `requests_mock` fixture which raises an `InvalidRequest` exception on unknown requests
- Replace similar fixture setups in various tests
> tests: add shared requests_mock fixture

- .github/workflows/main.yml
- script/install-dependencies.sh
Only add Linux test runner for now and install custom lxml wheel
----
Rel #5336
py312 is still alpha with the first beta release planned for 2023-05-22, but that doesn't matter. The dependency issues and test issues are all fixed on master now, so let's add a test runner to the CI config, so we can see if any further issues come up in the next couple of weeks/months.
The lxml wheel is built here (same repo as the old py311 temp lxml wheel repo, but renamed):
https://github.com/streamlink/temp-lxml-wheel-DO-NOT-USE
I couldn't manage to get the Windows wheel built, neither with the pre-built libxml2+libxslt libs, nor with self-built ones via vcpkg, so it's just the Linux wheel for now. Once there's an official lxml 5.0.0 release, this custom one can be removed and the Windows py312 CI …
> ci: add Python 3.12-dev test runner

- src/streamlink/plugins/youtube.py
For some reason, YouTube always sets the `playabilityStatus.status` value to `"OK"` on broken live streams, even if
`playabilityStatus.reason` is set to a specific error message.
Valid live streams and videos have set the `playabilityStatus.reason` value to `None`, so just check whether the value is truthy.
----
Resolves #5350 
I'd like to see a confirmation from someone else first that the assumption that `playabilityStatus.reason` is `None` on valid streams is actually correct. If it's not, then we unintentionally return no streams with these changes, which would be bad.
> plugins.youtube: check playabilityStatus.reason

- src/streamlink/stream/hls.py
- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls.py
- tests/stream/test_hls_playlist.py
Stop the stream early if no new segments were queued by the worker after the playlist's `targetduration * 2` has passed.
Use the timing factor of `2` to prevent potential issues with the reload timing of the playlist or when a stream discontinuity occurs.
----
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.1
> The `EXT-X-TARGETDURATION` tag **specifies the maximum Media Segment duration.**
> The EXTINF duration of **each Media Segment in the Playlist file, when rounded to the nearest integer, MUST be less than or equal to the target duration**; longer segments can trigger playback stalls or other errors. It applies to the entire Playlist file.
----
Resolves #2198
See https://github.com/streamlink/streamlink/issues/2198#issuecomment-1534150416
Before this can get merged, …
> stream.hls: stop stream early on missing segments

- dev-requirements.txt
- src/streamlink/plugins/dogan.py
- src/streamlink/plugins/mildom.py
No big changes, just a bump to ruff's latest version.
https://github.com/charliermarsh/ruff/releases/tag/v0.0.269
The included code changes aren't required right now and would only be needed in an upcoming version of ruff because some of the new/updated linting rules aren't selected by default now. See the release notes in regards to the updated `E` selector. I didn't feel like enabling everything explicitly now because these config changes would need to be reverted later again, which is unnecessary.
> tools: bump ruff to 0.0.269

- src/streamlink/session.py
- tests/conftest.py
- tests/test_session.py
This rewrites the session tests using pytest.
Split up into multiple commits. Some of them could be squashed, but I didn't feel like doing that because it makes tracking the individual changes more difficult...
There's also a fix included for a KeyError being raised when the `interface` session option gets unset when it's already unset.
> tests.session: refactor tests

- src/streamlink/utils/named_pipe.py
- tests/utils/test_named_pipe.py
- Refactor tests using pytest
- Add missing tests for handling close() exceptions
- Fix typing information of OS-dependent `NamedPipe` export
> tests: refactor named_pipe tests

- tests/cli/test_console.py
- tests/stream/test_file.py
- tests/stream/test_hls.py
- tests/stream/test_hls_playlist.py
- tests/stream/test_stream_wrappers.py
- tests/test_api_http_session.py
- tests/utils/test_crypto.py
- tests/utils/test_module.py
- tests/utils/test_parse.py
This refactors all remaining `unittest.TestCase`-based tests apart from those which
- are blocked by open PRs
- `Options`/`Argument`/`Arguments` tests (#5033)
- CLI `FileOutput`/`PlayerOutput` tests (#5310)
- CLI -> player args acceptance tests (#5310)
- are `streamlink_cli.main` tests
- are HLSStream integration tests
> tests: refactor unittest.TestCase tests

- docs/plugins.rst
Just a short explanation of what plugins actually are and what they do, and that protocol plugins are available even though they are not included in that list.
> docs: improve header text of the plugins page

- src/streamlink/plugins/dash.py
- src/streamlink/plugins/hls.py
- src/streamlink/plugins/http.py
- tests/plugins/test_dash.py
- tests/plugins/test_hls.py
- tests/plugins/test_http.py
Ensure that the entire input is matched.
----
Fixes #5366 
Previously it was possible to trick the implicit matcher of the HLS and DASH plugin to only match parts of the URL due to how the optional parameters are matched. Adding the end-of-string anchor to each regex fixes that.
> plugins: more strict protocol plugin matchers

- src/streamlink/plugin/api/http_session.py
- tests/test_api_http_session.py
- Refactor `HTTPSession.json()` classmethod:
The JSON encoding already gets determined by `json.loads()` when passing bytes data, with support for byte order marks, so calling the `HTTPSession.determine_json_encoding()` classmethod is not needed.
- Improve performance of `HTTPSession.determine_json_encoding()`:
Apply simple bitmasks on the first four bytes instead of building a list of bytes and checking for null-byte positions. Since this classmethod is not used anymore, deprecate it for now to avoid an unnecessary breaking change.
----
See `json.detect_encoding()` which gets called by `json.loads()` for `byte` inputs:
- https://github.com/python/cpython/blame/v3.12.0b1/Lib/json/__init__.py#L244-L271
- https://github.com/python/cpython/blame/v3.7.0/Lib/json/__init__.py#L244-L271
> http_session: refactor HTTPSession.json()

- src/streamlink/plugins/twitch.py
First things first, let's fix the error message not being parsed correctly in the access token error response...
#5370 
```
$ streamlink twitch.tv/gamesdonequick
[cli][info] Found matching plugin twitch for URL twitch.tv/gamesdonequick
[plugins.twitch][error] Error: failed integrity check
error: No playable streams found on this URL: twitch.tv/gamesdonequick
```
> plugins.twitch: get access token error message

- src/streamlink/plugins/mediavitrina.py
- tests/plugins/test_mediavitrina.py
```
$ streamlink https://player.mediavitrina.ru/gpm_tnt_v2/tnt/vitrinatv_web/player.html best
[cli][info] Found matching plugin mediavitrina for URL https://player.mediavitrina.ru/gpm_tnt_v2/tnt/vitrinatv_web/player.html
[plugins.mediavitrina][error] Stream is geo-restricted
error: No playable streams found on this URL: https://player.mediavitrina.ru/gpm_tnt_v2/tnt/vitrinatv_web/player.html
```
```
$ streamlink-ssh https://player.mediavitrina.ru/gpm_tnt_v2/tnt/vitrinatv_web/player.html best
[cli][info] Found matching plugin mediavitrina for URL https://player.mediavitrina.ru/gpm_tnt_v2/tnt/vitrinatv_web/player.html
[cli][info] Available streams: 240p_710k (worst), 360p_1200k, 480p_3400k, 720p_5000k, 1080p_8500k (best)
[cli][info] Opening stream: 1080p_8500k (hls)
[cli][info] Starting …
```
> plugins.mediavitrina: update re_url_json

- dev-requirements.txt
- pyproject.toml
- tests/plugins/test_turkuvaz.py
This explicitly adds the experimental rules added in ruff 0.0.269. I initially didn't want to add these because they will have to be removed again at some point when they are included in the "E" selector by default (which we already set). Since there are already code style cleanups required, let's just add them now, so linting issues get caught early.
https://github.com/astral-sh/ruff/releases/tag/v0.0.269
> tools: bump ruff to 0.0.272 and fix issues

- pyproject.toml
The stacklevel of the DeprecationWarning raised by `pkg_resources` got changed in setuptools 68.0.0, so we have to adjust our warnings filter.
`pycountry` is still importing `pkg_resources`.
----
From the last scheduled CI runner on master:
https://github.com/streamlink/streamlink/actions/runs/5328587588/jobs/9653353840#step:5:268
> ```
> ../../../../../opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pycountry/__init__.py:10
>   /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pycountry/__init__.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>     import pkg_resources
> ```
> tests: ignore DeprecationWarning in pycountry

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
`streamlink_cli.argparser` should be able to set session options which default to `True` to `False`. Fix that by checking whether the argument dest on the argparse namespace is not `None` (aka set).
Currently, there are no session options which default to `True`.
----
Required for being able to add `--webbrowser=false` with respective default value of `True` on the Streamlink session.
> cli.argparser: allow disabling session options

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
Revert 9c6dd568216da4e20be32e85413551a8cb2219e4
Fixes #5395 
Let's revert this for now. I will have a proper look at this tomorrow.
> revert: cli.argparser: allow disabling session options

- docs/api.rst
- docs/api/exceptions.rst
- docs/api/plugin.rst
- docs/api/session.rst
- docs/api/stream.rst
- docs/api/streamlink.rst
- docs/api_guide.rst
- docs/deprecations.rst
- src/streamlink/api.py
- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/http.py
The API docs should be split up for better legibility (I intend on adding docs for the webbrowser API). This also removes an unnecessary layer in the sidebar on the right. Some references needed an update, so I checked for the rest as well, but I didn't check thoroughly...
Current mess:
https://streamlink.github.io/api.html
New (mess):
https://deploy-preview-5398--streamlink.netlify.app/api.html
> docs: split API docs into multiple documents

- .codecov.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- dev-requirements.txt
- docs/install.rst
- pyproject.toml
- setup.cfg
- setup.py
- src/streamlink/logger.py
- src/streamlink/options.py
- src/streamlink/plugin/api/validate/_schemas.py
- src/streamlink/session.py
- src/streamlink/stream/dash_manifest.py
- src/streamlink_cli/compat.py
- src/streamlink_cli/main.py
- tests/cli/test_main.py
- tests/test_plugin.py
- tests/utils/test_processoutput.py
Opening this early as a draft.
py37 will see its EOL in about 2 months, on 2023-06-27
https://endoflife.date/python
The changes of this PR include:
1. Official removal of py37 support from the package metadata and docs, as well as updates to the CI config
2. Tooling config updates (mypy / ruff)
3. Removal of compat imports
4. Language/grammar updates of previously annotated stuff
This will obviously be a breaking change, so ideally, other breaking changes should be included in that release.
----
Additional tasks after merging these changes:
- Class/function signature changes with positional-only / keyword-only parameters (py38):
Perfect opportunity to fix some old issues with certain public APIs, e.g. `HLSStream.parse_variant_playlist()`, and more.
----
Everything else in regards to py38 …
> Drop support for Python 3.7

- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink/plugins/twitch.py
- src/streamlink/session.py
- src/streamlink/stream/hls.py
- src/streamlink_cli/main.py
- tests/cli/test_plugin_args_and_options.py
- tests/plugins/test_twitch.py
- tests/test_options.py
- tests/test_plugin.py
- tests/test_plugins.py
- tests/test_session.py
These are breaking changes of the `Streamlink` session and `Plugin` APIs.
Opening this as a draft for now, even though it's pretty much final, because I don't think that this has to be merged now. It simply fixes an old design flaw and is not too important and should be included with other breaking changes in the future in one go.
----
Two separate changes:
As mentioned in #5011, turning `Plugin.options` from a plugin class attribute into a plugin instance attribute is related to the removal of the `Plugin.bind()` class method in #4744 / #4768, and ideally should've been part of the `5.0.0` release. While `5.0.0` removed `Plugin.bind()`, the breaking changes were actually in the `Streamlink` session class where `Plugin.bind()` was called internally, and compatibility wrappers were added …
> Move plugin options to plugin instances and remove global plugin arguments

- src/streamlink/plugin/api/validate/__init__.py
- tests/test_api_validate.py
#5401 
https://streamlink.github.io/deprecations.html#deprecation-of-plugin-api-validate-text
> plugin.api.validate: drop deprecated text alias

- dev-requirements.txt
- docs/install.rst
- setup.cfg
- src/streamlink/utils/path.py
- src/streamlink/utils/socket.py
- src/streamlink/webbrowser/__init__.py
- src/streamlink/webbrowser/chromium.py
- src/streamlink/webbrowser/exceptions.py
- src/streamlink/webbrowser/webbrowser.py
- tests/utils/test_path.py
- tests/webbrowser/conftest.py
- tests/webbrowser/test_chromium.py
- tests/webbrowser/test_webbrowser.py
Part 2/4 of #5380 
Opening this as a draft was well until I have the rest finished.
----
This
1. Adds a utility executable resolver function with support for custom values, default names and fallback paths.
2. Adds a utility function for finding an available port on a specific network interface
- No tests, because I don't think mocking everthing here makes sense, and neither does running this without mocking
3. Adds the `trio` dependency, as well as `pytest-trio` and `trio-typing`
- `trio-typing` looks like it's going to get merged into `trio` soon
- `pytest-trio` is used for initializing the runloop in async tests, similar to `pytest-asyncio`.
Having implementations for both `asyncio` and `trio` seems to cause minor issues with trio's runloop in the tests, and on Windows it triggers a …
> webbrowser: implement Webbrowser / ChromiumWebbrowser

- docs/install.rst
- setup.cfg
- src/streamlink/webbrowser/cdp/__init__.py
- src/streamlink/webbrowser/cdp/connection.py
- src/streamlink/webbrowser/cdp/exceptions.py
- tests/webbrowser/cdp/__init__.py
- tests/webbrowser/cdp/conftest.py
- tests/webbrowser/cdp/test_connection.py
Part 3/4 of #5380
This currently includes the commits of #5381 (part 1) and #5386 (part 2), because this code is needed for the CDP connection stuff. Once those PRs have been merged into master, I will rebase this branch.
So the only relevant commits of this PR are the ones after the merge commit. See the check marks of the HEAD commits of those other branches.
----
This
1. Adds the `trio-websocket` and `typing-extensions` runtime dependencies.
- A bit unfortunate that we have to add another dependency for websockets, but it is what it is... Async I/O via trio is a requirement for a proper implementation.
- `typing-extensions` is required, because I needed `TypeAlias` for making the `CDPEventListener`'s typing work. This conveniently also adds `Self` and other things.
2. Implements the …
> webbrowser.cdp: implement CDP connection

- docs/api.rst
- docs/api/exceptions.rst
- docs/api/webbrowser.rst
- src/streamlink/session.py
- src/streamlink/webbrowser/cdp/__init__.py
- src/streamlink/webbrowser/cdp/client.py
- src/streamlink_cli/argparser.py
- tests/webbrowser/cdp/test_client.py
Part 4/4 of #5380
This currently includes the commits of #5381 (part 1), #5386 (part 2) and #5388 (part 3), because this code is needed for the CDP connection stuff. Once those PRs have been merged into master, I will rebase this branch. The base of the PR-branch is also outdated, hence the current merge-conflict (API docs related).
----
This
1. Adds various `webbrowser-...` session options and `--webbrowser-...` CLI arguments and finally implements the `CDPClient` class which plugins can use for extracting data from websites. It manages launching the Chromium-based web browser, connects to its remote debugging interface and establishes a CDP session instance. The API for performing the CDP session tasks is implemented in the `CDPClientSession` class, namely navigating, adding …
> webbrowser.cdp: implement CDP client

- src/streamlink/webbrowser/chromium.py
- tests/webbrowser/test_chromium.py
This adds Microsoft Edge to the Chromium fallback list on win32.
It actually prioritizes MS Edge over Google Chrome, which I think is a better solution because on Windows it's guaranteed that Edge is installed. Both are non-free browsers on a non-free OS, so I don't care one single bit about what people will say about edge vs chrome.
This does only affect the fallback paths, which means `chromium`, etc. is still looked up first in the `PATH` env var, even though this won't work on Windows unless people have special setups.
For those users of Windows who don't want to run Edge, they either won't notice it because it runs headlessly by default, or they can change it via the `--webbrowser-executable` option.
> webbrowser.chromium: add MSEdge fallback on win32

- src/streamlink/webbrowser/chromium.py
- src/streamlink/webbrowser/webbrowser.py
- tests/webbrowser/test_chromium.py
- tests/webbrowser/test_webbrowser.py
This replaces
> Could not resolve web browser executable
>
> Could not resolve web browser executable: /custom/path/...
with
> Could not find Chromium-based web browser executable: Please set the path to a supported web browser using --webbrowser-executable
>
> Invalid web browser executable: /custom/path/...
if none of the supported executable names or fallback paths could be resolved, e.g. when Chromium and others are not installed.
> webbrowser: improve resolve error message

- script/install-dependencies.sh
lxml has published 4.9.3 with `cp312` wheels for `manylinux_2_28` and `win_amd64`
https://pypi.org/project/lxml/4.9.3/#files
~~This means our custom lxml wheel is not needed anymore and the Windows CI runner can be enabled. Tests will fail because of other issues which will get fixed by #5418.~~ rebased
> ci.github: remove custom lxml cp312 wheel

- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/mjunoon.py
- src/streamlink/plugins/steam.py
- src/streamlink/plugins/ustvnow.py
- src/streamlink/plugins/webtv.py
- src/streamlink/stream/hls.py
- src/streamlink/utils/crypto.py
- tests/stream/test_hls.py
Had this on the to-do list for a while:
Re-export pycryptodome / pycryptodomex stuff in a single place, so packagers don't have to maintain dozens of patches.
- https://github.com/Legrandin/pycryptodome#pycryptodome
- https://src.fedoraproject.org/rpms/python-streamlink/blob/712c7a9a95dbd63d68314b0e4e55a51fe7cff8f5/f/python-streamlink-5.5.1-pycryptodomex.patch
Drawback of this approach is that this imports all the stuff at once, but we do that anyway since the Streamlink session is loading all plugins at once, too. And the stream implementations which import crypto stuff get loaded as well.
> utils.crypto: move Crypto imports to utils module

- docs/api/stream.rst
- docs/api_guide.rst
This removes unnecessary sections on the api/stream docs page and fixes the incorrect header.
> docs: fix header and sections in api/stream

- src/streamlink/plugins/filmon.py
- src/streamlink/plugins/mildom.py
- src/streamlink/plugins/oneplusone.py
- src/streamlink/plugins/twitch.py
- src/streamlink/stream/dash.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/http.py
Two commits:
1. A correction of d314c5b which shouldn't go into a stable release like this. The parameter removal is not a breaking change since it was only added to `master` so far.
Any keywords arguments now get passed to `HLSStream` and `MuxedHLSStream` using the already existing variable keyword arguments (`**kwargs`) which then get filtered when making HTTP session calls.
This also cleans up the API documentation a bit by having consistent names.
2. A "light" breaking change:
The `session_` argument was named that way during the Livestreamer project because `session` was supposed to be included in the variable keyword arguments (`**kwargs`) because of (an old version of) `requests` (see 0308347 and 39008e9).
Positional-only / keyword-only arguments have only become available with the …
> stream: fix signatures of Stream classes & methods 

- src/streamlink/webbrowser/cdp/connection.py
- src/streamlink_cli/argparser.py
- Update help text of `--webbrowser` CLI argument
- Add CDP docs link to `CDPBase` class docstring
> webbrowser: minor docs improvements

- src/streamlink/plugins/twitch.py
- src/streamlink/utils/random.py
- tests/plugins/test_twitch.py
- tests/utils/test_random.py
Resolves #5370
Also see #5380 
This PR implements the client-integrity token acquirement for the Twitch access token API endpoint, based on Streamlink's newly added webbrowser API (#5380).
Not fully ready yet, hence why I'm opening this as a draft. I am primarily looking for early feedback from users.
Before I'm going to properly open this, I'll have to update the commit message body and add some tests.
----
- It adds the `--twitch-purge-client-identity` plugin argument
- If available, it uses the device-id and client-integrity token from the plugin cache (client-integrity tokens expire after 16 hours)
- If no cached device-id + client-integrity token were found or if they expired, then it generates a new device-id and then imports and calls the webbrowser API
- In order to acquire the CI …
> plugins.twitch: webbrowser-based client-integrity

- src/streamlink/plugins/mitele.py
Fixes #5435 
One of the items of the CDN-token API response was empty which led to the 403 HTTP response (since the plugin yields all possible streams). This simply skips items with empty CDN-tokens.
@ROBGagn please check and verify
```
$ streamlink -l debug --http-proxy=... https://www.mitele.es/directo/boing
[cli][debug] OS:         Linux-6.3.12-1-git-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.5.1+106.g31d038d2
[cli][debug]  certifi: 2023.5.7
[cli][debug]  pycryptodome: 3.18.0
[cli][debug] …
```
> plugins.mitele: fix missing CDN token

- docs/deprecations.rst
- docs/index.rst
- docs/migrations.rst
This properly separates deprecations from breaking changes + migration hints. The deprecations page previously was a mixture of both without a clear distinction.
Breaking changes without any deprecations or migrations won't be included on the migrations page. That's what the changelog is for.
I've also changed the section headlines according to the page they are on, added hints when a deprecation got removed, and also added links to the issue/PR which introduced a deprecation or which argued for the change, as well as the PR which applied the breaking change.
Technically, the migration hints from the `Plugin.can_handle_url()` / `Plugin.priority()` changes should be moved to the migrations page. I left untouched it for now.
See the rendered docs preview. There's a high chance I messed …
> docs: add migrations page, rewrite deprecations

- docs/api.rst
- docs/api/options.rst
- docs/api/plugin.rst
- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session.py
- Add `api/options` page and document `Options` class
- Move `Argument` and `Arguments` from plugin page to options page
- Add docstrings for `Streamlink.options` and `Plugin.options`
----
https://github.com/streamlink/streamlink/pull/5033#issuecomment-1640105400
> docs: add docs page for Options class

- docs-requirements.txt
- Bump max version of sphinx from <7 to <8
- Bump max version of myst-parser to <3
- Pinpoint sphinx-design to 0.5.0
- Properly group dependencies by type
----
This doesn't bump the version of furo (didn't check for new versions yet), so it's still building with sphinx 6 and not with sphinx 7. The other bumped dependencies only bump their respective dependencies, including support for sphinx 7, with additional minor fixes. myst-parser bumped its major version because it has dropped support for py37 which we already did.
I decided to pinpoint the version of sphinx-design, because similar to the furo theme, it's responsible for the rendered HTML output, and we want that to be stable.
I will have a look at newer furo versions separately.
----
- …
> docs: bump and reorder docs-requirements

- dev-requirements.txt
- Properly group dependencies by type
- Remove typing-extensions from dev-requirements, as it's already a runtime dependency since 6.0.0
> chore: reorder dev-requirements

- docs-requirements.txt
- Bump furo sphinx theme to latest version
- Require sphinx >=6.0.0
----
- https://github.com/pradyunsg/furo/blob/main/docs/changelog.md
- https://www.sphinx-doc.org/en/master/changes.html
> docs: bump furo theme to 2023.07.26

- src/streamlink/plugins/huya.py
ref #5466 
Doesn't hurt and don't see any issues. No idea why their API returns non-TLS URLs, but since it's a progressive HTTP stream, I'm not even wondering...
```
$ streamlink -l debug https://www.huya.com/476318 best
[cli][debug] OS:         Linux-6.4.6-1-git-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 6.0.0+4.gca4ca90c
[cli][debug]  certifi: 2023.7.22
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1 …
```
> plugins.huya: force https stream URLs

- src/streamlink/session.py
- tests/plugin/testplugin.py
- tests/test_session.py
Ref https://github.com/streamlink/streamlink/issues/5468#issuecomment-1657212207
This also removes the unnecessary `TestPlugin.options` override which was missed in #5033
> session: add options argument to streams()

- src/streamlink/session.py
- src/streamlink/stream/hls.py
- src/streamlink_cli/argparser.py
- tests/stream/test_hls.py
Resolves #5476 
Descriptions in the commit messages.
Second commit increases the value from 2 to 3, which is a bit more lenient, so unstable live streams don't cause unnecessary interruptions. This comes at the cost of stable live streams without an endlist tag being stopped a bit later.
Not sure if the name of the CLI-argument and session-option makes sense and if there's a better one that's easier to understand.
----
As a reminder:
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.1
> The EXT-X-TARGETDURATION tag specifies the **maximum Media Segment duration**. The EXTINF duration of each Media Segment in the Playlist file, when rounded to the nearest integer, **MUST be less than or equal to the target duration**; longer segments can trigger playback stalls or other errors. …
> stream.hls: add --hls-segment-queue-threshold 

- src/streamlink/utils/processoutput.py
- tests/utils/test_processoutput.py
Try to drain the stdout/stderr streams first before handling the onexit task, so the overall result can be processed correctly
----
Fixes #5461 
The issue is caused by `process.wait()` resolving first in the `onexit` task, so the result of the `done` future gets set without the async interator(s) of the stdout/stderr stream(s) being drained in the `onoutput` task(s) first.
In my eyes, this looks like an issue in asyncio's subprocess implementation... No idea if this actually fixes #5461, but reordering the tasks at least made the added test pass while not reordering them made it fail.
> utils.processoutput: reorder asyncio tasks

- .github/ISSUE_TEMPLATE/1_plugin_issue.yml
- .github/ISSUE_TEMPLATE/2_bug_report.yml
- .github/ISSUE_TEMPLATE/3_plugin_request.yml
- .github/ISSUE_TEMPLATE/4_feature_request.yml
1. This makes the header text more clear
2. A specific version string is now required for plugin issues and bug reports instead of the dropdown, so people are asked to actually check their used version
3. Random cleanups and fixes
Checked my test repo for rendering issues. Everything looked fine...
> chore: update GitHub issue templates

- src/streamlink/plugins/nicolive.py
- src/streamlink/plugins/twitch.py
- src/streamlink/utils/times.py
- src/streamlink_cli/argparser.py
- tests/plugins/test_nicolive.py
- tests/utils/test_times.py
- Add support for floats via `hours_minutes_seconds_float()`
- Add support for negative timestamps
- Rewrite regexes and be as strict as possible
- Rewrite and parametrize tests with an extensive list of formats
- Update cli.argparser/plugin arguments using `hours_minutes_seconds()`
----
Related: #5493
> utils.times: rewrite hours_minutes_seconds()

- CHANGELOG.md
Release date is set to tomorrow. I will merge and publish if nothing else comes up in the mean time, so the recent HLS changes and bugfixes are out on a stable release.
> release: 6.1.0

- src/streamlink_cli/main.py
- tests/cli/test_main.py
- https://docs.python.org/3/library/ssl.html
- https://docs.python.org/3/library/ssl.html#ssl.OPENSSL_VERSION
- https://peps.python.org/pep-0644/
Relevant:
- #5425
> cli: log OpenSSL version in debug log

- src/streamlink/plugins/ustreamtv.py
- src/streamlink/stream/dash.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/segmented.py
- Turn `SegmentedStream{Writer,Worker,Reader}` into generic classes with segment and segment-result types
- Fix typing information of the writer's queue
- Add missing typing information
- Update segmented stream classes accordingly
----
#5498
Next step will be fixing the whole `Segment` mess by adding a common `BaseSegment`. This will require more changes due to how the current segments are implemented and structured.
> stream.segmented: fix and add more typing

- src/streamlink/plugins/twitch.py
- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls_playlist.py
- Declaratively define tag parsers explicitly using a decorator instead of relying on the method name format
- Build the tag-parser mapping when creating the parser class, and don't build it on the parser class when first instantiating it
- Update parser subclasses (Twitch)
- Update tests
> stream.hls: refactor tag parser mapping

- src/streamlink/logger.py
- tests/test_logger.py
- Always set encoding of `logging.FileHandler` to `utf-8`
- Update and add tests
----
Fixes #5531
> logger: fix missing FileHandler encoding

- src/streamlink/plugins/nicolive.py
Resolves #5515 
I am not sure though if this could break some streams, because metadata is not treated optionally, so if it's missing, then the validation schema could fail.
@SecondaryH could you please check some more streams (preferrably with a login - which I don't have) and verify these changes? Thanks!
----
Some streams I've checked:
1\. From the tests file:
```bash
streamlink --json https://live.nicovideo.jp/watch/co2619719 best | jq .metadata
```
```json
{
"id": "lv342666086",
"author": "novoll(千葉県民)",
"title": "【SFC】魔法騎士レイアース 初見プレイ【13枠目】"
}
```
2\. Picked randomly from their site
```bash
streamlink --json https://live.nicovideo.jp/watch/lv342666014 best | jq .metadata
``` …
> plugins.nicolive: add metadata

- src/streamlink/plugins/hiplayer.py
- tests/plugins/test_hiplayer.py
Fixes #5524
```
$ ./script/test-plugin-urls.py hiplayer
:: Finding streams for URL: https://alwasat.ly/live
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTV1
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTVSports
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
```
----
This also drops rotana.net from the plugin because the site appears to be completely different now:
https://rotana.net/ar/channels#/live/rotana_CinemaKSA
The site had a dedicated plugin in the past and then got merged into the hiplayer plugin:
- #4512
- #4507
> plugins.hiplayer: fix base64 data, drop rotana.net

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- src/streamlink_cli/output/player.py
- tests/cli/output/test_player.py
- tests/cli/test_argparser.py
- tests/cli/test_cmdline.py
- tests/cli/test_main.py
- tests/conftest.py
Resolves #5530
This adds the `--player-env KEY=VALUE` CLI argument, which allows adding environment variables to the spawned player process (on top of the inherited ones). The CLI argument can be repeated for being able to add multiple env vars. As mentioned in #5530, the intended purpose here is to be able to set env vars from the config files.
> cli: add --player-env argument

- src/streamlink/stream/hls.py
- tests/stream/test_hls.py
Fixes #5536 
@Hakkin Please give it a try. Thanks!
> stream.hls: fix endlist on empty playlist reload

- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/useragents.yml
- https://github.com/actions/checkout/releases/tag/v4.0.0 (nodejs 16 ([EOL in 4 days](https://endoflife.date/nodejs)) -> 20)
- https://github.com/peter-evans/create-pull-request/commits/6d9c0cdf5825c01278b6e63a0788434e6b3c5e27 (latest commit - only minor fixes, docs and deps changes)
> ci.github: bump versions

- src/streamlink/plugins/ustreamtv.py
Ref #5498
Quick refactor in preparation for the segmented stream changes with a common base `Segment`
----
Is this platform even used by anyone anymore?
NASA went to YT a while ago and I can't find any other live channels. It's already suspicious that googling "ustreamtv" returns the Streamlink plugin file on GitHub in the 3rd place and that there's only one other channel returned by google when searching for "video.ibm.com" which is also offline and dead.
@liamkennedy do you know more? You've opened a couple of issues about ustreamtv in the past.
https://en.wikipedia.org/wiki/IBM_Cloud_Video
> plugins.ustreamtv: refactor using dataclasses

- .codecov.yml
- MANIFEST.in
- build_backend/__init__.py
- build_backend/test_build_backend.py
- dev-requirements.txt
- pyproject.toml
- script/build-and-sign.sh
- tests/conftest.py
- Add custom build backend which overrides certain hooks
- Include custom build backend in sdists via `MANIFEST.in`
- Remove `build>=1.0.0` workaround from `build-and-sign.sh`
- Add build backend tests, update order of tests and coverage config
----
See
- #5548
- #5550
----
Non-editable and editable installs worked fine, and so did building the sdists and wheels, as well as building/installing from the newly built sdist.
Before I'm going to merge this, I'll have a second check tomorrow first, just in case...
> build: override setuptools build backend

- docs/install.rst
Unlike Debian backports, no instructions on how to add/enable the required `edge/testing` package repo, for reasons noted in the linked wiki.
> docs: add Alpine Linux to install docs

- src/streamlink/plugins/nos.py
- tests/plugins/test_nos.py
Fixes #5555
@ltguillaume could you please check and verify?
URLs of the type `https://nos.nl/artikel/...` are explicitly not supported, because adding a validation schema for getting the HLS URLs is a bit ridiculous (different JSON payload, nested objects, multiple kinds of video schemas).
----
```
$ ./script/test-plugin-urls.py nos
:: Finding streams for URL: https://nos.nl/collectie/13781/livestream/2385081-ek-voetbal-engeland-schotland
:::: Content is inaccessible or may have expired
:: Finding streams for URL: https://nos.nl/collectie/13951/video/2491092-dit-was-prinsjesdag
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://nos.nl/live …
```
> plugins.nos: rewrite and fix plugin

- .github/workflows/main.yml
- script/install-dependencies.sh
Ref #5544 
- Enable Python `3.12-dev` test runner on Windows
- Install custom-built cffi wheel on py312/Windows
- https://github.com/streamlink/temp-dependency-builds-DO-NOT-USE/blob/7418285a9f0eb4b186873d681a77e1c49b6af811/.github/workflows/cffi.yml
- https://github.com/streamlink/temp-dependency-builds-DO-NOT-USE/releases/tag/cffi-20230923-1
> ci.github: add py312-dev test runner on Windows

- src/streamlink/plugins/pandalive.py
- tests/plugins/test_pandalive.py
Fixes #5568
This also changes the pluginmatcher URL regex, so that it only accepts `/live/play/CHANNELNAME` URLs.
@feisao please check
----
```
$ ./script/test-plugin-urls.py pandalive
:: Finding streams for URL: https://www.pandalive.co.kr/live/play/pocet00
:::: 종료된 방송입니다.
:: Finding streams for URL: https://www.pandalive.co.kr/live/play/rladbfl1208
:::: Broadcast type: live
:: Found streams: 160p, 360p, 480p, 720p60, worst, best
```
> plugins.pandalive: fix live/play API call

- pyproject.toml
- script/install-dependencies.sh
Resolves #5544
This adds official support for the upcoming Python 3.12 release in a couple of days to the metadata of Streamlink's sdists/bdists.
https://peps.python.org/pep-0693/
cffi 1.16.0 has finally been released yesterday with support for py312, which means we can finally label Streamlink as py312 compatible and remove the custom-built wheel:
https://github.com/python-cffi/cffi/releases/tag/v1.16.0
cffi is a transitive dependency on Windows via trio, and it's optionally required (without declaring it as a dependency) by pycryptodome:
- https://github.com/python-trio/trio/blob/v0.22.2/setup.py#L93
- https://github.com/Legrandin/pycryptodome/blob/v3.19.0/lib/Crypto/Util/_raw_api.py#L85
> build: add Python 3.12 to package classifiers

- CHANGELOG.md
Let's publish a new release with official Python 3.12 support.
The planned release for 3.12 is today, but I've set the release date of Streamlink 6.2.1 for tomorrow.
https://peps.python.org/pep-0693/#release-schedule
The recent build-backend changes shouldn't justify bumping the minor version, as there are no changes when building, and it's not a new feature either, so it's just a minor version bump.
----
Btw, I've added the hacktoberfest tag to the repo a week ago in hopes for some more contributions this month. Then I noticed after registering my account that they're not rewarding people with t-shirts anymore and moved towards NFT-like nonsense. No idea if this non-code release-PR will be considered a bad PR now and void my participation (especially when I will merge it myself), but …
> release: 6.2.1

- src/streamlink/plugin/plugin.py
Fix a small typo I've discovered when reading the source: "QUALITY_WEIGTHS_EXTRA" -> "QUALITY_WEIGHTS_EXTRA"
> chore: fix typo

- src/streamlink/plugins/goodgame.py
- tests/plugins/test_goodgame.py
Fixes #5581
Fixes #5585
Fixes #5584
Fixes #5583 
@IosifShmidt
Please check and verify.
----
1. This now queries their API instead of finding the data in the page's embedded JSON.
However, URLs using the plugin's default matcher without the `/channel/` prefix appear to not have an API endpoint for querying the channel key, so it still needs to be acquired from the embedded JSON.
https://goodgame.ru/html/api4docs/index.html
That should work fine though:
```
$ streamlink -l debug goodgame.ru/Penta | grep plugins.goodgame
[plugins.goodgame][debug] channel='Mashinasmert'
[plugins.goodgame][debug] Channel appears to be offline
```
```
$ streamlink goodgame.ru/doesnotexist
[cli][info] Found matching plugin …
```
> plugins.goodgame: rewrite using API

- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/afreeca.py
- src/streamlink/plugins/ltv_lsm_lv.py
- src/streamlink/plugins/pluto.py
- src/streamlink/plugins/tv8.py
- src/streamlink/plugins/twitch.py
- src/streamlink/stream/hls.py
- src/streamlink/stream/hls_playlist.py
- tests/stream/test_hls.py
- tests/stream/test_hls_filtered.py
- tests/stream/test_hls_playlist.py
Ref #5498 
1. **Turn `Segment` and `Playlist` into dataclasses, so they can be subclassed**
- Make `TwitchSegment` inherit from `Segment`
- Update `TwitchM3U8Parser` accordingly
- Fix `ltv_lsm_lv` plugin (previously cloned the `Segment` named tuple, now simply updates the `uri` attribute)
2. **Remove `Sequence` named tuple wrapper, so `HLSStream{Writer,Worker}` operate on the `Segment` directly**
- Add `num` attribute to `Segment` and initialize with `-1`
- Move sequence number logic from `HLSStreamWorker` to `M3U8Parser`
- Update various `Sequence` references in `HLSStream{Writer,Worker}`
- Update generic typevar of `HLSStream{Writer,Worker,Reader}`
- Update HLS subclasses accordingly in various plugins
I was thinking about adding a `segment` compatibility property with a deprecation …
> stream.hls: remove Sequence named tuple wrapper

- src/streamlink/plugin/api/validate/_validate.py
`Match.__getitem__()` was added in py36, so we don't need to have the `isinstance(value, Match)` check and call `value.group(key)`.
> plugin.api.validate: remove unneeded Match check

- script/deploy-pypi.sh
PyPI has removed support for this and discards release signatures:
https://blog.pypi.org/posts/2023-05-23-removing-pgp/
----
2FA will also be a requirement starting in 2024 for each PyPI user.
This will affect the current release process using `twine` and the `streamlink` PyPI user (currently user+pass authenticated - #5129)
I'll have a look at the suggested alternatives by then. It's possible that this requires rewriting the release workflow here.
- https://docs.pypi.org/trusted-publishers/
- https://github.com/pypa/gh-action-pypi-publish
> script: don't upload PGP signatures to PyPI

- .codecov.yml
- .github/workflows/main.yml
Apparently, the runner images have removed py312 again 4 days ago in
https://github.com/actions/runner-images/commit/929931f61727947eb60ba4ecae57fe82202728ed
so `actions/setup-python` will download the binaries every time, but that doesn't matter apart from slightly longer setup times
> ci.github: update py312 runners

- src/streamlink/plugins/dash.py
- src/streamlink/plugins/hls.py
- tests/plugins/test_dash.py
- tests/plugins/test_hls.py
Allow URL paths ending in `.M3U8` and `.MPD` to be recognized by the HLS and DASH plugins.
----
Fixes #5615
> plugins: ignore case in protocol-plugin input URLs

- src/streamlink/plugins/dash.py
- src/streamlink/plugins/hls.py
- tests/plugins/test_dash.py
- tests/plugins/test_hls.py
For implicit (scheme-less) HTTPS URLs, the HLS and DASH plugins shouldn't match
1. `/example.m3u8` or `/example.mpd`, as the host part is missing here
2. `example.m3u8` or `example.mpd`, as those would be interpreted as TLDs without a path
> plugins: fix URL matchers of HLS and DASH

- MANIFEST.in
Some packagers are currently patching the versioningit fallback version string, which isn't meant for setting the right version. It's a fallback for when not using the dist tarball or a git repo with at least one tag.
The packagers need to do that because they incorrectly use the tarball generated by GitHub as package source instead of our signed sdist tarball which has the right version string already built in.
- https://git.alpinelinux.org/aports/tree/testing/streamlink/APKBUILD?id=083eb89bb9af1e5570429a2580c0c2d5d136be4c#n47
- https://src.fedoraproject.org/rpms/python-streamlink/blob/f8680363a554b0b49c447de73304013644f48575/f/python-streamlink.spec#_75
```sh
$ curl -sSL https://github.com/streamlink/streamlink/releases/download/6.2.1/streamlink-6.2.1.tar.gz \
| bsdtar -xOf- …
```
> build: include build-shell-completions.sh in sdist

- build_backend/test_onbuild.py
Fixes #5635 
```bash
$ python -m build --sdist
...
$ python -m venv /tmp/venv
$ source /tmp/venv/bin/activate
$ bsdtar -xz -C /tmp/venv -f dist/streamlink-6.3.0+1.g6bc7ebd2.tar.gz
$ cd /tmp/venv/streamlink-6.3.0+1.g6bc7ebd2
$ pip install . -r dev-requirements.txt
...
$ pytest
...
$ echo $?
0
```
> build: fix onbuild test in sdist

- src/streamlink/stream/file.py
- tests/stream/test_file.py
Most useless PR of the year, because `FileStream` isn't actually used in the entire code base, because `file://` inputs are handled by the `HTTPSession`'s `FileAdapter`. Other use cases are being a `Stream` wrapper for basic stream I/O objects, but that's not the case anywhere here either (it was the case in 4176c99db241ff6fa46ec9a6a0f30fda28a183be).
The `stream.file` module could therefore also be removed, but I feel like this should be done in a major version bump, so let's keep it for now.
Anyway, `FileStream.open()` attempted to open file paths in text mode ever since it was implemented (never used though), which is obviously wrong for the stream implementation:
https://github.com/streamlink/streamlink/blame/6.3.1/src/streamlink/stream/file.py#L32
I only noticed that after bumping …
> stream.file: fix read mode

- script/test-plugin-urls.py
Create a new Streamlink and HTTP session on each URL
----
This was a requirement for making the plugin test script work for #5645, otherwise every second request on tvp.pl would be rejected.
> script: fix plugin test script

- src/streamlink/plugin/api/validate/_validate.py
Small performance fix for the `_validate_sequence()` overload of `validate()` which I've noticed while writing the API docs.
> plugin.api.validate: fix perf of validate_sequence

- docs/api.rst
- docs/api/validate.rst
- src/streamlink/plugin/api/validate/__init__.py
- src/streamlink/plugin/api/validate/_exception.py
- src/streamlink/plugin/api/validate/_schemas.py
- src/streamlink/plugin/api/validate/_validate.py
- src/streamlink/plugin/api/validate/_validators.py
This finally adds the API documentation for `plugin.api.validate`. An API guide with real-life examples is not included yet and will be added later.
This was much more work than expected. Especially because of several sphinx-autodoc issues which required me to reformat and move everything multiple times.
I've tried to make the style as consistent as possible, but there are some inconsistencies between the `validate` docs, schema docs and utility function docs. These are just minor differences though and you won't notice them. I won't even tell you.
As explained in the top comment of `validate.rst`, the layout was chosen deliberately because of certain autodoc quirks. Unfortunately, it's not ideal, but it's the best I could come up with.
----
My first attempt was documenting all …
> docs: add plugin.api.validate API documentation

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_dynamic_segment_list_p1.mpd
- tests/resources/dash/test_dynamic_segment_list_p2.mpd
- tests/resources/dash/test_dynamic_segment_list_p3.mpd
- tests/stream/dash/test_manifest.py
This PR adds support to keep track of the last yielded segment when using SegmentLists. This actually makes SegmentLists with a dynamic manifest work.
I also check for `init` to avoid yielding the init segment after every refresh.
Fixes #5582
~I have also hardcoded a "live edge" of 3, when we don't have a current_segment yet. This should also be done prettier (and configurable).~
~Note that this PR is still very much WIP. It works, but it isn't pretty. I would like to get some feedback on how to keep track of the last yielded segment correctly. I'm currently storing the last yielded segment in a static dict CURRENT_SEGMENT (key is the representation id) on the Representation (since I need to keep track of them both on audio and video).~
~One of the problems I encounter is that when a …
> stream.dash: fix SegmentList in dynamic manifests

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_dynamic_segment_list_no_duration.mpd
- tests/resources/dash/test_dynamic_segment_list_p1.mpd
- tests/resources/dash/test_dynamic_segment_list_p2.mpd
- tests/resources/dash/test_dynamic_segment_list_p3.mpd
- tests/stream/dash/test_manifest.py
Follow-up for #5654, also mentioned in #5582
Reworked this PR to calculate the live edge based on the `suggestedPresentationDelay`.
> stream.dash: use suggestedPresentationDelay to calculate the live edge for dynamic manifests

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_dynamic_segment_list_p4.mpd
- tests/resources/dash/test_dynamic_segment_list_p5.mpd
- tests/stream/dash/test_manifest.py
Refactor `SegmentList.segments()` and warn about skipped segments when reloading the manifest and queuing new segments with a sequence number offset that's greater than one.
----
Follow-up of: #5654, #5657 
Related: #5607
/cc @michaelarnauts
> stream.dash: warn about skipped segments

- src/streamlink/plugin/api/validate/_validators.py
- tests/test_api_validate.py
Small improvement for `validate.length()`, which now allows changing the operator. Previously, it always checked the min length, aka `len(value) >= number`. Default remains the same.
> plugin.api.validate: add op keyword to length()

- dev-requirements.txt
Similar to ruff, mypy's version should be pinpointed, in case new releases introduce linting issues (which has been the case a couple of times already, requiring all open PRs to be rebased, which can be annoying for first time or inexperienced contributors).
1.7.0 changelog
https://github.com/python/mypy/blob/93e65e443eeac1e0f25a88b33851bb5239bab1a9/CHANGELOG.md#mypy-17
> tools: pinpoint latest mypy version

- tests/webbrowser/cdp/test_connection.py
This made #5668 fail:
https://app.codecov.io/gh/streamlink/streamlink/pull/5668/blob/tests/webbrowser/cdp/test_connection.py#L80
> tests: fix webbrowser test coverage

- src/streamlink/plugins/nasaplus.py
- tests/plugins/test_nasaplus.py
Opening this as a draft since there's currently no live stream running, only one scheduled stream in 3 days... No idea if live streams will have a different site layout.
```
$ ./script/test-plugin-urls.py nasaplus
:: Finding streams for URL: https://plus.nasa.gov/scheduled-video/iss-expedition-70-in-flight-educational-event-with-the-creative-learning-academy-in-pensacola-florida-and-nasa-flight-engineer-jasmin-moghbeli/
:: Found streams: 720p_alt2, 720p_alt, 720p, worst, best
:: Finding streams for URL: https://plus.nasa.gov/video/moon-101-introduction-to-the-moon/
:: Found streams: 79k, 234p, 270p, 360p_alt, 360p, 540p, 720p_alt, 720p, 1080p, worst, best
```
```
$ streamlink -j 'https://plus.nasa.gov/scheduled-video/iss-expedition-70-in-flight-educational-event-with-the-creative-learning- …
```
> plugins.nasaplus: new plugin

- script/test-plugin-urls.py
This can be used for testing generic URLs set in a plugin's test file, e.g. `CHANNELNAME`, `CHANNELID`, `@HANDLE`, etc.
Plugin tests should be updated accordingly in the future, so test URLs for specific channels don't have to be hardcoded.
> script: add -r/--replace to test-plugin-urls.py

- docs/players.rst
- Remove unmaintained/obsolete and proprietary players
- Daum PotPlayer
- MPC-HC
- OMXPlayer
- QuickTime
- Add new players
- IINA
- Change player order
- Add OS and license columns
- Add colored icons for supported transport methods
- Fix footnotes and known issues section
----
Closes #5677
This here uses color-coded icons from the `sphinx-design` dependency instead of "yes" and "no"...
----
Dead players like MPC-HC and OMXPlayer should be removed. And while we're at it, let's also remove proprietary players. There isn't even much info about PotPlayer available, and Quicktime doesn't work anyway...
No idea if my data about IINA is correct. The `--stdin` requirement definitely is, I even checked it just now in my macOS VM. I couldn't manage to get the other methods working though, so I …
> docs: clean up players page

- src/streamlink/compat.py
- src/streamlink/utils/parse.py
- tests/utils/test_parse.py
Resolves #5681 
```
$ python -c 'import lxml.etree;print(lxml.etree.LIBXML_VERSION)'
(2, 12, 0)
$ pytest >/dev/null; echo $?
0
```
```
$ python -c 'import lxml.etree;print(lxml.etree.LIBXML_VERSION)'
(2, 10, 3)
$ pytest >/dev/null; echo $?
0
```
> utils.parse: fix libxml2 2.12.0 compatibility

- src/streamlink/stream/hls/hls.py
- tests/stream/hls/test_hls.py
Only write segment maps to the output once
----
Fixes: #4310
> stream.hls: fix segment maps

- src/streamlink/plugins/piczel.py
Fixes #5684 
Segment initialization gets written to the output only once after merging #5689, so muxing now works fine when using FFmpeg 6.1:
```
$ streamlink -l debug https://piczel.tv/watch/ZeeMBT best
[cli][debug] OS:         Linux-6.6.2-1-git-x86_64-with-glibc2.38
[cli][debug] Python:     3.12.0
[cli][debug] OpenSSL:    OpenSSL 3.1.4 24 Oct 2023
[cli][debug] Streamlink: 6.4.1+6.g5680c7cf
[cli][debug]  certifi: 2023.11.17
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  trio: 0.23.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.1.0
[cli][debug] …
```
> plugins.piczel: fix and update HLS URL

- CHANGELOG.md
The HLS segment map fix (#5689) needs to be published in a new release, because all releases prior are broken with FFmpeg 6.1. Outputs of HLS streams with segment maps (which is a requirement for fragmented mp4 HLS streams) from those older Streamlink releases are all faulty, meaning muxing of currently downloaded video/audio streams fails, as well as demuxing of previously created recordings (affecting playback / file-thumbnail generation / etc), which is bad.
----
Old recordings with the faulty output which FFmpeg 6.1 now rejects need to be remuxed using an older FFmpeg version.
```sh
#!/usr/bin/env bash
for file in $(find . -type f -name "*.mp4" -print); do
ffprobe -v quiet "${file}" && continue  # ffprobe >=6.1 returns status code >0 for those faulty mp4 containers
echo "Remuxing …
```
> release: 6.4.2

- src/streamlink/plugins/btv.py
- tests/plugins/test_btv.py
Fixes #5697
```
$ ./script/test-plugin-urls.py btv
:: Finding streams for URL: https://btvplus.bg/live
:: Found streams: 720p, 1080p, worst, best
:: Finding streams for URL: https://btvplus.bg/live/
:: Found streams: 720p, 1080p, worst, best
:: Finding streams for URL: https://www.btvplus.bg/live/
:: Found streams: 720p, 1080p, worst, best
```
> plugins.btv: parse HLS multivariant playlist

- dev-requirements.txt
- docs-requirements.txt
With the addition of our custom build-backend hooks in #5558 and #5632 which override setuptools' wheel-build logic, and versioningit itself having moved from setuptools to hatch recently, setuptools no longer gets installed automatically, so we need to add it as an explicit build requirement, or it will be missing in the python environment. It has been working until a few days ago because of other dependencies which also pulled setuptools, but this is no longer the case on py312. ~~Not sure which dependency made this change, but it's not important.~~ (it was pycountry, which is finally available as a wheel after several years of only the sdist being available, hence the automatic setuptools install in the env)
Current test CI failures on master: …
> build: fix setuptools in {dev,docs}-requirements

- build_backend/onbuild.py
- build_backend/test_onbuild.py
- dev-requirements.txt
- docs-requirements.txt
- pyproject.toml
Keep backward compatibility for `versioningit <3.0.0`
----
https://versioningit.readthedocs.io/en/stable/changelog.html#v3-0-0-2023-12-13
> Breaking: The `build_dir` argument passed to [`Versioningit.do_onbuild()`](https://versioningit.readthedocs.io/en/stable/api.html#versioningit.Versioningit.do_onbuild) and `onbuild` method callables has been changed to an [`OnbuildFileProvider`](https://versioningit.readthedocs.io/en/stable/writing-methods.html#versioningit.OnbuildFileProvider) ABC
----
:heavy_check_mark: `versioningit <3.0.0`
```
$ pip install -U 'versioningit<3.0.0' >/dev/null
$ pytest -q -s build_backend/
.......
7 passed in 0.10s
$ rm -f dist/streamlink-*; python -m build --sdist --wheel >/dev/null 2>&1
$ bsdtar -xzOf dist/streamlink-*.whl streamlink/_version.py
__version__ = …
```
> build: add support for versioningit >=3.0.0

- pyproject.toml
- src/streamlink/utils/l10n.py
Fixed in `pycountry 23.12.7`:
https://github.com/pycountry/pycountry/blob/23.12.7/HISTORY.txt#L13
Filters were added in #5230, #5393
Setting the min-version requirement of pycountry is not necessary...
> tests: remove unneeded pycountry warning filters

- src/streamlink_cli/main.py
- tests/cli/test_main.py
- tests/cli/test_main_check_file_output.py
Ref https://github.com/streamlink/streamlink/issues/5727#issuecomment-1859078434
This now always logs the resolved output path, even on Windows using Python <=3.9
> cli: fix file output log msg on Windows <=py39

- src/streamlink/plugins/huya.py
Resolves #5744 
```
$ streamlink -l debug 'https://www.huya.com/chuhe'
[cli][debug] OS:         Linux-6.6.8-1-git-x86_64-with-glibc2.38
[cli][debug] Python:     3.12.1
[cli][debug] OpenSSL:    OpenSSL 3.2.0 23 Nov 2023
[cli][debug] Streamlink: 6.5.0+6.g3696dc99
[cli][debug]  certifi: 2023.11.17
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  trio: 0.23.2
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug]  url=https://www.huya.com/chuhe
[cli][debug] …
```
> plugins.huya: check stream availability

- pyproject.toml
This ignores the "timezone-unaware" `datetime` `DeprecationWarning` which `dateutil` raises on Python 3.12.
`dateutil` is a transitive test dependency, required by `freezegun`.
https://github.com/streamlink/streamlink/actions/runs/7367193017/job/20050194304#step:6:284
```
../../../../../opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/dateutil/tz/tz.py:37
/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/dateutil/tz/tz.py:37: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
EPOCH = datetime.datetime.utcfromtimestamp(0)
```
`dateutil` has fixed this in June, but they still …
> tests: ignore dateutil DeprecationWarning

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/useragents.yml
Quick bump of the used Python version in various CI workflows.
I'll also update the master branch protection rules afterwards, which hasn't been done yet after we've added official support for py312.
> ci.github: bump Python version

- src/streamlink/plugins/atresplayer.py
Resolves #5694 
Since @digitechtv or nobody else with access to the site decided to open a PR with a debug log, I decided to commit the changes myself and open a PR. Original commit author data has been set...
Tagging everyone who's responded to #5694
@MoliT @tvfj @jjcasmar
I'd still like to see a full debug log from somebody with access. Please install Streamlink from the branch of this pull request
```
pip install -U git+https://github.com/streamlink/streamlink@refs/pull/5742/head
```
of if you're unable to, at least post a debug log with the plugin changes being sideloaded
Thanks
> plugins.atresplayer: fix live API request

- src/streamlink/plugins/bigo.py
- tests/plugins/test_bigo.py
Fixes #5753
```
$ ./script/test-plugin-urls.py bigo -r SITE_ID 954321825
:: Finding streams for URL: https://www.bigo.tv/954321825
:: Found streams: live, worst, best
```
```
$ streamlink --json 'https://www.bigo.tv/954321825' | jq .metadata
{
"id": "7287389864212587887",
"author": "954321825",
"category": "League of Legends",
"title": "Gaming"
}
```
```
$ streamlink 'https://www.bigo.tv/achannelthatdoesnotexist'
[cli][info] Found matching plugin bigo for URL https://www.bigo.tv/achannelthatdoesnotexist
error: No playable streams found on this URL: https://www.bigo.tv/achannelthatdoesnotexist
```
```
$ streamlink 'https://www.bigo.tv/x'
[cli][info] Found matching plugin bigo for URL https://www.bigo.tv/x
[plugins.bigo][info] Channel is offline
error: No playable streams found on this URL: …
```
> plugins.bigo: rewrite and fix plugin

- src/streamlink/plugins/twitch.py
Resolves #5600
This ignores the `--webbrowser-headless` config in the Twitch plugin and always forces `headless` to be `False`, because Twitch is able to detect Chromium's headless mode when forcing the acquirement of the client-integrity token. You can check this easily by setting an invalid OAuth token for example (`--twitch-api-header="Authorization=OAuth invalid"`) or by modifying the plugin.
The CI tokens are currently not a requirement, but this can change at any time, and if they do and Streamlink has headless mode enabled by default (which is the case), then users are forced to update their configs or CLI arguments until we publish a new release, which is unnecessary. So let's set `headless` to `False` in the Twitch plugin now.
> plugins.twitch: disable headless mode

- docs/install.rst
Both packages appear to be unmaintained, with the latest packaged version being `5.5.1`.
- https://pkgsrc.se/multimedia/streamlink
- https://github.com/void-linux/void-packages/commits/559ab36d2914e685efcc7bf1a4433a73ffcd96cf/srcpkgs/streamlink
- https://github.com/void-linux/void-packages/pulls?q=streamlink
> docs: unlist outdated/unmaintained packages

- src/streamlink/plugins/vidio.py
- tests/plugins/test_vidio.py
Fixes #5761
```
$ ./script/test-plugin-urls.py vidio
:: Finding streams for URL: https://www.vidio.com/live/204-sctv-tv-stream
:: Found streams: 240p_alt, 240p, 360p_alt, 360p, 480p_alt, 480p, 720p_alt, 720p, worst, best
:: Finding streams for URL: https://www.vidio.com/live/5075-dw-tv-stream
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.vidio.com/watch/766861-5-rekor-fantastis-zidane-bersama-real-madrid
:: Found streams: 270p, 360p, 720p, worst, best
```
> plugins.vidio: fix stream token

- dev-requirements.txt
- pyproject.toml
- src/streamlink/plugins/crunchyroll.py
- src/streamlink/stream/wrappers.py
`RUF021` was added to the ignore list, because this rule wants useless parenthesis to be added to boolean expressions, despite everyone being aware of the operator precedence.
`PLC2801` has a faulty implementation in ruff 0.1.13, and it doesn't allow explicit dunder method calls (`__foo__()`), despite this being intentionally done in lots of cases. Some issues have already been fixed on their master branch, but others have not. I fixed those lines of code which made sense, but everything remained untouched with the rule being ignored. Otherwise, an annotation would need to be added, which doesn't make sense.
> tools: bump ruff to 0.1.13 and fix issues

- tests/plugins/__init__.py
This makes the error message much more clear when a plugin URL test has missing positive URLs. Happend to me yesterday after rewriting the artetv plugin and accidentally misspelling the `should_match_groups` attribute.
> tests: fix positive URLs assertion in plugins test

- src/streamlink/utils/args.py
- src/streamlink_cli/argparser.py
- tests/utils/test_args.py
This updates and fixes the `streamlink.utils.args` module, in preparation for #5715 (which I will rebase and modify after this got merged - after the next release).
----
The first commit keeps the same functionality as the current implementation, apart from different exceptions being raised. The tests have been fully rewritten, but the old tests also pass (ignoring the exception class changes).
The second and third commits fix some issues with the inputs of `filesize()` and `keyvalue()`. This will affect the `--ringbuffer-size` argument, as well as `--http-header`, `--http-cookie`, `--http-query-param`, `--player-env`, `--twitch-api-header` and `--twitch-access-token-param`. This is mainly just whitespace character related but it fixes the missing regex anchors.
The last commit fixes the …
> utils.args: rewrite module

- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink_cli/main.py
- tests/test_options.py
This explicitly adds all keywords which are passed to `argparse.ArgumentParser.add_argument()` to the `pluginargument` decorator (`Argument` class). ~~It also turns all options except for `name` into mandatory keywords (which is technically a breaking change, but I don't think anyone with common sense has defined custom plugin arguments using positional args).~~
The intention here is simplifying the parsing of the plugin module AST when building a plugins JSON file with all matchers and arguments (#4741), so Streamlink doesn't have to load all plugins at once. This is what I've been working on again in the past couple of days. It also improves type checking of all plugin arguments.
----
Opening this as a draft for now, because I don't want these changes to be included in the next release …
> options: refactor Argument/pluginargument

- docs/api/plugin.rst
- src/streamlink/plugin/plugin.py
- src/streamlink/plugins/nicolive.py
- src/streamlink/plugins/streann.py
- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/zattoo.py
- tests/test_plugin.py
Follow-up of #5715
This adds a `@pluginargument()` `type` function registry, so the `@pluginargument()` data can be fully JSON-serialized.
Built-in plugins now must always reference the `type` argument of each `@pluginargument()` (if set) via the registered function name. This is optional for third-party plugins.
> plugin: add str to pluginargument type argument

- src/streamlink/plugins/huya.py
- tests/plugins/test_huya.py
Set Referer and Origin headers, keep only necessary query string params in the stream URLs, and remove stream URL HEAD request.
----
Fixes #5784 
No idea if this is valid for all channels.
Random channel test:
```bash
for cdn in $(streamlink --json huya.com/shege | jq -r '.streams | keys[] | select(contains("source_"))'); do
timeout 20 streamlink -o /dev/null huya.com/shege $cdn
echo
done
```
```
[cli][info] Found matching plugin huya for URL huya.com/shege
[cli][info] Available streams: source_hs (worst), source_al, source_hw, source_tx (best)
[cli][info] Opening stream: source_al (http)
/dev/null
[download] Written 6.42 MiB to /dev/null (16s @ 411.13 KiB/s)                                                                                   
[cli][info] Stream …
```
> plugins.huya: fix stream URLs

- src/streamlink/plugin/plugin.py
- tests/test_plugin.py
- Add `int` and `float` types to the pluginargument type registry
- Rename `boolean` to `bool`
----
Somehow forgot to add this in #5779. The `bool` name change is fine, because it hasn't been included in a release yat and only affects Streamlink's own plugins anyway.
> plugin: add missing pluginargument type functions

- src/streamlink/plugins/aloula.py
- tests/plugins/test_aloula.py
Fixes #5791 
```
$ ./script/test-plugin-urls.py aloula
:: Finding streams for URL: https://www.aloula.sa/en/episode/6676
:::: This stream requires a login; specify appropriate Authorization and profile HTTP headers
:: Finding streams for URL: https://www.aloula.sa/en/live/saudiatv
:: Found streams: 360p, 480p, 1080p, worst, best
:: Finding streams for URL: https://www.aloula.sa/episode/6676
:::: This stream requires a login; specify appropriate Authorization and profile HTTP headers
:: Finding streams for URL: https://www.aloula.sa/live/saudiatv
:: Found streams: 360p, 480p, 1080p, worst, best
```
> plugins.aloula: add HTTP headers, update matchers

- tests/cli/test_main.py
- tests/cli/test_plugin_args_and_options.py
- tests/mixins/stream_hls.py
- tests/plugins/test_filmon.py
- tests/plugins/test_rtpplay.py
- tests/plugins/test_twitch.py
- tests/plugins/test_ustreamtv.py
- tests/plugins/test_vk.py
In preparation for the session initialization rewrite using the plugins JSON data...
Despite there being the `session` pytest fixture for initializing a Streamlink session object without loading any plugins, lots of tests are currently still manually initializing the session, which leads to all plugins being loaded every time. This slows down the tests significantly. On my local system, these changes improve the run time from ~15s to ~10s.
The upcoming plugins JSON data implementation will make lots of changes to the Streamlink class, so patching the `load_builtin_plugins()` method won't be necessary anymore in the tests afterwards.
> tests: fix session init

- dev-requirements.txt
Skip installing pytest>=8.0.0 until pytest-asyncio has been fixed
----
https://docs.pytest.org/en/latest/changelog.html#pytest-8-0-0-2024-01-27
```
$ pytest
============================================================= test session starts ==============================================================
platform linux -- Python 3.12.1, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/basti/repos/streamlink
configfile: pyproject.toml
testpaths: build_backend, tests
plugins: requests-mock-1.11.0, cov-4.1.0, trio-0.8.0, typeguard-4.1.5, asyncio-0.23.3
asyncio: mode=Mode.STRICT
collected 0 items                                                                                                                              
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File …
```
> tests: downgrade pytest

- dev-requirements.txt
pytest-asyncio 0.23.4 has been released and now itself limits pytest to <8, so this does not have to be done by us anymore.
As soon as pytest-asyncio will have resolved its incompatibilities with pytest >=8, the latest versions will be picked up by pip automatically.
----
#5802
> tests: remove pytest downgrade again

- src/streamlink/session.py
- src/streamlink/utils/module.py
- tests/test_plugins.py
- tests/test_session.py
- tests/utils/test_module.py
Minor performance improvement for loading (plugin) modules. This is unrelated to the plugins JSON data loader I've been working on, hence this PR.
----
1. **utils.module: fix load_module(), add exec_module()**
- Use global finder cache via `pkgutil.get_importer()` instead of always creating a new `FileFinder` object for each module
- Add `exec_module()` for being able to reuse `PathEntryFinder` objects returned by `pkgutil.iter_modules()`
- Add support for pathlib path objects
- Update tests
2. **session: re-use PathEntryFinder in load_plugins()**
3. **tests: re-use PathEntryFinder in test_plugins**
> utils.module: optimize plugin module loading

- src/streamlink/utils/parse.py
> utils.parse: fix import path

- src/streamlink/compat.py
- tests/test_compat.py
Going to rebase #5807 onto this, once merged into master.
#5807 currently simply removes `HTTPSession`, for two reasons, which is technically a breaking change of the plugin API and should be avoided, even though it's very unlikely that third party plugins actually import `HTTPSession`:
1. `plugin.api` now creates an import cycle, as `session.http` imports `plugin.api.useragents`
2. `plugin.api.http_session` is now a deprecated compat module
The compat exports of `plugin.api.http_session` also currently don't emit a deprecation warning, which they should. This PR will allow this to be fixed. Same with the import cycle, which gets fixed by importing the object on attribute access time from the module's global context.
> compat: add deprecated() function

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/useragents.yml
Fixes the NodeJS 16 deprecation warning on the CI runners.
> ci.github: bump setup-python action to v5

- .github/workflows/release.yml
- .github/workflows/test.yml
Bump remaining actions being based on the deprecated NodeJS 16 runners.
1. `upload/download-artifact`:
https://github.com/actions/upload-artifact/blob/v4.3.1/docs/MIGRATION.md
No changes here, since it's a trivial 1:1 artifact name mapping
2. `codecov/codecov-action`:
https://github.com/codecov/codecov-action/blob/v4.0.1/README.md#v4-release
No more token-less uploads. I've added the `CODECOV_TOKEN` secret env var to the repo.
> ci.github: bump actions

- docs/_man.rst
- docs/cli.rst
- docs/ext_argparse.py
- script/build-shell-completions.sh
- src/streamlink_cli/_parser.py
- src/streamlink_cli/main.py
- Move the `parser_helper()` function from `streamlink_cli.main` into the `streamlink_cli._parser` module
- Refactor `ext_argparse` and set default import paths
- Update import path in `build-shell-completions.sh`
Unfortunately, the `streamlink_cli._parser` module can't be excluded from the sdist/wheel distributions, as packagers might build shell completions from the installed `streamlink_cli` package instead of using the pre-built shell completions included in the sdist or building them from an editable install.
----
This helper function was added in #1638 and serves no purpose in the CLI's main module itself. It should therefore not be a part of it.
> docs: fix custom ext_argparse Sphinx extension

- docs/_static/styles/custom.css
This fixes horizontal scrollbars appearing in sidebars when there's a vertical non-overlay scrollbar (overlay scrollbars depend on the web browser and its settings).
Alternatively, `scrollbar-gutter: stable` could be set, but this would always claim space for the scrollbar, even if it's not visible, and that doesn't make sense for the left sidebar at least.
This also fixes the scrollbar being visible at all times in the TOC sidebar
> docs: fix scrollbars in sidebars

- .github/workflows/test.yml
- build_backend/commands.py
- build_backend/plugins_json.py
- build_backend/test_plugins_json.py
- pyproject.toml
- setup.py
Ref #4741
Part 1/x
----
This adds the plugins JSON build script + setuptools hook, and a CI test job for it.
The build script parses each plugin file and reads the pluginmatcher and pluginargument data by walking the module's abstract syntax tree. The result is the JSON-serialized pluginmatcher and pluginargument data of each plugin without having to install Streamlink and import any plugin modules. There are many cases though where parsing could fail, depending on the plugin implementation, for example because object references are not supported. That's why the pluginmatcher and pluginargument data is now defined very strictly.
The next step (different PR) will be implementing the session and CLI logic for reading the JSON and loading only the matching plugin module based on that.
> build: add plugins JSON build script

- src/streamlink/session/plugins.py
- src/streamlink/session/session.py
- src/streamlink/utils/module.py
- src/streamlink_cli/_parser.py
- src/streamlink_cli/main.py
- tests/cli/test_main.py
- tests/conftest.py
- tests/session/test_plugins.py
- tests/session/test_session.py
- Add `plugins_lazy` keyword to `Streamlink` session class
- Load pre-built plugins JSON data including matchers and arguments data
- Fall back to loading all built-in plugins if loading JSON data fails
- Iterate matcher/argument data of loaded and still unloaded plugins
- Load plugin modules of unloaded plugins when matching URLs are found
- Refactor `utils.modules` and add `get_finder()` function
- Change `--plugins` output from "Loaded plugins" to "Available plugins"
- Add tests
- Move matcher priority tests from `test_session` to `test_plugins`
----
Resolves #4741
This currently includes the commits of #5793, as explained there...
----
Loading plugins lazily saves a couple of MiBs of memory and makes resolving plugins a bit faster. It's not that much faster than I was hoping for, but …
> session: implement lazy plugins loading 

- pyproject.toml
Should've been included in #5819
> cli: ignore coverage in _parser util module

- docs/install.rst
- pyproject.toml
Resolves #5841 
----
bad
```sh
docker run --rm -i --mount type=bind,source=./dist,target=/dist python:3.11 bash <<"EOF"
cd "$(mktemp -d)"
tar -xzf /dist/streamlink-6.6.1+2.g47cebc73.tar.gz --strip-components=1
python -m pip install build
python -m build --no-isolation --wheel
EOF
```
```
ERROR Missing dependencies:
setuptools>=65.6
```
----
good
```sh
docker run --rm -i --mount type=bind,source=./dist,target=/dist python:3.11 bash <<"EOF"
cd "$(mktemp -d)"
tar -xzf /dist/streamlink-6.6.1+2.g47cebc73.tar.gz --strip-components=1
python -m pip install build setuptools==65.6 versioningit
python -m build --no-isolation --wheel
EOF
```
```
Successfully built streamlink-6.6.1+2.g47cebc73-py3-none-any.whl
```
> build: bump setuptools to >=65.6

- src/streamlink/session/plugins.py
- tests/session/test_plugins.py
Fixes #5843 
I didn't notice the missing log message because apparently I only checked this in a live environment from an editable install where all plugins get loaded at once like before, unlike in non-editable installs.
This bugfix justifies another patch release after merging. Will publish 6.6.2 later today...
----
```
$ pip install -q .
$ streamlink -V
streamlink 6.6.1+3.g21ef70bc
$ streamlink twitch.tv/smoke
[session][info] Plugin twitch is being overridden by /home/basti/.local/share/streamlink/plugins/twitch.py
[cli][info] Found matching plugin twitch for URL twitch.tv/smoke
Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
```
> session: fix missing plugin override log message

- src/streamlink/plugins/afreeca.py
Resolves: #5845 
I found a changes for the `https://play.afreecatv.com/{username}`.
By modifying the regex, streamlink can get the stream URL correctly.
```
[session][debug] Plugin afreeca is being overridden by /home/b4tt3ry/.local/share/streamlink/plugins/afreeca.py
[cli][debug] OS:         Linux-6.5.11-8-pve-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 6.5.1
[cli][debug]  certifi: 2023.11.17
[cli][debug]  lxml: 4.9.2
[cli][debug]  trio: 0.24.0
[cli][debug]  typing-extensions: 4.9.0 …
```
> plugins.afreeca: fix broadcast number regex

- src/streamlink/plugins/vimeo.py
Fixes #5702
HLS and DASH stream data is set to optional in the API response validation schema:
https://github.com/streamlink/streamlink/blob/6.6.2/src/streamlink/plugins/vimeo.py#L56-L57
If the data is missing from the API response, then its value will be `None`, hence the `AttributeError` when trying to call `.values()` for iterating over the data.
Didn't check this on actual live event streams, because I don't know how to find them on Vimeo. This PR fixes the `AttributeError`, but I don't know if live events are actually working.
@WolfganP @Sparticuz
Please see if there are any other issues while trying to watch live event streams, thanks.
> plugins.vimeo: fix missing HLS/DASH API results

- src/streamlink/plugins/ltv_lsm_lv.py
- tests/plugins/test_ltv_lsm_lv.py
Fixes #5857 
Two issues:
1. The site has changed and the embedded player ID can't be extracted separately anymore, so the whole embedded player URL needs to be found instead
2. The plugin's custom `HLSStreamWorker` subclass was not updated after some changes were made in the base class, resulting in an incompatible signature of `LTVHLSStreamWorker.process_segments()` (probably the reason why @karlis-vagalis was using the `--stream-url` parameter)
@karlis-vagalis please check and verify these plugin fixes using a couple of different stream URLs, as the live content is geo-blocked for me and it's only listing replays/VODs on their site. Please include a short debug log (without `--stream-url`), thanks. …
> plugins.ltv_lsm_lv: fix plugin, rm LTVHLSStream

- src/streamlink/stream/hls/hls.py
- src/streamlink/stream/hls/m3u8.py
- src/streamlink/stream/hls/segment.py
- tests/stream/hls/test_hls.py
Add the `key` attribute to the `Map` class, so segment maps can be encrypted independently or left as plain text, depending on the order of the `EXT-X-MAP` and `EXT-X-KEY` tags in the playlist.
TODO:
Rewrite the `HLSSegment`, `HLSStreamWriter` and `HLSStreamWorker` classes based on the logic of the DASH implementation, where init segments are queued by the worker separately.
----
Fixes #5856 
Let's fix this bug, even though the current implementation is terrible.
```
$ streamlink -l debug --hls-duration 20s --player-no-close --http-cookie domand_bid=5e377f548bdfca20defd15f0b178b8b42e538ed14569c97f6338178cde548a49 'https://delivery.domand.nicovideo.jp/hlsbid/65d4695bd76609a88f8bfe85/playlists/media/audio-aac-192kbps.m3u8?session=8b75576e7a29181c14eb064f0359172c7d7896c56598baea0000000065da9f …
```
> stream.hls: fix maps with and without keys

- src/streamlink/plugins/mangomolo.py
- tests/plugins/test_mangomolo.py
Resolves #5850 
Rel #5848
- https://www.mangomolo.com/about-us
- https://www.mangomolo.com/products
- https://www.google.com/search?q=Alpha+Technology+Group
```
$ ./script/test-plugin-urls.py mangomolo
:: Finding streams for URL: https://media.gov.kw/LiveTV.aspx?PanChannel=KTV1
:: Found streams: 240p, 360p, 720p, 1080p, worst, best
:: Finding streams for URL: https://media.gov.kw/LiveTV.aspx?PanChannel=KTVSports
:: Found streams: 240p, 360p, 720p, 1080p, worst, best
:: Finding streams for URL: https://player.mangomolo.com/v1/live?id=MTk1&channelid=MzU1&countries=bnVsbA==&w=100%25&h=100%25&autoplay=true&filter=none&signature=9ea6c8ed03b8de6e339d6df2b0685f25&app_id=43
:: Found streams: 240p, 360p, 720p, 1080p, worst, best
```
I wish there were a better way for platforms like this where …
> plugins.mangomolo: new plugin

- src/streamlink_cli/main.py
This prevents args from being logged in the debug output twice if two or more args share the same `dest`.
For example, I want to add `--plugin-dir` (`action="append"`) in addition to `--plugin-dirs` (`type=comma_list, action="expand"`). `--plugin-dir` will have the same `dest="plugin_dirs"`, so both arguments can be merged into the same attribute on the arguments namespace object `args.plugin_dirs`. Without this change, it'll log both args.
No tests, because the current test setup is still `unittest.TestCase` based and needs a rewrite first. I don't want to touch any of this code anymore.
> cli: only log args with the same dest once

- src/streamlink/plugins/bloomberg.py
- tests/plugins/test_bloomberg.py
Fixes #5868 
```
$ ./script/test-plugin-urls.py bloomberg
:: Finding streams for URL: https://www.bloomberg.com/live
:: Found streams: 272p, 360p, 720p_alt, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.bloomberg.com/live/europe
:: Found streams: 272p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://www.bloomberg.com/live/us
:: Found streams: 272p, 360p, 720p_alt, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.bloomberg.com/news/videos/2022-08-10/-bloomberg-surveillance-early-edition-full-08-10-22
:: Found streams: 100k, 176p, 272p, 360p, 540p, 720p_alt, 720p, 1080p, worst, best
```
> plugins.bloomberg: refactor and fix data regex

- src/streamlink/session/options.py
- tests/session/test_options.py
Fixes session option default objects unintentionally being shared (introduced in b82adee59af1a0c6fa1867ae85675ff3097ea47a).
Also removes the unneeded `defaults` keyword from `StreamlinkOptions()`.
> session: fix default options being shared

- docs/deprecations.rst
- src/streamlink_cli/argparser.py
See #5865
`--plugin-dirs` is a `comma_list` argument, which isn't ideal for path values. This therefore adds the `--plugin-dir` argument, which can be set multiple times with only one single path as argument value. Both argument values are merged into the `plugin_dirs` attribute on the arguments namespace object, so no changes are needed. But this also means that there's no deprecation warning when using the old argument.
```
$ streamlink -l debug --plugin-dir /tmp/foo --plugin-dir /tmp/bar --plugin-dirs /tmp/baz,/tmp/qux
[cli][warning] Plugin path /tmp/foo does not exist or is not a directory!
[cli][warning] Plugin path /tmp/bar does not exist or is not a directory!
[cli][warning] Plugin path /tmp/baz does not exist or is not a directory!
[cli][warning] Plugin path /tmp/qux does not …
```
> cli: add --plugin-dir, deprecate --plugin-dirs

- src/streamlink/plugins/ustvnow.py
- tests/plugins/test_ustvnow.py
Closes #5431
Completely untested. See https://github.com/streamlink/streamlink/issues/5431#issuecomment-1972725589
Since nobody even responded to my request, I'm opening this PR myself, even though I can't access any of these streams. There's a lot more wrong with this plugin, namely bad regexes and missing validation schemas, but I won't touch anything that I can't validate.
@pepsik-kiev @MajinLugia please give this PR a test and report back with a full `--loglevel=debug` output without running any third party software that embeds or launches Streamlink.
If there's no feedback, then I'm going to remove the plugin instead, because I can't maintain it myself, and nobody else with access has shown any …
> plugins.ustvnow: update matcher, reformat code

- docs/deprecations.rst
The badges should not be at the bottom of each sub-section. Having them right underneath the headline makes much more sense.
> docs: move up removal badges on deprecations page

- src/streamlink_cli/utils/progress.py
- tests/cli/utils/test_progress.py
This fixes the download progress output missing the last data chunk.
Without patch (depends on the timing of the last `write()` call):
```
$ streamlink -l none --force -o /tmp/foo.mp4 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/v9/prog_index.m3u8' best
[download] Written 563.48 MiB to /tmp/foo.mp4 (12s @ 45.01 MiB/s)
$ streamlink -l none --force -o /tmp/foo.mp4 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/v9/prog_index.m3u8' best
[download] Written 554.26 MiB to /tmp/foo.mp4 (12s @ 45.19 MiB/s)
$ streamlink -l none --force -o /tmp/foo.mp4 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/v9/prog_index.m3u8' best
[download] Written 545.10 MiB to /tmp/foo.mp4 (10s @ 51.81 …
```
> cli: update progress output after stream has ended

- tests/cli/test_main_logging.py
While packing the version, I got tests errors, probably because the order of test execution wasn't the same.
`test_main_logging` tests are changing the log level by calling `streamlink_cli.main.setup(parser)`. We need to reset it to its default value on teardown.
The log level is set by this code in `setup`:
```
silent_log = any(getattr(args, attr) for attr in QUIET_OPTIONS)
log_level = args.loglevel if not silent_log else "none"
log_file = args.logfile if log_level != "none" else None
setup_logger_and_console(console_out, log_file, log_level, args.json)
```
Here is a test failure caused by this:
```
________________________ TestLogging.test_default_level ________________________
self = <tests.test_logger.TestLogging object at 0x7f9d4174eb90>
def test_default_level(self):
>       assert …
```
> Fix tests by resetting the log level

- src/streamlink/plugins/tv3cat.py
- tests/plugins/test_tv3cat.py
Fixes #5889
Some streams are geo-blocked on the HLS segment level (403 HTTP response). That doesn't need to be detected by the plugin though...
```
$ ./script/test-plugin-urls.py tv3cat
:: Finding streams for URL: https://www.ccma.cat/3cat/buscant-la-sostenibilitat-i-la-tecnologia-del-futur/video/6268863/
:: Found streams: 720p_dash, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.ccma.cat/3cat/directes/324/
:: Found streams: 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.ccma.cat/3cat/directes/catalunya-radio/
:: Found streams: 96k, worst, best
:: Finding streams for URL: https://www.ccma.cat/3cat/directes/esport3/
:: Found streams: 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.ccma.cat/3cat/directes/sx3/
:: Found …
```
> plugins.tv3cat: rewrite plugin, add missing VODs

- pyproject.toml
Breaking changes, which need to be resolved soon:
https://github.com/python-trio/trio/releases/tag/v0.25.0
Limiting to `<0.25` ensures that the tests pass for now...
> build: set trio dependency to <0.25 for now

- docs/install.rst
- pyproject.toml
- src/streamlink/compat.py
- src/streamlink/plugins/twitch.py
- src/streamlink/session/session.py
- src/streamlink/webbrowser/cdp/connection.py
- src/streamlink/webbrowser/webbrowser.py
- tests/webbrowser/cdp/__init__.py
- tests/webbrowser/cdp/test_client.py
- tests/webbrowser/cdp/test_connection.py
- tests/webbrowser/test_webbrowser.py
See #5893
Breaking changes in `trio`'s `0.25` release (apparently the last breaking change before their first stable release):
https://github.com/python-trio/trio/releases/tag/v0.25.0
----
1. **build: add exceptiongroup dependency**
Add the `exceptiongroup` dependency directly to Streamlink, so we can write `ExceptionGroup` handling code on all supported versions of Python without having to rely on `trio`'s conditional dependency.
2. **webbrowser: fix compatibility with trio 0.25**
- Set min. version requirement of `trio` to `0.25`,
so we don't have to set `strict_exception_groups` to `True` on older versions (probably not even possible via `pytest-trio`)
- Fix compatibility with `trio>=0.25`:
Since `strict_exception_groups` now defaults to `True`, trio nurseries now always raise an …
> webbrowser: fix compatibility with trio 0.25

- src/streamlink/plugins/vimeo.py
- tests/plugins/test_vimeo.py
See https://github.com/streamlink/streamlink/pull/5854#issuecomment-2001985675
Some event streams are not accessible directly and the `oembed` API response doesn't include the `uri` attribute in this case. Accessing the embedded player of these events however seems to work and the config URL can be obtained this way. This PR splits up the `_query_api()` method and retrieves the `config_url` from events and non-event streams/videos separately.
The `player.vimeo.com` logic was also broken due to changes on their end, which should be fixed now.
No idea about other kinds of videos/streams. There's a high chance that some content is still not working correctly.
As can be seen in the tests diff, some URLs were removed, because they are not accessible anymore. Not sure if that's just the …
> plugins.vimeo: fix event and player URLs

- dev-requirements.txt
Apparently, pytest's [`ExceptionInfo.group_contains()`](https://docs.pytest.org/en/8.0.x/reference/reference.html#pytest.ExceptionInfo.group_contains) was only just added in pytest 8.0.0:
https://docs.pytest.org/en/8.0.x/changelog.html#additional-support-for-exception-groups-and-notes
I wasn't aware of this, because it's not noted in their docs directly like most stuff. That utility function is required by the updated tests in #5895 when making assertions about `ExceptionGroup`s.
Streamlink's dev-requirements should therefore bump the min-requirement of pytest to 8.0.0.
> tests: require pytest 8.0.0

- pyproject.toml
- src/streamlink/webbrowser/cdp/client.py
- src/streamlink/webbrowser/cdp/connection.py
- tests/conftest.py
- tests/webbrowser/cdp/__init__.py
- set `strict_exception_groups=True` in `CDPClient.launch()`
- monkey-patch `trio.run()` early in Streamlink's tests
----
This lifts the dependency requirements of Streamlink a bit. I didn't want to do this initially and bumped trio to `>=0.25`, because it requires patching `trio.run()` in Streamlink's tests, as `pytest-trio` doesn't allow setting custom `trio.run()` args/kwargs.
Since packagers of some Linux distros like Debian have to apply the same kind of patch in order to package Streamlink 6.7.1, we should instead apply the version compatibility fixes here ourselves.
> build: set trio min-requirement back to 0.22

- CHANGELOG.md
Just a small packaging related correction... Bumping Streamlink's AppImages and Windows builds won't be necessary, because there are no relevant application code changes.
Alternatively, we could also not release 6.7.2 in this current state just yet and wait for more (actual) changes, because it's not super important fixing those issues. Releasing this however could ease packaging in some cases. Those packagers chould however also apply the patches themselves.
- Alpine is on trio==0.21 and pytest>=8 (0.22 is now an actual requirement and not an arbitrary version number)
- Debian applies trio<0.25 patches and is on pytest>=8
- Fedora is on trio==0.23.1 and pytest==7.4.3
- FreeBSD is on trio==0.25.0 and pytest==7.4.4
- Gentoo disables new ExceptionGroup tests due to pytest>=8 not being …
> release: 6.7.2

- src/streamlink/plugins/showroom.py
Fixes #5909 
The HLS streams now have the correct `Content-Type` header according to [rfc8216](https://datatracker.ietf.org/doc/html/rfc8216#section-4), namely `application/vnd.apple.mpegurl`.
```
$ curl -I https://hls-css.live.showroom-live.com/live/17d0561da8f8c7d0e2f70005699c3088916f1b91b60a7dc8bde88ebb69da054b_default.m3u8 | grep content-type
content-type: application/vnd.apple.mpegurl
```
Streams are working fine with this fix when accessing from a Japanese IP address:
```
$ streamlink https://www.showroom-live.com/r/SAKURAGI_RICO best
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/r/SAKURAGI_RICO
[cli][info] Available streams: 144p (worst), 360p, 1080p (best) …
```
> plugins.showroom: fix geo-block check

- docs/install.rst
The "PyPI package" anchor in the "Package availability" section currently links to `#id4`, which is a duplicate of `#pypi-package-and-source-code`:
https://streamlink.github.io/install.html#package-availability
This is because the "Windows", "macOS", "Linux and BSD" and "PyPI package and source code" sections all require explicit section labels because of the big icon buttons at the top rendered by `sphinx-design`, which doesn't support the `autosectionlabel` Sphinx extension:
- https://github.com/streamlink/streamlink/blob/6.7.2/docs/install.rst?plain=1#L8
- https://github.com/streamlink/streamlink/blob/6.7.2/docs/install.rst?plain=1#L51
- https://github.com/streamlink/streamlink/blob/6.7.2/docs/install.rst?plain=1#L98
- https://github.com/streamlink/streamlink/blob/6.7.2/docs/install.rst …
> docs: fix anchor on install page

- src/streamlink_cli/utils/formatter.py
- src/streamlink_cli/utils/path.py
- tests/cli/utils/test_formatter.py
- tests/cli/utils/test_path.py
Fixes #5919 
To make sense of this in just a few seconds, just have a look at the two tests added in the last commit...
> cli.utils.formatter: respect max file name length

- src/streamlink/plugins/mangomolo.py
https://github.com/streamlink/streamlink/pull/5852#issuecomment-2038556693
`player.mangomolo.com/v1/live?...` apparently now requires a `Referer` header. The URL in the plugin test cases is from one of the `media.gov.kw` streams and works fine if the referer is set to this host.
```
$ ./script/test-plugin-urls.py mangomolo
:: Finding streams for URL: https://media.gov.kw/LiveTV.aspx?PanChannel=KTV1
:: Found streams: 240p, 360p, 720p, 1080p, worst, best
:: Finding streams for URL: https://media.gov.kw/LiveTV.aspx?PanChannel=KTVSports
:: Found streams: 240p, 360p, 720p, 1080p, worst, best
:: Finding streams for URL: https://player.mangomolo.com/v1/live?id=MTk1&channelid=MzU1&countries=bnVsbA==&w=100%25&h=100%25&autoplay=true&filter=none&signature=9ea6c8ed03b8de6e339d6df2b0685f25&app_id=43 …
```
> plugins.mangomolo: fix missing Referer header

- src/streamlink_cli/utils/path.py
- tests/cli/utils/test_path.py
https://github.com/streamlink/streamlink/issues/5919#issuecomment-2041196857
Updated tests fail without the `if len(path) <= length` removal and now properly check the max **bytes**.
> cli.utils.path: fix max bytes

- src/streamlink/plugin/api/validate/_validators.py
- tests/test_api_validate.py
Fixes #5931 
Since Python 3.11.9 / 3.12.3 / 3.13.0a6, `urllib.parse.parse_qsl()` now raises a `TypeError` if the input is not a `str`, is truthy and can't be passed to `memoryview()`, like integers for example, hence the test failure which previously just checked an invalid input to that validation schema.
> plugin.api.validate: check parse_qsd() input type

- build_backend/test_onbuild.py
When executing tests from the build directory (generated by bdist), the location of the Streamlink source is directly at the root directory and not in a `src` subdirectory.
This is what Debian does when building python packages to ensure newly built files are tested instead of source files.
> tests: fix test_onbuild when executed from build directory

- .codecov.yml
This adds a dedicated `build_backend` code coverage status check. The build backend should always be fully covered.
Its tests are currently not part of the `test` status check while its main module files are part of the `streamlink` status check, which isn't ideal.
> ci.codecov: add build_backend status check

- CHANGELOG.md
Release date set to tomorrow...
I'd like to wait for the Linux AppImage docker base-images with Python 3.12.3 to be built first (relying on pypa-manylinux), which will hopefully happen soon, so I can bump the AppImages to the latest Python version. The Windows builds are already good to go with Python 3.12.3 and 3.8.19-3-gf5bd65ed, as well as FFmpeg n7.0-7-gd38bf5e08e.
> release: 6.7.3

- .editorconfig
- CONTRIBUTING.md
- KNOWN_ISSUES.md
Some clean up of the contributing guidelines. This intentionally ignores the plugin requests for now.
Regarding the removal of `KNOWN_ISSUES.md`: it's completely useless. Known issues are those which are opened on the issue tracker.
> docs: clean up contributing guidelines

- CONTRIBUTING.md
See #5904
Follow-up of #5947 
This doesn't update any of the current plugin rules and just rephrases and clarifies them.
> docs: rephrase and clarify plugin rules

- src/streamlink/plugins/afreeca.py
When I used the correct password:
```
$ streamlink --loglevel debug --afreeca-stream-password 71 https://play.afreecatv.com/ecvhao/263153658
NoTagError: `git describe --long --dirty --always --tags` could not find a tag
[cli][debug] OS:         Linux-6.5.13-1-pve-x86_64-with-glibc2.39
[cli][debug] Python:     3.11.8
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 0.0.0+unknown
[cli][debug]  certifi: 2024.2.2
[cli][debug]  exceptiongroup: 1.2.1
[cli][debug]  lxml: 5.2.1
[cli][debug]  pycountry: 23.12.11
[cli][debug]  trio: 0.25.0
[cli][debug]  typing-extensions: 4.11.0 …
```
> plugins.afreeca: Support for password-protected streams

- src/streamlink/plugins/afreeca.py
The QUALITY variable is currently different from AfreecaTV.
And AfreecaTV currently has some support for 1440p.
Broadcasts that support 1440p have slightly different quality names than 1080p broadcasts, so we've modified them to give you flexibility in importing them.
1080p:
`sd: 360p, hd: 540p, hd4k: 720p, original: 1080p`
```
$ streamlink --loglevel debug https://play.afreecatv.com/cotton1217
NoTagError: `git describe --long --dirty --always --tags` could not find a tag
[cli][debug] OS:         Linux-6.5.13-1-pve-x86_64-with-glibc2.39
[cli][debug] Python:     3.11.8
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 0.0.0+unknown
[cli][debug]  certifi: 2024.2.2
[cli][debug]  exceptiongroup: 1.2.1 …
```
> plugins.afreeca: Enhance quality fetching

- src/streamlink_cli/console.py
- src/streamlink_cli/exceptions.py
- src/streamlink_cli/main.py
- tests/cli/test_console.py
- tests/cli/test_main.py
- tests/cli/test_main_check_file_output.py
- tests/cli/test_main_logging.py
Second attempt: #5044
Had these changes stashed for a while and forgot about it... This cleans up the random `console.exit()` calls and instead raises a `StreamlinkCLIError` exception, which is then caught in the `main()` function.
There's still a lot to do here in the future. For example, the entire `ConsoleOutput` implementation is pretty bad, especially in combination with the regular logging system and the download progress output, where it interweaves the progess and log lines. In the previous PR I also rewrote some tests. I didn't do this here and just did some bare minimum fixing of the existing tests, because it doesn't make sense writing/updating tests for the flawed CLI main module. Hopefully at some point in the future, the entire CLI will be rewritten with a clean design.
This …
> cli: remove console.exit()

- docs-requirements.txt
- https://pradyunsg.me/furo/changelog/#bold-burgundy
- https://pradyunsg.me/furo/changelog/#amazing-amethyst
Main changes are `:visted` link colors and disabled search result indexing for search engines.
> docs: bump furo theme version to 2024.04.27

- docs/_static/styles/custom.css
- docs/install.rst
In preparation for #5732 which will remove the py38 and x86 builds. The table has to go, hence the switch to the cards layout. Once only x86_64 builds are availble, the inner grid will be removed. Should there ever be ARM builds for Windows, then a simple badge can be added to the x86_64 one.
- https://sphinx-design.readthedocs.io/en/latest/grids.html
- https://sphinx-design.readthedocs.io/en/latest/cards.html
> docs: update Windows builds flavors

- docs/install.rst
- pyproject.toml
- src/streamlink/compat.py
- src/streamlink/plugins/twitch.py
- src/streamlink/webbrowser/webbrowser.py
- tests/webbrowser/cdp/test_client.py
- tests/webbrowser/cdp/test_connection.py
- tests/webbrowser/test_webbrowser.py
- Add `python_version<"3.11"` environment marker to `exceptiongroup`:
It's a no-op package on Python 3.11 and above, so we don't have to require it on all Python versions.
- Update compatibility imports
- Update dependency docs
----
`exceptiongroup` was added in #5895.
`exceptiongroup` also includes a bugfix for `contextlib.suppress` on `<3.12.1`, but that shouldn't be relevant to us:
https://github.com/agronholm/exceptiongroup/blob/1.2.1/src/exceptiongroup/__init__.py#L43-L46
The reason for this dependency update is that some distros like Arch have already started phasing out their `python-exceptiongroup` package because of their single Python 3.12 package where this compat lib is not needed:
https://archlinux.org/todo/drop-python-exceptiongroup/
For some reason though, they simple …
> build: only require exceptiongroup on py<3.11

- src/streamlink/plugins/chzzk.py
- tests/plugins/test_chzzk.py
Add plugin for [chzzk](https://chzzk.naver.com/) which is the streaming platform operating in South Korea. 
Resolves #5730
> plugins.chzzk: new plugin

- src/streamlink/plugins/tf1.py
Resolves #5379
This PR is aimed to provide authentification basis for the website TF1.fr. A step forward would be to check the user subscriptions, as now certain streams might be pay-per-view, under the TF1MAX subscription plan. The answer is the same as if you're not logged in, will answer "Permission insuffisante".
With recommendations from @bastimeyer earlier on, on issue 5379, I've rewrote the plugin to make sure it suits the standards.
> plugins.tf1: implement authentication

- dev-requirements.txt
- pyproject.toml
https://github.com/astral-sh/ruff/releases/tag/v0.4.5
> tools: bump ruff to 0.4.5 and fix issues

- src/streamlink/plugins/chzzk.py
Fixes: #6001
Any better suggestions are welcome.
> plugins.chzzk: live detail api response validation error fix

- docs/deprecations.rst
- src/streamlink/plugins/__init__.py
- tests/plugin/testplugin.py
- tests/test_plugins.py
These re-exports don't belong into the `streamlink.plugins` package. This was already deprecated during the Livestreamer era, more than 11 years ago:
https://github.com/streamlink/streamlink/blame/6458c4ac844b2b31e26ce6911d408d1a615d7434/src/streamlink/plugins/__init__.py#L1-L6
https://deploy-preview-6005--streamlink.netlify.app/deprecations
> plugins: officially deprecate re-exports

- src/streamlink/plugins/welt.py
```
$ ./script/test-plugin-urls.py welt
:: Finding streams for URL: https://welt.de/tv-programm-live-stream/
:: Found streams: 360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung192055593/Strip-the-Cosmos-Die-Megastuerme-der-Planeten.html
:: Found streams: 200k, 1000k, 1500k, 2000k, worst, best
:: Finding streams for URL: https://www.welt.de/mediathek/magazin/gesellschaft/sendung247758214/Die-Welt-am-Wochenende-Auf-hoher-See-mit-der-Gorch-Fock.html
:: Found streams: 700k, 1200k, 2400k, 4800k, worst, best
:: Finding streams for URL: https://www.welt.de/tv-programm-live-stream/
:: Found streams: 360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, …
```
> plugins.welt: fix validation schema

- src/streamlink/plugins/kick.py
- src/streamlink/session/http.py
- src/streamlink/session/http.pyi
- tests/conftest.py
- tests/plugins/test_kick.py
- tests/session/test_http.py
Three commits:
1. Add new test markers for excluding specific python versions
2. Refactor custom HTTPAdapter classes, so urllib3's SSLContext can be customized easily
3. Restore the plugin and use custom HTTPAdapter that disables the [`OP_NO_TICKET`](https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TICKET) SSLContext option
See https://github.com/streamlink/streamlink/issues/6018#issuecomment-2153150008
----
Working plugin from this PR branch using OpenSSL 3.0.13
```
$ docker run --rm -it ghcr.io/streamlink/appimage-buildenv-x86_64@sha256:537b8ef991c77cc633d932654aff3372cf7b4c233bb775b5ba8aa191dface5b1 bash -c '/opt/python/cp312-cp312/bin/python -m venv /venv;source /venv/bin/activate;pip install -q git+https://github.com/bastimeyer/streamlink@plugins/kick/restore;streamlink -l debug …
```
> plugins.kick: restore plugin with new HTTPAdapter

- src/streamlink/session/http.py
- tests/session/test_http.py
See https://github.com/streamlink/streamlink/issues/6018#issuecomment-2155891229
This uses a reference of the same `SSLContext` object in the `urllib3.ProxyManager`'s connection pool keywords as the regular `urllib3.PoolManager`.
I can't verify the proxy issue on kick.com though, as kick is blocking my entire server network. I'm using a socks5 tunnel via OpenSSH on my server, and regular HTTPS requests from the server don't work either.
Re-using the same SSLContext however is the correct thing to do:
- https://github.com/urllib3/urllib3/blob/2.2.1/src/urllib3/poolmanager.py#L587
- https://github.com/urllib3/urllib3/blob/2.2.1/src/urllib3/contrib/socks.py#L228
- https://github.com/urllib3/urllib3/blob/1.26.0/src/urllib3/poolmanager.py#L495
- …
> session.http: re-use SSLContext in ProxyManager

- src/streamlink/plugins/bilibili.py
Fixes #6031 
Offline
```
$ streamlink -l debug https://live.bilibili.com/22529135
[cli][debug] OS:         Linux-6.9.3-1-git-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.3
[cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[cli][debug] Streamlink: 6.7.4+20.g3bf12192
[cli][debug]  certifi: 2024.6.2
[cli][debug]  lxml: 5.2.2
[cli][debug]  trio: 0.25.1
[cli][debug]  typing-extensions: 4.12.1
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.8.0
[cli][debug]  url=https://live.bilibili.com/22529135 …
```
> plugins.bilibili: fix schema for offline channels

- src/streamlink/plugins/cnbce.py
- tests/plugins/test_cnbce.py
Resolves #6028 
https://en.wikipedia.org/wiki/CNBC-e
Content is geo-restricted. Checked using a VPN from Cyprus...
@ipstreet312 Please check and post a debug log
----
Geo-restriction
```
$ streamlink https://www.cnbce.com/canli-yayin
[cli][info] Found matching plugin cnbce for URL https://www.cnbce.com/canli-yayin
[plugins.cnbce][error] Could not access stream (geo-blocked content, etc.)
error: No playable streams found on this URL: https://www.cnbce.com/canli-yayin
```
With VPN
```
$ streamlink -l debug https://www.cnbce.com/canli-yayin best
[cli][debug] OS:         Linux-6.9.3-1-git-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.3
[cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[cli][debug] …
```
> plugins.cnbce: new plugin

- src/streamlink/session/http.py
In the custom base `SSLContextAdapter`, disable SHA1 digest ciphers by default, so the tests pass on all OpenSSL configurations.
This won't affect the `SSLContext` of the default `HTTPAdapter`.
----
See https://gitlab.archlinux.org/archlinux/packaging/packages/streamlink/-/issues/1
Can also easily be reproduced on `debian:sid`.
> session.http: disable weak digest ciphers

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
master
```
$ streamlink https://www.twitch.tv/clip/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/clip/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
error: No playable streams found on this URL: https://www.twitch.tv/clip/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
```
PR
```
$ ./script/test-plugin-urls.py twitch -r CHANNELNAME pgl_dota2
:: Finding streams for URL: https://clips.twitch.tv/GoodEndearingPassionfruitPMSTwin-QfRLYDPKlscgqt-4
:: Found streams: 360p30, 480p30, 720p60, 1080p60, worst, best
:: Finding streams for URL: https://player.twitch.tv/?parent=twitch.tv&channel=pgl_dota2
:: Found streams: audio_only, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: Finding streams for URL: …
```
> plugins.twitch: refactor matchers, fix clip URLs

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
Resolves #6015 
Compared to #6016, this time it doesn't touch any ad filtering logic.
See https://github.com/streamlink/streamlink/issues/6015#issuecomment-2145853480 why #6016 had to be reverted in #6019
@KynikossDragonn please check again if this does indeed fix all the discontinuty warning spam (apart from actual discontinuities between live and ad content)
> plugins.twitch: fix discontinuity warning spam

- src/streamlink/plugins/pluzz.py
- tests/plugins/test_pluzz.py
- Split into separate matchers for each supported site
- Update API URL
- Fix video ID validation schema
- Fix token URL validation schema
- Remove unnecessary `update_qsd()` calls
----
Resolves #6047
@uNouss please check if something's not working correctly that's not covered by the test URLs
```
$ HTTPS_PROXY=socks5h://localhost:1920 ./script/test-plugin-urls.py pluzz
:: Finding streams for URL: https://france3-regions.francetvinfo.fr/bourgogne-franche-comte/direct/franche-comte
:: Found streams: 216p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://la1ere.francetvinfo.fr/info-en-continu-24-24
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams …
```
> plugins.pluzz: refactor, upd API URL, fix schemas

- src/streamlink/plugins/vidio.py
- tests/plugins/test_vidio.py
Fixes #6056 
```
$ ./script/test-plugin-urls.py vidio
:: Finding streams for URL: https://www.vidio.com/live/204-sctv-tv-stream
:: Found streams: 240p_alt, 240p, 360p_alt, 360p, 480p_alt, 480p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: Finding streams for URL: https://www.vidio.com/live/5075-dw-tv-stream
:: Found streams: 240p, 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.vidio.com/live/777-metro-tv
:: Found streams: 240p, 360p, 480p, 720p, worst, best
:: Finding streams for URL: https://www.vidio.com/watch/766861-5-rekor-fantastis-zidane-bersama-real-madrid
:: Found streams: 270p, 360p, 720p, worst, best
```
```
$ streamlink -j https://www.vidio.com/live/5075-dw-tv-stream best | jq .metadata
{
"id": "5075",
"author": null,
"title": …
```
> plugins.vidio: fix stream token, add metadata

- dev-requirements.txt
- pyproject.toml
Ruff 0.5.1 reverted the forced decorator parentheses config for pytest fixtures and test markers.
https://github.com/astral-sh/ruff/pull/12106
Let's keep the parentheses though, because it's all about consistency. Test fixtures and markers with parameters obviously require them, so I don't see a reason to follow the new default config of ruff and remove them where no parameters are involved.
> tools: bump ruff to 0.5.1 and fix issues

- src/streamlink/plugins/twitch.py
Resolves #6070 
No idea if this justifies having another patch release just yet, considering that the Twitch plugin is priority number one... I'll think about it. Neither Twitch's website, nor my Twitch GUI use uppercase channel names in any way, so CLI users of Streamlink can always use lowercase channel names as a workaround in 6.8.2.
```
$ ./script/test-plugin-urls.py twitch -r CHANNELNAME HasanAbi -i video -i /v -i clip
:: https://player.twitch.tv/?parent=twitch.tv&channel=HasanAbi
::  audio_only, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: https://www.twitch.tv/HasanAbi
::  audio_only, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: https://www.twitch.tv/HasanAbi/
::  audio_only, 160p, 360p, 480p, 720p, 720p60, 1080p60, worst, best
:: …
```
> plugins.twitch: fix uppercase channel names

- src/streamlink/logger.py
- tests/test_logger.py
Follow-up of #6080 
This prevents potential character encoding errors on the logger's default streams, stdout and stderr, depending on the default stream encoding.
----
master
```
$ PYTHONIOENCODING=ascii streamlink -l debug -p mpv -a '"--title=🐻"' httpstream://file:///dev/zero best
[cli][debug] OS:         Linux-6.9.9-1-git-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.4
[cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[cli][debug] Streamlink: 6.8.3+1.g09c19cf8
[cli][debug]  certifi: 2024.7.4
[cli][debug]  lxml: 5.2.2
[cli][debug]  trio: 0.26.0
[cli][debug] …
```
> logger: backslashreplace stream encoding errors

- dev-requirements.txt
With `ruff 0.5.3` now considering its built-in language server to be stable and `ruff-lsp` not being necessary anymore, I'm thinking about using its formatter to reformat all files and then making its format mandatory as a CI check that runs `ruff format --diff`. Most major editors have support for auto-formatting via the LSP, so there's no reason not to finally clean up bad code styles. This could however make it more difficult for new and existing contributors to submit good PRs, but I don't think it'd be too bad if the docs are updated accordingly. I'm not a fan of commit hooks, so auto-reformat hooks on commit won't happen (local client setups should never be in the way of submitting PR).
- https://github.com/astral-sh/ruff/releases/tag/0.5.3
- https://docs.astral.sh/ruff/editors/ …
> tools: bump ruff to 0.5.3

- pyproject.toml
Except for `preview` (and `exclude`), all these config values are already the default, but let's define them explicitly.
- https://docs.astral.sh/ruff/settings/#format
- https://docs.astral.sh/ruff/formatter/#preview-style
Adding the formatter config doesn't change anything, as we still don't enforce a strict code style. But as said in #6087, I'm going to finally change that after dropping py38.
> tools: add explicit ruff format config

- src/streamlink/plugins/yupptv.py
- tests/plugins/test_yupptv.py
Resolves #6092 
The plugin extracted the wrong HLS playlist URL from their (garbage) JS code. This is fixed now. I've also refactored the plugin and fixed the bad code style, and I implemented ad filtering, as most streams seem to have preroll ads which then cause an unnecessary stream discontinuity. Ad segments apparently are lacking the `.ts` file extension in the segment URLs, which is used to detect ads. Hopefully this doesn't break actual stream segments. Seemed fine in the streams I checked though. I didn't touch the plugin's authentication logic. No idea if this is working at all. I don't really care though.
@DeltaEpsilon19498 please check the plugin changes and see if any streams which I didn't test are not working correctly …
> plugins.yupptv: refactor and fix plugin

- src/streamlink/plugins/tvp.py
- tests/plugins/test_tvp.py
Hello,
I've added handling of sport.tvp.pl live videos to the tvp plugin.
Admittedly I have little Python experience, but I tested the changes editing \pkgs\streamlink\plugins\_plugins.json, \pkgs\streamlink\plugins\tvp.py while removing the cached compiled file.
> plugins.tvp: sport.tvp.pl handling

- dev-requirements.txt
I've also tried bumping mypy to the latest version, but apparently there's an unresolved bug in regards to overloaded functions and type narrowing of `Any` arguments.
> tools: bump ruff to 0.5.5

- .github/workflows/test.yml
- build_backend/plugins_json.py
- build_backend/test_plugins_json.py
- src/streamlink/session/plugins.py
- tests/session/test_plugins.py
This adds warning comments to the plugins JSON file, so people who randomly try to modify plugin matchers don't break their Streamlink install. The comments are removed from the read data before parsing the actual JSON payload.
> build: add warning comments to plugins.json

- src/streamlink/webbrowser/cdp/client.py
- src/streamlink/webbrowser/cdp/connection.py
- tests/webbrowser/cdp/test_connection.py
Allow the `CDPClientSession` (via `CDPClient.session()`) to set custom memory channel buffer sizes, so that more HTTP requests/responses can be buffered without blocking
> webbrowser.cdp.client: add max_buffer_size param

- src/streamlink/plugins/sportschau.py
- tests/plugins/test_sportschau.py
The current plugin for sportschau.de is not working. 
Example: https://www.sportschau.de/olympia/sportschiessen-luftpistole-10m-mixed-im-re-live,video-olympia-sportschiessen-104.html
```
streamlink https://www.sportschau.de/olympia/sportschiessen-luftpistole-10m-mixed-im-re-live,video-olympia-sportschiessen-104.html
[cli][info] Found matching plugin sportschau for URL https://www.sportschau.de/olympia/sportschiessen-luftpistole-10m-mixed-im-re-live,video-olympia-sportschiessen-104.html
error: No playable streams found on this URL: https://www.sportschau.de/olympia/sportschiessen-luftpistole-10m-mixed-im-re-live,video-olympia-sportschiessen-104.html
```
This PR fixes it.
> plugins.sportschau: fix sportschau

- src/streamlink/plugin/api/aws_waf.py
- src/streamlink/plugins/vtvgo.py
Resolves #6099 
1. This adds the `plugin.api.aws_waf` module which uses Streamlink's webbrowser API in order to get an AWS Web Application Firewall token
2. Fixes the vtvgo plugin's bot-detection issue by acquiring an AWS WAF token
The token is cached for four days once successfully acquired. Chromium's headless mode unfortunately does not work because AWS detects it, so it's disabled (`--webbrowser-headless` has no effect).
```
$ ./script/test-plugin-urls.py vtvgo
:: https://vtvgo.vn/xem-truc-tuyen-kenh-k%C3%AAnh-vtv5-t%C3%A2y-nguy%C3%AAn-163.html
:::: Getting new AWS WAF token (bot-detection)
:::: Launching web browser: /usr/bin/chromium
::  480p, 720p, worst, best
:: https://vtvgo.vn/xem-truc-tuyen-kenh-vtv1-1.html
::  480p, 720p, worst, best
:: …
```
> plugins.vtvgo: acquire AWS WAF token

- src/streamlink/plugins/tiktok.py
Resolves #6105 
```
$ ./script/test-plugin-urls.py tiktok -r CHANNEL ktkt7621v6a -m
:: https://www.tiktok.com/@ktkt7621v6a
::  ao, ld, origin, sd, hd, worst, best
::   {'id': '7398851432071645960', 'author': '브롤 멜로디 잘하는사람', 'category': None, 'title': '제발 도와주세요 미코 30랭크 까지만 ㅜㅜㅜ'}
:: https://www.tiktok.com/@ktkt7621v6a/live
::  ao, ld, origin, sd, hd, worst, best
::   {'id': '7398851432071645960', 'author': '브롤 멜로디 잘하는사람', 'category': None, 'title': '제발 도와주세요 미코 30랭크 까지만 ㅜㅜㅜ'}
```
> plugins.tiktok: fix room ID schema

- src/streamlink/plugin/api/aws_waf.py
- src/streamlink/webbrowser/chromium.py
- tests/webbrowser/test_chromium.py
Resolves #6110 
Since this sets Chromium's `--user-agent=...` launch argument now, all supported Chromium forks need to be checked whether this launch argument exists there, too. It's very much possible that forks have removed or disabled it, which will then result in a launch failure. I'll have a look later when I get the time spinning up my VMs.
Any help from others however is very much appreciated.
> webbrowser.chromium: set --user-agent launch arg

- src/streamlink/plugins/twitch.py
Resolves #6109 
1. Adds the `--twitch-force-client-integrity-token` plugin argument (I didn't want to add another plugin arg when the CI token stuff was implemented, but since people are actively patching the plugin, let's just add the arg to make their lives a bit easier)
2. Removes the now broken CI token decoding+parsing due to the new token format with encrypted data
I also checked removing the `headless=False` override, and requesting access tokens worked just fine. This however might be because they simply don't care about the `is_bad_bot` flag right now. So what should we do now? Remove the value override and let the user decide again via `--webbrowser-headless` (defaults to `True`)? Should Twitch make any changes though, then people will actively have to set …
> plugins.twitch: add --twitch-force-client-integrity, remove CI token decoding+parsing logic

- src/streamlink/webbrowser/cdp/client.py
- src/streamlink/webbrowser/chromium.py
- tests/webbrowser/cdp/test_client.py
- tests/webbrowser/test_chromium.py
- Add `headless` keyword and attribute to `CDPClient`
- If in headless mode, read user-agent from CDP, remove headless hint, and then update UA via `Network.setUserAgentOverride()`
- Remove `--user-agent=...` Chromium launch argument if in headless mode as it also overrides the UA platform
----
Replaces #6111
See #6113 
/ping @Hakkin 
No changes to any plugins / CDPClient implementation yet...
Overriding the UA string via `Network.setUserAgentOverride()` worked in my AWS-WAF test. I don't know the difference between this and `Emulation.setUserAgentOverride()` though. The method from the CDP emulation domain might do more than overriding network request headers.
- https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-setUserAgentOverride
- …
> webbrowser.cdp.client: update UA in headless mode

- docs/ext_plugins.py
- src/streamlink/plugins/twitch.py
- src/streamlink/plugins/vtvgo.py
- tests/test_plugins.py
Plugins which use Streamlink's webbrowser API should be documented accordingly.
> docs: add $webbrowser plugin metadata item

- src/streamlink/session/options.py
- src/streamlink/webbrowser/cdp/client.py
- src/streamlink/webbrowser/chromium.py
- src/streamlink/webbrowser/webbrowser.py
- src/streamlink_cli/argparser.py
- tests/webbrowser/cdp/test_client.py
- tests/webbrowser/conftest.py
- tests/webbrowser/test_chromium.py
See https://github.com/streamlink/streamlink/pull/6114#issuecomment-2269268484
Since headless mode can potentially be detected, we shouldn't set it as the default mode. Plugins should always work reliably in their default configuration without users having to change Streamlink's default options should there be a change of headless mode detection by the website a plugin covers with Streamlink's webbrowser API. It doesn't matter that a short web browser window might appear on the user's screen (in the default configuration).
So, this changes the default value of `--webbrowser-headless` from `True` to `False` and now also logs which mode Chromium is being launched in. I don't consider this a "breaking change" (wouldn't be a real one anyway as it's only a change in behavior), as the entire …
> Change default value of --webbrowser-headless to False

- src/streamlink/plugins/twitch.py
Follow-up of #6116 
----
Successful streaming access tokens
```
$ streamlink --twitch-force-client-integrity --twitch-purge-client-integrity twitch.tv/gorgc
[cli][info] Found matching plugin twitch for URL twitch.tv/gorgc
[plugins.twitch][info] Removing cached client-integrity token...
[plugins.twitch][info] Acquiring new client-integrity token...
[webbrowser.webbrowser][info] Launching web browser: /usr/bin/chromium (headless=False)
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
$ streamlink --twitch-force-client-integrity --twitch-purge-client-integrity --webbrowser-headless=true twitch.tv/gorgc
[cli][info] Found matching plugin twitch for URL twitch.tv/gorgc
[plugins.twitch][info] Removing cached client-integrity token...
[plugins.twitch][info] …
```
> plugins.twitch: remove headless=False override

- .readthedocs.yml
Testing readthedocs as a hoster for PR preview builds of Streamlink's documentation, because Netlify doesn't bother updating their Python versions which is now causing dependency issues.
Resolves #5543
----
The first attempts will very likely fail. I only quickly glanced through their docs. Will refine the build config later.
There's the `$READTHEDOCS_VERSION_TYPE == external` check, which will abort all other builds apart from PR preview builds:
- https://docs.readthedocs.io/en/stable/reference/environment-variables.html#envvar-READTHEDOCS_VERSION_TYPE
- https://docs.readthedocs.io/en/stable/builds.html#cancelling-builds
PR preview URLs should be added as a status check, similar to netlify:
- https://docs.readthedocs.io/en/stable/pull-requests.html#pull-request-previews
The default RTD …
> ci: build docs previews on readthedocs

- CHANGELOG.md
I'd also like to include the bloomberg plugin fixes (#6107) in this release, but I still haven't gotten any feedback from anyone so far. All it takes is running the plugin from the PR branch and a confirmation that the webbrowser fallback does indeed work should the initial HTTP request not include the streams JSON data. Takes one minute... I'm getting valid JSON data without the need for the fallback, so I can't test this.
Then there's the Windows builds and Linux AppImages changes (#6052). I said I wanted to do this in the next minor version bump, but I think I'll wait until 7.0.0 which will pull the plug for py38 entirely in October, which is less than two months away.
- https://github.com/streamlink/streamlink/compare/6.8.3...bastimeyer:releases/6.9.0
- …
> release: 6.9.0

- src/streamlink/webbrowser/chromium.py
- tests/webbrowser/test_chromium.py
This skips using http-session proxies (set via `--http-proxy`) when requesting Chromium's IPC websocket URL when using the webbrowser API.
See https://github.com/streamlink/streamlink/discussions/6129#discussioncomment-10315629
It does NOT forward any proxy settings to the launched Chromium process. This is still unsupported.
----
The following example acquires an integrity token using the local IP address, while making any regular HTTP requests using the set proxy.
```
$ streamlink --http-proxy socks5h://localhost:1920 --twitch-force-client-integrity --twitch-purge-client-integrity twitch.tv/gorgc best
[cli][info] Found matching plugin twitch for URL twitch.tv/gorgc
[plugins.twitch][info] Removing cached client-integrity token...
[plugins.twitch][info] Acquiring new client-integrity …
```
> webbrowser.chromium: skip proxy on WS URL request

- .codecov.yml
- .github/workflows/test.yml
First CPython 3.13 beta release will be tagged in a week:
https://peps.python.org/pep-0719/#release-schedule
This PR adds CI test runners for 3.13 with the required compatibility wheels of certain dependencies.
But let's not merge this yet...
> ci.github: add Python 3.13-dev test runners

- pyproject.toml
- tests/webbrowser/test_chromium.py
- tests/webbrowser/test_webbrowser.py
This adds some more linting rules for async code and the initialization of logger classes.
Going to add the [`G` ruff rules (flake8-logging-format)](https://docs.astral.sh/ruff/rules/#flake8-logging-format-g) for more code cleanups together with the `ruff format` changes after dropping py38, as the `G` rules will require fixing more than 300 logger calls (no str.format() calls or f-strings as log messages - log message arguments should only be formatted when the log level matches).
> tools: add ASYNC and LOG rules to ruff config

- docs-requirements.txt
- docs/conf.py
- keep sphinx-design 0.5.0, so docs can still be built on py38
- allow building docs using Sphinx 8 (sphinx-design >=0.6.0)
- fix Sphinx tags deprecation warning
----
- https://sphinx-design.readthedocs.io/en/latest/changelog.html
- https://www.sphinx-doc.org/en/master/changes/8.0.html
- https://github.com/sphinx-doc/sphinx/commit/d2f1acc0cade3b02d24dbdade5533405b6424b1f
> docs: bump sphinx-design to >=0.5.0,<=0.6.1

- src/streamlink/logger.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/test_main_logging.py
- tests/test_logger.py
This allows changing the default log format and log date format, which can be useful in some cases, or for specific applications using Streamlink via its CLI which parse the log output.
There's currently no validation of the format, so if the user inputs invalid variables, the error messages with tracelog will be pretty ugly...
```
$ streamlink -l debug | grep Streamlink
[cli][debug] Streamlink: 6.9.0+10.g9d323e3e
```
```
$ streamlink -l all | grep Streamlink
[13:31:07.558270][cli][debug] Streamlink: 6.9.0+10.g9d323e3e
```
```
$ streamlink -l debug --logformat '[{asctime}][{filename}][{name}][{levelname}] {message}' --logdateformat '%Y-%m-%dT%H:%M:%S.%f' | grep Streamlink
[2024-08-25T13:33:53.689482][main.py][cli][debug] Streamlink: 6.9.0+10.g9d323e3e
```
> cli: add --logformat and --logdateformat

- src/streamlink/logger.py
- src/streamlink_cli/main.py
- tests/cli/test_main_logging.py
- tests/test_logger.py
1. This fixes repeated errors being written to stderr whenever a new log message fails to be written to stdout due to the stream pipe being closed by the other process, e.g. when executing `streamlink -l debug | head -n1`. This issue is caused when trying to flush the stdout stream buffer after writing a log message. Python's `logging` module explicitly doesn't handle this case (for some reason).
The fix is to simply ignore `OSError` (`BrokenPipeError`) in [`logging.StreamHandler.flush()`](https://github.com/python/cpython/blame/v3.12.5/Lib/logging/__init__.py#L1137-L1146). On Windows, `BrokenPipeError` is not raised and instead a simple `OSError` with `errno=EINVAL`.
As an optimization, follow-up log calls [could all be ignored by overriding …
> Fix OSError (BrokenPipeError) on stdout flush

- src/streamlink/plugins/pandalive.py
- tests/plugins/test_pandalive.py
Fixes #6147
```
$ ./script/test-plugin-urls.py pandalive -m -r CHANNEL s22unn22
:: https://www.pandalive.co.kr/live/play/s22unn22
:::: Broadcast type: rec
::  160p, 360p, 480p, 720p60, 1080p60, worst, best
::   {'id': None, 'author': 'ෆ세은ෆ (s22unn22)', 'category': None, 'title': '[녹] 오늘 낮 3시방송 본방사수!!!'}
```
```
$ streamlink -l debug https://www.pandalive.co.kr/live/play/s22unn22 best
[cli][debug] OS:         Linux-6.10.6-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.12.4
[cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[cli][debug] Streamlink: 6.9.0+18.g0ea86fbf
[cli][debug]  certifi: 2024.7.4
[cli][debug]  lxml: 5.3.0 …
```
> plugins.pandalive: fix missing HTTP headers

- .github/workflows/useragents.yml
The useragents module was moved/renamed in #6112 last month. Apparently I forgot to add the updated CI workflow file to the commit (leading dot in the path).
This PR fixes that, updates the `peter-evans/create-pull-request` 3rd party action to the latest version, and adds the `workflow_dispatch` event, which I will trigger after merging, so the UAs can be updated for this month.
The CI run from earlier today obviously didn't add the modified file, so nothing was committed and no PR was opened:
https://github.com/streamlink/streamlink/actions/runs/10649258855/job/29519199821#step:6:92
> ci.github: fix useragents workflow

- src/streamlink/session/options.py
- src/streamlink/stream/ffmpegmux.py
- src/streamlink_cli/argparser.py
- tests/stream/test_ffmpegmux.py
Hello.
When creating a plugin using FFMPEGMuxer, I wanted to display a finer log level (verbose, debug) than FFmpeg's info, so I added the argument “--ffmpeg-loglevel”. 
[ffmpeg Documentation: 5.2 Generic options](https://www.ffmpeg.org/ffmpeg.html#Generic-options)
```sample_console
[soprano1125@localhost streamlink]$ ffmpeg -hide_banner -loglevel test
Invalid loglevel "test". Possible levels are numbers or:
"quiet"                                                                                                                                            
"panic"                                                                                                                                            
"fatal" …
```
> stream.ffmpegmux: add loglevel

- src/streamlink/plugins/dlive.py
Fixes #6170
HLS media playlist URLs now require a signature, which needs to be acquired by sending a POST request to a specific API endpoint.
```
$ streamlink https://dlive.tv/kriminel best
[cli][info] Found matching plugin dlive for URL https://dlive.tv/kriminel
[cli][info] Available streams: 360p (worst), 480p, 720p, src (best)
[cli][info] Opening stream: src (hls)
```
> plugins.dlive: sign live HLS media playlist URLs

- src/streamlink/plugins/vk.py
- tests/plugins/test_vk.py
Fixes #6177
This
- simplifies the pluginmatchers
- adds the missing `list` API request param (required by some videos)
- adds the missing `hls_ondemand`/`dash_ondemand` items to the validation schema
- handles inaccessible videos in the validation schema
- updates the pluginmatcher and URL redirection tests
```
$ ./script/test-plugin-urls.py vk
:: https://vk.com/dota2?w=wall-126093223_1057924
::  144p, 240p, 360p, 480p, 720p, 1080p, worst, best
:: https://vk.com/search?c%5Bq%5D=dota&c%5Bsection%5D=auto&z=video295508334_171402661
::  144p, 240p, 360p, 480p, 720p, worst, best
:: https://vk.com/video-122792749_456242046?list=ln-YXS9u57K48LhkU6C3X
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://vk.com/video-9944999_456239622
::  144p, 240p, 360p, 480p, 720p, worst, best
:: …
```
> plugins.vk: fix API params and validation schema

- tests/utils/test_named_pipe.py
Scheduled tests failed today:
https://github.com/streamlink/streamlink/actions/runs/10821794638/job/30024523254#step:7:286
Join reader thread after awaiting its `done` event before continuing with test assertions (and fix incorrect timeout values).
https://github.com/streamlink/streamlink/blob/5d9b7163b931b77678a438758f76e582e572dde4/tests/utils/test_named_pipe.py#L27-L32
> tests: fix race condition in named-pipe tests

- tests/cli/main/conftest.py
When running `test_handle_url[no-plugin]` and not finding a matching plugin, an HTTP request will be made for checking HTTP redirections. This in turn means that the test's `doesnotexist` hostname will be looked up, which unnecessarily delays test execution.
Simply use the `requests_mock` fixture in all CLI-main tests to mock the session's HTTPAdapter and prevent any DNS lookups.
----
https://github.com/streamlink/streamlink/blob/b788b1e4467ae7813616e637a06fbde83f17ded1/tests/cli/main/test_handle_url.py#L97-L106
[Test (windows-latest, 3.12)](https://github.com/streamlink/streamlink/actions/runs/10866640205/job/30154450498#step:7:299)
```
============================ slowest 10 durations =============================
7.07s call …
```
> tests: fix cli.main.handle_url tests

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
Streamlink overrides `ArgumentParser._match_argument()` in order to be able to parse `--arg -v` arguments. By default `-v` is interpreted as an argument-parser argument, and not as a value. This was fixed in #2333, but the method of the stdlib has received a change after our override was merged. This PR fixes that, fixes the code formatting, and adds missing tests for full code coverage.
- https://github.com/python/cpython/blame/v3.13.0rc2/Lib/argparse.py#L2227-L2247
- https://github.com/python/cpython/commit/be5c79e0338005d675a64ba6e5b137e850d556d1
> cli.argparser: update _match_argument() override

- src/streamlink_cli/output/file.py
- tests/cli/output/test_file.py
Continuing with some test rewrites, this PR rewrites the `FileOutput` tests based on pytest. The only `unittest.TestCase`-based tests remaining are now HLS integration tests.
> tests: rewrite cli.output.file tests

- src/streamlink/logger.py
- src/streamlink_cli/compat.py
- src/streamlink_cli/main.py
- src/streamlink_cli/streamrunner.py
- tests/cli/main/test_logging.py
- tests/cli/test_compat.py
- tests/cli/test_streamrunner.py
- tests/test_logger.py
Follow-up of #6142
This fixes the case where `sys.stdout` is `None`, when the Python process doesn't have the stdout file descriptor (fd1). This can be forced in BASH for example, by appending `>&-`.
```py
import pathlib,os,sys
pid = str(os.getpid())
fd1 = pathlib.Path("/proc", pid, "fd", "1")
sys.stderr.write(f"{pid=}\n{sys.stdout is None=}\n{fd1.readlink() if fd1.exists() else None=}\n")
```
```sh
$ python <<< "${CODE}"
pid='318408'
sys.stdout is None=False
fd1.readlink() if fd1.exists() else None=PosixPath('/dev/pts/2')
```
```sh
$ python <<< "${CODE}" >&-
pid='318428'
sys.stdout is None=True
fd1.readlink() if fd1.exists() else None=None
```
Currently on master, this results in an `AttributeError`, as the `streamlink_cli.compat` module assigns its `stdout` attribute to …
> cli: add devnull fallback for missing stdout fd

- docs/install.rst
This reverts #5980
`trio-websocket` now finally fully supports the `strict_exception_groups=True` breaking change introduced by `trio==0.25`, and fixed its failing tests. This is still unreleased though.
https://github.com/python-trio/trio-websocket/commit/f5fd6d77db16a7b527d670c4045fa1d53e621c35
The Alpine Linux package maintainers have now added the patch to their `py3-trio-websocket` package and restored it and its dependants, namely Streamlink.
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/72300
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/72332
With `trio-websocket` being fixed, package maintainers of other distros will hopefully also update their packages soon. Unlike Alpine, they simply kept old versions around.
Btw, these issues never affected …
> docs: add back Alpine Linux package

- src/streamlink_cli/main.py
- tests/cli/main/test_output_stream_passthrough.py
Fixes #6206 
```
$ env PATH="" ~/venv/streamlink-312/bin/python -m streamlink --no-config -l debug --player-passthrough=hls twitch.tv/esl_dota2 best
NotVCSError: Git not installed; assuming this isn't a Git repository
[cli][debug] OS:         Linux-6.11.0-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.12.6
[cli][debug] OpenSSL:    OpenSSL 3.3.2 3 Sep 2024
[cli][debug] Streamlink: 0.0.0+unknown
[cli][debug]  certifi: 2024.8.30
[cli][debug]  lxml: 5.3.0
[cli][debug]  trio: 0.26.2
[cli][debug]  trio-websocket: 0.12.0.dev0
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug] …
```
> cli: fix passthrough without player

- dev-requirements.txt
- pyproject.toml
- src/streamlink/utils/processoutput.py
- tests/cli/test_streamrunner.py
- tests/testutils/handshake.py
- tests/testutils/test_handshake.py
- tests/utils/test_processoutput.py
The `utils.processoutput` utility is currently used by `FFMPEGMuxer` to validate the ffmpeg binary by reading its version string and compile flags.
This was previously done using `asyncio` from the stdlib, hence the requirement of `pytest-asyncio` in the tests. The only other tests making use of the `asyncio` run loop were the CLI's `StreamRunner` tests (just for convenience though) and the `handshake` test utilities for making assertions about thread synchronization.
Since Streamlink's webbrowser API is based on `trio`, it doesn't make sense mixing async run loops from two different libs. On Windows, this also raises a warning when running Streamlink's testsuite.
The rewritten `utils.processoutput` module and its tests are now much cleaner and easier to read due to trio's structured …
> Rewrite asyncio-based `utils.processoutput` code based on trio and remove `pytest-asyncio` dev-requirement

- src/streamlink/session/plugins.py
- src/streamlink/utils/module.py
- tests/utils/test_module.py
Always look up and return already cached modules, but allow overriding cached modules if `override` is set to `True`.
Set `override=True` when calling `exec_module()` in `StreamlinkPlugins._load_plugin_from_finder()`.
----
See https://github.com/streamlink/streamlink/pull/6218#issuecomment-2395065369
The only other place where `load_module` and `exec_module` are currently used apart from `StreamlinkPlugins` (lazy plugins loader), is `tests/test_plugins.py`, where all plugin modules are loaded for the parametrization of plugin-module tests (has a test module? has plugin matchers defined? exports `__plugin__`? etc...).
Since we're now returning the already cached plugin modules from pytest's collector in `tests/plugins/test_*.py` rather than re-executing everything, this should also improve …
> utils.module: add override parameter

- .git-blame-ignore-revs
This ignores commit 1 and 3 of the now merged #6218 in git-blame.
- 16a1d84386539c8c8e480b73a519e179fcb8703c
- 045166b52acb62af4d6e3e3635ffaf4bd23c0e31
> tools: ignore typing refactor commits in git-blame

- src/streamlink/session/options.py
- tests/session/test_options.py
Noticed that bug while updating the typing annotations.
The `--interface` CLI argument (and its respective session option `interface`) currently only affects the `HTTPAdapter`s mounted at `http://` and `https://` (the default configuration). Some plugins however not only override the default adapters, but extend the adapter mapping with custom schemes or additional hostnames that must match:
- https://github.com/streamlink/streamlink/blob/20a58b9c88e1348f453cc4bb3567e0a937ed74a2/src/streamlink/plugins/abematv.py#L261-L263
- https://github.com/streamlink/streamlink/blob/20a58b9c88e1348f453cc4bb3567e0a937ed74a2/src/streamlink/plugins/kick.py#L48
- https://github.com/streamlink/streamlink/blob/20a58b9c88e1348f453cc4bb3567e0a937ed74a2/src/streamlink/plugins/filmon.py#L184-L186
> session: fix --interface on custom HTTPAdapters

- .github/workflows/test.yml
CI won't pass until actions/python-versions#312 has been merged.
edit:
Merged an hour ago, restarting failed CI jobs, and then going to merge...
> ci.github: remove -dev suffix from py313 runners

- .codecov.yml
- .github/workflows/test.yml
- docs/install.rst
- pyproject.toml
- setup.py
> chore: drop support for Python 3.8

- docs/install.rst
Closes #5732 
I'm going to merge this PR once the Linux AppImage and Windows builds have been updated. I don't know though when this will happen, because it's not particularly urgent to update the AppImages right now. I'll probably do this on Streamlink's next release with a minor version bump (`6.9.x`).
----
CentOS 7 will reach its EOL at the end of this week on 2024-07-01, which is what the `pypa/manylinux2014` docker images are based on, which in turn is what Streamlink's AppImages are currently based on. This means that the AppImages will have to switch to newer manylinux images, namely `manylinux_2_28` (AlmaLinux 8 based with glibc 2.28), which will be the end for "32 bit" i686 AppImages.
- https://endoflife.date/centos
- https://github.com/pypa/manylinux/blob/095daf5fc97b98aa0f1e48c3 …
> docs: drop i686 Linux AppImages and x86+py38 Windows builds

- src/streamlink/session/options.py
- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
- tests/session/test_options.py
Remove the following deprecated session options:
- `hls-segment-attempts`
- `hls-segment-threads`
- `hls-segment-timeout`
- `hls-timeout`
- `dash-segment-attempts`
- `dash-segment-threads`
- `dash-segment-timeout`
- `dash-timeout`
- `http-stream-timeout`
and their respective CLI arguments (DASH CLI args didn't exist):
- `--hls-segment-attempts`
- `--hls-segment-threads`
- `--hls-segment-timeout`
- `--hls-timeout`
- `--http-stream-timeout`
> session: remove deprecated stream-type options

- docs/cli/config.rst
- src/streamlink_cli/constants.py
- src/streamlink_cli/main.py
- tests/cli/main/test_setup_config_args.py
This will remove support for the old and deprecated config file paths in the 7.0.0 release.
Those old config paths have been deprecated since 2.2.0 (2021-06-19):
- https://streamlink.github.io/deprecations.html#config-file-paths
- https://streamlink.github.io/changelog.html#streamlink-2-2-0-2021-06-19
TODO: Update the docs' migrations page
> cli: remove deprecated {,plugin-}config paths

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/main/test_output_stream.py
One of the breaking changes to be included in 7.0.0.
Deprecation was introduced by #5268 in [5.4.0 on 2023-04-12](https://streamlink.github.io/changelog.html#streamlink-5-4-0-2023-04-12)
> cli: remove deprecated --force-progress argument

- docs/cli/plugin-sideloading.rst
The example path was accidentially removed in 9ca7660
> docs: restore plugin sideloading path on Windows

- src/streamlink_cli/argparser.py
- src/streamlink_cli/console.py
- src/streamlink_cli/main.py
- tests/cli/main/test_check_file_output.py
- tests/cli/test_argparser.py
- tests/cli/test_console.py
Follow-up of c587485
- Fix `AttributeError` when asking for input for required plugin args
- Fix `AttributeError` when confirming file output path
----
master - file output
```
$ streamlink httpstream://file:///dev/zero best -o /tmp/recording </dev/null
[cli][info] Found matching plugin http for URL httpstream://file:///dev/zero
[cli][info] Opening stream: live (http)
/tmp/recording
[cli][error] File /tmp/recording already exists, use --force to overwrite it.
```
```
$ streamlink httpstream://file:///dev/zero best -o /tmp/recording 0>&-
[cli][info] Found matching plugin http for URL httpstream://file:///dev/zero
[cli][info] Opening stream: live (http) …
```
> cli: fix errors on missing stdin fd

- src/streamlink/plugins/tv3cat.py
- tests/plugins/test_tv3cat.py
Resolves #6241 
That site apparently has changed its hostname while still supporting the old one, which redirects. Didn't check any changes to the site itself, since updating the matchers alone seemed to work.
```
$ ./script/test-plugin-urls.py tv3cat
:: https://www.3cat.cat/3cat/directes/tv3/
::  480p, 720p, 1080p, worst, best
:: https://www.3cat.cat/3cat/t1xc1-arribada/video/6260741/
::  720p_dash, 576p, 720p, 1080p, worst, best
:: https://www.ccma.cat/3cat/buscant-la-sostenibilitat-i-la-tecnologia-del-futur/video/6268863/
::  720p_dash, 576p, 720p, 1080p, worst, best
:: https://www.ccma.cat/3cat/directes/324/
::  480p, 720p, 1080p, worst, best
:: https://www.ccma.cat/3cat/directes/catalunya-radio/
::  96k, worst, best
:: https://www.ccma.cat/3cat/directes/esport3/
:::: The content is …
```
> plugins.tv3cat: update plugin matchers

- src/streamlink/options.py
- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
- tests/test_options.py
```
$ streamlink twitch.tv/CHANNEL
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
error: No playable streams found on this URL: twitch.tv/CHANNEL
```
```
$ streamlink twitch.tv/CHANNEL --twitch-disable-hosting --twitch-disable-reruns
[warnings][streamlinkdeprecation] The --twitch-disable-hosting plugin argument has been disabled and will be removed in the future
[warnings][streamlinkdeprecation] The --twitch-disable-reruns plugin argument has been disabled and will be removed in the future
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
error: No playable streams found on this URL: twitch.tv/CHANNEL
```
```
$ echo -e 'twitch-disable-hosting\ntwitch-disable-reruns' > /tmp/config
$ streamlink --config /tmp/config twitch.tv/CHANNEL …
```
> cli: warn when deprecated plugin argument is set

- dev-requirements.txt
- src/streamlink/stream/hls/hls.py
The mypy bump requires a fix since their 1.12.0 release includes a regression in regards to unions of iterators and iterables, so we need to explicitly turn the `list` object into an `Iterator`, so that it matches the type of `reversed(...)`
> `src/streamlink/stream/hls/hls.py:422:24: error: Item "list[HLSSegment]" of "Union[Iterator[HLSSegment], list[HLSSegment]]" has no attribute "__next__"  [union-attr]`
> tools: bump ruff to 0.6.9 and mypy to 1.12.0

- src/streamlink_cli/argparser.py
- tests/cli/test_argparser.py
This allows keeping the values of deprecated plugin arguments
> cli: keep values of deprecated plugin arguments

- docs/migrations.rst
The 7.0.0 migration notes added in #6235 didn't use the same format as the other migration notes on that page.
> docs: rewrite 7.0.0 migrations

- src/streamlink_cli/output/player.py
- tests/cli/output/test_player.py
VLC allows having custom variables in its --input-title-format parameter value for displaying certain **stream metadata**, for example `$a` for the stream author metadata or `$t` for the stream title metadata.
To avoid unintended variable substitution, `$` characters need to be escaped by replacing `$` with `$$`.
https://wiki.videolan.org/Documentation:Format_String/
When Streamlink's --title argument was implemented in 5c3cf57, a workaround was added for VLC, so users could escape a dollar sign with a leading backslash in the --title value, so the resulting `\$$` sequence would be turned back into a regular `$`, allowing VLC to interpret stream metadata variables.
However, the title value that's passed to `PlayerOutput` is already formatted by the CLI's `Formatter` instance, which means …
> cli.output: remove VLC stream metadata variables

- src/streamlink_cli/argparser.py
- tests/cli/main/test_logging.py
- Remove unnecessary line breaks and adjust line length in preparation for indentation changes
- Fix minor spelling, grammar and punctuation errors, as well as names
- Rephrase and always use imperative or a descriptive style without talking to the reader or in third person
- Use common style when enumerating possible values
- Reference other related arguments where it makes sense
- Explicitly mention stdout/stderr instead of console output
- Rewrite incorrect/inaccurate and outdated help texts
> cli.argparser: rewrite and fix help texts

- src/streamlink/logger.py
- src/streamlink_cli/main.py
- rearrange keywords based on `logging.basicConfig()`
- remove TODO note, as "format" is also used in `logging.basicConfig()`
----
I added the "rename to fmt" TODO note for the `format` keyword in 85ea235d139d5505307157643807d6f04b02f59c when I added ruff's "A" linting rules, as it shadows `builtins.format`, but since `logging.basicConfig()` uses the same keyword name and since `streamlink.logger.basicConfig()` is based on it, it doesn't make sense using a different name.
https://docs.python.org/3/library/logging.html#logging.basicConfig
> logger: mark basicConfig kwargs as kw-only

- .readthedocs.yml
The version strings in the PR preview builds on RTD are currently not working
https://app.readthedocs.org/projects/streamlink/builds/26084325/#248769245--66
because RTD creates a shallow clone with a fetch depth of 50, which is hardcoded:
https://github.com/readthedocs/readthedocs.org/blame/727da6e216f0fd0d08f7921b72de92a9c26fb25a/readthedocs/vcs_support/backends/git.py#L34
The current "fetch tags" command doesn't unshallow, so the latest tag can't be reached from any PR, resulting in a failure when running `git describe --tags`. It also fetches every tag, which is not what we want either.
https://github.com/streamlink/streamlink/blob/47d8e1d1b78362b5320788dd643b80a30ade6104/.readthedocs.yml#L10
----
This PR therefore updates the fetch tags logic, only targets the latest tag after …
> ci.readthedocs: update fetch depth with tags

- src/streamlink/plugin/plugin.py
This fixes the missing `Plugin.session` attribute documentation, switches the used docstring format, and fixes some documentation issues.
The order of attributes is unfortunately not respected by Sphinx for some strange reason, despite `bysource` being set as `member-order` in Sphinx's autoclass directive. Must have something to do with some of the attrs being set in the constructor. Or it's a bug, don't know...
https://github.com/streamlink/streamlink/blame/e4fe1ed6acbbf72602ea65e7783f167edc10687b/docs/api/plugin.rst#L8
> plugin: update and fix Plugin attr docstrings

- src/streamlink_cli/main.py
- tests/cli/main/test_logging.py
This also sorts the dependency names alphabetically...
master
```
$ streamlink -l debug
[cli][debug] OS:         Linux-6.11.5-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.13.0
[cli][debug] OpenSSL:    OpenSSL 3.4.0 22 Oct 2024
[cli][debug] Streamlink: 6.11.0+67.g4af4a88a
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug]  trio: 0.27.0
[cli][debug]  trio: 0.27.0
[cli][debug] …
```
> cli: fix duplicate dependency logging

- docs/index.rst
VLC should not be mentioned on the docs' index page without mpv.
Linking to the API guide while talking about the Python API also doesn't make sense, so use the correct link.
> docs: update index page

- CHANGELOG.md
Closes #6228
Preliminary changelog for `7.0.0`. The release date is currently just a template value.
No idea if I've missed something. Will check when it's ready...
> release: 7.0.0

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- src/streamlink_cli/show_matchers.py
- tests/cli/main/test_show_matchers.py
This adds the `--show-matchers` CLI argument for listing a plugin's matchers. Regular text and JSON output is supported.
While the JSON output contains all data (excluding the redundant `re.UNICODE` flag), the regular text output uses **yaml-like** syntax, skips missing matcher names and default priorities/flags, uses text for priority constants and flags (human readable), and it puts verbose regex patterns on the next line with a secondary indentation level. As said, it's not valid yaml, as it would require quoting+escaping the single-line regex patterns or adding yaml block-style indicators, which would make reading more difficult.
Plugin sideloading is of course supported.
Examples
```
$ streamlink --show-matchers twitch
- name: player
pattern: https?://player\.twitch\.tv/\?.+
- name: …
```
> cli: add --show-matchers argument

- .github/workflows/test.yml
See #6289
This ignores error 141 (pipefail) and preserves other exit codes. As mentioned, the tags are always fetched fine by `git fetch`, so this must be some kind of race condition in the Windows builds of `bash`, `git` or `awk`. I don't want to debug this further, because it's stupid. The piped commands should never fail with 141.
Going to restart the CI runs a couple of time before merging, just like in #6289... That PR didn't catch the error which occurred during the scheduled CI runs though.
> ci.github: ignore git fetch pipefail on Windows

- src/streamlink/plugin/plugin.py
- src/streamlink/session/plugins.py
- tests/session/test_plugins.py
- tests/test_plugin.py
This fixes accidentally shared `matchers` and `arguments` references in plugin classes which inherit from existing plugin classes.
It's not really a problematic issue, as it's very unlikely that the ancestor plugin class is used in a Streamlink session when it's already overridden by a plugin subclass in the same session, but it should still be fixed.
These changes unfortunately make the `Plugin` API docs look a bit weird.
----
Fixing this also made me realize that we never deprecated the old `arguments = Arguments(...)` definition style in plugin classes. The docs tell the user to always use the plugin decorators, but this is not enforced, hence why there's even a test case for the old plugin arguments definition. The matchers definition is theoretically also possible this way. This …
> plugin: fix shared matchers and arguments in inherited plugins

- src/streamlink/plugins/welt.py
```
$ ./script/test-plugin-urls.py welt
:: https://welt.de/tv-programm-live-stream/
::  360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: https://www.welt.de/mediathek/dokumentation/space/strip-the-cosmos/sendung192055593/Strip-the-Cosmos-Die-Megastuerme-der-Planeten.html
::  200k, 1000k, 1500k, 2000k, worst, best
:: https://www.welt.de/mediathek/magazin/gesellschaft/sendung247758214/Die-Welt-am-Wochenende-Auf-hoher-See-mit-der-Gorch-Fock.html
::  700k, 1200k, 2400k, 4800k, worst, best
:: https://www.welt.de/tv-programm-live-stream/
::  360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
:: https://www.welt.de/tv-programm-n24-doku/
::  360p_alt, 360p, 432p_alt, 432p, 720p_alt, 720p, 1080p_alt, 1080p, worst, best
```
> plugins.welt: fix schema

- src/streamlink/stream/dash/dash.py
- src/streamlink/stream/ffmpegmux.py
- src/streamlink/stream/segmented/segmented.py
- tests/stream/dash/test_dash.py
DASH streams currently fail with an ugly error traceback if FFmpeg is unavailable or can't be used.
This is because the `FFMPEGMuxer` instance which is created in `DASHStream.open()` checks for `FFMPEGMuxer.is_usable()` itself in its constructor and raises a `StreamError` if FFmpeg is unavailable. This is bad for multiple reasons, because the substreams were already opened and don't get closed properly in this case, and their respective worker threads still try to enqueue new segments, leading to the error. On top of that, some class attributes are uninitialized and another thread-join call fails too.
As a simple solution for now, check for the FFmpeg availabilty in `DASHStream.open()` before opening any substreams. This fix also has the side-effect of falling through to video-only or …
> stream.dash: fix missing FFMPEGMuxer.is_usable()

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_dynamic_no_publish_time_timeline_with_start.mpd
- tests/resources/dash/test_dynamic_no_publish_time_timeline_without_start.mpd
- tests/stream/dash/test_manifest.py
Remove requirement from `publishTime` and `availabilityStartTime` in dynamic DASH manifests and simply default to UNIX Epoch.
----
Resolves #6322 
According to ISO/IEC 23009-1:2022 section 5.3.1.2, `MPD@publishTime` is an optional attribute with a default value, and it "shall be present" in dynamic manifests, same as the `MPD@availabilityStartTime` attribute. For static manifests, we've already set these attributes to optional in the parser, as they are not important in this case.
For dynamic manifests however, defaulting to UNIX Epoch can be problematic, depending on whether segment timelines include at least one timestamp anchor or not. If they don't, as the `SegmentTimeline.S@t` attribute is optional (section 5.3.9.6.2), then their anchor is the manifest's publishTime. Defaulting to …
> stream.dash: opt publishTime/availabilityStartTime

- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_baseurl_urljoin.mpd
- tests/stream/dash/test_manifest.py
- Remove `BaseURL.join()` and replace it with simple `urllib.parse.urljoin()` calls:
Appending a trailing path separator is incorrect, and checking for absolute and non-empty components is unnecessary
- Remove unused `BaseURL.is_absolute()` property
----
Fixes #6327 
As said in the linked issue, I have no idea why the weird `parts[2] += "/"` logic was added in the initial DASH implementation.
`urllib.parse.urljoin()` is IETF RFC 3986 compliant, which is what's required by ISO/IEC 23009-1:2022 5.6.4 (BaseURL processing section of the DASH standard).
----
@zhenyahacker please have a look and check if that's working for you. Thanks.
> stream.dash: refactor BaseURL.join()

- src/streamlink/plugins/bilibili.py
Resolves #6329 
The HLS stream however appears to be really slow or the connection is throttled. Their website doesn't use HLS and just progressively downloads a single FLV container. (see #5782 - still no feedback after almost a year now)
```
$ streamlink -l debug https://live.bilibili.com/32352415?hotRank=0&session_id=2f53f6b1e46116ea00151dcda767571a_7ACB95EC-467D-4EBE-94AB-EE4491304448&launch_id=1000338&live_from=77002 best
[cli][debug] OS:         Linux-6.12.1-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.13.0
[cli][debug] OpenSSL:    OpenSSL 3.4.0 22 Oct 2024
[cli][debug] Streamlink: 7.0.0+29.gcae99032
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycryptodome: …
```
> plugins.bilibili: accept MPEG-TS HLS streams

- src/streamlink/plugins/bilibili.py
- tests/plugins/test_bilibili.py
Resolves #5700 
This adds back the v1 API request and the progressive HTTP streams. Those streams have a higher quality compared to their HLS streams for some reason. The plugin therefore treats them with a higher priority, so that `--stream-types=http` doesn't have to be set (its default value is `hls,http,*`). (*This will be cleaned up eventually with the new stream selection stuff though*)
----
Getting some channel IDs from their `/all` page:
```js
>>> Array.from(document.body.querySelectorAll("a#card")).slice(0, 10).map(a=>new URL(a.href).pathname.substring(1)).join(" ")
'26807102 30048568 31602877 31561419 31142202 24660442 31773868 30844372 11484134 27768132'
```
Testing the progressive HTTP streams from the v1 API:
```bash
for channel in 26807102 30048568 31602877 31561419 31142202 …
```
> plugins.bilibili: add back HTTPStream from v1 API

- src/streamlink/stream/dash/dash.py
- tests/stream/dash/test_dash.py
- tests/stream/dash/test_manifest.py
Follow-up of 53ac068
Simply pass the whole input URL as `base_url` value, since we're always joining all URLs using `urllib.parse.urljoin()`.
Add another test case which fails on 53ac068 due to the incorrect path splitting, and update all remaining tests.
----
Fixes #6337 
Introduced by #6328
@pzhlkj6612 please check. Thanks!
> stream.dash: fix base_url input

- src/streamlink/options.py
- src/streamlink/plugin/plugin.py
- src/streamlink/session/session.py
- tests/cli/test_argparser.py
- tests/test_options.py
This makes the `options` arguments of both the `Streamlink` session class and the `Plugin` class more consistent. The former currenly doesn't allow passing an `Options` object as the `options` argument, while the latter doesn't allow `dict`s and always requires an `Options` object.
The reason for these inconsistencies is that the `Streamlink` session defines a set of default values and key-value mappings, so passing an `Options` object didn't make sense when it was implemented. The `Plugin` options argument was implemented when the `Plugin.bind()` nonsense was removed and `Plugin.options` were turned from class attributes to instance attributes (5.0.0 - #5033), so regular `dict`s were never considered as plugin options arguments.
~~A side-effect of these changes however is that plugin …
> options: make Options inherit from dict

- src/streamlink_cli/show_matchers.py
- tests/cli/main/test_show_matchers.py
Fixes #6360
```
$ cd $(mktemp -d)
$ python -m venv .
$ source ./bin/activate
$ pip install -U git+https://github.com/streamlink/streamlink.git@7.1.0 >/dev/null 2>&1
$ streamlink -V
streamlink 7.1.0
$ streamlink --show-matchers=twitch
error: Plugin not found
$ pip install -U git+https://github.com/bastimeyer/streamlink.git@cli/fix-show-matchers >/dev/null 2>&1
$ streamlink -V
streamlink 7.1.0+1.g11337165
$ streamlink --show-matchers=twitch
- name: live
pattern: https?://(?:(?!clips\.)[\w-]+\.)?twitch\.tv/(?P<channel>(?!v(?:ideos?)?/|clip/)[^/?]+)/?(?:\?|$)
- name: vod
pattern: https?://(?:[\w-]+\.)?twitch\.tv/(?:[\w-]+/)?v(?:ideos?)?/(?P<video_id>\d+)
- name: clip
pattern: https?://(?:clips\.twitch\.tv|(?:[\w-]+\.)?twitch\.tv/(?:[\w-]+/)?clip)/(?P<clip_id>[^/?]+)
- name: player
pattern: …
```
> cli: fix --show-matchers ignoring lazy plugins

- src/streamlink/plugins/abematv.py
- src/streamlink/plugins/ard_mediathek.py
- src/streamlink/plugins/bbciplayer.py
- src/streamlink/plugins/picarto.py
- src/streamlink/plugins/streann.py
Verbose plugin matcher regexes of some plugins were split into multiple simple matchers in 742988f2d57f1807bea2210a1d721c632c1d7b75.
Some regex capture group references however were not updated, resulting in `IndexError` being raised.
----
Fixes #6366 
See #6363, #6364 
Here's the list of all updated plugins in 742988f2d57f1807bea2210a1d721c632c1d7b75 and their current number of `@pluginmatcher`s, with all `self.match`/`self.matches` references (for accessing matchers and their regex capture groups). 
```
$ for file in (git show --format="" --name-only 742988f2d57f1807bea2210a1d721c632c1d7b75 -- src/); echo $file; grep -c -F '@pluginmatcher' $file; grep -F 'self.match' $file; echo; end
src/streamlink/plugins/abematv.py
3
if self.matches["onair"]:
onair = self.match["onair"]
elif …
```
> plugins: fix broken matcher capture groups

- src/streamlink/plugins/kick.py
- tests/plugins/test_kick.py
Closes #6325
See https://github.com/streamlink/streamlink/pull/6325#issuecomment-2543143217 (credits to @Hakkin)
This seems to fix the 403 response just fine, so let's add the header to the entire HTTP session when initializing the plugin. Alternatively, the header could be added by the custom `KickAdapter`, but then the adapter would also need to be mounted on other (sub-)domains where the HLS stream data is accessed from. Or it could be set on all API requests and HLSStream instances, but that would be a bit redundant and therefore unnecessary.
In addition to fixing the 403 responses, this PR also fixes the VOD URL matcher. Surprisingly though, some VODs I checked still returned 403 when accessing the HLS playlist, which made me believe that the header didn't work. Turns out that those …
> plugins.kick: fix 403 error and VOD URL matcher

- src/streamlink/plugins/twitch.py
- tests/plugins/test_twitch.py
A couple of code refactor commits.
The initial motivation for these changes was adding authentication debug log messages. But then I decided against adding this, as it's unnecessary. If the `Authorization` Twitch API HTTP header has an invalid value, acquiring an access token will fail with an error message that perfectly describes the error. No auth and valid auth data pass silently. We don't need to log this and the user's name. Doing this only bloats up the GQL access token request by also querying `VerifyEmail_CurrentUser` (the most sensible query I could find on their website) and doing additional error handling.
----
1. Refactor tests for easier test-setup of plugin options
2. Refactor logic for acquiring an access token and fix duplicate GQL requests for VOD when client-integrity …
> plugins.twitch: refactor Twitch._access_token()

- dev-requirements.txt
freezegun==1.5.0 fixes incompatibility issues with Python >=3.13, so make that the min required version
----
https://github.com/spulec/freezegun/commit/d75458f3f691d0c2c35559872716d0ebab738817
1.5.0 has been released almost a year ago on 2024-04-23, so bumping this test requirement shouldn't cause any issues for packagers
> tests: bump freezegun requirement to >=1.5.0

- src/streamlink/stream/ffmpegmux.py
Correctly log the command argument vector instead of a non-shlex concatenated command line string.
```
[stream.ffmpegmux][debug] ffmpeg command: ['/usr/bin/ffmpeg', '-y', '-nostats', '-loglevel', 'info', '-i', '/tmp/streamlinkpipe-1452919-1-6843', '-i', '/tmp/streamlinkpipe-1452919-2-7479', '-c:v', 'copy', '-c:a', 'copy', '-copyts', '-f', 'matroska', 'pipe:1']
```
> stream.ffmpegmux: fix logging format of cmd argv

- docs/install.rst
I've added secondary AppImage builds which bundle [Streamlink's FFmpeg Linux builds for both `x86_64` and `aarch64`](https://github.com/streamlink/FFmpeg-Builds):
- https://github.com/streamlink/streamlink-appimage/compare/7.1.2-1...dbfed5180690c3c0c9cd3dfc6f31285e9d0b235a
- https://github.com/streamlink/streamlink-appimage/actions/runs/12991168153
The current non-FFmpeg AppImages will be kept unless we'll see that these new ones will be preferred by users. FFmpeg is optional, and it's available on the user's distro in most cases anyway.
Apart from the file system access times, there shouldn't be an increase in loading time when using the AppImages with the bundled FFmpeg binary. The AppImage file size has grown from ~36MiB to ~83MiB (on `x86_64`).
With FFmpeg (`--ffmpeg-ffmpeg` is always …
> docs: add FFmpeg to Linux AppImages

- src/streamlink/validate/_validators.py
- tests/test_validate.py
Check for `collections.abc.Container` instances in `validate.contains()` rather than `str` objects, so everything that implements `__contains__` can be validated as well, like lists, dicts, etc.
> validate: check for Container in contains()

- src/streamlink/plugins/nos.py
- tests/plugins/test_nos.py
Fixes #6419 
@ltguillaume please check and see if any content on the site is still not working correctly with these plugin fixes. The live streams are geo-blocked for me, and the main live stream apparently is currently offline. That shouldn't be a problem though, considering that the plugin only required simple validation schema changes, and no other stream-related changes.
```
$ ./script/test-plugin-urls.py nos -m
:: https://nos.nl/collectie/13951/video/2491092-dit-was-prinsjesdag
::  360p, 480p, 720p, 1080p, worst, best
::   {'id': '2491092', 'author': None, 'category': None, 'title': 'Dit was Prinsjesdag'}
:: https://nos.nl/l/2490788
::  360p, 480p, 720p, 1080p, worst, best
::   {'id': …
```
> plugins.nos: update matcher, fix validation schema

- .github/workflows/preview-build.yml
- docs/_static/styles/custom.css
- docs/install.rst
Closes #6424 
This new `preview-build` workflow triggers the `preview-build` workflows on the `streamlink/windows-builds` and `streamlink/streamlink-appimage` repos whenever something was pushed to `master` and either `pyproject.toml`, `setup.py`, `MANIFEST.in` or `src/**` was modified:
- https://github.com/streamlink/windows-builds/actions/workflows/preview-build.yml
- https://github.com/streamlink/streamlink-appimage/actions/workflows/preview-build.yml
These two links are added to the run's summary markdown text, so users can find the build artifacts easily when clicking the workflow here. Unfortunately, direct links in the summary can't be included, as the workflow here merely triggers the workflows on the other repos. GitHub doesn't include a workflow run ID in its API response.
The …
> ci.github: add preview-build workflow

- CONTRIBUTING.md
- docs/install.rst
> docs: fix preview build references in OS tables

- src/streamlink/plugins/tf1.py
> plugins.tf1: fix help text of --tf1-password

- .github/workflows/test.yml
- docs/install.rst
- pyproject.toml
Instead of defining brotli and zstandard directly, rely on urllib3's version requirements and use its brotli and zstd extras markers.
brotli or zstandard may be required by some websites which ignore the HTTP client's decompression capabilities set in the Accept-Encoding HTTP header. Both dependencies are picked up automatically if available.
----
https://github.com/urllib3/urllib3/blob/2.3.0/pyproject.toml#L41-L48
> build: add decompress extras marker

- src/streamlink/plugins/euronews.py
- tests/plugins/test_euronews.py
Fixes #6450 
If there are any issues with embedded YouTube streams on euronews, like required logins, then there's nothing that can be done. These streams should be freely available and Google simply might block users of certain IP address ranges which they deem bots or otherwise untrustworthy.
```
$ ./script/test-plugin-urls.py euronews
:: https://arabic.euronews.com/live
::  worst, best, 144p, 240p, 360p, 480p, 720p
:: https://de.euronews.com/live
::  worst, best, 144p, 240p, 360p, 480p, 720p
:: https://de.euronews.com/my-europe/2025/02/24/frankreichs-prasident-macron-wird-trump-treffen
::  vod, worst, best
:: https://es.euronews.com/live
::  worst, best, 144p, 240p, 360p, 480p, 720p
:: https://euronews.com/live
::  worst, best, 144p, 240p, 360p, 480p, 720p
:: …
```
> plugins.euronews: rewrite and fix plugin

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/main/test_handle_url.py
- Don't retry fetching streams if `--retry-streams` and `--retry-max` are both set to zero. This was previously only possible if both were unset.
- Update CLI argument help texts accordingly
- Fix `FatalPluginError` not being handled properly on first try
- Add tests for `fetch_streams_with_retry()`
----
Resolves #6454 
Any comprehension issues with the updated help texts? They should be fine now IMO.
https://streamlink--6455.org.readthedocs.build/cli.html#cmdoption-retry-streams
> cli: allow --retry-streams to be set to 0

- src/streamlink/logger.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/console.py
- src/streamlink_cli/main.py
- tests/cli/main/test_check_file_output.py
- tests/cli/main/test_logging.py
- tests/cli/test_argparser.py
- tests/cli/test_console.py
- tests/test_logger.py
- tests/test_plugin_userinput.py
Replaces #6457
In preparation for #6449
This PR fixes a couple of console output issues and logger setup issues, and also splits the console output into two streams. The separation of console output streams is necessary in order for the download progress to be fixed later on. Progress output should never be written to a file, but since we want some console output to be written to log files as well, especially error messages, we need to use two streams.
Currently on master, the `ConsoleOutput` always inherits the stream of Streamlink's root logger. This is problematic because `--logfile=...` sets the logger stream to a file, which means all `ConsoleOutput` including user prompts are written to the log file instead of being written to a TTY where the user has to write their input.
Also, …
> cli.console: refactor and split into two streams

- src/streamlink/plugins/nicolive.py
Fixes #6440 
@cykac04 please have a look at this PR...
After browsing lots of streams, I was finally able to find one live stream where cookies were required. The one you posted was offline unfortunately.
HLS streams where cookies are required all appear to be multivariant streams with an external audio stream, so muxing via FFmpeg is required. I'm not sure, but I think there's an issue with the audio stream synchronization. That is unrelated to the plugin however, as it has nothing to do with the HLS protocol or the stream data. It may be an issue with the stream itself, because audio synchronization depends on the individual bitstreams and their presentation timestamps, not on the HLS metadata …
> plugins.nicolive: set stream cookies from WS data

- src/streamlink_cli/main.py
- tests/cli/main/test_handle_url.py
Plugin constructors can sometimes print log messages. The "plugin found" CLI log message should therefore be printed before initializing the plugin.
> cli: log plugin found message early

- CHANGELOG.md
Release date is set to tomorrow, but I'm not sure if I want to publish 7.2.0 tomorrow just yet...
I've been working on #6449 which I'd like to include, as it's related to the console output stream changes, but it's still unfinished and there's still lots to do...
https://streamlink--6475.org.readthedocs.build/changelog.html
> release: 7.2.0

- src/streamlink_cli/console/console.py
- src/streamlink_cli/console/progress.py
- src/streamlink_cli/console/stream.py
- src/streamlink_cli/console/windows.py
- src/streamlink_cli/constants.py
- src/streamlink_cli/main.py
- src/streamlink_cli/streamrunner.py
- tests/cli/console/test_console.py
- tests/cli/console/test_progress.py
- tests/cli/console/test_stream.py
- tests/cli/console/test_stream_wrapper.py
- tests/cli/console/test_windows.py
- tests/cli/main/conftest.py
- tests/cli/main/test_output_stream.py
- tests/cli/test_streamrunner.py
Resolves #6449
~~These are unfinished changes... The implementation works and should mostly be fine, apart from stuff that may come up while finishing and cleaning this up. Most tests however still need to be done (the CI status checks will therefore currently fail, tests and typing stuff). I still decided to open this PR, because this helps me finding potential issues.~~
~~The PR branch is currently based on #6496, because this branch hasn't been merged yet. Once merged, I'm going to rebase here.~~
----
1. Implement status messages on the console output via `ConsoleOutput.msg_status()`
- Add base line-buffered `ConsoleOutputStream(StreamWrapper)` without status message support
- Add `ConsoleOutputStreamANSI` with status message support via ANSI control sequences
- Check for available …
> cli.console: implement status messages

- src/streamlink/plugins/twitcasting.py
Suppress HLS multivariant errors if websocket streams are available
----
Closes #6503
> plugins.twitcasting: suppress HLS errors

- pyproject.toml
PEP 639 support was added in setuptools 77 (2025-03-19):
- https://peps.python.org/pep-0639/#goals
- https://setuptools.pypa.io/en/latest/history.html#v77-0-0
This deprecates the `project.license` table in favor of a standardized SPDX license string, as well as the temporary setuptools-specific `tools.setuptools.license-files` table in favor of `project.license-files`.
`tools.setuptools.license-files` and `project.license-files` can't be set at the same time. ~~Considering that setuptools 77 was only released in March, we should wait a bit more before switching the metadata format, as recent enough setuptools versions might not be packaged yet on all Linux distros where we have recent Streamlink releases packaged.~~
```
$ pip install .
...
$ grep -E '^License' …
```
> build: switch to PEP 639 license metadata

- docs/developing.rst
This small PR resolves the linter/formatter references found at: https://streamlink.github.io/latest/developing.html
> docs: resolve linter/formatter references

- src/streamlink/stream/dash/dash.py
- src/streamlink/stream/dash/manifest.py
- tests/resources/dash/test_period_selection.mpd
- tests/stream/dash/test_dash.py
Ref https://github.com/streamlink/streamlink/issues/5058#issuecomment-2843678464
A `LookupError` should not be raised when selecting a specific DASH period. Instead, raise a `PluginError` with a better error message.
This PR also adds support for selecting DASH periods by their `id` attribute, which is an optional value. This requires quotation when using the DASH plugin (`streamlink 'dash://URL period="ID"'`), as it's parsing Python literals, and IDs are string values. Probably not ideal that Streamlink doesn't log what's available, but that's not the goal of this PR.
Example on a random DASH stream from steamcommunity.com:
IndexError/LookupError (master):
```
$ streamlink 'dash://https://cache11-ams1.steamcontent.com/broadcast/76561198074710428/5461257622813668676/manifest/0/cache11-ams1 …
```
> stream.dash: fix LookupError on period selection

- src/streamlink/stream/dash/dash.py
- tests/resources/dash/test_period_selection.mpd
- tests/stream/dash/test_dash.py
Follow-up of #6518 
Let's log the available DASH periods, so they can easily be selected when using the DASH plugin (`dash://URL period=...`).
The log message doesn't make much sense for regular plugins returning `DASHStream`s, as the user doesn't control which period is being used. But since it's just a debug message, that should be fine...
> stream.dash: log available periods

- tests/resources/__init__.py
- tests/test_compat.py
Python 3.14 beta 1 has been released two days ago. This fixes the failing tests due to some newly added deprecation warnings.
Runners can't be added yet despite GH having added py314 to their runners, because we'll need to build missing wheels for some dependencies first, which are currently missing. This is unrelated to this PR.
> tests: fix py314 issues

- .github/workflows/test.yml
- dev-requirements.txt
This currently installs custom-built wheels from our `temp-dependency-builds-DO-NOT-USE` repo, so they don't have to be built on each test run here, wasting time. Those deps are `lxml`, `brotli` and `zstandard`. The other binary deps should all have matching wheels.
Streamlink's dev-requirements adds the `faster-cache` marker for `mypy`, which tries to install `orjson`. This build currently fails, hence why the marker has been temporarily disabled, not just for the CI runner.
On Windows, there were lots of build issues with pretty much everything, on top of the setup of the Python 3.14-dev build taking one and a half minute, which is quite ridiculous. So only the Linux test runner for now.
> ci.github: add py314 Linux runner

- docs/install.rst
- https://packages.msys2.org/base/mingw-w64-streamlink
- https://www.msys2.org/
- https://www.msys2.org/docs/package-management/
- https://www.msys2.org/docs/environments/
```
$ pacman -Syu
...
$ pacman -S mingw-w64-x86_64-streamlink
...
$ /mingw64/bin/streamlink -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.10
[cli][debug] OpenSSL:    OpenSSL 3.5.0 8 Apr 2025
[cli][debug] Streamlink: 7.3.0
[cli][debug]  certifi: 2025.4.26
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.4.0
[cli][debug]  pycryptodome: 3.22.0
[cli][debug]  trio: 0.30.0
[cli][debug]  trio-websocket: 0.12.2
[cli][debug]  urllib3: 2.4.0
[cli][debug]  websocket-client: 1.8.0 …
```
> docs: add MSYS2 to packages list

- docs/install.rst
It doesn't make sense listing package maintainers in Streamlink's docs. Most data is either outdated or wrong, e.g. when there's not a single responsible package maintainer. We also shouldn't publish email addresses like this.
Actual package maintainer data can always be found on the linked package URLs.
> docs: remove package maintainers list

- tests/test_validate.py
Some error messages have been changed on lxml's master branch which cause our validation schema tests to fail. These error message changes will be part of lxml's next major release, version 6.x, which is still alpha. Even though we currently limit the upper version to 5, we can already update the failing tests.
> tests: update lxml validation error messages

- src/streamlink/plugins/blasttv.py
- tests/plugins/test_blasttv.py
Blast is a video game (mainly Counter-Strike) tournament organizer who streams their matches on their website alongside the usual Twitch and YouTube. The streams on blast.tv are usually in 4K as opposed to 1080p on other platforms.
I've been using this plugin locally for a couple years. Over time, I've  recorded different API (`https://api.blast.tv/v1/broadcasts/live`) responses in comments in the plugin code to make development and testing easier, but I'm happy to move those to a more appropriate place.
There are some caveats:
- Streams don't run 24/7--they'll only run, idk, 8-12 hours a day, 10 weeks a year, which I imagine would be annoying for reviewers. I'm creating the PR now because there should be regular daytime CST streams from now through June 22.
- The stream used to …
> plugins.blasttv: new plugin

- src/streamlink/plugins/twitch.py
- src/streamlink/stream/dash/dash.py
- src/streamlink/stream/hls/hls.py
- src/streamlink/stream/segmented/segmented.py
- src/streamlink/utils/thread.py
- tests/conftest.py
- tests/stream/dash/test_dash.py
- tests/stream/hls/test_hls.py
- tests/utils/test_thread.py
- Add `NamedThread` class that automatically sets its name from its class name, with an optional suffix, and with a unique counter
- Make `SegmentedStreamWriter` and `SegmentedStreamWorker` subclass from `NamedThread` and pass through the optional `name` suffix
- Make `SegmentedStreamReader` and its subclasses (HLS and DASH) set the optional name suffix for its writer and worker threads, and fix signature of the Twitch plugin's subclass
- Add `name` argument to `HLSStream`, so it can be passed to its reader
- Make `MuxedHLSStream` set the "audio" suffix for all audio substreams
- Add and update existing tests accordingly
----
https://github.com/streamlink/streamlink/issues/6550#issuecomment-2957280081
After this has been merged, I will add the thread name to the default logformat for the …
> stream: set specific names for each thread

- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py
- tests/cli/main/test_logging.py
Follow-up of #6556 
```
$ streamlink -l trace
[20:43:49.001245][MainThread][cli][debug] OS:         Linux-6.14.10-1-git-x86_64-with-glibc2.41
[20:43:49.001380][MainThread][cli][debug] Python:     3.13.3
[20:43:49.001438][MainThread][cli][debug] OpenSSL:    OpenSSL 3.5.0 8 Apr 2025
[20:43:49.001482][MainThread][cli][debug] Streamlink: 7.4.0+6.g4dd62f2d
[20:43:49.001523][MainThread][cli][debug] Dependencies:
[20:43:49.002676][MainThread][cli][debug]  certifi: 2025.4.26
[20:43:49.003257][MainThread][cli][debug]  isodate: 0.7.2
[20:43:49.003561][MainThread][cli][debug]  lxml: 5.4.0
[20:43:49.003972][MainThread][cli][debug]  pycountry: 24.6.1
[20:43:49.004225][MainThread][cli][debug]  pycryptodome: 3.23.0
[20:43:49.004557][MainThread][cli][debug]  PySocks: 1.7.1 …
```
> cli: add thread name to trace logging format

- .github/workflows/test.yml
The `3.14.0b2` runner has stopped working two days ago:
https://github.com/streamlink/streamlink/actions/runs/15646409717/job/44084622309#step:7:1
No idea what this is about, but pytest stalls for over an hour and then the job gets cancelled. I can't reproduce this on my local machine with the same Python version. This must be something on GitHub's end with their Python builds, so let's just disable the runner for now. Our tests were passing before this issue came up.
> ci.github: temporarily disable py314 Linux runner

- src/streamlink/plugins/aloula.py
- tests/plugins/test_aloula.py
Fixes #6571 
```
$ ./script/test-plugin-urls.py aloula
:: https://aloula.sba.sa/en/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://aloula.sba.sa/en/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://aloula.sba.sa/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://aloula.sba.sa/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://www.aloula.sa/en/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://www.aloula.sa/en/live/saudiatv
::  360p, 480p, 1080p, worst, best
:: https://www.aloula.sa/episode/6676
::  240p, 360p, 480p, 720p, 1080p, worst, best
:: https://www.aloula.sa/live/saudiatv
::  360p, 480p, 1080p, worst, best
```
> plugins.aloula: add aloula.sba.sa to URL matcher

- src/streamlink/plugins/goodgame.py
- tests/plugins/test_goodgame.py
Fixes #6584
HLS playlist URLs are now returned by the API, and they now require an access token that's already included in the query strings.
```
$ ./script/test-plugin-urls.py goodgame -r USERNAME bonivur -r CHANNELNAME boni
:: https://goodgame.ru/bonivur
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/bonivur/
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/bonivur?foo=bar
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/channel/boni
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/channel/boni/
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/channel/boni?foo=bar
::  240p, 480p, 720p, source, worst, best
:: https://goodgame.ru/player?boni
::  240p, 480p, 720p, source, worst, best
:: …
```
> plugins.goodgame: fix plugin

- tests/test_cache.py
Tiny oversight by me in #6568 
Tests consistently failed on freethreading builds. I'll add runners for this now that lxml 6.0.0 supports freethreading.
> tests: fix cache atomicity test

- src/streamlink/plugins/lrt.py
Resolves #6606 
Stream URLs + metadata are now embedded as DOM rehydration data. The follow-up API request is still the same.
```
$ ./script/test-plugin-urls.py -m lrt
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-klasika
::  540p, 720p, 1080p, worst, best
::   {'id': 'Klasika', 'author': None, 'category': None, 'title': 'Radijo teatras'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica
::  540p, 720p, 1080p, worst, best
::   {'id': 'WORLD', 'author': None, 'category': None, 'title': 'Savaitė su „Dviračio žiniomis“'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-opus
::  540p, 720p, 1080p, worst, best
::   {'id': 'Opus', 'author': None, 'category': None, 'title': 'Vakarų musonas'}
:: https://www.lrt.lt/mediateka/tiesiogiai/lrt-plius
::  540p, 720p, 1080p, worst, best
::   {'id': …
```
> plugins.lrt: rewrite and fix stream URL schema

- pyproject.toml
The recent issues with `orjson` have been fixed. It should now be working on 3.14, 3.14t and 3.13t, so let's add it back to the `typing` dependency group via mypy's `faster-cache` extra.
https://github.com/ijl/orjson/releases/tag/3.11.0
Removed in #6592 (from dev-requirements.txt)
> tools: add back faster-cache mypy extra

- pyproject.toml
Let's update Streamlink's package metadata now that Python 3.14 RC1 has been tagged and everything's working fine. The CI runners haven't received updated builds yet, but I've built and check everything locally, so tagging full 3.14 compatibility with the first release candidate is fine.
Once 3.14.0 final has been released, we can move the CI runners to the default test matrix.
> build: add Python 3.14 to package classifiers

- docs/ext_argparse.py
- docs/ext_plugins.py
- Switch from `nodes.section` to `node.Element`
- Replace `ViewList` with `StringList` for typing reasons
- Clean up `{Argparse,Plugins}Directive.run()`:
- Set `document` attribute directly
- Don't repeatedly `append()` to the `StringList` object
----
Resolves #6624 
See https://github.com/streamlink/streamlink/issues/6624#issuecomment-3145870992
> docs: fix compatibility with docutils==0.22

- src/streamlink_cli/main.py
- tests/cli/main/test_logging.py
Let's not call `sys.exit()` or `parser.error()`, and instead raise an exception for better static code analysis.
> cli: replace sys.exit() and parser.error() calls

- src/streamlink/plugins/mediaklikk.py
- tests/plugins/test_mediaklikk.py
Fixes #6626
The sports channels are all geo-blocked, so I don't know if they're actually working. What I'm seeing is a template stream with a geo-block message.
```
$ ./script/test-plugin-urls.py mediaklikk
:: https://hirado.hu/belfold/video/2025/08/09/szuletesnap-a-budapesti-allat-es-novenykertben
::  400k, 800k, 1200k, 1600k, 3000k, worst, best
:: https://hirado.hu/elo/m1
::  240p, 360p, 480p, 540p, 720p, 1080p, worst, best
:: https://hirado.hu/elo/m2
::  240p, 360p, 480p, 540p, 720p, 1080p, worst, best
:: https://m4sport.hu/elo/
::  240p, 360p, 480p, 540p, 720p, 1080p, worst, best
:: https://m4sport.hu/elo/?channelId=m4sport+
::  240p, 360p, 480p, 540p, 720p, 1080p, worst, best
:: https://m4sport.hu/elo/?showchannel=mtv4plus
::  240p, 360p, 480p, 540p, 720p, 1080p, worst, best
:: …
```
> plugins.mediaklikk: fix player data regex

- src/streamlink/plugins/vkvideolive.py
See https://github.com/streamlink/streamlink/issues/6639#issuecomment-3229531225
```bash
url=https://live.vkvideo.ru/funny/record/e385402f-26d0-4331-a2bd-3dd89a97ca9a?tab=records
for quality in $(streamlink --json "$url" | jq -r '.streams | keys[]'); do
echo $quality
streamlink --quiet --stdout "$url" "$quality" \
| ffprobe -v error -of json -show_streams - \
| jq -r '.streams[] | select(.codec_type == "video") | "\(.width)x\(.height)"'
done
```
```
best
2560x1440
full_hd
1920x1080
high
1280x720
low
640x360
medium
852x480
quad_hd
2560x1440
worst
640x360
```
> plugins.vkvideolive: add missing VOD qualities
