streamlink/streamlink

.travis.yml
Add in some Python releases for Travis and clean a few things up, more modifications are needed.
=> Add some python releases

.gitignore, tox.ini
Reverts streamlink/streamlink#10
=> Revert "add py35 to tox"

script/release.sh
This is a script I use in order to release something on Github as well
as push onto Pypi. I use this with a similar project called "kubeshift".
This release script will automatically process things such as renaming
the versioning, creating changelogs as well as uploading to Pypi.
After this is merged, we'll go ahead and do our first release of
Streamlink!
=> Add release script

setup.py
Changing the authors / email / clean-up a bit of the formatting.
Got to set it to "0.0.1". I'll be creating a script ready for a release
/ access to pypi.
=> Get setup.py ready for a release.

README.md
Yay 0.0.1 release! Streamlink is now on Pypi.
=> Update the README with installation notes

docs/plugin_matrix.rst
=> Add streamboat to the docs

.travis.yml
=> Remove faraday from travis run

docs/_themes/sphinx_rtd_theme_violet/LICENSE, docs/conf.py, src/streamlink/__init__.py
=> Update copyright author

.coveragerc, .travis.yml
This will (hopefully) work now that we aren't having a tox conflict.
=> Add a coverage file

docs/issues.rst
Let me know if you'd like anything changed.
=> [Docs] Fix a typo in issues and improve wording

docs/install.rst
Fixed #63.
Only instances of the problem seemed to be in install.rst
=> Fix instances of chrippa/streamlink to streamlink/streamlink in docs

docs/plugin_matrix.rst, src/streamlink/plugins/tvplayer.py
A fix for the TVPlayer.com plugin, hasn't worked for a while and this supports the new page layout and API.
=> TVPlayer plugin supports the latest version of the website

src/streamlink/plugins/itvplayer.py
The page layout had changed, this updates the productionId extraction method to support the new page layout.
=> itvplayer: updated the productionId extraction method

src/streamlink/plugins/crunchyroll.py
This fixes #70. If the API returns an adaptive quality stream this is an HLS variant playlist that contains a superset of the other streams listed - in some cases it includes higher quality streams. If there is no adaptive quality stream then we fall back to handling each of the other streams. There are two types of streams - plain HLSStreams and HLS variant playlists. These can be identified by the presences of a `video_encode_id` which indicates that the stream is a plain old HLS stream, otherwise it is a variant playlist.
=> crunchyroll: decide if the stream is a variant playlist or not

src/streamlink/plugins/connectcast.py
Connectcast.tv seems to have switched to RTMP streams. I have updated the plugin to reflect this.
=> Updated connectcast plugin to support RTMP streams

win32/streamlinkrc
Changed "livestreamer" to "streamlink" in streamlinkrc file
=> fixed instance of livestreamer

docs/cli.rst
Just a note regarding https://github.com/streamlink/streamlink/issues/81 in the docs so people aren't too confused.
=> Update cli to note a few windows issues

src/streamlink/plugins/twitch.py
=> Changed the twitch plugin to use https instead of http

src/streamlink_cli/argparser.py, src/streamlink_cli/main.py
Any thoughts on the wording? I'm not particularly creative
=> remove run-as-root option, reworded warning

src/streamlink/plugins/piczel.py
Thank you to github user @intact all credit goes to him
fixes #112
=> Add piczel.tv plugin (courtesy of @intact)

src/streamlink/plugins/goodgame.py
Patch to fix the goodgame.ru plugin courtesy of @intact, fixes #128
=> Fix for goodgame.ru plugin

src/streamlink/plugins/younow.py
Fixes #127 with the suggested change by @stevek123.
=> plugins.younow: update API url

src/streamlink/plugins/euronews.py
This fixes #140 as reported by @karlo2105.
=> plugins.euronew: update to support the new site

docs/plugin_matrix.rst, src/streamlink/plugins/webtv.py, tests/test_plugin_webtv.py
A new plugin to support web.tv, as requested by @Rotarum in #142
=> plugins.webtv: added a new plugin to support web.tv

src/streamlink/plugins/connectcast.py
Fixes #151 ... missed this one...
=> plugins.connectcast: fix regex issue with python 3

src/streamlink/plugins/euronews.py, src/streamlink/plugins/zdf_mediathek.py
The ZDF mediathek plugin needed to be changed for the new version of the site. Resolves #138
=> Overworked Plugin for ZDF Mediathek

script/makeinstaller.sh, script/release.sh
Update the release script to include Windows binary generation as well.
=> Update release scripts

script/release.sh
Encountered this minor issue in the release script. :) Damn capitals.
=> Spelling error in release script

src/streamlink/plugins/nhkworld.py
This should fix #192, the plugin now uses the new HLS streams.
=> plugins.nhkworld: update the plugin to use the new HLS streams

src/streamlink/plugins/picarto.py
Some streams are available as HLS, which is now supported. Now gives a warning when the stream is offline. 
Fixes #199
=> plugins.picarto: updated the plugin to use the new javascript

docs/plugin_matrix.rst, src/streamlink/plugins/nineanime.py
This PR adds support for the site 9anime.to as requested by @Victolabs in #202 :)
=> Add support for 9anime.to

docs/players.rst
A small update to the player docs from #152 :)
=> More updates to the player docs about OMXPlayer

CONTRIBUTING.md, docs/players.rst
This is a PR to create [contributing guidelines](https://github.com/blog/1184-contributing-guidelines), one of the main things I want is to keep a list of known issues in there so that we don't get bugs out of our control reported over and over again. If you guys think of other known issues please let me know and I'll add it to this PR.
=> Contributing guidelines

docs/install.rst
Updated the install docs to reflect the reality of installing `pycryptodome` automatically
=> Small update to the install docs

docs/plugin_matrix.rst, src/streamlink/plugins/tigerdile.py
Credit to skulblakka for original implementation in livestreamer. See: https://github.com/skulblakka/livestreamer/commit/ec9ff879d06dd7db089a22234202a0f48daf9970
=> Added tigerdile.com support.

src/streamlink/plugins/twitch.py
Fixes https://github.com/streamlink/streamlink/issues/190
=> Update client ID

src/streamlink/plugins/crunchyroll.py
Missed this last time, didn't test the subscriber streams. 
Should resolve #243, also renames the streams from bitrate to low, mid, high so that all the names are consistent :)
=> plugins.crunchyroll: support ultra quality for subscribers

src/streamlink/stream/hls.py
As pointed out in #166, HLS streams do not start playing right away. 
Instead of waiting for the full segment to be downloaded, start writing out the segments as they are downloaded. This will improve the delay starting HLS streams and the delay from "live" in live streams.
=> Start playing HLS Streams as soon as any data has been download

README.md
Fixed typo in README.md caught by Vangelis66
=> Fixed typo in README.md.

src/streamlink/plugins/twitch.py
This PR adds clips support to the Twitch plugin.
e.g.:
https://clips.twitch.tv/basetradetv/BeautifulDuckOpieOP
=> plugins.twitch: support for clips added

src/streamlink/plugins/bigo.py
Should fix the issues reported in #234. The site was updated and the FlashVars were changed.
=> Updated bigo plugin to support site changes

NOTICE, script/makeinstaller.sh, win32/LICENSE.txt
I compiled some license notices to keep us a bit more legit :)
=> License notices for bundled libraries/software 

src/streamlink/plugins/youtube.py
As reported in chrippa/livestreamer/issues/1541, there are some additional URL formats for live streams. 
This PR adds support for this style of URL:
- https://www.youtube.com/c/FRANCE24English/live
- https://www.youtube.com/c/FRANCE24/live
- https://www.youtube.com/embed/live_stream?channel=UCQfwfsi5VrQ8yKZ-UWmAEFg
=> plugins.youtube: support additional live urls

docs/plugin_matrix.rst, src/streamlink/plugins/foxtr.py, src/streamlink/plugins/kralmuzik.py, src/streamlink/plugins/showtv.py, src/streamlink/plugins/startv.py, src/streamlink/plugins/tv8.py
As requested by @Rotarum in #210, #211, and #212.
=> Add support for a few Turkish live streams

docs/plugin_matrix.rst, src/streamlink/plugins/trt.py
Adds support for live streams on http://www.trt.net.tr.
=> Support for the live channels on trt.net.tr

README.md, docs/install.rst
=> Add links for windows portable version.

docs/plugin_matrix.rst, src/streamlink/plugins/atresplayer.py
=> plugins.atresplayer: add support for live streams on atresplayer.com

docs/plugin_matrix.rst, src/streamlink/plugins/kanal7.py, src/streamlink/plugins/powerapp.py, src/streamlink/plugins/tv360.py
Support for these sites:
- powerapp.com.tr
- tv360.com.tr
- kanal7.com
=> Turkish Streams IV

docs/plugin_matrix.rst, src/streamlink/plugins/ine.py
As requested in chrippa/livestreamer/issues/1552.
=> plugins.ine: added support for INE videos

appveyor.yml
Get code coverage for Windows tests.
=> appveyor: add codecov support

src/streamlink/plugins/tvcatchup.py
The site layout changed slightly and the stream regex needed to be updated. This fixes #318 :)
=> plugins.tvcatchup: fix for site change

src/streamlink/plugins/picarto.py
This PR fixes the issue reported in #288.
=> plugins.picarto: Remove the unreliable rtmp stream

.coveragerc, .gitignore, src/streamlink/plugins/atresplayer.py, src/streamlink/plugins/ine.py, src/streamlink/plugins/tvplayer.py, src/streamlink/utils.py, tests/plugins/testplugin.py, tests/test_buffer.py, tests/test_cache.py, tests/test_cli_main.py, tests/test_cmdline.py, tests/test_hls_playlist.py, tests/test_plugin_tvplayer.py, tests/test_plugins.py, tests/test_streamlink_api.py, tests/test_utils.py
Added some tests for a few things. Including one meta test that loads each of the plugins to ensure that there are no syntax errors :)
=> Boost the test coverage a bit

tests/test_cmdline.py
=> tests: use mock from unittest when available otherwise fallback to mock

src/streamlink/stream/hls.py
This PR fixes the issue reported in #332. I did some tests which seemed to work, unplugged the network cable and set a really low timeout, the stream recovered correctly.
=> stream.hls: retry stream segments

docs/plugin_matrix.rst, src/streamlink/plugins/huajiao.py, src/streamlink/plugins/zhanqi.py
plugin for zhanti.tv from https://github.com/steven7851/livestreamer/blob/patch-3/src/livestreamer/plugins/zhanqi.py
=> Add plugin for huajiao.com and zhanqi.tv

docs/plugin_matrix.rst, src/streamlink/plugins/pluzz.py, tests/test_plugin_pluzz.py
This plugin adds support for the French public TV video platform Pluzz. It supports both VOD and live streams. Some streams may be geo-locked to France. The platform currently provides HDS, HLS and DASH streams.
Some URLs for testing:
* live
* http://pluzz.francetv.fr/france2 (may be geo-locked at some hours)
* http://pluzz.francetv.fr/franceinfo (not geo-locked)
* VOD
* http://pluzz.francetv.fr/videos/jt_1920.html (not geo-locked)
* http://pluzz.francetv.fr/videos/sherlock.html (geo-locked)
* any video on http://pluzz.francetv.fr/depuis-l-etranger/france3 (not geo-locked)
I have anyway some issues when selecting HDS streams with this plugin: I currently can't tell if it's related to my plugin implementation or to streamlink:
* No sound when trying to play HDS version with this URL (HLS …
=> Add support for pluzz.francetv.fr

docs/plugin_matrix.rst, src/streamlink/plugins/bongacams.py
This adds support for desktop (rtmp) streams on bongacams.com
=> Added support for bongacams.com streams

docs/install.rst
Opted for just adding a row in the Other platforms instead of putting a separate subheading under Windows binaries.
=> added chocolatey to the documentation

src/streamlink/plugins/artetv.py, tests/test_plugin_artetv.py
* Fixes https://github.com/chrippa/livestreamer/issues/1281 due to site changes
* Add support for HDS streams
* Add tests
=> Fix ArteTV plugin

docs/plugin_matrix.rst, src/streamlink/plugins/tv8cat.py, tests/test_plugin_tv8cat.py
Adds support for http://tv8.cat/directe
=> plugins.tv8cat: added support for tv8.cat live stream

tests/test_plugin_streamme.py
I don't know if this is useful or if my test cases are useful, so any feedback is welcomed.
=> Add basic tests for stream.me plugin

src/streamlink/plugins/ssh101.py
Dunno if there are many streams left on this site, but I have updated the plugin to support any that are left.
=> Update to support new SSH101.com site layout

script/makeinstaller.sh
=> windows-installer: add the version info to the installer file

MANIFEST.in
Two minutes after merging #328 I notice this.. D'oh
=> include CHANGELOG.rst instead of .md in the egg

src/streamlink/plugins/twitch.py
A reported in #432 by @GreyAsteroid (cool avatar btw). 
This PR changes the `_get_hls_streams` so that it only checks for hosted channels when playing a live stream, and ignores hosted channels when playing VOD.
=> plugins.twitch: only check hosted channels when playing a live stream

src/streamlink/plugins/rtve.py
=> plugins.rtve: add support for legacy stream URLs

src/streamlink_cli/main.py
One more attempt to resolve #337
=> streamlink_cli.main: close stream_fd on exit

src/streamlink/plugins/adultswim.py
Fixes the remaining issue with adult swim VOD support.
=> plugins.adultswim: correct behaviour for archived streams

src/streamlink_cli/output.py
Only `kill` the player process if the process fails to stop from a `terminate` (after a timeout of 10 seconds). 
On Windows `terminate` is the same as `kill`.
Fixes #276
=> cli: try to terminate the player process before killing it

src/streamlink/plugins/chaturbate.py
Since yesterday Chaturbate seems to have a new way of setting the .m3u8 playlist for their player.
=> plugins.chaturbate: new regex

src/streamlink/plugins/pluzz.py
HLS streams on pluzz.francetv.fr now require token generation, as for HDS streams.
=> plugins.pluzz: fix HLS streams

src/streamlink/plugins/livecodingtv.py
=> Update livecodingtv plugin to support the new domain: liveedu.tv

src/streamlink/plugins/srgssr.py
Fixes the final issues with the SRGSSR plugin.
=> plugins.srgssr: fix playlist reload auth issue

src/streamlink/plugins/turkuvaz.py
Small bug fix for the turkuvaz plugin.
=> plugins.turkuvaz: add referer to the secure token request

script/makeinstaller.sh
=> installer: include the missing pkg_resources package

src/streamlink/plugins/pluzz.py
This PR improved the Pluzz plugin:
* DRM-protected streams are ignored (for example: http://pluzz.francetv.fr/videos/castle_20h35_,152224484.html)
* print log messages when no stream is available (geo-restricted content, DRM, expired content...).
=> plugins.pluzz: ignore DRM-protected streams + log messages

docs/plugin_matrix.rst, src/streamlink/plugins/dogus.py, src/streamlink/utils/__init__.py, tests/test_utils.py
Fixed support for the ntv.com.tr live stream and added support for eurostartv.com.tr/canli-izle.
=> Fixes and additions to the dogus plugin

src/streamlink/plugins/twitch.py
The main change from v3 was to look up the channel ID, the user endpoint is used to find the channel ID instead of the channel endpoint (thanks @bastimeyer). 
I grouped the functions in to private/public/unused so that it's easier to tell which ones need to work. I also added some warnings to the unused/unsupported methods in case anyone is importing them (unlikely, I know). 
As discussed in #377.
=> plugins.twitch: update public API calls to use v5 API

src/streamlink/plugins/filmon.py
The FilmOn API has been updated for live and VOD streams. 
Example URLs:
- filmon.com/channel/bbc-one
- filmon.com/tv/channel-4
- filmon.com/vod/view/229376-0-things-to-come
- filmon.com/vod/view/229388-0-trouble-bound
- filmon.tv/group/feature-movie (previously unsupported?)
I couldn't see any more URLs that exist on the site. 
This fixes #507
=> plugins.filmon: updated plugin to match changes made to the filmon site

docs/plugin_matrix.rst, src/streamlink/plugins/ceskatelevize.py, src/streamlink/plugins/czech_tv.py, src/streamlink_cli/console.py
As per the request in #518, originally copied from chrippa/livestreamer/pull/1508, renamed the plugin and added some better geoblocked error notification.
=> Support for Ceskatelevize streams

src/streamlink/plugins/douyutv.py
from https://github.com/soimort/you-get/issues/1657
=> plugins.douyutv: fix room id regex

docs/plugin_matrix.rst, src/streamlink/plugins/huya.py
Add support for HLS stream for Huya.com from issue #425
=> Add support for Huya.com in issue #425

docs/plugin_matrix.rst, src/streamlink/plugins/rtvs.py
As requested and discussed in #519, courtesy of @intact :)
=> Add Rtvs.sk Plugin

CHANGELOG.rst
Fixes the amount of dashes under the title for the changelog
=> Fix the CHANGELOG.rst

script/release.sh
Closes https://github.com/streamlink/streamlink/issues/527
=> Fix underlining issue

script/release.sh
Another update to the release script to include sdist
upload instead of that 50MB binary :)
=> Update release script again to include sdist

.travis.yml, appveyor.yml, src/streamlink/utils/l10n.py, tests/test_localization.py, tests/test_localization_pycountry.py
Added `Country` and `Language` classes. Optionally use `pycountry` if `iso639` or `iso3166` are not available.
=> Localization enhancements 

src/streamlink/plugins/openrectv.py
Added `source` quality to the `OPENRECtv` plugin, as requested in #541 :)
=> plugins.openrectv: add source quality for openrectv

src/streamlink/plugins/huomao.py
**Adding plugin to play video sources from huomao.tv / huomao.com.**
I could not find any documentation for developing plugins for Streamlink so winged it a bit (a lot) and used some of the other plugins as inspiration. Let me know if something needs to be changed. Also; Python isn't my strongest side, so let me know if something seems completely bananas.
=> plugins.huomao: Adding plugin for Huomao

CHANGELOG.rst, setup.py, src/streamlink/__init__.py
=> 0.3.2 Release

script/release.sh
Update the release script again since I forgot to remove the underscores
for dashes..
=> Update underscores title release script

src/streamlink/plugins/openrectv.py
Seems to have been broken for a while ... 
Example URLs can be found on openrec.tv/movielist:
- openrec.tv/movie/vzvMwVqMSv0
=> plugins.openrectv: fixed broken vod support

src/streamlink/plugins/media_ccc_de.py, src/streamlink/plugins/orf_tvthek.py
A couple more not-raw string escape sequence deprecation warnings removed :)
=> Remove deprecation warning for invalid escape sequences

src/streamlink/plugins/ard_mediathek.py
The "smil" stream endpoint was changed in someway, probably "akamai" was removed from the stream URL, causing the HDS streams to not be recognised as akamai streams. This patch checks the cdn value returned in the smil stream info and sets the akamai flag for HDSStreams
appropriately. 
Fixes #576 :)
=> plugins.ard_mediathek: update to support site change

src/streamlink/plugins/connectcast.py
=> plugins.connectcast: API changes

docs/plugin_matrix.rst, src/streamlink/plugins/huomao.py, tests/test_plugin_huomao.py
Adding tests to the Huomao plugin as mentioned in PR #517.
=> Huomao plugin tests

docs/plugin_matrix.rst, src/streamlink/plugins/app17.py
=> Add plugin for 17app.co

setup.py
See discussion on #567. Paging @mmetak.
=> setup: choose pycountry as a dependency using an environment variable

docs/plugin_matrix.rst, src/streamlink/plugins/tga.py
Fix validation schema for longzhu.com in plugins/tga.py and standardize the returned stream name.
=> Fix issue #426 on plugins/tga.py

src/streamlink/plugins/zhanqi.py
With the new api does not need to download the entire page.
Delete useless code "stream_weight", and make http as live for best quality.
=> plugins.zhanqi: use new api

docs/plugin_matrix.rst, src/streamlink/plugins/daisuki.py, src/streamlink/stream/ffmpegmux.py, src/streamlink/stream/file.py, src/streamlink/stream/rtmpdump.py, src/streamlink/stream/stream.py, src/streamlink/stream/streamprocess.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py, tests/test_plugin_tvplayer.py
Main plugin courtesy of @intact: https://gist.github.com/intact/3d6af5f361c1a44fd878 👍 
Adds a new option `--daisuki-mux-subtitles` that will automatically convert the xml subtitles to srt and mux them into the output stream which requires `ffmpeg`. (Which I think is pretty cool.)
=> plugins.daisuki: add support for VOD streams from daisuki.net

src/streamlink/plugins/rtve.py, src/streamlink/stream/ffmpegmux.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py
Simple change to the regex to extract the content-id, should work for any video content :) 
Update: added an option to mux in subtitles when available (my Spanish is bad and subtitles help me).  
Fixes #612
=> plugins.rtve: update rtve plugin to support VOD

src/streamlink/plugins/rtve.py
As pointed out in https://github.com/streamlink/streamlink/issues/612#issuecomment-282900657, some of the available lower qualities were missing. This PR adds all the available qualities from HLS and HTTP.
=> plugins.rtve: return all the available qualities

src/streamlink/plugins/pluzz.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py
This PR add VOD subtitle support for the pluzz plugin.
=> Add subtitle support for pluzz plugins

docs/plugin_matrix.rst, src/streamlink/plugins/wwenetwork.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py
As requested by @whitetop in #636.
Two new options were added to support this plugin:
- `--wwenetwork-email`: the email for the WWE Network account
- `--wwenetwork-password`: the password for the WWE Network account
Both are required to access content.
=> plugins.wwenetwork: support for WWE Network streams

src/streamlink/utils/l10n.py, tests/test_localization.py
Fix for #649 and https://github.com/streamlink/streamlink-portable/issues/12. 
Greetings to our Korean users!
=> utils.l10n: fix for some locales without an official name in pycountry

src/streamlink/plugins/tvplayer.py
As reported in #654 by @willbrow, some channels (ITV at least) require a postcode be set to work. 
If the user has not set their postcode, and a postcode is required to watch the channel then a postcode (SE1 9LT) will automatically be set.
The user can change their postcode on the tvplayer.com website.
SE1 9LT is the postcode of the ITV HQ in London.
=> plugins.tvplayer: automatically set postcode when required

docs/plugin_matrix.rst, src/streamlink/plugins/ard_live.py
As reported by @karlo2105 in #660 the `ard_live` was no longer working.
Updated the plugin to support the new site layout, also added support for VOD streams.
=> plugins.ard_live: updated to new site layout

docs/plugin_matrix.rst, src/streamlink/plugins/ard_mediathek.py
- Added `mediathek.daserste.de` support to `ard_mediathek` (like i wrote in #661)
- Removed unused code.
=> plugins.ard_mediathek added mediathek.daserste.de support

docs/donate.rst
This fixes https://github.com/streamlink/streamlink/issues/652
=> Fix up the donate docs

docs/donate.rst
Should finish what was started in #672 and fix #652 :)
=> docs.donate: drop name headers to subsection level

docs/install.rst
Just a small tweak to the night installer link to make it more obvious :)
=> docs: make the nightly installer link more obvious

docs/plugin_matrix.rst, src/streamlink/plugins/beam.py
Should fix #688 :) Also provides and HLS alternative for live streams.
=> plugins.beam: add support for VOD and HLS streams for live

src/streamlink/plugins/bbciplayer.py
Added `hls` stream support in addition to the existing `hds` stream support.
=> plugins.bbciplayer: add support for HLS streams

docs/plugin_matrix.rst, src/streamlink/plugins/camsoda.py, tests/test_plugin_camsoda.py
works only for live streams, not for vods
Fixed streamlink/streamlink#683
=> plugins.camsoda Added support for camsoda.com

docs/plugin_matrix.rst, src/streamlink/plugins/garena.py, tests/test_plugin_garena.py
=> plugins.garena - Added new plugin garena

src/streamlink/plugins/aliez.py
Also fixed Regex verifying we're on a video/live page. Fixes #695, with wildcard TLD suggestion.
=> Aliez plugin now accepts any TLD

src/streamlink/plugins/dailymotion.py
As requested by @karlo2105 in #733 :)
The featured video from the channel's page will be played.
=> plugins.dailymotion: play the featured video from channel pages

README.md
This is similar to what @bastimeyer has over on the gui: https://github.com/streamlink/streamlink-twitch-gui#why and I wanted to make sure we're noting that for the CLI as well. I've slightly modified what he had to make sure we're also linking Twitch's official stance regarding ad blockers.
=> Add readme note about supporting streamers

src/streamlink/plugins/twitch.py
As pointed out in #782 by @hodor22.
Extracts the channel/video ID from pop-out player URLs.
Adds support for clips subdomain. There is a v2 clips API, which responds with the same schema as the original v1 clips API but only requires the clip name without the channel
name (as per the new clip URLs).
fixes #782
=> plugins.twitch: support for pop-out player URLS and fixed clips

src/streamlink/plugins/chaturbate.py, tests/test_plugin_chaturbate.py
It will now use an **API**
still **not sure** if they will stick with this or **if they will change it back again**.
It's **~2 days** now with this, maybe they won't change it back.
tested with
- linux - python2.7
- win10 - python3.5
---
Let's close all **chaturbate** related Issues
closes #767 
---
closes #634 
not sure how to test if someone uses OBS but it **should work**,
because we use the **api** and not the website.
---
closes #685 
**without** an RTMPDUMP **update** #741 the **rtmp chaturbate streams won't work**,
and if the hls streams are laggy well its's an chaturbate issue not streamlink.
=> [chaturbate] Fixed plugin - New API

docs/plugin_matrix.rst, src/streamlink/plugins/cam4.py
This PR provides support for cam4.com.
As requested in https://github.com/chrippa/livestreamer/issues/689
=> Add support for Cam4 [NSFW]

docs/plugin_matrix.rst, src/streamlink/plugins/vrtbe.py, tests/test_plugin_vrtbe.py
**EXAMPLES**
- LIVE
https://www.vrt.be/vrtnu/kanalen/canvas/
https://www.vrt.be/vrtnu/kanalen/een/
https://www.vrt.be/vrtnu/kanalen/ketnet/
- VOD
https://www.vrt.be/vrtnu/a-z/belfast-zoo/1/belfast-zoo-s1a14/
https://www.vrt.be/vrtnu/a-z/sporza--korfbal/2017/sporza--korfbal-s2017-sporza-korfbal/
https://www.vrt.be/vrtnu/a-z/de-grote-peter-van-de-veire-ochtendshow/2017/de-grote-peter-van-de-veire-ochtendshow-s2017--en-parels-voor-de-zwijnen-ook/
Fixed streamlink/streamlink#788
=> [VRTbe] new plugin for vrt.be/vrtnu

tests/test_cmdline.py
If `stream-types` is set to anything that doesn't include `test` as a stream type, then the tests for the cmd line will fail.
Added the option to assert a specific exit code as well.
=> tests: cmdline tests can fail if there are some config options set

docs/plugin_matrix.rst, src/streamlink/plugins/telefe.py, tests/test_plugin_telefe.py
As issued in https://github.com/streamlink/streamlink/issues/805
=> Add support for Telefe (VOD)

docs/plugin_matrix.rst, src/streamlink/plugins/cyro.py, tests/test_plugin_cyro.py
Fixed streamlink/streamlink#721
=> [cyro] New plugin for embeded streams from cyro.se

src/streamlink/plugins/pcyourfreetv.py
See https://github.com/streamlink/streamlink/pull/833
=>  plugins.pcyourfreetv: add token parameters

src/streamlink/plugins/ustreamtv.py
Fixed some timeout handling issues with the UStream plugin.
Should fix #840
=> plugins.ustreamtv: log timeout errors and adjust retries for polling

src/streamlink/plugins/pcyourfreetv.py, tests/test_plugin_pcyourfreetv.py
http://pc-yourfreetv.com layout has been updated. This PR will update the corresponding plugin to support such changes.
=> plugin.pcyourfreetv: update for new page layout

src/streamlink/plugins/tvplayer.py, tests/test_plugin_tvplayer.py
As pointed out in #849 @nicr4wks the tvplayer.com website has been updated. This PR updates the plugin to support the changes.
=> plugin.tvplayer: update to support new site layout

docs/plugin_matrix.rst, src/streamlink/plugins/eltrecetv.py, tests/test_plugin_eltrecetv.py
As suggested in https://github.com/streamlink/streamlink/issues/805
=> Add support for ElTreceTV (VOD & Live)

docs/plugin_matrix.rst, src/streamlink/plugins/ellobo.py, src/streamlink/plugins/streann.py, src/streamlink/utils/crypto.py, tests/test_utils_crypto.py
Also supports ellobo.com, fixing #869. Not so straightforward :)
=> plugins.streann: support for ott.streann.com + ellobo.com

src/streamlink/plugins/pcyourfreetv.py
It looks like a game of cat and mouse... At the next layout change, I will probably give up and ask for deleting this plugin.
=> plugins.pcyourfreetv: fix for new new new layout

docs/plugin_matrix.rst, src/streamlink/plugins/streamable.py
Supports VOD streams from streamable.com
- streamable.com/s/5uk0a/ulyjaq
- streamable.com/sf37q
=> plugins.streamable: support for videos on streamable.com

docs/plugin_matrix.rst, src/streamlink/plugins/pluzz.py, tests/test_plugin_pluzz.py
See https://github.com/streamlink/streamlink/issues/902
=> plugins.pluzz: rework for new france.tv platform replacing pluzz.francetv.fr

src/streamlink/plugins/tvplayer.py
Should fix the issue mention in https://github.com/streamlink/streamlink/issues/849#issuecomment-303064621.
=> plugins.tvplayer: fix bug with some channels not loading

src/streamlink/plugins/hitbox.py
Fixes the issue in #935 and adds support for hosted channels.
=> plugins.hitbox: fix new VOD urls, and add support for hosted streams

src/streamlink_cli/argparser.py
This adds a few more examples to the player docs to hopefully address confusion like in https://github.com/streamlink/streamlink/issues/895
=> Add a few more examples to the player option

src/streamlink/plugins/app17.py
e.g. http://17app.co/share/profile/c87cbac6-7716-40f8-b36d-98919786cb97
=> plugins.app17: fix hls url and support UID page

docs/plugin_matrix.rst, src/streamlink/plugins/looch.py
Fixes #991 with support for both VOD and live streams.
=> plugins.looch: support for live and vod streams on looch.tv

docs/plugin_matrix.rst
=> Update plugin_matrix.rst for arconai.tv

win32/streamlinkrc
Add MPC-HC x64 in streamlinkrc
(if i of course added the changes to the desired file)
=> Add MPC-HC x64 in streamlinkrc

src/streamlink/plugins/dogan.py
teve2.com.tr updated to use a different api URL (same as cnnturk.com)
=> plugins.dogan: small api change for teve2.com.tr

src/streamlink/plugins/kanal7.py
The iframes on the kanal7 site are now nested.
=> plugins.kanal7: fix for nested iframes

src/streamlink/plugins/bbciplayer.py
Update to the API call URL and the method for determining the VPID of the programme. There was an issue with the ident card stream being selecting instead of the actual programme, this PR makes the plugin more robust.
=> bbciplayer: fix for api changes to iplayer

docs/plugin_matrix.rst, src/streamlink/plugins/picarto.py
Adds support for VOD to the picarto plugin as requested in #1006 .
=> plugins.picarto: support for VOD

src/streamlink/plugins/ine.py
Update to fix a small change in the jwplayer embed code, fixes #1026.
=> plugins.ine: update to extract the relocated jwplayer config

src/streamlink/plugins/app17.py
=> plugins.app17: change ROOM_URL

src/streamlink/plugins/artetv.py
Fixed streamlink/streamlink#1045
=> [arte] vod api url update & add new/missing languages

docs/plugin_matrix.rst, src/streamlink/plugins/brittv.py
=> plugins.brittv: support for live streams on brittv.co.uk

src/streamlink/plugins/douyutv.py
=> plugins.douyutv: update post data

src/streamlink/plugins/vidio.py, tests/test_plugin_vidio.py
Fixed streamlink/streamlink#949
=> [vidio] Fixed Plugin, new Regex for HLS URL

src/streamlink/plugins/npo.py
Fixed streamlink/streamlink#1062
If they remove the **old API** _(currently used by streamlink)_,
the livestreams won't work with the **new API**.
=> [npo] Update for new website layout, Added HTTPStream support

src/streamlink/plugins/tvplayer.py, tests/test_plugin_tvplayer.py
=> plugins.tvplayer: small update to channel id extraction

src/streamlink/plugins/ufctv.py
Fixed issues discussed in streamlink/streamlink#1029
=> [ufctv] updated to capture 4500k streams

docs/plugin_matrix.rst, src/streamlink/plugins/vk.py, tests/test_plugin_vk.py
Adds support for vk.com VoD and Livestream services.
Should solve #879.
=> plugins.vk: add support for vk.com vod/livestreams

src/streamlink/plugins/arconai.py, tests/test_plugin_arconai.py
Fixed streamlink/streamlink#1067
Fixed streamlink/streamlink#1073
=> [arconai] Fixed plugin for new website

src/streamlink/plugins/douyutv.py
Use douyu open API which no need sign token.
=> plugins.douyutv: use douyu open API

src/streamlink/plugins/app17.py
17app webpage has a big change, new url is https://17.live.
=> plugins.app17: new layout

ISSUE_TEMPLATE.md, README.md
See #1104
- Move all links to the readme footer (except certain external links)
- Update all links and use https where possible
- Fix markdown format (headers, lists, links, code blocks)
- Reword paragraphs
- Add more links to the Streamlink website
- Use markdown for all Open Collective links and images
- Reorder badges in the readme header
- Add Open Collective link to the footer of the issue template
=> Restructure readme

src/streamlink/plugins/adultswim.py
=> plugins.adultswim: fix for some live streams

src/streamlink/plugins/bbciplayer.py
The beeb now enforces logins for watching iPlayer, logins are now
enforced by the plugin.
=> plugins.bbciplayer: fix for page formatting changes and login

src/streamlink/plugins/cdnbg.py
Update to support new page layout and support for bloombergtv.bg and
tvevropa.com.
Fixes #1164 and fixes #921.
=> plugins.cdnbg: support for updated layout and extra channels

src/streamlink/plugins/liveme.py, tests/test_plugin_liveme.py
Fixed streamlink/streamlink#1149
=> [liveme] url regex update

src/streamlink/plugins/arconai.py, tests/test_plugin_arconai.py
Just updates ArconaiTv to support the new url.
=> plugins.arconaitv: fix arconaitv to new url

docs/plugin_matrix.rst, src/streamlink/plugins/bongacams.py
Fixed streamlink/streamlink#1074
=> [bongacams] replace RTMP with HLS

src/streamlink/plugins/app17.py
```wansu-global-pull-rtmp.17app.co```
```wansu-china-pull-rtmp-17.peibupei.com```
```qiniu-global-pull-rtmp.17app.co```
```qiniu-china-pull-rtmp-17.peibupei.com```
=> plugins.app17: fix wansu cdn url

script/release.sh
Keeps on changing random .py files, let's only change setup.py and
__init__.py
=> Update the release script

docs/plugin_matrix.rst, src/streamlink/plugins/webcast_india_gov.py, tests/test_webcast_india_gov.py
As issued in https://github.com/streamlink/streamlink/issues/1222
=> Add support for webcast.gov.in

src/streamlink/plugins/tvplayer.py
A small tweak to handle the slightly different layout when the logged in user has a subscription. I also added some more verbose logging for easier debugging.
=> plugins.tvplayer: extract the channel id when logged in as a subscriber

src/streamlink/plugins/kanal7.py
Fixes #1267. There was a slight change to the page layout.
=> plugins.kanal7: update for page layout change and referrer check

src/streamlink/plugins/turkuvaz.py
Fix support for `minikacocuk.com.tr` and `atvavrupa.tv` live streams, and add support for `anews.com.tr`.
=> plugins.turkuvaz: fix some turkuvaz sites and add support for anews

docs/plugin_matrix.rst, src/streamlink/plugins/dogus.py, src/streamlink/plugins/startv.py
HDS streams don't appear to be supported any more, and star tv is now an embedded YouTube live stream.
=> plugins.dogus/startv: fix dogus sites

src/streamlink/plugins/huya.py
issue #1256
fix huya.com plugin
=> fix huya.com plugin

src/streamlink/plugins/pandatv.py
fix APIv3 and let wangsu cdn priority
=> plugins.pandatv: fix APIv3

src/streamlink/plugins/liveme.py
closes streamlink/streamlink#1295
=> [liveme] API update

src/streamlink/plugins/tvcatchup.py
Fixed small change in the website layout. 
fixes #1254, fixes #1282
=> plugins.tvcatchup: HLS source extraction update

src/streamlink_cli/main.py
A nice solution for this error was found in gevent/gevent#1000
Fixed streamlink/streamlink#916
Fixed streamlink/streamlink#975
Fixed streamlink/streamlink#1236
Maybe this will help streamlink/streamlink-twitch-gui#467
=> Ignore WinError 10053 / WSAECONNABORTED

src/streamlink/plugin/api/useragents.py, src/streamlink/plugins/camsoda.py, tests/test_plugin_camsoda.py
- only free public streams are supported
- use "privacy.resistFingerprinting" useragent for FireFox
- removed html tests, regex only tests are enough
Fixed streamlink/streamlink#1271
=> [camsoda] Fixed broken plugin

src/streamlink/plugins/zdf_mediathek.py
Fixed streamlink/streamlink#1329
=> [zdf] apiToken update

src/streamlink/plugins/bilibili.py
fix bilibili plugin issue #1331
=> fix plugin for bilibili to adapt the new API

docs/issues.rst, docs/players.rst, win32/streamlinkrc
- Domain expired
- Not maintained anymore
=> [docs] Removed MPlayer2

src/streamlink/plugins/btv.py
Fixed https://github.com/streamlink/streamlink/issues/1163
=> [BTV] Fixed login return message

src/streamlink/plugins/picarto.py
This should fix #1354 
I tried to make the plugin a bit more robust, but it is still reliant on regex scraping the page to determine online/offline status. If anyone has any suggestions on how to do this in a more robust way, let me know.
=> Reworked picarto.tv plugin to deal with website changes.

docs/plugin_matrix.rst, src/streamlink/plugins/olympicchannel.py, tests/test_plugin_olympicchannel.py
This plugin works for both non-premium live streams, and vods on the site. I'm kinda new to this so if the naming conventions or other things like that are off let me know and I'll do my best to fix them,
=> Add plugin for olympicchannel.com

src/streamlink/plugins/tigerdile.py, tests/test_plugin_tigerdile.py
I noticed that this plugin would fail if you missed the trailing slash. Since it works with or without it, I just make the final slash optional in the regex.
=> Updates and improvements to tigerdile.com plugin

src/streamlink/plugins/mlgtv.py, tests/test_plugin_mlgtv.py
Fixed streamlink/streamlink#1362
=> [mlgtv] Fixed broken Plugin

docs/plugin_matrix.rst, src/streamlink/plugins/qq.py, tests/test_plugin_qq.py
Fixed https://github.com/streamlink/streamlink/issues/1190
=> [qq] New Plugin for live.qq.com

src/streamlink/plugins/streann.py
Fixed streamlink/streamlink#1319
=> [streann] Added headers for post request

src/streamlink/plugins/douyutv.py
fix #1393, fix #1370, fix #1102
=> [Douyutv] fix API

src/streamlink/plugins/dailymotion.py
can be tested with
- http://www.dailymotion.com/france24
- http://www.dailymotion.com/televizijak23
Fixed streamlink/streamlink#1292
---
Added error message for geo-blocked videos,
it can be tested with
- https://www.dailymotion.com/video/x2lefik - _blocked outside of france_
---
closes streamlink/streamlink#1093 it's user related, not streamlink
=> [Dailymotion] Fixed livestream id from channelpage

script/makeinstaller.sh
=> nsis: restore old install dir, keep multiuser

LICENSE, debian/copyright, docs/_themes/sphinx_rtd_theme_violet/LICENSE, docs/conf.py, src/streamlink/__init__.py
=> Welcome 2018

src/streamlink/stream/hls.py
and don't raise KeyKerror if the m3u8 file is empty this allows the file to reload.
---
Fixed streamlink/streamlink#1419
streamlink/streamlink#1423 required for youtube.
=> [hls] Don't try to skip a stream if the offset is 0

src/streamlink/plugins/mitele.py, tests/test_plugin_mitele.py
- fallback if not hls_url was found, just the suffix.
- added url tests
- added all channels
Fixed streamlink/streamlink#1337
=> [mitele] Update for different api response

docs/plugin_matrix.rst, src/streamlink/plugins/zengatv.py, tests/test_plugin_zengatv.py
Fixed streamlink/streamlink#890
=> [zengatv] New Plugin for zengatv.com

src/streamlink/plugins/youtube.py
Fixed streamlink/streamlink#1264
Test url
https://www.youtube.com/watch?v=aqz-KE-bpKQ
=> [youtube] added Audio m4a itag 256 and 258

src/streamlink/plugins/vaughnlive.py
As discussed, should fix #1187
=> Vaughnlive Fix

src/streamlink/plugins/ok_live.py, tests/test_plugin_ok_live.py
This PR adds a plugin for ok.ru live videos (#1404)
=> Add ok.ru/live plugin

src/streamlink/plugins/tf1.py, tests/test_plugin_tf1.py
TF1 group renamed some of her channels, NT1 & HD1, as "TFX" & "TF1 Séries Films". So I've updated plugin according to last TF1 changes.
=> [TF1] Fix plugin

src/streamlink/plugins/bigo.py
Update regex per #1412 so that the bigo plugin will work again.
=> [bigo] update video regex to match current website (#1412)

src/streamlink/plugins/facebook.py
more information https://github.com/streamlink/streamlink/issues/990#issuecomment-354804542
currently not fixable with streamlink
Closes https://github.com/streamlink/streamlink/issues/990
Closes https://github.com/streamlink/streamlink/issues/880
=> [facebook] mark as broken, they use dash now.

src/streamlink/plugins/periscope.py
They use normal and variant playlists now.
Closes https://github.com/streamlink/streamlink/issues/1438
=> [periscope] Fix for variant HLS streams

src/streamlink/plugins/foxtr.py
=> plugins.foxtr: update regex to match new site layout

src/streamlink/plugins/kanal7.py
=> plugins.kanal7: fix for new streaming iframe

README.md
navigate to streamlink before python setup.py install
=> added cd streamlink

script/release.sh
Adds a little blurb on the OpenCollective to our release script
=> Add OpenCollective message to release script

CHANGELOG.rst
Updates the changelog from past releases to include notes on the Open
collective.
=> Manually update CHANGELOG.rst

src/streamlink/plugins/dailymotion.py, tests/test_plugin_dailymotion.py
* Fix https://github.com/streamlink/streamlink/issues/1542
* Add unit tests for dailymotion plugin
=> [dailymotion] Fix for new stream data API

src/streamlink/plugins/streann.py, tests/test_plugin_streann.py
- **more debug** msg
- set **headers** on every **get request**
- use **new** url for **stream_url**, the old one still works but the website uses this url
Closes https://github.com/streamlink/streamlink/issues/1505
=> [streann] Fixed broken plugin

src/streamlink/plugins/tga.py
Support new url pattern `http://y.longzhu.com/<channel>?from=challcontent`
=> update plugin for longzhu.com to support new url pattern

docs/plugin_matrix.rst, src/streamlink/plugins/pixiv.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py, tests/test_plugin_pixiv.py
Streams can be found at https://sketch.pixiv.net/lives
closes #1515 
---
Ping @Gameplayer9198
=> [pixiv] New plugin for sketch.pixiv.net

docs/plugin_matrix.rst, src/streamlink/plugins/playtv.py, tests/test_plugin_playtv.py
See https://github.com/streamlink/streamlink/pull/1533.
=> [playtv] Add support for international Play TV website 

docs/plugin_matrix.rst, src/streamlink/plugins/welt.py, tests/test_plugin_welt.py
Plugin for Welt, a German news/docutainment TV channel, previously called N24.
Geo-blocked to Germany...
=> plugins.welt: add plugin

src/streamlink/plugins/vaughnlive.py
Bit slow in creating this PR... fixes #1456.
=> plugins.vaughnlive: Updated server map

src/streamlink/plugins/itvplayer.py
Updates two URLs and a regex in line with server side changes.
=> Small tweaks to fix ITV player. Fixes #1622

docs/plugin_matrix.rst, src/streamlink/plugins/tvp.py, tests/test_plugin_tvp.py
> Telewizja Polska S.A. (TVP S.A., or Polish Television) is a public broadcasting corporation,
> the only public TV broadcaster in the territory of the Republic of Poland.
> https://en.wikipedia.org/wiki/Telewizja_Polska
http://tvpstream.vod.tvp.pl
http://tvpstream.vod.tvp.pl/?channel_id=1455
```
[cli][info] Found matching plugin tvp for URL
http://tvpstream.vod.tvp.pl/?channel_id=1455
[cli][info] Available streams: none_101k, 288p_228k (worst), 288p_578k,
288p_1119k, 288p_1797k, 576p_2433k, 576p_3811k (best)
[cli][info] Opening stream: 576p_3811k (hls)
```
closes https://github.com/streamlink/streamlink/issues/1590
---
ping @remek30
=> [TVP] New Plugin for Telewizja Polska S.A.

src/streamlink/plugins/dogan.py
=> plugins.dogan: update for page layout change

src/streamlink/plugins/filmon.py
Fixes #1575, a continuation of @Billy2011's PR #1610.
This changes the plugin to look for the `channel_id` in the page when given a `tv` URL, this makes it more robust and fixes the issue with Sat1. 
Thanks to @bastimeyer for giving me the copy-paste quote regex ;)
=> plugins.filmon: more robust channel_id extraction

src/streamlink/plugins/ok_live.py
=> plugins.ok_live: fix <hlsurl> extraction

src/streamlink/plugins/btsports.py, src/streamlink/utils/__init__.py, src/streamlink_cli/argparser.py, src/streamlink_cli/main.py, tests/test_utils.py
Basic plugin to support BT Sports, requires a login to use.
=> plugins.btsports: add plugin bt sports

src/streamlink/plugins/ine.py
The offloaded the playlisting to a jwplayer service.
Fixes #1662
=> plugins.ine: support for updated site layout

docs/plugin_matrix.rst, src/streamlink/plugins/kingkong.py, tests/test_plugin_kingkong.py
This pull request will add a plugin for www.kingkong.com.tw, a game streaming website in Taiwan.
This plugin is mostly modified from the one of Douyutv.
Example of stream URLs can be found in the Kingkong front page.
A VOD URL example is provided FYI:
https://www.kingkong.com.tw/video/2152350G38400MJTU
=> Add plugin for www.kingkong.com.tw

src/streamlink/plugins/vidio.py
=> plugins.vidio: update to support new layout

docs/plugin_matrix.rst, tests/test_plugin_btsports.py
Forgot to update the docs plugin matrix.
=> plugins.btsports: add missing plugin matrix entry and tests

src/streamlink/plugins/vidio.py
=> plugins.vidio: py2 vs. py3 unicode fix

src/streamlink/plugins/goodgame.py
Update for layout change and added some debug messages.
Fixes #1678
=> plugins.goodgame: update for change in page layout

src/streamlink/plugins/goodgame.py
Thanks due to @flijloku.
Should properly fix #1678 now. I added a big more debug logging, and a channel offline warning - it still checks the streams just in case...
=> plugins.goodgame: fix bug with streamkey extraction

src/streamlink/plugins/tvcatchup.py, tests/test_plugin_tvcatchup.py
Fixes #1695, thanks @LoneFox78
=> plugins.tvcatchup: support for https URLs

src/streamlink/stream/segmented.py
The segmented stream downloader uses a threadpool to allow multiple segments to be downloaded simultaneously. The thread pool installs an atexit hook so that causes them to complete their current tasks, this means that if segments are still downloading streamlink will continue running until the segments are downloading.
By unregistering this atexit hook (because there aren't any consistency issues) the exit time can be sped up in some cases.
See #521.
=> Allow streamlink to exit faster when using Ctrl-C

src/streamlink/plugins/bfmtv.py, tests/test_plugin_bfmtv.py
Update regular expression with https scheme. BFM urls are secure now
=> plugins.bfmtv : Update regular expression

script/makeinstaller.sh
My bad, didn't update the windows installer... thanks @mmetak
=> win-installer: add missing isodate module

src/streamlink/plugins/dailymotion.py
Should give better error logging for offline channels, and other errors.
=> plugins.dailymotion: fix error logging for stream errors

src/streamlink/plugins/bbciplayer.py
=> plugins.bbciplayer: add dash support

docs/plugin_matrix.rst, src/streamlink/plugins/brightcove.py, src/streamlink/plugins/reshet.py, tests/test_plugin_reshet.py
Includes a small enhancement to the brightcove player class.
=> plugins.reshet: support for reshet.tv live and VOD streams

src/streamlink/plugins/vaughnlive.py
=> Fix bug 1730, vaughnlive port change

src/streamlink/plugins/crunchyroll.py
Some streams will not work with the session ID from the mobile app API. Accessing the website will generate a session ID that works for all streams.
If a authenticated session ID is provided on the command line, the account details must match or be omitted.
Should fix #1574
=> plugins.crunchyroll: switch method of obtaining session id

src/streamlink/plugins/facebook.py
=> plugins.facebook: remove debugging code

src/streamlink/plugins/funimationnow.py, tests/test_plugin_funimationnow.py
This PR adds the ability to login. Premium content should be available, however I do not have a subscription so I cannot test it. 
Fixes #789, pinging @vinnyA3. 
If #1724 is merged, I'd like to update this plugin to store the incap cookies.
=> plugins.funimationnow: login support and bug fixes

src/streamlink_cli/main.py
=> logging: do not log when using quiet options (--json, --quiet, etc)

src/streamlink/plugins/bbciplayer.py
Updated all the logging too.
Bug was here: https://github.com/streamlink/streamlink/compare/master...beardypig:bbciplayer-fix?expand=1#diff-9255f1b591e686fe40d95231404a723bL162
=> plugins.bbciplayer: fix bug is DASH for VOD

src/streamlink/plugins/pluzz.py
This PR:
* brings DASH stream support
* fixes HDS stream retrieving
=> [plugins.pluzz] DASH stream support + fix for HDS streams

src/streamlink/plugins/rtbf.py
This PR:
* brings DASH stream support
* fixes radio stream retrieving
=> [plugins.rtbf] Fix radio streams + DASH support

docs/plugin_matrix.rst, src/streamlink/plugins/vinhlongtv.py, tests/test_plugin_vinhlongtv.py
TV/Radio channel from Vietnam
https://www.youtube.com/user/VinhLongTV/about
---
Fixed https://github.com/streamlink/streamlink/issues/1762
=> plugins.VinhLongTV: New plugin for livestreams of thvli.vn

src/streamlink/plugins/vaughnlive.py
Includes a custom `Stream` class to rejigger the stream (thanks @yoya3312)
fixes #1780
=> plugins.vaughnlive: support for the HTML flv player

docs/plugin_matrix.rst, src/streamlink/plugins/tlctr.py, tests/test_plugin_tlctr.py
TV channel from Turkey
https://en.wikipedia.org/wiki/TLC_(Turkey)
Fixed https://github.com/streamlink/streamlink/issues/1516
=> plugins.tlctr: New Plugin for tlctv.com.tr/canli-izle

src/streamlink/cache.py, src/streamlink/logger.py, src/streamlink/plugin/api/utils.py, src/streamlink/plugins/facebook.py, src/streamlink/plugins/onetv.py, src/streamlink/plugins/vk.py
Including beardypig's fix and a couple of cosmetics
=> Convert literal comprehensive dicts to dict contructs

docs/plugin_matrix.rst, src/streamlink/plugins/lrt.py, tests/test_plugin_lrt.py
Support for live and VOD streams :)
Fixes #1812
=> plugins.lrt: add support for Lithuanian National Television

src/streamlink/plugins/vrtbe.py, src/streamlink/stream/dash_manifest.py
Live streams have DRM for the higher quality streams, only the lower quality streams are available without DRM.
For VOD streams, all auth cookies must be sent using `--http-header/--http-cookie` as authentication is not currently supported.
Fixed a small bug in the DASH manifest segment generator for static timeline playlists. 
Fixes #1821
=> plugins.vrtbe: update to new page layout/API

src/streamlink/plugins/pandatv.py
fix indentation bug and add support for new url pattern 'https://xingxiu.panda.tv/<channel id>'
=> [plugins.pandatv]fix indentation bug and add support for new url pattern

src/streamlink/plugins/nos.py
Updated to the new page layout and modernised the plugin a bit. 
Fixes #1811
=> plugins.nos: update for new page layout for live and VOD

docs/plugin_matrix.rst, src/streamlink/plugins/canalplus.py, src/streamlink/plugins/cnews.py, tests/test_plugin_canalplus.py, tests/test_plugin_cnews.py
Changes in the CanalPlus plugin would be too ugly and complex, so I split plugin and move the CNEWS part in a new plugin.
=> plugins.cnews : separate CNEWS data from CanalPlus plugin.

src/streamlink/plugins/itvplayer.py
All live and VOD streams appear to be available as HLS streams (and DASH
with DRM).
Fixes #1788 (but not with DASH)
=> plugins.itvplayer: update to new HTML5 API

docs/plugin_matrix.rst, src/streamlink/plugins/yupptv.py, tests/test_plugin_yupptv.py
I wasn't able to test subscription videos, but I assume it'll work.
Fixes #506
=> plugins.yupptv: support for yupptv with login support

src/streamlink/plugins/atresplayer.py
Updated to new page layout and API. 
Fixes #1843
=> plugins.atresplayer: support new layout/API

src/streamlink/stream/dash.py, src/streamlink/stream/dash_manifest.py, tests/resources/dash/test_7.mpd, tests/streams/test_dash_parser.py
Support for `SegmentList` type DASH streams. 
Fixes #1849
=> stream.dash: support for SegmentList streams with ranged segments

src/streamlink/plugins/atresplayer.py
Support for VOD streams on `atresplayer`.
Requires #1852 for the DASH streams to work.
=> plugins.atresplayer: update to support VOD streams

docs/plugin_matrix.rst, src/streamlink/plugins/mjunoon.py, tests/test_plugin_mjunoon.py
Support for both live and VOD streams from mjunoon.tv. 
Would be nice to have someone test it out. 
Fixes #1834
=> plugins.mjunoon: support for live and vod streams on mjunoon.tv

src/streamlink/plugins/live_russia_tv.py, tests/test_plugin_liverussiatv.py
Adds support for VOD streams as well as fixes in the live streams. 
Fixes #1872
=> plugins.live_russia_tv: fix for live streams, and support for VOD

.github/ISSUE_TEMPLATE/Bug_Report.md
This somehow slipped through...
=> Fix bug report template

docs/plugin_matrix.rst, src/streamlink/plugins/tvtoya.py, tests/plugins/test_tvtoya.py
Support for the live stream on http://tvtoya.pl/live. 
Most of the work done by @remek30.
=> Add tvtoya plugin

src/streamlink/utils/args.py, src/streamlink_cli/argparser.py, tests/test_utils_args.py
make it usable for plugin args
added tests
---
ref https://github.com/streamlink/streamlink/pull/1902#discussion_r200304653
=> utils.args: Moved streamlink_cli utils.args into streamlink package

src/streamlink/plugins/tv4play.py, tests/plugins/test_tv4play.py
VOD and Livestream fix
closes https://github.com/streamlink/streamlink/issues/1882
ping @Ordval
---
also support for `self.get_title()`
=> plugins.tv4play: Fix for updated website

src/streamlink/plugins/twitch.py
`AttributeError: 'TwitchAPI' object has no attribute 'session'`
`AttributeError: 'UsherService' object has no attribute 'session'`
---
error is related to #1925
=> plugins.twitch: Fixed AttributeError and Flake8

src/streamlink/plugins/crunchyroll.py
`AttributeError: 'CrunchyrollAPI' object has no attribute 'session'`
error is related to #1925
=> plugins.crunchyroll: Fixed AttributeError and Flake8

src/streamlink/plugins/filmon.py
`AttributeError: 'FilmOnAPI' object has no attribute 'session'`
error is related to #1925
=> plugins.filmon: Fixed AttributeError

src/streamlink/plugins/rtve.py
`AttributeError: 'ZTNRClient' object has no attribute 'session'`
and Flake8 error
---
error is related to https://github.com/streamlink/streamlink/pull/1925
=> plugins.rtve: Fixed AttributeError 'ZTNRClient' has no 'session'

src/streamlink/stream/hls_playlist.py
- declares explicit all pattern strings as raw strings
- move global & all other regex pattern to precompiled regex objects to `M3U8Parser`
- code optimization for parser loop
=> stream.hls_playlist: fix some regex pattern & code optimization

src/streamlink/plugins/younow.py, tests/plugins/test_younow.py
- Fixed `self.session.http` issues
- added title and author
- better error msg
- plugin cleanup / flake8
=> plugins.younow: Fix for session error and plugin cleanup

src/streamlink/plugins/youtube.py
`streamlink --title "{author} - {title}" URL best`
---
Use `PluginError` instead of `log.error` with `return` for video_id
---
removed not used import and schema
=> plugins.youtube: Added support for {author} and {title}

src/streamlink/plugins/ceskatelevize.py
They now use **https** but it is _invalid_ for `requests`,
so we need to use it but ignore it.
---
There region block message is now played as the video,
but it can't be detected if it is blocked from there API call.
If you don't want the region block message video,
this command closes Streamlink faster `--hls-segment-ignore-names  "/0.k,/1.k"`
---
Added some trace logs
---
closes https://github.com/streamlink/streamlink/issues/1955
@remek30
=> plugins.ceskatelevize: Fix for https issues

.github/ISSUE_TEMPLATE/Bug_Report.md, .github/ISSUE_TEMPLATE/Feature_Request.md, .github/ISSUE_TEMPLATE/Plugin_Issue.md, .github/ISSUE_TEMPLATE/Plugin_Request.md
Resolves #1961
Further discussion is welcome.
- Made all templates as consistent as possible
- Removed a couple of lines and tried to use short and precise sentences
- Fixed left over spelling/grammar errors
- Reworded the header and other comments
- Changed a few links
=> Reword+reformat issue templates for consistency

src/streamlink/plugins/openrectv.py
openrec.tv now requires users to login to access the streams, this PR
adds support for logins. Support for `--title` has also been added.
Fixes #1960
=> plugins.openrectv: update to match site changes and title support

src/streamlink/plugins/mjunoon.py
Fixed https://github.com/streamlink/streamlink/issues/1969
=> plugins.mjunoon: use a User-Agent

src/streamlink/plugins/steam.py
The session ID is set in a cookie when the page is loaded, thus the page
must be requested, but only to get the session ID cookie.
Fixes #1977
=> plugins.steam: api requests now require a session id

src/streamlink/plugins/twitch.py, tests/plugins/test_twitch.py
https://www.twitch.tv/twitch/video/292713971
---
Fixed https://github.com/streamlink/streamlink/issues/1982
@Tomalak
=> plugins.twitch: new video URL regex

src/streamlink/plugins/drdk.py
The main reason for the existing plugin failing was the URL for live
streams being outdated; no general list appears to exist, so instead we
rely on those provided for the individual channels, cf. also the approach
used for VODs.
=> Update and reactivate plugin for dr.dk

src/streamlink/plugins/sportal.py
```
$ streamlink https://www.sportal.bg/sportal_live_tv.php?str=19
[cli][info] Found matching plugin sportal for URL 
https://www.sportal.bg/sportal_live_tv.php?str=19
[plugin.sportal][warning] SSL certificate verification is disabled.
[cli][info] Available streams: 540p (worst, best)
[cli][info] Opening stream: 540p (hls)
```
---
Fixed https://github.com/streamlink/streamlink/issues/1165
SSL issue https://github.com/streamlink/streamlink/issues/1494
=> plugins.sportal: Removed old RTMP streams, use HLS

src/streamlink/plugins/steam.py, tests/plugins/test_steam.py
=> Update steam plugin to work with steam.tv urls

src/streamlink/plugins/schoolism.py
=> plugins.schoolism: support for assignment feedback videos

src/streamlink/plugins/euronews.py
Fixes #2047
This utilizes the `update_scheme` util method and uses the scheme of the input URL for the missing explicit scheme of the API request URL.
Live streams of various subdomains should be working now, some VODs I've tested (unrelated to these changes) seem to be broken and need to be fixed.
=> plugins.euronews: fix live stream API URL scheme

src/streamlink/plugins/ssh101.py, tests/plugins/test_ssh101.py
Also converted delimiters to single quotes
Test url: https://www.ssh101.com/live/m1gacytv54201
=> Fix ssh101

docs/plugin_matrix.rst, src/streamlink/plugins/teleclubzoom.py, tests/plugins/test_teleclubzoom.py
TV Channel from Switzerland.
closes https://github.com/streamlink/streamlink/issues/1993
@097115
=> plugins.teleclubzoom: New plugin for teleclubzoom.ch

docs/plugin_matrix.rst, src/streamlink/plugins/senategov.py, tests/plugins/test_senategov.py
Only supports the senate hearing streams (as far as i know).
Fixes #2042
=> plugins.senategov: support for hearing streams on senate.gov

docs/plugin_matrix.rst, src/streamlink/plugins/stadium.py, tests/plugins/test_stadium.py
Support for watchstadium.com/live
closes #1188 (better late than never, eh @unlocKing...)
=> plugins.stadium: support for live stream on watchstadium.com

src/streamlink/plugins/egame.py
test url: https://egame.qq.com/497383565
=> [plugins.egame]update regex to support new pattern

docs/plugin_matrix.rst, src/streamlink/plugins/cubetv.py, tests/plugins/test_cubetv.py
This pull request adds support for live streams from [cubetv.sg](https://www.cubetv.sg) website. Closes #2079
=> plugins.cubetv: support for live streams on cubetv.sg

src/streamlink/plugins/bilibili.py
#2126 was closed because we couldn't reproduce the issue OP had, but it appears that the website indeed changed its API as @undeadking pointed out. With these changes, the plugin works again, but I am unsure if they will revert back API changes again (as it already happened when #2126 was closed).
=> plugins.bilibili: Fix plugin after API change

src/streamlink/plugins/npo.py
Added support for the new standard domain "npostart.nl".
=> Update to the NPO plugin

src/streamlink/plugins/twitch.py
`streamlink --title "{title} - {author} - {category}" <url> best`
`{category}` and `{game}` both work interchangeably as per #1576
Title parsing works for live streams, VoDs and clips.
=> plugins.twitch: Add support for {title}, {author} and {category}

src/streamlink/plugins/bbciplayer.py
Slight change in the data layout in the episode page for bbc iplayer. 
Fixes #2172
=> plugins.bbciplayer: change in the mediator info in the page layout

docs/plugin_matrix.rst, src/streamlink/plugins/stv.py, tests/plugins/test_stv.py
STV is a television channel serving Scotland.
- https://en.wikipedia.org/wiki/STV_(TV_channel)
closes https://github.com/streamlink/streamlink/issues/2038
=> plugins.stv: New Plugin for https://player.stv.tv/live

docs/plugin_matrix.rst, src/streamlink/plugins/vtvgo.py, tests/plugins/test_vtvgo.py
VTV is the national television broadcaster of Vietnam.
https://en.wikipedia.org/wiki/Vietnam_Television
closes https://github.com/streamlink/streamlink/issues/1536
=> plugins.vtvgo: New plugin for https://vtvgo.vn/

docs/plugin_matrix.rst, src/streamlink/plugins/sbscokr.py, tests/plugins/test_sbscokr.py
SBS is a national South Korean television and radio network company.
- https://en.wikipedia.org/wiki/Seoul_Broadcasting_System
closes https://github.com/streamlink/streamlink/issues/1106
=> plugins.sbscokr: New Plugin for http://play.sbs.co.kr/onair/pc/index.html

src/streamlink/plugin/api/useragents.py
use some more common / new User Agents
=> api.useragents: update User-Agent list

docs/plugin_matrix.rst, src/streamlink/plugins/afreeca.py, tests/plugins/test_afreeca.py
closes https://github.com/streamlink/streamlink/issues/2203
=> plugins.afreeca: use Referer for every connection

src/streamlink/plugins/btsports.py
=> plugins.btsports: fix for change in login flow

src/streamlink/plugins/tvrby.py
closes https://github.com/streamlink/streamlink/pull/2209
=> plugins.tvrby: Fixed broken plugin.

src/streamlink/plugins/trt.py, tests/plugins/test_trt.py
Fixed https://github.com/streamlink/streamlink/issues/2214
=> plugins.trt: Added support for https url, fixed logger error

docs/plugin_matrix.rst, src/streamlink/plugins/kanal7.py, tests/plugins/test_kanal7.py
closes https://github.com/streamlink/streamlink/issues/2215
=> plugins.kanal7: Fixed iframe_re/stream_re, added new domain

src/streamlink/plugins/youtube.py
closes https://github.com/streamlink/streamlink/issues/2245
=> plugins.youtube: replace "gaming" with "www" subdomain

src/streamlink/plugins/dogus.py
Some of the channels have migrated to YouTube. Some extra channels on Kral Muzik are supported as well now.
Fixes #2213
=> plugins.dogus: support for YouTube embedded streams

docs/install.rst
We've had a package of streamlink since the fork.
Thanks!
=> Add OpenBSD to the installation docs

src/streamlink/plugins/rtve.py
```
$ streamlink http://www.rtve.es/deportes/mas-tdp/directo/ -l debug
[cli][info] Found matching plugin rtve for URL http://www.rtve.es/deportes/mas-tdp/directo/
[plugin.rtve][debug] Found content with id: 1712295
[cli][info] Available streams: 270p_alt (worst), 270p, 360p_alt, 360p, 576p_alt, 576p, 720p_alt, 720p (best)
```
closes https://github.com/streamlink/streamlink/issues/2282
=> plugins.rtve: Fixed content_id search

src/streamlink/plugins/streamme.py, tests/plugins/test_streamme.py
```
$ streamlink https://www.stream.me/... source
[cli][info] Found matching plugin streamme for URL https://www.stream.me/...
[cli][info] Available streams: 144p (worst), 368p, 576p, source (best)
[cli][info] Opening stream: source (hls)
```
closes https://github.com/streamlink/streamlink/issues/2254
=> plugins.streamme: Fixed source quality, added title and author

src/streamlink/plugins/mitele.py, tests/plugins/test_mitele.py
- plugin cleanup: removed hls url build (Ref #1337),
the api returns a correct url at the moment and this is not needed.
- better error messages
- added support for new channels
closes https://github.com/streamlink/streamlink/issues/2281
=> plugins.mitele: plugin update

src/streamlink/plugins/atresplayer.py
```
$ streamlink https://www.atresplayer.com/directos/la-voz-24h/
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/la-voz-24h/
[cli][info] Opening stream: live (hls)
$ streamlink https://www.atresplayer.com/directos/atreseries/
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/atreseries/
[cli][info] Available streams: 360p (worst), 404p, 720p, 1080p (best)
```
closes https://github.com/streamlink/streamlink/issues/2280
=> plugins.atresplayer: Fixed HLSStream

src/streamlink/plugins/pluzz.py
Fixed https://github.com/streamlink/streamlink/issues/2332
=> plugins.pluzz: Fixed Video ID and logging update

src/streamlink/plugins/pluzz.py
Fixed https://github.com/streamlink/streamlink/issues/2344
=> plugins.pluzz: Fixed regex, they use quotes now.

docs/plugin_matrix.rst, src/streamlink/plugins/cdnbg.py, tests/plugins/test_cdnbg.py
closes https://github.com/streamlink/streamlink/issues/2343
=> plugins.cdnbg: New domain videochanel.bstv.bg

src/streamlink/plugins/tf1.py
closes https://github.com/streamlink/streamlink/issues/2345
=> plugins.tf1: Fixed python2.7 ascii error

.travis.yml
As mentioned in https://github.com/streamlink/streamlink/pull/2342#issuecomment-472718463, same changes as in https://github.com/streamlink/streamlink/pull/2342/commits/9bf941258c4ee95eca0052965b01d7e1da85cd13
Related: #2326
=> TravisCI: don't publish wheels on Github releases

docs/plugin_matrix.rst, src/streamlink/plugins/ntv.py, tests/plugins/test_ntv.py
NTV is russian tv channel (#2346): 
https://en.wikipedia.org/wiki/NTV_(Russia)
=> plugins.ntv: new Plugin for ntv.ru (#2346)

src/streamlink/plugins/rtpplay.py, tests/plugins/test_rtpplay.py
closes https://github.com/streamlink/streamlink/issues/2379
=> plugins.rtpplay: fix _m3u8_re and plugin cleanup

script/sdistsign.sh, setup.py
=> Update supported wheels so the job doesn't bomb

src/streamlink/plugins/idf1.py
```
$ /usr/bin/streamlink http://www.idf1.fr/live
[cli][info] Found matching plugin idf1 for URL http://www.idf1.fr/live
error: No playable streams found on this URL: http://www.idf1.fr/live
```
=> [plugins.idf1] Update for new website layout

src/streamlink/plugins/bbciplayer.py
This change worked for me. They changed the layout of the data on the page, only a slight change but I'd like someone else to verify it. 
Fixes #2371.
=> plugins.bbciplayer: small change to where the VPID is extracted from

src/streamlink/plugins/mediaklikk.py
Things were changed on the site, all the current livestreams work now.
=> plugins.mediaklikk: update plugin

docs/plugin_matrix.rst, src/streamlink/plugins/reuters.py, tests/plugins/test_reuters.py
closes https://github.com/streamlink/streamlink/issues/2427
=> plugins.reuters: New Plugin

docs/plugin_matrix.rst, src/streamlink/plugins/vimeo.py, tests/plugins/test_vimeo.py
This plugin adds support for Vimeo. It supports both VOD and live streams. It also supports subtitles.
=> plugins.vimeo: add support for vimeo.com

src/streamlink/utils/__init__.py, tests/resources/__init__.py, tests/test_utils.py
closes https://github.com/streamlink/streamlink/issues/2435
=> utils.__init__: remove cElementTree, it's just an alias for ElementTree

src/streamlink/plugins/welt.py, tests/plugins/test_welt.py
Fixes the plugin after the recent site layout changes. Live TV stream and VODs are now working again.
=> plugins.welt: fix plugin

src/streamlink/plugins/ustvnow.py, tests/plugins/test_ustvnow.py
The USTVNow website was completely redesigned and relaunched, this PR updates the plugin to handle the new site. 
Fixes #2498
=> plugins.ustvnow: updated to handle new auth, and site design

src/streamlink/plugins/pixiv.py
this adds the possibility to directly login to pixiv using the sessionid and devicetoken.
this can be useful for:
- automation scripts
- as a backup login method in case pixiv disables the oauth tokens that are used in the application
=> add login posibility for pixiv using sessionid and devicetoken

src/streamlink/plugins/twitch.py
Props to @back-to for noticing the behaviour :)
Fixes #2533
=> plugins.twitch: support for different clips URL

src/streamlink/plugins/wwenetwork.py, src/streamlink/utils/times.py, tests/plugins/test_wwenetwork.py, tests/test_utils_times.py
Update to support the new website version. The auth/refresh tokens are not stored, so each time a video is loaded a new login request is issued. 
Fixes #2564.
=> plugins.wwenetwork: support for new site

src/streamlink_cli/main.py
* Fixed use of invalid member console.logger
* Fixed lint warning "Too many arguments for logging format string"
=> CLI logging issues

docs/plugin_matrix.rst, src/streamlink/plugins/linelive.py, tests/plugins/test_linelive.py
=> plugins.linelive: new plugin for LINE LIVE (live.line.me)

docs/plugin_matrix.rst, src/streamlink/plugins/tv1channel.py, tests/plugins/test_tv1channel.py
=> plugins.TV1Channel: Fixed new livestream iframe

src/streamlink/plugins/lrt.py, tests/plugins/test_lrt.py
=> plugins.lrt: fixed livestreams

docs/plugin_matrix.rst, src/streamlink/plugins/clubbingtv.py, tests/plugins/test_clubbingtv.py
https://github.com/streamlink/streamlink/issues/2468
=> plugins.clubbingtv: new plugin for Clubbing TV website

docs/plugin_matrix.rst, script/makeinstaller.sh, setup.py, src/streamlink/plugins/oneplusone.py, src/streamlink/plugins/ovvatv.py, tests/plugins/test_oneplusone.py
plugin was broken due to changes on the site (urls and some data).  For example:
https://1plus1.video/tvguide/1plus1/online
Though it is geo restricted, but working via proxy
=> plugins.ovvatv: fix site changes

src/streamlink/plugins/wwenetwork.py
The config for the episode move from being embedded in the page page to an API call. 
Fixes #2585
=> plugins.wwenetwork: update for small page/api change

src/streamlink/plugins/youtube.py, tests/plugins/test_youtube.py
=> plugins.youtube: fixed reason msg, updated _url_re

docs/plugin_matrix.rst, src/streamlink/plugins/nownews.py, tests/plugins/test_nownews.py
Adds support for news.now.com. 
Fixes #2592
=> plugins.nownews: added support for the HK news site news.now.com

src/streamlink/plugins/bbciplayer.py, tests/plugins/test_bbciplayer.py
=> plugins.bbciplayer: fixes issue with nonce extraction/HD channels

src/streamlink/plugins/cinergroup.py
Added the https://www.haberturk.com/tv/canliyayin link to cover #2390
=> plugins.cinergroup: #2390 fix

src/streamlink/plugins/zattoo.py, tests/plugins/test_zattoo.py
closes https://github.com/streamlink/streamlink/issues/2623
=> plugins.zattoo: _url_re update for some new urls

src/streamlink/plugins/itvplayer.py
The ITV1 and ITV4 HLS streams are protected by DRM, but the RTMP streams are still available. 
Fixes #2555
=> plugins.itvplayer: Use flash streams for ITV1/ITV4

docs/plugin_matrix.rst, src/streamlink/plugins/viutv.py, tests/plugins/test_viutv.py
=> plugins.viutv: support for the viu.tv live stream

src/streamlink/plugins/bloomberg.py
There was a bug where the Australian stream could be used instead of the US stream when requesting the US page.  
Also fixes #2476
=> plugins.bloomberg: fix issue where the incorrect playlist could be used

docs/plugin_matrix.rst, src/streamlink/plugins/twitcasting.py, tests/plugins/test_twitcasting.py
Add support for https://twitcasting.tv
=> plugins.twitcasting: new plugin for TwitCasting.tv

src/streamlink/plugins/twitch.py
Since it should be pretty clear now that #2680 won't get fixed any time soon on Twitch's end or that it's probably even an intentional change (which "accidentally gets fixed" from time to time), we have to make a decision now.
As said in #2680, we don't really want to use Twitch's own client-id in Streamlink, but if we want to fix this issue, we don't have any other choice.
Twitch's developer ToS can be read here:
https://www.twitch.tv/p/legal/developer-agreement/
----
The changes of this PR make all private API calls use Twitch's own client-id and also remove authorization data from these API calls, since OAuth tokens are tied to the client-id which they have been granted from and take precedence when set. All other API calls are still using Streamlink's own client-id.
This means that …
=> plugins.twitch: fix API issue - 410 gone error

src/streamlink/plugins/twitch.py, tests/plugins/test_twitch.py
Fixes the issues mentioned in #2722
Please don't squash the commits when merging.
=> plugins.twitch: fix disable reruns

src/streamlink/plugins/bilibili.py
closes https://github.com/streamlink/streamlink/issues/2676
closes https://github.com/streamlink/streamlink/issues/2712
=> plugins.bilibili: fix Livestreams with status 1 (set Referer)

src/streamlink/plugins/nhkworld.py
=> plugins.nhkworld: the site migrates from xml to json stream data

docs/thirdparty.rst
Hello, reddit user [abbidabbi](https://www.reddit.com/user/abbidabbi/) was kind enough to reach out and recommend I put my program on your list of third party programs. So here I am! 
I'm not too experienced with .rst files so please let me know of any improvements I can make.
As listed in the file, the project URL is: https://git.sr.ht/~krathalan/wtwitch
=> Add wtwitch to list of thirdparty programs

docs/issues.rst
and add link to --player-args parameter
See #2769
=> docs: fix MPV parameters on common issues page

src/streamlink/plugins/twitch.py, tests/plugins/test_twitch.py
and improve rerun check
Fixes #2779 
Please see https://github.com/streamlink/streamlink/issues/2779#issuecomment-579130649 first.
=> plugins.twitch: fix rerun validation schema

src/streamlink/plugins/filmon.py
closes https://github.com/streamlink/streamlink/issues/2775
=> plugins.filmon: retry for 50X errors

src/streamlink/plugins/piczel.py
Fix for: https://github.com/streamlink/streamlink/issues/2767
- Fix STREAMS_URL
- Fix HLS_URL
- Remove RTMP support
- Fix HLS support
closes https://github.com/streamlink/streamlink/issues/2767
=> plugins.piczel fix

.travis.yml
see https://travis-ci.org/streamlink/streamlink/jobs/660210770#L3194
=> travis-ci: don't run doctr on pull requests

docs/plugin_matrix.rst, src/streamlink/plugins/wasd.py, tests/plugins/test_wasd.py
=> plugins.wasd: new plugin for WASD.TV

src/streamlink/plugins/app17.py
=> plugins.app17: fix for new layout

src/streamlink/plugins/twitch.py
closes https://github.com/streamlink/streamlink/issues/2752
=> plugins.twitch: Fixed clips

docs/plugin_matrix.rst, src/streamlink/plugins/rotana.py, tests/plugins/test_rotana.py
https://en.wikipedia.org/wiki/Rotana_Records
```$ streamlink https://rotana.net/live/
[cli][info] Found matching plugin rotana for URL https://rotana.net/live/
[cli][info] Available streams: 1080p (worst, best)
```
closes https://github.com/streamlink/streamlink/issues/2808
=> plugins.rotana: new plugin for rotana.net

docs/_themes/sphinx_rtd_theme_violet/static/css/theme.css, docs/donate.rst, docs/index.rst, docs/install.rst
I don't think we need to (temporarily) include the old bintray uploads here.
=> docs: fix and rewrite various sections and pages

src/streamlink/plugins/youtube.py
Modified the configuration schema because Youtube API changed.
It works.
I kept a lot of the plugin code and got rid of the old useless code.
```adp_audio``` may not be accurate and ```adp_video``` is incomplete.
I had a look at #2822. @fgietzen are you sure ffmpeg is installed on your system ?
I'm not sure who is in charge of this module. Maybe @beardypig ?
=> Youtube Plugin Fix

src/streamlink/plugins/abematv.py
https://abema.tv/now-on-air/news-global
```
$ streamlink https://abema.tv/now-on-air/news-global worst
[cli][info] Found matching plugin abematv for URL https://abema.tv/now-on-air/news-global
[cli][info] Available streams: 180p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 180p (hls)
```
closes https://github.com/streamlink/streamlink/issues/2443
=> plugins.abema: support for Abema overseas version

src/streamlink/plugins/zattoo.py, tests/plugins/test_zattoo.py
closes https://github.com/streamlink/streamlink/issues/2725
closes https://github.com/streamlink/streamlink/issues/2885
closes https://github.com/streamlink/streamlink/issues/2886
=> plugins.zattoo: fix app token and new recording URL

docs/plugin_matrix.rst, src/streamlink/plugins/zeenews.py, tests/plugins/test_zeenews.py
`streamlink https://zeenews.india.com/live-tv best`
https://en.wikipedia.org/wiki/Zee_News
closes https://github.com/streamlink/streamlink/issues/2566
=> plugins.zeenews: new plugin for https://zeenews.india.com/live-tv

docs/plugin_matrix.rst, src/streamlink/plugins/viasat.py, tests/plugins/test_viasat.py
closes https://github.com/streamlink/streamlink/issues/2900
=> plugins.viasat: remove play.nova.bg domain

src/streamlink/plugins/filmon.py
closes https://github.com/streamlink/streamlink/issues/2948
=> plugins.filmon: use /tv/ url and raise PluginError for invalid channels

src/streamlink/plugins/ruv.py
=> flake8: E741 ambiguous variable name

src/streamlink/plugins/app17.py
=> plugins.app17: update API

docs/install.rst
- https://github.com/streamlink/streamlink/pull/3003#discussion_r434312282
- https://github.com/streamlink/streamlink/pull/3003#discussion_r434313068
=> docs/install: fix Windows package manager

src/streamlink/plugins/foxtr.py
=> plugins.foxtr: fix playervars_re

src/streamlink/plugins/huya.py
- fixes #3001
- update _hls_schema
=> plugins.huya: fix _hls_re

docs/plugin_matrix.rst, src/streamlink/plugins/btv.py, tests/plugins/test_btv.py
- Remove unnecessary login code
- Fix plugin URLs and plugin test URLs
- Update plugin_matrix.rst URL and description
closes #2899
=> plugins.btv: remove login and fix API URL

src/streamlink/plugins/bigo.py, tests/plugins/test_bigo.py
=> plugins.bigo: fix bigo

docs/plugin_matrix.rst, src/streamlink/plugins/n13tv.py, tests/plugins/test_n13tv.py
Sorry for the noise in creating a new PR...
Closes #2996
See plugin removal #3000 (after this gets merged)
See also: #3009 (closed PR)
I hope this addresses the previous code reviews.  Thanks.
=> plugins.n13tv: new plugin - replaces plugins.reshet

src/streamlink_cli/main.py
=> cli.main: fix msecs format in logging output

src/streamlink/plugins/youtube.py
Revert 'isLiveContent' from https://github.com/streamlink/streamlink/pull/2858
Added 'signatureCipher' for protected videos.
closes https://github.com/streamlink/streamlink/issues/3021
=> plugins.youtube: Fix isLive and signatureCipher

src/streamlink/plugins/nicolive.py
- fix wss api url format issue
closes #3028
=> Plugin.nicolive: resolve new api format

src/streamlink/plugins/facebook.py
closes https://github.com/streamlink/streamlink/issues/2992
closes https://github.com/streamlink/streamlink/pull/3014
=> plugins.facebook: use meta og:video:url and added basic title support

src/streamlink/plugins/ceskatelevize.py
=> plugins.ceskatelevize: add new api for some links

src/streamlink/plugins/picarto.py, tests/plugins/test_picarto.py
closes https://github.com/streamlink/streamlink/issues/3042
=> plugins.picarto: fixed vod url detection

src/streamlink/plugins/adultswim.py, tests/plugins/test_adultswim.py
Fixes https://github.com/streamlink/streamlink/issues/2218
=> plugins.adultswim: fix/rewrite

.github/workflows/main.yml
Solves the issue mentioned here:
https://github.com/streamlink/streamlink/pull/3012#issuecomment-643585918
=> ci: run scheduled tests, ignore coverage report

src/streamlink/plugins/tv8.py
API
https://static.personamedia.tv/player/config/tv8.json
```json
{
"servers": {
"manifest": "https://tv8.personamedia.tv/tv8",
"hlsmanifest": "https://tv8.personamedia.tv/tv8hls?fmt=hls",
"api": "https://service.personamedia.tv/"
},
}
```
closes https://github.com/streamlink/streamlink/issues/3079
=> plugins.tv8: fix plugin with new api

docs/thirdparty.rst
Add [OBS-Streamlink](https://github.com/dd-center/obs-streamlink) into thirdparty.rst
=> Add OBS-Streamlink into thirdparty.rst

docs/players.rst
VLC 3 has been released for a while now.
=> docs: update reference to minimum VLC version

docs/plugin_matrix.rst
=> docs: update turkuvaz plugin matrix entry

docs/plugin_matrix.rst, src/streamlink/plugins/drdk.py, tests/plugins/test_drdk.py
New PR to fix previous screw up... (previously #3090)
I was initially looking to fix and close issue #2323, but since that was opened, the live channels have stopped working too. This PR fixes live channels again, but not the VoD access, so it does not close that issue. I will hopefully return to this at some point and get the VoD access working as well.
=> plugins.drdk: fix/rewrite

src/streamlink/plugins/crunchyroll.py
Updated the auth logic a bit, re-authenticating with the auth token no longer returns an auth token. If the saved token no longer works then it will try to authenticate with the username and password if they are set. 
I updated the old logging calls too.
fixes #3148
=> plugins.crunchyroll: update auth logic

src/streamlink/plugins/tvplayer.py, tests/plugins/test_tvplayer.py
https://github.com/streamlink/streamlink/issues/3145#issuecomment-689650652
=> plugins.tvplayer: update regex and tests for /uk/ URLs

docs/plugin_matrix.rst, src/streamlink/plugins/dogus.py, tests/plugins/test_dogus.py
=> plugins.dogus: add startv URL

src/streamlink/plugins/twitch.py, tests/plugins/test_twitch.py
- Removes the custom parameters and properties from the parser and adds
the "prefetch" field to the namedtuple Segment.
- Filters out prefetch segments in the worker's process_sequences method
- Replaces the playlist_reloads counter with a playlist_sequence == -1
check, which is sufficient for checking the beginning of the stream.
- Adds had_content property to worker, which checks for segments which
are not ads until the first segment was found.
- Refactors the info log messages and fixes the
"This is not a low latency stream" message when preroll ads exist.
- Cleans up tests
- Adds more tests for certain low-latency and disable-ads conditions.
=> plugins.twitch: refactor worker, parser and tests

docs/install.rst
easy_install removal:
https://github.com/streamlink/streamlink/issues/2896#issuecomment-623272899
Commits can be squashed if you want
=> docs: remove easy_install and clean up install page

src/streamlink/plugins/tv360.py
=> plugins.tv360: fix HLS URL regex and plugin

src/streamlink/plugins/atresplayer.py, src/streamlink/plugins/brightcove.py, src/streamlink/plugins/btsports.py, src/streamlink/plugins/earthcam.py, src/streamlink/plugins/galatasaraytv.py, src/streamlink/plugins/googledrive.py, src/streamlink/plugins/ine.py, src/streamlink/plugins/itvplayer.py, src/streamlink/plugins/kugou.py, src/streamlink/plugins/liveme.py, src/streamlink/plugins/mrtmk.py, src/streamlink/plugins/nownews.py, src/streamlink/plugins/powerapp.py, src/streamlink/plugins/streamingvideoprovider.py, src/streamlink/plugins/theplatform.py, src/streamlink/plugins/trtspor.py, src/streamlink/plugins/tv360.py, src/streamlink/plugins/tvplayer.py, src/streamlink/plugins/wwenetwork.py
As identified in: https://github.com/streamlink/streamlink/issues/3191#issue-705642714
=> plugins: fix unescaped literal dots in url_re entries

docs/plugin_matrix.rst, src/streamlink/plugins/svtplay.py, tests/plugins/test_svtplay.py
Tested under both Py2 and Py3 against supported sites within the plugin.
There's no necessity for an account, but streams are geo-IP restricted to Sweden.
closes #3133
=> plugins.svtplay: rewrite/fix

src/streamlink/plugins/yupptv.py, tests/plugins/test_yupptv.py
- Remove site login code and device logout code
- Add credentials caching/purging code and command line options
- Fix class name in plugin test, update tests to loop over list
- Minor update to negative test function name
Fix for #3094. Verified as working by one user: #3094 (comment)
closes #3094
=> plugins.yupptv: fix/minor rewrite

docs/plugin_matrix.rst, src/streamlink/plugins/wasd.py, tests/plugins/test_wasd.py
- fixed _url_re
- use api v2 for livestreams
- removed VOD support
closes https://github.com/streamlink/streamlink/issues/3105
=> plugins.wasd: fixed plugin

tests/streams/test_hls_filtered.py
- Refactor test setup and properly tear down threads
- Re-order tests
- Change mocked request URLs to temporarily work around bleeding threads
from previously run HLSStream tests which are sometimes still making
requests on the same URLs and causing the mocked playlist URL to
incorrectly advance one call and breaking the current stream worker
Resolves #3187
See https://github.com/streamlink/streamlink/pull/3187#discussion_r492716895
As mentioned in the linked comment, test_hls.py and test_twitch.py need to be fixed at some point, so that they gracefully tear down their spawned HLSStream threads, so that the same mocked request URLs don't get queried in tests which are run (directly) afterwards. Using unique mocked request URLs in each test would make this extra safe.
----
All tests …
=> stream.hls_filtered: fix tests

docs/plugin_matrix.rst, src/streamlink/plugins/mico.py, tests/plugins/test_mico.py
=> plugins.mico: new plugin for http://www.micous.com/
